### ISSUE TITLE
Record user_id & timestamp of course material upload & last course material edit

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10005]
**What problem are you trying to solve with Submitty**
We have no history of the date and author of course material uploads & edits

**Describe the way you'd like to solve this problem**
Let's add 4 new columns to the course database course_materials table a few extra columns....

uploaded_by - character varying - foreign key to users table user_id
upload_date - timestamp with timezone

last_edit_by - character varying - foreign key to users table user_id
last_edit_date - timestamp with timezone

The migration to add this information should set all of these columns to be null for existing courses.  

When a new course material is uploaded, the last_edit columns are NULL.
When a course material is edited, we overwrite any data that might be in the last_edit_by columns.  (We don't store the full history of edits to the course material, only the last edit.)

**Comment by anishsaraogi** [comment]
Hi Barbara,

I have been looking into your software and loved the idea. I was also thinking about being one of the contributor in GSOC in your Organization. I would love to contribute to this issue as a starting point.

Regards,
Anish

**Comment by anishsaraogi** [comment]
Hi Barbara,

I just looked at your past comments and realized that we should create a PR instead of asking to be assigned. I'll start working on this issue.

**Comment by bmcutler** [comment]
@dhruvgupta0503 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
