### ISSUE TITLE
User resizing markdown text area 

### ISSUE THREAD

**Issue by Nicc041** [Submitty/Submitty#10008]
**Describe the bug**
Markdown textboxes that can be resized by the user can be expanded as much or as little as possible. I assumed it's supposed to stay fixed with auto resizing or the user is only suppose to be able to resize vertically.

**To Reproduce**
Sign in as instructor, go to sql toolbox or course setting, find a textbox that you can resize.

**Configuration**
 - OS: [e.g. Windows, Linux, ...]
 - Browser [e.g. Chrome, Safari]

**Screenshots**
watch video to see the bug
https://github.com/Submitty/Submitty/assets/143554135/c8e5154c-dbe6-466e-8ab6-bb30b5a45317

**Comment by nithinkatta** [comment]
I would like to slove this issue
please assign me

**Comment by bmcutler** [comment]
@nithinkatta 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact

**Comment by dhruvgupta0503** [comment]
hey i want to work on this issue

**Comment by Nicc041** [comment]
May want to refer to PR #10007, so the textboxes are the same.

**Comment by vansasuu** [comment]
PR #10007, was merged with the same issue that occurs here
Submitty Vagrant has many more of these toolboxes and checkboxes which resizes identically. 
Global code of the textboxes needs to be replaced
