### ISSUE TITLE
Download all files button not working

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#10001]
**Describe the bug**
When clicking the download all files button on the submission page, a new tab opens up with a pop up message that says "You do not have access to that page". I am able to download each file individual, however. 

**Expected behavior**
It should let me download all of my submitted files at once.

**To Reproduce**
This was on production so unsure of exact steps right now. The conditions are a team gradeable with the multiple parts option (ability to submit multiple languages). I also submitted multiple files.

**Configuration**
 - OS: Linux
 - Browser: Brave

**Comment by Cibiyanna26** [comment]
will you assign this issue to me
