### ISSUE TITLE
Browser crashes/hang if submission count out-of-sync with database

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1001]
If we manually make a new submission (e.g., copy the directory "1" with submitted files to "2"), then log in as that user and attempt to make an additional submission, the page hangs.  

This is presumably because the database only knows about version 1.

When the fake directory is deleted, then things return to normal.  [ Well, you have to kill and restart the browser. ]

It shouldn't hang/crash.  We should either get an error/warning message about the problem, or better yet the system should heal itself and accept the new files as version "3".

**Comment by MasterOdin** [comment]
Is this a normal action that an instructor would take for a course? What would they be hoping to accomplish? How often would we be expecting people to be doing this?

**Comment by bmcutler** [comment]
We were attempting to quickly test having >1 submission & active version.

No, it's not a normal use case.  But it might happen if files are being manually placed/uploaded (we discourage this).  Or if the database is restored after a problem, but the files weren't affected.

**Comment by jbarthelmess** [comment]
I added a warning message for this in the summary_page_edits branch (just the error message, not self healing).

**Comment by MarisaPLee** [comment]
With the new ways for instructors to upload files for a student, it was determined that this should no longer be an issue.
