### ISSUE TITLE
Alert message for Late Days & Daylight Savings Time

### ISSUE THREAD

**Issue by 04vmatsibekker** [Submitty/Submitty#10014]
**Describe the bug**

An assignment is due the day before daylight savings in March, and the student takes a late day. Daylight savings passes and the clock moves forward an hour, the student will still have 24 hours to submit the assignment so the student can submit the assignment technically "two" days late if they submit before 1 am on the second day, and in this scenario, only one late day will be deducted.

Opposite of that in November after day light savings passes, a student would only have until 11 pm the next day to submit the assignment for 1 late day.

**Expected behavior**

A banner should be displayed to let students know the actual amount of time they are allotted on the assignment for late days.

**Comment by wdturner** [comment]
I just ran into this. I give 2 late days to submit "Status Updates." A student submitted on Sunday 11/5 at 23:56. The assignment was shown as 2 days late in some places (submission version selection), but as three days in, for example, the "Late Day Usage" report on the grading screen. It was considered too many days late and assigned a 0 when runnning Rainbow Grades.

**Comment by bmcutler** [comment]
@wdturner 
While I agree it that this offers imperfect useability, the computation of late days is already really complicated, with huge and expensive database queries that are already a burden on the performance of every TA grading related page.  In the short term, we are going to stick with the current math performed by SQL, where 'late day's are strictly 24 hours intervals from the due date.  We can add cautions to instructors and students when deadlines fall around time changes, but we don't want to add extra complexity to the SQL queries to handle these situations.
Sorry :(
