### ISSUE TITLE
Remove Customize Website Theme

### ISSUE THREAD

**Issue by RitaLei123** [Submitty/Submitty#10013]
**What problem are you trying to solve with Submitty**

Remove the top bar, left sidebar, right sidebar, bottom bar panel because it is buggy and no one uses it anymore.

**Describe the way you'd like to solve this problem**

Remove the features and leave the custom style and sidebar links panels.

**Describe any potential alternatives you'd tried to solve the problem**

Adjust the tables and find all the areas that applied these feature. This might be a global feature on Submitty because it applies to all the webpages.
 
**Additional context**

<img width="459" alt="image" src="https://github.com/Submitty/Submitty/assets/117528498/0a8653a2-27b4-4e01-9711-4fa726c389bd">

**Path to Issue:**
Instructor --> Sample --> Course Setting --> Customize Website Theme

**What it currently does:**
Top Bar --> Works like the Left Sidebar 
Bottom Bar --> Works like the Right Sidebar

**Comment by sumanbalayar08** [comment]
I am interested in solving this issue. Can you assign me this issue.
