### ISSUE TITLE
Store grader / grade time per component instead of per gradeable

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1004]
At the moment, we only store the grader at a per gradeable level, but it'd be nice to store this at a per component level. We also want to start storing a timestamp for each gradeable data item.

Primarily, we'll add this only for labs, tests, and then finally for rubrics.

The initial work for this would be:
* Move gc_grader_id from gradeable_data to gradeable_component_data (change prefix to gcd_)
* Add gcd_grade_time which will be timestamp to gradeable_component_data
* Add properties to GradeableComponent model that stores these two new DB fields
* Hook up interfaces to use these fields when saving to the DB

Grading Interfaces Done:
- [x] Lab (@jbarthelmess assigned for this)
- [x] Numeric/Text
- [ ] Rubric

**Comment by jbarthelmess** [comment]
First part should be done, pending pull request goes through
