### ISSUE TITLE
Editing course material page is buggy

### ISSUE THREAD

**Issue by VVVITH** [Submitty/Submitty#10058]
**Describe the bug**
When instructor editing a course metarial. The page able to scroll in the background behind/around the modal. It makes hard to make changes on course material especially editing the material release date. It's hard to get the 'now' button at the bottom of the calendar.

**Expected behavior**
The background should not be able to scroll when using the editing page. All the buttons on the calendar should be easy to access.

**To Reproduce**
1. Log in as an instructor
2. Go to course material page
3. Choose a course material, click edit
4. Try to make changes on the release date.
5. See error

**Configuration**
 - OS: [e.g. Windows, Linux, ...]
 - Browser [e.g. Chrome, Safari]

**Screenshots**

https://github.com/Submitty/Submitty/assets/92846547/70598a31-d45f-4720-bb44-5933c1e8dbd4

**Additional context**
Please not only fix the scroll background, but also check if the scroll of the editing page works good enough to make the calendar easily access.

**Comment by 07-Atharv** [comment]
Can i take up these issue?

**Comment by 2001sahil** [comment]
can i work on this issue???

**Comment by sahil-ansari01** [comment]
I'm working on the issue assign me for it !!
![Screenshot from 2023-12-14 20-21-33](https://github.com/Submitty/Submitty/assets/108484457/907565fa-7ccd-41de-8fdd-b59a6ad6209f)

**Comment by jatinxkirito** [comment]
@VVVITH I think it might be working now

https://github.com/Submitty/Submitty/assets/99955741/c54aed0e-35c8-4478-93bf-6fc4ae5fcc7a

**Comment by bmcutler** [comment]
Hi @07-Atharv @2001sahil  @sahil-ansari01 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
