### ISSUE TITLE
TA grading progress bar incorrectly shows 100%

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10050]
**Describe the bug**
I opened the grading interface for a peer team gradeable, for which I have done no grading, and the TA grading progress bar indicates that 100% of the grading is complete.

This bar:
<img width="533" alt="image" src="https://github.com/Submitty/Submitty/assets/16820599/0f57faa5-76c9-44cb-a32e-e3be5b9f4f7a">

**Expected behavior**
The progress bar should indicate the percentage of the grading I have been assigned to do which has been completed.

**Comment by manish2022-creator** [comment]
I am going to solve this is it still opened?

**Comment by bmcutler** [comment]
Hi @manish2022-creator 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact

**Comment by thegame615** [comment]
closed by PR [#10272](https://github.com/Submitty/Submitty/pull/10272)
