### ISSUE TITLE
TA grading w/ Peer grading - incorrect % completed

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10061]
**Describe the bug**

I have a gradeable with no autograding, with manual/TA grading and peer grading.
2 components of the rubric are peer grading, two components of the rubric are standard TA/instructor.

Grading has been completed.  All the students filled out their peer grades (every student submission has many peer grades).  All of the TA/instructor marks are completed.

But the TA grading status bar shows:
<img width="372" alt="Screenshot 2023-12-12 at 11 22 07 PM" src="https://github.com/Submitty/Submitty/assets/5871417/dbc284d2-c75c-4c85-a693-6daac50175b9">

and the gradeables page shows:
<img width="177" alt="Screenshot 2023-12-12 at 11 22 29 PM" src="https://github.com/Submitty/Submitty/assets/5871417/00b7d449-f481-4bd7-920a-8a8e7f53e129">

the grading stats page correctly shows:
<img width="185" alt="Screenshot 2023-12-12 at 11 23 11 PM" src="https://github.com/Submitty/Submitty/assets/5871417/51d65cc1-e993-4947-9c12-edfa82aa2103">

Note that if I ungrade one component for one student, my grading complete percent bar drops from 50% to 48%.  

If as instructor I add my own scores to peer grading components (this is not expected, but I have the option to add my own scores in for averaging -- for example if one student received too few responses from the peers), even then the grading progress bar is still stuck at 50% exactly.  Instructor scores in peer grading do not change the completion %.

**Expected behavior**
The grading status progress bar should be at 100% in the example described above.

And in general, the grading status progress bar should show how many of the components that are assigned to the current user are complete.  (As instructor/TA we are only expected to complete the non-peer components.

**Additional context**

NOTE:  We will eventually want a way to describe the % of peer grading completed.  That is, the instructor probably wants to hold off on releasing the grade results until a target percentage of the peer grading has been completed.  And the instructor will want to identify if any students have zero peer grades for one or more components -- because this will negatively impact and/or block them from receiving their grades.  Please consider how to address this -- perhaps by adding more data to the grading stats page.

**Comment by sahilsuman933** [comment]
Duplicate issue #10050 

// @bmcutler

**Comment by bmcutler** [comment]
@sahilsuman933 
This is not a duplicate issue.
#10050 is for peer grading view which incorrectly shows grading is complete when it is actually incomplete.
This issue is for the instructor/TA grading view which incorrectly shows grading is incomplete when it is actually complete.

**Comment by anmolchhabra21** [comment]
Hi @bmcutler, can I start working on this issue?
