### ISSUE TITLE
Blockquotes have no visual indicator

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#10073]
**Describe the bug**

Markdown blockquotes have no padding/margin or borders to indicate that there is a blockquote

**Expected behavior**

Blockquotes should have some padding

> like this

**To Reproduce**
1. Insert a blockquote into Markdown text
2. Look at the preview

**Configuration**
 - OS: [e.g. Windows, Linux, ...] MacOS
 - Browser [e.g. Chrome, Safari] Chrome

**Screenshots**

![Screenshot 2023-12-14 at 10 31 10 AM](https://github.com/Submitty/Submitty/assets/13932583/85014f13-0400-499c-89ba-d1c47d7bfed5)

**Additional context**

Input text: 

```md
> of all time
```

**Comment by pankaj-2503** [comment]
May i work on this issue , it seems i can work on it to rectify the bugs

**Comment by bmcutler** [comment]
Hi @pankaj-2503 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact

**Comment by jatinxkirito** [comment]
@PythonCoderAS can you please share screenshot from the readme where exactly is the problem coming

**Comment by PythonCoderAS** [comment]
> @PythonCoderAS can you please share screenshot from the readme where exactly is the problem coming

The screenshot I sent earlier is the rendered output. In contrast, this is what GitHub outputs for the same Markdown:

<img width="96" alt="Screenshot 2024-01-03 at 2 42 50 PM" src="https://github.com/Submitty/Submitty/assets/13932583/14234767-5d23-4f86-95de-2f70d06a0779">

Notice how there's a gray bar on the left showing that the text given was a blockquote. In contrast, a blockquote renders identically to non-blockquoted text on Submitty.

**Comment by anukoolvikram** [comment]
Hii @PythonCoderAS. I am new to the open source contribution. Could you please guide me through, to resolve this issue?

**Comment by PythonCoderAS** [comment]
> Hii @PythonCoderAS. I am new to the open source contribution. Could you please guide me through, to resolve this issue?

You need to apply CSS styling to blockquote items. Something along the lines of https://jsfiddle.net/1qwtke4b/1/

```css
blockquote {
  border-left: 2px solid #aaa;
  padding-left: 0.5em;
  margin-left: 0;
}
```

I don't know where Submitty does styling, and you likely want the coloring different for the other themes.

**Comment by PythonCoderAS** [comment]
![Screenshot 2024-01-11 at 2 52 05 PM](https://github.com/Submitty/Submitty/assets/13932583/5ce49ca9-c617-40cb-aa79-2e0b545e3250)
