### ISSUE TITLE
Download output.csv from rainbow grades from webpage

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10078]
**What problem are you trying to solve with Submitty**
Instructors want to download the .csv of the grades from rainbow grades.
This file is located in /var/local/submitty/courses/SEMESTER/COURSE/rainbow_grades/output.csv
Currently they must use scp to download that file (and its not documented)

**Describe the way you'd like to solve this problem**
Let's add a blue "Download CSV of grades" button to get this file from the top of the "Gradebook" page.

We probably want to add a note on this page about when the grades were last updated (grab the timestamp that "generate grade summaries" was run.)

**Comment by TusharPuri10** [comment]
I can make adjustments to meet your preferences. Let me know if there are any specific changes you have in mind.

**Comment by rutuja-khaire** [comment]
I want to work on this issue please assign me this issue
