### ISSUE TITLE
Markdown posts have padding that non-markdown posts do not

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#10070]
**Describe the bug**

When making a post with Markdown enabled, even if no markdown is used, the resulting post has extra padding because by default the Markdown renderer will add in `<p>` tags for every paragraph. In contrast, when not using Markdown, the text is inserted as is, without `<p>` tags. This leads to an inconsistency in post padding.

Additionally, normal posts have spaces prepended to them at the beginning, but Markdown posts do not.

**Expected behavior**
 Both modes would make the post look the same

**To Reproduce**
1. Make a post with normal text
2. Edit post to use Markdown

**Configuration**
 - OS: [e.g. Windows, Linux, ...] MacOS
 - Browser [e.g. Chrome, Safari] Chrome

**Screenshots**

**Additional context**

Regular post:

```html
<span class="post_content">    Post text here 
</span>
```

Markdown:

```html
<span class="post_content">    <div class="markdown " style=""><p>Post text here</p>
</div>
</span>
```

**Comment by pankaj-2503** [comment]
Assign this issue to me i can solve this issue.

**Comment by bmcutler** [comment]
Hi @pankaj-2503 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
