### ISSUE TITLE
Provide Markdown previews locally

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#10071]
**What problem are you trying to solve with Submitty**

Currently, rendering Markdown requires making a server request. This seems pretty wasteful and could easily be done client side, especially since Submitty does not appear to support any "niche" extensions or document any common extensions like tables.

**Describe the way you'd like to solve this problem**
Use JS to render the markdown preview

**Describe any potential alternatives you'd tried to solve the problem**
Continue using serve r side rendering for the preview

**Additional context**

**Comment by cjreed121** [comment]
We currently do not have any Markdown render engine on our front end. This would involve adding a new Markdown engine on the front end. Adding one would take a decent amount of time and there might not be perfect consistency between the front end and back end rendering as well. We aim to provide exactly what is shown in the preview would be what is shown after the post completes.

While it is true that a whole network request per preview can be a lot, it might break our intended functionality and decrease maintainability. GitHub actually uses a network request for each Markdown preview which I'm assuming is for similar reasons.

For the reasons above, I'm closing this as something we don't plan to address.
