### ISSUE TITLE
Team Gradeables - team name length

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10074]
**Describe the bug**
Students can optionally specify a team name for their gradeable.
Currently we don't seem to have a limit on the length of the team name or on the characters that can be used for a team name.
If the team name is excessively lengthy, this impacts the rendering of the TA grading index page and makes it difficult for graders to do their work.  Also, if there are weird or un-renderable characters in the team name, the display is confusing.

NOTE: instructors can edit a team name from the grading index page.  So lengthy team names can be manually replaced one-at-at-time.  But this is temporary, students can re-edit the team name.

**How to fix it**

NOTE: At this time, let's not write a migration to change any existing team names.  

* Let's truncate long team names already in the database before displaying the TA grading index page.  About 30 characters should be sufficient.  If the name is longer than 30 characters let's add "..." (ellipses) to make clear its been truncated.

* On the page where the students specify their team name or edit their team name, let's add some text:
"Team names are limited to 30 characters"
And if a student tries to make a longer team name, they should get an error message and the new name should not save.
Let's make sure this applies to new teams, new team names, and editing names of existing teams.

* On the page where instructors can edit the name of a team, let's also cap the length of edits to team names to 30 characters.

* Let's also decide on a reasonable set of characters that can be used in team names:  letters, numbers, spaces, dash, underscore for sure.  Would be nice to include characters with accents also.  But is it necessary to have emojis?  This is unnecessary and outside the original purpose of team names - to help instructors in large classes where it is helpful to label big groups and facilitate efficient course management.

**Comment by Sreevardhan1729** [comment]
In the first point below the NOTE are you telling to truncate the long team names from the database itself or to truncate just for displaying it?

**Comment by Sreevardhan1729** [comment]
**Question:**

In the first point following the `NOTE`, are you suggesting truncating the original team names in the database or only truncating them for display purposes?

**Comment by RuchiKalkandha** [comment]
I would like to give this a try. Could you assign it to me.

**Comment by bmcutler** [comment]
Hi @RuchiKalkandha 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact

**Comment by bmcutler** [comment]
@Sreevardhan1729 
Any existing team names that are very long should not be truncated in the database (we will not write a migration to change any existing data in the database).  Existing team names that are very long are only truncated before being displayed to prevent the display from being negatively impacted.

**Comment by shubhankarsharma876** [comment]
@bmcutler I am skilled in JavaScript, React.js, Node.js, MySQL. And looking forward to contribute can you suggest me some issue to resolve.

**Comment by GO-viper7** [comment]
@bmcutler 
hey, should special characters be also excluded in the team name ? except dash and underscore which were mentioned in decription.

**Comment by MasterOdin** [comment]
I think fine to omit most special characters except for `-` and `_` for now, and just make it easy to expand the list as needed.
