### ISSUE TITLE
Remove "individual" from the URL in the hw grading interface

### ISSUE THREAD

**Issue by jbarthelmess** [Submitty/Submitty#1008]
Currently the RCS ID for the student being graded shows up in the url in the grading interface.  Looking ahead to supporting peer grading, this would undercut the goal of anonymity for the site. May want to port all variables being past to _POST instead of _GET.

**Comment by MasterOdin** [comment]
Moving from `$_GET` to `$_POST` wouldn't really solve anything as it's still super easy to figure out who's grading who. We would need to do something more involved like having some random ID per user that we use in the case of anonymous grading (stored in the DB).
