### ISSUE TITLE
Rainbow Grades Notes

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1010]
Rainbow Grades currently shows notes on individual reports but not on the course summary report. This is because notes get used for a variety of things and some notes are lengthy pieces of feedback that would make output.html very ugly. 

One possibility would be to add this information as hover notes. It would be nice if there was a way for the user to search through the contents though, and hovers may preclude this.

**Comment by holzbh** [comment]
It's been 5 years since this issue was created (and I may have typed it up while jointly brainstorming with @bmcutler ). I'm not sure what the intent was at this point -- but...

RainbowGrades `customization.json` supports a top level `note` array where each entry is a dictionary of `user` and `msg`. This is shown on the all-students `output.html` . Those don't show up on individual student HTML files, not sure which 'notes' did? But this issue either needs clarification or it should be closed.

**Comment by bmcutler** [comment]
closing in favor of more specific new issues.
