### ISSUE TITLE
Want to add dark mode feature to the website

### ISSUE THREAD

**Issue by dwivedishrey** [Submitty/Submitty#10104]
**What problem are you trying to solve with Submitty**

**Describe the way you'd like to solve this problem**

**Describe any potential alternatives you'd tried to solve the problem**

**Additional context**

**Comment by manish2022-creator** [comment]
Its nice idea as it improves customization for users but its already exists as if you havent installed software in your device you can check it out here --
https://submitty.org/student/account/theme
