### ISSUE TITLE
Peer Grading status buttons inconsistent

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10107]
**Describe the bug**
I'm a peer grader, I've been assigned to grade 2 students.
The assignment has 5 TA graded components and 1 peer graded component
Both students have submitted.
One of the students has been graded by the TA, the other has not.

This is my view:

<img width="598" alt="Screenshot 2024-01-15 at 7 06 31 PM" src="https://github.com/Submitty/Submitty/assets/5871417/2f7054c0-c97c-41be-9b75-e54c0f658f50">

I have done my peer grading, but why am I seeing the white status buttons for the TA graded components for the student who hasn't been graded yet?  
BTW, when I go into the UI for the TA and complete the grading, then the white buttons disappear

BTW: If I grade 4 of the 5 TA grading components then only 1 of the white TA status buttons is visible.
<img width="512" alt="Screenshot 2024-01-15 at 7 09 53 PM" src="https://github.com/Submitty/Submitty/assets/5871417/fb4c60c8-03f6-4993-bf97-0a5ba6374423">

**Comment by MrPhenomenal3110** [comment]
Could you please assign this issue to me ?

**Comment by arnavchhokra** [comment]
hi, can I be assigned this issue?

**Comment by Xiayucheng1212** [comment]
@bmcutler Hi, I am new to this project. Can you please give more details about how to reproduce this situation(like how to create a peer grader)?

**Comment by bmcutler** [comment]
HI @MrPhenomenal3110 @arnavchhokra @Xiayucheng1212 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
