### ISSUE TITLE
Allow setting a min/max value for components for rubric

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1011]
Right now, we only allow setting a singular limit for a component that clamps scores and then an implicit clamp at 0.

We either have a positive or negative clamp and gives us the following two ranges of values:
* [0, positive_value]
* [negative_value, 0]

We should allow that we can set both the min and max clamps, defaulting to 0 for both min and max values.

Not sure we would want to apply this for test grading or checkpoints. Thoughts @bmcutler?

**Comment by bmcutler** [comment]
Yes for test grading
No for checkpoints

Also, to throw a further wrench in here...  We've had requested use cases where it would be nice to allow a gradeable component (hw rubric item or test problem) that has a "regular" points maximum, that allows exceeding that max with extra credit points.  A test problem might be graded out of 10 points, but the instructor would like to allow students to earn a maximum of say 12 points for that problem.  That is "built-in" extra credit.  Yes, we can achieve this with an extra gradeable component, but that clutters the test data entry or homework rubric.

So perhaps we want 3 values for each component.  Max negative score, Max regular score, Max extra credit.  Design discussion needed.

**Comment by bmcutler** [comment]
replaced by #1290
