### ISSUE TITLE
add background color description for Rubric Grading 

### ISSUE THREAD

**Issue by ziesski** [Submitty/Submitty#10112]
Currently Submitty documentation page does not have description on what the teal background color stands for.
https://submitty.org/grader/rubric_grading/

If I am correct, the teal background color is a design decision, stands for full credit, so when the rubric starts from full credit and deducts points onwards, it is visually clear which cell is full credit to initially check. 

It would be nice if there is clear description of this design decision. (Some graders got confused as they thought teal color meant selected) 

<img width="409" alt="Screen Shot 2024-01-16 at 12 58 11 PM" src="https://github.com/Submitty/Submitty/assets/123261952/85ae6fd4-647e-4164-8472-15dd29e4356d">

**Comment by williamjallen** [comment]
The documentation is probably not the first place people are going to look when they are confused about the UI.  I think it would be better to add some sort of visual cue directly to the page for this.  Perhaps an info pill to the left of the mark value?

**Comment by Xiayucheng1212** [comment]
I agree with @williamjallen 's opinion, but I'm not sure why we need this teal color to highlight a full credit. The number and the description after that should show the meaning of the grade.

**Comment by kaushal-malpure** [comment]
@ziesski Can i work on this issue?

**Comment by Vermasushant144** [comment]
Hello sir I work on this issue under GSOC (24)

**Comment by ZheyuDeng** [comment]
Cloes issue #10112 as PR #10140 is merged.
