### ISSUE TITLE
Office Hours Queue Spacing Issue

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#10117]
**Describe the bug**
Every time the websocket server sends an update to a student client, a whitespace line gets added to the screen. The gap between "For more information" and "My Queue Status" is where it goes. This may become quite large as office hours goes on.
<img width="1204" alt="image" src="https://github.com/Submitty/Submitty/assets/55092742/d7effa19-5f6f-42e9-85fa-47db3ca066e7">

**Expected behavior**
There should not be any extra whitespace lines when the queue updates.

**To Reproduce**
1. Join the office hours queue as a student
2. Have another student join the office hours queue
3. As a grader/instructor help and finish helping the 2nd student
4. You will now notice extra whitespaces lines on the first student's page

**Configuration**
 - OS: Mac
 - Browser: Brave

**Screenshots**
Shown above

**Additional context**
The issue is likely that the returned content gets rendered with some <br> tags but they never get replaced or removed.

**Comment by Xiayucheng1212** [comment]
@cjreed121 Hi, I tried to reproduce this bug by following your steps, but the above blank didn't show up. Could please guide me through to reproduce it?

**Comment by fardin-developer** [comment]
Hey, Can I work on this.....

**Comment by AavanVadiwala** [comment]
pr #10256 fixes this issue
