### ISSUE TITLE
specify which ta grading panels are available to peer graders

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10114]
**What problem are you trying to solve with Submitty**
When a peer grader logs in to grade an assignment, they get the TA grading interface.
This interface is designed for TAs who do lots of grading, but it can be confusing for first time graders.

<img width="603" alt="Screenshot 2024-01-18 at 1 28 45 PM" src="https://github.com/Submitty/Submitty/assets/5871417/43ed2507-6bfd-453a-a900-664fb850af4f">

Why are the panels in this order:  autograding, rubric, files, solution notes, discussion?

The most common use case for peer grading is to look at the files tab and fill out the rubric tab.
The may never need the autograding, solution notes, and discussion tab (discussion tab only appears if the assignment has a form thread associated).

If they are just giving feedback on an in class presentation they may only need the rubric tab.

**Describe the way you'd like to solve this problem**
Let's allow the instructor to specify which tabs should be displayed to peer graders.

On the edit gradeable / grader assignment tab let's add a question a set of checkboxes underneath this question:

<img width="448" alt="Screenshot 2024-01-18 at 1 33 43 PM" src="https://github.com/Submitty/Submitty/assets/5871417/59d633d1-9252-450d-b8dc-351da4ddf5ba">

e.g., let's add:
"Which tabs should be visible to peer graders?" 
- [ ] autograding
- [ ] rubric
- [ ] files
- [ ] solution/notes
(and if relevant to this gradeable - [ ] discussion)
All should be checked by default but can be unselected

**Comment by AnuRage-git** [comment]
Greetings @bmcutler I am new to submitty and I'd like to work on this issue.
Could you guide me on what changes are expected in the client and what part of the code I'd be working on?

**Comment by GO-viper7** [comment]
It was truly a challenging issue
Enjoyed solving it 😊
You may go through the PR @bmcutler 
Thank you.
