### ISSUE TITLE
Forum reply button should be disabled when text area is empty

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10126]
**Describe the bug**
The "submit reply to all" button is enabled and clickable when no content has been entered in the forum text box.

**Expected behavior**
The submit button should be disabled when no content has been entered.

**Screenshots**
![image](https://github.com/Submitty/Submitty/assets/16820599/226958de-937f-490c-b6e1-e52eec71b0ca)

**Comment by NewtonFernandis** [comment]
Hey @williamjallen, I will take this up. Could you please assign this to me?

**Comment by jeffreyC4** [comment]
I think I can handle this issue by adding event listener to text-area.

**Comment by byteWizard07** [comment]
Hi @williamjallen, I would like to work on this issue. please assign it to me.

**Comment by Abhishek3777** [comment]
Hi @williamjallen , I can work on this issue.

**Comment by shivanshusawan66** [comment]
Hi @williamjallen  I would like to work on this issue.
