### ISSUE TITLE
Autograding shows 0 in anonymous mode

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#10120]
**Describe the bug**
When anonymous mode is enabled, autograding shows 0/0 for all students although most students got non-zero scores. "Too many late days" is also not shown.
![image](https://github.com/Submitty/Submitty/assets/7108039/2088a2e3-e3cd-4c42-bd21-7d03b83f57d1)

It can be confirmed by switching the anonymous mode off. Then all autograder scores are shown properly:
![image](https://github.com/Submitty/Submitty/assets/7108039/667cc0e0-ea75-405d-ae95-fbf44cad0fcc)

**Expected behavior**
The real autograding score should be shown. "Too may late days" and other tags should be properly shown on the "Grade" button.

**To Reproduce**
1. Navigate to the grading interface, e.g., https://submitty.cs.rpi.edu/courses/s24/csci2600/gradeable/quiz1/grading/details
2. Enable anonymous mode and observe all autograded points shown as 0/0
3. Disable anonymous mode and notice how actual autograding scores are properly shown

**Configuration**
 - OS: Windows 11 Home Version 23H2 OS build 22631.3007 Experience Windows Feature Experience Pack 1000.22681.1000.0
 - Browser: Mozilla Firefox 121.0.1 (64-bit)

**Screenshots**
Provided above

**Additional context**
None

**Comment by KCony** [comment]
I don't mean to push, and if it is considered to be low priority I'd understand but I just wanted to check if there is any progress on this one, @bmcutler @NiaHeermance

**Comment by KCony** [comment]
Any updates on this bug?

**Comment by williamschen23** [comment]
The only thing that still needs to be fixed was too many late days, let me know if there's anything else that isn't consistent.
