### ISSUE TITLE
incorrect errors for generate_repos script when specified gradeable does not exist

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10137]
**Describe the bug**
We have bugs in the generate_repos script if improper arguments are provided.

Documentation is here:
https://submitty.org/instructor/assignment_preparation/managing_git

```
sudo /usr/local/submitty/bin/generate_repos.py <semester> <course_code> <project_name/gradeable_id>
```

Firstly, if you specify a gradeable_id that does exist but is not a vcs gradeable, it goes ahead and makes repositories.
The script should warn the instructor that this gradeable is not a vcs gradeable.
And then the script should stop and not make the repositories.

Secondly, if the specified `gradeable_id` doesn't exist, we get a warning, and the instructor is asked if they want to continue.
If they say yes, but the script continues and then fails with this error:
AttributeError: 'NoneType' object has no attribute 'eg_vcs_subdirectory'
which is confusing to the instructor. 

The warning needs to be more firm (it was too easy to say yes).
It should say "please make the gradeable before attempting to run this script.

However, we do have an option to make a gradeable that has repos that do not match the gradeable id.
This is intended for individual (non team) assignments that will share a repo over multiple gradeables.
In this case the instructor specifies the repo name that will be used in common for multiple gradeables:

<img width="781" alt="Screenshot 2024-01-29 at 10 05 03 AM" src="https://github.com/Submitty/Submitty/assets/5871417/cc03c9a8-b162-479d-9f22-2516e86e433b">

So if the gradeable_id doesn't exist, the script should check if any gradeable has the specified repo name specified as the the shared repository name (for one or more gradeables).  The script should only continue if that is true.  And there may be a bug here...  this error should not happen:
AttributeError: 'NoneType' object has no attribute 'eg_vcs_subdirectory'

**Comment by snehalchaudhari98** [comment]
Hi @bmcutler , this looks like an interesting issue, I'm interested in working on it. Could you please assign it to me?

**Comment by Xiayucheng1212** [comment]
Hello @bmcutler , I am looking at these three sub-issues and thinking that maybe this issue can be splitted into two smaller issues? The first one focuses on dealing with the "single gradeable repository" and the second deals with the "multiple gradeables". Please give me some suggestions, thank you!

**Comment by bmcutler** [comment]
HI @snehalchaudhari98 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
