### ISSUE TITLE
1) In doc webpage u can add a section for FAQ 2) in the side navigation u can collapse a menu if another navigator is clicked 

### ISSUE THREAD

**Issue by vr-varad** [Submitty/Submitty#10135]

**Comment by vr-varad** [comment]
@gonsie Can i work on it?

**Comment by gonsie** [comment]
I am not the person to ask. 

According to the [CONTRIBUTING.md](CONTRIBUTING.md) guide, I don't think you need to ask first. Just submit a pull request with your change.

**Comment by bmcutler** [comment]
Closing as this issue has no description and is incomplete and unclear
