### ISSUE TITLE
Discussion Forum - "Mark unread from here"

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10158]
**What problem are you trying to solve with Submitty**
When you click on a thread in Submitty, we make a record in the "viewed_responses" database table for that user, thread, and timestamp.
But if the user doesn't have time to view the entire (lengthy) thread of messages at that time, they might want to "mark the thread as unread, either entirely, or from a specific point, so they can come back later.

**Describe the way you'd like to solve this problem**
Let's add a button to the UI 
"Mark unread from here"
It should be subtle, possibly tucked-away feature, to avoid clutter.  
A white button or maybe in a three dot popout menu with this as an option.
Maybe we can combine a few other less-used forum features in a popout menu.

**Comment by williamjallen** [comment]
@jatinxkirito That looks like it might be an independent problem.  Please create a new issue detailing what you did to cause that to happen: https://github.com/Submitty/Submitty/issues/new
