### ISSUE TITLE
Label original author in forum replies

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10162]
**What problem are you trying to solve with Submitty**
When a student makes a post anonymously, it is currently impossible to determine if the same student is the author of a subsequent reply.  This can be confusing in some cases when follow-up questions are asked by multiple anonymous students.

**Describe the way you'd like to solve this problem**
This problem can be solved easily by adding a tag or other visual indicator which labels the student as the author of the original thread.

**Comment by Xiayucheng1212** [comment]
How about change the signature from "Anonymous" to "Original Poster"?

**Comment by bmcutler** [comment]
@MasterOdin 

We discussed this a bit in person and the Submitty and decided it is sufficient (for now) to only label the "OP" anonymous. It is unusual to have a lengthy anonymous back and forth with multiple anonymous users education forum where it is necessary to uniquely identify more than OP.

This is also related to "Live Lecture Chat" -- where we will need to worry about clearly labeling many anonymous users.
https://github.com/Submitty/Submitty/issues/7207
