### ISSUE TITLE
Issue while opening discussion forum

### ISSUE THREAD

**Issue by jatinxkirito** [Submitty/Submitty#10161]
I tried to create open discuss forum but instead it gives error
<img width="957" alt="Screenshot 2024-02-03 190130" src="https://github.com/Submitty/Submitty/assets/99955741/1579e3e4-2dd3-4040-9d7d-ea05085e59c3">

I traced back to source but couldn't find the issue
<img width="614" alt="Screenshot 2024-02-03 190619" src="https://github.com/Submitty/Submitty/assets/99955741/0638bbd6-61a0-4384-b489-110720081c97">

Can anyone please help

**Comment by jeffreyC4** [comment]
This may be an issue with the current state of your local VM. I would pull the most recent version of the app from the main branch, SSH into the VM, and run "submitty_install" to see if the issue persists. I had no issues with any of the accounts that had access to the forum.

**Comment by jatinxkirito** [comment]
> This may be an issue with the current state of your local VM. I would pull the most recent version of the app from the main branch, SSH into the VM, and run "submitty_install" to see if the issue persists. I had no issues with any of the accounts that had access to the forum.

@jeffreyC4  I checked but my fork is already up to date with the main branch. So that doesn't seem to be a issue

**Comment by jeffreyC4** [comment]
> > This may be an issue with the current state of your local VM. I would pull the most recent version of the app from the main branch, SSH into the VM, and run "submitty_install" to see if the issue persists. I had no issues with any of the accounts that had access to the forum.
> 
> @jeffreyC4 I checked but my fork is already up to date with the main branch. So that doesn't seem to be a issue. This wasn't a pre existing forum, I created a new one

The current function in the main branch is below, which doesn't match the image in the original issue post.  I would verify this matches on your end and run "submitty_install_site" to ensure changes are reflected on the VM. The method below handles the empty thread_id array case before the query call, which could be the issue?

``` PHP
public function getFirstPostForThreads(array $thread_ids): null|array {
        if (count($thread_ids) === 0) {
            return null;
        }
        $placeholders = $this->createParameterList(count($thread_ids));
        $this->course_db->query("SELECT * FROM posts WHERE parent_id = -1 AND thread_id IN {$placeholders}", $thread_ids);
        $return = [];
        foreach ($this->course_db->rows() as $row) {
            $return[$row['thread_id']] = $row;
        }
        return $return;
}
```

**Comment by jatinxkirito** [comment]
> > > This may be an issue with the current state of your local VM. I would pull the most recent version of the app from the main branch, SSH into the VM, and run "submitty_install" to see if the issue persists. I had no issues with any of the accounts that had access to the forum.
> > 
> > 
> > @jeffreyC4 I checked but my fork is already up to date with the main branch. So that doesn't seem to be a issue. This wasn't a pre existing forum, I created a new one
> 
> @jatinxkirito The current function in the main branch is below, which doesn't match the image in the original issue post. I would verify this matches on your end and run "submitty_install_site" to ensure changes are reflected on the VM. The method below handles the empty thread_id array case before the query call, which could be the issue?
> 
> ```
> public function getFirstPostForThreads(array $thread_ids): null|array {
>         if (count($thread_ids) === 0) {
>             return null;
>         }
>         $placeholders = $this->createParameterList(count($thread_ids));
>         $this->course_db->query("SELECT * FROM posts WHERE parent_id = -1 AND thread_id IN {$placeholders}", $thread_ids);
>         $return = [];
>         foreach ($this->course_db->rows() as $row) {
>             $return[$row['thread_id']] = $row;
>         }
>         return $return;
> }
> ```

@jeffreyC4 Thanks for the help
