### ISSUE TITLE
TA Interface Does Not Reflect Student Peer Grading Status

### ISSUE THREAD

**Issue by wuj18** [Submitty/Submitty#10166]
**Describe the bug**
In the current system, instructors can visually identify if a student has completed their assigned peer grading tasks, as these components are highlighted in purple. However, this functionality appears to be missing on the TA interface, where the status indicators for peer grading completion do not change regardless of a student's grading activity.

**Expected behavior**
The TA interface should reflect the peer grading status accurately, similar to the instructor's interface. Once a student has graded a peer component, the corresponding components should be highlighted to indicate completion. 

**To Reproduce**
1. Log in to a student account and grade a peer homework assignment.
2. Log in to the instructor account to observe that the graded components are highlighted in purple.
3. Log in to the TA interface and notice that all peer grading components remain unhighlighted.

**Configuration**
Windows Chrome

**Screenshots**

instructor's interface:
<img width="929" alt="f9d6b35a905fa68d74c8791b06e2ad3" src="https://github.com/Submitty/Submitty/assets/75406429/5e2a28ba-3cc0-485d-93c8-6147194d9653">

ta's interface:
<img width="929" alt="6704dd640adcd18b5367725c10200fc" src="https://github.com/Submitty/Submitty/assets/75406429/d064b7e0-4857-4395-9c4a-3859eab437a3">

**Additional context**

**Comment by snehalchaudhari98** [comment]
Hi @wuj18, I am interested in working on this issue. Can you assign this to me?

**Comment by HimanshuKhatarkar** [comment]
Hey @wuj18 I'd really like to work on this issue. Does it need to be **assigned** or I can Start by **myself**?

**Comment by wuj18** [comment]
Hey @HimanshuKhatarkar, I'm already working on this issue. Could you search for another one that hasn't been assigned yet? Appreciate it!

**Comment by bmcutler** [comment]
Hi @snehalchaudhari98  @HimanshuKhatarkar  

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
