### ISSUE TITLE
Search functionality for timezone in user profile

### ISSUE THREAD

**Issue by samhithaarani** [Submitty/Submitty#10186]
**What problem are you trying to solve with Submitty**
 in user profile , we have many timezones to select for, so it would be great if we have search functionality. 

**Describe the way you'd like to solve this problem**
simply,by adding an Event Listener to the dropdown,we can perform search of relavent inputs... 

![Time-Zone-Fix](https://github.com/Submitty/Submitty/assets/73035235/54f1115e-f995-4691-ad07-f543df3acc48)

**Comment by AdnanMehr8** [comment]
Hey @samhithaarani , I am interested in adding this feature. Assign me so I can start working on it.

**Comment by bmcutler** [comment]
Hi @AdnanMehr8 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact

**Comment by ishsarin** [comment]
Hi @samhithaarani , if this issue is open, I'd like to contribute.
Please assign me this issue.

**Comment by michaelkrar** [comment]
@samhithaarani  Reviewing this right now everything looks good but I do not understand how the commits in DatabaseQueries.php help to solve the issue or if it is a solution to another issue, as this looks like code that deals with Gradeable data rather than User data(correct me if I am wrong).

**Comment by omsai11** [comment]
Hi @samhithaarani added this feature kindly review the feature

**Comment by Aditya-Dhodapkar** [comment]
Hi @bmcutler , I have submitted a PR for this fix. How do I get someone to review it?

Thanks!
