### ISSUE TITLE
Not able to login. 

### ISSUE THREAD

**Issue by balkishaniaastha** [Submitty/Submitty#10195]
I have installed  submitty on Ubuntu server. When I am trying to login with default credentials in web ui. It is showing can not login. Can anyone help me???

![Screenshot from 2024-02-20 18-42-41](https://github.com/Submitty/Submitty/assets/139435633/2282fe36-be5f-4dd9-9ed7-889700d6a6d9)
![image](https://github.com/Submitty/Submitty/assets/139435633/09d887ef-9deb-4ffd-babc-039e294c8d07)

**Comment by cjreed121** [comment]
This is not a bug and is being addressed on Zulip
