### ISSUE TITLE
Specify a recommended format for titles of Pull Requests (and Issues?)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1019]
To ensure that the commit history is clear.

**Comment by MasterOdin** [comment]
Ideally, the PR name should be < 50 characters (including about leaving ~5 or so for github to attach the link when merging) and be a clear and concise explanation of what was changed where. It would then be what we would directly copy and paste into a changelog per release.

**Comment by bmcutler** [comment]
* Each PR should be addressing/closing an open issue (usually).
* The PR title should be useful (not just the issue#).
* Titles of PR, Issues, and commits should be <= 50 characters (usually).
* The issue# being closed should be in the PR message ("Closes issue#").
* The commit message should talk about WHAT changed, and WHY. Not HOW – how is the diff, and you don’t need to repeat it.
* Comments explaining the code should be *in* the code, rather than in the PR message or comments.
* Including screenshots in the issue or PR message is helpful for UI changes.
* The comments should explain a bit about the purpose/history/overview -- don't assume the reader knows it (or link to the issue that explains everything).
* Be explicit about what you want feedback on, or why you are asking for specific reviewers.

notes stolen from:
https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests
https://github.com/blog/1943-how-to-write-the-perfect-pull-request
https://github.com/thoughtbot/guides/tree/master/code-review

**Comment by bmcutler** [comment]
added http://submitty.org/developer/how_to_contribute
