### ISSUE TITLE
Dropdown Menu to Manually Set Month/Year in Calendar

### ISSUE THREAD

**Issue by arougey** [Submitty/Submitty#10242]
To prevent having to click the left or right arrows 12 times to change the year and 1-12 times to get to a different month, there could also be a dropdown menu with each month/year.

A solution would be to simply place two more dropdown menus to the left of the preexisting one that changes the viewing format for the year and month.

I can't think of any alternative solutions that would be more effective than a dropdown menu.

**Comment by Xiayucheng1212** [comment]
@arougey Hi, I am interested in working on this issue. What do you think about the range of the year shown in this dropdown menu? Like from 1000 to 9999 or 1900 to 2100?
