### ISSUE TITLE
Write documentation on submitty.org for Manual/TA Grading "Version Conflict"

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10254]
**What problem are you trying to solve with Submitty**
New TAs/Instructors don't know what "Version Conflict" means on the TA grading interface

**Describe the way you'd like to solve this problem**
Add documentation to submitty.org in the TA or grader section.
Possibly also add a ? link from live website to the documentation section.

**Comment by williamschen23** [comment]
closed in https://github.com/Submitty/submitty.github.io/pull/617
