### ISSUE TITLE
Calendar button that sets date to current day

### ISSUE THREAD

**Issue by arougey** [Submitty/Submitty#10265]
Now that there is/is going to be a way to quickly change the calendar dates, there should also be a way to quickly change the calendar date to the current day. 

In my mind, this would be a simple button somewhere on the upper navigation bar that simply has text that says "Today". 

An alternative could be an option within the dropdown menu, but I think this alternative is worse.

**Comment by PGPradhan** [comment]
To address this issue I would like to give me some suggestion.
1.   Replace the existing date handling code with a modern date library like **Luxon or date-fns.** These libraries provide robust date manipulation capabilities and can handle date formatting and parsing more effectively.
2.  Submitty is used in different regions. Therefore, it may face an issue of **Localization**. To encounter this issue we can implement libraries like Moment.js or Globalize.js that can help us format dates according to different locales.

**Comment by arougey** [comment]
Closed by #10267
