### ISSUE TITLE
New forum posts added by sockets should be highlighted as unread

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10319]
**Describe the bug**
When you are viewing a forum thread for the first time, all the posts within it are light blue (light blue = unread -- in light mode).  If a new post is added while you are on that thread, the websocket will add it as white post (white post = read -- in light mode).  This doesn't make sense to have the newest posts be read while the older posts are blue.

**Expected behavior**
All new posts should be unread.

**Related Note**
I've noted elsewhere (maybe not formally typed up as an issue) that the visualization of read vs unread posts in dark mode is unclear (or even buggy) since most users in dark mode aren't even aware that we have read vs. unread status in the forum.  This should be fixed.  The colors used for read vs unread mode should be adjusted so the difference is more obvious.

**Comment by DannyJiang1** [comment]
Hi! Can this issue be assigned to me? I would love to work on this.
