### ISSUE TITLE
integrate open-source forum/bulletin board 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1032]
for student questions & instructor/ta/peer answers
perhaps phpBB?

**Comment by MasterOdin** [comment]
Based off previous conversations, before anyone starting this, I'd like to see what is the features we want in our "ideal" system. What would the student see, how they would interact with it, etc.  How does it integrate with the rest of the system? Do we want to allow students to appear anonymously to each other (but the instructor would see who asked what questions)? What features does the instructor need? What would be the work flow for the instructor?

phpBB might have far more things than we need for Submitty so integrating it would not be good (as we might have a very custom build of it and then we cannot easily upgrade it in the future), but maybe we'll use all of the features.

**Comment by bmcutler** [comment]
initial implementation of forum complete
