### ISSUE TITLE
Remove 'status' variable from Polls

### ISSUE THREAD

**Issue by Kush-Raval** [Submitty/Submitty#10335]
**Describe the bug**

Right now there is a status column for polls that isn't used after https://github.com/Submitty/Submitty/pull/10184 is merged. 
The status variable is in files that aren't using it.

**Expected behavior**
The column should be dropped from public.polls 
Removed from relevant files:
polls_data.json
poll.php
course_data.py

**Comment by Kush-Raval** [comment]
This issue should be tackled approximately a month after #10184 is merged

**Comment by williamschen23** [comment]
closed by #10626
