### ISSUE TITLE
Wide view forum posts have white shadow in dark mode

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10345]
**Describe the bug**
When viewing discussion forum posts in the wide view in dark mode, a white gradient appears underneath each post.  

![image](https://github.com/Submitty/Submitty/assets/16820599/ae875ee3-0dad-4684-b15b-e02e9735e9ee)

**Expected behavior**
The white shadow should be eliminated in favor of a cleaner design.

**Comment by CCWizma99** [comment]
@williamjallen, Sorry for the first reference. I had made that to pull request to my own branch. I hope the pull request will solve the issue.

**Comment by CCWizma99** [comment]
Now it's done...
