### ISSUE TITLE
Upduck number wraps to next line on mobile if post is edited

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#10367]
**Describe the bug**

If the post was edited, it makes the line slightly too big, and forced the number of upducks to go onto the next line on a mobile device.

**Expected behavior**

They should all stay in one line.

**To Reproduce**
1. Find a post that was edited
2. Visit it

**Configuration**
 - OS: [e.g. Windows, Linux, ...] iOS
 - Browser [e.g. Chrome, Safari] Chrome

**Screenshots**

![IMG_1375](https://github.com/Submitty/Submitty/assets/13932583/70e3c1cd-2e31-4285-b7ee-031884a3460c)

**Additional context**

**Comment by CCWizma99** [comment]
What about a design like this? Now if description goes to the next line, Upduck will also go with it.

Light mode
![image](https://github.com/Submitty/Submitty/assets/68075099/b9bc5355-27fc-4d19-aeb5-5aca81cd537c)
Dark mode
![image](https://github.com/Submitty/Submitty/assets/68075099/2c4e9fe2-d87f-4dea-9c4e-56c07c09bf8c)

Whole post look
![image](https://github.com/Submitty/Submitty/assets/68075099/ff3d7d90-56c1-41db-aa32-7dce2318bd6b)
