### ISSUE TITLE
Grading details page control buttons are not consistent

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10397]
**Describe the bug**
The control buttons on the grading details page have no padding between them, and are not styled consistently.
![image](https://github.com/Submitty/Submitty/assets/16820599/6d539a20-13df-46dd-bbbb-74abc7d18ea2)

**Expected behavior**
The UI should be clean and consistent.

**Comment by dhananjay0610** [comment]
Hi, will raise a PR.
