### ISSUE TITLE
Increased-contrast pdf upload

### ISSUE THREAD

**Issue by Adsalor** [Submitty/Submitty#10425]
**What problem are you trying to solve with Submitty**
When bulk uploading pdfs, checking each page of each scan for legibility and scan clarity is infeasible, especially for large courses, so many scans which are near-illegible need to be rescanned later.

**Describe the way you'd like to solve this problem**
The Bulk Upload page should have an option to massively increase contrast on uploaded scans so that faint handwriting will still be visible.

**Describe any potential alternatives you'd tried to solve the problem**
Right now, I download the page .jpg and put a filter on it to increase contrast if a page is unreadable. It takes much longer than normally opening the pdf and is a lot less convenient.

**Comment by bmcutler** [comment]
Hi Adsalor,

I don't think this is a problem that can or should be solved with a post-process in software.
If the data isn't in the upload, we can't correct/invent that data.

Please see:
https://submitty.org/instructor/assignment_preparation/bulk_pdf_upload#tips-for-scanning
