### ISSUE TITLE
Add banner warning message for clock skew

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10458]
**What problem are you trying to solve with Submitty**
If your native machine / web browser clock time is different than the server clock time -- not just that the timezone is different, but the actual time is difference -- this can cause rendering bugs, user confusion, and problematic errors.

**Describe the way you'd like to solve this problem**
Let's add a simple check as we are prepping to render each webpage.
What is the current server clock?  What is users machine clock?   
It's ok/normal if the server and the browser have different timezones but represent the same time when converted to UTC.

But are they different by more than 5 minutes?  
This is a bug, one of the machines is not correctly using ntp to sync to the worldwide agreed upon time.   If they are different by more than 5 minutes let's add a banner that says "WARNING: Your client / web browser clock does not match the server clock and this may cause rendering bugs or other errors."

**Describe any potential alternatives you'd tried to solve the problem**
What threshold should we use?  I think something between 1-5 minutes makes sense.

See also #10440 (a bug related to skew) and #9584 (mac users development machines regularly experience skew) 
Banner should be similar to warning message for socket server being down #7020

**Comment by subCode321** [comment]
Hi @bmcutler can I pick this issue up?
