### ISSUE TITLE
the HTTP version of Submitty does not load

### ISSUE THREAD

**Issue by ION606** [Submitty/Submitty#10468]
**Describe the bug**

when going to http://submitty.cs.rpi.edu, the website will not load.

**Expected behavior**

Either a redirect to https or (probably less optimal) serving the site via http

**To Reproduce**
1. go to http://submitty.cs.rpi.edu

**Configuration**
 - OS: Windows, Fedora Spin Sway, IOS
 - Browser firefox, chrome, safari

**Screenshots**

![image](https://github.com/Submitty/Submitty/assets/58801387/9272b146-5180-4350-81c4-47c4428c0fe8)

**Additional context**

**Comment by bmcutler** [comment]
This is not a bug with Submitty, it should not be reported on Github.
