### ISSUE TITLE
Forum post upduck fails "Error parsing data. Please try again."

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#10466]
**Describe the bug**

Attempting to like a post results in a banner saying "Error parsing data. Please try again."

**Expected behavior**
The like should go through

**To Reproduce**
1. Go to thread
2. Attempt to like a post

**Configuration**
 - OS: [e.g. Windows, Linux, ...] MacOS
 - Browser [e.g. Chrome, Safari] Chrome

**Screenshots**

<img width="731" alt="Screenshot 2024-05-25 at 4 56 53 PM" src="https://github.com/Submitty/Submitty/assets/13932583/1c2583ad-682b-4671-9baf-56fcf65ea1a9">

**Additional context**

The request to 
https://submitty.cs.rpi.edu/courses/u24/csci4210/post/likes gets redirected to https://submitty.cs.rpi.edu/authentication/login which gets redirected to https://submitty.cs.rpi.edu/home, and the latter serves HTML.

**Comment by skara9** [comment]
Seems to be broken by #10373, which renamed the `/post/likes` route to `/posts/likes` to be consistent with the rest of the schema, but didn't update the client side AJAX call.
