### ISSUE TITLE
use: "quiz_normalize_and_drop" silent failure

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1048]
If in Iris, customization.json contains a boolean instead of an integer, e.g.
`"use": {"quiz_normalize_and_drop": true}`
then ./process_grades.out will immediately stop execution with no error message when running the following code in main.cpp:preprocesscustomizationfile()
`else if (token == "quiz_normalize_and_drop") {
          QUIZ_NORMALIZE_AND_DROP = itr.value();
	}`

If possible, an error message should be displayed.

**Comment by bmcutler** [comment]
redesign/solved as part of #1924
