### ISSUE TITLE
Cypress test for TA Grading Keyboard shortcuts

### ISSUE THREAD

**Issue by manzil-infinity180** [Submitty/Submitty#10501]
Writing the e2e test for this hotkey as i mentioned below and also attached the image for it. If we break the code in it the cypress code can help us and also reduce the time in debugging

**Describe the way you'd like to solve this problem**

Here is a list of shortcuts so far, (as per this pr #1995 )
* A: autograding module
* G: grading rubric module
* O: file browser module
* S: student info module
* 1 - 9: select/deselect rubric mark (of currently open component)

<img width="1266" alt="Screenshot 2024-06-02 at 6 29 40 PM" src="https://github.com/Submitty/Submitty/assets/119070053/8d4c5d85-a381-4aaf-945c-302c704a7908">

**Comment by manzil-infinity180** [comment]
please assign

**Comment by Clemo97** [comment]
nice, now close the issue @williamjallen and @manzil-infinity180
