### ISSUE TITLE
"Download Zip File" button downloads an empty zip file

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#10540]
**Describe the bug**
For a gradeable that uses Git, downloading Zip file for a student submission downloads an empty zip file.

**Expected behavior**
A zip file containing the student's submission should be downloaded.

**To Reproduce**
1. Navigate to the grading page of a student, e.g. https://submitty.cs.rpi.edu/courses/u22/csci4963/gradeable/hw01/grading/grade?who_id=5ZPpXEfkHpisfOA&sort=id&direction=ASC as shown in the screenshot below.
2. Click the "Download Zip File" button.
3. Open the folder where the zip file was downloaded.
4. Check the properties of the zip file to see that it is a valid zip file but contains no files inside of it. Here is an example:
[hw01_anon_v7.zip](https://github.com/user-attachments/files/15808689/hw01_anon_v7.zip)

**Configuration**
 - OS: Windows 11 Home Version 23H2 OS build 22631.3593 Experience Windows Feature Experience Pack 1000.22700.1003.0
 - Browser: Mozilla Firefox 127.0 (64-bit)

**Screenshots**
![image](https://github.com/Submitty/Submitty/assets/7108039/5ed7f6ce-eb77-4759-8e63-99e37bc6b415)

**Additional context**
This is from CSCI 4963 from U22, Homework 1. The gradeable uses git to collect submissions.

I recall reporting this bug long time ago, and I thought it was fixed. The bug was due to the download submission functionality using only ``submissions`` directory and ignoring the fact that git-based assignments store student code in ``checkout`` directory.

**Comment by williamschen23** [comment]
Hello, 

I was unable to recreate this bug, both the results directory and then checkout directory was download on my end. Can you provide more information on the bug?
<img width="469" alt="image" src="https://github.com/user-attachments/assets/335cfbf9-2302-4b8f-bf01-e5d64806b303">

**Comment by KCony** [comment]
Hey @williamschen23 ,

Sure, what kind of information would you like me to provide? I just tried to reproduce the bug that I reported, and it is still a bug, The downloaded file that I receive has 374 bytes, so it is essentially empty. Here is the file:
[hw01_5ZPpXEfkHpisfOA_v7.zip](https://github.com/user-attachments/files/16589395/hw01_5ZPpXEfkHpisfOA_v7.zip)

The folder structure is there but there are no files in this ZIP.

When you tried to reproduce it, which course/semester did you use? In my case, it was a summer 2022 semester and CSCI-4963. I also suspect that the bug might be related to Submitty issues in the anonymization implementation.

In any case, I'd really like this to be fixed ASAP because otherwise, I don't have access to old submissions through the WebUI. Please let me know how I can help you investigate this issue.

Also, please tag me with @KCony when responding to my comments because otherwise GitHub does not notify me that someone commented on my issue. I noticed your comment from a month ago by pure luck. Thanks!

**Comment by williamschen23** [comment]
This was an issue about not being able to download student's submissions from archived courses, both GIT and non-GIT submissions. Barb said that there are other ways in order to download student submissions, and since production Submitty is separated into different disk partitions and permissions might have changed, there is no guarantee that you can download submissions again. 

Also this works on the development VM after archiving a course, so I will close the issue now.
