### ISSUE TITLE
In the TA grading rubric, the TA can not use the arrow keys to enter in a non whole number.

### ISSUE THREAD

**Issue by AndrewMRPI** [Submitty/Submitty#1055]
In the TA grading rubric, the TA can not use the arrow keys to enter in a non whole number. For example, when the maximum point value for a question is 3.5, the TA may not use the arrow keys to advance towards 3.5. However, the TA may manually put in 3.5. However, even though that value may stay in that box, the rubric will not accept it as valid and request the TA to put a number no more than 3 even though 3.5 was specified as the maximum. This seems to be the case for regular, extra, and penalty credit.

**Comment by MasterOdin** [comment]
What's the full `<input>` that TAs see? I'm guessing that this is that we've specified a question that has a max value of 3.5, and a step size of 1, which the `<input type="number">` "messes" up on.

An example of this would be:
https://jsfiddle.net/rtrngq1b/1/
```
<form action="#" onsubmit="return false;">
<input type="number" min="0" max="3.5" />
<input type="submit" value="Submit" />
</form>
```
This will complain when trying to submit 3.5 as step defaults to 1, and so the nearest allowed number is 3.

https://jsfiddle.net/rtrngq1b/2/
```
<form action="#" onsubmit="return false;">
<input type="number" min="0" max="3.5" step="0.5" />
<input type="submit" value="Submit" />
</form>
```
Works fine for inputting 3.5.

So I don't think this is a TA grading bug so much a bug on the instructor form for creating a gradeable allowing for a step that doesn't work with the current max. Should make sure the max is evenly divisible by the step size.

**Comment by bmcutler** [comment]
currently does this, yay!

**Comment by bmcutler** [comment]
whoops, read matt's comment

**Comment by J16053** [comment]
I've been playing around with this to try and see where to start, and discovered that on the instructor form interface, if the precision size is changed to be indivisible by the current max points, the points are altered to be a multiple of the precision upon component reload. However, if the max points is changed to be a non-multiple, the precision remains unchanged, resulting in this instructor form bug. It seems as though there is already some kind of check in place, it just has not accounted for all possible input changes.
