### ISSUE TITLE
Formatting in markdown unable to directly apply to text

### ISSUE THREAD

**Issue by ZheyuDeng** [Submitty/Submitty#10563]
**Describe the bug**

Markdown text formatting should be like Github. When there's selected text, formatting should be directly apply to the text.
Right now when user clicks any formatting it is inserted in front of the selected text, making no changes. 

When there isn't selected text, it toggles the end of the line. User will need to click back to the default text then remove them and finally type the text for formatting to work which isn't optimal.

https://github.com/Submitty/Submitty/assets/122962727/628d9f5c-18cd-47e9-8b34-6cb65d3ac723

**Expected behavior**
Corretly apply formatting to text.
Directly type the text within formatting when there isn't any selected text.

**To Reproduce**
Go to http://localhost:1511/courses/s24/sample/forum/threads/new

**Comment by williamschen23** [comment]
I cannot replicate the second line. Also for the first line, if someone is referring to a file that has two underscores, they would need extra steps to tell markdown that it is not markdown for italics, so I think that the italics are fine in that regard.

**Comment by ZheyuDeng** [comment]
Close #10563 as Fixed by https://github.com/Submitty/Submitty/pull/10582

**Comment by ZheyuDeng** [comment]
Close #10563 as Fixed by https://github.com/Submitty/Submitty/pull/10582
