### ISSUE TITLE
"Grade Inquiry Only" button is broken

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10576]
**Describe the bug**
The "Grade Inquiry Only" button appears to be broken.  See the screen recording below.

**Expected behavior**
The Grade Inquiry Only button should only show students who have an active grade inquiry.

**Screenshots**

https://github.com/Submitty/Submitty/assets/16820599/03cef255-fdc5-4389-9b71-863c306abda5

**Comment by luchsj** [comment]
The filter seems to work on my end, but the page refreshes and disables it again. If you click the filter and then immediately stop the refresh, the filter works, but clicking on a student then returning to the list will break it.
I'm also getting this warning in the console when I click the button (in either state):
```
Cookie “inquiry_status” does not have a proper “SameSite” attribute value. 
Soon, cookies without the “SameSite” attribute or with an invalid value will 
be treated as “Lax”. This means that the cookie will no longer be sent in 
third-party contexts. If your application depends on this cookie being 
available in such contexts, please add the “SameSite=None“ attribute to it. 
To know more about the “SameSite“ attribute, read 
https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

js.cookie.min.js:2:846
```
