### ISSUE TITLE
TA grading notebook viewer only shows short answer responses upon click

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10607]
**Describe the bug**
Short answer responses currently do not show up in the notebook viewer panel of the TA grading interface unless the user clicks the short answer response text box.  This bug is potentially hugely impactful, because it could lead TAs to believe that a student did not submit an answer for a problem.  The student view does not have this issue.

https://github.com/Submitty/Submitty/assets/16820599/fbe62bc2-3cff-4549-addd-226f9275ffa2

**Expected behavior**
Responses should always be shown in the TA grading interface.

**Comment by sahilsuman933** [comment]
It must be solved in some other PR.﻿


https://github.com/Submitty/Submitty/assets/34382211/e504a699-2d1a-4168-9aa2-887f693745df

**Comment by williamschen23** [comment]
From my end I cannot reproduce this either.

**Comment by sahilsuman933** [comment]
Then, we can close it.
