### ISSUE TITLE
TA grading control buttons have ugly white outline in dark mode

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10711]
**Describe the bug**
The control buttons in the TA grading interface have an ugly white outline in dark mode.

![image](https://github.com/user-attachments/assets/1ecbc5bf-e6e7-483b-b2da-ae2bf6843137)

**Expected behavior**
The TA grading control buttons should have a clean design in both light and dark modes.

**Comment by lukeckk** [comment]
Im working on this
