### ISSUE TITLE
Text on TA grading panel selectors is not centered

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10712]
**Describe the bug**
The text inside the TA grading panel selectors is not centered within the colored outline:
![image](https://github.com/user-attachments/assets/f4d9c5ba-768d-4000-b5de-87f42a10c73f)

**Expected behavior**
The text should be centered.

**Configuration**
 - Safari 17.4.1

**Comment by ayushvyasgit** [comment]
Can i do this ?
i will center the text

**Comment by ayushvyasgit** [comment]
assign me
