### ISSUE TITLE
Build better courses for vagrant box

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1075]
Right now we create several (5?) courses when doing `vagrant up` where everyone generally then just uses one course for development/testing. We should therefore:
1. require setup_sample_courses.py to be given a course to build
2. in install_system.sh add course code to setup_sample_courses.py call
3. Update documentation to use course code in development instructions

**Comment by MasterOdin** [comment]
So after discussion with @bmcutler, this has changed to creating three courses:
1. Sample
    This will house a gradeable type in all categories as well as multiple different electronic gradeables that have interesting autograding, don't have ta grading, etc. This should appear as a normal course mid-semester.
2. Tutorial
   This will be the same as current one
3. Dev
   This will contain several different autograding homeworks as well as things that might be in development to be later moved to tutorial.

Tutorial and Dev will only have the four "core" accounts on them (developer, instructor, ta, grader, student) while Sample will have 100+ students.

**Comment by bmcutler** [comment]
Sample should have gradeables in the grading complete category that have:
* no autograding (ta grading only)
* no tagrading (autograding only)
* both tagrading & autograding
* autograding with hidden test cases
* autograding with extra credit tests
* ta grading with extra credit
* ta grading with penalty

**Comment by MasterOdin** [comment]
I think we can combine of these as some of them are not contradictory.

IE. We could combine "no tagrading" with "autograding with hidden test cases" and "autograding with extra credit", etc as if we don't, we'll end up with 10+ electronic gradeables which will end up having >5,000+ submissions and Vagrant will still take forever to spin up and be ready.
