### ISSUE TITLE
Uncaught SyntaxError: Identifier has already been declared

### ISSUE THREAD

**Issue by manzil-infinity180** [Submitty/Submitty#10758]
**Describe the bug**
During testing for notebook view panel , when i add the notebook from notebook builder and move back to ta grading interface i am getting two uncaught syntaxerror
```js
Uncaught SyntaxError: Identifier 'showPopup' has already been declared
Uncaught SyntaxError: Identifier 'colorEvent' has already been declared
```
For `showPopup ` it is due to naming conflict, as we have variable and function with the same name 
For `colorEvent ` i did not get the possible reason for the syntax error

**Expected behavior**
We have to fix the syntax error , so cypress test does not fail due to this syntaxError

**To Reproduce**
1. Submitty > sample > Edit Gradeable(http://localhost:1511/courses/f24/sample/gradeable/grading_homework/update?nav_tab=1)
2. From notebook builder click on start new and create a notebook 
3. Go back to rubric grading interface (http://localhost:1511/courses/f24/sample/gradeable/grading_homework/grading/grade?who_id=jKjodWaRdEV9pBb&sort=id&direction=ASC) 
4. See the error from inspect
5. 
**Configuration**
 - OS: [Windows]
 - Browser [Chrome]

**Screenshots**
`Before the notebook `

![before_the_notebook](https://github.com/user-attachments/assets/5a23dca8-cfa8-4d51-904e-bebe30480025)

`After adding the notebook from notebook builder `
![when_we_add_notebook_from_notebook_builder](https://github.com/user-attachments/assets/7c543fce-1387-4b22-8644-dc80055425e6)

**Additional context**

**Comment by msudipta888** [comment]
hey can i fix this issue if you agree

**Comment by msudipta888** [comment]
can you tell in more details about this issue

**Comment by manzil-infinity180** [comment]
> can you tell in more details about this issue

@msudipta888 sorry! you can see their i already raised a pr for it, try to pick some other issue 
Thank You
