### ISSUE TITLE
Sometimes deleting a question in the create/edit gradeable form will break it.

### ISSUE THREAD

**Issue by AndrewMRPI** [Submitty/Submitty#1076]
When one deletes a question that is not at the end of the create/edit gradeable form, the form will break. I tested this only when editing the form and not when creating. I will fix this issue when I am finished with porting the page.

**Comment by MasterOdin** [comment]
This is for a gradeable that has not had any grading in it so far?

**Comment by AndrewMRPI** [comment]
Yes, I did not test those that had been graded already.
