### ISSUE TITLE
Fix formatting in RainbowGrades Customization page

### ISSUE THREAD

**Issue by ziesski** [Submitty/Submitty#10881]
**Describe the bug**

![image](https://github.com/user-attachments/assets/fbbcb364-02ba-44c5-8965-9292192a11f5)

Notice how `display_rank_to_individual` has broken formatting due to lengthy term.

**Expected behavior**

Come up with better formatting that works with all the terms. 

**Additional context**

#10863 is related.

**Comment by udaykakade25** [comment]
This issue can be fixed using 'word-wrap: break-word' property in CSS. Please assign me the issue :)
