### ISSUE TITLE
"future polls" should not include "tomorrows polls"

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10897]
**Describe the bug**
Polls that are expected to release in the next day/24 hours are duplicately listed in tomorrows polls and future polls.  This is confusing.

**Expected behavior**
Future polls should not include tomorrows polls.

<img width="726" alt="Screenshot 2024-08-29 at 10 54 07 PM" src="https://github.com/user-attachments/assets/c6d37ab0-259a-4fcc-a843-7e964cf97d0f">

**Comment by naikmubashir** [comment]
I'd like to work on this issue, assign it to me.

**Comment by AsHuToShSiNgH02** [comment]
hey, is this issue open, if yes then I would like to work on it, assign it to me
