### ISSUE TITLE
Submitty fails to properly refresh the sum of all items in a numeric/text gradeable upon deletion of a rubric item

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#10938]
**Describe the bug**
When editing a numeric/text gradeable, a rubric item is removed, the total of points is not recomputed.

**Expected behavior**
The total of all points in the rubric should be properly updated when a rubric item is removed.

**To Reproduce**
1. Navigate to the Numeric/Text gradeable and edit it by clicking the pencil icon.
2. Remove an existing rubric item and observe that the total number of points has not been updated. In the animated GIF attached, the total should have been updated to read "6" because after deletion of the rubric item, there is only one item with 6 points left. However, Submitty still shows 12 points as the total.

**Configuration**
 - OS: Windows 11 Home Version 23H2 OS build 22631.3593 Experience Windows Feature Experience Pack 1000.22700.1003.0
 - Browser: Mozilla Firefox 127.0 (64-bit)

**Screenshots**
![firefox_vxNHyW7iB7](https://github.com/user-attachments/assets/9f812d3c-f439-432b-85f2-e3a2b967ca2c)

**Additional context**
N/A

**Comment by williamschen23** [comment]
In addition there is no error checking on the two boxes, which will have some decoding errors if not properly dealt with
