### ISSUE TITLE
Add a "today" and "tomorrow" shortcut to the Polls "Expected Release Date" calendar selector

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10942]
**What problem are you trying to solve with Submitty**

I have exported and imported polls from a previous term.
Before importing I set the dates 1 year ahead to make sure they were not visible to students until I was ready to use them.

When prepping for class I adjust the dates.  

<img width="372" alt="Screenshot 2024-09-13 at 9 17 05 AM" src="https://github.com/user-attachments/assets/698b41d3-438d-49ef-bc7a-0fecde02a29d">
 what the problem is. -->

**Describe the way you'd like to solve this problem**

Let's add the "today" and "tomorrow" shortcuts used on other calendars on Submitty to this dropdown as well.

**Comment by 25tallurich** [comment]
Is anyone working on this? If not may I work on this?
