### ISSUE TITLE
buggy late day message text

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10963]
**Describe the bug**
<img width="1045" alt="Screenshot 2024-09-19 at 6 53 26 PM" src="https://github.com/user-attachments/assets/96ffb2f1-806c-4705-b073-87cecc3110d7">
that message is ok.

but this other message is not ok:
<img width="889" alt="Screenshot 2024-09-19 at 7 06 12 PM" src="https://github.com/user-attachments/assets/05577644-2863-4b47-a0b5-296d4e8897eb">

The assignment allows students to use 1 late day.
My user has 2 late days available.

I believe that last sentence should  not say "You have 1 remaining late day for this assignment"
And it should instead say 
"You have 1 remaining late day for future assignments"

EDIT TO ADD:

While we are in here editing this message.  Let's add a link...
For more information, see your complete "My Late Days / Extensions" page, which points to the link also available from the  left sidebar on the bottom.

**Comment by kartikshukla17** [comment]
Hi would love to contribute to the issue!

**Comment by SharkyBytes** [comment]
Hey If the issue is still open Can I contribute for this issue??
