### ISSUE TITLE
Add unchecked blue marks to closed component view in TA grading.

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10972]
**What problem are you trying to solve with Submitty**

From the TA interface, when a component is open, we see ALL of the marks, whether they are blue or white or checked or unchecked:
<img width="561" alt="Screenshot 2024-09-20 at 7 28 11 PM" src="https://github.com/user-attachments/assets/2c0461cd-1394-4d0e-a465-6dceca4b8096">

From the TA interface, when we close the component, we see only the marks that are checked and the custom mark (if thye received it)
<img width="548" alt="Screenshot 2024-09-20 at 7 28 31 PM" src="https://github.com/user-attachments/assets/96ef2edf-d012-42cd-9c84-a896d6fa6517">

This is misleading / incomplete information about what the student will see.

When grades are released, the students see all of the blue marks (whether they are checked or not) and all of the white marks that they received (including the custom mark).
<img width="590" alt="Screenshot 2024-09-20 at 7 29 19 PM" src="https://github.com/user-attachments/assets/67e8419a-9aa7-4eb5-9d89-55815a8a1773">

**Describe the way you'd like to solve this problem**

Let's add the unchecked blue marks to the view when the mark is closed.

**Comment by VinayakPaka** [comment]
I would like to work on this issue ? Can you please assign this issue to me.

**Comment by sarthakvermaa** [comment]
Can you please assign this task to me?
