### ISSUE TITLE
Turning off anonymity in discussion forums

### ISSUE THREAD

**Issue by ditursi** [Submitty/Submitty#10997]
I would like the ability to turn off anonymous discussion forum posting for a course. I believe that students (indeed, people in general) are less like to appropriately filter what they are saying when they don't have to sign their name to their statements.

**Comment by bmcutler** [comment]
Posts on the forum are only anonymous to other students.   The instructor and other members of the teaching staff can see the authors full name and user id by clicking on the eyeball icon.

The teaching staff have ability to moderate the forum, editing to remove inappropriate content or deleting the post. (NOTE: posts aren't actually deleted, we store the history of edits and this can be reviewed/reverted by the instructor.). Instructors also have the ability to edit the boolean anonymity of a student's post.

Thus, I do not think it is necessary to give the option to remove anonymity from the entire course's forum.  Anonymity is an important feature to encourage students who are shy or lack confidence to ask help and engage in the forum in a positive way.
