### ISSUE TITLE
Rainbow Grades Failing When "status" field is null

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1100]
After recent changes to the contents of generated grade summary reports on Submitty, some `status` fields have a value of `null` instead of a string. This causes a crash in Rainbow Grades (main.cpp:1545) since a string is expected:

`std::string status = (*itr2).value("status","NOT ELECTRONIC");`

**Comment by MasterOdin** [comment]
Well, technically, status can either be a integer or a null (if we're talking about gradeable_data.status), so the expectation that it's a string is also wrong (though I guess it is a string when expected from the DB into a file).

**Comment by holzbh** [comment]
It used to be things like "Good" or "Late" which are definitely strings, so either it's not the same field as in the DB, or the meaning of the status field has changed? It's definitely been non-numeric in the past in the grade reports.

**Comment by MasterOdin** [comment]
Oh, I see what you mean. It was converted to a string in TAGradingServer/account/submit/admin-grade-summaries.php.

It at least cannot be a null in the database, and it must be on the conversion out it's messing up.

Though, would it make more sense to always output the actual integer for status in grade summaries and then let RainbowGrades operate on the integer?

**Comment by holzbh** [comment]
The issue was that there is a `Gradable::status` which is an int, and one under `LateDaysUsedCalculation::getGradable()` which is a string. We want the latter for grade summaries, though the logic for zeroing out score may be based on `Gradable::status`, I didn't dig deeper into the purpose of the two statuses.

Leaving this open for further commenting, not sure if unification makes sense. Having arbitrary integer codes is ugly though - I think the status should be human-readable by the time it hits reports, and earlier if possible. If it isn't in the codebase I'd like either a table of status code -> meaning or a comment/array somewhere for decoding integer codes. Right now seems like this is asking for trouble down the road if anything changes about which status codes mean what.

**Comment by MasterOdin** [comment]
I think I'd like to do the same thing I did with [GradeableType](https://github.com/Submitty/Submitty/blob/master/site/app/libraries/GradeableType.php) which is just make an "enum" class which contains a human readeable string (and a way to go to and from a real string) and use that consistently across the PHP code base. Would have to replicate this into the C++ code as well though.

I'd much prefer to stay as an integer code until immediate output as opposed to sometimes being a string, sometimes being an integer.

**Comment by holzbh** [comment]
So I see two options, either:

1. We only use the enum class approach inside PHP, and at output time in [GradeSummary::generateSummariesFromQueryResults()](https://github.com/Submitty/Submitty/blob/master/site/app/models/GradeSummary.php#L54-L56) convert to a string.

2. We stick to integers in the PHP and the .json output and maintain copies of the enum mapping in both PHP and C++. 

I could go either way, I'm in favor of definitely at least doing it in PHP. Thoughts, @bmcutler ?

**Comment by holzbh** [comment]
After discussion with @bmcutler we decided that "status" when written to the report should be a string both to make it easier for users to do their own operations on generated grade summaries, and because this may be expressing a more complex message (i.e. status code may correspond to "Bad" but we want the status field in the JSON to read "Bad too many late days."

Not opening another issue since #1110 will affect planning any actions.
