### ISSUE TITLE
If there's only one test case....  simplify the student view

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1102]
If there's only a single test case in a electronic gradeable, let's simplify the display.  

* Don't display the "Total" bar. 
* Auto-expand the details for the one test case.   (but still allow it to be collapsed?)

Note:  This was the previous behavior, but either the code was lost or perhaps because we have the "submission limit" test case that is usually "view_testcase" : false.

So revise that to:  "if there's only a single testcase with view_testcase == true"

**Comment by MasterOdin** [comment]
It's most likely the case of latter (namely that we now have a hidden testcase for everything so while the user only sees one testcase, the system thinks there are two so minimize both).

**Comment by wangj35** [comment]
Also, do not show a "Results" header if there are no visible testcases.
