### ISSUE TITLE
Write migration to correct partially deleted gradeables.

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#11130]
**Describe the bug**

Related to PR #11121 

Thanks @IDzyre for steps to reproduce a problem with delete gradeable
https://github.com/Submitty/Submitty/pull/11121#issuecomment-2460806085

- [ ] what is flawed about the database and/or filesystem
- [ ] how can we repair the flaws -- we must assume that delete failed for a reason (part way through)  and deleted something that we need to recreate.

Now that we know how to reproduce these incompletely deleted gradeables, we need to write a migration to correct the corruption of any flawed gradeables on production systems.

It's not enough that we patched the code in one spot that access the flawed gradeables to prevent one crash, we should fix the flawed/corrupted data.  There are likely other places in the system where these flawed gradeables are causing/could cause problems.

**Comment by IDzyre** [comment]
An update to the steps to reproduce, you need at least two gradeables for the frog robot to appear.

**Comment by lavalleeale** [comment]
The deletion issue from the example lined up with our investigation of the issue, and should not be possible to happen again, but it does not seem possible to completely restore the state of the gradeables. The two queries the migration needs to aim to revert are  [`UPDATE electronic_gradeable SET eg_depends_on = null, eg_depends_on_points = null WHERE eg_depends_on=?`](https://github.com/Submitty/Submitty/blob/2d7918788894281be43d1709d84c6bb1225af48f/site/app/libraries/database/DatabaseQueries.php#L6307) and [`DELETE FROM gradeable_anon WHERE g_id=?`](https://github.com/Submitty/Submitty/blob/2d7918788894281be43d1709d84c6bb1225af48f/site/app/libraries/database/DatabaseQueries.php#L6309).
