### ISSUE TITLE
Make Matlab autograding examples

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1113]
* Run a non plot (text only) matlab program, save text output.  (doesn't need a screen?)

* Run a program with a plot, screenshot the plot.

* Investigate writing a plot to a file, bypassing the need for screenshot (& a screen?)

**Comment by MasterOdin** [comment]
I think trying to do 2 (figure out how to run the matlab code, figure out how to get the appropriate window, screenshot that window, etc), it's probably easier to do 3 before that as then you'll just need to worry about running matlab (without all the other headaches) and seeing if something like this works:

```
figure('Visible','off')
plot(1:100)
saveas(gcf,'file.fig','fig')
```

or something of that nature ([gcf](https://www.mathworks.com/help/matlab/ref/gcf.html) is a special variable that refers to the latest opened figure).
