### ISSUE TITLE
The "Clear Filters" button wraps poorly

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#11167]
**Describe the bug**
The "Clear Filters" button wraps poorly.

**Screenshots**
![image](https://github.com/user-attachments/assets/5518692a-9f48-4e11-9aac-7ae673ac7930)

**Comment by niloferh** [comment]
I can work on this, can it be assigned to me?

**Comment by niloferh** [comment]
Sorry, I actually won't get the chance to take a look at this, someone else can go ahead and work on it

**Comment by ShashidharM0118** [comment]
@williamjallen Could you please provide more details on the expected behavior, especially for smaller screens, where the "Clear Filters" button might not fit on the same line?
