### ISSUE TITLE
Forum "Anonymous" checkbox needs space between checkbox and text

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#11177]
**Describe the bug**
The checkbox to post anonymously has no space between it and the corresponding text:
![image](https://github.com/user-attachments/assets/aeb11750-2fe2-4fea-a482-a7ff7627fa71)

**Expected behavior**
A small amount of space should be present.  It's important to note that CSS should be used to make the space non-breaking so the checkbox and text are always on the same line.

**Comment by Koladweep** [comment]
Eh, can you specify which page you encountered this bug on?
