### ISSUE TITLE
Feature Request: Display Number of Open Issues in README

### ISSUE THREAD

**Issue by RaginiSharma01** [Submitty/Submitty#11192]
It would be helpful to display the current number of open issues in the repository's README file. This could give contributors and users a quick overview of the project's status and indicate areas where help is needed.

You can use GitHub's issue badges or a simple manual update to the README to reflect the number of open issues.

Suggested Implementation:
Add the following badge to the README:
![Open Issues](https://img.shields.io/github/issues/{owner}/{repo})
I would love to work on this and contribute to the project. Could you please assign it to me?

**Comment by williamjallen** [comment]
@RaginiSharma01 I don't see a need to display the number of issues in our README, given that GitHub already displays the issue count at the top of the page.

**Comment by RaginiSharma01** [comment]
ok @williamjallen I got it
