### ISSUE TITLE
Gradeable Page has some bugs

### ISSUE THREAD

**Issue by AndrewMRPI** [Submitty/Submitty#1121]
The create/edit gradeable page won't save the question correctly after you update the question after you created it and then saved the page. When you go back to edit the question, the data won't save.

**Comment by AndrewMRPI** [comment]
Turns out the bug only happens on the sample issues provided. Not quite sure if it is worth fixing then. Will test more.

**Comment by MasterOdin** [comment]
Can you write a clearer sequence to reproduce this bug? I can't quite follow what your steps as written.

**Comment by AndrewMRPI** [comment]
1. Edit a provided sample homework gradeable. 
2. Change the data on the TA questions. 
3. Press Edit gradeable
 When you come back to the edit gradeable page, the data would not have saved. Sorry I should have been more clear.

**Comment by wangj35** [comment]
Not the same issue, but a bug on the same page:
When creating a new gradeable, if you start with a kind that has TA grading on by default (Numeric or Checkpoint), and then switch back to Electronic, "Will this assignment also be graded by the TAs?" has a default value of false. If you keep that radio selection false and submit the form, the value originally entered for "TA Grading Open Date" is still considered when putting the gradeable into the database (createNewGradeable in DatabaseQueries) and will cause an error if invalid.
