### ISSUE TITLE
Install .setup/bin to /usr/local/submitty/.setup/bin

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1144]
Right now, you run all .setup/bin scripts in-place in the repo. While this is fine on the Vagrant machine, on a real machine, this means that these scripts have to be edited with the proper DB information which isn't really good considering it may prevent doing a git pull.

We should instead install these scripts to /usr/local/submitty/.setup/bin where they're owned by root (maybe?) and can read from /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh to get the DB information.

All scripts would then read out of INSTALL_SUBMITTY.sh as appropriate details (DB host, user, password, etc.)

**Comment by bmcutler** [comment]
Proposal:

/usr/local/submitty/bin   stuff that instructors can run.   e.g.,  regrade.py,  grading_done.py,  build_course utilities, etc.

/usr/local/submitty/sbin  stuff that hwcron or root or hwcgi run   e.g.,  create_course.py,  grading_scheduler.py,  cgi stuff, etc.

/usr/local/submitty/.setup/bin   stuff that is run at system installation & setup time, or by developers who have sudo and are testing a dev machine or patching a live system to work with new code

Yes, permissions should control who can run what stuff, but sorting it into directories makes it easier to spot permissions errors, and allows browsing if the user forgot what the script was called or is curious what else they can do.

**Comment by MasterOdin** [comment]
I agree with separating things out into separate directories anyway just to reduce the clutter of things in a directory and to maintain a stronger sense of who has access to what (which permissions do, but just chmodding a directory leaves less room for error than having to chmod each individual file).

**Comment by emaicus** [comment]
Per our conversation earlier, right now partial_reset currently uses hard-coded variables for host, user, etc.
