### ISSUE TITLE
Drop glyphicons from PHP/HTML/CSS code

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1169]
Right now, we use a mixture of glyphicons and FontAwesome for icons in the codebase. As FA is easier to update, use, etc. due to its nature of being "text" (UTF-8 characters?) instead of a png spritesheet, I'd like to get rid of any place we use glpyhicons and use the appropriate replacement FA icon instead.

**Comment by bmcutler** [comment]
closed in #1224
