### ISSUE TITLE
Security in display_file

### ISSUE THREAD

**Issue by chameco** [Submitty/Submitty#1172]
As seen in #1158 .

`display_file` allows access to arbitrary files when logged in as student. Steps to replicate:

1) Login as instructor, open an assignment for grading, pop-out a file.
2) Right-click the logout link on the grading page, open in new tab.
3) Refresh the pop-out window; it will show the login screen.
4) Login as student, the pop-out window will once again show the contents of the file.
5) Refreshing the main grading page will show that you are no longer authorized.

**Comment by MasterOdin** [comment]
> Yeah, it looks like these lines https://github.com/Submitty/Submitty/blob/master/site/app/controllers/MiscController.php#L34-L36 needs an additional check that $_REQUEST['path'] starts with submissions. We need to accept arbitrary paths to some extent, but need to make sure those arbitrary paths exist within the $_REQUEST['dir'] directory.

**Comment by bmcutler** [comment]
Regarding file or zip of files & directories download option.

Wishlist:

Student level users can download their own submission materials, only if allowed for the course/gradeable (if student accounts are not well-secured, it might be better to disallow download of submission materials).

When peer grading is enabled, student peer graders can only download their peers' submission materials during the open grading period, and they can only download the material of students they are assigned to peer grade.  The materials would be minimally anonymized.

Limited access graders can only download the materials of students they are assigned to grade, and only during the open grading period.

Full access graders can download the materials of any student for gradeables that will be graded by TAs, at any time.
