### ISSUE TITLE
Sample courses should have users common to multiple courses

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1174]
Since there is now a central user database, [setup_sample_courses.py](https://github.com/Submitty/Submitty/blob/master/.setup/bin/setup_sample_courses.py) should have some users that are enrolled in multiple courses, and some that are not.

**Comment by bmcutler** [comment]
maybe its just create more specific user .ymls (says @MasterOdin)

**Comment by saxocellphone** [comment]
I think we have this now. For example, user willia is only enrolled in sample
