### ISSUE TITLE
"Archiving" of old courses from master submitty DB

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1184]
Wishlist:

We have a set of "current" courses, that are getting updated daily from the registrar feed.

We have a set of "recent" courses, that are good to maintain for reference.  Instructors want to review how they did something / how it worked last time they taught the class.  Students want to review grades from the term that just completed.  The user table for these courses are no longer auto-updated, but users can still access.  And in the case of students finishing an "incomplete" they may be making new submissions, instructors adding/changing grades.  These courses should still be backed up.

We have a set of "offline" courses.  No one needs to log in to these courses anymore.  These courses should not appear on the home/index page (issue #1183). The database may be backed up and removed from the database server.  The directory probably still exists (so we can do plagiarism checks).

Develop a process for either removing users from the master DB who are not in any current or recent course.  Or a process for reconstructing the master DB from a set of recent & current courses.  Or both.

(from #1138)

**Comment by bmcutler** [comment]
Partially completed over winter break.
Need to document on submitty.org under System Administrators, and
test/debug making the directories/files read-only and the database read-only and confirm that the instructor can still access most things.

Then...  let's add a small sample archived course to the vagrant machine to allow continued testing.

**Comment by prestoncarman** [comment]
Our submitty server has run out of INodes. We have manually archived our old courses to help clean up the system, but this would have be a nice option. You could have various levels of archiving:
- Compete zip of all the files.
- Remove all files except the last submission.
- Remove all submissions, the scored less then X,
- Remove all submissions not graded by a TA.
I think it would be nice to be able to keep some information in the application and just do some clean up so it does not take up space/inodes on the server.
