### ISSUE TITLE
Create the database in create_course.sh

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1188]

**Comment by MasterOdin** [comment]
So the only potential issue here is that create_course.sh is chowned to be root:course_builders which means that putting the DB information into this file would mean that instructors (and head TAs?) would be able to then get at it which would be bad.

I'd say that "create_course.sh" should be a root level action and chowned (like INSTALL_SUBMITTY.sh) to root:root and throw an error if attempted to be run by someone other than ID 0.

@bmcutler, thoughts?
