### ISSUE TITLE
Maintaining course enrollment

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#120]
Right now an instructor needs to do initial data entry & maintain the course list in 2 different places:
  * create website login (& SVN, if needed) accounts  https://github.com/RCOS-Grading-Server/HWserver/wiki/QUICKSTART:-INSTRUCTOR--or-COURSE-MANAGER#instructor-creating-student-accounts
  * add to ta grading database  https://github.com/RCOS-Grading-Server/HWserver/wiki/QUICKSTART:-INSTRUCTOR--or-COURSE-MANAGER#instructor-prepare-grading-database-instructions

- [ ] This should be merged to 1 place.

- [ ] WEBFORM - FILE UPLOAD OPTION:  We should make the upload file non-RPI-registrar specific.  (although it would be great if it detected & allowed the RPI format!  And we could extend to other school's special format's as needed.)

- [ ] WEBFORM - ONE-AT-A-TIME:  student addition or student drop (move to special "invalid/drop" lab section) or lab section change or grading section change

NOTE:  We should not completely remove a student from a course, even if they formally drop.  We may be asked about any grades before they dropped.

NOTE:  Sometimes we have students with special registration status (e.g., independent study), or test "students" that should not be removed from the course or dropped, even if they don't appear on the official roster.  Those students may or may not be assigned to an official lab section and/or homework grading section.

--------------------
original comment:

In addition to authenticating a user into the system...

Create list of allowed users per course.  Check this list before accepting submissions from each specific user.  (Or even allowing them onto the page).

**Comment by MasterOdin** [comment]
Well, you would want to just query this against the students table (which is part of the TAGradingServer) right?

**Comment by bmcutler** [comment]
Right now an instructor needs to do initial data entry & maintain the course list in 2 different places:
  * create website login (& SVN, if needed) accounts  https://github.com/RCOS-Grading-Server/HWserver/wiki/QUICKSTART:-INSTRUCTOR--or-COURSE-MANAGER#instructor-creating-student-accounts
  * add to ta grading database  https://github.com/RCOS-Grading-Server/HWserver/wiki/QUICKSTART:-INSTRUCTOR--or-COURSE-MANAGER#instructor-prepare-grading-database-instructions

- [ ] This should be merged to 1 place.

- [ ] We should make the upload file non-RPI-registrar specific.  (although it would be great if it detected & allowed the RPI format!  And we could extend to other school's special format's as needed.)

NOTE:  We should not completely remove a student from a course, even if they formally drop.  We may be asked about any grades before they dropped.

NOTE:  Sometimes we have students with special registration status (e.g., independent study), or test "students" that should not be removed from the course or dropped, even if they don't appear on the official roster.  Those students may or may not be assigned to an official lab section and/or homework grading section.

**Comment by MasterOdin** [comment]
This has been done already in a variety of commits
