### ISSUE TITLE
Specification of homework deadline / Fully test/debug deadline other than midnight

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#121]
- [x] The submission side allows specification of a non-midnight time, but should be thoroughly tested.

- [x] The ta grading side does not allow specification of a time (assumes midnight?).

EDITED TO ADD

- [x] The instructor should specify the due date and time in ONE PLACE.  Right now they have to put it in both the config/class.json AND on the homework rubric page.  Needs a design discussion.  The config/class.json should probably turn into a webform.

- [x] Instructor specification of course late day policy.  Needs documentation, & maybe a webform.  Instructor may want to disallow any late submission (not just a popup warning).  Issue #61

**Comment by MasterOdin** [comment]
The TA Grading doesn't use a plugin that supports selecting both date and time (and newer versions of it doesn't appear like it can still).

We would want to switch to a different plugin (like http://trentrichardson.com/examples/timepicker/) that allows selection of both date and time. However, database is already setup to allow non-midnight times  as the column type is timestamp.

**Comment by MasterOdin** [comment]
This was merged into master. While it defaults to today's date at midnight, can change the time to anything using the sliders at the bottom of the popup.

**Comment by bmcutler** [comment]
related to issue #316
