### ISSUE TITLE
Create missing webforms

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#122]
Right now, there's a lot of places users have to go through the database to manage things. We need to add webforms for managing these things:

- [ ] Students Table
- [x] Late Days Exceptions
- [x] Late Days
- [ ] Users Table
- [ ] Sections Table
- [ ] Academic Integrity (still needed?)

These are ordered in priority of completion

**Comment by bmcutler** [comment]
Make sure that the late days exceptions table is clear about for which homework the extension is granted.  (The homework number/name usually matches the rubric id number... but may not!  If a homework rubric was deleted and recreated the numbers get "off")

**Comment by pbailie** [comment]
The DB foreign constraint rules dictate that the _Students_ table is dependent on the _Sections_ table.  Therefore, _Sections_ may have to be addressed before _Students_.  But from labstaff support perspective -- _Late Day Exceptions_ may be more important than _Sections_.

Creating branch `Issue_122` to begin work.

**Comment by MasterOdin** [comment]
This is true and I support the decision to focus on Late Day Exceptions right now as this is also more "mission critical" for instructors (as the other web forms would really only be used at the beginning of the semester and then not again).

I also removed the "Late Days Table" as I'm not sure what exactly that references as this is all contained in the students table really.

**Comment by bmcutler** [comment]
Remaining items covered by other issues.
