### ISSUE TITLE
Streamline navigation through the TA grading interface

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1238]
2 options:

Grade every component of the rubric for one student, then press "next" to move to next student 

Grade specific component on the rubric for student A, and when that is "saved" (closed), move to the student B, and automatically open that same component for marking and automatically scroll the pdf to the appropriate location.

[ we'll have to make a UI for the instructor to specify which page/crop of the X page pdf corresponds to each component ]

created related issue #1261

**Comment by bmcutler** [comment]
See also discussion in #872

**Comment by AndrewMRPI** [comment]
Actually the arrow keys move through students according to the Users: Student page, so this issue can be closed.
