### ISSUE TITLE
Put Name of university / Name of VM somewhere?

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1252]
Would be nice to have something visual differentiating our 2 VMs, Ubuntu vs Debian.
Could just sneak it in the name of each course on the VM/setup sample courses (Issue #1236).

Or we could make a space for the university/department to insert their name in the title bar.  
And put the distribution in that spot for our vagrant VMs.

Or in the breadcrumb line?

**Comment by MasterOdin** [comment]
To do this within the breadcrumb line, we'd probably either want to add the ability to add a new "front" node (before the course name) that has this name (add it to master.ini?) or add the ability to change the second node ("Submitty") to be whatever you wanted it to be (defaulting to Submitty).

**Comment by bmcutler** [comment]
We finished this a while ago...  :)
