### ISSUE TITLE
Have test ajax calls block till previous one completes

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#126]
If someone submits multiple test columns at one time, it ends to the potential of having multiple rows in the database for that particular test. Should not happen. Also further restrict the DB to explicitly disallow this in case multiple users are editing the same test.

**Comment by bmcutler** [comment]
Wasn't an issue we encountered recently...  but the error behavior when you exceed the max per part was nonintuitive.  improve please.  suggestion greyed out placeholder of max in each box.

**Comment by MasterOdin** [comment]
We've implemented new restraints on the DB to prevent multiple rows, and implementation of #1004 will generally fix the issues caused by this.
