### ISSUE TITLE
Create "rcos homework server" logo & add to page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#128]
(need to finalize the 'product' name)

There's blank space on the upper right corner of the page... (or we should reorganize/redesign the overall page layout)

**Comment by bmcutler** [comment]
Melissa, you asked about Photoshop skillz earlier.  Do you want to lead the brainstorming for a design?

**Comment by lindquistador** [comment]
Yeah sure I could do that

**Comment by bmcutler** [comment]
Our name is Submitty.

**Comment by bmcutler** [comment]
see http://submitty.org
