### ISSUE TITLE
Write delete course database script [renamed]

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1282]
REWRITE/RENAME of the original issue.

Write a short script that will clean up a course from the databases...  it should delete the course database and remove the course from the master submitty database courses table.  Note: removing the course from the master database courses table should cascade delete to remove the table associating users with their valid courses.  the script WILL NOT delete the files from /var/local/submitty/courses/etc.  That should be a separate step, only if desired.

Also making new issue #1304

old text of issue below
---------------------

Process of creating new courses for instructors that have other courses and do not have other courses needs to be tested & debugged.

Documentation needs to be cleaned up.  If sysadmins are supposed to use the new /usr/local/submitty/bin/adduser.py script, it should be added to the documentation.

I managed to get myself stuck.  I was trying to reset a course (delete database & directory) without deleting the master submitty database.   Account "A" that already had a course wasn't able to be instructor for a new course.  So account "B" made the course as instructor and tried to invite "A" to be a co-instructor, but that resulted in the error below.  Account A is still not able to access the course.

I very likely didn't follow intended sequence of actions, but the documentation is missing.  Not sure if a trigger was supposed to clean up something, or if the code is just incomplete / under-tested.

---------------

FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/Database.php (Line 116) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);

Message:
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "courses_users_pkey"
DETAIL:  Key (semester, course, user_id)=(XXX,XXX,XXX) already exists.

Strack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueriesPostgresql.php(94): app\libraries\Database->query('
INSERT INTO courses_users (semester, course, user_id, user_group, registration_section, manual_registration) 
VALUES (?,?,?,?,?,?)', Array)
#1 /usr/local/submitty/site/app/controllers/admin/UsersController.php(147): app\libraries\database\DatabaseQueriesPostgresql->insertCourseUser(app\mod
els\User, 's17', 'csci1200')
#2 /usr/local/submitty/site/app/controllers/admin/UsersController.php(22): app\controllers\admin\UsersController->updateUser('graders')
#3 /usr/local/submitty/site/app/controllers/AdminController.php(52): app\controllers\admin\UsersController->run()
#4 /usr/local/submitty/site/public/index.php(192): app\controllers\AdminController->run()
Extra Details:
	query: 
INSERT INTO courses_users (semester, course, user_id, user_group, registration_section, manual_registration) 
VALUES (?,?,?,?,?,?)
<snip>

**Comment by pbailie** [comment]
So if I understand this correctly, there are actually two distinct issues here.

1. `adduser.py` is undocumented.
2. There is a unique constraint violation happening in the Submitty Master DB when trying to get an instructor to have more than one course.

**Comment by MasterOdin** [comment]
1. Yeah, we need to add documentation on using adduser.py to add users (instructors) to the system 
2. It sounds like we also want to add a "deletecourse" script that deletes the directory for the course as well as delete the DB for that course and remove it from the master DB (reverse the steps of create_course.sh).
3. Determine the full state of the system that would cause this issue (I agree with Peter on what it sounds like is happening).

**Comment by bmcutler** [comment]
Instructions placed on 
http://submitty.org/sysadmin/course_creation
