### ISSUE TITLE
Was able to create a course, even though the master database was not valid

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1283]
The "submitty" database existed, but it didn't have any tables in it (due to permissions error grabbing sql file?).  

create course should not construct the course database if the top level database is invalid.

**Comment by pbailie** [comment]
Re-read #1283.  Not yet resolved on commit 669142a.

**Comment by bmcutler** [comment]
Note:  I got myself into a bad state by copying pasting buggy instructions to re-create the top level db (outside of install_system).
Instructions here are now correct:
http://submitty.org/sysadmin/database
