### ISSUE TITLE
Add teams and submissions to sample team assignment

### ISSUE THREAD

**Issue by James-M-Anderson** [Submitty/Submitty#1287]
Currently there is only one team assignment with no teams or submissions in the Sample course.

setup_sample_courses.py should create randomized teams and submissions for them. We should also have team assignments in the grading stage and with past team lock dates.

**Comment by CouleeApps** [comment]
#2064 does most of this, but there's still a few things that would be nice:

- [ ] Team gradeable in grading stage
- [ ] Team gradeable before open, has no teams
- [ ] Team gradeable with grades released

**Comment by saxocellphone** [comment]
Closing this issue for now,  I don't want to add too many team-related gradeables since the number of autograding submissions has increased drastically
