### ISSUE TITLE
Can't edit teams when there is no TA grading/Always show Grading Details

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#1288]
If a professor creates a team assignment with no TA grading, they are currently unable to access the Grading Details page without url hacking. This means that it is impossible for non superuser professors to modify team compositions/create student teams for assignments with no TA grading.

To fix this issue, we discussed making the grading details page accessible to the professor (and possibly TAs) even if there is no TA grading.

**Comment by bmcutler** [comment]
@emaicus This should be closed now, right?  Please confirm
