### ISSUE TITLE
Web UI to add/delete registration sections for a course

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1293]
Allow instructors to add section at any time.
Can only delete a registration section if there are no users in it.

Note:  Instructions have been added to submitty.org so a sysadmin can directly add registration sections to the database.

**Comment by MasterOdin** [comment]
Adding sections (and managing them?) should just be a UI within managing the course, we don't need a sysadmin tool to do this.

**Comment by bmcutler** [comment]
Modified issue title & description.
