### ISSUE TITLE
Replace UI images with Font Awesome

### ISSUE THREAD

**Issue by AndrewMRPI** [Submitty/Submitty#1296]
UI images should be replaced with Font Awesome for consistency. One known UI image is the resize icon in the TA grading page. It is used in /site/public/css/jquery-ui.min.css. Once they are all removed, we can get rid of the image file, images/ui-icons_222222_256x240.png. Please look at #1272 for more details.

**Comment by bmcutler** [comment]
finished?  re-open if something is missing.
