### ISSUE TITLE
Write php utility/library function that writes date/time/timezone

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1301]
In our agreed upon format.
(& another that reads?) 

And change all php code to use this function

**Comment by MasterOdin** [comment]
This new functionality should be added as static functions within the DateUtils.php class.

**Comment by muarachmann** [comment]
@bmcutler this seems to be good issue i can handle. Any guides would be greatly appreciated thanks :)

**Comment by bmcutler** [comment]
We will re-open if this is still an issue.
