### ISSUE TITLE
Generate Grade Summaries exceeds server memory

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1306]
On a fresh Ubuntu vagrant build, in the sample course, when using Generate Grade Summaries for the first time, I get an exception. Examples across separate destroy/rebuilds are:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in /usr/local/submitty/site/app/models/Gradeable.php on line 367

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/submitty/site/app/models/AbstractModel.php on line 83

Refreshing several times eventually lets the generation complete without throwing another exception.

**Comment by holzbh** [comment]
Update: The failure is happening in [GradeSummary.php153:](https://github.com/Submitty/Submitty/blob/master/site/app/models/GradeSummary.php#L153) because the current workflow is

1. Grab all Gradeables in one query
2. Process the Gradeables one at a time, storing information for each student's summary file in memory
3. Write out all summary files

Unfortunately, it looks like grabbing all the Gradeables data (step 1) for sample is a memory problem with the 128M memory limit we currently have. Doing one query per user would result in a large number of queries.

Some preliminary thoughts on how to manage this:
* Only grab constant number (G) of g_id at a time
* Only grab a constant number (U) of user_id at a time
* Select G and U such that G*U < C, where C is a constant indicating the maximum number of Gradeables to load at once

**Comment by holzbh** [comment]
Since users is typically going to outnumber the number of gradeables, for the moment I'm testing with just using 1 gradeable at a time (G=1), which hasn't failed with the default 128MB. It's still worth doing some G>1 testing to see where the breaking point is and if we can minimize the number of queries by doing multiple

This is a periodic operation though so it might not be too terrible to have gradeable_id number of  queries, but I could see DB load problems down the road especially if multiple courses are simultaneously generating grade summaries and we're still doing that many.

**Comment by MasterOdin** [comment]
I would want to extend the DB to have the capacity to either return all results all at once or to smartly return an interator to go through (a lot of pages would benefit from this as we don't need all gradeables all at once when we're looking at the summary page for a gradeable).
