### ISSUE TITLE
TA Grading Order 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1314]
When in the middle of TA grading, the "next" and "prev" buttons should cycle through the students in the same order as on the details page (alphabetical by rotating or registration section as appropriate for this gradeable).

Question: At one point it was taking you to the next *ungraded* student.  I don't know if it still does that, if we want to support that.  To be discussed.

New Feature Request: Give the TA an option of "random order", like "overwrite grader", and "open same stuff" (open component, autograde test, and files & scroll to same place I had open on the last student).  When in random order mode, it visits the students in a random order, but repeatable order (so if you go 2 next & 2 prev you are back on the same student).   Note: random order is used to somewhat distribute bias of being first or last graded.

**Comment by bmcutler** [comment]
We discussed this last week and Glenn is going to start refactor/redesign/implementation

Notes:

* option to grade in (pseudo) randomized order 
* skip over students with "no submission" or "cancelled submission"
* skip to the next ungraded student (and eventually, if I'm grading a specific problem, skip to the next student with that problem ungraded)
* make sure it does something good with teams (currently a bug! #3245 )
* make sure it works for both grade by registration & grade by rotating section
* make it efficient
* let's design a clear/elegant/simple UI to control what next means...  (allow instructor to set, allow TA to override, store state in a cookie???)

**Comment by bmcutler** [comment]
@CouleeApps What is the status of this issue?

**Comment by Kevin-MM** [comment]
I've got Glen's old branch up and running and it appears to work great.  As part of this issue I will:

- [ ] Add a 'random' order button to details page
- [ ] Make it so when viewing all sections on the detail page, ordering by some criteria doesn't default to showing you only your assigned sections

**Comment by Kevin-MM** [comment]
Additional Items:
 - [ ] Add an additional set of arrows to the TA grading interface that allows the grader to move to the next ungraded item.  This is an important distinction from the initial set of arrows, which goes to the next submission (graded or not).
- [ ] Implement 'by component' functionality for the arrows.  For example, if a grader has a component open, and they click the 'next ungraded' arrow, they should get the next submission where that specific component is ungraded.
- [ ] Solidify the concept of 'view all' mode and 'view sections' mode.  The next arrows should respect which mode you are in.  The progress bar on the top of the TA grading interface should correctly indicate progress for each mode.

**Comment by Kevin-MM** [comment]
The rest of these issues will be addressed in #3951
