### ISSUE TITLE
New Rubric System

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#132]
Need to finish up the new rubric system.

Tasks for it:
- [x] Remove rubric_number for the system. All references should just use rubric_id instead
- [x] Allow for custom rubric_name for all created rubrics.
- [x] Allow for custom rubric_submission_id for all created rubrics (to properly reference folders on the submission server)
- [x] Allow for custom rubric_parts_submission_id for parts (with each part potentially having it's own unique id). This should just be a comma separated list in the one column.
- [x] File Viewer when grading (don't display any files in the tabs on the left pane, just have a list of files underneath with each file being clickable to view it)
- [x] Save used assignment number when grading and then load that number for subsequent regrades. ~~Allow for TAs to manually change the assignment numbers though that they're grading. This should allow them for changing multiple active assignments without losing their work.~~ (this should be done in a subsequent patch)
- [x] TA grading access to submitted homeworks before deadline (#117)
- [x] Deadline other than midnight (#121)

Test cases:
Multi Part Assignments:
- [ ] All parts submitted on time
- [ ] One part submitted on time, one part submitted late (but not too late)
- [ ] One part submitted on time, one part submitted too late
- [ ] One part submitted on time, one part submitted late, one part submitted too late
- [ ] One part submitted on time, one part not submitted
- [ ] One part submitted on time, one part submitted late, one part not submitted
- [ ] One part submitted on time, one part submitted too late, one part not submitted
- [ ] All parts submitted late (but not too late)
- [ ] One part submitted late, one part submitted too late
- [ ] All parts submitted too late
- [ ] No parts submitted

Single Part Assignments:
- [ ] Submitted on time
- [ ] Submitted late
- [ ] Submitted too late
- [ ] Not submitted

Additional test cases:
- [ ] Student has previous grades with late days and on next assignment should have late days used, with no exceptions and with some exceptions.
- [ ] Autograder for assignments with separate parts 

Should be further tested with extensions for students on the homework assignment.

**Comment by MasterOdin** [comment]
Rubric name and submission_ids handled now in creation/editing of rubric as of 318ac81b488826b7f7231442ef4ef7e1998fde4f

**Comment by bmcutler** [comment]
Proposed (and tentatively agreed) on a significant design simplification:
Parts will actually be grouped together for version history & submission date.  
All parts are submitted together so they have the same due date and the same # of late days.

**Comment by bmcutler** [comment]
@MasterOdin Can we close this issue?
