### ISSUE TITLE
Allow negative points in autograding test case

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1324]
Use case:

one test case may check for hardcoding, or use of forbidden technique and want to apply a large negative score penalty that effectively zeros out points from other test cases.

**Comment by scopeInfinity** [comment]
Hi @bmcutler, can you please clarify my doubts regarding scoring rules.
Is it allowed to have total score as negative for any case? If yes, which among late submission penalty, negative score testcases or both can contribute to total negative score?

Reference Image
![image](https://user-images.githubusercontent.com/9819066/37541935-59529dc6-2982-11e8-8712-d37cd6a7d366.png)

**Comment by bmcutler** [comment]
Make sure that when penalty autograding is implemented we test & revise the short-circuited submission limit test case implementation from PR #5527 to ensure correct math.
