### ISSUE TITLE
maintenance mode

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#133]
Add a system configuration for maintenance.

A message "not accepting new submissions", and an estimate of when things should be back online.

**Comment by MasterOdin** [comment]
Do we want to extend this maintenance to the grading server as well?

In any case, I'm assuming the flag would be a ```"maintenance": true/false``` parameter in the class.json

**Comment by bmcutler** [comment]
Yes, should also disable parts of ta grading as well.  (Alert TAs who are currently grading?  That might be challenging?)

I was thinking a whole system flag that the sys admins would use when they needed to update software, or even reboot whole machine.

Could also be nice to have per course.  Might even be automatically set/unset when course builder is running the "build course" script to prepare configurations?

**Comment by MasterOdin** [comment]
You could have the system run an ajax call to check if matienance has been turned on when they're grading, and if so, not allow them to proceed. Wouldn't be too hard/expensive really in the grand scheme of things.

Where would you set a system level config value like this? I'm not sure there's a "system.json" file or anything in existence, so I feel like you'd have to do it per course at the moment.

**Comment by bmcutler** [comment]
Overlaps with #1415
