### ISSUE TITLE
autograde compare a file of numbers with a tolerance

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1362]
For example, a matlab output file with a vector or matrix of floating point numbers.  Reasonable partial credit if the size of the vector or matrix is correct, and the numbers are within instructor specified tolerances.

**Comment by bmcutler** [comment]
Design idea:
Expected output files is provided by the instructor.
We tokenize this input file and identify all numbers (only digits and '.') vs all other strings.
If the student's file matches all other strings perfectly, and all numbers within a tolerance (specified in the config.json file), they can receive full or partial credit (controlled in the config.json file)

**Comment by bmcutler** [comment]
As an example, a student might be expected to write a program to output a table of sports scores for tennis players. sorted by winning percentage:

The correct output:

```
GAME STATISTICS
Player              W    L   percentage
David Nalbandian   49   44        0.527
Radek Stepanek     24   22        0.522
Marcos Baghdatis   73   69        0.514
Ivan Ljubicic      21   25        0.457
Danai Udomchoke    18   25        0.419
```

And we want to give partial credit if the only mistake the student makes is in the formatting of the final score (if they have the wrong number of significant digits):

```
GAME STATISTICS
Player              W    L   percentage
David Nalbandian   49   44        0.53
Radek Stepanek     24   22        0.52
Marcos Baghdatis   73   69        0.51
Ivan Ljubicic      21   25        0.46
Danai Udomchoke    18   25        0.42
```

Or alternately if they get the column spacing wrong:

```
GAME STATISTICS
Player W L  percentage
David Nalbandian 49  44  0.527
Radek Stepanek  24  22  0.522
Marcos Baghdatis  73  69  0.514
Ivan Ljubicic  21  25  0.457
Danai Udomchoke  18  25  0.419
```

**Comment by poorna2152** [comment]
The [numdiff](https://www.nongnu.org/numdiff/) linux package can handle number difference when given a certain tolerance (also does string difference as well). Can we use that for this?
eg:
for above example
`numdiff file1.txt file2.txt -a 0.1` (with -a flag setting a tolerance)
outputs as no diff between the files.

**Comment by poorna2152** [comment]
`numdiff` output for the first two ouputs in the above comment when run without a tolerance.
![Screenshot from 2022-07-25 22-53-30](https://user-images.githubusercontent.com/58025190/180838180-2a851075-518e-4f63-8f6e-0f8210cd5062.png)
