### ISSUE TITLE
Grading Details page display of incomplete autograding results

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1363]
If autograding is incomplete (e.g., there is a submission folder, but not a results folder), the grading details page should not show 0/30 pts, instead that spot should either be blank or it have a message  "incomplete" or "ungraded".

**Comment by MasterOdin** [comment]
I think a better solution for this would be to have a flag in electronic_gradeable_data that is `was_graded` that defaults to `false` and in insert_version_details.py it gets updated to `true`. That way we're not adding in directory checks for all rows in that table (or even just the ones that have a value of 0) and supporting it is pretty minimal effort.

**Comment by bmcutler** [comment]
can we just allow that value to be null in the database
(either is a database change that if we're doing it needs to be done ASAP)

**Comment by MasterOdin** [comment]
The current structure is:
```
CREATE TABLE electronic_gradeable_data (
    g_id character varying(255) NOT NULL,
    user_id character varying(255),
    team_id character varying(255),
    g_version integer NOT NULL,
    autograding_non_hidden_non_extra_credit numeric DEFAULT 0 NOT NULL,
    autograding_non_hidden_extra_credit numeric DEFAULT 0 NOT NULL,
    autograding_hidden_non_extra_credit numeric DEFAULT 0 NOT NULL,
    autograding_hidden_extra_credit numeric DEFAULT 0 NOT NULL,
    submission_time timestamp(6) with time zone NOT NULL,
    CONSTRAINT egd_user_team_id_check CHECK (user_id IS NOT NULL OR team_id IS NOT NULL),
    CONSTRAINT egd_g_user_team_id_unique UNIQUE (g_id, user_id, team_id, g_version)
);
```

I wouldn't be wholly opposed to allowing the `*_credit` columns be null and use the fact any of them are null as indicators that this hasn't completed autograding or to have a binary flag (as I suggested) that indicates whether or not autograding has been complete.

You are right that either would require slight DB changes so we should make a decision sooner rather than later on this if we want it for this semester.

**Comment by bmcutler** [comment]
Oh, I forgot there are actually 4 pts fields (more complicated/messy).  I retract my suggestion.  Let's do a simple additional boolean for autograding_complete.

@MasterOdin  or @jbarthelmess can one of you ASAP make a PR that adds the new column and whatever minimal initialization of that column so it doesn't break things (e.g., always set to true).  And then proper use of the column can come later.

**Comment by bmcutler** [comment]
Actually, we finished this a while ago, I think.  Will reopen if there is still something.
