### ISSUE TITLE
Indication that Generate grade summaries is complete or when last run

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1372]
either make the green message hang around
or
make the page say "done"
or 
include a "date last ran/finished" on the view page

(or some combination of these)

**Comment by bmcutler** [comment]
Also...  put this on the upload .csv students :)

**Comment by Kevin-MM** [comment]
@bmcutler Can you please give me more clarification about your second comment?  If this is no longer longer a thing then we can close this issue.
