### ISSUE TITLE
Reorganize Submitty Developer docs

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1374]
It feels to me that we want another level of sub-folders within the left hand navigation that allows for a cleaner organization of concerns. The current setup is:
```
VM Install using Vagrant
Development Instructions
Database
Automated Grading
JSON Configuration Files
JSON Responses
Coding Style Guide
How to Contribute
Autograding Tests
PHP Unit Tests
End-to-End Tests
Travis CI
Rainbow Grades Tests
```

It might be nice to reorganize it to something like (I think):
```
VM Install using Vagrant
Development Instructions
PHP Site Development
    Model-View-Controller
    Folder Layout
    Database Layer
    Unit Testing
    End-to-End Testing
    Code Style
Autograding Development
    Testing
    Code Style
Rainbow Grades Tests
JSON Configuration Files
JSON Responses
Travis CI
How to Contribute
```

Where this is all under the main title of "Developer".

Makes this a bit cleaner I think when we add more and more documentation for an increasing amount of differing sections of code that are largely independent of each other.

**Comment by holzbh** [comment]
Agreed. Might be nice to have some sort of collapse-and-expand for these inner layers of links. 

I threw something up quickly that doesn't expand/collpase for splitting up Rainbow Grades instructions but I'm not saying the style is ideal. Italics are a bit odd, but for non-link page group headings there should be something to visually differentiate them from links, so I just went with italics.

**Comment by MasterOdin** [comment]
Done in 23553d6fd8feaa868446fe0f699349b95bf98b01

**Comment by MasterOdin** [comment]
Closing this as the docs are organically being rewritten to better fit our needs and that we don't necessarily need a meta-issue to track this.
