### ISSUE TITLE
JS for some of ta grading is broken

### ISSUE THREAD

**Issue by MarisaPLee** [Submitty/Submitty#1382]
- [x]  Custom mark score and comment does not save upon refresh.
- [ ]  Broke moving questions around
- [x]  Javascript is broken to update who the grader is.
- [ ]  Should not show general comment to peers(marks js should not default to closing general comment)

**Comment by yshubham** [comment]
Is anyone working on this?  If not I would like to work on it.

**Comment by LeonMontealegre** [comment]
@yshubham  Yes, I am currently working on pretty much everything in ta-grading.js right now. Sorry.

**Comment by yshubham** [comment]
cool , Thanks

**Comment by bmcutler** [comment]
refactor in progress, other issues will be opened as needed.
