### ISSUE TITLE
Peer stats on Status Page for tas

### ISSUE THREAD

**Issue by MarisaPLee** [Submitty/Submitty#1385]
* Stats for grading done is only out of ta grading questions, this should be made clear, perhaps by adding stats for peer grading done.
* It would be nice to explain the numbers in the parenthesis
* If there is a peer component, the stats on the right (average, standard deviation) is incorrectly calculated

**Comment by Sagnik-Chaudhuri** [comment]
I wanted to get started with this. What should I do?

**Comment by bmcutler** [comment]
replaced by #5372
