### ISSUE TITLE
Peer grading code improvement

### ISSUE THREAD

**Issue by MarisaPLee** [Submitty/Submitty#1387]
- [ ] ~~Since in gradeable_component_data the gcd_grader_id is part of the primary key it would be nice to move that to the third column, next to the other columns that make up the primary key~~
- [x]  Break out checking permissions to a seperate function
- [x]  Remove unused code in electronic grader view and controller from when we saved the entire gradeable at once
- [ ]  ~~Update AbstractDatabaseQueries.php~~
- [x]  Should remove total_tagrading_extra_credit and total_peer_grading_extra_credit. Rename total_tagrading_non_extra_credit and total_peer_grading_non_extra_credit to indicate that they are max...there is no longer explicit extra credit or not
- [ ]  ~~Not sure why getgradeablecomponents was rewritten, it's more difficult to read/understand~~
- [ ]  ~~Instead of checking if getGrader() is null to see if a component is graded, we should check if the component has_marks or has_grade.~~

**Comment by jchulton** [comment]
Removing 
Since in gradeable_component_data the gcd_grader_id is part of the primary key it would be nice to move that to the third column, next to the other columns that make up the primary key
Also its work noting that AbstractDatabaseQueries.php no long exists
