### ISSUE TITLE
Home page tweaks

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1400]
- [x] Default name for course should be the course_id.  Don't have special case for "Course Name".
- [x] Make configure work even if you don't have institution_name, institution_url, or username_change_text set.  (Right now it errors).
- [x] username_change_text is not being initialized in either install_submitty or submitty_conf
- [x] intuition_homepage is being set in both install_submitty and submitty_conf, but doesn't seem to be working. 
- [x] Also, on the list of "Your Courses" on the homepage, please add the course name.  So it should say something like "f17 csci1200 Data Structures"
- [x] Error if you can't read course configuration file.

**Comment by emaicus** [comment]
Could not replicate lack of username change text on vagrant up. I'll try it on an install system next.

**Comment by emaicus** [comment]
Unable to replicate username_change_text not being initialized. Hopefully the fix to make configure work better with defaults fixes the issue if it exists.
