### ISSUE TITLE
Parts bug w/ re-building gradeable

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1420]
If an gradeable is created & built first with a config that does not have parts, then the config is changed to now have parts and re-built, it seems that we don't recognize it to now have parts.

Something isn't getting re-freshed correctly.  Needs more investigation.

**Comment by MasterOdin** [comment]
This sounds like either the build_*.json file isn't being made correctly or there's a bug with loading the config in the [GradeableAutogradingConfig](https://github.com/Submitty/Submitty/blob/master/site/app/models/GradeableAutogradingConfig.php) model.

**Comment by bmcutler** [comment]
It's a files problem, most likely not a webcode or db problem.
I manually cleaned out all of the files (scattered in multiple directories), then re-ran and it was fine.
We don't have a "make clean" option for building gradeables -- I've been meaning to add that.  It would be good to track down what isn't automatically getting refreshed.

**Comment by MasterOdin** [comment]
If the way you're checking is via the web UI, then it's connected to the
file loaded via that model, which is the build_*.json

**Comment by bmcutler** [comment]
may include permissions issues when switching from sample configuration (hwcron can access) to private course repo configuration.

**Comment by bmcutler** [comment]
Will reopen if still a problem.
