### ISSUE TITLE
git (or other vcs) team repos

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1422]
with team creation the timing will be weird here...  

If all the teams are made (don't necessarily need all members confirmed)...  then calling generate_repos.py with a specific gradeable (note: the repo name doesn't normally have to be the same as a gradeable id, and we want that to continue), but if it is a team repo/team gradeable then we need to know the gradeable_id.  Then we look up the team names in the database.

In order to have access to a team repo, you need to have accepted an invite to that team.

should display full path to team repo on the "manage team" page.

It might be nice if there was a cron job to generate repos for teams, so when a new team was formed, that repo was created automatically (without the instructor or root needing to run the script explicitly).  caution on this though!

**Comment by MasterOdin** [comment]
How are team IDs determined for a given submission?

Primarily, for this, we need to know if a gradeable is done via team or individual and if team, who is on a given team. All of this requires opening a course DB connection.

**Comment by bmcutler** [comment]
whether an assignment is or is not a team assignment is stored with the gradeable (and cannot be changed after initial creation).
team ids are assigned when the first user creates the team (and is currently a combo of that users user_id and a number, so it is unique)
We're already opening a db connection to get the list of users who need repos for non team assignments.

In case it wasn't clear from my first post...  i think we'd still like to allow generation of individual repos without tying it to a specific gradeable (that may or may not exist yet).  a optional arg to the script would tie it to a gradeable and deal with teams.

**Comment by MasterOdin** [comment]
We're opening a connection to the overlord DB, we'll need to open a second to the course. 

What do you mean by generation of repos without tying to a gradeable? Do we not currently handle that?

**Comment by bmcutler** [comment]
Correct, want to maintain the option to use it like we do now, without specifying an existing gradeable or requiring that repo name == gradeable name.

But there is an option to specify an existing gradeable, and if that is a team gradeable, then ...

**Comment by bmcutler** [comment]
Also, we have a customer for team gradeable w/ repos.  @sep2112 will use it for 2 projects if its ready.
