### ISSUE TITLE
add user error (already exists in the master db?)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1424]
I'm getting the "frog robot" when I try to add a new user (it worked fine for some users, not sure what's different about this one)  Looking in the logs, other instructors have had the same error (pasted below).

Maybe this student is in multiple courses?

----------

14:29:41 09/04/2017 - FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/Database.php (Line 116) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);

Message:
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "courses_users_pkey"
DETAIL:  Key (semester, course, user_id)=(XXXX, XXXX, XXXX) already exists.

Strack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueriesPostgresql.php(99): app\libraries\Database->query('
INSERT INTO courses_users (semester, course, user_id, user_group, registration_section, manual_registration) 
VALUES (?,?,?,?,?,?)', Array)
#1 /usr/local/submitty/site/app/controllers/admin/UsersController.php(149): app\libraries\database\DatabaseQueriesPostgresql->insertCourseUser(app\models\User, 'XXXX', 'XXXX')
#2 /usr/local/submitty/site/app/controllers/admin/UsersController.php(20): app\controllers\admin\UsersController->updateUser('students')
#3 /usr/local/submitty/site/app/controllers/AdminController.php(52): app\controllers\admin\UsersController->run()
#4 /usr/local/submitty/site/public/index.php(221): app\controllers\AdminController->run()
Extra Details:
	query: 
INSERT INTO courses_users (semester, course, user_id, user_group, registration_section, manual_registration) 
VALUES (?,?,?,?,?,?)
	parameters:
		XXXX
		XXXX
		XXXX
		4
		
		true

**Comment by pbailie** [comment]
> Maybe this student is in multiple courses?

The error is a database primary key violation.  Primary keys are used to identify/enforce unique records.  Here, the primary key is the semester, course, and user id columns.  That is, every user_id with semester and course all _combined_ is a uniquely identifiable record, so a student being in multiple courses shouldn't trigger this error.

Was this user already in the system via auto-feed...?  That is one possibility to trigger a primary key violation.

**Comment by bmcutler** [comment]
Has this been fixed?  Can we close this?
