### ISSUE TITLE
Redo/refactor Generate CSV report to use new code in Generate Grade Summaries

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1427]
330 students, 10 lab sections, 4 gradeables (not much data in them yet)

@masterodin, @holzbh maybe this is the same issue as grade summaries and will be solved with Matt's rewrite?

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/submitty/site/app/libraries/Database.php on line 99
--

1 | 0.0000 | 398032 | {main}( ) | .../index.php:0
2 | 0.0502 | 558584 | app\controllers\AdminController->run( ) | .../index.php:221
3 | 0.0502 | 559296 | app\controllers\admin\ReportController->run( ) | .../AdminController.php:52
4 | 0.0502 | 559296 | app\controllers\admin\ReportController->generateCSVReport( ) | .../ReportController.php:24
5 | 2.8911 | 65765080 | app\models\LateDaysCalculation->__construct( ) | .../ReportController.php:48
6 | 2.8912 | 65765080 | app\libraries\database\DatabaseQueriesPostgresql->getLateDayInformation( ) | .../LateDaysCalculation.php:26
7 | 2.8912 | 65765080 | app\libraries\Database->query( ) | .../DatabaseQueriesPostgresql.php:614
8 | 3.3426 | 65776448 | fetchAll ( ) | .../Database.php:99

**Comment by MasterOdin** [comment]
How big of a xlsx or csv did you try uploading just so I can test against a similarly sized one to make sure this is fixed.

The problem is that we load the entire file into memory and then go through it line by line, which obviously topples over if the file is too large. Rewriting it to use a [SplFileObject](http://php.net/manual/en/class.splfileobject.php) to load the file and then read it line by line operating on only a fraction of the memory at once would fix this (right now we use file()).

**Comment by bmcutler** [comment]
I'm not uploading, I'm trying to export the csv of grades.  (I wanted to download the student names since printing lab checksheets is currently broken).

**Comment by MasterOdin** [comment]
Oh, whoops, yeah, it's the same issue as with rainbow grades (trying to load all gradeables into memory at once).

**Comment by MasterOdin** [comment]
So my approach to this problem would probably be something like turn the [generateGradeSummaries](https://github.com/Submitty/Submitty/blob/master/site/app/controllers/admin/ReportController.php#L117-L227) function into a generic one that takes in a Callable.

Then in the generateGradeSummaries/generateCSV, you provide your lambda function.

For generateGradeSummaries, I think it'd be something like:
```
$base_path = FileUtils::joinPaths($this->core->getConfig()->getCoursePath(), 'reports', 'all_grades');
$func = function($user) use ($base_path) {
    file_put_contents(FileUtils::joinPaths($base_path, $user['user_id'].'_summary.json'), FileUtils::encodeJson($user));
}
```

and then replace both lines of the form:
```file_put_contents(FileUtils::joinPaths($base_path, $current_user.'_summary.json'), FileUtils::encodeJson($user));```
in the generic function with a call to `$callable($user);`

For the CSV, we can probably just use [file_put_contents](http://php.net/manual/en/function.file-put-contents.php) if we wanted to write the file to the server else pass in an array by reference in the anynmous function that you append each string joined together line in and then at the completion of the generic function output the download link to the user.

**Comment by pbailie** [comment]
The current CSV generation code creates column headers that consist of each gradeable's database ID and that gradeable's max score.  I do not see gradeables' max scores as data points collected by `ReportController::generateGradeSummaries()`, nor do these data points appear to be consistently recorded in the database (e.g. an electronic gradeable's max score is the summation of all `testcase` scores in its JSON file config).

For efficiency, I am not going to preserve the max scores in CSV headers.

**Comment by MasterOdin** [comment]
We'd have to scan the config.json file to get the autograder max score. The TA Grading Score should be available via iterating through the gradable components, if not a top level function. I'm fine with not having the max score, and I'm not sure that's a huge loss. We can always bring it back if there's demand.

**Comment by pbailie** [comment]
I had spoken with Dave G about it -- his opinion was that the max score was trivial information as instructors should intuitively know the scoring they create for their own curriculum.
