### ISSUE TITLE
Rubric with no items, pressing "+ rubric item" does not work

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1429]

**Comment by bmcutler** [comment]
To reproduce:
create a new gradeable, specify "no" ta grading.  save.
then edit the gradeable, switch to "yes" ta grading.  You will have no rubric items for the gradeable, and pressing +rubric doesn't work.

If you say "yes" initially, it will insert a default first rubric item automatically.

Requested behavior: 
Always starting with no rubric items is more intuitive.  let's never have a default rubric item.
Make sure this doesn't cause any problems.

**Comment by MarisaPLee** [comment]
I was unable to reproduce the issue. To add a new rubric item we look at the number of the last rubric item that there is, we don't check for if there is not any rubric items. To not have a default first rubric item would require refactoring the code.

**Comment by bmcutler** [comment]
I believe this is fixed.  Will reopen if necessary.
