### ISSUE TITLE
ta grading details page fails to load if no valid sections/users in sections

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1442]
with one a single user in the course, in the null section, the page did not load, errors about grading component (sorry I did not copy-paste them).  perhaps its a divide by zero error.

make sure we aren't requiring/assuming 1 or 2 students in every section in order to compute an average/stddev in order to view the page.

**Comment by xprilion** [comment]
Hey @bmcutler can you please suggest a few steps to replicate the issue?

**Comment by bmcutler** [comment]
will reopen if still a bug
