### ISSUE TITLE
file browser looks wacky on firefox (at least on Mac)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1451]
same student looks fine on chrome
see image
<img width="743" alt="wacky_filebrowser" src="https://user-images.githubusercontent.com/5871417/30297264-2eb0f874-9715-11e7-9856-014a361483c0.png">

**Comment by rudhman** [comment]
I am not getting the same results. It looks normal for me.

**Comment by CouleeApps** [comment]
This is because all the <div>s are `float: left`;
