### ISSUE TITLE
upload peer grading "assignments"/matchings

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1456]
Instead of the random assignment/matching, allow the instructor to upload a csv (design reasonable format) that matches each student in the class with n other students for peer grading.  

feature request from @holzbh

**Comment by ChameeraD** [comment]
HI, How can I start contributing on this ?

**Comment by chikamsoachu** [comment]
I think this is a good idea byt  for me to work on this i would like to know how the teacher would specify the students, would it be by name,username  ,student  ID etc. i would prefer to add a graphical interface so as to make the work faster for large amount of students

**Comment by sarthak77** [comment]
Hey can someone suggest some issues for beginners to get familiar with the code
