### ISSUE TITLE
"deadline" doesn't make sense for test grading

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1462]
The due date should automatically be set to the date graders can begin grading?  (but this is weird too, since we might start grading -- and need access to grading, before all items are uploaded)

Workaround is to just reset the dates after all items have been uploaded so no one is marked "late"

**Comment by bmcutler** [comment]
if students cannot upload to the assignment, there should be no due date or submission open date (these fields should both be NULL?)

**Comment by KevinMackenzie** [comment]
For assignments where students don't upload, we could set the submission date and TA beta testing date equal to the manual grading date and set the due date equal to the grades released date.  Then, the date consistency validation would need to recognize that this is the case so it doesn't give the user an error.  

Note: for the new create/edit gradeable UI to save automagically, some extra information would need to be sent in the each request so the server doesn't reject these dates.
