### ISSUE TITLE
"Central" DB that knows all users & all courses (renamed issue)

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#147]
A single relational DB would ensure greater data consistency, and reduce the chances of data anomalies.

**Comment by MasterOdin** [comment]
Need to add a __DB_PREFIX__ flag to maintain courses are using separate tables still while in same DB. For postgresql, this prefix should specify which schema we use (with one schema per class)

**Comment by bmcutler** [comment]
Matt and I had a long discussion about this today, first agreeing that it would be good to switch to a single database, but then both (I think) deciding that separate databases per class per semester would be good.  Decision is not final.  Further discussion is invited.

Advantages of keeping separate databases per class per semester:
S1. It's easy to archive or relocate or discard all data for a single course.  If it was all one big database, this would be messy.  We could probably decide to purge the entire database (after backup/archive of course) during the winter semester break or over the summer.  But if we have even 1 course that needs to delay grades and preserve the data, purging the other courses will be blocked or picking through the database would be messy.
S2. speed of database accesses for your single course only depend on the size of that course.  It won't be slower if there are other courses that are huge or lots of 10 year old courses on the system.
S3. debugging a problem in 1 course, where we need to manually examine tables, will be much easier if all of the data is related to that course.  Also, the sequences/indices/counters will start at 1 for rubrics/tests/students/etc for each course.  Small numbers are easier to work with manually.
S4. System upgrades with new features that mandate changes to the schema (tables/columns) can be rolled out during semester break.  Or even per database (if courses overlap the rollout).  Things are much messier with a mega database with past courses.  Backwards compatibility is good, except when it blocks better important design improvements.

Advantages of going to a single merged database:
M1. If we want an interface where a user logs in without specifying the semester or course or whether they are a student (only having submission access) or a TA (having both submission & grading access), if we had a single database, we could generate a list of things they have access to.  This top level "menu" is what Blackboard LMS provides (and other systems).   However, most of our students and most of our TAs will only be interacting with 1 course on the system for the current term.  And most of them can bookmark the exact URL with course & semester embedded.  A top level menu page is then unnecessary (and frankly an annoying extra step on LMS).
M2. Sysadmins don't need to make new databases each term for each course

**Comment by bmcutler** [comment]
At a meeting earlier this semester we all pretty much agreed that the advantages of individual databases "win".

**Comment by MasterOdin** [comment]
So I was giving this some thought and have a proposed design for this that might work for this.

Design would be:
```
users
courses
user_course (links users to courses)
sessions
```

and then all other tables would be prefixed with `${SEMESTER}_${COURSE}_` which is used to maintain uniqueness between courses and makes it easy to remove old courses. This would simplify adding users and knowing what courses a user has access to (so we could easily make a "semester/course" landing page if they are omitted from the url). Additionally, it would mean that a student would only need to login once per course.
