### ISSUE TITLE
Bug with config having only one part

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1471]
Doesn't make a "part1" folder.  Building this config should be an error or a warning.

**Comment by MasterOdin** [comment]
Right now, this feature only works if all the parts involve compilation.

This needs to be rewritten such that run the clean folders over `TMP_SUBMISSION/submission` folder and (if VCS) `TMP_SUBMISSION/checkout` folder to delete the files. This should be done before the compilation step.
