### ISSUE TITLE
Add Names to Bulk Upload Suggestion

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1482]
This is a feature request:

After doing a bunch of Bulk Upload work, I've noticed that since we have a lot of students with questionable handwriting, preferred names, hyphenated last names they don't hyphenate, etc. that sometimes I have to do a lot of guesswork or have a second tab open on the Students page to search around in.

If the suggestions that are automatically made as I type could include Preferred+Last Name that would be convenient. Sometimes students don't use the Preferred name that we have, so having both First AND Preferred would be even better, but that might eat up a lot of real estate.

**Comment by bmcutler** [comment]
closed weeks ago
