### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by ishaq** [Submitty/Submitty#1492]
At the very least it should have keyboard shortcuts for:

1. Next/Previous submssion
2. Rubric Items e.g. I should be able to press "1" to mark off rubric Item 1

I am attaching keyboard shortcut map of gradscope, might come in handy.

![grading_shortcuts](https://user-images.githubusercontent.com/75963/30567504-b534afe2-9c9e-11e7-9641-3355170c2b00.jpg)

**Comment by CouleeApps** [comment]
Planning to do this
