### ISSUE TITLE
Make header collapsible

### ISSUE THREAD

**Issue by ishaq** [Submitty/Submitty#1493]
[ image redacted -- contains student information]

please see the image above, it should be collapsible. Dragging a panel on top of it does not help since when you go to the next submission, the panel goes under the header.

**Comment by bmcutler** [comment]
I think it will be simpler to just make sure the panel stay on top when you move to the next student. 

Also, let's make sure the navigation bar (with arrows) stays on top.  Maybe relocate it.  (design discussion needed)

**Comment by bmcutler** [comment]
PR #1564 partially addresses this...
It works on Mac Firefox, but does not work on Mac Chrome.
Please test on more platforms.

**Comment by andrewaikens87** [comment]
It seems to work on Chrome for Linux (Ubuntu). I will investigate the Mac chrome issue.

**Comment by MasterOdin** [comment]
More important than saying "It works on Mac Chrome" is listing the version numbers of the web browsers you use as they should be very cross-platform in terms of what works and what doesn't. Googling "negative z-index chrome" showed several SO posts on why Chrome and Firefox behave differently in this case, but I suspect a newer version of chrome may have changed this.

**Comment by andrewaikens87** [comment]
I have tested on Linux Chrome and Firefox, I am going to set up to test on my Mac. All indexes are positive on the TA grading page now. Will look into making the grading_toolbar moveable once this issue is resolved.
