### ISSUE TITLE
Mark Issues

### ISSUE THREAD

**Issue by AndrewMRPI** [Submitty/Submitty#1500]
- [ ] Readd components swaps
- [x] Make marks button bigger and readd the next button.
- [x] Fix overwrite grader
- [x] Ghost bust ghost marks
- [x] Ticket Race conditions / marks clobber marks if both added at same time
- [x] Race condition when 2 TAs grade some student 
- [ ] Make rubric more like autogarding rubric
- [x] Fix making a new mark and immediately giving it someone doesn't.
- [x] Add publish in database.
- [ ] Add Delete components 
- [x] Add Delete marks

**Comment by bmcutler** [comment]
notes for "publish":  This a boolean flag to be added to each mark in the database gradeable_component_mark table.   By default it is false.  It is an additional checkbox on the instructor view create/edit gradeable.   When a students grade is prepared for their viewing, normally only marks that were selected for them are included.  But when the publish bit is true, the details (pts & message) of that mark are also included in the student display.

**Comment by bmcutler** [comment]
remaining items in issue #1954
