### ISSUE TITLE
teams that exist across multiple gradeables

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1508]
Long term:  Might want to have teams of students that persist across multiple gradeables.

Implementation ideas:
a) students need to reform teams for every assignment
b) instructor can export teams as a .csv from the first gradeable and upload the .csv of team assignments to the second gradeable
c) teams can be shared across multiple gradeables

Advantage of option c:  Team repos can be shared across gradeables.

**Comment by tushargr** [comment]
@bmcutler  Can you tell me fields that are required in teams csv file. And do we need popup form for importing csv file on grading details page considering "Import Teams" button will be on top right on grading details page. The popup form will display when "Import Teams" button is clicked.

**Comment by bmcutler** [comment]
Revised Design Proposal:


Part 1: Team Sharing between gradeables

In "Create new Gradeable", when asked if this is a team assignment, there is an option to "use teams from previous gradeable", and a drop down menu with the choices of all existing gradeables that use teams.  If this is selected, then yes all teams and team ids for these gradeables are shared.  Once a gradeable is created, you cannot change the sharing of teams.   

Only a few things cannot be changed after making a gradeable:  1) gradeable id, 2) gradeable type (electronic upload, checkpoint, numeric/text), 3) is it a team assignment, and now 4) are the teams shared with another gradeable? which gradeable?

When teams are shared, they use the same team id.   This will allow us to share repositories across gradeables.  When a team is edited in one gradeable, the team will be changed for all gradeables sharing that team.  Maybe only the original gradeable allows editing of team contents?  Or maybe you can edit in any one, but it changes everywhere?


Part 2: Export/Import team members

This is basically what you have already implemented, but let's *not* re-use the team ids.  When you import teams, you generate new/unique ids for each team.  Teams can be edited by students or instructor after they are imported, just like teams formed by students or by the instructor one at a time.  

How does the database change?  We'll need to store the gradeable links for team id sharing somewhere.  Perhaps just add a "parent gradeable for team sharing" to the gradeable table?  @MasterOdin do you have a comment/suggestion?


When deleting a gradeable...  just one more check.  You cannot delete a gradeable if any other gradeable is sharing teams from this gradeable.

**Comment by KevinMackenzie** [comment]
It would be a good idea to only let the original gradeable be referenced by another, so if A is the original and B uses the same teams as A, then a third gradeable C would reference A regardless of if A or B are chosen.  This would prevent annoying dependencies issues so only the original gradeable can't be deleted.

**Comment by tushargr** [comment]
Part 2 can be implemented by making changes to pull request.

For Part 1, 
We currently use gradeable_teams table to get teams for a gradeable ( using getTeamsByGradeableId() function ) which is further used for rendering preview grading page (on which teams are displayed) .
If gradeable B, C are sharing teams with original gradeable A,
I guess we will be using getTeamsByGradeableId(A) even to display preview grading page of B, C.   

Also, Consider A is the original and B uses the same teams as A, 
and instructor wants C to use same teams as B.
we have two options-
1. Store B in "parent gradeable for team sharing" column in gradeable table for gradeable C.
  Then we will have to use something like union- find algorithm for finding original gradeable.
  But this will make it easy to display "parent gradeable for team sharing" on gradeable C edit form.
2. Store A in "parent gradeable for team sharing" column in gradeable table for gradeable C. 
Then we can't display B as parent gradeable of C in gradeable edit form of C.

**Comment by bmcutler** [comment]
Let's not allow have a chain of parents.  A<-B<-C.  If C wants to share teams, it should share with A.  Only include in the dropdown list of gradeables the "original" gradeables that can be the 'parent'.

We can only delete a gradeable if no other gradeable shares teams with this gradeable (no other gradeable declares this gradeable as the 'parent').

Also, we will forbid delete of a gradeable that has one or more teams.  When a team is formed we start creating file structure, and we will forbid deletion if there are any files associated with the gradeable.

**Comment by bmcutler** [comment]
closing this as low priority
export/import teams works fine
if requested again in the future, we can help automate 
this step with a UI shortcut on gradeable creation.
