### ISSUE TITLE
XML iClicker Parser Should Use /usr/bin/env

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1513]
Right now the iClicker XML conversion script uses `/usr/bin/python3` instead of `/usr/bin/env python3`. (Unless we can't require python 3.) This will add support for people who have Python in other locations such as `/opt`

Additionally, if python3 is not present on the system, then a "file or directory does not exist" error is produced, however it's hard to tell this is actually referring to the interpreter and not the script. (Occurred on a modern Mac that didn't have python3). Would be nice if we could catch this before launching the script, and at least give a more descriptive error.

While I'm at it, need to make sure Rainbow Grades isn't generating the "Extra Late Day Earned At..." note if the corresponding json field isn't present.

**Comment by holzbh** [comment]
Addendum: RainbowGrades/parsexml.py needs u+x

**Comment by holzbh** [comment]
This should still be updated but #1540 just invokes python now in the Makefile. That may cause problems if the "python" command is pointing to 2.7 instead of 3.x...

**Comment by holzbh** [comment]
I forgot this existed, will revisit it.

**Comment by MasterOdin** [comment]
We should always be using `python3` everywhere (and I agree that the shebang line should always be `/usr/bin/env python3`), never just `python` or `python2` as the former is not clear as to what might run.

**Comment by holzbh** [comment]
I'll be making a pull request today to address most of this issue as well as #1660. Leaving the `python $(GRADING_DIRECTORY)/json_syntax_checker.py customization_no_comments.json` line alone in RainbowGrades/MakefileHelper for now since that's also touched by the grading/ code and I'd rather not break that in this pull.

I'm not addressing the "Hey, maybe they flat out don't have python installed" right now either, feels low priority. If someone really wants it added, they can make a new issue.
