### ISSUE TITLE
Update list of students

### ISSUE THREAD

**Issue by chris-j-tang** [Submitty/Submitty#1518]
Update list of students to be graded so that students who have dropped the class no longer show up on the list

**Comment by pbailie** [comment]
The student auto feed script I wrote for RPI automatically moves dropped students to a NULL registered section within the database.  This _effectively_ removes dropped students from the classlist within Submitty UI.  Classlist updates are scheduled for every weekday in the afternoon.

I plan to write a detailed description of this script to Submitty.org.
