### ISSUE TITLE
Do not allow grades to be submitted to electronic gradeables with no submission

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1541]
It appears that you cannot expand the rubric if there is no submission...  but there is a sideways way to get a grade entered.

If you're grading a specific problem, have that rubric component expanded, and click "go to next student" (and that next student has no submission), you can select marks for that rubric item and hit next and they get stored.

**Comment by scopeInfinity** [comment]
Hi  @bmcutler @LeonMontealegre , I tried reproducing it but failed.
After expanding Rubrik and going to next student with no submission gives me results as shown in Image 2.
For me rubrik closes whenever we switch to next student irrespective of submission status.

![Image1](https://user-images.githubusercontent.com/9819066/36371419-0a7bb894-1588-11e8-8ade-e4869a8cc4d6.png) 
Expanded Rubrik [Image 1]
![Image2](https://user-images.githubusercontent.com/9819066/36371423-0d227682-1588-11e8-8aad-ecd1340dc540.png)
After clicking on 'Go to Next Student'  [Image 2]

Is it fixed or am I missing something?

**Comment by bmcutler** [comment]
If a student has no submission but the TA managed to enter a grade (not sure how, but this happened recently), the student will get an error when they try to enter that gradeable.  

FATAL ERROR
Error (Code: 0) thrown in /usr/local/submitty/site/app/views/AutoGradingView.php (Line 621) by:
       $totalPointsEarned = $current->getNonHiddenTotal() + $current->getHiddenTotal() + $totalInstructorPointsEarned;


Message:
Call to a member function getNonHiddenTotal() on null

This code (and other code getting the current version) should be wrapped with a null check (in case a ta grade gets in there somehow) and the tas should be blocked from submitted a grade with an invalid version.
