### ISSUE TITLE
Grading for unsubmitted work

### ISSUE THREAD

**Issue by chris-j-tang** [Submitty/Submitty#1547]
When a student fails to submit work, automatically set the grade to 0 instead of rendering the 'marks' rubric unusable. In turn, the student will have a grade assigned to them on Submitty instead of no grading.

(I'm  not sure if this is the best way to about this problem.)

**Comment by bmcutler** [comment]
We're working on fix to this in #1450 and #1541.  Closing as is duplicate issue.
