### ISSUE TITLE
LLVM class needs lex / yacc whitelisted

### ISSUE THREAD

**Issue by laprej** [Submitty/Submitty#1549]
[CSCI 4975/6975: A Compiler Case Study: LLVM](http://www.cs.rpi.edu/~laprej/courses/rpi-csci-4975-2017-fall.html) needs a few programs to be whitelisted.  Namely, lex/flex and yacc/bison.  Is adding the full paths to [execute.cpp](https://github.com/Submitty/Submitty/blob/master/grading/execute.cpp) all that's required?

**Comment by bmcutler** [comment]
sorry for the delay.  in PR #1551.  (& installed..)
