### ISSUE TITLE
Preferred Name Doesn't Allow Dashes

### ISSUE THREAD

**Issue by tcyrus** [Submitty/Submitty#1562]
When trying to change the Preferred First Name, It returns the message "Invalid Username. Please use only letters and spaces."

**Comment by MasterOdin** [comment]
The issue on this is that we're not using a unified interface for checking/setting preferred names. On the admin side, we have this block ([found here](https://github.com/Submitty/Submitty/blob/master/site/app/controllers/admin/UsersController.php#L124-L1333)) that handles checking of name stuff:
```
        if (!empty($_POST['user_preferred_firstname']) && trim($_POST['user_preferred_firstname']) != "") {
            $error_message .= preg_match("~^[a-zA-Z'`\-\. ]+$~", trim($_POST['user_preferred_firstname'])) ? "" : "Error in preferred first name: \"{$_POST['user_preferred_firstname']}\"<br>";
        }
```


On the student side of things, we have this block ([found here](https://github.com/Submitty/Submitty/blob/master/site/app/controllers/HomePageController.php#L60-L76)):
```
            if (ctype_alpha(str_replace(' ', '', $newName)) === true) {
                // snipped
            }
            else
            {
                $this->core->addErrorMessage("Invalid Username. Please use only letters and spaces.");
            }
```

We should most likely be using that regular expression in both places (the simplest fix) to ensure that we're allowed the same set in both spots. Implementation of this would be just add a static method to Users model that is something like:

```
static public function checkPreferredName($preferred_name) {
    return preg_match("~^[a-zA-Z'`\-\. ]+$~", $preferred_name) === 1;
``` 

and then just call that in both places so we only have to worry about that regex once.

**Comment by pbailie** [comment]
I recall seeing the preferred_name validation being a different kind of check... but left it alone in favor of other priorities.  I'm actually glad to see it getting attention.

**Comment by bmcutler** [comment]
(since this issue is still open.... )
@pbailie One more quick change.  Can you please allow parentheses in the preferred name.  
Thanks
