### ISSUE TITLE
Comparison to similar projects

### ISSUE THREAD

**Issue by wonga6** [Submitty/Submitty#157]
Comparing the RCOS open source homework server to other open source and commercial homework submission systems / automated run&testing / automated grading / TA grading environments. What do they do similar and different?

**Comment by bmcutler** [comment]
Adding Eric, Joe, Ben.  (probably can't assign all 3 of you)

**Comment by Mijumaru3** [comment]
Some similar ones we've looked at: UMD - Marmoset Project, Web-Cat.
