### ISSUE TITLE
On a student's grading screen I cannot click any buttons on the Navigation bar

### ISSUE THREAD

**Issue by Phansa** [Submitty/Submitty#1572]
As of this week when I am on a student's assignment page the area that has the logout button + part that says Submitty->Principles of Software -> HW3 Grading -> Student Index is all unclickable. I can only navigate using the buttons on the top left pane with the home button / right and left arrow buttons.

![submittyscreen](https://user-images.githubusercontent.com/16921040/31449295-84c1a8dc-ae74-11e7-9768-a8cdebe9bc67.png)

If I go back 1 screen those links all work properly. 
![submittyscreen2](https://user-images.githubusercontent.com/16921040/31449429-e6e1a346-ae74-11e7-9062-954bcf793425.png)

Also this down arrow picture is not being loaded on the student's assignment page which be causing this issue - 
![consoleerror](https://user-images.githubusercontent.com/16921040/31449594-4dbac44e-ae75-11e7-8129-d4694f2de06c.png)

![consoleerror](https://user-images.githubusercontent.com/16921040/31449728-b01a317e-ae75-11e7-8440-d1e8b08aa69a.png)

I am using Google Chrome / Windows 10 and I think steps to reproduce this bug would be to log in as a grader and go an individual's assignment page and try to click the nav bar links / check the console to see if the down_arrow picture loads.

**Comment by bmcutler** [comment]
duplicate issue #1505
