### ISSUE TITLE
Team Documentation

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1573]
Add two pages to submitty.org with instructions (one for students, the other for instructors) on how to use teams.  Include screenshots.

Also, some of the information on vcs/git should move to this page and/or move to a vcs page under instructor.  (Currently it's under sysadmin http://submitty.org/sysadmin/git)

**Comment by AnkitKhatri55555** [comment]
Hey,@bm-cutler, I want to work on this issue.Please assign me this issue.

**Comment by tcyrus** [comment]
@AnkitKhatri55555, see [`CONTRIBUTING.md`](https://github.com/Submitty/Submitty/blob/master/CONTRIBUTING.md)
