### ISSUE TITLE
iClicker Documentation Incomplete

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1580]
Moved issue from:
https://github.com/Submitty/submitty.github.io/issues/17

iClicker documentation is missing the "earned_late_days" field, needs to be added. I'll get on it shortly.

Appending to this issue, the "warning" field incorrectly says to use a string for the "value" field instead of an integer.

**Comment by holzbh** [comment]
Looks like the part about the `warning` block's `value` field can be ignored since that page's documentation isn't using quite as rigid a structure for the explanation, and no longer has the problem described in this issue.
