### ISSUE TITLE
Grader List Ignores Permissions

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1583]
On the Grading Status page (where I can see statistics for graded questions and there's the Grading Details and Download Zip of All Students buttons), for an electronic gradeable with Full Access Graders as the minimum permission level and Registration Section as the grading allocation, I see all grader names listed under "graders".

Not sure if the problem is cosmetic and only on this page, or if limited access graders can actually grade when they shouldn't. Looks bad either way.

**Comment by saxocellphone** [comment]
How does one change the minimum permission level? I can't seem to find the setting.

**Comment by holzbh** [comment]
Under the Edit Gradable interface, near the bottom (above to the Registration/Rotation section radio buttons) is a dropdown with the minimum permission level:

![image](https://user-images.githubusercontent.com/26691043/39270438-137d3874-48a4-11e8-9d77-6c1b4e04404b.png)

**Comment by saxocellphone** [comment]
I did some testing, it seems like it's only a minor cosmetic fix
