### ISSUE TITLE
Unreferenced Runner-Generated Files

### ISSUE THREAD

**Issue by duncjo** [Submitty/Submitty#1591]
I encountered unexpected behavior when trying to write a suite of tests for an assignment in which the students' program is to validate user input and, on valid input, generate an output file "myfile.txt".  My suite of tests was:

1. Run the program on valid input and test STDOUT and the contents of "myfile.txt" against expected results.
2. Run the program on invalid input followed by valid input and test STDOUT and STDERR (but ignore the contents of "myfile.txt").

What I found was that if "myfile.txt" is not referenced as an "actual_file" in the second test, then the first test validation uses the "myfile.txt" from the second test run.  The following sequence of events appears to be causing this unexpected (to me) behavior:

- The first test run generates "myfile.txt" and, because it is referenced as an "actual_file," it is renamed to "test01_myfile.txt" before validation.
- The second test run also generates "myfile.txt" but, because it is not referenced as an "actual_file", it is left as "myfile.txt".
- Then in the first test validation phase, the code in ``main_validator.cpp`` which trys to find a file match for "myfile.txt" (the "actual_file" in the first test) ends up picking the file named "myfile.txt" instead of the one named "test01_myfile.txt".

I've worked around it for now by adding "myfile.txt" as an "actual_file" to the second test (even though I don't care what it contains at that point).  This causes it to be renamed to "test02_myfile.txt" and then in the first test validation phase, the correct "test01_myfile.txt" is selected.

**Comment by emaicus** [comment]
Solved by the move to testcase isolation.
