### ISSUE TITLE
Finer-Grained Control of Autograder Point Assignment

### ISSUE THREAD

**Issue by duncjo** [Submitty/Submitty#1592]
While points can currently be allocated on a per-test basis, it does not seem to be possible to control how many of those points should be determined by the various validation checks for that test.

As an example, A test on a single stream of input may contain three validation parts (checking STDOUT, STDERR, and a program-generated output file).  Currently, one can assign the entire test a number of points (say 4) but the three validation parts appear to have equal weight in determining how many of those points are earned.  It would be helpful to be able to specify that the STDOUT validation check is worth 1 point, STDERR is worth 1 point, and the generated file is worth 2 points.

**Comment by bmcutler** [comment]
Yes, you can do exactly this.  It's the "deduction" option.
http://submitty.org/instructor/assignment_configuration

By default, the validation checks are equal weight, but if in your case you would specify that the generated file is deduction=0.5, and STDOUT & STDERR are 0.25 each.  The deductions must add up to at least 1.0.  Basically this encodes that if the check fails (or is a partial fail) this is the fraction of the total test points will be subtracted.  We always round down  and have no partial points.

I frequently use 1.0 deduction to the correct output check (which students can earn partial credit if some lines of output are correct, and some are incorrect).   And 0.5 deduction for memory-error/memory-leak free execution (tested via dr memory).   Students earn no points if they don't have at least some correct output (even if it is memory error free).  Students earn half credit if their output is perfect but they have memory leaks.

Here's an example of the syntax:
https://github.com/Submitty/Tutorial/blob/master/examples/08_memory_debugging/config/config.json

I'll leave this issue open until we make a more complex example and improve the documentation.

**Comment by bmcutler** [comment]
Also...  you can view the "complete" config file created by the BUILD_<COURSENAME>.sh script, which fills in all of the defaults you did not specify, to see more options.

/var/local/submitty/courses/<SEMESTER>/<COURSE>/config/complete_config/complete_config_<GRADEABLE>.json
