### ISSUE TITLE
Stricter on Team Lock Date

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1595]
Requests:

Let's display a history of team membership on the instructors view when they hit the pencil icon for the team.  Information requested:  team formed on date, (perhaps) date that each member joined, date of last edit.

Let's display more warning messages (in orange or red) when members have been invited by not yet accepted.  E.g., add something like: "Your team is not finalized until all pending invitations are accepted.  Invitations must be accepted by the team lock date: <INSERT DATE>".

Let's make sure the team formation buttons are well color coded.  It should be blue if you haven't formed or joined a team or if you have unaccepted pending invitations.  It should be red if the team lock date has passed and any of the above.  It should be white if you are on a team and your team has no pending invitations.

Pending invitations must be accepted before the team lock date.   Let's not delete pending invitations on the team lock date, but rather let's prevent invitations from being accepted after the team lock date.

Teams of 1 can still be created after the team lock date, but the instructor can see when the team was formed by clicking on the pencil icon (above).

**Comment by James-M-Anderson** [comment]
Should we add team formation date, last edit date, and join date for each member to the database or should we pull this from the team history json file that we already have?

**Comment by bmcutler** [comment]
No changes to the database.  Just pull this from the history json file.

**Comment by tushargr** [comment]
@bmcutler wouldn't it be better to have complete history of addition/removal of team member rather than formation date and last edit date.
There could be 3 columns : 1st showing user id, 2nd with action (addition or removal) and 3rd with date time.
This history will itself give team formation and last edit date
