### ISSUE TITLE
[BUG] Python parser not lexing dictionary declarations properly.

### ISSUE THREAD

**Issue by emmetthitz** [Submitty/Submitty#1613]
![image](https://user-images.githubusercontent.com/6633471/32924857-b3a5c692-cb0c-11e7-98d3-e91d7f86ca7b.png)

The python parser reports the number of dictionaries incorrectly when using 
```
x={**a,**b,**c}
```
syntax to merge dictionaries - it even throws to STDERR. I looked for an upstream project (Lichen?) to file an issue with, since this would be on them, but couldn't find anything.

**Comment by chameco** [comment]
Issue upstream in [language-python](https://hackage.haskell.org/package/language-python) (not updated for newer versions of Python 3.x). Evaluating alternative Python parser backends, but for now at least this should fail more gracefully.
