### ISSUE TITLE
Add a release date to the TA data entry for each lab (& homework & other things)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#162]
Instructor can set up entire semester worth of labs, but TAs won't accidentally enter this weeks labs in a future week.

**Comment by MasterOdin** [comment]
So you want to add a "Due Date" or something when creating labs and tests and then display that info in the tab header?

So you'd see:
Lab 1 (9/2), Lab 2 (9/9), Lab 3 (9/15), ... on the view (don't display year unless the year on the first lab is different than the year of the last lab).

**Comment by bmcutler** [comment]
Sure, labeling the tab would be a nice feature.  But more important, don't let a TA add grades for a lab that's happening in the future.

**Comment by bmcutler** [comment]
@MasterOdin Can this be closed?

**Comment by MasterOdin** [comment]
We have not added "due dates" to labs and tests yet so no? Unless you don't think this is something that should be implemented?

**Comment by bmcutler** [comment]
Ok, I was confusing "Other" which has a due date.  Is due date the date it opens for TAs to enter grades?  Or were you just using the date to sort the gradeable things?

It might be more clear to call it a "grading opens" or "grading available" (grading available might sound like grades available to students).

Yes, we'd like a date for labs & tests/quizzes too.
