### ISSUE TITLE
Show commit hash for git assignments

### ISSUE THREAD

**Issue by ferria** [Submitty/Submitty#1626]
Feature request: it would be nice to be able to see the commit hash for the current submission after clicking "Grade My Repository" to submit an assignment.  This would help make sure that the latest commit has been submitted.

**Comment by firedranzer** [comment]
@ferria I want to work on this issue. Please show me relevant files and required changes to work with.Thanks.

**Comment by bmcutler** [comment]
General note to those interested in Google Summer of Code 2018: We
will not be adding folks to the Github Submitty organization until
they are accepted into the GSOC program.  And similarly, we will not
be formally assigning issues through Github to interested applicants.
You may ask questions or add information to open issues.  And you may
submit a pull request from your own fork of the repository if you
think you fully understand the issue and have a complete solution.

Note that the author of an issue may not be a developer, and may not know 
how to solve the problem.  

I've updated this page with suggestions for new developers:
http://submitty.org/developer/
