### ISSUE TITLE
Forum Implementation

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#1632]
Design has been discussed offline.

Current Features:

- View Thread

- Create Thread

- Respond to thread (post)

- Create and remove announcements

- Upload an image attachment to post

- Teaching staff being able to delete/hide posts

- Posting anonymously

Features to be added:

- reply to specific post in a thread 

- edit your comment

- delete your comment

- make a thread an announcement after being posted

- inline image attachments

- fixed width font for code when replying or creating a thread

- multiple image attachments per post

- self pinning threads

- thread categories and sorting by them

- make hyperlinks work inside of post

- instructor/ta posts should be visually different (different background?)

**Comment by bmcutler** [comment]
made 2 new issues...   #1678 and #1677
