### ISSUE TITLE
Textbox for student data entry / Short answer questions

### ISSUE THREAD

**Issue by wonga6** [Submitty/Submitty#164]
No doing a full grading but just have students answer a question, like "what is your iClicker ID"?

**Comment by bmcutler** [comment]
Alternatively, parsing this data from a file upload (e.g., a README.txt, Issue #163 ) is a possibility.
(But rather cumbersome.)

Also, don't want to re-invent/re-implement the wheel with all manner of checkbox/radio button input!

**Comment by Mijumaru3** [comment]
So we would look to have a place on the website where they can enter this information?
