### ISSUE TITLE
Generate Grade Summaries progressively slower

### ISSUE THREAD

**Issue by maksimt** [Submitty/Submitty#1647]
I noticed that generate grade summaries is essentially a double for-loop over gradables and students.

I wonder whether a simple fix might be to set

` $size_of_gradeable_id_chunks = 5;`

To larger values. That way it's up to the database to handle larger queries in parallel/efficiently rather than the submitty server's job.

Another option is to store last-touched dates on a per-gradable basis in the database, and only re-build gradables that have been touched since the last time summaries have been built. Since gradables are typically only touched in a time-window of constant size, effectively this would make the operation be O(|S|) instead of O(|S| |G|). The downside is the cost of storing and accessing the pre-computed gradables; from the outside it's unclear what the best option is given your architecture.

**Comment by bmcutler** [comment]
Known issue.
The small chunk thing was a hack for very large classes else we run out of memory.
This code is badly in need of an overhaul/refactor.  It is actually high priority.

**Comment by MasterOdin** [comment]
This was fixed by #1843
