### ISSUE TITLE
RainbowGrades iclicker should support multiple files per lecture

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#1660]
Right now the iclicker configuration in customization.json is pretty rigid.

A user should be able to configure two or more files for one "iclicker" lecture by specifying an array of filenames inside the `file:` field since multiple sessions may actually apply to one iclicker question.

This is preferable to the alternative of writing some sort of tool to mash multiple files together, though that's a possible stopgap measure.

**Comment by holzbh** [comment]
Pull request above is partial solution.

We need to change things around so each file can have a different column associated with it. It's probably better to associate questions to one or more (filename, column, answers).

@bmcutler suggested that it would be nice if the system output information about unused columns in files, and some sort of statistic since seeing like a 70% incorrect rate on a question might indicate a mistake in the customization.json

**Comment by holzbh** [comment]
Adding a note here: a commit caused the multiple method to fail because of an assert. Should be removing this assert probably, but will likely disappear in the full rework of iClicker questions anyway.

Also, can't use `./xxxx.py` because on WSL there's weird file system issues regarding permissions on any Windows-native portion of the filesystem, so we're better off explicitly invoking using `python3 xxxx.py`. Will fix that in RainbowGrades/Makefile in the PR for this issue.

**Comment by bmcutler** [comment]
Closing because we will be removing support for iclicker. 
(replaced with Submini)
