### ISSUE TITLE
Github integration?

### ISSUE THREAD

**Issue by amueller** [Submitty/Submitty#1663]
Hi.
This looks like a really cool project. I was wondering whether there is, or are plans for, integrating with github or gitlab. I'm using github classroom for my assignments, and so students submit via that platform. It would be great to directly import their submissions from there.

Thanks,
Andy

**Comment by bmcutler** [comment]
Hi @amueller 
Yes, we are working on this.  I think we've got the UI for instructors sorted out to allow specification of a general url/path for the repo.
The remaining detail is specifying username/password credentials/ssh keys (we're going to assume the repo is not public).

**Comment by MasterOdin** [comment]
Closed with #3669
