### ISSUE TITLE
Interactive visualization of AST in AnalysisTools

### ISSUE THREAD

**Issue by chameco** [Submitty/Submitty#1666]
Currently the static analysis framework can output JSON diagnostic information for both tokenization and parsing. Additionally, it can output an HTML page with embedded JavaScript in order to interactively visualize token data. It would be nice if this page also visualized the AST data output by the parser.

The currently-generated JSON should already be in a format conducive to drawing trees using D3.js.

**Comment by chameco** [comment]
https://bl.ocks.org/mbostock/4339083 is potentially useful as an example.

**Comment by chameco** [comment]
The binary used to obtain the data should be located at `/usr/local/submitty/SubmittyAnalysisTools/diagnostics` on a typical Vagrant install.

This can be run with `--help` to list options, but in brief:

    /usr/local/submitty/SubmittyAnalysisTools/diagnostics --language python file.py

where `file.py` is the Python file you would like to analyze.
This will output (to standard output, you probably want to redirect to a file) a JSON object with two fields: "tokens" and "nodes". You can safely ignore the "tokens" field; the "nodes" field is what we would like to visualize.

**Comment by thatCode-Psy** [comment]
What branch is your tool on?

**Comment by khashf** [comment]
@chameco  : I'm working on this enhancement. Could you please assign me?

**Comment by bmcutler** [comment]
documented here:
http://submitty.org/instructor/tree_tool
