### ISSUE TITLE
Use a different parsing backend for Python static analysis

### ISSUE THREAD

**Issue by chameco** [Submitty/Submitty#1673]
We currently use [language-python](https://hackage.haskell.org/package/language-python) as the backend for Python static analysis. This package is no longer actively maintained and does not support some modern Python 3 features (see #1613 ). Furthermore, this package is not included in the latest [Stackage LTS set](https://www.stackage.org/lts-10.3), preventing the project from updating and gaining access to bug-fixes and library ecosystem improvements.

This coincides with the upcoming integration of the Common AST backend, which will also require dispatch to an external tool for parsing.

**Comment by thatCode-Psy** [comment]
So is the goal to just update the package to 3.X?

**Comment by marwanatef2** [comment]
Does using the [AST](https://docs.python.org/3.8/library/ast.html#module-ast) python library instead will solve the problem?
