### ISSUE TITLE
Viewed grade status for TEAM assignments

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1689]
Related to #1449 
So it the assignment is a team assignment, there is still only one checkmark in the column indicating if the student(s) have viewed their grade.  What does this mean?  One of the team members have viewed it?  (which one?)  All of the team members?  Ideally we would know who has and who has not viewed.

**Comment by saxocellphone** [comment]
I believe we decided that the current method is sufficient during the meeting
