### ISSUE TITLE
make login page's username text field grab focus on load

### ISSUE THREAD

**Issue by slime-man** [Submitty/Submitty#1704]
when I load up submitty dot com, right now I gotta tab into my autofilled credentials, so that I can hit Enter, so that I can log in.

There's only one thing on the page at this point, it's totally appropriate for the user box to request focus.

**Comment by MasterOdin** [comment]
Can just add https://www.w3schools.com/tags/att_input_autofocus.asp to the input box.

**Comment by turing93** [comment]
Hi, I would like to work on this issue. I was going through the readme and I could not figure where to get the source of the web page in the issue. 
Any advice regarding where and how to start?

**Comment by tushargr** [comment]
@MasterOdin please review the pull request.
