### ISSUE TITLE
Resizable answer box?

### ISSUE THREAD

**Issue by laprej** [Submitty/Submitty#1705]
Hi,

When I create an electronic file gradeable can I resize the box presented to the students?  Here is my config.json file:

```
{
    "autograding" : {
	"submission_to_runner" : [ "*txt"],
	"work_to_details" : [ "*txt"]
    },
    "textboxes" : [
        {
            "label": "1. 9877 in NBO hexadecimal? [1 point]",
            "filename" : "quiz04_01.txt"
        }
    ],
    "testcases" : [
        {
            "type" : "FileCheck",
            "title" : "Review Question #1",
            "actual_file" : "quiz04_01.txt",
            "points" : 0
        }
    ]
}
```

Here's what the students see:

![screen shot 2018-02-08 at 3 47 51 pm](https://user-images.githubusercontent.com/463531/35997449-84d9d598-0ce7-11e8-83b7-4d80e12cd37e.png)

**Comment by laprej** [comment]
It occurred to me that this particular screenshot didn't really showcase my problem.  Sometimes I ask questions requiring a few short sentences.  A small input text box leads students to think I'm looking for a single-word answer.  The size of the text box does not constrain the length of their answer but I have gotten a number of students requesting I make it larger :)

**Comment by bmcutler** [comment]
Add the "rows" tag, I think that's what you want
see example:
https://github.com/Submitty/Submitty/blob/master/more_autograding_examples/paragraph_textboxes/config/config.json

(sorry, I thought you wanted the paragraph box with rows to be even bigger)
