### ISSUE TITLE
Late days for Team Assignments

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1725]
Design plan:
For a team assignment, if a team submits late, every student on the team will be charged that many late days.  If one or more members does not have enough late days, only that student(s) assignment will be status bad and their score will be auto zeroed when grade summaries are generated and when displayed with Rainbow Grades.  Students who do have available late days will receive the non zero assignment grade.

~~Excused Absense Extensions (e.g., for illness) for team assignments should be applied to the team, granting the team 1 or more days extension.~~

**Comment by bmcutler** [comment]
This may work (fingers crossed) with the revised query for generate rainbow grades & late days.  It just needs more testing.  Related to #1900 and #1846.

**Comment by bmcutler** [comment]
reported current bug:  The TA report section for a team assignment that is late needs to correctly display the # of late days used on that team assignment.  Currently it shows no late days used.

Adding @shailpatels on this.  Please work together to debug/display the correct information.

**Comment by saxocellphone** [comment]
I believe this is fixed in the ReportController with the new lateday calculation? I could be wrong though.
