### ISSUE TITLE
Postgres Error When Creating A New Course

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#1727]
Error message issued when creating a new course: 
```
psql:/usr/local/submitty/site/data/course_tables.sql:980: ERROR:  relation "attachment" does not exist
```

https://github.com/Submitty/Submitty/blob/afb0e7847870dec825c96c3056bd6bf1527e4312/site/data/course_tables.sql#L980

`course_tables.sql` does not have a definition for a table called `attachments`.  This causes the `ALTER TABLE` query on line 980 to fail.

**Comment by pbailie** [comment]
I would try to correct this, but I cannot find any information about the missing table.

**Comment by andrewaikens87** [comment]
This was part of the discussion forum. The table isn't necessary anymore as all attachments are stored on the file system and as a result you should be able to remove this line. Let me know if this works.
