### ISSUE TITLE
Vagrant 'Sample' course includes TA grades for assignments with no submission

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1732]
Our scripts to pre-populate the 'sample' course make submissions for many of the students but not all.  The scripts that pre-populate TA data should be aware of this and not enter grades for students that have no submission.
<img width="875" alt="screen shot 2018-02-15 at 2 42 54 pm" src="https://user-images.githubusercontent.com/5871417/36277365-a9aed838-125e-11e8-94d9-357661b871f9.png">

**Comment by yashjainpro** [comment]
interested in this bug how to move forward with it and interested in doing  GSOC with you
