### ISSUE TITLE
Submission timezone not honored

### ISSUE THREAD

**Issue by jgfoster** [Submitty/Submitty#1745]
Our server is set to PST and I set the submission deadline to midnight PST (GMT - 8). Yet the submission time shows as three hours later and the students are told that their submissions are late if they are after 9pm.

**Comment by RylanOC** [comment]
I'm still working on a long term fix for this issue, but a quick and dirty solution would be to modify line 98 of `site/app/models/config.php` (Which I believe will be located in `/usr/local/submitty/site/app/models` on the server) from `protected $timezone = "America/New_York";` to `protected $timezone = "America/Los_Angeles";`
