### ISSUE TITLE
Add VCS ID for users

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1747]
Right now we can only rely on using user_id for referencing git repos but this won't work if using an external git service (such as github) where a person's username for Submitty wouldn't match their github username (like me).

This should be a new field `vcs_id` that's a varchar and in the master submitty database in the users table. `vcs_id` should be modifiable by the user on their homepage.

**Comment by tushargr** [comment]
Hi I would like to work on it

**Comment by tushargr** [comment]
@MasterOdin what should be limitation for username . for eg:- in github username restrictions are -                     
Min: 1
  Max: 39
  Can contain: a-z A-Z 0-0 -
  Other: Can not start with a dash
should i implement this or consider other vcs also
