### ISSUE TITLE
Documentation for git

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1758]
Git allows you to specify a user/password in the checkout URL by doing '{username}:{password}@{git_checkout_path}' (putting 'http://' in front of the string if it's a URL). Additionally, we can add an ssh key for any user we want to hwcron so that we don't need to specify a full password (especially if using git). 

This information (and all information on VCS) should be documented under http://submitty.org/instructor/

**Comment by prestoncarman** [comment]
It would be nice to see the workflow for a student using git to submit homework. It seems the system supports submitting homework through git, but there is not documentation. We are definitely interested in using this in Fall.

**Comment by MasterOdin** [comment]
I've bumped this up to try and get this done this month as I've got a draft of it that I've just never finished up. We do support a workflow either using a Git on the same machine as Submitty (which is how we at RPI utilize it) as well as using external Git URLs (so like using Github/Gitlab/etc.). 

We do have instructions on internal git usage (http://submitty.org/sysadmin/git), but need to expand it to cover external sources, and to incorporate changes that an instructor can set a repo URL on a per course and per gradeable level.

**Comment by MasterOdin** [comment]
So we've fleshed out the documentation for Git (see [sysadmin/Setting up Git](https://submitty.org/sysadmin/git) and [instructor/Create and Edit Gradeable#Using Git](https://submitty.org/instructor/create_edit_gradeable#using-git)) as well as overhauled and generally simplified the Git system in #2293 and #1904.

I've also finally created #2741 to track another improvement we'd like to put into the system to support users that don't (or can't) use ssh keys for external resources.

@prestoncarman Please let me know if this helps clarify how to use the system, or if you'd like further information on how it might work or what might be unclear.
