### ISSUE TITLE
Give each gradeable in the logs a unique ID

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1760]
Right now, each row in autograding_logs gets a PID (which duplicates), what untrusted user is running, path to user submission which when combined can give us rows to look at, however, if we are grading the same thing multiple times in a log, it might mean that we have rows with identical versions of these 4 variables which make it hard to fully make each submission unique.

It'd be nice that whenever a job is submitted, we give it a unique ID that we can use to reference it later.

A simple way to generate a nice UUID through python3:
```
import uuid
str(uuid.uuid4().hex)
```

**Comment by bmcutler** [comment]
closed by #1776
