### ISSUE TITLE
Default number of members for a team should be 2

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1762]
Right now, when you select to use a team assignment for a new gradeable, it defaults to a team of 1 member, but when you hit submit, it requires you to set it to 2. We should just default to 2 when you initially open the pane.

**Comment by bmcutler** [comment]
I think we had a setting that would allow unlimited size teams (dunno if it was '-1' or '0' means unlimited -- not particularly intuitive).  Whoever takes this issue should also revise/document that option.  Maybe unlimited should be the default?

**Comment by han0305** [comment]
Hello, I am new to open source and I will like to contribute here.I have installed the instance of Submitty and gone through the functionalities.
Kindly,guide me on how to contribute.
Thanks.
