### ISSUE TITLE
Add stats to numeric & checkpoint ta grade pages

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1764]
Instructor request:  Display the overall average & std dev and the per component average & std dev for numeric gradeables.  Let's also do the same for checkpoint gradeables.

Proposed design: add a "View Statistics" button to the top of the data entry page for that gradeable.  When clicked, a small popup with the information appears.  Discussion welcome.

**Comment by ChameeraD** [comment]
I would like to give a try on this. Can you please guide mt through.

**Comment by tushargr** [comment]
@bmcutler what value should we take corresponding to dark and half dark color on checkpoint gradeables for computing avg and std dev.

**Comment by tushargr** [comment]
Should i take 
1 mark for dark color
0.5 mark for light color
0 for no color ?

**Comment by bmcutler** [comment]
@tushargr Yes, that's grading color scheme is documented at the top of the checkpoint data entry webpage.
