### ISSUE TITLE
How do I upload the sample submissions?

### ISSUE THREAD

**Issue by rudhman** [Submitty/Submitty#1765]
I am not able to figure out how to upload the sample submissions. Also I cannot access the database when I go to localhost:15432.

**Comment by bmcutler** [comment]
Hi @rudhman,

Please join our new Slack server to ask questions about setup/usage.
link at the bottom of this page:  http://submitty.org/developer/

When you re-ask your question there, please give a little more information about your setup.  
Did you follow the steps on this page?
http://submitty.org/developer/vm_install_using_vagrant
What step did you get stuck on?

**Comment by rudhman** [comment]
I am at the 8th step, I can access the page but can't login. It shows  
Could not login using that user id or password error. 
Also there is a "debian: VM not created. Moving on..." status on the comand line.
. Also I did the step 9 and unable to access the database at the given url (localhost:15432).

I use ubuntu 17.10 with kde plasma on a system with i5 proccessor.

**Comment by bmcutler** [comment]
Please post this information on slack
