### ISSUE TITLE
Forming Teams

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1790]
Right now, students need to know the username of another student to create and form a team.
(We intentionally do not allow list all/search/name completion because of FERPA concerns).

We'd like to let students advertise themselves as "seeking partner/team" for this gradeable.  This option should be added to the create team page.  The names & emails would appear on other students pages when they go to form teams. 

This will probably involve an addition to the database, design discussion needed.

**Comment by tushargr** [comment]
@bmcutler 
I have a design proposal-

1. Create Team Page- two buttons 'Seek Team' and 'Click to see users seeking team'
![1](https://user-images.githubusercontent.com/21223046/37142911-7b071158-22df-11e8-8d6b-e4b60170048d.png)

2. On clicking 'Seek Team' , user will be displayed with popup form for confirmation.
![2](https://user-images.githubusercontent.com/21223046/37142944-9be0fda8-22df-11e8-9426-1f4868e4b392.png)

3. on clicking button 'Click to see users seeking team' , user will be displayed a pop up form with list of users seeking team.
![3](https://user-images.githubusercontent.com/21223046/37142988-bd8b279e-22df-11e8-82b3-a8b4b88ba3a4.png)

4. On manage team page - there will be 'Click to see users seeking team' button which on clicking displays the popup with list of user seeking team.
![4](https://user-images.githubusercontent.com/21223046/37143038-edac39c2-22df-11e8-9065-478b79ae83bc.png)

**Comment by tushargr** [comment]
and when the user will be part of a team , his/her username will be removed from the list.

**Comment by tushargr** [comment]
Also when the user is not in any team and is seeking for team, we can have button 'Stop Seeking Team' button next to 'Create Team' to remove user from the list of users seeking team.
