### ISSUE TITLE
Implement CAS authentication

### ISSUE THREAD

**Issue by toshipiazza** [Submitty/Submitty#1803]
We currently have a login system in place which allows login/logout, but I think it'd be neat if we could plug directly in to the RPI CAS system. Although they don't say what the CAS system is, it _looks_ like a re-skin of JASIG CAS (judging from [this js file](https://cas-auth.rpi.edu/cas/js/cas.js)). Luckily, JASIG CAS was very pluggable in my limited usage of it a few years ago.

pros:
- logout comes for free! (https://cas-auth.rpi.edu/cas/logout)
- easier for school to reset passwords
- [JASIG CAS](https://wiki.jasig.org/display/CAS/Home) is a trusted project from MIT with an [official](https://wiki.jasig.org/display/CASC/phpCAS) php client library to work with it.

cons:
- do teachers have an account through our CAS system? If not, probably not worth it then because then we'd still need to maintain an admin login panel or sthg
- CAS does authentication, not authorization. We still need a way to identify students vs teachers/graders. I assume this already happens somewhere in the code, but it might need to be reworked if we implement this.

Also note that since JASIG CAS is an open source project, this still scales well to other schools and possibly with other deployment strategies.

**Comment by MasterOdin** [comment]
Has RPI published any documentation on how to integrate CAS into something like Submitty?

**Comment by toshipiazza** [comment]
Interaction with CAS is well known as the protocol is documented [here](https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol.html), though I do believe we at least need to ask dotCIO to add submitty to the list of valid services if their CAS supports it (i.e. if they haven't ripped support for it out).

I am skeptical though since dotCIO doesn't have any documentation on how to setup integration, and it has removed most mentions to JASIG on the webpage (just commented out)

**Comment by inlinefan** [comment]
We currently use kerberos through PAM, which allows people to use their RCS credentials OR local credentials.  This allows us to give instructors a second account that behaves like a student account for debugging/testing.  It wouldn't be a bad thing to work on, but I don't think it is an improvement on what we have.

**Comment by bmcutler** [comment]
Another potential downside of using the CAS system is that we (admins of the Submitty machine) wouldn't control expiration of the authentication.  It's nice to specify a long (possibly infinite) timeout so students working on homework over many hours don't have to re-authenticate.

**Comment by toshipiazza** [comment]
RE: specifying an infinite timeout, you can *probably* set a timeout on the CAS client plugin so that the user never gets logged out on Submitty. Since the cookie never expires, Submitty never redirects you to the CAS server for login--unless someone forces logout via CAS.
