### ISSUE TITLE
Allow Markdown for 'upload message' and 'office hours queue welcome message

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#1821]
Discussed in the meeting today. In the screenshot below for example the user would be able to use italics, bold, links, and possible other stylistic tags. The can be moderated by using HTMLPurifier, which can filter specific tags. 

![screenshot from 2018-03-21 21-00-50](https://user-images.githubusercontent.com/16356240/37745415-168ec420-2d4b-11e8-9c81-c69101b748cf.png)

Should discuss more offline of specific details of what to allow. 

EDITED TO ADD:  Please also allow markdown in the Office Hours Queue Welcome Message

Note:  Both of these messages are specified on the course settings page

**Comment by muarachmann** [comment]
@andrewaikens87,   @bmcutler , @pbailie could this be synonymous to a WYSIWYG editor like https://summernote.org/ or https://ckeditor.com/ I have worked with this and they are pretty good both. Though i prefer summernote to the rest. If yes please can you guide me on where to implement this feature thanks

**Comment by bmcutler** [comment]
Please see discussion on PR #3685
Let's use markdown (make sure html is scrubbed of scripts)

**Comment by bmcutler** [comment]
Our most recent plan was to use markdown everywhere that fancy formatting would be beneficial.  It's going really well in the notebook formatting.  Let's keep going.

I can't remember the status of use of markdown for the instructor specified messages on the Course Settings page.  

I just tried to use markdown for the "Upload Message" but the link didn't render properly.  It did insert a <br> for a stray newline (the <br> was typed not rendered), so something isn't quite right.

**Comment by bmcutler** [comment]
@elihschiff 
Maybe this is something you can do quickly?

**Comment by bmcutler** [comment]
@elihschiff Switch that, let's have @DefinitiveAbove work on this :)
