### ISSUE TITLE
Coordinate submitty system upgrade/installation of worker machines from primary machine

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1832]
When INSTALL_SUBMITTY.sh is run on the primary machine, it should notify halt the shipper & worker daemons on all machines, then (download?)/install software on all machines, then restart daemons on all machines.  

Requires communication & correct permissions.  

And the whole thing needs to be properly documented.

**Comment by emaicus** [comment]
I propose the following design for consideration:

First, I want to store the currently installed commit hash and tag in the submitty.json file at install submitty time. Tags in github reference a specific commit, but it is easy to find the most recent previous tag.

When a shipper is started, it creates an autograding_worker.json on the worker machine, which provides arguments to the worker in regards to how to run. I want to include the commit hash and tag used by primary submitty in this file. 

When a worker is started, it will read this file. If it's locally installed commit hash does not match the commit hash requested by primary, it will perform a checkout and reinstall.

After it starts execution, the autograding_worker script will monitor the autograding_worker.json for changes. If it sees a change, it will restart itself, causing it to re-read the file.

The main point that we need to clarify is how to handle the case in which primary attempts a reinstall from a commit that has not been checked in to github in any fashion (e.g. it's not on any branch).

In this case, I propose the following:
If the currently installed commit is more recent than the tag, we do nothing.
If the currently installed commit is less recent than the tag provided by primary, we checkout the tag and reinstall.

**Comment by MasterOdin** [comment]
1. The worker running as hwcron might not be able to upgrade itself due to file permissions/folder ownership (like if we were to add an untrusted user to that machine).
1. The shipper running as hwcron does not have permissions to write files to `/usr/local/submitty/config`
1. The shipper running as hwcron would then have ssh access to other machines and be able to modify some number of files on it
1. why does the autograding_worker need to monitor the json file for changes? the shipper (or whatever does this), when sshed into the machine, could just send a signal (like `SIGUSR1`) to the worker to reload itself.
1. what's the purpose of the tags? so that workers are always running a tag while master submitty could be running whatever?

**Comment by bmcutler** [comment]
To add to Evan's post.  If the commit hash isn't available from github, and the tags don't match (the primary may have rolled back or far jumped ahead), we install the commit for the tag on the worker machine.   We assume commits after/between tags do not have significant changes that affect worker/shipper and running the closest tag but slightly different version worker/shipper is fine.

**Comment by bmcutler** [comment]
Permissions ugh.  
Perhaps a signal is a better plan than info in a file?  But I'm still in favor of writing down all of the information in a file.

**Comment by MasterOdin** [comment]
The signal was purely just a suggestion on restarting the worker. We actually should just use systemctl. I agree with writing and reading config values from a file.

**Comment by MasterOdin** [comment]
So to some up the discussion we had in-person today for implementation:

INSTALL_SUBMITTY_HELPER.sh at the end will iterate through all workers it knows about and for each:
1. rsync the `/usr/local/submitty/GIT_CHECKOUT_Submitty` directory from the shipper to the worker machine
2. run the installer `/usr/local/submitty/.setup/INSTALL_SUBMITTY.sh` on the worker

These steps can be disabled by putting at the top of the `autograding_workers.json` file by setting a flag `update_worker` (or something named like that) to false.
