### ISSUE TITLE
Fix the TA view / Student information huge late days table

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1846]
* Refactor the code to use the other(?) query

* Fix the first column (Late days allowed), it looks like it's only using default allowed late days, not the per student edits by date to late days allowed

* for team assignments, make multiple tables of all gradeables & lateness for each member of the team, just display them one after the other with a scroll bar

**Comment by bmcutler** [comment]
@saxocellphone Maybe you can take a look at this one.  You'll probably have to ask @MasterOdin for help.  But getting familiar with another part of the code base will be good prep for the summer.

**Comment by saxocellphone** [comment]
@bmcutler @MasterOdin I'm not really sure where to start with this nor do I understand what the issue is. Is the table referring to the database? Any help is appreciated

**Comment by bmcutler** [comment]
From the TA interface, the "Student Information" pane (with the black border) has a table showing how the late days are calculated.

**Comment by MasterOdin** [comment]
So @bmcutler mentioned where to find the table. It currently uses the [LateDaysCalculation](https://github.com/Submitty/Submitty/blob/master/site/app/models/LateDaysCalculation.php) model which has some issues. However, we no longer need that model as you can basically load each gradeable from the DB with all the necessary information you might want. You can utilize the code from [ReportController](https://github.com/Submitty/Submitty/blob/master/site/app/controllers/admin/ReportController.php):
https://github.com/Submitty/Submitty/blob/bcc778514299bfabf574131f5eacce3732c695e1/site/app/controllers/admin/ReportController.php#L122-L126
to form how you would do this query (changing the second parameter to be the user_id of the student (or students in the case of a team assignment) of the assignment you're looking at to get all gradeables by them, and then just iterating through that to construct the table.

**Comment by saxocellphone** [comment]
@MasterOdin I was able to get the table to work, but I'm using some repeated code from ReportController. Should I rewrite the LateDayCalculation model to make it more efficient or should I just copy and paste the late day code?

**Comment by MasterOdin** [comment]
LateDayCalculation should probably just go away as it's filled with inefficient code patterns. Getting all Gradeables model for a user (which is what the ReportController does) gives you all of the per gradeable late day information and then in iterating though them to determine the status, you could then be writing out the statuses as appropriate.
