### ISSUE TITLE
late days allowed 'removing' entries

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1848]
Bug:

The "late days allowed" tab from the instructor user interface does not allow us to remove an entry in the late_days table added for a student.  If we have made an accidental entry for a student, we should be able to remove that.  The workaround now is to re-specify the default for that student.

The page has an attempt/hack to do so:  If you re-enter the same date and specify "Late Days" as 0, then the row disappears from the tab display, but it's still in the database table (with the value 0), and queries that use the table, will have zero, which is wrong, if the course has a non-zero default number of late days.

Instead, this tab display should show ALL rows in the table (sorted by username, then date), and we should have a pencil or x icon to delete  a row.  And we should be able to specify '0' late days for a student -- to zero out the default number allowed.

**Comment by scopeInfinity** [comment]
Hi, @bmcutler  
I just wanted to know if apart from adding 'x' icon for deletion of a row,  is there any requirement for `Multiple Entry Deletion Via CSV Upload`?
