### ISSUE TITLE
Registered Section Restricted to Numeric Values (Does not support alpha characters.)

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#1852]
Sections at our institution are represented by alpha characters (A, B, C, etc.). It would be nice to be able to use these as section designation in submitty.

The Registered Section is part of the new student screen and on the student view. I am sure there are other places that this information is used.

**Comment by tushargr** [comment]
@bmcutler @pbailie 
I added section_type (can be numeric or alphabet) in course_templete.ini (taken by create_course.sh while creating course). Now the config.ini will have section type also after the course is created.

For further implementation, I can see two options-
1. No change in database tables. Registration section and rotating section in various table will be int as it is now. In database queries, if the query involve reg section or rot section, we will check the config.ini  for section_type. If the section_type is numeric, then no change. Else if section_type is alphabet, we will change reg section and rot section extracted from database to alphabet type.
2. Change the database to make reg section and rot section column in tables as string.
 And while creating a course, we will store numeric or alphabet in tables (need to work on create_course.sh). No need to change database queries as in tables appropriate section type will be stored.
Right now I am trying to implement 1.

**Comment by bmcutler** [comment]
Please don't change the configs.  
The registration section should be generalized to be a string in the database, and all of the places that use it.
Let's restrict the values that can be used to strings containing 0-9, a-z, A-Z, -, and _.  I think all other symbols can be excluded.  This check will just be at data entry time, from the new add section web ui.

**Comment by tushargr** [comment]
Ok I got it.
I misunderstood it earlier. I thought this feature will include swapping between alphabet and numeric registration section (changing existing reg section name from numeric to alphabet and vice versa).
Now I got what to do

**Comment by pbailie** [comment]
The auto feed script currently validates that the registration section is numeric.  I will update accordingly to accept "strings containing 0-9, a-z, A-Z, -, and _".

**Comment by MasterOdin** [comment]
We can also add the check within the DB as well fairly easily.
