### ISSUE TITLE
"Manual/TA/Peer Grading Rubric" on the Gradeable Form values are not saved

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#1854]
I created a new gradeable using the template option. All the fields were populated and I edited the fields that changed for this new assignment. Once I clicked save, the "Manual/TA/Peer Grading Rubric" items were missing. I tried editing the form to add them back, but the form does not show the new rubric items.

**Comment by bmcutler** [comment]
We are in the middle of a significant rewrite/refactor/redesign of this code.   Please re-open issues for problems with the new interface.
