### ISSUE TITLE
Add logout button (RCOS IGNORE THIS)

### ISSUE THREAD

**Issue by sep2112** [Submitty/Submitty#186]
Please.

**Comment by MasterOdin** [comment]
So we want to incorporate something like this:
```
You can get "pseudo" logout behavior though using a $_SESSION variable.

Here's a code block: (put this at the top of index.php instead of the current authentication code, also remove the session_start() call that appears below the authentication stuff)
```
session_start();
if (isset($_GET['logout'])) {
    session_destroy();
    echo "Logged out";
    exit();
}
if (!isset($_SESSION['logged_in'])) {
    $_SESSION['logged_in'] = false;
else {
    if (isset($_SERVER['PHP_AUTH_USER'])) {
        $user = $_SERVER['PHP_AUTH_USER'];
        $_SESSION['logged_in'] = true;
    } else if (isset($_SERVER['REMOTE_USER'])) {
        $user = $_SERVER['PHP_AUTH_USER'];
        $_SESSION['logged_in'] = true;
    }
}

if (!$_SESSION['logged_in']) {
    header('WWW-Authenticate: Basic realm=HWServer'); 
    header('HTTP/1.0 401 Unauthorized'); 
    exit;
}

// rest of index.php
```

I believe this should work fine in FF and Chrome, but not IE 11 as is (in that if you hit logout, the box will appear the next time you visit, but then if you hit cancel, you're logged in. Might be able to fix that with some more work)

**Comment by bmcutler** [comment]
Prior Issues:  Issue # 89, Issue #84, Issue #85, Issue #76

**Comment by bmcutler** [comment]
Why is this necessary?  (Currently, closing the browser completely with accomplish this logout.)

Let's proceed with caution.  If Matt's suggestion above doesn't clean up all of the credentials (giving user a false sense of security) or if it leaves things in a corrupt state (hampering future attempts to log in), that would be worse than the current implementation.

**Comment by pbailie** [comment]
As I understand it, the HTTP spec doesn't include any official logout functionality.  That's why many websites suggest you completely close your browser, even after "logging out."

Websites that have a logout button are using hacks, often involving setting and destroying a session cookie (as Matt's example code does).  But that doesn't stop the browser client from re-sending your login/password credentials -- which is normal behavior by HTTP spec.  So as far as I know, the only sure and official way to "logout" from any website is to close your browser client.

**Comment by bmcutler** [comment]
Many users (both students & developers) click without thinking when their browser offers to "save password".  Any logout implementation should be tested with password savers.

**Comment by MasterOdin** [comment]
We don't necessarily have to worry about "save password" of browsers, but considering not all browsers implement the ability to "log out" (as they don't guarantee getting rid of authentication details on a 401 page). The only thing that really should be done is a small little box that simply states "Please close your browser to log out", but nothing further should be done, so leaving this issue open (so we don't have this suggested again and people can see the entire discussion), but marking as "wontfix".

**Comment by MasterOdin** [comment]
Done in 8fb64ae406f94a584b91e2ca132788d47b94b199
