### ISSUE TITLE
Add "current time on server" dynamic clock to submission page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1865]
In the upper right corner, under the due date, let's display the current date/time on the server (precision=minutes? or seconds?).  

This is a common feature on some conference submissions systems.  It should not need to constantly poll the server, but do so occasionally in case of time drift problems.  

Perhaps it indicates "late" or displays the time until deadline.  (design discussion needed)
<img width="330" alt="screen shot 2018-04-12 at 6 02 29 pm" src="https://user-images.githubusercontent.com/5871417/38706697-24b42102-3e7c-11e8-9d03-bbb2c408a848.png">

**Comment by xprilion** [comment]
Hey @bmcutler, I have solved this with the minute precision currently and the current time remains static. 

How would you like the precision to be?

The `$DATE_FORMAT = "m/d/Y @ H:i";` line does not use the second precision, which is what I used for displaying the current time.

Besides, how do you wish to have the 'Late' indicator implemented? I believe we could change the text color of the due date to red and right below it, display the 'late by' time which will essentially be the difference in time from the due date to the current date while making the submission.

**Comment by bmcutler** [comment]
@hdrodz97 
Bumping the priority of this...

Feature request to display a countdown timer until the deadline -- must be robust to different browser/OS and not get confused if the computer is put to sleep/hibernate/lid closed/local clock or timezone modified, etc.

related to #5303 & 5345
