### ISSUE TITLE
Create docker container 'test suite'

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1867]
Whenever a container is built on the system for use in autograding, we need to make sure it has the minimal components necessary to run the autograding code. This issue should document those requirements, and then track the development of a simple python script that given an image will run a very brief test suite within the container to ensure it has the necessary capabilities.

**Comment by bmcutler** [comment]
@MasterOdin 
what is the status of this issue?

**Comment by MasterOdin** [comment]
Closing this for now as the script exists in 37853a349de4121c5fa1202559b4048582270a50. Once a pipeline for instructors to define images in place, can move that script to the necessary place.
