### ISSUE TITLE
Feature Request: Dark Theme

### ISSUE THREAD

**Issue by AudreyBeard** [Submitty/Submitty#1873]
Like many other dark-dwelling grad students, I prefer dark themes when looking at code. The light color theme of Submitty strains my eyes, and I would appreciate a dark theme.

I have tried adjusting the colors in my browser, but that overrides Submitty's syntax coloring.

Thanks!

**Comment by shailpatels** [comment]
closing already implemented

**Comment by shailpatels** [comment]
Reopening - misinterpreted as dark mode for electronic grader submission panel only
