### ISSUE TITLE
Investigate using Twig/Blade for the PHP views

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1887]
Twig: https://twig.symfony.com/
Blade: https://laravel.com/docs/5.6/blade

I think using either (preferably twig) is better than the current approach (which I regret doing) and should result in cleaner views/logic as that would better enforce the "no non-view logic in a view".

**Comment by MasterOdin** [comment]
So from discussion, we'd like to do initial research into replacing the homepage with a Twig template. That will give us an idea how Twig would hook into the current infrastructure (calling it, where would templates live, etc.) as well as a general view of how the views would look. Following that (and discussion), we'll either go ahead with more translations of Twig or scrap the idea.

**Comment by CouleeApps** [comment]
Started this with the homepage template in the [twig-templates](https://github.com/Submitty/Submitty/tree/twig-templates) branch

**Comment by CouleeApps** [comment]
Twigged up the admin Users page (which also includes the Graders and Rotating Sections pages). See branch for impl

**Comment by MasterOdin** [comment]
I think that's probably enough pages for now to be able to judge whether or not it's worth continuing with the twig refactors (and tweaks we might want to make in how we interact with Twig) which we should probably do tomorrow?

Good job though!

**Comment by CouleeApps** [comment]
I'm definitely in favor of continuing with Twig. With the new gradeable interface being built on top of it, and considering how much it improved the readability of the views, it seems like a very good choice to use it. We can discuss more at the meeting.

**Comment by bmcutler** [comment]
in progress in #2053
