### ISSUE TITLE
Allow uploading of CSVs of test grades

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#191]
Format would be:

Need to take the scores for each question, put them into an array, use 
```$pgArray = DatabaseUtils::fromPHPToPGArray($question_array)```
to get the proper postgres array format for the questions, then do something like:
```Database::query("INSERT INTO grades_tests (test_id, grade_test_user_id, student_rcs, grade_test_questions, grade_test_value, grade_test_text) VALUES (1, ?, ?, ?, ?, ?)", array(User::$user_id, $student_rcs, $pgArray, $test_grade, "")```
and do this for every line in the file.

**Comment by bmcutler** [comment]
Works :)

Eventually want to have more sanity checks:
Is this the right course?  Do all of the users exist?  
Is this the right exam #?  If there are are scores for the students, do most of them match (just some minor regrades?
And add an "undo" feature.
