### ISSUE TITLE
Investigate use of json_agg instead of array_agg for Gradeable query

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#1914]
The gradeable query aggregates several 1:m relationships we have for a gradeable (a gradeable has one gradeable_data row which has many gradeable_component which each have their own gradeable_component_data which have many gradeable_component_mark which all have their own gradeable_component_mark_data) which we use array_agg to join down into a single result set. However, due to non-uniform cardinality of these arrays, for some arrays of arrays (the mark stuff), we have to do some type-casting of arrays to comma separated strings which are then in turn array aggregated. While this works, it creates a confusion in types (seen principally in that the current codebase at the time of his issue creation [see files at commit 20fc6c453ac83efe7e8cc66bf8e4d991cfab68e2] in that points (a float field) and publish (a bool field) are both strings. While we could properly typecast all of these fields after they've been further split apart (within the GradeableComponent model), it may be better to use the [JSON](https://www.postgresql.org/docs/9.5/static/datatype-json.html) datatype via json_agg (or jsonb_agg) instead.

When doing this, we must make tests of correctness and check the speed/performance of the query.

**Comment by KevinMackenzie** [comment]
In #2235, I am using this for the queries with the new gradeable model and there is a statistically significant performance increase with using `json_agg` (P-val < 0.0001)

**Comment by MasterOdin** [comment]
How are types returned from the DB when in JSON form? That was the biggest issue was to ensure that types (at least for string, Boolean, and numeric) would be easier to get out of the DB.

**Comment by KevinMackenzie** [comment]
The type information is maintained, so numeric columns in the db will be
numeric values in the json, booleans get converted properly, and nulls
propagate well. You just call json_decode on the string and it pretty much
magically works.
