### ISSUE TITLE
instructor content timed release & user access control

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1921]
Use case:
Instructor would like to post/host .pdf or other files on the Submitty server.
And specify which users can access the file(s), and what time they are available.

Examples:
* A lab exercise that should be released/made available at the start time of the student's lab.  Each registration section of students has a different start time.
* A homework assignment that has different versions (perhaps a unique version for each student).

From the navigation page or the page of the assignment, the student is given a url/link, and the file under that link is only accessible if the timestamp & username is valid.

Need to design both the instructor interface for releasing this link.
And make sure its intuitive for how the student downloads it.  (link should be visible but greyed out with a release time?)

- [x] Interface for instructors to release files
- [x] Interface for students to download files
- [x] Allow instructors to release at a specific date
- [x] Don't show to students before that date
- [ ] Enforce date with access control (so students can't guess the urls)

**Comment by bmcutler** [comment]
related to #865

**Comment by Kevin-MM** [comment]
Confirmed students can view unreleased materials provided they have the url.
