### ISSUE TITLE
instructor triggered "grade my repository" when repo does not exist.

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1934]
causes errors.  Also autograding /tmp files should clean themselves up!

**Comment by zjxiaohan** [comment]
I created a gradeable that requires vcs, and immediately pressed `Grade My Repository`. There are no errors thrown but `failed_to_clone_repository.txt (0.37kb)` is generated in `Submitted Files`. Am I reproducing it correctly?

**Comment by MasterOdin** [comment]
Fixed as a side-effect of #3700 which moved the git clone operations in a separate step before grading occurs.
