### ISSUE TITLE
Implement Selenium tests for the Discussion Forum

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#1975]
Current tests are located in `Submitty/tests/e2e/`, we would like to have tests for the Discussion Forum. This can include testing to ensure that merge threads is performing as expected once it is merged. A good example to refer to is `test_login.py`. Also make sure to reference [the documentation](https://www.seleniumhq.org/docs/).

**Comment by scopeInfinity** [comment]
Few E2E  selenium tests for forums are added in #1962
It covers tests for basic operations(create/delete theads and replies), attachments and merging threads.

**Comment by bmcutler** [comment]
Closing this umbrella issue. 
We will open specific new issues to tackle thorough discussion forum testing.
