### ISSUE TITLE
Automate generate_repos.py

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1978]
When the instructor makes a VCS assignment with repos hosted on the local machine -- let's make repos.

However, for team assignments we have to run generate repos after the teams have been formed (and it can be run multiple times to handle teams formed since the last time it was run.)  And also it would be necessary to re-run to handle newly registered students for individual assignments.

**Comment by MasterOdin** [comment]
The same interface for generating repos for a gradeable after an instructor makes it can be hooked up to do that for teams as they form.

**Comment by bmcutler** [comment]
@drumilpatel2000 
We have instructor documentation for creating assignments to use submitty server hosted git repositories:
https://submitty.org/instructor/managing_git

We'd like to eliminate the need for instructors to call the generate_repos script.  
We'll want to instead have the submitty_daemon user do this either from the jobs daemon or perhaps a cron job.
We'll need to trigger creation both when the instructor makes the gradeable, but also if a new user is added to the course (for any previously created git gradeables), and also when a team is formed.
...  lots of cases to handle :)

**Comment by bmcutler** [comment]
Switching this one to Kevin instead of Drumil.
@Kevin-MM let's talk on Monday if this is unclear.
