### ISSUE TITLE
PoS Error Messages: Compilation of JUnit tests

### ISSUE THREAD

**Issue by milana2** [Submitty/Submitty#199]
Right now compilation assigns full credit as long as one specific .class file is found. However, compilation of other files, including instructor tests, may have failed, in which case the STDERR of javac shows under "Details". In most cases compilation failure leads to failure with cryptic messages of subsequent steps.

We should print a warning, asking students to look at Details every time there is Details (errors or warnings) in any of the compilation jobs.

**Comment by sihsob** [comment]
@milana2 Were there specific warnings you had in mind to print out?  I'm a little confused since I believe the errors should show up like they do for other test cases

**Comment by bmcutler** [comment]
Now we can specify a list of compilation results (an array of .class files).  Partial credit for compilation is awarded as a fraction of the files that exist.

Would be good to have an error message in the unexpanded test case if there are warnings or errors in compilation.  New issue:  #806
