### ISSUE TITLE
PoS Error Messages: Coverage report message

### ISSUE THREAD

**Issue by milana2** [Submitty/Submitty#200]
Need to change message in grading/JUnitGrader.doit_emma_coverage_report from
"ERROR: Insuffficient block and/or line coverage below threshhold for..." to
"ERROR: Insuffficient block coverage below threshhold for..." since we are taking block coverage only.

**Comment by sihsob** [comment]
Just curious but are the error messages from emma located in a similar place as the other errors in the c files?

**Comment by sihsob** [comment]
At this time, I've found where to fix this particular line.  Just need to run some tests to make sure the output is showing up correctly.

**Comment by bmcutler** [comment]
Closing this.  If necessary, please create a new issue with more specific details.
