### ISSUE TITLE
If a Developer edits their sections, they get demoted to Instructor

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2006]
This is probably not a big problem in practice because (I assume) nobody is a Developer on the live server.

To reproduce:
View graders on a course and edit a Developer. There is no option to keep their group as Developer and they are demoted to Instructor when you submit the form.

**Comment by MasterOdin** [comment]
The developer group made sense and was necessary back in the early days of Submitty (when it was HSS) as it was the only way to get certain information for debug purposes.

We should just get rid of it and move the one place it's being used to show if debug is on.
