### ISSUE TITLE
Show Grading Statistics

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#201]
When viewing page that has all labs, tests, or rubrics, should have option to "View Stats". This should either open a new popup or take user to a new page, that then shows as fine-grained stats as possible. For example, for a test page, it would show:
- Histogram of grade distribution
- Mean, Median, Std Dev, Lowest, Highest of grades
- Mean, Median, Std Dev, Lowest, Highest score of a question
- Option to only consider grades above threshold (by default 0)

For a rubric page, we could do something like
- Histogram of grade distribution
- Mean, Median, Std Dev, Lowest, Highest on grade
- Mean, Median, Std Dev, Lowest, Highest per question (and part?)
- Average number of late days used by students who used late days
- Number of students who did use late days (and were still graded)
- Number of students who submitted too late
- Number of students who didn't submit

Need to brainstorm exactly what would be good statistics.

**Comment by bmcutler** [comment]
Some of these are useful for both the students & the instructor/TAs.  Some intended for just the instructor/TAs. 
For the student visualization, need to ensure confidentiality of the grades.

**Comment by sihsob** [comment]
@lindquistador I can look into how to actually displaying the results that you generate for the students and eventually the TAGrading

At the moment I just have javascript libraries in mind - should not cause security issues

**Comment by MasterOdin** [comment]
I'm not sure what you mean by javascript libraries? Also, all of these TA statistics should only be shown to instructors for now till the grading and submission code are better unified (and submission code actually uses database).

**Comment by sihsob** [comment]
Like libraries for displaying the data in nice graphs and today in the RCOS meeting, Barb and I figured that it might be easier to implement the student side first (they're getting basic statistics anyways as of)

**Comment by MasterOdin** [comment]
Okay, that makes sense. You should just focus on student statistics for now as that's far more graphical than this.

**Comment by bmcutler** [comment]
I think the confusion is about the different types of data.  @sihsob and @lindquistador are tackling data available in the autograding logs and visualizations that are immediately helpful to the students (& instructor / TAs).  @MasterOdin is thinking about data from the grading database targeting TAs/instructors.  Both types of data will need to think about security/confidentiality (when made available to students).  Maybe eventually they'll be the same data... in the database.

**Comment by sihsob** [comment]
Ah okay, I think the two issues currently about this is both targeted towards the TA side - perhaps have one that's about student histograms?

**Comment by bmcutler** [comment]
Also read notes in #136

**Comment by bmcutler** [comment]
most of this is done.  other issues for histogram #1650 etc
