### ISSUE TITLE
User Feedback: Whitespace

### ISSUE THREAD

**Issue by jungj5** [Submitty/Submitty#202]
Based on what I have read from the HSS surveys, it seems like a lot of people are having problems with the whitespaces/line skips. People will have the correct output but in a slightly different format and at times they will get extremely little to no credit. We should look into finding a way to check if the output is correct when looking past the formatting differences.

**Comment by goldschmidt** [comment]
Hello, just a note that this certainly should be optional.  I think for
most assignments, extra spacing is indeed incorrect -- i.e., when coding,
being exact is important.

G

On Wed, Oct 21, 2015 at 8:19 PM, Joseph Jung <notifications@github.com>
wrote:

> Based on what I have read from the HSS surveys, it seems like a lot of
> people are having problems with the whitespaces/line skips. People will
> have the correct output but in a slightly different format and at times
> they will get extremely little to no credit. We should look into finding a
> way to check if the output is correct when looking past the formatting
> differences.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RCOS-Grading-Server/HWserver/issues/202>.
>



-- 
David Goldschmidt, Ph.D.
Executive Officer
Computer Science Department
Rensselaer Polytechnic Institute
Troy, New York
http://www.cs.rpi.edu/~goldsd/
goldschmidt@gmail.com

**Comment by bmcutler** [comment]
These two functions in grading/myersDiff.cpp
  myersDiffbyLineNoWhite 
  myersDiffbyLinebyCharExtraStudentOutputOk
Are trying to tackle this issue.  However, it needs a more complete and robust implementation.  

The instructor should be able to specify:
  * exact match required (including spaces, tabs & characters)
  * output should be neat, with columns of data aligned (e.g., a table with consistent (but not specified) column width and left/right alignment)
  * at least one space/tab/newline between non whitespace characters/words
  * matches if all whitespace is ignored/removed

Full or partial credit if:
  * matches if everything is converted to lowercase
  * number is a close match (e.g., only difference in # of significant digits, difference is within a small epsilon)
 
Currently all character differences in Myers diff are equal.  But maybe they should be weighted differently (spaces, punctuation, lower weight than letters/numbers?)

**Comment by bmcutler** [comment]
Also..  It is important to sync any changes with the myers diff code with the php diff viewer.  If whitespace differences are allowed, the color highlighting must help indicate what is different but not a deduction from what is different and must be fixed for full credit.

**Comment by bmcutler** [comment]
@Mijumaru3 is also helping with this issue.
