### ISSUE TITLE
User Feedback: Partial Credit on the Server

### ISSUE THREAD

**Issue by wonga6** [Submitty/Submitty#204]
From the homework server student survey:
Partial credit is tricky/unfair on the server. So a response from one student on the survey was that more points were obtained for having 5 memory leaks than one memory; 1 point was lost for 5 memory leaks whereas 2 were lost for 1 memory leak.

**Comment by bmcutler** [comment]
Currently there is no partial credit for Dr Memory.  If it does not say "NO ERRORS FOUND", all points for that portion of the test case are deducted.  We should create a more nuanced grading module for Dr Memory output.

**Comment by bmcutler** [comment]
Has been redesigned.
