### ISSUE TITLE
functionality & documentation of "Overwrite Grader" checkbox

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2049]
This was solved with #903, but it looks like some recent changes to how the assigned marks get saved has caused the "Overwrite" feature to stop working.  No matter what the "Overwrite Grader" Checkbox state is, the data always gets saved to the server.

---------------------------

EDITED by @bmcutler

This checkbox should only be displayed for instructor users.
By default any editing to a component should replace the grader in the database.

Leave the text as "Overwrite Grader".  (Short is good)
It is only visible to instructors.
By default it is checked.  (edits replace the grader).
If unchecked, and previously graded, edits will not change the grader.

To close this issue:
- [ ] rename to "Silent Edit"
- [ ] implement desired behavior
- [ ] write end-to-end test cases to confirm behavior (and avoid re-breaking in the future)
- [ ] document purpose of this checkbox in instructor section of submitty.org

**Comment by CouleeApps** [comment]
Looks like this is working fine to me. Changing a grade as a different grader does not overwrite the previous grader's name on the list:

Originally:

![](https://i.imgur.com/vEEVQne.jpg)

After logging in as TA and changing the grade:

![](https://i.imgur.com/Bbbu1WI.jpg)

**Comment by KevinMackenzie** [comment]
I think I misinterpreted what this feature should do.  I thought it would not allow any changing of already-graded components when unchecked.

**Comment by CouleeApps** [comment]
This issue should really be named "improve wording on 'overwrite grader' checkbox"
