### ISSUE TITLE
Build (or Rebuild) Assignment Button

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#2050]
It would be nice when working with an assignment if you could rebuild it from the web interface. Simply have a button that ran the build script on the server.

**Comment by prestoncarman** [comment]
How do you execute the student submissions? Can you set up a similar process for the build script?

**Comment by MasterOdin** [comment]
@tushargr, I need to finish (or I can hand off what I've done to someone else) #1979 which would allow hwphp to create a new "build" job for hwcron to execute asynchronously as we don't really want to allow hwphp to execute shell commands.

**Comment by prestoncarman** [comment]
Oh, I just looked at yoru pull request and it seems you found a solution. :+1: Nice.

**Comment by bmcutler** [comment]
@MasterOdin we can rebuild the assignment even without your revision/improvement to the cron tasks.  (we talked about it in today's meeting).

@prestoncarman Maybe we misunderstood your request?  We are implementing rebuild of the assignment configuration (if the instructor has modified the config.json or related files).  Another thing we should (and can easily) add to the UI is a way for an instructor to request a "regrade" of a particular student submission.  I'll open a new issue for the regrade task...  :)
