### ISSUE TITLE
Migrate all of the PHP views to Twig

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#2053]
Views to do (mid-summer):

- [x] TA Grading
   - [x] Information Panel (waiting on a pull request)
   - [x] Regrade Panel
- [x] Autograding
   - [x] Checks list

Waiting on changes and for a later issue:

- Forums (by @scopeInfinity)
   - Thread
   - Create Thread
   - Statistics
   - Search
- Plagiarism (currently unfinished)
- ~~Diff viewer~~ (unlikely)

**Comment by CouleeApps** [comment]
Started the process of removing the shell "View" classes on [remove-twig-layer](https://github.com/Submitty/Submitty/tree/rip-view-layer). Need feedback for if this is how we want the controllers to look.

**Comment by CouleeApps** [comment]
This is nearly done, current views remaining:

- [ ] Forums
   - [ ] Thread
   - [ ] Create Thread
   - [ ] Statistics
   - [ ] Search
- [ ] Plagiarism (actual view unfinished)
- [ ] TA Grading
   - [ ] Information Panel
   - [ ] Regrade Panel
- [ ] Autograding
   - [ ] Checks list 
   - [ ] Diff viewer (uncertain)

Apart from that there are a few more things I want to do with the view layer that can wait until a later issue, including:
* Replace style="long list of styles" with CSS classes
* Remove as many php functions / classes as possible and use `{% include %}`
* Move some of the math into the model classes
* Clean up some twig files I made earlier before I knew about many of the new features
