### ISSUE TITLE
Horizontal Scrollbar for Rainbow Chart

### ISSUE THREAD

**Issue by etran2726** [Submitty/Submitty#206]
PREVIOUS TITLE:  Horizontal Scrollbar for Rainbow Chart

The length of the rainbow chart causes the page to expand to the right. A slight improvement would be to put the chart in its own frame that has its own vertical scrollbar.

**Comment by MasterOdin** [comment]
The solution would be to add a "overflow-x: scroll" attribute to the CSS that contains the rainbow grades.

**Comment by bmcutler** [comment]
Currently the format of the data is optimized for the instructor view (each student is one row in a huge table).  We should design & implement an alternate format that is optimized for the student view -- that is not restricted to one row and thus has a manageable page width.

**Comment by bmcutler** [comment]
The student data is now transposed so it is vertical and horizontal scroll isn't needed anymore :)
