### ISSUE TITLE
It's possible to invite someone to a team and then leave it

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2075]
This leaves them with invitations from empty teams... And it's possible to do this more than once.

![](https://i.imgur.com/9RjhhWu.jpg)

**Comment by bmcutler** [comment]
good catch, we should delete all invitations to the team when the last person leaves it.

**Comment by saxocellphone** [comment]
Right now, when the creator of the team leaves, the submission folder stays in the folder for that assignment, and if that person makes the team again, a new submission folder is made with a different number in front of the userid. Is this the appropriate behavior?
