### ISSUE TITLE
INSTALL_SUBMITTY_HELPER changes permissions on files in repo

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#2080]
See relevant lines in `.setup/INSTALL_SUBMITTY_HELPER.sh`:
https://github.com/Submitty/Submitty/blob/68ec41f777dcc7ae87db005e259c1ecc9fad0c67/.setup/INSTALL_SUBMITTY_HELPER.sh#L105-L107

This changes the permissions in the git repo on a ton of files. These new permissions either need to be reverted or  we're going to want to make a PR to update the permissions on all files that are checked in to reflect this.

See https://pastebin.com/jGrvatkZ for the full list of affected files (it's basically everything), changing from `644` to `755`.

**Comment by bmcutler** [comment]
to ignore permissions changes we can edit
.git/config
and change:
[core]
        repositoryformatversion = 0
        filemode = true
to be:
[core]
        repositoryformatversion = 0
        filemode = false

**Comment by MasterOdin** [comment]
What are the ideal permissions for the GIT_CHECKOUT_Submitty? `760` on all files with `root:hwcron` ownership?

**Comment by bmcutler** [comment]
on primary
640 on files, 750 on directories, dev/sysadmin:hwcron
(dev/sysadmin owner so they author edits/commits that will be pushed to github)

on worker
supervisor needs write.
could be 660 files 770 directories, root:supervisor (or we could make supervisor the owner)

**Comment by bmcutler** [comment]
NOTE: I think the shared repo directory from host to vagrant is messing with the permissions.
