### ISSUE TITLE
Forum: color coded & instructor ordered tags

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2094]
It might be nice to give the instructor explicit control over the ordering of the categories (not chrono or alphabetic), and to color code the labels for the categories.

for example:

I could imagine wanting one color for all hws:  (hw1, hw2, hw3, final_project)
another color for tests:  q1, q2, exam1, q3, final_exam
another color for questions: question

And wanting to specify they are ordered:  question, hw1, hw2, hw3, final_project, q1, q2, exam1, q3, final_exam

The ordering & coloring would be used in the thread display sidebar, the pull-down menu for filtering, and in choosing the category for a new thread, or editing the categories of an existing thread.

Let's discuss

**Comment by scopeInfinity** [comment]
TODO
- [ ] Fix order of categories in threads list on view thread page
