### ISSUE TITLE
Team grading hw stats don't show up 

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2119]
With the partially graded team assignment, there is no progress bar on the navigation page and all the sections are reporting 0% graded. 

~~Would be nice if it was "in the middle of grading" like the other grading homework, and had some (but not all) grades entered~~

**Comment by CouleeApps** [comment]
Actually, I'm wrong. It looks like it does have sample grade data, it's just not displayed in the ui.

**Comment by CouleeApps** [comment]
![](https://i.imgur.com/0SKstCn.jpg)
![](https://i.imgur.com/MfUo1fn.jpg)
![](https://i.imgur.com/DmfGudh.jpg)
![](https://i.imgur.com/Vx2nJvW.jpg)

**Comment by anamika2004** [comment]
I would like to work on this.
