### ISSUE TITLE
Links are very hard to recognize

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2122]
For some reason <a> tags are the same color as normal text and have no underline. Without hovering them there is no way to tell that they are links. 

Example (can you find any/all of the links on this page?):
![](https://i.imgur.com/YK6gFxO.jpg)

**Comment by KevinMackenzie** [comment]
it looks like there are a few different styles that will have to be updated so it doesn't look weird with blue text.  Namely: The links for the buttons on the admin view page (like  "edit", easy), the icons ("i" elements, easy), and the navigation column of the forum (haven't figured out how yet).

**Comment by bmcutler** [comment]
Has been improved in some/most cases.  Re-open with specific cases as needed.
