### ISSUE TITLE
Tell people they need javascript if they have it disabled

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2141]
Likely using `<noscript>` tags

**Comment by muarachmann** [comment]
@bmcutler this is a pretty simple fix `<noscript>We need javaScript functionality switched on for proper functioning of Submitty </noscript>`
- Question is this to be place everywhere or in specific loacations. If yes please point them out and i would gladly make a PR for this

**Comment by xprilion** [comment]
Hey @CouleeApps I guess this issue got covered in #3253! Please check and close if already solved! :) I would surely love to work on this if anything is remaining!

**Comment by MasterOdin** [comment]
Yeah, it was originally done in #3247, which was then reverted as installation got messed up and so we re-opened the PR as #3253 as we examined what went wrong. That's been merged and running well so we can definitely close this out.
