### ISSUE TITLE
Grade badge color consistency

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2145]
On the results page, badges have different coloring schemes. For consistency's sake, we should only use one of these.

Autograding:
* Green: 100%
* Yellow: 1-99%
* Red: 0%

![](https://i.imgur.com/G5L6qug.jpg)

Manual / TA grading:
* Green: 100%
* Yellow: 50-100%
* Red: 0-50%

![](https://i.imgur.com/lYj6s27.jpg)

**Comment by CouleeApps** [comment]
Planning to use the second scheme with red as 0-50% per meeting discussion

**Comment by jchulton** [comment]
Looks good. One thing to note is that I should probably change the color scheme of the Manual TA grading rubric to match this color scheme
