### ISSUE TITLE
gradeable url/link & delete gradeable X are not both displayed

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2152]
If both should be displayed, only the link is displayed.

At the same time, let's convert the red X to a trashcan icon (from our chosen icon library).

**Comment by bmcutler** [comment]
And also, while we're at it, let's change the edit button to a pencil 
And the rebuild button to a wrench (let's discuss options for exact icon choice)
And let's put the trash can icon next to the pencil & the wrench
And make sure there are good hover / tool tips for each icon

**Comment by CouleeApps** [comment]
Instead of all these icons, we could also use a dropdown. Then we can have text labels and still save space on the page.
