### ISSUE TITLE
Late day banner table

### ISSUE THREAD

**Issue by jchulton** [Submitty/Submitty#2153]
We should also chart out how the late day banner should read in different circumstances

**Comment by MasterOdin** [comment]
Can we link to and make these things public (but not public editable) so that these issues are self-contained? A user of our system is going to have no idea what "SUMMER2018" means or what we've designed and cannot give any meaningful feedback.

**Comment by jchulton** [comment]
Table is located here. https://docs.google.com/spreadsheets/d/1_YtCICqIPvnxiPVW6OiVmFgai_6ntTdMMa8JI5I_S0s/edit?usp=sharing
