### ISSUE TITLE
RainbowGrades Expects Numeric Sections

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#2159]
As per #2069, we now have alphanumeric section names.

[This line](https://github.com/Submitty/RainbowGrades/blob/1df486e0bf7828e7aa039d54d2914c65a73a4154/main.cpp#L1193) in RainbowGrades currently expects registration section to be an int. This should be changed to handle strings, which will break handling of old raw data. (Spring 2018 and prior).

This will involve changing a little bit of logic (now NULL section should be "null" instead of 0, validSection() has to change), accessors/modifiers for Student need to be changed, possibly more changes.

**Comment by bmcutler** [comment]
Closed in Submitty/RainbowGrades#1
