### ISSUE TITLE
Instructors cannot see hidden cases in the submission view

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2162]
Should they be allowed to? Currently this is hard coded to never show hidden cases in the submission / HomeworkView: https://github.com/Submitty/Submitty/blob/master/site/app/controllers/student/SubmissionController.php#L120

**Comment by MasterOdin** [comment]
I would say yes, as submitting to the server is a common way to make sure all autograder tests are working properly.

**Comment by CouleeApps** [comment]
This is intended behavior as per meeting discussion.
