### ISSUE TITLE
Display error on window resize

### ISSUE THREAD

**Issue by ropern123** [Submitty/Submitty#2164]
When resizing browser window, content can go outside the central box in an unsightly fashion, and when it does, the navigation bar and Submitty banner no longer fill the entire page.
Examples from the homepage and the grading page:

![homepage_display_error](https://user-images.githubusercontent.com/25157467/41382206-2cc6508e-6f39-11e8-9fca-739705c7ae29.PNG)

![grading_display_error](https://user-images.githubusercontent.com/25157467/41382583-c04d674c-6f3a-11e8-8c17-639b6eb8a2a8.PNG)

This doesn't seem to be an issue on the forum...
![forum_no_error](https://user-images.githubusercontent.com/25157467/41382909-2f9107ac-6f3c-11e8-88b1-8f5d67f4fbc4.PNG)
...until you refresh and increase the width
![forum_error](https://user-images.githubusercontent.com/25157467/41382911-2f9b6ac6-6f3c-11e8-99d1-162ff011fd33.PNG)

**Comment by xprilion** [comment]
Unable to replicate the issue, which pages does this occur on @ropern123 ?

**Comment by drumilpatel2000** [comment]
@ropern123 This issue require design changes for different sizes.
This issue will probably be solved in [Mobile-Friendly Website and/or Phone/Tablet Application](https://submitty.org/developer/project_ideas) GSoC Project.

**Comment by bmcutler** [comment]
Closing this issue, will open new specific issues for mobile design steps as appropriate.
