### ISSUE TITLE
Unexpected Indenting Of Gradable Diff Formatting 

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#2194]
A student showed me this page which shows the results from submitting his code. The student was struggling with matching the formatting, but the diff made this even more difficult, since it was indenting several lines.

![submitty_test_results](https://user-images.githubusercontent.com/3517157/41556128-ad6f9bb0-72ee-11e8-83f1-8fae69b9f94a.jpeg)

**Comment by MasterOdin** [comment]
Would you be able to provide the multiplication.txt file that you're using for the assignment?

**Comment by bmcutler** [comment]
We have seen something similar before (and I think fixed it.. )
Can you tell us what browser/OS/Submitty version you're using?  
Thanks

**Comment by prestoncarman** [comment]
A student reported the issue to me from a windows computer. I don't remember which browser they were using (I think it was chrome). The submitty code was last updated in April: commit 0ab699d5.

[multiplication2.txt](https://github.com/Submitty/Submitty/files/2116529/multiplication2.txt)

**Comment by saxocellphone** [comment]
I tried replicating the issue but I can't. It doesn't seem like multiplaction2.txt has any weird characters in it.

**Comment by andrewaikens87** [comment]
@saxocellphone Not sure if this helps but I have noticed this sort of thing can happen when you modify your zoom settings on your browser. Screenshot on: Ubuntu 18.04, Chrome, 67% zoom (commit: 19a4040). The output seems to be fine on other zoom levels. 

![screenshot from 2018-07-03 23-48-23](https://user-images.githubusercontent.com/16356240/42255828-bdc87192-7f1b-11e8-9022-329d7e05c7b9.png)

The screenshot posted by @prestoncarman seems to be zoomed in, if the student tries zooming in or out it may fix their view in the meantime.

**Comment by saxocellphone** [comment]
Hmm interesting, I use firefox mainly and that does not happen with that. I tried it on chrome and it seems to break. I'll need to look into that

**Comment by bmcutler** [comment]
@CouleeApps 
This is still an issue, a big problem, that has to be addressed before we switch to the sidebar
Zoom level 66 and 33 show the problem 

<img width="890" alt="screen shot 2018-08-08 at 9 20 03 pm" src="https://user-images.githubusercontent.com/5871417/43872809-968ff9ea-9b51-11e8-887d-d3ae9fa2682f.png">
