### ISSUE TITLE
Unexpected Nesting Tests Results (Impropper formatting)

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#2195]
![improper_nesting](https://user-images.githubusercontent.com/3517157/41556303-34c00230-72ef-11e8-97df-a5480119bc6f.png)

The tests started nesting themselves instead of being separate tests.

**Comment by bmcutler** [comment]
Hi Preston, 
Are you using the most recent version of Submitty? 
Could you also let us know what OS/browser you're using? 
Thanks
Barb

**Comment by prestoncarman** [comment]
I am using Ubuntu 18.04 with variety of browsers (Chrome, Chromium, Firefox). They all have the issue. 

![windows_now_nested](https://user-images.githubusercontent.com/3517157/41618561-6148d11e-73b8-11e8-973e-13d6198cd7b1.png)

The submitty code was last updated in April: commit 0ab699d5.

**Comment by CouleeApps** [comment]
The code for this has been refactored recently with the Twig template updates. If you still have this problem in the future feel free to re-open this issue.
