### ISSUE TITLE
End 2 end tests for the forums don't clean up

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2208]
They create new threads but don't (can't?) delete them, so if you run them multiple times you will get errors from the copied threads.

**Comment by xprilion** [comment]
The test failures in #3774 are happening due to this. Shall be working on this first!

**Comment by Fenn-CS** [comment]
Hello, @xprilion have you made any progress on this?

**Comment by bmcutler** [comment]
Plan:  Develop the API for the forum, have specific API calls to help scrub the database (& file system) of threads that were made for testing.  Need to reset the serial/auto-increment for table (e.g. the thread id can be re-used.)

....More discussion to happen

**Comment by MasterOdin** [comment]
I'm not sure we need to reset the auto-increment value of a table and that the e2e tests can probably get by without testing for that minute level of specificity, and that there's ways to deal with "is this the thread I just created" type questions without testing for exact ID.

**Comment by wusatosi** [comment]
I am not sure if this is still an issue.
The [test failure this issue causes](https://travis-ci.com/github/Submitty/Submitty/jobs/206141893#L3314-L3334) [does not fail](https://github.com/Submitty/Submitty/runs/2748554409?check_suite_focus=true#step:25:23) in current e2e tests.
