### ISSUE TITLE
Difference in "kill signal file too large" output

### ISSUE THREAD

**Issue by wonga6** [Submitty/Submitty#221]
The way I understood it was that one student submitted code with an infinite loop to the server, and on one case the only output he got was the message "file size limit exceeded." However when he added his own print statements to the program and submitted it again to the server the same test case showed his output as well as the expected output. He suggested that in the case of an infinite loop a diff be run on an empty text file so that the student could at least see what the expected output is. I would say also show the student at least a part of the text file before the program got cut off. 

*also note: I did two tests to the server with his code (he sent me his code and instructions on what he had done to it to produce the different outputs) and when I tried to recreate the error I only got the message "file size limit exceeded" in both cases (both with and without the added print statements).

**Comment by Mijumaru3** [comment]
Went through log files and it was not actually a difference in output with the same kill signal. Student was confused as to why/when each submission was giving each kill signal. Error messages could be made clearer. Will test various outputs from infinite loops to see which messages can be improved.

**Comment by sihsob** [comment]
So I'm a bit confused, did he get kill signals or was it just the file size limit exceeded error?

**Comment by Mijumaru3** [comment]
So he wasn't getting both messages at the same time. He was getting different messages (kill signal or file size exceeded) depending on which submission he was on. In some of his submissions he had an infinite loop and was outputing inside of it. In other submissions he had commented out the output but the infinite loop was still there (and he also had some debugging statements that were outside the infinite loop, which is why in those cases he was able to see the student and expected output comparison).

**Comment by sihsob** [comment]
Ah okay so I'm assuming with output, he was getting a file too large error and a kill signal when he commented out his output but both had the infinite loop.  This makes sense with the findings that I've gotten.

**Comment by bmcutler** [comment]
This might be a place where we rephrase error messages/omit/expand error messages.  In this case we should only say "file too large" and perhaps specify "student output file too large, might you have a runaway loop or recursion with a print statement?" and omit the "kill signal".   While "kill signal" is a stardard CS term, kids in CS1 / DS haven't learned this term and we want them to focus on the first part.  

(We should leave "kill signal" if it's the only message.)

**Comment by sihsob** [comment]
There should not be a kill signal associated with file size too large (unless the message kill signal appears somewhere else).  If so, I'd like to see the student's code to try and regenerate the two messages at the same time.

**Comment by bmcutler** [comment]
Closing now.  Interface has changed substantially.   Will create a new issue with a more specific task if needed.
