### ISSUE TITLE
Replace inline CSS with style rules

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2271]
Many pages have lots of inline `style="etc"` attributes, often with large amounts of exact duplicates. We should move those all into the css file to reduce page size and make the code cleaner. Just have to make css classes for any repeating elements and have the class contain the css rules instead of having them inline.

**Comment by bmcutler** [comment]
we have made good progress on this code improvement task.
we can reopen with more specific tasks/files as appropriate.
