### ISSUE TITLE
Setup Sample Courses Miscounting Gradeables

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#2279]
The generated `customization_sample.json` right now has 13 assignments but a count of 15, which causes problems with Rainbow Grades. This causes Rainbow Grades to crash since it expects a non-existent 14th and 15th assignment to have a max.

The generated file should also probably go somewhere else, currently it gets dumped in `/usr/local/submitty/.setup`, my current branch will move it to `/usr/local/submitty/test_suite/rainbowGrades/`

(Sidequestion for @bmcutler - is this the Rainbow Grades behavior we want? Or should it be able to handle a promise that there will be more gradeables later in a bucket? )

**Comment by bmcutler** [comment]
Yes, that's a bug I apparently introduced with my max new features/refactor last term.
Would like it to work as before.

**Comment by holzbh** [comment]
Changed label since the solution will be a change to Rainbow Grades.

Regarding the location of the generated .json file, it has to be in .setup at the moment since the testing process is `sudo /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh clean test_rainbow`, and the `clean` argument would remove anything in the `test_suite` directory.
