### ISSUE TITLE
Prevent calls to undeclared magic setter/getter methods

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2298]
In the `AbstractModel`, the `__call` method used to setup setters/getters for all public/protected properties should check if the method the caller is trying to invoke is listed in the `@method` list above the class declaration.  This allows us to control access to protected properties without explicitly creating public member functions such as: 
```
/** @internal */
public function setTotalHiddenExtraCredit() {
    throw new \BadFunctionCallException('Setters disabled for AutogradingConfig');
}
```
... which clutter class definitions.  If these functions don't exist, however, it might not always be clear *why* a particular access function isn't enabled.

**Comment by MasterOdin** [comment]
The createMockModel helper test function inside the BaseTestCase can serve as an idea of how one might start an implementation of this feature.

**Comment by MasterOdin** [comment]
So far as I'm aware, this was never actually done? Is this being closed as a "won't fix" or closed because it was thought of being done?
