### ISSUE TITLE
Add enumeration for user permission levels

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2304]
User permission checking is always done using hard-coded numbers whenever the comparison is made, but it would be much more clear if these permission levels were an enumeration.  This could also prevent permission bugs from arising.  As it stands, 

0. Developer (rarely/never used)
1. Instructor
2. TA
3. Grader
4. Student

**Comment by MasterOdin** [comment]
Developer no longer is a class in the system
