### ISSUE TITLE
VPAT -- Empty Link Error (Mutiple Views)

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#2311]
https://github.com/Submitty/Submitty/blob/06466d100cf8ef50e14a6eab368cc3e8ff98b089/site/app/templates/GlobalFooter.twig#L6-L8

These lines generate the following error in WAVE: "﻿﻿﻿﻿﻿﻿A link contains no text."

More information:
>**What It Means**
A link contains no text.
**Why It Matters**
If a link contains no text, the function or purpose of the link will not be presented to the user. This can introduce confusion for keyboard and screen reader users.
**How to Fix It**
Remove the empty link or provide text within the link that describes the functionality and/or target of that link.
**The Algorithm... in English**
An anchor element has an href attribute, but contains no text (or only spaces) and no images with alternative text.
**Standards and Guidelines**
[2.4.4 Link Purpose (In Context) (Level A)](http://webaim.org/standards/wcag/checklist#sc2.4.4)

**Analysis**
What's happening here is that the link "text" is not actually text in a regular sense.  The link is visibly attached to a "github" symbol.  The link is an \<i\> element (italicized text), no text within.  Instead, this \<i\> element is overridden by CSS with classes `fa`, `fa-github`, and `fa-lg` to display the github symbol.  These classes are defined in [https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css](https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css), which is an external resource not in the Submitty repository.

**EDIT / EXPANDED**
"﻿﻿﻿﻿﻿﻿A link contains no text" error also exists as follows:

https://github.com/Submitty/Submitty/blob/6e820ae5e83dd172285203246d1deb4fa9624609/site/app/templates/GlobalHeader.twig#L39

https://github.com/Submitty/Submitty/blob/6e820ae5e83dd172285203246d1deb4fa9624609/site/app/templates/GlobalHeader.twig#L57

https://github.com/Submitty/Submitty/blob/978a1276e3670c701257b1a9087da35bd461c643/site/app/templates/Navigation.twig#L36-L38

NOTE: Below code produces the error when specifically rendering "edit" or "rebuild" buttons.
https://github.com/Submitty/Submitty/blob/978a1276e3670c701257b1a9087da35bd461c643/site/app/templates/Navigation.twig#L73-L80

There may be more pages to report as I continue VPAT examination.

**Comment by pbailie** [comment]
I found this note in WAVE about aria in regards to the homepage view.  (the note was tagged by the user's first name).
>**What It Means**
An ARIA role, state, or property is present.
**Why It Matters**
ARIA provides enhanced semantics and accessibility for web content.
**How to Fix It**
Ensure the ARIA role, state, or property is used correctly. Use standard HTML accessibility features when possible. Be aware that support for ARIA is limited in older browsers and assistive technologies.
**The Algorithm... in English**
An ARIA role, state, or property is present, excluding landmark roles, aria-labelledby, or aria-describedby which have distinct icons.
**Standards and Guidelines**
None

**Comment by pbailie** [comment]
> To fix this, we'll probably want to follow some of the stuff highlighted at https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility, namely (I think) adding a `aria-hidden` attribute to the `<i>` tag and an `aria-title` to the link?

`aria-hidden` effectively "hides" an element from a screen reader, which is good to work alongside CSS's `visibility: hidden;`, but could reduce functionality if applied to a visible control.

There is no `aria-title` attribute listed among [www.w3.org's WAI-ARIA states and properties definitions](https://www.w3.org/TR/wai-aria/#state_prop_def), but there is `aria-label` and `aria-labelledby`.  `aria-labelledby` permits us to use existing text somewhere in the page to label a link without text.  Screen readers would then use that text as the link's label.  But if no such text exists, we alternatively use `aria-label` to add an accessibility label for screen readers.

**Comment by pbailie** [comment]
To @ropern123 
@bmcutler asked me to assign this issue to you in regards to the navigation view (landing page that shows gradeables after a user logs in).  Each gradeable can possibly have an "edit" (pencil) and "rebuild" (wrench) button.  Both of those fall under a "﻿﻿﻿﻿﻿﻿a link contains no text" accessibility error.  These buttons need a `aria-label` attribute added, but the button render macro in [_Submitty/site/app/templates/Navigation.twig_](https://github.com/Submitty/Submitty/blob/e7b932dcc1338d2f6993a21210851b7e51a209ba/site/app/templates/Navigation.twig#L62-L90) receives a button's properties from elsewhere.

Please dig further into the view and model code and (at minimum) add `aria-label="edit course"` and `aria-label="rebuild course"` attributes to the Navigation view's rendered "edit" and "rebuild" buttons.  My inference is to check [_site/app/views/NavigationView.php_](https://github.com/Submitty/Submitty/blob/e7b932dcc1338d2f6993a21210851b7e51a209ba/site/app/views/NavigationView.php) and/or [_site/app/models/Button.php_](https://github.com/Submitty/Submitty/blob/e7b932dcc1338d2f6993a21210851b7e51a209ba/site/app/models/Button.php).

For @bmcutler 
When a course has lots of gradeables, a page full of "edit course" / "rebuild course" controls may become confusing to screen reader users by which edit or rebuild control belongs to which gradeable.  An idea I had would be to append the gradeable's name or ID to the `aria-label` attribute.

e.g. `aria-label="edit course hw01"` / `aria-label="rebuild course hw01"`.
OR
e.g. `aria-label="edit course Homework 01: Hello World"` / `aria-label="rebuild course Homework 01: Hello World"`.

**Comment by drumilpatel2000** [comment]
@pbailie Have you founded some more link which shows the same errors?

**Comment by pbailie** [comment]
> @pbailie Have you founded some more link which shows the same errors?

In one of my morning meetings, we discovered that the list of available gradeables (homeworks and other assignments) has this problem.  We need this view fixed right away, so I am expected to attend to it.

Thank you for asking.

**Comment by bmcutler** [comment]
We will re-open if other problems arise.
