### ISSUE TITLE
Empty grading screen on Autograde only assignments

### ISSUE THREAD

**Issue by jchulton** [Submitty/Submitty#2348]
If you navigate to the TA grading screen for a gradeable that has only autograding components, you get this (and a console error anytime you try to toggle any of the dragable panels
![firstopenerror](https://user-images.githubusercontent.com/11095297/42349676-8459fb18-807b-11e8-9258-7b6cbae7e25a.JPG)

**Comment by CouleeApps** [comment]
Kind of a duplicate of #2339

**Comment by jchulton** [comment]
Yeah whoops
