### ISSUE TITLE
Errors grading no-submission student with student-assigned-pdf-pages gradeable

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2360]
When trying to grade a student who has no submission on a gradeable that uses student-assigned pdf pages, many errors arise in trying to load data for page assignments that don't exist.
![image](https://user-images.githubusercontent.com/3719964/42466483-12346fa0-837d-11e8-942c-81dca7f2da00.png)

**Comment by bmcutler** [comment]
Will re-open if this is still an issue.
