### ISSUE TITLE
Option to re-assign randomly the rotating section assignments of teams

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2367]
Currently teams are assigned to the rotating section of their initial member.
Add a button on the summary/overview or index page for an electronic gradeable that is set to "grade by rotating section" named "Randomly re-assign teams to rotating sections" that will take all current teams and divide them into (mostly) even groups for each rotating section.  Could do this by randomizing the list of teams and then 'dealing' them out to the rotating sections.

**Comment by Sahil333** [comment]
Can you tell me more about the button? How it will work? I made some changes so that every time a new team is created, it will randomly re-assign rotating section to all the teams for that gradeable.
