### ISSUE TITLE
Add unique key constraint between g_id and team_id in gradeable_data table

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2371]
Its all in the title.  There is a unique key constraint between `user_id` and `g_id` in the `gradeable_data` table, but not between `team_id` and `g_id`, which means we can have multiple grades for a team despite only allowing one grade per individual.

**Comment by bmcutler** [comment]
@MasterOdin 
Is this still an open/valid issue?
Is this easy to fix?  Are there any difficulties if old courses do violate uniqueness?

**Comment by MasterOdin** [comment]
This is still an issue. The fix is just doing something like `ALTER TABLE ONLY public.gradeable_data ADD CONSTRAINT UNIQUE (g_id, gd_team_id);`. I believe Submitty does a good enough job here to never violate this constraint in code currently so that we've never run afoul of it.
