### ISSUE TITLE
bug: no manual/ta grading hides all panels

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2377]
when I click on a student who has submitted I would like to see their autograde results & files.
but it's just blank.

it's only supposed to hide the rubric panel...

**Comment by MasterOdin** [comment]
We should probably also indicate on the panel button thing which options are disabled (gray out the icon and don't set a link attribute?)

**Comment by bmcutler** [comment]
We had been not displaying that rubric icon at all.  But it confused at least one instructor last term.

Actually the confusion was an instructor had visited a no-manual-grading gradeable, it didn't display the rubric and saved in the cookie "don't display rubric panel", then when the instructor visited another gradeable with manual grading the cookie hid the rubric panel and the instructor (who never actively hid the rubric panel was confused).  

So yes, I think on the no rubric gradeable we should display a message somewhere "no ta/manual grading for this gradeable".  And then make sure we're not modifying the rubric panel visibility cookie.

**Comment by jchulton** [comment]
Pull request is up: https://github.com/Submitty/Submitty/pull/2386
