### ISSUE TITLE
Prepend timestamp to queue files

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#2394]
In looking at Kevin's PR, it occurs to me that we're doing the same sort operation by time creation time in a couple places requiring that we load the entire list of files into memory to do that sort. It'd be beneficial to probably just prepend the timestamp of the file to its name and then just have it be sorted by timestamp naturally when just using an operation to get the directory list. The upside of this being then we could just use an iterator when looking at the directory since we realistically only want a file from near the top of the list or the total number of entries, neither of which require a full list traversal.

Pros:
* Don't need to sort list of files to get the "oldest" ones
* Can use iterators on the file list saving memory & time
* Easier to "bump" something up the queue (rename file instead of using `touch -d` and google
* Can easily see via filesystem generally where file is queued in relation to everything else

Cons:
* Cannot as easily find a specific queue file / general counts of queue files per course/gradeable

**Comment by bmcutler** [comment]
No, this is not a good idea.
The timestamp on the file itself is what we use for priority in grading.
Sorting by file timestamp is/should be supported by any language (right?)
The field in the json file is redundant initially, but is used when that data is carried along through autograding and into the history (used to measure wait time etc).

The real disadvantage would be if regrade was called repeatedly with overlapping sets of student assignments.  With the current naming scheme only 1 queue file would be created per student.  With this proposal there would be multiple (or we'd have to check if a another queue file with a different timestamp already existed...  ugh)
