### ISSUE TITLE
Use proper checks on GET/POST methods for controllers

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#2399]
Right now, all functions can be activated via just having something in the $_REQUEST field without any further care. We should be limiting it such that methods that must be explicitly called via $_POST require that `$_SERVER['REQUEST_METHOD']` is set to the appropriate type (GET/POST) for a given route. This is definitely necessary for #300 and an extension of the work outlined in #933.

As a side effect of doing this, we can then within our router have it validate the CSRF token automatically for any POST request which also lowers the chance of us forgetting to do that within a controller method and expose a security bug.

**Comment by zjxiaohan** [comment]
So, after going through the project, I found there are only two possible consequences: either **(1)** returning a JSON that says fail or **(2)** redirecting to the previous page and adding an error message on the top.

Probably we can just do it later after some parts of API are ready and get equal behaviour by using things like `disableRedirect` as in the diagram.

**Comment by zjxiaohan** [comment]
Close this as it is solved in #3980.
