### ISSUE TITLE
recreate_sample_courses.sh Syntax Error

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#2404]
This was the output I got from running recreate_sample_courses.sh:

>root@vagrant:/usr/local/submitty/GIT_CHECKOUT/Submitty# sudo python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh
>  File "/usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh", line 8
>    if [[ "$UID" -ne "0" ]] ; then
>                       ^
>SyntaxError: invalid syntax

**Comment by CouleeApps** [comment]
There. Command to run is now `sudo bash /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh`
