### ISSUE TITLE
Bulk PDF upload page sorts split files alphabetically

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2417]
When splitting a large pdf (say 500+ pages) into 2 page chunks, there are several hundred pdf files loaded into the page.  The order these are displayed in are sorted alphabetically, so instead of the order being:
```
<pdf_name>_0.pdf
<pdf_name>_1.pdf
<pdf_name>_2.pdf
...
```
The order is:
```
<pdf_name>_0.pdf
<pdf_name>_100.pdf
<pdf_name>_101.pdf
...
```
Which breaks the order the pages are in the source pdf.

**Comment by MasterOdin** [comment]
We probably just want to prepend all numbers such that they're the same length figuring that out and doing on [this line](https://github.com/Submitty/Submitty/blob/master/site/cgi-bin/pdf_check.cgi#L101) in pdf_check.cgi as we have total number of pages of the PDF and number of pages per split, the number of zeroes to use to pad should be easy to figure out.
