### ISSUE TITLE
Create Submitty Docker Repository

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#2425]
This will be a repository that holds Dockerfiles for basic builds for at least the following:
- [ ] python (2.7, 3.4+)
- [ ] Clang (3.8+)
- [ ] Java (8, 10)

with an easy structure/README to add further ones and instructions on how to publish to https://hub.docker.com/r/submitty/

**Comment by MasterOdin** [comment]
This has been started with [Submitty/DockerImages](https://github.com/Submitty/DockerImages) repository which will hold various components making up a docker image, with then pushing to https://hub.docker.com/r/submitty/ (example: https://hub.docker.com/r/submitty/python/)

**Comment by bmcutler** [comment]
done, right?
