### ISSUE TITLE
Stats for Verify Grader

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2440]
Add to Stats page for each electronic gradeable:

at the top of the left side (with overall % graded):

% of all components that have been verified (a.k.a. double graded - grader2 != NULL)

% of all components that grader1 is a full access or instructor OR grader 2 != NULL and grader2 is a full access or instructor.

-----------

On the left side, in the "by XX section" list.
instead of "Section 1: 9/10 (90%)" put "Section 1: 9/10 (90% graded), 5/10 (50% verified), 4/10 (40% double graded).

---------

On the right side,  in the 
"Statistics for Manually Graded Components:" list
instead of "Count: 18", put "18/20 (90% graded), 8/20 (40% verified), 6/20 (30% double graded)"

**Comment by HKaufmann-Student** [comment]
If this is still available, I would like to work on this.
