### ISSUE TITLE
More late day banner issues

### ISSUE THREAD

**Issue by jchulton** [Submitty/Submitty#2445]
If a student has an excused extension, the late day banner displays the wrong number of remaining late days.
![late days master bug](https://user-images.githubusercontent.com/11095297/42785815-cc49f6d6-8921-11e8-9ff7-44bb43081423.JPG)
Note that students are given 3 initial late days, so I don't know why the banner would display 128 remaining late days instead of 126, is it adding the 2 past due date?

Also the double counting bug seems to be back ): Basically the late day banner does not take into account the late days used on the assignment it corresponds with.
The late day banner says I only had one day left and tried to use 2
![late day banner bug](https://user-images.githubusercontent.com/11095297/42786135-0462865e-8923-11e8-8a00-aa6ef84f1566.JPG)
However, I actually had 3, I used two on this assignment (Grading Homework), as my late day information shows.
![late day banner bug 2](https://user-images.githubusercontent.com/11095297/42786194-46c063ae-8923-11e8-818e-ce062fb1f128.JPG)
 The late day banner doesn't account for this.

**Comment by bmcutler** [comment]
@ropern123 I've just unassigned you (I think you said you hadn't started)
and put @RylanOC  on instead.  Please talk if you have questions.
