### ISSUE TITLE
Sample users with cancelled submission

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2469]
All students either have no submissions for a gradeable, or one of their submissions is `Active`, but (inspired by #2467) we should have some users with a cancelled submission for a gradeable on any of the sample gradeables that are `closed` or later.  The user that does the selenium tests should have at least one of these cancelled submissions for one of the visible gradeables.

**Comment by bmcutler** [comment]
closed with PR #3848
