### ISSUE TITLE
Improve visibility of unresolved regrade request

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2487]
From the summary page if there are unresolved regrade requests, that message could be red & bold.

From the navigation page, maybe we use notification badges to display the count of outstanding regrades for the students you are assigned.

When actually viewing the ta grading page for a student with an unresolved regrade request, it should be super obvious.  (background color?  maybe that's too much?)

**Comment by sak6lab** [comment]
These are changes I am proposing that will go in my next pull request.

- red & bolded text when there are grade inquiries from summary page of a gradeable
![bolded_and_red_outstanding_grade_inquiries](https://user-images.githubusercontent.com/15002610/58888121-e4a89700-86b4-11e9-8113-c694a0bd6bd3.JPG)

- notification badges on 'regrade' button on gradeable from navigation page
![navigation_page_notification_badges](https://user-images.githubusercontent.com/15002610/58888197-0a35a080-86b5-11e9-9b45-d9d3ca35e615.JPG)

- red border on grade inquiry or regrade panel and flashing grade inquiry button on navigation panel only when grade inquiry is pending

![obvious_student_grading_grade_inquiry](https://user-images.githubusercontent.com/15002610/58888463-6d273780-86b5-11e9-9106-409d2ffe4fea.gif)

Do these changes statisfy the issue?

**Comment by sak6lab** [comment]
- got rid of notification badges on 'regrade' button

- got rid of red border on grade inquiry 'regrade' panel and flashing button in navigation panel

- instead added new exclamation icon and grade inquiry 'regrade' panel will be brought to the front **when there is grade inquiry is pending** and untoggled and only untoggled when panel is closed .
![bring_to_front_grade_inquiry_panel](https://user-images.githubusercontent.com/15002610/58912069-4550c780-86e7-11e9-83cf-24548ae20e23.gif)

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve visibility of unresolved regrade request](https://trello.com/c/jr3rCCtc/12-improve-visibility-of-unresolved-regrade-request)
