### ISSUE TITLE
Line wrap of long component names in student view of TA grades

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2504]
See attached
<img width="1155" alt="screen shot 2018-07-20 at 12 54 25 am" src="https://user-images.githubusercontent.com/5871417/42983925-8f46c24e-8bb7-11e8-9162-95051166d168.png">

If the title is longer than the screenwidth, it discards the mark indentation

**Comment by CouleeApps** [comment]
A bit of flexbox and it appears to be wrapping better:
![](https://i.imgur.com/M501Nbg.jpg)
![](https://i.imgur.com/mXzrdPg.jpg)
