### ISSUE TITLE
Question:  What is MinGrader when there is no manual grading?

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2507]
This is for electronic gradeables.
What does the model return?  
(it shouldn't be a value hidden in the form if you toggle on & off ta manual grading)

The code in #2505 can probably be refactored.

**Comment by KevinMackenzie** [comment]
Minimum grading group defaults to 1 (instructor) when creating a new gradeable regardless of if there is any manual grading enabled.  Both the new and the old gradeable model unconditionally load the database value for this property, so regardless of if manual grading is enabled, the `min_grading_group` will reflect the last saved value.  Disabling manual grading does not change `min_grading_group`.

**Comment by bmcutler** [comment]
status?

**Comment by KevinMackenzie** [comment]
This has come up a few times, but I foget what the current consensus on it is.  I know I have said that throwing an exception on this case is not a good idea.  As it stands, checks to `has manual grading` must be used in conjunction with this getter for desired behavior.  This keeps the exposure to the state of the gradeable more transparent, but does risk improper use of the interface.
