### ISSUE TITLE
pdf viewer: scroll to instructor assigned page number when component opens

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2569]
This was working, but broke with recent pdf viewer changes.

**Comment by saxocellphone** [comment]
Is done with most recent pr

**Comment by saxocellphone** [comment]
Huh I demoed this on Friday and I'm pretty sure it was working, I'll check again

**Comment by saxocellphone** [comment]
@bmcutler I tested it on masters and it worked for me. Could it be that I hardcoded "upload.pdf" as the pdf name? I thought this should only work with that filename.

**Comment by bmcutler** [comment]
It's working now.  I'm not sure what changed.
However I am seeing a small bug with the exact position of the scroll.  I believe we had the same problem before.  It doesn't scroll to the whole page or the top of the page.   It overshoots.  For example, if I want it to be on page 4, it displays the bottom 2/3 of page 4 and the top 1/3 of page 5.  It might be related to zoom, something to debug.

**Comment by bmcutler** [comment]
added that to #2593
