### ISSUE TITLE
(minor?) UI improvements to Plagiarism 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2572]
On the "main" page:

- [x] If there is a queue file in the jobs folder -OR- a finished plagiarism run (the ranking.txt file exists) there should be an entry on this page.  (currently it's only looking for ranking.txt?)

- [x] The date should be the timestamp on the ranking.txt file (or N/A if there's only a queue file for a newly created job).  I think the timestamp might be the queue time??  (not sure)

- [x] Next to each entry on the main page, add the # of students in the current term who have submitted this assignment at the time of the last run (# of subfolders in  /var/local/submitty/courses/<SEMSETER>/<COURSE>/lichen/concatenated/<GRADEABLE>/).  And the # of submissions.
(# of subfolders in /var/local/submitty/courses/<SEMSETER>/<COURSE>/lichen/concatenated/<GRADEABLE>/*/).   Format example:  "27 students, 101 submissions"

- [x] Add a boolean checkbox next to each entry on the main page for: "Enable nightly re-run".  By default this option is off.

- [x] (EDITED TO ADD)  If one of the entries has been put in the queue for reprocessing, make the re-build icon and/or date a different color?  (So we know we don't have to press rebuild again).  Maybe we can display the difference between queue file (job not started yet) and the PROCESSING_ file (job started but not completed)

- [x] (EDITED TO ADD) If any of the entries on this page is in the queue to be run, refresh the page every 30 seconds (or 10 seconds or a minute??)  We do this on other pages in the system.

On the "results" page":

- [ ] Make the left & right boxes full height.

- [x] Reduce space between the left & right file boxes.  

- [x] In all places where the user name is displayed (in drop down and selection) use "preferred first name (display name) last name <username>" (standardize to other uses on the website)

- [x] (EDITED TO ADD) Add a 'legend/key' at the top to explain what the grey/yellow/orange/red colors mean.

- [ ] I don't think there should be a "None" choice in the version dropdown menu for the left panel user.

**Comment by bmcutler** [comment]
Sounds good :)

**Comment by tushargr** [comment]
@bmcutler 
Last point in task list-
"None" option for version is required to be displayed when no user is selected in left side. Can we leave this for now.

**Comment by bmcutler** [comment]
I've unchecked the full-height of code option.  If I 'zoom out' (ctrl minus) in my browser, and make my browser tall, I still only have ~30 lines of code visible.  Hoping we can make the code window full height to the current browser size.

screenshot:
<img width="1226" alt="screen shot 2018-07-28 at 8 36 27 pm" src="https://user-images.githubusercontent.com/5871417/43361740-2a3e21a8-92a6-11e8-8831-5b2f5b8aa865.png">

Yes, it's ok to leave the version 'none' as is.

**Comment by bmcutler** [comment]
Also, please include the user id in angle brackets after the first & last name (github lost my angle brackets above)

<img width="231" alt="screen shot 2018-07-28 at 9 16 04 pm" src="https://user-images.githubusercontent.com/5871417/43361908-7b18678c-92ab-11e8-978e-4bc16c2bb2e1.png">

**Comment by bmcutler** [comment]
Unfortunately it's not a request for a specific # of lines.  Ideally it would work on any monitor size, on any browser height, on any zoom (and re-adjust if I modify the browser height or zoom).
I have seen different # of lines displayed, but it doesn't refresh.  Let's ask @CouleeApps  tomorrow.

**Comment by CouleeApps** [comment]
I would suggest using `height: calc(100% - Npx)` for some N that makes it line up. If that doesn't work you might get success by using flexbox, but that may require changing the global header/footer template.
