### ISSUE TITLE
Upload Photos Firefox Compatability

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#2575]
Currently Upload Student Photos works correctly in Chrome.

In Firefox (running Quantum 61.0.1 (64-bit)), I don't see the icon for "no photo uploaded" though I do see the text. If I try to upload an image (single PNG or zip, even using the zips provided in `sample_files/user_photos`) the browser appears to do *something* but on reload no photos are assigned, and `ssh`ing into the VM there's nothing in the course's uploads directory.

**Comment by jn7070** [comment]
I think Firefox works now with my latest update to upload images part 3 which solves the automatic refresh and it's on master branch too.
