### ISSUE TITLE
prevent wrapping between mark box & points

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2577]
<img width="117" alt="screen shot 2018-07-27 at 10 18 54 am" src="https://user-images.githubusercontent.com/5871417/43326318-83bb2e68-9186-11e8-97a1-68384c534faa.png">

**Comment by CouleeApps** [comment]
What browser is this? Not happening to me with Chrome.

**Comment by bmcutler** [comment]
Chrome on Mac.  Actually if I ctrl +- zoom in & out it changes from wrap to no wrap and back.  
It appears to still be a problem, I'm on master branch. 
Shift reload doesn't help.
I can show you tomorrow if you don't believe me :)

**Comment by bmcutler** [comment]
Also the text for the custom mark wraps to the next line.
Both of these problems happen when you zoom out.  (in chrome on mac)
<img width="485" alt="screen shot 2018-08-03 at 2 40 49 pm" src="https://user-images.githubusercontent.com/5871417/43659863-44925c84-972b-11e8-9838-42bdb1065b46.png">
