### ISSUE TITLE
PDF annotations - remaining work

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2593]
from: https://github.com/Submitty/Submitty/pull/2521

- [x] zoom is mostly broken
- [x] erase
- [ ] download pdf with annotations
- [x] permissions checks (who can view & download the annotated pdf)
- [x] sometimes the rendering is weird(?)
- [x] refactor/share js code
- [x] put the forked code in pdf-annotate.ps, check it out, and use it
- [x] the 'right slide/full screen view' button is broken for all non pdf files (?)
- [x] the filename link for a pdf should do the same thing as the 'right slide/fullscreen view' button

- [x] EDITED TO ADD: scroll to specified page is sometimes off.  Sometimes overshoots. For example, if I want it to be on page 4, it displays the bottom 2/3 of page 4 and the top 1/3 of page 5. It might be related to zoom?

@saxocellphone Make sure this list is complete, and re-order to match our whiteboard discussion

**Comment by saxocellphone** [comment]
Basically all done, except for download, which will be later
