### ISSUE TITLE
Bugfix for Undefined Function error (could be older version of postgres?)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2597]
I had to revert PR #2588 due to the following error (just from trying to load the navigation page)

Make sure we're using the same ordering as elsewhere in the system.

-----------------------------

12:23:15 07/29/2018 - FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 175) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);

Message:
SQLSTATE[42883]: Undefined function: 7 ERROR:  function pg_catalog.substring(integer, unknown) does not exist
LINE 6: ORDER BY SUBSTRING(rotating_section, '^[^0-9]*'), COALESCE(S...
                 ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Strack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(651): app\libraries\database\AbstractDatabase->query('
SELECT count(*) as cnt, rotating_section
FROM users
WHERE rotating_section IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
GROUP BY rotating_section
ORDER BY SUBSTRING(rotating_section, '^[^0-9]*'), COALESCE(SUBSTRING(rotating_section, '[0-9]+')::INT, -1), SUBSTRING(rotating_section, '[^0-9]*$')', Array)
#1 /usr/local/submitty/site/app/models/gradeable/Gradeable.php(955): app\libraries\database\DatabaseQueries->getTotalUserCountByGradingSections(Array, 'rotating_section')
#2 /usr/local/submitty/site/app/views/NavigationView.php(543): app\models\gradeable\Gradeable->getGradingProgress(app\models\User)
#3 /usr/local/submitty/site/app/views/NavigationView.php(231): app\views\NavigationView->getGradeButton(app\models\gradeable\Gradeable, 5)
#4 /usr/local/submitty/site/app/views/NavigationView.php(200): app\views\NavigationView->getButtons(app\models\gradeable\Gradeable, app\models\gradeable\GradedGradeable, 5)
#5 unknown file(unknown line): app\views\NavigationView->showGradeables(Array, Array)
#6 /usr/local/submitty/site/app/libraries/Output.php(114): call_user_func_array(Array, Array)
#7 unknown file(unknown line): app\libraries\Output->renderTemplate('Navigation', 'showGradeables', Array, Array)
#8 /usr/local/submitty/site/app/libraries/Output.php(83): call_user_func_array('self::renderTemplate', Array)
#9 /usr/local/submitty/site/app/controllers/NavigationController.php(89): app\libraries\Output->renderOutput('Navigation', 'showGradeables', Array, Array)
#10 /usr/local/submitty/site/app/controllers/NavigationController.php(23): app\controllers\NavigationController->navigationPage()
#11 /usr/local/submitty/site/public/index.php(260): app\controllers\NavigationController->run()
Extra Details:
	query: 
SELECT count(*) as cnt, rotating_section
FROM users
WHERE rotating_section IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
GROUP BY rotating_section
ORDER BY SUBSTRING(rotating_section, '^[^0-9]*'), COALESCE(SUBSTRING(rotating_section, '[0-9]+')::INT, -1), SUBSTRING(rotating_section, '[^0-9]*$')
	parameters:
		1
		2
		3
		4
		5
		6
		7
		8
		9
		10
		11
		12
		13
		14
		15
		16
		17
		18
		19
		20
		21
		22
		23
		24
		25

**Comment by MasterOdin** [comment]
The error is because we're applying a string function (substring) to an integer (rotating_section), not because of postgresql version.

Rotating section is always an integer so we don't need to do any sorting algorithm like we do with registration section (which is a string).
