### ISSUE TITLE
Improve migration instructions for database migrations

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2615]
There are currently 3 different ways that contributors are getting around the problem of "How do I know if a column / table already exists before I make it in the `up` function".  We should use one method and document how it should be done.  The way that I find works well and is pretty clean is something like:
```
cursor.execute("SELECT * FROM regrade_requests LIMIT 0")
colnames = [desc[0] for desc in cursor.description]
if 'team_id' not in colnames:
            cursor.execute('ALTER TABLE regrade_requests ADD COLUMN team_id VARCHAR(255)')
            cursor.execute('ALTER TABLE regrade_requests ADD CONSTRAINT regrade_requests_fk2 FOREIGN KEY (team_id) REFERENCES gradeable_teams(team_id)')
```
This option allows the `up` function to have a separate block to execute when the column doesn't exist yet.

Something similar can probably be achieved with entire tables, but I have not needed to do that yet myself.

**Comment by KevinMackenzie** [comment]
I wasn't dropping the column in `down` b/c the migrations doc page said to avoid destructive db changes in `down`.

**Comment by MasterOdin** [comment]
The way to check for a column in a table is to use the utility function [table_has_column](https://github.com/Submitty/Submitty/blob/master/migration/migrator/db.py#L104-L117) in the Database class, or for the above example:
```
if database.table_has_column('regrade_requests', 'team_id'):
    pass
```
