### ISSUE TITLE
Lichen:  Sort assignments by due date

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2618]
In 2 places:  the main lichen page, and in the drop down menu on create edit gradeable
Sort the gradeables by the due date (oldest assignments at the bottom of the list -- like other places on Submitty).

Include the due date in the text in both places, e.g.:

"Grades Released Homework (due: 2018-07-30 23:59:59 -0400)"

**Comment by williamjallen** [comment]
I am nearly done with a PR which solves this issue.  Currently, I am sorting the lists and including the due date for each gradeable on the main Lichen page (see screenshot).  Adding the due date to the dropdown on the configure gradeable page makes the dropdown cluttered, almost 3/4 of the width of my page in fact.  Should I still implement this feature or leave it out for now?

**Comment by bmcutler** [comment]
I won't argue with 3 year ago me.  I was looking at the prototype with real course data and was confused by the chaotic order that assignments appeared.
If you've got it coded up add it to the PR.
This is a part of the system with a lot of data -- it isn't necessary pretty.

**Comment by williamjallen** [comment]
Ok, I'll go ahead and add it to the PR.
