### ISSUE TITLE
Success and error messages hidden behind nav bar

### ISSUE THREAD

**Issue by ropern123** [Submitty/Submitty#2656]
When using the top bar of the site wrapper, error and success messages go behind the admin nav bar and become difficult to read.

**Comment by MasterOdin** [comment]
Need to probably lower the z-index of the nav bar (it's at 9999 right now) and raise the z-index of the alert classes (it's at the default) such that alert > nav.

**Comment by sarthak77** [comment]
Can I take up this issue?

**Comment by sarthak77** [comment]
Is someone working on the issue or i can take it?
