### ISSUE TITLE
Make Sure Room Templates Are Up To Date

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#2657]
Make sure that room templates are using the newest version of the room and are using any appropriate visual features, labeling, arrows drawn on the diagram, notes about counting / left handed desks / etc.

**Comment by MasterOdin** [comment]
I've never looked at these things, but we should probably make sure we're outputting somewhere on the output of these seating charts when they were last updated as well just for a clear marking especially as the live server may lag the development.
