### ISSUE TITLE
Rotating sections broken :(

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2671]
From the setup sections page:
Attempting to redo the rotating sections completely...

FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 175) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);

Message:
SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "sections_rotating" violates foreign key constraint "gradeable_teams_rotating_section_fkey" on table "gradeable_teams"
DETAIL:  Key (sections_rotating_id)=(1) is still referenced from table "gradeable_teams".

Strack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(1194): app\libraries\database\AbstractDatabase->query('DELETE FROM sections_rotating')
#1 /usr/local/submitty/site/app/controllers/admin/UsersController.php(361): app\libraries\database\DatabaseQueries->deleteAllRotatingSections()
#2 /usr/local/submitty/site/app/controllers/admin/UsersController.php(37): app\controllers\admin\UsersController->updateRotatingSections()
#3 /usr/local/submitty/site/app/controllers/AdminController.php(58): app\controllers\admin\UsersController->run()
#4 /usr/local/submitty/site/public/index.php(240): app\controllers\AdminController->run()
Extra Details:
	query: DELETE FROM sections_rotating
	parameters:

**Comment by bmcutler** [comment]
I cannot reproduce this now.  It was broken before the demo and during the demo today.  We did not have valid rotating sections.  I did not install new code on the server, but now it seems to work (I was able to create valid rotating section & assign students).  Not sure what changed except we made some gradeables, had some test student submissions, and did some grading.   Still try to prevent/handle the above error.

**Comment by bmcutler** [comment]
ALSO....  if rotating sections have NOT been configured yet (no sections, everyone in NULL) but the instructor attempts to select rotating in create/edit gradeable, have some scary red message appear saying "Go setup rotating sections first, then return to this page", perhaps with a link to the setup sections page.

**Comment by CouleeApps** [comment]
The main error is because gradeable_teams has a foreign key reference (gradeable_teams_rotating_section_fkey) to sections_rotating. Deleting the sections to recreate them violates this key constraint. It seems that students have their sections set to null first and then are automatically assigned rotating sections. The fix here is to make teams work in the same way.

**Comment by CouleeApps** [comment]
Fixed the error. Going to put the scary message in its own issue because it's less urgent.
