### ISSUE TITLE
Order and groupings for options on "Course Settings" page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2674]
[ notes from meeting -- comments welcome after draft revision implemented ]

Basic Course Settings:
full course name
course url
enable discussion forum

Submission Settings:
upload message
course autograding configuration directory
keep previous files uploaded
version control type
version control base url

Late Day Settings:
initial allowed late days
default max late days

TA/Instructor Manual Grading Settings:
Returned Grades Message (note name change)
Regrade Requests Allowed
Regrade Warning Message

Final Grades and Customized Message Settings:
Display Rainbow Grades
Display Seating
Display Custom Banner

**Comment by MasterOdin** [comment]
Do we want to break each section into its own tab like the create gradeable page?

**Comment by CouleeApps** [comment]
This was completed in #2697
