### ISSUE TITLE
File upload:  By student vs Scanned Exam

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2676]
[ notes from meeting -- comments welcome after draft revision implemented ]

Instead of 3 radio buttons, have 4.  (backend is still 3 core types)

Gradeable Type:
O  Student will upload files
O  TA/Instructor will bulk upload scanned .pdf files
O  Checkpoints (simple data entry)
O  Numeric/Text (simple data entry)

_The difference between the first two types will be stored in a new database variable (I think it needs to be new)._  

On the autograding/submissions tab, a new question for that variable:

hide things below here under an "advanced options expander thing"

Will this gradeable be scanned and uploaded as bulk pdfs by the TA/Instructor?
O Yes  O No   
_(this will be initialized based on choice on first first page, but can be edited which will toggle the choice on the first page if we go back there)_

What can students do?

View the gradeable on the course home page?  O Yes  O No  O Yes, but only when grades are released
Make new submissions?    O Yes  O No
Download submission files?   O Any version  O Active version only  O None

_If "yes" to bulk pdf these default/reset to "When released", "No", "Active only"
If "no" to bulk pdf these default/reset to "Yes", "Yes", "Any version"_

_If/when "No" is selected for View the gradeable, then make submissions and download files are greyed out or(?) hidden (and maybe also set to "no" and "none")._

**Comment by KevinMackenzie** [comment]
With the `student submit`, `student view,` `student download`, and `student download any version` properties we have in the database, we have enough information already to differentiate a pdf exam upload  from a student-submitted assignment (since you will never have a bulk pdf exam that students can upload).  This issue should be just a matter of UI changes.

**Comment by bmcutler** [comment]
Actually I disagree, an instructor may choose to toggle those settings independent of the student vs instructor upload choice.

After allowing student submissions, I would like to temporarily disable student view, submit, & download while I'm re-running a programming contest with the full test suite.  When I release the contest results I will re-enable view, but not submit.  You can't infer the student vs instructor from the other variables.

**Comment by KevinMackenzie** [comment]
I was thinking that `exam upload` would only imply that `student submit` is false, but there are cases where the `student submit` is false and the gradeable isn't a scanned exam, so the implication doesn't go both ways and the two booleans aren't synonymous.  

The scanned exam is a use-case of the electronic file submission gradeable type and typically has certain values for some of the four booleans I mentioned, but isn't required to.  It also doesn't add any behavior beyond what the `student submit` boolean already controls.

In the Create Gradeable page, if we introduce this distinction as different use cases (gradeable "templates", ignoring the existing use of the term) for the electronic file submission type and allow the user to load these presets at any time, we can make clear what a "scanned exam" means compared to other configurations of the electronic gradeable by explicitly labeling the values each use-case sets.  While I don't see very many of these 'use cases' existing, I think it would be an effective way to communicate what a "scanned exam" does.
