### ISSUE TITLE
Calendar view/picker for Create/Edit Gradeable Dates

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2684]

**Comment by VictorLi718** [comment]
I could only find two datetime pickers with the functionality of time zone. One is the old-style one with jquery that we already have. The other one requires bootstrap 3 and 4 which we don't install. So far I can't find a suitable one for it..

**Comment by VictorLi718** [comment]
#3285

**Comment by VictorLi718** [comment]
Close by #3285
