### ISSUE TITLE
Course materials is broken (students cannot see)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2688]
It seems we are not saving the "share to student on DATE" selections.
That WAS being saved to a json by the submitty_php, but I don't see that file right now.
Permission error probably.

**Comment by CouleeApps** [comment]
At least on my local vagrant machine, the file is still being recreated even if I delete it. It may be the case that, on the live machine, it has some sort of different permissions. Without the ability to know what's different on the live server, the best solution I can think of at this moment is to add an error if/when saving fails.
