### ISSUE TITLE
Expand flexibility of file permissions, use ACL?

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#270]
It is not possible right now to give write access to co-instructors (or an instructor and a head TA) and read-only access to a group of TAs (& hwphp & hwcron).  This more complex permission could be done with ACLs.

**Comment by inlinefan** [comment]
It will result in a small performance hit that will need to be evaluated before going live.  We are also likely to need to increase the number of groups per class in order to achieve the desired level of granularity.

**Comment by bmcutler** [comment]
Currently we use a single group for instructors / TAs for "data structures" for this term and all files from all previous terms.  We should consider making 2 groups...  "data structures this term" and "data structures all prior terms" so that TAs who do not *need* access to prior semesters have only the minimum access they need.
