### ISSUE TITLE
Add version number/string to CSS to force reload of cached files on re-install

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2702]
(similar to the magic sauce we already have for javascript files)

**Comment by CouleeApps** [comment]
What's strange about this is that we _do_ add a timestamp version to the end of the css files. For some reason it just doesn't work in some cases.

**Comment by MasterOdin** [comment]
I found one on the TA Grading page:
```
<link rel="stylesheet" type="text/css" href="css/pdf/toolbar_embedded.css"/>
```

**Comment by bmcutler** [comment]
@mktung 
Not sure if this is still an open/unresolved issue.  Please search & fix or close issue.
Thanks
