### ISSUE TITLE
Date changes not saving

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#2704]
On the Edit Gradeable page, changing a date results in the "Saving..." notification but no success notification and the date is not saved.

**Comment by KevinMackenzie** [comment]
I can't seem to reproduce this behavior.  Can we get details about: What type of gradeable, if ta grading enabled?

**Comment by holzbh** [comment]
![submittykonstan](https://user-images.githubusercontent.com/26691043/43922643-59cd86c0-9bed-11e8-8389-abcf8a5512c8.png)

That's the example that was provided. He uses the wording "check off" in the e-mail so I'm assuming this is a checkpoints-style gradeable.
