### ISSUE TITLE
Show error when using rotating sections before they are set up

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2708]
From #2671

> ALSO.... if rotating sections have NOT been configured yet (no sections, everyone in NULL) but the instructor attempts to select rotating in create/edit gradeable, have some scary red message appear saying "Go setup rotating sections first, then return to this page", perhaps with a link to the setup sections page.

**Comment by VictorLi718** [comment]
For this problem, I search through all related codes and I guess I can't find this error message anymore. Maybe it has been already solved? And these are the screenshots when I deleted all the rotating section from database. Does these means everyone is in NULL?
<img width="667" alt="Screen Shot 2019-03-21 at 22 44 56" src="https://user-images.githubusercontent.com/30506009/54797811-166c9e80-4c2c-11e9-8374-1dd081852b3c.png">
<img width="1653" alt="Screen Shot 2019-03-21 at 21 24 39" src="https://user-images.githubusercontent.com/30506009/54797812-166c9e80-4c2c-11e9-84b5-60e78b6788fa.png">
<img width="1205" alt="Screen Shot 2019-03-21 at 22 44 42" src="https://user-images.githubusercontent.com/30506009/54797813-166c9e80-4c2c-11e9-954d-8331df1a9175.png">

**Comment by VictorLi718** [comment]
I have tried to create a completely new course. But there is still no such problem. It will show 
<img width="1120" alt="Screen Shot 2019-04-02 at 6 48 24 PM" src="https://user-images.githubusercontent.com/30506009/55441315-5c086000-5578-11e9-8694-d74231c18365.png">

**Comment by VictorLi718** [comment]
Showing error message when there is no rotating section.
