### ISSUE TITLE
Allow reloading of active assignment for graded rubrics

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#271]
This allows for students who selected the wrong active assignment to easily allow them to switch it and request a regrade if they so want. Right now a DB update is required.

**Comment by bmcutler** [comment]
I think this could be a TA-controlled button on the regular TA interface.   Make it clear that this is an unusual refresh.

**Comment by bmcutler** [comment]
related to issue #293?

**Comment by bmcutler** [comment]
We do not want to make it easy for students to request spurious regrades.
Email or office hours is the appropriate way to request regrades.
