### ISSUE TITLE
Small tweaks to UI

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2725]
- [x] Make left bar icons the same size when collapsed/uncollapsed (so they don't move vertically when toggling this option).  Probably a size in between the current sizes?

- [x] The hover text for "Collapse Sidebar" should be "Un-Collapse Sidebar" or "Expand Sidebar" when it is collapsed.

- [x] Should it be "Manage Students" and "Manage Graders" instead of just "Students" and "Graders" in the sidebar?  (group says yes)

- [x] It could also be "Manage Sections" instead of "Setup Sections".  (group says yes)

- [x] Make it just "Student Photos" (be consistent with "Course Materials").  I originally had requested that both of these are prefixed with "Upload" if the instructor hasn't uploaded anything yet, but that's too complicated/unnecessary.

- [x] Put edit gradeable pencil icon all the way on the left of each gradeable row on the home/navigation page.

- [x] Leave the delete gradeable icon where it is (after the gradeable name) but switch to a black trashcan.

- [x] The create/edit gradeable tabs wrap terribly on a middle/small width screen:
     Make sure to put line breaks in the right places.  And probably reduce the space between the tabs, and reduce the extra space on some of the tabs.

<img width="922" alt="screen shot 2018-08-15 at 1 10 44 pm" src="https://user-images.githubusercontent.com/5871417/44161903-a7730a00-a08c-11e8-8510-667cc635b192.png">
  
- [x] Replace all (in ui text) 'auto-grading' with 'autograding'

- [x] Several of the text boxes on the Course Settings page are too small.  When a sentence length string is expected use a bigger box.

Edited to add: 
- [x] After group discussion:  Cut the "Quinn" from the top of the list.  Instead make it "Logout Quinn" at the bottom.  A little awkward perhaps but then there are no entries in the sidebar without a link&icon, and developers still have a shortcut to remind them who they are logged in as.  We can change it later if someone has a better design.

- [x] If the instructor has specified an external course home page URL, that should be the first link and labeled "Home" on the side bar.  It should be the top link.  Maybe "Course Home" goes to the external URL (if provided, omit this from sidebar if it was not provided).  And "Submitty Main" or "Submitty Navigation" on the sidebar which goes to the navigation/home page.

**Comment by bmcutler** [comment]
Oh, and I think e84848 might be a better warning/red color (more grey, at least to me looks better on the white/lighter background).

**Comment by bmcutler** [comment]
And I think the green of the buttons should match the green of the progress meters under the grading buttons.  I like the progress bar green better (5fb760).

But to chose the final final colors perhaps a color picker tool should be used :)

**Comment by CouleeApps** [comment]
Some more thoughts:

- Homepage buttons need horizontal alignment for the text so it forms columns
- "Gradeables" page ... the term "Gradeable" is likely confusing to students who are not familiar with Submitty ... not sure if there is something better. 
- If there are no gradeables, the Gradeables page says "There are currently no assignments posted." Assignments vs gradeables?
- Some pages don't resolve sidebar highlights (eg goto forum and click a different post, nothing is highlighted)
- Homepage should not have sidebar, put log out in the About You panel
- Banner messages are overlapping the header, should move them down into the main page body
- Danger/success buttons are too bright. https://contrastchecker.com/ is very useful for picking colors that are accessible. Curious to know if VPAT considers this.

**Comment by bmcutler** [comment]
Gradeables encompasses all things on that page (labs, quizzes, projects, etc).  We had a small group discussion and decided it was a Submitty term we want the users to learn :)  Yes, the page should say "no gradeables available"

**Comment by VictorLi718** [comment]
closes #3019

**Comment by VictorLi718** [comment]
All the checkpoints has been finished.
