### ISSUE TITLE
History of student actions on active version & cancelled homework

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#273]
Right now we only store the final state of the "active" assignment in the student's "user_assignment_settings.json" file. 

The value is set when the student submits a new version (it automatically sets the most recent/highest version number as active).  It is set to zero (an invalid number) when the student hits "cancel".  Or the student can select any version and change active to that version.

This is related to Issue #271.  The value is read and stored when the TA first grades the assignment and late days are charged.  If a student changes the value after the TA has graded, it doesn't affect the grade or the late days.

In the same file, user_assignment_settings.json we can store the full history of the changes to that variable in addition to the final value.  Having the full history of changes to this variable (date/time & value) will allow us to investigate unusual grading situations.

We can & should also store the full history of grading and regrading of the versions of this assignment (date/time, auto grade awarded, who triggered the batch regrade action, maybe a message about why).  Maybe not stored in this same user_assignment_settings.json file (in the submissions directory, written by hwphp), since we'll need to watch out for race conditions.  Maybe this history should be stored in the results directory (since that's written by hwcron).

**Comment by ZishanHuang** [comment]
In pull request #357 , the active version history is added to the user_assignment_settings.json.

**Comment by bmcutler** [comment]
created grade_history.json file in PR #479
