### ISSUE TITLE
Grading UI Not Obviously Scalable At Some Resolutions

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#2734]
**Edit:** It also means that I can't see all of the sidebar buttons... original issue follows below:

Scale (Windows, not browser zoom): 250%
Resolution: 3200x1800
Browser: Chrome

See the attached image, that's my entire browser. There's no vertical scrollbar on the far right, and the down arrow key will be interpreted as a hotkey for the rubric panel (which is fine, but this is the other way I might try to scroll on most webpages), and the draggable corner for the red and black boxes is hidden because it's below the "bottom" of my browser. Mentioning it now, though I'm not sure we have anything we want to do about it short term. I think we discussed at some point putting draggable "resize" triangles on all four corners of each box, which would mostly solve this problem (though it might still be unclear you can MOVE the box up, not just resize it).

This is a bit of an unusual view, but this is how my laptop shipped ; I don't think I've ever changed the display settings or scaling.

![cutoffgradingui](https://user-images.githubusercontent.com/26691043/44237514-bdf98e00-a17e-11e8-876a-6b1fb16e1f93.PNG)

**Comment by bmcutler** [comment]
@andrewaikens87
This is related to your discussion forum scroll nightmare.
Can you describe the bug and/or the fix?

**Comment by bmcutler** [comment]
related / duplicate #3412
