### ISSUE TITLE
Pressing "infinity" on a create/edit gradeables date destroyed my course

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2763]
Creating a new gradeable,
pressed "infinity" on the grades released date
Got "internal server error" popup
Edited it back from 9999 to 2018 December
It said "saving..." in the upper (but never saved)
Now when I go to gradeables I get the frog robot.

I'll see what's broken in the database and manually fix it...  but please fix this urgently.

**Comment by bmcutler** [comment]
Hmm, cannot immediately reproduce on vagrant machine.

**Comment by bmcutler** [comment]
11:28:27 08/24/2018 - FATAL ERROR
app\exceptions\ValidationException (Code: 0) thrown in /usr/local/submitty/site/app/models/gradeable/Gradeable.php (Line 477) by:
            throw new ValidationException('Date validation failed', $errors);


Message:
Date validation failed

Strack Trace:
#0 /usr/local/submitty/site/app/models/gradeable/Gradeable.php(545): app\models\gradeable\Gradeable->assertDates(Array)
#1 /usr/local/submitty/site/app/models/gradeable/Gradeable.php(221): app\models\gradeable\Gradeable->setDates(Array)
#2 /usr/local/submitty/site/app/libraries/database/PostgresqlDatabaseQueries.php(1682): app\models\gradeable\Gradeable->__construct(app\libraries\Core, Array)
#3 unknown file(unknown line): app\libraries\database\PostgresqlDatabaseQueries->app\libraries\database\{closure}(Array)
#4 /usr/local/submitty/site/app/libraries/database/DatabaseRowIterator.php(56): call_user_func(Closure, Array)
#5 /usr/local/submitty/site/app/libraries/database/DatabaseRowIterator.php(37): app\libraries\database\DatabaseRowIterator->next()
#6 /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php(206): app\libraries\database\DatabaseRowIterator->__construct(PDOStatement, app\libraries\database\PostgresqlDatabase, Closure)
#7 /usr/local/submitty/site/app/libraries/database/PostgresqlDatabaseQueries.php(1767): app\libraries\database\AbstractDatabase->queryIterator('
            SELECT
<SNIP>
#8 /usr/local/submitty/site/app/models/gradeable/GradeableList.php(72): app\libraries\database\PostgresqlDatabaseQueries->getGradeableConfigs(Array)
#9 /usr/local/submitty/site/app/controllers/NavigationController.php(37): app\models\gradeable\GradeableList->__construct(app\libraries\Core)
#10 /usr/local/submitty/site/app/controllers/NavigationController.php(27): app\controllers\NavigationController->navigationPage()
#11 /usr/local/submitty/site/public/index.php(268): app\controllers\NavigationController->run()
Extra Details:
	grade_released_date: Invalid date-time value!

URL: https://submitty.cs.rpi.edu//index.php?semester=f18&course=csci1200&component=navigation
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by bmcutler** [comment]
These 4 dates all had year = 10000

I manually:
update electronic_gradeable set eg_team_lock_date='2018-12-31 23:59:59' where g_id='hw01';
update electronic_gradeable set eg_regrade_request_date='2018-12-31 23:59:59' where g_id='hw01';
update gradeable set g_grade_released_date='2018-12-31 23:59:59' where g_id='hw01';
update gradeable set g_grade_locked_date='2018-12-31 23:59:59' where g_id='hw01';

Please allow the system to load webpages even if the dates are screwed up.  If the database doesn't prevent these values from being inserted, the website still needs to load.

**Comment by bmcutler** [comment]
Also it appears the database is not storing the timezone, the dates are all 3:59+00
(which is a change from how we did it before and probably causing #2762)

**Comment by KevinMackenzie** [comment]
time zones aren't stored in the database.  The `timestamp with timezone` type in the database only affects how dates are interpreted when saving date strings to the database.

**Comment by KevinMackenzie** [comment]
Closed by #2765
