### ISSUE TITLE
Add constraint to prevent dates later than early year 9999

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2772]
Most parts of the system have problems with years larger than 4 digits.  The `Infinity` button on the Edit Gradeable page for a long time set the date to be the last moment before year 10000 in the timezone of the user, which meant that the date would be early 10000 in other time zones, which is 5 digits (bad!).  We should add constraints to the database that prevent dates from being this close to year 10000 (i.e. Jan 1, 9999 as a max).  Any existing dates later than this should be clamped to this value.

Additionally, the php should enforce this limit and fail to load dates later than that specified in the database constraint (at the very least for the gradeable's date properties)

**Comment by MasterOdin** [comment]
So in doing this, the constraint for the DB/PHP should be "03/01/9999 12:00:00" while the "soft limit" (ie. don't let the UI stuff) go beyond "01/01/9999 12:00:00" which should also make implementation easier with regards to potential timezone shifts.

**Comment by bmcutler** [comment]
Duplicates Issue #2735
