### ISSUE TITLE
The autograding score for the different submissions versions is often wrong

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2785]
The numbers in the dropdown are (sometimes) wrong
I don't see a pattern in what's breaking.
<img width="686" alt="screen shot 2018-08-29 at 12 24 57 am" src="https://user-images.githubusercontent.com/5871417/44765291-1ab35c00-ab22-11e8-9f1c-071ca66cd28e.png">
<img width="624" alt="screen shot 2018-08-29 at 12 25 09 am" src="https://user-images.githubusercontent.com/5871417/44765292-1ab35c00-ab22-11e8-99be-537fecacac2b.png">

**Comment by hbh7** [comment]
I've got the same issue (shown [here](https://f.hbh7.com/_bczs29.png))
It seems to me that they're reversed (so 1 is 3, 2 is still 2, and 3 is 1) although I haven't done further testing

**Comment by bmcutler** [comment]
Also (perhaps unrelated) the totalling of the autograding test results on the page is often wrong.
Maybe I should make a new issue for this.
