### ISSUE TITLE
Dates on forum posts look buggy (appears to be UTC rather than timezone adjusted)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2786]
Probably related to #2762 
Happening on our production server.
timezone is correctly set to America/New York.

(cannot reproduce this bug on my vagrant box)

I posted this ~ 2pm
<img width="302" alt="screen shot 2018-08-29 at 5 06 34 pm" src="https://user-images.githubusercontent.com/5871417/44815600-ef764e80-abad-11e8-976b-e1f9494c4fbf.png">

**Comment by Aaron1011** [comment]
I'd like to work on this.

**Comment by andrewaikens87** [comment]
@bmcutler can you please post the timestamp column data for the post displayed above?

**Comment by bmcutler** [comment]
id | thread_id | author_user_id |           timestamp           
----+-----------+----------------+-------------------------------
  2 |         2 | cutler         | 2018-08-29 18:16:08.777392+00

**Comment by andrewaikens87** [comment]
When you are in the course database and run `show timezone;` what does it return? Might have to run something like: `ALTER DATABASE db_name SET timezone to 'America/New_York';` and then `SELECT pg_reload_conf();` to reload the conf files. This should hopefully change the timestamp to have a -04 rather than the +00.

**Comment by MasterOdin** [comment]
Realistically, we should be loading from the database and casting the
timezone set in the config and not relying on the DB to store the exact
timezone.

**Comment by bmcutler** [comment]
on the server:
submitty_s18_csci1200=# show timezone;
 TimeZone 
----------
 UTC
(1 row)

on my vagrant:
submitty_f18_sample-# ;
 TimeZone  
-----------
 localtime
(1 row)


looks like you're on to something...

**Comment by bmcutler** [comment]
In my debugging I have found that twig's formatting displays correctly: (in local timezone)
<h3 class="upperinfo-right">Due: {{ due_date|date("m/d/Y @ H:i") }}</h3>
<h3 class="upperinfo-right">Due2: {{ formatted_due_date }}</h3>

And php formating is incorrect (ignores timezone, stays in UTC)
'due_date' => $gradeable->getSubmissionDueDate(),
'formatted_due_date' => $gradeable->getSubmissionDueDate()->format($DATE_FORMAT),

Due displays correctly
Due2 displays incorrectly

**Comment by andrewaikens87** [comment]
To find the default timezone settings for php in interactive mode (`php -a`): `echo date_default_timezone_get();`

**Comment by bmcutler** [comment]
I set the vagrant box db to have timezone utc, but that didn't break the timezones on the vagrant machine...  even with the pg_reload_conf.  Missing something...

**Comment by bmcutler** [comment]
that looks ok

php > echo date_default_timezone_get();
America/New_York
