### ISSUE TITLE
deleted thread/post may still appear in notifications?

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2787]
I made a new thread & post in a brand new course
Then realized I made it from the wrong account
So I deleted it and then reposted it from the correct account
If I go to "show all" in notifications, it only lists one thread (it appears to be the first one)

When I click on it I get this popup:
<img width="663" alt="screen shot 2018-08-29 at 5 08 17 pm" src="https://user-images.githubusercontent.com/5871417/44815772-71ff0e00-abae-11e8-8f43-c14f3e6c9ece.png">

Not sure if its because the title & contents of the 2 threads are identical?  It should be doing everything by thread/post id, right?

**Comment by bmcutler** [comment]
When I logged in from a 3rd account I now see 2 notifications.  

So that's where my confusion was coming from, apparently I am never 'notified' of my own posts?   I personally would like to see all notifications, even from myself.  (But I'll leave that to a group discussion/decision.)

But more importantly, I think we should delete notifications of deleted threads/posts.  Or at least not show them in the "show all" option.  Or possibly just have it as a greyed out "<deleted thread/post> " (since you can't view it if you click on it).  Design discussion may be needed.

**Comment by MasterOdin** [comment]
My view on this would be that:
1. You should not see notifications of actions that you cause. It would just cause confusion as I'd only expect to be notified of viewing a thread such that something happened I don't know about.

2. If you delete a thread/post, the notification that is associated with it should also be deleted. The only person that might have an interest in notifications of deleted things would be instructors I guess, but unless they have some way of viewing the content, it just seems like it'd end up being noise.

**Comment by scopeInfinity** [comment]
Hi,
It is just like you have mentioned, the current implementation doesn't generate a notification to a user if it was triggered by the same user.

And from my side, both greying out or deleting notifications for deleted posts/thread looks good to me.
