### ISSUE TITLE
"My Late Days" on a class with no assignments => Fatal Error

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2793]
Happening live on production for Network Programming

**Comment by saxocellphone** [comment]
I tested it on blank course and it doesn't seem to be happening

**Comment by CouleeApps** [comment]
As it's the production server, I don't get an error message... @bmcutler is there anything in the logs?

Also, it seems like the class actually has one gradeable, and it's a future assignment (no tas). Crashing on accessing my late days as a student.

**Comment by bmcutler** [comment]
reopen if still a bug.
