### ISSUE TITLE
Notifications Options

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2797]
Set of checkboxes somewhere?
Notify me of:
* New announcements (cannot uncheck)
* Replies to my thread (cannot uncheck)
* My thread/post was edited or deleted or merged (cannot uncheck)
* Replies to a thread that I have posted in (off by default)
* All new threads (off by default)
* All new posts (off by default)
* A thread/post was edited or deleted or merged (only available to instructors, off by default?)

other things?

**Comment by andrewaikens87** [comment]
Receive a notification when a regrade request has replied to

**Comment by drumilpatel2000** [comment]
We can also add notification setting for particular purpose:-
1. All new post for pinned thread

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notification Options](https://trello.com/c/N4LfDPIP/10-notification-options)
