### ISSUE TITLE
Discussion Forum: Filter unresolved & view crashes Submitty

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2799]
If I filter to show "unresolved", it displays only the unresolved threads on the left.
But then if I click on a thread I get the frog robot.  And I'm stuck.  
I can view other submitty pages, but the discussion forum is broken.  
I delete my submitty cookies and then I'm ok again.

**Comment by andrewaikens87** [comment]
I am able to recreate this on the production server, but not on my local machine. I have created a course with the same course id as DS and the relevant cookie information seems to be identical. Was the type of exception that was thrown or any other information output to the logs?

**Comment by bmcutler** [comment]
23:25:46 09/01/2018 - FATAL ERROR
Error (Code: 0) thrown in /usr/local/submitty/site/app/views/forum/ForumThreadView.php (Line 275) by:
				$cookieSelectedThreadStatus[] = $selectedStatus;


Message:
[] operator not supported for strings

Strack Trace:
#0 unknown file(unknown line): app\views\forum\ForumThreadView->showForumThreads('', Array, Array, false, false, 'tree', 0, 1)
#1 /usr/local/submitty/site/app/libraries/Output.php(127): call_user_func_array(Array, Array)
#2 unknown file(unknown line): app\libraries\Output->renderTemplate('forum\ForumThread', 'showForumThreads', '', Array, Array, false, false, 'tree', 0, 1)
#3 /usr/local/submitty/site/app/libraries/Output.php(96): call_user_func_array('self::renderTemplate', Array)
#4 /usr/local/submitty/site/app/controllers/forum/ForumController.php(707): app\libraries\Output->renderOutput('forum\ForumThread', 'showForumThreads', '', Array, Array, false, false, 'tree', 0, 1)
#5 /usr/local/submitty/site/app/controllers/forum/ForumController.php(96): app\controllers\forum\ForumController->showThreads()
#6 /usr/local/submitty/site/public/index.php(272): app\controllers\forum\ForumController->run()

URL: https://submitty.cs.rpi.edu//index.php?semester=f18&course=csci1200&component=forum&page=view_thread

**Comment by scopeInfinity** [comment]
Hi,
Can you please give some reviews on the small referenced PR, if it fixes the issues in production?
