### ISSUE TITLE
icons & other visuals for forum

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2800]
The checkmark in a green circle ('resolved') is hard to see.  Let's just make it a green checkmark (no circle).  Similar to the "student has viewed grade" on index page listing details for all students in TA grading.

Similarly the ! in a yellow circle (unresolved) is hard to see.  Let's make it a question mark (no circle).  Yellow is good.

The thread list page up & page down overlapping the upper left & lower right corners of that thread list aren't well positioned.  They cover up the icons.  I think it would be better to not overlap and instead stretch that button to be wider.  Also, if I'm at the top of the list (or the top of the list has been loaded), that page up button should not appear.  And if I'm at the bottom of the list (or has been loaded), the page down button should not appear.  (or should be greyed out?)

Finally, the forum has a fixed height.  If I ctrl-minus on this page (to try to see more content, there's wasted space at the bottom of the page.

**Comment by soulspark666** [comment]
Does this issue still need any work, or is it was reopened by some mistake??

**Comment by bmcutler** [comment]
The forum height is still problematic.  @andrewaikens87  is working on that (it may not have a specific issue).
