### ISSUE TITLE
Locally host external libraries (jquery,bootstrap,fontawesome,etc)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2821]
Possibly this will speed up some page loading?

**Comment by MasterOdin** [comment]
Not in the way I think you're hoping. Right now, these resources are being cached within the browser anyway if you request the page and then for any subsequent page load, the browser should just use that cache. Moving to an external version of the library however would improve things on the first load (and of loading other sites) as it's more likely multiple sites may use the same external CDN.

Improving our own page loading would be to improve the efficiency of the PHP code.

**Comment by bmcutler** [comment]
@MasterOdin  I was just going to ask for your thoughts.
Things are sometimes really slow on production, maybe you can stop by this afternoon and help diagnose the problem?

**Comment by bmcutler** [comment]
@thatCode-Psy 
We are going to move forward with this implementation.   It might not help performance, but it has other advantages.  Please ask questions here.
Also tagging @holzbh for discussion.
