### ISSUE TITLE
Cannot reply to forum posts when in "chronological" view

### ISSUE THREAD

**Issue by IreLynn** [Submitty/Submitty#2831]
When the threads are displayed chronologically (as opposed to hierarchically), the "Reply" button is not present on any posts within threads. There is a "Reply" box; however, attempting to reply to the thread using this results in being redirected to the top thread with an error message, "There was an error submitting your post. Parent post doesn't exist in given thread."
![screenshot from 2018-09-07 22-41-25](https://user-images.githubusercontent.com/22512775/45249530-cf523800-b2ef-11e8-9539-48cf2e30874a.png)
![screenshot from 2018-09-07 22-41-50](https://user-images.githubusercontent.com/22512775/45249531-cf523800-b2ef-11e8-8602-18ce72bdb3c4.png)
![screenshot from 2018-09-07 22-41-55](https://user-images.githubusercontent.com/22512775/45249532-cf523800-b2ef-11e8-8c0c-a04a315185eb.png)

**Comment by IreLynn** [comment]
I don't actually know what the difference in the views is supposed to be, because I don't notice one, even when showing merged threads (although I didn't look into it _that_ closely...) but I hadn't expected there to be an issue just because I was in a different view & lost a reply I'd typed up.

**Comment by IreLynn** [comment]
figured out what "chronological" actually does; I guess it's just for the comments, and rather than nesting replies it sorts all posts in a thread chronologically (makes sense). also sort of makes sense that replying would not be supported in this mode..? although it could easily just default to replying to the first post in the thread, or if replying shouldn't be supported here, the misleading "reply" form could be hidden in this page...

**Comment by saxocellphone** [comment]
Yes you are right, the reply should default to replying to the parent thread, which is the intended action. However, I cannot reproduce this problem on the Submitty running on my VM. Obviously, something is going wrong on the live server. I'll definitely look into this.

**Comment by saxocellphone** [comment]
Looks like something is going wrong with the existsPost function in DatabaseQueries. Maybe something screwy with the parentIDs in the database?

**Comment by IreLynn** [comment]
imo it's also just sort of misleading to have the "chronological" and "hierarchical" radio buttons right in line with all the buttons that pertain to the list of threads when they don't do anything to that list, they change the display for the thread that's currently open, but that may be more of a me problem :)
