### ISSUE TITLE
course materials subfolders cannot paste url into gradeable

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2856]
How to reproduce:
Add a course materials file to a subfolder.
Make sure its released to students.
Go view that file from the course materials.
Copy the URL from the file viewer.
Create/edit a gradeable, paste that URL in "What is the URL to the assignment instructions?"

-> Error saving the gradeable.  Cannot give students a link to the file in the course materials if it has a subdirectory.

Mostly assigning this to @CouleeApps , adding @KevinMackenzie just in case.

**Comment by KevinMackenzie** [comment]
I can't seem to reproduce this error.  @bmcutler, can you open the network tab in the web inspector then try to change the gradeable URL, then paste the response to the request that shows up in the network view (it should be json)

**Comment by KevinMackenzie** [comment]
It looks like this is because the `g_instruction_url` is a `varchar(255)` column, so if the url is longer than 255 characters it will fail to save.
