### ISSUE TITLE
better error message if you got the course url for the wrong semester

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2857]
If a student clicks on a stale link to submitty from an old semester (semester & course are in the url), they are prompted for username & password, but after successfully logging in they are told they do not have access.   Right now TAs & instructors are getting lots of emails from students complaining they do not have access (when really it's a stale URL).

It would be nice for the error message to say
*what* they do not have access to (then they might realize that it says f17 instead of f18)
And to tell them what they do have access to instead (redirect them to the submitty home page listing the classes they can access.

Let's also check the other cases and make *appropriate* error messages:
You do not have an account at all
You have an account and successfully logged in but you don't have access to any courses (perhaps you dropped all your courses and/or your courses have been archived).   
You have access to other courses, but not this one.
Probably some other things too...

**Comment by VictorLi718** [comment]
#2965

**Comment by HarendraSingh22** [comment]
Why is this issue still open? It seems to have been resolved in #2965 ,which has been already merged.

**Comment by bmcutler** [comment]
stale issue, now we have a list of valid courses, don't need this.
