### ISSUE TITLE
Default late days for course should be zero

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2858]
The course settings default for "initial allowed late days" should be zero.
And the default max late days should also be zero.

Change "My Late Days" on sidebar to "My Late Days/Extensions"
And also change the title of that page.
(can discuss wording)

**Comment by p-murli** [comment]
Hey, I'm a beginner and I'd like to contribute. Is this issue open and can I take it up?

**Comment by trane2** [comment]
This issue is closed
