### ISSUE TITLE
Switch to a better fixed width/monospace font

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2863]
Displaying autograding output (actual/expected) works ok with basic ascii, but other printing characters sometimes print with different widths (examples will be shared offline).  Chose another font that works for everything.

**Comment by MasterOdin** [comment]
This issue should probably be clarified what we're looking for here. We're looking for a font that has a good number of the unicode characters defined (though we're pretty much guaranteed to have gaps, and there's not a ton we can do about that).

My suggestion would be looking into either FreeMono (from GNU) or DejaVu Sans Mono, though it should be noted that these still only really get us a guarantee of showing less than 5% (~4,000-5,000 characters out of >130,000) of the full unicode spec in fixed width, and that it should be noted within our documentation somewhere of this limitation.

I believe that Wing IDE by default might use Lucida Grande Mono.

**Comment by saxocellphone** [comment]
I can try something out but I still haven't received any examples yet

**Comment by MasterOdin** [comment]
A reported example had these following characters:
```
•
║
═
╔
╗
╚
╝
╟
╤
─
┼
```

In such a configuration:
```
╔══════╤═══════════╗
║• an •|• example •║
╟──────┼───────────╢
║• ab •|• cdefghi •║
╚══════╧═══════════╝
```
(which if done in a non-fixed font that supports these looks terrible)

And probably supporting at least other characters taken from https://www.utf8-chartable.de/unicode-utf8-table.pl?start=9472&unicodeinhtml=dec, but worth investigating using a font with the widest support.
