### ISSUE TITLE
Shorten list of files shown to students from SVN checkout

### ISSUE THREAD

**Issue by wonga6** [Submitty/Submitty#289]
Currently for Principles of Software, when you click "grade SVN" and all the files from the SVN checkout are shown it can be confusing to see a list of every single file in your repository, even those files that are not related to the homework that you were working on. 

It would be nice if instead of the whole checkout list, the section "files from SVN checkout" just shows files that are related to that homework.

**Comment by bmcutler** [comment]
First, let's make this a collapseable box.

Automatically determining which set of files to display is non trivial (if the assignments are cumulative across the term, possibly all files are of interest).

**Comment by bmcutler** [comment]
In order to work on this, we need to get svn fully configured on vagrant and get an example of a sizeable svn repo as a sample homework.

also dependent on issue #314

**Comment by bmcutler** [comment]
and issue #311

**Comment by milana2** [comment]
My preference is to leave it as is now, simple and unambiguous. In the current PoS setup pretty much every homework depends on the previous ones, so there is value in showing all the files. 

Or if we have to change, make it a collapsable list.

**Comment by MasterOdin** [comment]
I think a better solution might be to implement a similar solution as on the TA side of things where we minimize the directory structure and that can be expanded as desired

**Comment by bmcutler** [comment]
Closing this.  Not really an issue since we now encourage separate repos for unrelated assignments
