### ISSUE TITLE
"Allow regrade request" checkbox under course configuration does nothing

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#2901]
If a course does not allow regrade requests by default, checking the box to allow them does nothing

**Comment by bmcutler** [comment]
There's also a checkbox per gradeable.  You have to check both to enable it per gradeable.  It works ok, its just unclear/unintuitive.

**Comment by shailpatels** [comment]
Oh ok, I didn't know about that. Closing this issue then.
