### ISSUE TITLE
Inconsistent Syntax Highlighting

### ISSUE THREAD

**Issue by JoshuaBeard** [Submitty/Submitty#2921]
When grading Python programs, Submitty will perform syntax highlighting, but inconsistently (from zero to two parts of a three-part problem). The parts that are highlighted vary from student to student.

**Comment by bmcutler** [comment]
related to #2874
If you can figure out a pattern, this would help debug & fix the problem

**Comment by JoshuaBeard** [comment]
It seems that beginning a Python file with block comments breaks the highlighting:
```
""" Comment """
import math
print(math.pi)
```
Is not highlighted, but both:
```
import math
print(math.pi)
""" Comment """
```
and
```
# Comment
import math
print(math.pi)
```
Seem to be fine.

**Comment by JoshuaBeard** [comment]
Submitty also seems to sometimes format the Python file as it would a C/C++ file - I noticed this when all text after a `//` got formatted as a comment.

![firefox_screenshot_2018-10-06t22-05-39 713z](https://user-images.githubusercontent.com/16946477/46576205-8cd55700-c992-11e8-89ab-c725f5095ffa.png)
