### ISSUE TITLE
"Users who got the mark" for limited access should not show names

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#2946]
They can't grade most of those users so they shouldn't be able to see their names in the "who got the mark" popup. Just general statistics is fine.

**Comment by bmcutler** [comment]
Yes, limited access shouldn't see the specific names of anyone they do not have access to view (not quite the same as did not grade).

I think it would be great to show the students who got the mark that they can view/grade.   Just one more clause in a (I'm sure) very complicated query... :)

The purpose of this feature is to allow us to go back to that student I graded 30 minutes ago that I realize now I graded incorrectly.  And yes limited access graders can benefit from this feature.
