### ISSUE TITLE
Is it possible to increase the file upload limit?

### ISSUE THREAD

**Issue by jake-billings** [Submitty/Submitty#2953]
I just encountered the following error in submitty while attempting to submit homework 2 for CSCI2500 Computer Organization:

“ERROR! Please contact administrator with following error:”
 
“Files(s) uploaded too large. Maximum size is 100kb. Upload file(s) was 131.475 kb.”

It seemed like a normal amount of homework to me, so other people might also encounter this issue.
 
Is there a way to raise the limit?

**Comment by MasterOdin** [comment]
If an instructor does not set a `max_submission_size` in their config.json for a gradeable, Submitty will default to 100kb for submissions. See the [pdf_example](https://github.com/Submitty/Submitty/blob/master/more_autograding_examples/pdf_exam/config/config.json) for an example of how this directive is used.

@bmcutler can weigh in on whether or not we should change the default to something higher.

**Comment by bmcutler** [comment]
Hi @jake-billings 
Please double check your submission.  If it's a code-only assignment it should easily fit in the 100kb limit (that's the default).  These limits help us monitor the total size of materials collected and backed up.  Make sure you aren't including the executable or any compilation files or large data files.  If you're pretty sure that your submission doesn't include any unnecessary files, and you do need to submit something larger, then contact your instructor to increase the limit for that assignment.
Barb
