### ISSUE TITLE
simple grading page sorting causes crash.

### ISSUE THREAD

**Issue by zhuguotian** [Submitty/Submitty#2959]
I am a mentor in RCOS and when I tried to grade people in my session, the submitty immediately crushed if I sort the students by their last name. Also when sorting by the first name, it's not working properly.
![frogggyyyy](https://user-images.githubusercontent.com/16641618/46445367-8d78ae00-c744-11e8-8aa1-d83352785c7c.png)

**Comment by andrewaikens87** [comment]
Closed via #2963
