### ISSUE TITLE
Allow students to import code from a github repository 

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#296]
It would do a git checkout/clone of repo and use it as a submission to the grading server

**Comment by bmcutler** [comment]
This should be a straightforward extension of the interface for SVN upload.  We should make sure the interface is flexible and can work with regular github repositories, github classroom repositories, other commercial/3rd party cloud git repositories (or other version control software), and privately admined git repositories (like our current svn interface).

**Comment by MasterOdin** [comment]
My main issue with just extending the current interface is that we force the instructor to either allow uploads OR use svn/git. I'm proposing that we allow them to use either/or on the same assignment.

We also have to consider the case where the student has a repo per homework and not just one repo per semester as Github Classroom is setup for the former configuration, which we don't support really at all.

**Comment by bmcutler** [comment]
Yes I agree with your examples.   Extend and make more flexible.  Though for some classes the instructor might want to limit options on some or all homeworks.  CS1 might want to exclusively use drag & drop.  DS might want to exclusively use zip (learning to zip is a good skill).

**Comment by MasterOdin** [comment]
To implement this, I think that we want to allow the options:
1. Clone From Repo (Instructor provides a string for where to clone repos from, allows for variables
2. Student Upload
    1. Allow Drag & Drop
    2. Allow Repo

For 1, we allow the instructor to specify something like `https://github.com/{$course}/{$user}_{$gradeable_id}` or whatever where there's a list of `{$...}` variables that would automatically be converted dynamically for the gradeable/user/course. At the very least, `{$user}` should be supported.

For 2.ii, we can use something like [git ls](https://stackoverflow.com/a/9622518/4616655) to detect if we should use git or svn. Additionally, for HWs with multi-parts, do we want to allow a repo per part or just one for whole assignment and just require student to setup the right folder structure.

**Comment by MasterOdin** [comment]
This issue has been replaced with the following four issues which track different parts of this implementation:
1. #1056 
2. #1057 
3. #1058 
4. #1059
