### ISSUE TITLE
Registration Section data not always synced between master DB and course DB

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#2960]
The manage sections form inserts new registration sections into the course database, skipping over the master database.  As a result, registration section data between the master and course databases are not properly synced.

To fix: new registration sections should be inserted to the master database in the `courses_registration_sections` table.

**Comment by bmcutler** [comment]
@pbailie 
In addition to solving this bug, can you also write a migration to fix existing courses with sections that aren't in the master table?  Thanks!

**Comment by pbailie** [comment]
> @pbailie
> In addition to solving this bug, can you also write a migration to fix existing courses with sections that aren't in the master table? Thanks!

I'll provide this solution in the Sysadmin Repo.  Work is underway.
