### ISSUE TITLE
Auto-open and/or open all files when TA grading

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2974]
This feature is kinda buggy, and not all that useful.

When a TA is grading a multi-file homework, and you've opened a bunch of submitted files to do your grading, it would be nice to have those same filenames open when you move to the next student.  Many students do choose the same or similar file names.  But we don't want to just open all of the submitted files (like the timestamp, and other data files or provided code files that aren't relevant)

Feature Request:  Remember (in a cookie) all filenames that were opened but not closed.  Then when you go to the next student, if they have any files matching those names, then auto-open those files.  The list will probably accumulate the different capitalizations or naming representing the typical implementation strategy for a homework..... e.g., student.h, Student.h, person.h, people.h, etc.

This will also have the benefit of handling a student with no submission, or no submitted files (currently, you have to reopen all files after passing a student with no submission/files).

**Comment by RylanOC** [comment]
It looks like this has been added.
