### ISSUE TITLE
PDF Annotator text tool trims

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#2990]
When leaving editing remarks, since the textbox placement is a little trial-and-error, I sometimes have textboxes that are not quite where I want them on the x-axis.

To correct this I've tried to put spaces in front of the text I intend to display, but when I change tools / make another textbox to commit the text, all the leading spaces are truncated. Can we support leading/trailing spaces?

Edit: I am using Chrome, and did just clear my cache to get the freshest version of the annotator JS

**Comment by MasterOdin** [comment]
Fixed in Submitty/pdf-annotate.js@3d122aab8ed4502d1de3cb6009b474bedb46a823 and Submitty/pdf-annotate.js@7fb3731450f5188b389883a62b0e304204388d7a. Will be installed as part of v.19.04.00.
