### ISSUE TITLE
grades released hidden test points should only be visible for active version

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#2994]
If autograding has a hidden test, the points for the hidden test are made visible when the (ta) grades are released.

Currently, the student can visit their non active versions and see how many hidden points were awarded for each test case.  But I think we should stop this.

Hidden points should only be displayed for the active version (and only after grades are released).

**Comment by KevinMackenzie** [comment]
The student could switch their active version after grades are released to see the hidden testcases and switch back to their original graded version without penalty, so would it make more sense to only show it for the graded version?
