### ISSUE TITLE
Download all files on submission permissions issue

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#2996]
On a gradeable that allows students to download their files, there seems to be an issue when using the  download all files button. It works fine when downloading each individual file but will send a "You do not have access to that page." when trying to click the "Download all files" button.

Edit: This was noticed on a gradeable that had the "bucket" submission type with two program files and 1 being a pdf.

**Comment by CouleeApps** [comment]
Are you able to replicate this in vagrant? If so, how? I have tried multiple times and still only see this on the live server.
