### ISSUE TITLE
excessive vertical space on submission page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3031]
Not sure when this changed, but we seem to have a 100% vertical fill happening on the submission page.

When the content is small, but the page is tall, it adds extra padding to the two boxes on the page.  In this example the submission box is small (just a sentence because submissions are disabled), and the autograding results are also short since we only have 2 tests.

I think it would be better to have the extra vertical space at the bottom of the page, as before.

<img width="477" alt="screen shot 2018-10-25 at 10 45 00 pm" src="https://user-images.githubusercontent.com/5871417/47541574-b6a1df80-d8a7-11e8-88d0-fe8ba5ec50d9.png">

This happens with the regular submission box too, its just exaggerated in this case.

[I think this is a @CouleeApps thing, but also tagging @KevinMackenzie just because]

**Comment by CouleeApps** [comment]
This is a side-effect of my attempt to clean up some pages that were very short. Planned fix is to just have the last box take all the extra space to maintain full-page height.
