### ISSUE TITLE
Generalizing Paragraph Textbox Config

### ISSUE THREAD

**Issue by achristoforides** [Submitty/Submitty#3082]
- [x] Rename "assignment_message" to "gradeable_message" (optional)
- [x] Message should be boxed banner, not green text
- [x] Problem Label should be bold (required)

New Content array (holds content boxes):
- [x] Holds html description, labels (before descriptions), input fields
- [x] Headers for content, newlines, links, italics, bold, colored font, preformatted (fixed width font for code), math symbols, image source=, images included in the assignment (can't see assignment, can't see images/files)

Textbox Modifications:
- [ ] New code box option where instructor selects language

Multiple Choice
- [x] Multiple choice input for questions
- [x] Check-all-that-apply multiple choice input for questions

**Comment by bmcutler** [comment]
@emaicus please review issue & open new issues for remaining items (as appropriate) and then close this issue.
