### ISSUE TITLE
Instructor Team View/Edit Interface (formerly Team cancel invitation does not work)

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#3085]
Occurs when on a team and trying to cancel an invitation.  

To reproduce: create a team, then invite a different user, then try to cancel that invitation -> it will not cancel the request and display the following error:

![image](https://user-images.githubusercontent.com/16356240/47892781-0c3e3500-de30-11e8-80fc-2feb9195a2bf.png)

**Comment by bmcutler** [comment]
There's also an issue with students somehow being on multiple teams.  Initially I thought this bad data happened when we were in a bad state with the team query code.  But an instructor has reported that this happened with teams created after the code was fixed.

**Comment by bmcutler** [comment]
Related Feature Request:  The instructor interface for teams does not display invites to a team, only current members.  Let's add invites to the instructor display (from the grading -> student index page, when you click on the pencil next to a student or team).

Related Feature Request 2:   The instructor interface shows the history of the team, but only the date the team was formed and the last edited date.  There is more history information in the user_assignment_settings.json file.  Let's display it when the instructor clicks the edit pencil for the team.

**Comment by bmcutler** [comment]
We don't seem to be logging the cancel to the user_assignment_settings.json history file (or cancel is erroring before it can be logged to the history file).

**Comment by bmcutler** [comment]
@VictorLi718   Please tackle the remaining items in this issue.  Kevin has fixed (hopefully) the team cancellation bug.

**Comment by VictorLi718** [comment]
For the Related Feature Request, I think we already have this feature
![image](https://user-images.githubusercontent.com/30506009/48749798-83eecb00-ec4a-11e8-97cf-b1ed27434a21.png) The instructor can add name here and click "submit" to make changes. 

Should I still make any changes to this?

**Comment by VictorLi718** [comment]
For the Related Feature Request 2, I made a pull request.

**Comment by bmcutler** [comment]
When students form a team, they first send an invitation, then the other user must accept the invitation.  A student is not officially a member of the team until the invitation is accepted.

The instructors can currently only view members of the team.  They can add members to the team. 
 but they cannot see the invitations.  Note: a student may have multiple invitations.  Once a student has accepted an invitation, all other invitations are deleted.  And no other invitations will be saved.

**Comment by bmcutler** [comment]
@VictorLi718 
Please add pending invitations to the instructor view for a particular team.  And we could add an option to accept the invitation for the student. 

Also it would be nice to list invited members for each team on the list of all teams.  But display them differently...  maybe in italics and light grey font?

<img width="483" alt="screen shot 2018-11-28 at 5 02 43 pm" src="https://user-images.githubusercontent.com/5871417/49186138-c04cb600-f331-11e8-878a-d28992d3d78c.png">

**Comment by VictorLi718** [comment]
Because this is about JavaScript, we just passed the members and json into it and there is no data about pending invitation. So maybe we have to rewrite the render function? Could you please have a look on it @KevinMackenzie ?
