### ISSUE TITLE
Late Day Penalty

### ISSUE THREAD

**Issue by AudreyBeard** [Submitty/Submitty#3089]
Looking at the docs and the web interface, it doesn't look like an instructor can impose an automatic point deduction for unexcused late submissions - the student receives 0 in these cases. I would like to see an option for deducting a fixed number of points (or a fixed percentage) for each unexcused late day.

**Comment by bmcutler** [comment]
related to #2982 -- design suggested in that issue can be used to solve this issue too

**Comment by bmcutler** [comment]
This is pretty complicated, so we're going to delay implementation...
But our new grade override feature will allow you to handle this case manually.  
Please check it out in the meantime:
https://submitty.org/instructor/grade_override

**Comment by bmcutler** [comment]
closing as low priority
