### ISSUE TITLE
Warnings should incur a small penalty or have a noticeable message

### ISSUE THREAD

**Issue by sihsob** [Submitty/Submitty#309]
At the moment students get full points for warning messages after compilation.  Should have it so that students either get a small penalty or print some sort of big ERROR/WARNING message to make them look at it.

**Comment by bmcutler** [comment]
To clarify, compiler warning messages should always be an intimidating red message on the compiler test.  And the instructor should be able specify a point penalty multiplier (0.0 -> 1.0) in the config.h for having warnings (by default no point penalty).

**Comment by bmcutler** [comment]
Yup.  If an instructor wants to insist that code have no warnings at all, they can use a compile flag that converts warnings into errors and then all tests of the executable will also fail.

**Comment by ZishanHuang** [comment]
Solved in #384
