### ISSUE TITLE
"Download all" improvements

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3099]
From the initial page for grading an assignment, the "download all" should include the **option** to grab the results folder in addition to the submissions and checkout folders.

It should also include the **option** to only grab the folder for the current active version of each of the submission, checkout and results folders (to decrease size).

Also, if the size of the zip is large ~350MB, it can take a long time to prepare (4.5 minutes) and we are not giving feedback on this process to the user.  If the file is even larger (or if the machine is more loaded or the file system is slow), it fails with the frog robot.  (Perhaps a timeout of some sort?)

**Comment by bmcutler** [comment]
When I was testing #4015, this issue came up again.
Attempting to download a zip of all students for a small class, but perhaps many/larger files...
The page seemed to hang (I waited a minute or two before giving up).
Some indication of expected time (number of files, size of files, total size of zip), progress so far, would be very helpful (so the user knows what's going on, and to please be patient)

**Comment by MasterOdin** [comment]
We may want to replace the naive zip method we currently have with https://github.com/maennchen/ZipStream-PHP, which I believe will largely solve the various issues here of the page hanging, too large of files causes a page crash, etc.
