### ISSUE TITLE
Improve error message when invalid course/semester

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#310]
Right now, if you get the semester wrong, a javascript popup will appear that says ```INVALID SEMESTER: f00``` (regardless of entered semester) and if you enter an invalid course it will say ```INVALID COURSE: csci0000``` and then the user is presented with a plain white page. We should:
a) Output an html error page on these cases (ie. a 404 type page)
b) Output the actually entered semester/course and not f00 and csci0000

@bmcutler do we want to exactly match semester and course code or do we want to be case-insensitive (as right now the server would throw an error if you entered F15 or CSCI1100)? My vote is for "case-insensitive" in that we always lowercase the semester/course.

**Comment by bmcutler** [comment]
Case insensitive is good.  I think I have that in some places, but likely not all.
