### ISSUE TITLE
Reduce frequency of rebuild gradeable

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3100]
Right now if anything is changed about the gradeable (dates, rubric, etc) it triggers an autograding configuration rebuild

This is a problem if we have jobs in the queue to grade for that assignment and they are picked up to grade while the gradeable is being rebuilt (one of the files, config/complete_config.. ) does not exist so those gradeables fail with an "ERROR unable to prepare job"

So let's only trigged a rebuild of the gradeable if the specified config file changes OR if the user presses the rebuild gradeable button.

**Comment by dpshelio** [comment]
In my case I found it even more frequently! Even when I don't change anything, just clicking the edit button and go back to the gradeables (via the menu), it asks me to run the `BUILD_course.sh`.
