### ISSUE TITLE
limited scope undo/redo on checkpoint grading page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3101]
Use case:  TA/mentor grader using Submitty website on a phone to check off students in lab.   Grader wants to scroll to find the student, but accidentally clicks on a checkpoint, changing the data.  Currently its not clear which box was just changed.  And especially if the page data is stale (it may have been 10 minutes since the grader hit reload, and other graders are also working on this page).

Let's add an undo/redo option!

Only a small amount of history needs to be stored.  Just a few clicks (maybe up to 5).    Maybe we can also highlight those boxes with a "recently edited by you" outline color?  This could just be stored in a cookie?  Store which student, which checkpoint, old value, new value for each action.  And somewhere on the page is an undo button, that just reverts those changes.  And if you've undone, then there can also be a redo?

**Comment by Manda7rsnt** [comment]
Hi @bmcutler I would want to work on this issue,
Can you guide me on how or where should I be starting? or 
Can you link me to the relevant parts of the codebase?

**Comment by accakks** [comment]
@bmcutler I am also interested in working on this. 
But since @Manda7rsnt already asked, let us know if there are parts of it we can  both work on separately. Or if @Manda7rsnt is not working on it, I can take this up.
