### ISSUE TITLE
Create more dummy information in vagrant

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#311]
We want to add some dummy stuff in the vagrant box to indicate some of the capabilities of the system
- [x] Have multiple assignments in the classes (at least one being separate parts)
- [x] Have rubric created for some of these assignments
- [x] Have a graded submission for >0 students
- [x] Have some labs (with grades submitted for a student)
- [x] Have quiz/test (with grades submitted for a student)
- [ ] Have rainbow grades generated 
- [x] Multiple student accounts (we have just one `student`. Do we want to just name them `student#`?

@bmcutler any more suggestions that you would want to see?

**Comment by bmcutler** [comment]
We should also setup some sample svn directories.

I think we should have multiple numbered student accounts.

We're also going to want to test permissions with multiple co-instructors and multiple TAs, some that are "head TA"/"course manager", and some that are regular graders.
