### ISSUE TITLE
Regrade Request per problem (or per TA)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3110]
When the grading of an assignment has been done by multiple people, when a student submits a regrade for specific problem(s) we would like it to notify only the people we graded those problems.  And have the the regrade resolved per problem.

* Maybe list the components like discussion forum categories that the student can check when they start the conversation thread for the regrade.

* The TAs can uncheck the 'categories' (components) as the regrades are resolved.

* The query for deciding if a specific TA should be shown pending regrades can then more correctly direct the TAs to regrade.

* Maybe the stoplight buttons for the grading from the index page can turn red for the problems that have an outstanding regrade request.

[needs design discussion]

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Regrade Request per problem (or per Ta)](https://trello.com/c/YGSOJdKo/9-regrade-request-per-problem-or-per-ta)
