### ISSUE TITLE
Grade summaries and assignments without a due date...

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3112]
Right now, if the assignment "has no due date" (and late days should be irrelevant), but the hidden due date is before the "submission" (or instructor upload) date, the student is getting a "bad" status for the assignment in the grade summaries and rainbow grades is setting the score to zero.

The hack workaround fix is to "Show all dates" for the gradeable date tab and edit the due date to be after the last submission/upload.

The status of any assignment with no due date should be "good" or "no submission"/"unsubmitted".
(We might not have an enum for "no submission"/"unsubmitted", but we should make one!  

related to issue #3106

**Comment by KevinMackenzie** [comment]
I'm working on converting the Grade Summaries to use the new model, which is waiting on the late days to use the new model (#3043).  Would you rather I fix this asap (today) or fix it while converting to the new model (sometime this week)
