### ISSUE TITLE
autograding sample test cases are giving compilation error

### ISSUE THREAD

**Issue by josethomas98** [Submitty/Submitty#3113]
I am getting a configuration error on running the BUILD_XXX.sh for the sample test cases given in the test cases repository.I tried several sample questions following the guidelines and modifying the config.json file. Is there anything else that i could try or can i get a demo config.json file that is valid.

**Comment by bmcutler** [comment]
Sorry about this confusion.
Please ask questions on our Slack server if you're still having trouble:
https://submitty.org/developer#online-community-discussion-and-contact-submitty-administration-team
