### ISSUE TITLE
bulk upload data history forensics file improvements

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3123]
I used this to track down a missing upload last night...  yay!  It helped and was faster than before!  Awesome!  Thanks!

A few feature requests to make it an event more helpful tool:

1. When you write out the file bulk_upload_data_json there are some extra characters and the formatting is not easy-for-humans/pretty printed:

    a:3:{s:16:"submit_timestamp";s:41:"2018-11-15 22:02:11-0500 America/New_York";s:16:"upload_timestamp";s:42:"11-15-2018_22:01:17-0500 America/New_York
";s:8:"filepath";s:101:"/var/local/submitty/courses/f18/csci1200/uploads/split_pdf/test03/11-15-2018_22:01:17-0500/w01_72.pdf";}

    What are the a:3 and s:16 and etc characters?  And the ';' too?  Those aren't in our other json files.   And pretty print will add newlines and auto-indentation.

2.  The main thing I ended up doing was group and sorting by file name and page count.  
for example:  filename "w01_72.pdf" above
We named our batches of 10: w01, w02, w03, ... and c01, c02, c03, ....   And the exam was 12 pages, so I could quickly tell this was the 7th exam in the w01 packet.

    Can you make a new page, visible only by instructors and full access TAs, that we access by clicking on a link button from the entry page of ta grading statistics.  The new page should be scraped from these bulk upload data files and have 4 columns:

    * user name, preferred first & last names
    * upload timestamp
    * submit timestamp
    * filepath  --- EDITED TO REVISE:  Let's not display or sort by full filepath.  Just the filename.  The filepath includes the upload time.  I just want to sort by "w01_72.pdf" just the filename.  

    And the user can separately sort these 4 columns, kinda like we can sort the columns of the 
    forum statistics.  Ask @andrewaikens87 how that works.

**Comment by MasterOdin** [comment]
> When you write out the file bulk_upload_data_json there are some extra characters and the formatting is not easy-for-humans/pretty printed:
> 
> a:3:{s:16:"submit_timestamp";s:41:"2018-11-15 22:02:11-0500 America/New_York";s:16:"upload_timestamp";s:42:"11-15-2018_22:01:17-0500 America/New_York
";s:8:"filepath";s:101:"/var/local/submitty/courses/f18/csci1200/uploads/split_pdf/test03/11-15-2018_22:01:17-0500/w01_72.pdf";}
> 
> What are the a:3 and s:16 and etc characters? And the ';' too? Those aren't in our other json files. And pretty print will add newlines and auto-indentation.

It's a string created by calling [serialize](https://php.net/manual/en/function.serialize.php) on a PHP array, not a proper JSON object.

**Comment by bmcutler** [comment]
this is issue #3182
