### ISSUE TITLE
Late day banner showing different late days left

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#3125]
A student submitted an assignment 1 day late and has 6 more late days which is correct, but then banner says if you submit today again you will only have 5 remaining. 

![sharedimage](https://user-images.githubusercontent.com/12129065/48666796-988a6200-ea96-11e8-9a61-abb79067b751.png)

**Comment by bmcutler** [comment]
duplicate/related issues: #3184 #2455
