### ISSUE TITLE
Team Assignment: Has Viewed Grade Status missing/buggy

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3131]
If/When students view the grade for their team assignment, 
currently the instructor cannot see that information (always says no one has seen it)

**Comment by VictorLi718** [comment]
![image](https://user-images.githubusercontent.com/30506009/49492618-0b316680-f827-11e8-8d4e-43875671867f.png)
For this bug, I tried but couldn't reproduce it.

**Comment by VictorLi718** [comment]
The problem is now about the info on the main page.

**Comment by VictorLi718** [comment]
Well, unfortunately, I can't reproduce the problem either... (Maybe do it during hackathon)
![image](https://user-images.githubusercontent.com/30506009/49691180-b6356f00-fb0a-11e8-97df-5bf0df284d1e.png)

**Comment by bmcutler** [comment]
The bug on production is still that it shows 0 teams have viewed when the details page shows some teams have viewed.
