### ISSUE TITLE
Inconsistent time on regrade requests 

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#3137]
![submitty broke](https://user-images.githubusercontent.com/12129065/49099939-bf882700-f240-11e8-8724-f929f14c0c1b.PNG)

A student just submitted a regrade request but the time submitted shown does not match the actual time

**Comment by xprilion** [comment]
Hi, this could probably be due to the server time not matching the user's time. An issue on localization I believe.

**Comment by bmcutler** [comment]
duplicate / related to #3594 ?

**Comment by shailpatels** [comment]
@bmcutler Yeah this issue would most likely be fixed by solving #3594

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Inconsistent time on regrade requests](https://trello.com/c/jkG76G0N/8-inconsistent-time-on-regrade-requests)
