### ISSUE TITLE
"Students who got the mark" throws a SQL error

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#3138]
Attempting to grade on the live server (as a mentor) throws this.

![image](https://user-images.githubusercontent.com/711973/49100741-95cfff80-f242-11e8-9d21-6fd03fb8550b.png)

**Comment by LeonMontealegre** [comment]
@CouleeApps 
Does this error still happen?
I can't seem to reproduce it

**Comment by bmcutler** [comment]
closing this for now.  please re-open if it is still a bug.
