### ISSUE TITLE
More access control for TA grading

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#315]
Some TAs should have access to lab, homework, and test data entry for all students.  

Some TAs should only have access to some components of grading and/or only a subset of students.

Right now, TAs can edit the URL and access all lab sections & all grading sections.

Want to strike the right balance between full access TAs efficiently navigating the interface and ensuring that access to student information in our largest classes is restricted to only those who need-to-know/need-to-edit.

**Comment by MasterOdin** [comment]
I think we should rename things in our system. We have students and then staff (currently called users, but rename it to staff). Staff have three categories with their own permission flags:

1) Grader  
They can only view lab/test sections they were assigned to. They cannot use the "&all" url parameter.

2) TA
Same as grader but have access to "&all" url parameter

3) Instructor
Same as TA, but always see "&all" and can edit the course

(We have a fourth, but this isn't publically advertised as a possibility)
4) Developer
Same as instructor, but also sees information on queries run on the page and other debug information as I figure it out. This can only be toggled through the database.
