### ISSUE TITLE
'Who got this mark' exception

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3150]
reported by a full access grader when clicking 'who got this mark'

Failed to get stats for mark: SQLSTATE[42883]: Undefined function: 7 ERROR:  function pg_catalog.substring(integer, unknown) does not exist
LINE 3:              ORDER BY SUBSTRING(sections_rotating_id, '^[^0-...
                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by MasterOdin** [comment]
Looking through the queries, I suspect its from these lines:
https://github.com/Submitty/Submitty/blob/059b28cac0bad8ace402ed6d2939593fa0b1d4b0/site/app/libraries/database/DatabaseQueries.php#L1606-L1619

Need to modify this such that if `$grade_type` is registration, then we use the `SUBSTRING` function and the three clauses in the ORDER BY, else if it's rotating, it can just be a normal ORDER BY on it as a numeric column.
