### ISSUE TITLE
Possible permissions error cheking unpacking

### ISSUE THREAD

**Issue by dpshelio** [Submitty/Submitty#3153]
In the current master (c99b355) I've found there must be an error on permission checking as `packer_unpacker` cannot check whether the directory for the submission has been created. These are the messages:
```
ERROR: the submission directory does not exist/var/local/submitty/courses/01/course/submissions/hw01/student/1
ERROR: failed preparing submission zip or accessing next to grade ('ERROR: the submission directory does not exist', '/var/local/submitty/courses/01/course/submissions/hw01/student/1')
primary ERROR unable to prepare job: /var/local/submitty/to_be_graded_queue/01__course__hw01__student__1
```
After changing few bits on the `prepare_autograding_and_submission_zip` function I found it has to do with permissions. I have not been able to find who is running that though!

However, if I roll back to 1461db45d05b298a, where I was before, then it works!!

**Comment by bmcutler** [comment]
@emaicus can you try to reproduce and see if it's still a bug (maybe we've already fixed this), or fix it if it's still a problem.  Thanks :)

**Comment by linhbngo** [comment]
This is still a problem on the latest master:

```
 | ERROR: the submission directory does not exist /var/local/submitty/courses/fall2019/csc331_80/submissions/hw01/lngo/
2
2019-05-10 00:07:03.228 -0400 | ~SHIP~ |       |             |                                                                             |
                      | ERROR: failed preparing submission zip or accessing next to grade ('ERROR: the submission directory does not exist',
 '/var/local/submitty/courses/fall2019/csc331_80/submissions/hw01/lngo/2')
2019-05-10 00:07:03.228 -0400 | ~SHIP~ |       |             |                                                                             |
                      | primary ERROR unable to prepare job: /var/local/submitty/to_be_graded_queue/fall2019__csc331_80__hw01__lngo__2
root@submitty:/var/local/submitty/courses/fall2019/csc331_80# ls submissions/hw01/lngo/
1/                             2/                             user_assignment_settings.json
root@submitty:/var/local/submitty/courses/fall2019/csc331_80# ls submissions/hw01/lngo/1/
part1/             part2/             .submit.timestamp
root@submitty:/var/local/submitty/courses/fall2019/csc331_80# ls submissions/hw01/lngo/1/
part1  part2
root@submitty:/var/local/submitty/courses/fall2019/csc331_80# ll submissions/hw01/lngo/
total 20
drwxr-s--- 4 submitty_php csc331_80_tas_www 4096 May 10 00:07 ./
drwxr-s--- 3 submitty_php csc331_80_tas_www 4096 May 10 00:05 ../
drwxr-s--- 4 submitty_php csc331_80_tas_www 4096 May 10 00:05 1/
drwxr-s--- 4 submitty_php csc331_80_tas_www 4096 May 10 00:07 2/
```

**Comment by emaicus** [comment]
This was modified in the spring. We will re-evaluate if the issue reappears.

**Comment by linhbngo** [comment]
Hi, 

I run into this error again:

2019-09-13 10:06:09.281 -0400 | RgCb16 |       |             |
                                            |                      | ERROR: the submission dire
ctory does not exist /var/local/submitty/courses/fall2019/csc141_01/submissions/assignment_0/lc
ui/1
2019-09-13 10:06:09.285 -0400 | ~SHIP~ |       |             |
                                            |                      | ERROR: failed preparing su
bmission zip or accessing next to grade ('ERROR: the submission directory does not exist', '/va
r/local/submitty/courses/fall2019/csc141_01/submissions/assignment_0/lcui/1')
2019-09-13 10:06:09.285 -0400 | ~SHIP~ |       |             |
                                            |                      | primary ERROR unable to pr
epare job: /var/local/submitty/to_be_graded_queue/fall2019__csc141_01__assignment_0__lcui__1
