### ISSUE TITLE
Redo front end for multi-part assignments

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#316]
Currently a homework with multiple "parts" looks like multiple assignments to the students.
The parts are only glued together when a rubric is created.  This is bulky for the students, more places they need to remember to check for TA feedback.

Instead, students should have one page per assignment, with multiple places to upload or drag & drop files.  They will still be able to submit & test one part as a time, as they finish working.

Under the hood, multi-part assignments will still be separate directories.

The instructor configuration json (config/class.json) should be redesigned to give instructor grouping control for these parts.  By default a homework should have a single deadline, but optionally separate dates can be specified for each part.  Some of the other fields (open for submissions, release TA comments) may be overall or per part (to be determined).

Once the front end & json are redesigned & reimplemented, the create a new rubric page can be streamlined to read dates and parts from the config/class.json.

**Comment by MasterOdin** [comment]
I'm going to propose a new JSON format which would then be drafted into a database schema afterwards:

```
{
    "assignment_id": "lab01",
    "assignment_name": "Lab 1 Getting Started",
    "assignment_released": true,
    "grades_released: false,
    "due_date": "2015-09-02 23:59:59.0"
    "allowed_late_days": 2,
    parts: [
        {
            "part_id": "_part1",
            "part_name": "Part 1"
        },
        {
            "part_id": "_part2",
            "part_name": "Super Fun Part 2"
        }
    ]
}
```
part_id and part_name are optional and will be filled in automatically (as "_part#" and "Part #") if missing. Each part would have its own upload box on one central assignment page. The whole parts section is optional and if not filled in, there'll be one upload box.

Then, when you're making a rubric, we show as many parts as were made for the assignment (so for above example, rubric would have two parts). Don't allow for less/more parts.

**Comment by bmcutler** [comment]
Yes, looks like the core of what we agreed on.  

We did discuss the "what if" the parts had different deadlines (part one due on Tuesday, part 2 due on Thursday night).  So that would be an additional optional field inside of each part.

**Comment by MasterOdin** [comment]
How would grading ideally work in a scenario where the parts have different due dates? I would say not allow grading till after the final due date.

**Comment by bmcutler** [comment]
You should get no points for a part submitted late.  Or perhaps late days can be used for the part.  So yes, each part can have a different due date and different number of late days.

In practice, this is the scenario I see:
Early in the week and exercise relating to the homework is due.  For our last homework, which includes C++ inheritance, a paper diagram of the class inheritance is due in lab on Wednesday, no late days allowed.  (Mostly this is to help kids get the correct diagram before they tackle implementation.)  It would help to insist that they also upload the diagram to the homework server, for a part 1 that is due by 8pm Wednesday with no late days.

If we follow the paper from SIGCSE this year that had students submit tests cases mid week for peer grading before the implemented & debugged code was due at the end of the week.  In that case, no late days are allowed for the intermediate assignment.

**Comment by bmcutler** [comment]
Another though....  if we allow peer grading (comments & feedback, with or without scores) mid week.  Can multiple users (TAs and/or students) comment/grade on the same homework?  Not in the current design...

**Comment by bmcutler** [comment]
the redesign and simplified interface for multiple parts with drag and drop finishes this feature.
Note: There is a single deadline, students can submit to one or multiple parts in a single submission,  max number of submissions is applied to the whole assignment, and late days are charged for a whole assignment.  The TA grading interface does not break the rubric into parts explicitly, but questions can be labeled for a specific by the instructor if appropriate.
