### ISSUE TITLE
More Notification Settings

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#3160]
- Receive a notification when a regrade request has replied to
- Receive a notification when a user is invited to a team
- TA gets an email notification when a grade inquiry has been made (for a student/component that the TA is assigned to)

EDITED TO ADD (from @andrewaikens87 note on PR #3896):
- For grade inquiries and other like notifications, we should include these on the notification settings page. Even if there is no plan to allow users to opt out (grayed out checkbox). 
- Also for these notifications, we should identify an icon to sit next to them on the notification page. It's currently blank and looks inconsistent.

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [More Notification Settings](https://trello.com/c/EWsAlDrm/7-more-notification-settings)

**Comment by bmcutler** [comment]
edited comment to add note from @andrewaikens87  on PR #3896

**Comment by sak6lab** [comment]
![new-notification-settings](https://user-images.githubusercontent.com/15002610/61138590-d90b7580-a495-11e9-826b-fb7d3531e522.PNG)

These are the notification settings I am planning to add. The ones with dark blue checks are by default true for the user but can be disabled if need be. The grade inquiry notifications are always checked and cannot be changed.

I am going to do this in three PR as testing would be a lot easier: one for grade inquiry, one for team, and one for gradeables.

Along with implementing the settings I have to implement the following notifications: grade inquiry resolved, new team invites, new team member submission, gradeable accepting submissions, and gradable released grades. The notifications that are optional will require the addition of columns in the notification settings table so expect migrations.

- [ ] Grade Inquiry Notifications

- [ ] Team Notifications

- [ ] Gradeable Notifications

**Comment by sak6lab** [comment]
For icons, now that we will have headers for each section maybe we can add individual icons beside those.
