### ISSUE TITLE
"Max # of late days allowed" in the My Late Days/Extensions table

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3162]
It looks like we are calculating the # of late days the specific student could use on a homework.
Rather it should be the # of late days that are allowed on that assignment (from the create/edit gradeable dates page).

Even if I have 5 late days to spend, if I'm only allowed to use 2 late days on the last homework (because the TAs are going to start grading 2 days after the deadline), I can only use 2 late days.

[please discuss amongst yourself who will fix this]

**Comment by KevinMackenzie** [comment]
the math for this "late days allowed" looks like: ```min(max_assignment_late_days, student_late_days_remaining) + extension```
