### ISSUE TITLE
hardcoded RLIMIT_FSIZE

### ISSUE THREAD

**Issue by dpshelio** [Submitty/Submitty#3164]
I've found this place ([grading/TestCase.cpp#L358](https://github.com/Submitty/Submitty/blob/master/grading/TestCase.cpp#L358)) where the `RLIMIT_FSIZE` is set to 10MB and ignores the values set on the `resource_limits` entry on the `config.json` file for each course.

**Comment by bmcutler** [comment]
If this is still a problem for you please re-open and explain in more detail

The line you have pointed at has likely changed, but I think it is related to adjusting the limits for compilation, and is setting a minimum rather than a maximum.  The instructor can override with a higher maximum as desired.

**Comment by MasterOdin** [comment]
Looking up the line from repo state from Dec 7, 2018, that line now refers to this one (permalinked against current master):
https://github.com/Submitty/Submitty/blob/2f041cb1680dc499680f0e6afbcf2e05935e825e/grading/TestCase.cpp#L321

Which calls this function:
```cpp
void adjust_test_case_limits(nlohmann::json &modified_test_case_limits,
                             int rlimit_name, rlim_t value) {
  
  std::string rlimit_name_string = rlimit_name_decoder(rlimit_name);
  
  // first, see if this quantity already has a value
  nlohmann::json::iterator t_itr = modified_test_case_limits.find(rlimit_name_string);
  
  if (t_itr == modified_test_case_limits.end()) {
    // if it does not, add it
    modified_test_case_limits[rlimit_name_string] = value;
  } else {
    // otherwise set it to the max
    //t_itr->second = std::max(value,t_itr->second);
    if (int(value) > int(modified_test_case_limits[rlimit_name_string]))
      modified_test_case_limits[rlimit_name_string] = value;
  }
}
```

Where it'll use at a minimum of 10MB for that RLIMIT. I think @dpshelio might have been looking to set it to a lower value?

**Comment by bmcutler** [comment]
Yes, and that is not what we support.  
If there is a specific need, the issue can be re-opened with details.
