### ISSUE TITLE
Buggy Message for Late Day

### ISSUE THREAD

**Issue by VictorLi718** [Submitty/Submitty#3184]
I found this bug when I tried to submit hw 2 days late. Could you please try to reproduce it and fix it? 
<img width="1656" alt="screen shot 2018-12-08 at 17 20 33" src="https://user-images.githubusercontent.com/30506009/49971404-608f0700-fefc-11e8-9d35-1f4db6997c1f.png">
![image](https://user-images.githubusercontent.com/30506009/49971261-de064780-fefb-11e8-8190-85a4d267c967.png)

**Comment by Fenn-CS** [comment]
I am unable to replicate this scenario. The popup shows the right number in the case of 2 days late. Except the time is a factor here but if that's the case who can supply the right parameters to reproduce the issue? 

![Screenshot from 2019-05-23 06-59-46](https://user-images.githubusercontent.com/14317775/58229018-65b47580-7d28-11e9-869f-042efc3e8015.png)


I would go ahead and continue investigation with  #3125, while waiting on feedback to confirm this is no longer an issue.

**Comment by bmcutler** [comment]
probably related to #3316.  Will wait for unit testing to test/debug.
