### ISSUE TITLE
Skip no-submission students when grading

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#3192]
Considering there is no ability to grade them anyway, it would improve usability of the grading interface if we just skipped students with no submission.

**Comment by MasterOdin** [comment]
This should be a decision that's run by TAs who are grading. At least when I was TA of CS1, myself and fellow of TAs would love hitting a student who didn't submit as it provided a "relief" as we hit submit with a zero grade. We absolutely loved the psychological basis of it even though it could have been easily automated away (which is suggested in this issue).

**Comment by CouleeApps** [comment]
Ah, in psoft we have the opposite problem. Because all the homeworks use really deeply nested directories of java, hitting a no-submission student will collapse all of your pre-expanded answer files and make you have to reopen everything... That's a topic for a separate report though
