### ISSUE TITLE
Course materials doesn't let you view PDF files when extension is all caps

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#3193]
The option to popup view works for `.pdf` files but not `.PDF` files

Should be a pretty simple fix, just need to case insensitive compare instead when checking the extension

**Comment by weavermonkey** [comment]
Could I pick this up?

**Comment by HarendraSingh22** [comment]
@weavermonkey working on this? 
@CouleeApps I want to take this one

**Comment by HarendraSingh22** [comment]
@CouleeApps ...

**Comment by Psp98** [comment]
@MasterOdin can you provide a reference link to that file that needs to be updated?
