### ISSUE TITLE
'who got mark' data is still wrong and unclear

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3194]
There are not 483 users in this course.
There must be bugs in the queries when the students have multiple submissions?

The numbers are not well labeled.

<img width="195" alt="screen shot 2018-12-17 at 12 54 27 am" src="https://user-images.githubusercontent.com/5871417/50069142-bda5e980-0196-11e9-9479-d00c29ef4429.png">

**Comment by xprilion** [comment]
Hey! I would like to work on this task. However, I am unable to replicate this issue on my local machine. Can you please suggest me some pointers?

**Comment by bmcutler** [comment]
duplicate issue
