### ISSUE TITLE
drag and drop to upload > 20 student photo images might be broken

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3208]
Is there a limit on # of files?  

I tried to upload 42 images (not using zip, just a collection of .pngs), and only about half of them were uploaded.  Selecting fewer of them at a time they all went through.  

I didn't encounter any error messages.
I don't believe it was a problem with total file size.

**Comment by vorabrijesh** [comment]
I have opened PR [Max number of files which a user can upload #5201](https://github.com/Submitty/Submitty/pull/5201) which will not allow more than 20(default PHP) submissions. It will show an error message. If you want to upload more than 20, then you would have to zip the files.
