### ISSUE TITLE
2 minor forum bugs

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3218]
When I click on "alphabetical" or "chronological", the forum switches to the top (most recent/announcement post).  Fortunately, the mode stays and I can return to the thread I was previously on as a workaround.

Also, when someone else deletes a post, the notification is added to my notifications list, but without a link, so I can't clear it (unless I click "mark all as seen")

**Comment by mattraneri** [comment]
We just had a discussion about forum delete behavior:

The desired behavior is the following:

If the user is an instructor and allowed to view deleted forum posts, then the link should go to the forum and "Show deleted threads" should be enabled automatically.
If a student's post is deleted by an instructor or TA, then the student shouldn't get a link and only be able to clear it using the 'marked as read' option on the right hand side of the page
