### ISSUE TITLE
missleading documentation on `insert_database_version_data.py` script

### ISSUE THREAD

**Issue by dpshelio** [Submitty/Submitty#3222]
`insert_database_version_data.py` file on `sbin/autograder/` has [a misleading usage documentation](https://github.com/Submitty/Submitty/blob/master/sbin/autograder/insert_database_version_data.py#L10-L19). It says it can be called directly with arguments but it doesn't provide so.

**Comment by DaasDaham** [comment]
could you please expand on this issue

**Comment by shailpatels** [comment]
outdate, script and documentation no longer exist

**Comment by shailpatels** [comment]
Reopening - documentation disappeared? but may need to be rewritten
