### ISSUE TITLE
Add Tool Tips to Forum Post Badges

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#3223]
Posts on the forum get badges like this:
![image](https://user-images.githubusercontent.com/3719964/51503066-03ae2880-1da7-11e9-97bd-6454a9117c53.png)
It would be helpful if these icons had some sort of tooltip to describe what each meant since its not labeled anywhere else.

**Comment by drumilpatel2000** [comment]
@MasterOdin @shwehtom89 @KevinMackenzie  can you please briefly explain this issue to me ?

**Comment by shwehtom89** [comment]
@drumilpatel2000 This issue was still open because the pin icon in the forum was missing a tooltip see #3378. The other icon tooltips were added previously in #3280.
