### ISSUE TITLE
Feature Request: Sort capability to grade details page

### ISSUE THREAD

**Issue by dpshelio** [Submitty/Submitty#3236]
I would like to quickly sort the columns in the grade details page to see for example which ones I still need to mark.

I suppose that more complicated is then to keep the previous/next arrow to follow such ordering, but with the column ordering I could open them in different tabs as I need them.

**Comment by Kevin-MM** [comment]
I've referenced a pull request that will close this issue.  We've added sorting to most columns on that page.  We've added buttons to the TA grading interface that allow you to move to the next ungraded submission, either by any ungraded component, or by a specific ungraded component.  I believe this new functionality addresses this issue.
