### ISSUE TITLE
Feature request: Allow full grade without need for comment

### ISSUE THREAD

**Issue by dpshelio** [Submitty/Submitty#3237]
When grading manually, I cannot give full mark without providing a comment (or a blank space), whereas I can do so for no mark at all. I would think a 0 mark needs more feedback than a full mark.

**Comment by bmcutler** [comment]
Hi dpshelio,

I think what you're looking for is already implemented.  

If the instructor configuring the gradable sets up that component "assign points by count down", then the first mark will be "full credit", and most/all of the marks should be negative.  If the component is set to "assign points by count up", then the first mark will be "no credit", and most/all of the marks should be positive.

In either case, if you want both a "full credit", and a "no credit" mark, you can just add the other one at the start of grading.

Barb
