### ISSUE TITLE
Standardize Cron Usage in Submitty

### ISSUE THREAD

**Issue by kasra-sheik** [Submitty/Submitty#3256]
As of now, we haven't set a standard for adding/editing cron jobs throughout Submitty. It would be nice to have a centralized place where our jobs live so that future developers can easily manage them. 

@MasterOdin has suggested adding a static file in our .setup directory called `crontabs`. During the install process, we could just read in from that file and assign the job to the appropriate user.

This PR should move the cron job responsible for sending emails (and any other jobs that might exist at the time of reading this) into our static file(s). This way we have example usage for creating/installing cron jobs in Submitty moving forward.

**Comment by bmcutler** [comment]
Closing this for now.  Can re-open when we have a larger set of tasks (or multiple users) handled by cron jobs.
