### ISSUE TITLE
Improving form validation in `New Gradeable`

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3293]
Form validation are only applied when form is submitted. This creates a `bad experience` for the user as they are not able to rectify their mistakes on time.

Fix :- Form validation should be applicable `onchange` not `onsubmit` javascript event. This will make the user to check their mistakes at time of filling the form which creates a `good experience` for the user.

**Comment by sarthak77** [comment]
Can i take up this issue?

**Comment by MasterOdin** [comment]
I would advocate for an approach such that if there is mistakes, the instructor is told the error and also has the form filled in for them with what they put in. That way we're only doing validation in one place (which is hard enough) and not over two.

**Comment by bmcutler** [comment]
current behavior is ok.  would require doing the same check in two places and be harder to maintain.  

Closing issue (please re-open if there are more specific problems)
