### ISSUE TITLE
Late days and out-of-order homework submissions & grading

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#330]
Just wondering how late days totaling & exceeding allowed total late days work if the homework deadlines are close, but students submit them out of order or the TAs grade out of order.

Assuming that the number of allowed late days is greater than the # of days between due dates.  Or if there are multiple open homeworks simultaneously.  Also with special circumstance extensions, students might be submitting homeworks out-of-order.

**Comment by MasterOdin** [comment]
Grading out of order would break things yes. I guess a solution for this would be if a TA grades something that would affect a later grade, it does checked that the status of the later homework is not affected and if it is, then we make later homework grades drafts till a TA looks at it again.

Students submitting things out of order shouldn't really matter as their ability to submit doesn't depend on their late day status in any day.

**Comment by bmcutler** [comment]
What if two rubrics have the same due date & time (no unique ordering)

**Comment by bmcutler** [comment]
Adding @JerameyATyler to test and document current functionality

**Comment by bmcutler** [comment]
This is mostly finished.
Will re-open new issue(s) with specific bugs or new features as needed.
