### ISSUE TITLE
Add fake SMTPD server to vagrant to test emails

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3310]
Right now there's no way to test the new email functionality of Submitty except on a live server with a real SMTP setup. We should install and setup something like my own [nullsmtpd](https://github.com/MasterOdin/nullsmtpd) to write any "sent" emails to a folder on the local machine.

**Comment by kasra-sheik** [comment]
Just looked through your package, this looks awesome. Testing email related functionality on Submitty requires me to comment out parts of the email script in order to avoid spamming hundreds of fake emails and getting undelivered replies. Would love to see this added to the dev sandbox.
