### ISSUE TITLE
Potential Student Confusion: military vs am/pm time

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3313]
In most places on the site for assignment deadlines we use military time (e.g., 23:59:59) with no am/pm.  This is fine for deadlines after noon, it's clear.  But for deadlines before noon, @KCony has pointed out this could be unclear, and students might reasonably argue that a "10:00" deadline means 10pm not 10am.  

In other places we do use am/pm, e.g., in the discussion forum, and for some stats information about grading.  So our lack of consistency is problematic.

Proposal:  a) Use military time + redundantly label am/pm.  Or b) switch to non-military time w/ am/pm everywhere.  This is (mostly) for student facing display only.  Database would still be military, time pickers would still be military.  

Thoughts?  @MasterOdin @holzbh @emaicus @andrewaikens87 

Once we have a plan, perhaps @shwehtom89 can tackle the implementation :)

**Comment by MasterOdin** [comment]
My vote is for b: use am/pm everywhere that's displayed to students and leaving the time-pickers for setting up gradeables as military time.

**Comment by holzbh** [comment]
I'm a fan of military time but since we're in the US it's not uncommon to expect 12 hour time, and I agree that students might see something like "10:00" and think that means 10PM. I know it's simple math but a lot of people get thrown off by military time so my vote would be for option b) as well.

**Comment by hinduBale** [comment]
Can anyone point out, where exactly the changes have to be made. I mean, in which file, the code has to be changed?  
I would like to make this conversion from military to non-military timing.
