### ISSUE TITLE
Queue order is backwards

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#3318]
When you submit you get put at the end of the queue. That is reported as "1 out of 5" ... which means there are 4 others in front of you.

This is backwards from how you'd expect a queue to work, where being first means nobody is in front of you. Just needs a invert and it should be good.

**Comment by vaibhav-k3** [comment]
Hello , My name is Vaibhav Kulkarni , i am new to submitty. i want to work on this issue so that i can get familiar with codebase . can you please give me a pointer to where i shall start from or have a look at ?.
