### ISSUE TITLE
Easier way to un-resolve a resolved forum thread

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3324]
use case:

student asks question

instructor answers question (and believes problem is solved, so presses the "mark as resolved" button)

student (possibly same/possibly different student) wants to ask a followup/extension of the original question and may or may not want to mark the thread as unresolved again should see 2 blue buttons at the bottom of their response:  "Submit Reply to All"   or "Submit Reply to All & Mark as Unresolved" . (Only do this if a thread is in 'resolved' state.  If a thread is in 'comment' or 'unresolved' state just have submit reply to all button'.)

**Comment by sarvesh211999** [comment]
@bmcutler I want to work on this issue.
