### ISSUE TITLE
Cleanup Emails Table

### ISSUE THREAD

**Issue by kasra-sheik** [Submitty/Submitty#3326]
As email related functionality has finally been rolled out and is live, the emails table is growing fast. With each instructor post, seating assignment, grades released, and other class-communication methods, hundreds of rows are being added to the emails table.

As for the current mechanism for sending emails, the _send_email.py_ script tries to read 100 unsent emails off of the _emails_ table every minute. Given the growing size of the table, queries against the table might start to slow down after a while. It might be nice to add a cleanup script which deletes old (sent) emails after a certain amount of time (maybe weekly/monthly/at the end of each semester). 

Another discussion would be to sort/index the table in such a way so that our desired queries don't take as long despite potentially thousands of rows being searched. One method could be to always append queued emails to the end of the table so that we don't have to sift through the entire table to find unsent emails.

**Comment by MasterOdin** [comment]
While I could get behind arching/deleting old emails after a set period of time, like everything that relates to a DB, we should base this around real world numbers and statistics and not just gut feelings on what we think would be good.

For example, a simple use case I cooked up locally:
```
submitty=# SELECT COUNT(*) FROM emails;
  count
---------
 3847125
(1 row)

Time: 254.037 ms
submitty=# SELECT COUNT(*) FROM emails WHERE sent IS NULL;
  count
---------
 1300000
(1 row)

Time: 272.905 ms
submitty=# SELECT * FROM emails WHERE sent IS NULL ORDER BY id LIMIT 25;
... RESULTS ...
(25 rows)

Time: 435.059 ms
```

Which run on my laptop (so less powerful than the production server) means that finding 25 emails right in the middle of a table with 2+ million rows still takes less than half a second (which is probably not the slowest part of the script). Updating 100 rows in there takes about ~1-5ms. I would say this is easily not a major bottleneck in the system, especially compared to things like 

The point of this is that I think it's important that we note the actual growth of the email table over a period of time (per day? per week?) and use that to make an informed decision on this (though I'd vote for cleaning out the table of the previous semester right as we go into the next semester).

> Another discussion would be to sort/index the table in such a way so that our desired queries don't take as long despite potentially thousands of rows being searched. One method could be to always append queued emails to the end of the table so that we don't have to sift through the entire table to find unsent emails.

This already happens in that `id` is an autoincrement primary key which is an index we use to sort the table on. This column is always in-order (as we let the DB set it for incoming new rows) and so there's no need to take any action here.

**Comment by bmcutler** [comment]
Simple data points:
~1,000 emails in the last day
~7,500 emails in the last week
~34,000 emails since Jan 1st (today is Feb 20th, first day of the term was Jan 14th)
~163,000 emails in 1 year of usage.  (significant additional functionality was added this summer, so this might not represent a 'normal' year.)

**Comment by bmcutler** [comment]
In addition to the performance cost for queries, we should consider the memory usage of this table & backups of this data.   

Using 
select pg_size_pretty(pg_database_size('NAME_OF_DATABASE'));

database for a single large course ~50-100 MB
current size of master database 171 MB

Using
select pg_size_pretty(pg_total_relation_size('emails'));

current size of the emails table (stored in the master database), after ~1 year  155 MB
