### ISSUE TITLE
Customizable page footer

### ISSUE THREAD

**Issue by mcglow2** [Submitty/Submitty#3332]
It would be beneficial for site admins to have the ability to add a bit of custom text and HTML to the page footers.

**Specific use case:** Adding links, messages, or disclaimers as required by policy.  Such as RPIs web accessibility policy which requires a link to it on each page.

**Comment by MasterOdin** [comment]
Is this something that would ever need to be done at the course level or is it probably fine to leave at the system level?

**Comment by mcglow2** [comment]
System level should be sufficient for the use cases I can envision.

**Comment by MasterOdin** [comment]
I would say let's put in `/usr/local/submitty/config` and new file named `footer_links.json` that has the same structure as the [sidebar.json](https://submitty.org/instructor/website_customization#specifying-custom-links-in-the-submitty-sidebar) we use for Courses' sidebar.

**Comment by accakks** [comment]
Hi @mcglow2 @MasterOdin Can I take this up?

**Comment by DaasDaham** [comment]
@MasterOdin shall the sysadmin append data to footer_links.json file through a JavaScript function ? 

https://stackoverflow.com/questions/36856232/write-add-data-in-json-file-using-node-js/36856787

Will this be a viable method ?

**Comment by MasterOdin** [comment]
Feel free @accakks.

It would not be possible to do this through JS as we don't have node as a dependency of Submitty (and I'm against adding it here). The sysadmin would just manually edit the file on the file system with their choice of editor (nano, emacs, vim, etc.) following a workflow similar to that of instructors of defining their sidebar (see the link I used in my previous comment).

**Comment by Fenn-CS** [comment]
@accakks  are you still working on this?

**Comment by accakks** [comment]
@Fenn-CS No, you can take this up if you want.

**Comment by Fenn-CS** [comment]
Ok thanks... I am currently working on another issue would take this up next if it's still up.

**Comment by Fenn-CS** [comment]
Ok thanks for letting me know.
