### ISSUE TITLE
submitty.json cgi_url value is ignored

### ISSUE THREAD

**Issue by mcglow2** [Submitty/Submitty#3335]
The **cgi_url** value in the **submitty.json** config file is not used by the code anymore.  Model **Config** builds **cgi_url** from the **base_url** value.  **base_url** is derived from the **submission_url** value in  **submitty.json**

I ran into this when attempting to allow remote machines to access the vagrant install running on my dev machine.   Apache submitty config was modified to listen on all IP addresses.  Vagrant was configured to forward host 11132 to guest 80.

**submitty.json** 
```
  "submission_url": "http://mypublic.rpi.edu:11132",
  "vcs_url": "",
  "cgi_url": "http://127.0.0.1/cgi-bin",

```
resulted in this error.  Note cURL trying to access cgi-bin at the host address.

![robot1](https://user-images.githubusercontent.com/13893140/53885964-fbbfe600-3fec-11e9-95ff-04f095081a77.png)

I was able to work around this, but the reference to **cgi_url** should be removed from the setup scripts and config files if it cannot be used.

**Comment by mattraneri** [comment]
The threat model of the cgi-bin directory is assuming that it can only be accessed internally from the server- I haven't been through every one, but just be aware that by allowing the directory to be public that you're increasing the attack surface with code that doesn't expect to be called externally

That being said, the config option could be removed

**Comment by MasterOdin** [comment]
The error you get looks to be that the system is attempting to make a call to the submission_url via cURL and that's failing. My guess would be that the hostname you're using is not accessible from within Vagrant which is causing the error to throw when it attempts to make a call from within itself. I wonder if it would be worth re-enabling the cgi_url variable to be read in in similar fashion to vcs_url such that if it's blank (or does not exist), then use submission_url to construct it, else use the value in submitty.json.

@mcglow2 How did you end up working around this and what would you have ideally wanted available to you to help make it easier to avoid this error? Or is just removing the unused variable fine?

**Comment by mcglow2** [comment]
@mattraneri Nothing is currently protecting the /cgi-bin directory from external access.  I confirmed on the production CS submiity site.  Any machine can post to /cgi-bin/pam_check.cgi and get a response.  I agree that this is probably not a good thing.

@MasterOdin I worked around the vagrant name resolution by putting the DNS name and IP for mypublic.rpi.edu in the vagrant VMs /etc/hosts file.

**Comment by mcglow2** [comment]
@mattraneri I found #3312 and will see if they can apply this config change to the production server.

**Comment by MasterOdin** [comment]
And if you could have set the cgi_url in the config, then you could have done that instead of modifying the hosts file and had it all work?

**Comment by mcglow2** [comment]
@MasterOdin Yes, if the value of cgi_url was used by the Config model I believe it would have worked

**Comment by DaasDaham** [comment]
@MasterOdin So basically there will be an if-else condition in the submitty_http.conf file such that whenever an error is thrown, then a call should be made from cgi_url value ?

**Comment by MasterOdin** [comment]
No, this isn't an edit to the apache configuration files. It's a change to `site/app/models/Config.php` such that if it detects a non-empty value for cgi_url, use that instead of defaulting always to `base_url() + /cgi-bin`

**Comment by Sahil333** [comment]
I placed an if-else block at the initialization of cgi_url in Config.php. Hope it will work.
