### ISSUE TITLE
Extremely long comments and \n appearing in TA comments

### ISSUE THREAD

**Issue by Mijumaru3** [Submitty/Submitty#335]
In Principles of Software in the returned TA grade rubric that students see some of the comments left by the TA are one incredibly long line that I have to scroll over horizontally to see all of it. Instead of the comments breaking into new lines, there are "\n" 's appearing in the comments that indicate where a newline should have started.

**Comment by MasterOdin** [comment]
Should probably wrap [nl2br](http://php.net/manual/en/function.nl2br.php) around [Line 337](https://github.com/RCOS-Grading-Server/HWserver/blob/master/public/view/homework.php#L377)

**Comment by MasterOdin** [comment]
So it's a potential of several things. One of them might be that that we're saving line endings as ```\r\n``` to the database and then when trying to display it back to the browser in the textarea it gets messed up (as it'll only support ```\n```?). Alternatively, the clean_string_javascript function might have some bugs in it that isn't properly doing something (I'm not sure what it's purpose is to be honest).

**Comment by bmcutler** [comment]
fixed in PR #377
