### ISSUE TITLE
Redirection not handled properly on login page

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3353]
### Reproduction of Error
Error is thrown when we press login without entering the password.This does not implies wrong password but password = `NULL`
![screenshot from 2019-03-08 04-43-26](https://user-images.githubusercontent.com/42701709/53996395-3eed9680-415e-11e9-9858-bfe0621153e7.png)
![screenshot from 2019-03-08 04-45-04](https://user-images.githubusercontent.com/42701709/53996396-3eed9680-415e-11e9-85ea-4cdf4a4b1efe.png)

### Possible Solution
Front end javascript form validation can be provided .Such that when password or login = `NULL` It throws an error and form is not submitted.

**Comment by MasterOdin** [comment]
I think we can be even simpler than that and just make both fields required. However, we should also investigate what the JSON response we're getting back is here as at worst case, we should just be outputting "Bad username/password" to the user and not throwing an exception/fatal error.
