### ISSUE TITLE
Improve documentation on apache configurations

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3356]
On https://submitty.org/sysadmin/installation for step 6, we give some instructions on setting up Apache and point to the two existing apache configurations we have:
https://github.com/Submitty/Submitty/blob/master/.setup/apache/submitty.conf
https://github.com/Submitty/Submitty/blob/master/.setup/apache/submitty_http.conf

We should put in documentation in both of these files on what all of it does and why it's there so that it acts as a good starting point and that sysadmins can know why it is we're doing stuff the way we are.

**Comment by bmcutler** [comment]
@MasterOdin bumping priority on this issue, please :)

**Comment by MasterOdin** [comment]
Currently working on this now, should have it done soonish. Order of work as I see it:

- [ ] Fix #1040 by making Travis use the same apache conf as Vagrant
- [ ] Move that conf from `.setup/vagrant/sites-available/submitty.conf` to `.setup/apache/submitty_http.conf`
- [ ] Migrate all non-ssl bits of the new `.setup/apache/submitty_http.conf` to `.setup/apache/submitty.conf`

which should then close this issue as `.setup/vagrant/sites-available/submitty.conf` is fairly well documented.
