### ISSUE TITLE
Wrong Command for database

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3366]
# Error
On `vagrant ssh` we get following
![Screenshot from 2019-03-10 15-32-15](https://user-images.githubusercontent.com/42701709/54083494-0f9b7d00-434a-11e9-9370-6ad39fb28040.png)
According to above description database is hosted on `15432` but actually database is hosted on port `16432` .
This is also mentioned  in documentation that  database is hosted on `16432`.

# Possible Solution
Change  `15432` to `16432` in  `.setup/distro_setup/setup_distro.sh`.

**Comment by DaasDaham** [comment]
yes I noticed it as well
