### ISSUE TITLE
Improve completion signal on ajax grading forms

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#337]
These include labs, tests, and other grades. Right now a blue/red border gets shown to the right of the updated box which messes with the display of things. Should change the icon to be less intrusive to the user but still indicate when an ajax call is being made/completes/fails.

Additionally, this goes hand in hand with #126 to allow for TAs to enter grades as quickly as humanly possible and not have the page break for them (disregarding the race conditions if another TA tries to enter the same grade at the same time).

**Comment by bmcutler** [comment]
Closing now, we can re-open and investigate if it is still a problem.
