### ISSUE TITLE
Shrink navigation menu on smaller resolutions

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#338]
Right now when shrinking the page width, the navigation bar will just push downward covering content on the page, as it's an absolute div (this can be replicated on manage rubric page as if you shrink the width completely, you can't hit the "New Rubric" button anymore). We should make it such that it starts condensing menu options as you get smaller and smaller till at the smallest possible resolution it just shows a button for dropdown only and within the dropdown are all menu options.

**Comment by bmcutler** [comment]
will go away when we have the navigation pages
