### ISSUE TITLE
Sidebar links tooltip CSS overridden on new gradeable page

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3380]
##### Proper Working of bootstrap tooltip:-
![Screenshot from 2019-03-12 10-53-35](https://user-images.githubusercontent.com/42701709/54177370-00d2d880-44b8-11e9-85c9-73d8e2906c56.png)
##### Tooltip become less opaque when `New Gradeable` is selected
![Screenshot from 2019-03-12 11-13-44](https://user-images.githubusercontent.com/42701709/54177371-00d2d880-44b8-11e9-9d66-5f90a0e9d73b.png)
## Possible Cause
CSS is overrided when `New Gradeable` is opened.
Overriding CSS maybe present in twig of `site/app/templates/admin/admin_gradeable`.

**Comment by sin3point14** [comment]
I would like to try solving this one, any tips?
and also as i am not very proficient with git can i get some help on how to submit my code?

**Comment by sin3point14** [comment]
I think that this problem was caused due to the difference in perspective of the viewer with respect to the monitor, as when lined side-by-side there seems to be no difference in the tooltips-
![image](https://user-images.githubusercontent.com/43549821/54398154-f9414880-46de-11e9-9410-47c929eb0eff.png)

**Comment by sin3point14** [comment]
This doesn't seem to be an actual issue, but an illusion sort of thing caused by the angle at which a person views the display(or perhaps is monitor specific?)-
![image](https://user-images.githubusercontent.com/43549821/54399837-3957f980-46e6-11e9-9cbe-725e44dde740.png)

**Comment by abhinavsagar** [comment]
Can i work on this?
