### ISSUE TITLE
Remove hardcoded specifics from Rainbow Grades

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#339]
An example of this would be [these lines](https://github.com/RCOS-Grading-Server/HWserver/blob/master/RainbowGrades/student.cpp#L245-247) that suppose specific sections are fake, though this won't work for all semesters/courses (such as CSCI1100 sometimes having 15 sections in a fall semester)

**Comment by bmcutler** [comment]
Make a new issue for any specific remaining problems.
