### ISSUE TITLE
Small textarea for Editing in Discussion Forum

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3410]
## Bug
When editing a long post we can only see a small text area which is not scrollable  This make editing of post difficult .
When we edit suddenly size of text area increases. 
![Error](https://user-images.githubusercontent.com/42701709/54491250-eac37e80-48e2-11e9-9bb9-00aed12501b6.gif)

**Comment by sin3point14** [comment]
I will be able to work up a solution but wouldn't it make more sense if the scrollbar would apply only to the post text and not the buttons, else what would be the use of the "Link" and "Code" buttons and for ease of the user it is better to have the "Update Post" and "Cancel" button stuck to the popup as well. So should I integrate these changes as well?
