### ISSUE TITLE
Sort People by Lastname instead of User ID

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#3414]
Currently, in the grading page, students are sorted by their user ID.

As user ID can be irregular, and students can have a preferred last name, this may lead to confusion.

For example, in the sample data, there is someone named Alyssa P Hacker, and different from other students, her user ID starts with her first name, making her the first in the list. When a professor grades, she or he may instinctively go to the bottom of the page to find someone whose last name starts with "H", who is actually on the top of the list.

![p1](https://user-images.githubusercontent.com/20266703/54497811-65c56e80-48bc-11e9-8e08-56968f67fe9f.png)

Another case, if someone changes the preferred last name (like Tim Cook changes his name to Tim Apple), he or she does not get relocated. This may be confusing for professors who are used to finding people by last name, too.

![p2](https://user-images.githubusercontent.com/20266703/54497812-6827c880-48bc-11e9-97d8-9c897c476e87.png)

**Comment by bmcutler** [comment]
This is likely a low priority enhancement.  We already have sort by preferred name available on the checkpoint grading which is used in lab where alpha by name are important.  Manual grading of uploaded assignments primarily needs consistent grading.  Or sorting by grading status:  e.g. feature request #3236.

The page for grading of uploaded assignments is getting an overhaul for issue #1314  and PR #3307.  Addition of new sorting should be held until this overhaul is complete.

**Comment by Kevin-MM** [comment]
I believe #4171 may close this issue?

**Comment by zjxiaohan** [comment]
Yeah I believe so I was thinking of the same thing when I saw your PR.
