### ISSUE TITLE
Feature request: which individuals on team have viewed grade

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3415]
related to #3131 

Right now it just shows a green check mark, but it would be good to know which team member(s) have viewed their grade.  

Step 1:  We may need to modify the database to store more detailed information?    What's the right design?

Step 2:  Visually, how should we display this?  My suggestion...  red x = no one has seen it.  then a mix of green & grey checkmarks, if it's a team of 3 and 2 have viewed it will be 2 green checks and 1 grey check.  Then when you hover over the checks, the hover text lists the members who have viewed and the members who have not viewed.   Note:  If you hover over any single check it shows the same complete information for the team.  You don't have to hover over individual checkmarks.

Then on the status page, it lists the # of teams that have had at least one member view (current data), and separately the # of students who have viewed their team's grade.

**Comment by sin3point14** [comment]
A suggestion for the visual indication is to use a style similar to facebook's reacts, Where we could simply have 2 checkmarks, green and gray, with a number next to them to indicate number of individuals under that category and hovering them would show the list of members or if the team size is very large then, say, 10 members in the hover dropdown and rest would be visible in a popup on clicking the checkmark.
