### ISSUE TITLE
Instructor GUI for new gradeable - Boxes for typing are small

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3416]
If the gradeable title is long, the text scrolls horizontally and is difficult to see and edit.  The box should get bigger as needed.  Other boxes too.

In general, make this page more visually pleasing.

**Comment by bejuzb0** [comment]
Are we looking to make the boxes into something like textarea? In the textarea the vertical scrollbar appears, which makes it easier to edit texts but the box size remains same, or should the box height should increase?

**Comment by Fenn-CS** [comment]
Hello @bmcutler 

> Boxes for typing are small

By that, I understand generally the input fields are not large enough (take up enough space) is this right?

>  The box should get bigger as needed. Other boxes too

Two options come in mind here, 
1. Making the form vertical such that each title and input box take up a full row on their without needing to make the boxes grow and input gets. This is with the assumption that a title for greadable is normally not supposed to be too long.
2. Doing 1 with the exception that we add some JavaScript to expand the input box sizes as text grows.  Here there's no assumption and input can really long without giving instructors bad experiences.

## old view 
![new-greadable-old-look](https://user-images.githubusercontent.com/14317775/55043935-a483c300-5038-11e9-9f89-46a4cc2c927c.png)
## proposed vertical view (title and input boxes on different rows)
![new-greadable-proposed-look](https://user-images.githubusercontent.com/14317775/55043915-8f0e9900-5038-11e9-9e7d-0d3e75838a03.png)

Is this a good way to present it? If so, I would go ahead and push the update. :)
