### ISSUE TITLE
date picker time intialization

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3419]
from instructor:

When I go to the date/time field, the picker sticks to whatever it had as a default time rather than loading the actual value from the control. In the example below, I'd expect the picker to show 9:59. Actually, if I just select some new date in the picker without touching the time, it would still set the time to 23:59, quite unexpectedly for me.

![image](https://user-images.githubusercontent.com/5871417/54506043-f7f76200-4910-11e9-8066-c0d4c66f3164.png)

**Comment by VictorLi718** [comment]
Is this the bug you are facing? 
![gr1yhYiS16](https://user-images.githubusercontent.com/30506009/56100957-dfb53b80-5eec-11e9-8cf5-8c75324068b4.gif)
Seems that it will not update the picker as soon as you change the value, it will update the picker when you close the picker and reopen it. It is a tough problem, I am going to look at it further.

**Comment by shwehtom89** [comment]
Hi Victor, yes I believe that is bug we are going after. Although in the meeting we discussed that ideally we would have the time picker sync with the text as you type. Please checkout [https://github.com/Submitty/Submitty/tree/fix_date_picker_val](url). This updates the picker if you manually type.

**Comment by VictorLi718** [comment]
Hi Thomas @shwehtom89 . I tested your code and it solved this bug. But it clears out the default value like this. I don't if this only happens on my computer. Could you please solve them?
![image](https://user-images.githubusercontent.com/30506009/56256822-4034ac00-6098-11e9-8c81-f716f1e5f6da.png)
And remember to clear out the console.log when everything is good.

**Comment by emaicus** [comment]
This appears to have been fixed over the summer.
