### ISSUE TITLE
Better course material checkboxes

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#3428]
It is not easy for an instructor to share a lot of files to students if the files are not zipped, as every file needs to be checked individually.

![Screenshot from 2019-03-19 20-48-34](https://user-images.githubusercontent.com/20266703/54658113-28620c00-4a89-11e9-8e2a-b7fadb624367.png)

It might be nice if there are some kind of tree view style checkboxes, where the value in the upper level overrides all values of the lower level if the checkbox of the upper directory is checked.

![image](https://user-images.githubusercontent.com/20266703/54658186-75de7900-4a89-11e9-80df-c8df9485580e.png)

**Comment by xprilion** [comment]
Would like to work on this! A checkbox beside the folder name should solve it :)
