### ISSUE TITLE
Implement notification system

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#343]
We should implement a notification system (like LMS) that alerts users for various events. It should consist of popup to view the notification as well as setting to potentially send email about it. 

Potential events for notification would be:
- New Homework (for submission for students in non-disabled sections and for grading for TAs)
- Grades released

**Comment by bmcutler** [comment]
Could also notify TAs that the rubric is ready for them to start grading :)

Could add a date that the instructor expects grading to be complete and it pesters them with increasing frequency as the deadline approaches.

**Comment by bmcutler** [comment]
This will be clear when we have the navigation/home pages for student/ta/instructor

**Comment by bmcutler** [comment]
This is initially "badges" on the new/unread/reply-to-my-thread forum posts.
But it is also an option to sign up for (or unsubscribe) email notifications... when we have sorted out how to email.

**Comment by bmcutler** [comment]
yay! done (months ago)
