### ISSUE TITLE
Instructor/TA documentation for bulk upload / QR codes

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3434]
and link to/from current documentation on scanning

**Comment by shailpatels** [comment]
@bmcutler Could you clarify what type of documentation you want? There's https://submitty.org/instructor/exams#bulk-upload-and-split-with-qr-codes which is linked from the bulk upload page on submitty when you click the bulk upload with qr button.

**Comment by bmcutler** [comment]
oh great :) Yes, that's mostly what we want.

When implementation is finished, you and I should review the finished package.  Also, we should add some '?' links from the upload page to the docs.  I heard from an instructor that their TAs were confused/stuck about both how to scan and how to upload and they didn't know to look on submitty.org for instructions.
