### ISSUE TITLE
Move to a more extendable parser of bbcode for forums

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3439]
Right now, we use a custom parser for the limited source of bbcodes. However, due to the very simplistic regex based approach we have, it's not possible to use any bbcodes within the [code] one (as they'd get processed) and that writing the rules for them are somewhat complex. #3403 shows an example of this issue.

It would probably be useful to instructors to have some way to specify at least some slight formatting of things including bold, italics, etc. To support these, do we want to try and write our own "proper engine" or would it be possible/better to use something existing, like https://github.com/thunderer/Shortcode? Additionally, moving to this, we'd probably also then just force usage of bbcode for formatting of various other textboxes and the like (such as shown in #1821). I'd heavily advocate for consistency here over allowing only bbcode in the forums and then some HTML subset elsewhere which is bound to be confusing, and a pain to document/maintain.

I'm not sure it's worth putting any further work into the forums and how it handles formatting until we come to a conclusion on this topic. Thoughts @bmcutler and @andrewaikens87?

**Comment by bmcutler** [comment]
related to #3197 & #3513

**Comment by MasterOdin** [comment]
Closed as we have moved to Markdown for rendering.
