### ISSUE TITLE
Allow rubric to grade non-electronic/non HSS submissions

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#344]
A new instructor configuration option, that allows the hw rubric grader to grade non-electronic/non HSS submissions.

Instead of showing "no submission", allow the grader to enter the date submitted (or equivalently the # of late days used), and then grade using the rubric.

The student page view will also need to be changed.  Currently if a student has no submissions for a homework, then it doesn't even look for a TA grade result (even if it might be available).

Current workaround is to create a dummy empty assignment submissions for all students (but this doesn't allow the grader to (easily) specify days late.

**Comment by MasterOdin** [comment]
We should add a new column to the assignments table that reads "allow_submission" which defaults to true where:

if true, system acts like it does currently allowing student to submit, TA grades based off submitted code (or lack thereof) 

if false, students see an assignment, but cannot submit anything, TA grades whatever having them enter submission date (defaults to due date of assignment) before then just filling out the rubric. The rubric should also be full screen in this case with no left pane.

**Comment by MasterOdin** [comment]
The student page should be changed though such that it looks to see if there is a grade available (regardless of submission count) and display it. We're already generating the TA reports for non-submissions anyway so might as well show them.

**Comment by bmcutler** [comment]
Yup, sounds good :)

**Comment by bmcutler** [comment]
Implemented something like this for exam grading.  Some remaining open tasks in other issues.
