### ISSUE TITLE
Improve student ID validation in "Late Days Allowed"

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#3449]
The code regarding validation only checks if that ID exists in Submitty, which could lead to problems.

Known bugs are:
- [ ] ~Instructors can enter late days for themselves.~ (Removed according to the [suggestion](https://github.com/Submitty/Submitty/issues/3449#issuecomment-475809032) of @MasterOdin)
- [ ] When instructors enter late days for students who do not belong to this course, there are no error messages.

Related code: https://github.com/Submitty/Submitty/blob/14b37fcf3af673ad67a65f069bb61c90c3d703f1/site/app/controllers/admin/LateController.php#L95-L100

**Comment by MasterOdin** [comment]
So I'm not sure the first is a real issue as that really falls under "we trust our instructors not to be actively malicious against themselves".

The second should definitely be fixed though.

**Comment by zjxiaohan** [comment]
Thank you for your information!

That's true :rofl: I would doubt if instructors will enter IDs for themselves, and I agree that the second one is more urgent. That being said, if we could fix the second one, the first one could be easily fixed. Because the problem of the current code is that `getSubmittyUser` does not get any information about courses.

**Comment by MasterOdin** [comment]
Like I said, I don't think the first is a real problem and that we really don't have to bother trying to "fix" it, regardless of how easy/hard it is (I'd advocate for not bothering for the added complexity of it).

**Comment by zjxiaohan** [comment]
Thank you for pointing out the unnecessary complexity concern. I agree and I have removed the first problem in the issue.
