### ISSUE TITLE
Forum Bar Rework

### ISSUE THREAD

**Issue by shwehtom89** [Submitty/Submitty#3462]
The Discussion Forum top bar should have its layout changed to match the order outlined in
![updated_forum_bar](https://user-images.githubusercontent.com/34754780/54873422-3d51de80-4dac-11e9-8e07-db0d994f67a3.png)

The "More" button should invoke a drop down menu for more advanced features such as adjusting the order of posts by chronological, alphabetical or hierarchical as well as having options to show deleted and merged threads. A link to the stats page should also be available in "More".

**Comment by bmcutler** [comment]
closed with #3475
