### ISSUE TITLE
Include Student ID number in Student Data

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#3465]
Allow for an optional field to be included in student data that is a numeric-only student ID (e.g. 9-digit RPI RIN)

**Comment by bmcutler** [comment]
Use case for this feature will be automatically assigning scanned exams to students.  If we have the students handwrite a 9 digit student ID number into a special box on the exam, we should be able to detect this ID with high accuracy (well known & 'solved' computer vision / machine vision post office zip code problem).

**Comment by bmcutler** [comment]
group meeting...  decided to call this "numeric_id" in the database.
It will be a new column both master db and also copied by trigger to each course db.
Field may be null or empty string if data doesn't exist.
This is presumably a unique number assigned by the school, but we will not enforce this with the database.  (In case a school does re-use these numbers years later).
