### ISSUE TITLE
Wrong command in regrade request

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3484]
## Issue
Initially when we click on `Submit Grade Inquiry` . After it is resolved when we click `Submit Grade Inquiry` again It will result change in status of query but it will not post anything 
![ezgif com-video-to-gif(6)](https://user-images.githubusercontent.com/42701709/54922754-d7419480-4f2e-11e9-8001-6b00f0955c52.gif)

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wrong command in regrade request](https://trello.com/c/GWgakVwt/3-wrong-command-in-regrade-request)
