### ISSUE TITLE
Student Photos displays students without images as broken img tags

### ISSUE THREAD

**Issue by xprilion** [Submitty/Submitty#3503]
On the Student Photos page, currently, when a student does not have any image uploaded for him/her, the list of students is displayed with broken img tags defined as - 

`<img alt="No Image Available" />`

However, it would be more intuitive to the design if instead a placeholder image was displayed, or a properly formatted Error message. Using a broken img tag does not feel correct. 

![Screenshot from 2019-03-27 18-38-28](https://user-images.githubusercontent.com/7047208/55078168-87de9e00-50bf-11e9-88fd-6d948705c282.png)

**Comment by xprilion** [comment]
Looking for suggestions on what would be a good replacement for the broken tags. Will submit my solution once decided! :)

**Comment by MasterOdin** [comment]
I would probably vote for either just not showing an image at all without a title, display an identicon (using something client side like https://github.com/stewartlord/identicon.js or perhaps a server side one?), or something like this:
![No Image Example](https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg?sanitize=true)
