### ISSUE TITLE
Unrendered &quot; in gradable submission page

### ISSUE THREAD

**Issue by xprilion** [Submitty/Submitty#3513]
There's a tiny error here which prevents` &quot;` to render as " as shown below in the highlighted text

![Screenshot from 2019-03-31 21-03-42](https://user-images.githubusercontent.com/7047208/55291177-2721cf00-53f9-11e9-9558-6bbd4b7f06e6.png)

**Comment by bmcutler** [comment]
See also comments in #3685 
We should switch to markdown formatting for these instructor specified strings.
