### ISSUE TITLE
Upload Classlist Error Disappears

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#3515]
After uploading an improperly formatted CSV file through the web interface an error notification shows up, but before you can read and understand the error, it disappears. I had to take a screen shot and then read the message before being able to fix the issue. The notification has a x box, but just disappears on its own. The only way to see the error message again is to repeat the process.

It seems that the message should display until the users closes it. (Or at least can stop it from disappearing.)

**Comment by bmcutler** [comment]
Related to #3212 ?

**Comment by KevinMackenzie** [comment]
This kind of issue could definitely be solved by spawning error messages in JS in some cases.  I suspect the issue here is that page is being loaded a second time quickly after the first page load and clearing the messages (since they aren't persistent across page loads).

**Comment by MasterOdin** [comment]
The problem here is that the status messages fade out automatically after 5 seconds, and these status messages are probably not the appropriate vehicle to deliver validation errors.
