### ISSUE TITLE
Anonymous issues (for limited access graders)

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#3523]
Introduced in #3302. Limited access graders have access to student names who posted anonymously. To recreate simply open the edit post or show history option on a post that is anonymous.

**Comment by MasterOdin** [comment]
Is this that limited access graders should be able to edit posts, but not view who posted?

**Comment by andrewaikens87** [comment]
Yes, if the original contributor requested to post anonymously.
