### ISSUE TITLE
Late Resubmit button red for gradeables with no autograding

### ISSUE THREAD

**Issue by CouleeApps** [Submitty/Submitty#3530]
When a gradeable has no autograding points, even if you have submitted on time, the Late Resubmit button will be red. This is because the button checks "do you have more than 50% of 0 points" which is false, so it's red. 

![](https://i.imgur.com/21eNPUV.jpg)

Easy reproduce: submit to the development "upload only" gradeable and then set the deadline to have passed. Even though you submitted the button is red.

Fix is to find where it does that (probably NavigationView.php) and make it make the button not red if there are no autograding points.

**Comment by rohithbalaji123** [comment]
@CouleeApps, I would like to work on this issue!

**Comment by CouleeApps** [comment]
@rohithbalaji123 if you want to work on this, be sure to fork the repository and make a pull request with your fixes.

**Comment by rohithbalaji123** [comment]
Yeah, sure. Thanks!

**Comment by rohithbalaji123** [comment]
@CouleeApps, can you please review the PR?
