### ISSUE TITLE
Number of Late Days Displaying Too Low

### ISSUE THREAD

**Issue by farrer1** [Submitty/Submitty#3534]
**Describe the bug**
When looking at a specific homework for which you have already submitted late, Submitty displays the number of late days you will have after a late submit incorrectly. It takes the number of late days you have left after your existing late submission, and displays the number of late days you would have left if you were charged those late days again. For example, if I had 4 late days and submitted an assignment a day late, it would tell me I had 3 left, then say that if I submit again that same day, I will have 2 left. If you submit again, it still says you have 3 and will have 2.

**Expected behavior**
Submitty displays that I will have the same number of late days I have now if it the submission is not an additional day late.

**To Reproduce**
1. Submit late to a homework assignment by one day
2. Open the homework page to resubmit
3. See error

**Configuration**
 - OS: Windows
 - Browser Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/38223007/55512787-fa0c3100-5631-11e9-8949-8ec22fd7aa3e.png)

**Additional context**

**Comment by bmcutler** [comment]
This has been an ongoing, frustrating-to-students problem.
We need to debug this once and for all, and create a serious set of test cases to ensure it stays fixed.
