### ISSUE TITLE
Code Mirror on discussion forum not displaying well with long code lines

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#3566]
**Describe the bug**
Scroll can appear with only a couple of lines.

**Expected behavior**
Code should not create a scroll bar with only a couple of lines.

**Comment by bmcutler** [comment]
Note:  We're moving to markdown for the forum posts, this should be revisited when the dust has settled...

**Comment by xprilion** [comment]
I checked into this, I do not see a scroll for the forum code at all now!

**Comment by bmcutler** [comment]
this issue referred to code mirror.
opening another issue related to markdown (long code lines run off screen)
