### ISSUE TITLE
Accessibility Navigation Menu like Google

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3573]
**What problem are you trying to solve with Submitty**
Present accessibility follows following path
1. Breadcrumbs
2. Sidebar
3. Main content

This makes transition to different focus-able element  difficult

**Describe the way you'd like to solve this problem**
Accessibility navigation menu like Google 
![ezgif com-video-to-gif(17)](https://user-images.githubusercontent.com/42701709/56198369-73efe180-6058-11e9-89d1-0473947171a5.gif)
We can use this to access parts of webpage like
1. Breadcrumbs
2. Sidebar
3. Main content
4. Direct link to Documentation

**Comment by drumilpatel2000** [comment]
@pbailie @bmcutler @MasterOdin  Can this feature be implemented in Submitty

**Comment by mktung** [comment]
Was this closed by #3949?

**Comment by bmcutler** [comment]
Yes, I think the skip navigation is this same idea.  Closing now.  We'll reopen a new issue if there are other specific shortcut designs for accessibility navigation to consider.
