### ISSUE TITLE
Too long threads displayed without clipping

### ISSUE THREAD

**Issue by xprilion** [Submitty/Submitty#3575]
**Describe the bug**
Long threads in the Discussion Forum are displayed as is, without any clipping of initial content and then an option to see remaining content.

https://www.loom.com/share/15602cea7fc64a91bd21cae031d45211

**Expected behavior**
A Read More button/link should be displayed after clipping the content upto a certain height.

**To Reproduce**
1. Go to Discussion Forum
2. Create New Thread and enter a very long text
3. See error

**Configuration**
 - OS: Linux
 - Browser: Chrome

**Comment by MasterOdin** [comment]
As stated by @bmcutler in #3576, this hasn't really been a problem that we've seen by the courses that use the forums in Submitty that this hasn't been an issue thus far, so closing this. If we start seeing requests for something like this from our users, then we'll reopen this issue and your PR.

Thanks for contributing to Submitty.
