### ISSUE TITLE
.submit_compile_output.txt should not have the group executable bit set

### ISSUE THREAD

**Issue by ZishanHuang** [Submitty/Submitty#358]
In the grading results, .submit_compile_output.txt should not have the group executable bit set.

root@vagrant-ubuntu-trusty-64:/var/local/hss/courses/f15/csci1100/results/pythontest/student/1# ls -la
total 44
drwxrws--- 2 hwcron csci1100_tas_www 4096 May 24 21:14 .
drwxrws--- 4 hwcron csci1100_tas_www 4096 May 24 21:14 ..
-rw-rw---- 1 hwcron csci1100_tas_www  492 May 24 21:14 .grade.timestamp
-rw-rw---- 1 hwcron csci1100_tas_www  785 May 24 21:14 submission.json
-rw-rwx--- 1 hwcron csci1100_tas_www  403 May 24 21:14 .submit_compile_output.txt
-rw-rw---- 1 hwcron csci1100_tas_www  482 May 24 21:14 .submit.grade
-rw-rw---- 1 hwcron csci1100_tas_www 1981 May 24 21:14 .submit_runner_output.txt
-rw-rw---- 1 hwcron csci1100_tas_www 2112 May 24 21:14 .submit_validator_output.txt
-rw-rw---- 1 hwcron csci1100_tas_www 1213 May 24 21:14 test01_0_diff.json
-rw-rw---- 1 hwcron csci1100_tas_www    4 May 24 21:14 test01_1_diff.json
-rw-rw---- 1 hwcron csci1100_tas_www    0 May 24 21:14 test01_execute_logfile.txt
-rw-r----- 1 hwcron csci1100_tas_www    0 May 24 21:14 test01_STDERR.txt
-rw-r----- 1 hwcron csci1100_tas_www  134 May 24 21:14 test01_STDOUT.txt

**Comment by bmcutler** [comment]
fixed with PR #397
