### ISSUE TITLE
Special characters in email announcements break stuff

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3581]
**Describe the bug**
I tried to put '¯\_(ツ)_/¯' in a discussion forum announcement w/ email.  The announcement posted to the forum, but the emails did not send.

Looking in the email logs we had this error:
Error Sending Email: 'ascii' codec can't encode character '\xaf' in position 873: ordinal not in range(128)

**Expected behavior**
Either escape/encode this character properly, or if that doesn't work for some reason, remove the character.
Make sure it handles all special characters, actually.

**Comment by MasterOdin** [comment]
Probably just need to do something like:
* replace this line:
https://github.com/Submitty/Submitty/blob/0d31f37dce5a511667e2e50929eb66b9ef02009a/sbin/send_email.py#L117
with (change of last parameter):
```
mail_client.sendmail(EMAIL_SENDER, email_data["send_to"], email.encode('utf8'))
```

* (maybe) add `Content-Type: text/html; charset=utf-8` to the top of the message at:
https://github.com/Submitty/Submitty/blob/0d31f37dce5a511667e2e50929eb66b9ef02009a/sbin/send_email.py#L101

**Comment by kasra-sheik** [comment]
PR Fix Created: https://github.com/Submitty/Submitty/pull/3586
