### ISSUE TITLE
Investigate using NPM to manage browser dependencies

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3591]
We currently have dependencies on the following third-party libraries for the browser UI:
1. fontawesome
2. jQuery
3. PDF.js
4. flatpickr
5. twig.js

It might be useful to investigate if we could utilize NPM within our toolchain when installing the site and that like composer, we install the dependencies, and then copy them under the appropriate place under `public/vendor/`. This would allow us to have a good set place for where we set versions of dependencies and have an automatic place to pull them from. Each of these packages have as part of them the available min files to keep the size of them down.

The pros here would be cleaner way to maintain our third-party dependencies, as well as upgrade them.

The con here would be that we'd be bringing in a new core dependency for Submitty to function (Node.JS and NPM) that's only used in the installation process.

@bmcutler let me know if you'd like to have a conversation about what this would look like.

**Comment by prestoncarman** [comment]
I think having a system like NPM and Composer to manage dependencies is a good idea. It could help simplify the set up process and code management. While these systems have had some problems in the past, overall they should be a net positive for the project.
