### ISSUE TITLE
Checkbox and radio labels should be clickable

### ISSUE THREAD

**Issue by jgfoster** [Submitty/Submitty#3592]
**What problem are you trying to solve with Submitty**
Clicking on the text next to a checkbox does not change the stated of the checkbox.

**Describe the way you'd like to solve this problem**
Clicking on the text next to a checkbox should change the state of the checkbox.

**Describe any potential alternatives you'd tried to solve the problem**
Require users to click on a small widget when they could click on a larger area.

**Additional context**
[Checkbox and radio labels should be clickable](https://stackoverflow.com/questions/2257606/making-checkbox-and-radio-labels-clickable)

**Comment by KaelanWillauer** [comment]
I'm working on the new gradeable (index.php?semester=s19&course=blank&component=admin&page=admin_gradeable&action=view_gradeable_page)

**Comment by NoahOlsen** [comment]
I'm working on the new gradeable, yes and no options.(index.php?semester=s19&course=sample&component=admin&page=admin_gradeable&action=view_gradeable_page)
