### ISSUE TITLE
Add timezone info to regrade_requests.timestamp

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3594]
**Describe the bug**
Currently, regrade_requests.timestamp relies on the DB's timezone being the same as the rest of the system so that it can assume that the proper time was put into the DB. If the DB uses some other timezone, all dates put into the DB will be off when displayed.

**Expected behavior**
A timezone is attached to any and all timestamps inserted into regrade_requests.

**Comment by xprilion** [comment]
@MasterOdin are we looking for an additional column in the `regrade_requests` table? Since altering the timestamp column would require making it text/varchar and that would be quite a tedious rework on the code.

**Comment by MasterOdin** [comment]
We're not looking to add a new column to `regrade_requests`, but rather just change the definition from `timestamp TIMESTAMP NOT NULL` to `timestamp TIMESTAMP WITH TIME ZONE NOT NULL`. 

The query itself would probably be something like:
```
ALTER TABLE regrade_requests ALTER COLUMN 'timestamp' TYPE TIMESTAMP WITH TIME ZONE
```

where you may need to append `USING 'timestamp' AT TIME ZONE '<TIMEZONE>'` to the query where `<TIMEZONE>` is the timezone that postgresql uses implicitly for columns. ((To get this, you could do something like `SELECT EXTRACT(TIMEZONE FROM now())/3600.0;` to get the offset and then translate that to a timezone string (e.g. if the offset is 0 -> UTC, if 1 -> CET, etc.))

**Comment by sak6lab** [comment]
Could we not just change how the database is created 

from \Submitty\migration\migrator\migrations\course\20180611120540_regrade_request.py

```database.execute("CREATE` TABLE regrade_requests (id serial NOT NULL PRIMARY KEY, gradeable_id VARCHAR(255) NOT NULL, timestamp TIMESTAMP NOT NULL, student_id VARCHAR(255) NOT NULL, status INTEGER DEFAULT 0 NOT NULL)")```

to

```database.execute("CREATE` TABLE regrade_requests (id serial NOT NULL PRIMARY KEY, gradeable_id VARCHAR(255) NOT NULL, timestamp TIMESTAMP WITH TIMEZONE NOT NULL, student_id VARCHAR(255) NOT NULL, status INTEGER DEFAULT 0 NOT NULL)")```

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add timezone info to regrade_requests.timestamp](https://trello.com/c/XfrL3j7D/2-add-timezone-info-to-regraderequeststimestamp)
