### ISSUE TITLE
Document footer_links.json

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3606]
**What problem are you trying to solve with Submitty**
Add documentation on how to use the footer_links.json configuration to submitty.org

Probably add it to this page 
https://submitty.org/sysadmin/system_customization

Include the specific example of how we use it at RPI (adding link to accessibility policy)

(related to PR #3590 and Issue #3332)

**Comment by pbailie** [comment]
I am adding the section on footer links to the end of the system customization page.  I am also updating and cleaning up some outdated information on this page.  And for reader's convenience, I created a table of contents at the top.

I had already created an example json file showing links that are not _exactly_ the same as RPI, but what is important is there (such as sample accessibility policy link).
