### ISSUE TITLE
Re-enable using the setcsvfields.py script

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3617]
From the discussion in Submitty/submitty.github.io#76.

Previously, we had used a [sbin/setcsvfields.py](https://github.com/Submitty/Submitty/blob/master/sbin/setcsvfields.py) script to allow a sysadmin to set what would be the fields of an incoming CSV file. From #1205, we dropped that functionality and that all uploaded CSVs/XLSXs need to be in the right prescribed format.

Do we want to bring back this script? Or just remove it completely?

The old documentation for the page can be seen [here](https://github.com/Submitty/submitty.github.io/blob/8805d67c4a269f74fdb86b4b6653d22f062b9b0c/_docs/sysadmin/system_customization.md)

@bmcutler, @pbailie, thoughts?

**Comment by pbailie** [comment]
`setcsvfields` was made largely obsolete (for us at RPI) by the student auto feed, but other schools may prefer to manually upload their classlists.

What I see as the underlining issue is that spreadsheet classlists provided to professors are not guaranteed to be in a standard form.  Even here at RPI — the dept. may get spreadsheet classlists from the registrar and again from the Dean's office.

While the two versions will have most of the same information, that information is not guaranteed to be in the same column order.  So even a system-wide mapping script may or may not work well at other schools.  On the other hand, it isn't difficult (although it might be viewed as inconvenient) for a professor using Excel to delete unneeded columns and reorder pertinent columns to match the spec dictated in the user list upload UI.

BTW — my open PR #3270 includes several bugfixes in parsing Excel spreadsheets.

**Comment by bmcutler** [comment]
Since we're not using it anymore, let's delete it.  

Yes, it is mildly annoying to shuffle columns in excel prior to uploading, but even non-tech instructors should be able to do that.  And its unlikely they will use any script they did not write themselves, esp if we aren't using (and therefore testing) it.  An instructor or school can write their own script(s) customized to their data source.
