### ISSUE TITLE
Graders should be able to move through students who have recieved a certain mark

### ISSUE THREAD

**Issue by benjaminrsherman** [Submitty/Submitty#3624]
**What problem are you trying to solve with Submitty**
When redefining a mark it's often necessary to move through students who have already received that mark to determine if the mark still applies.  This can take a long time if the mark had been applied sporadically.

**Describe the way you'd like to solve this problem**
Add the ability to move between students who have received points for a certain mark.

**Comment by bmcutler** [comment]
We've got a "who got what mark" button next to each mark.  Each username has a link to jump into grading the student.  Is that what you're looking for?

Or do you want to short cut the click from the list to navigate forward & backward through that list of who got the mark?  

(It sounds like this is a limited use feature need, so I hope we leave as is?)

**Comment by bmcutler** [comment]
closing as low priority / unclear UI design
