### ISSUE TITLE
Course materials/student photos upload max size should detect apache limit

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3626]
**Describe the bug**
I believe the default apache upload limit is 10M.  But we typically override that limit on our production machine to allow students to upload (somewhat) larger files if the instructor has specified a larger submission limit for an assignment.

However, the course materials upload is (I believe) hard-coded to limit to 10M, even if the apache limit is raised.  Let's make this feature check apache and give an error message only if we exceed the apache limit on the system.

This also might be the case for instructor upload of student photos.

**Comment by MasterOdin** [comment]
I'm not sure we've got apache limiting what we can upload, but rather it's more likely the php.ini value of [post_max_size](https://www.php.net/manual/en/ini.core.php#ini.post-max-size) or [upload_max_filesize](https://www.php.net/manual/en/ini.core.php#ini.upload-max-filesize) which are things we can detect using [ini_get](https://www.php.net/manual/en/function.ini-get.php).

**Comment by bmcutler** [comment]
see also:
https://submitty.org/sysadmin/system_customization#allowing-large-student-file-upload-submissions
