### ISSUE TITLE
Add requirements.txt for python packages

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3630]
Right now, we don't have an obvious place for what python packages are required for what component (as well as version). If we want to use automatic check of versions (#3611), we need to add these files somewhere that contain this information.

Python packages:
- [ ] migrator (add under `migration/`)
- [ ] autograder (add under `autograder/`)
- [ ] submitty_utils (add under `python_submitty_utils/`)
- [ ] submitty_scripts (add it somewhere logical under `.setup/`)

**Comment by wusatosi** [comment]
Dependencies in install_systems.sh with latest versions
```
python-pam==1.8.4
PyYAML==3.12
psycopg2-binary==2.8.6
sqlalchemy<1.4.0
pylint==2.8.1
psutil==5.8.0
python-dateutil==2.8.1
watchdog==2.0.3
xlsx2csv==0.7.8
pause==0.3
paramiko==2.7.2
tzlocal==2.1
PyPDF2==1.26.0
distro==1.5.0
distro-info===0.18ubuntu0.18.04.1
jsonschema==3.2.0
jsonref==0.2
docker==5.0.0
```

**Comment by MasterOdin** [comment]
I'm not sure where you're getting `distro-info` from?
