### ISSUE TITLE
Text overflow with when editing forum category.

### ISSUE THREAD

**Issue by shwehtom89** [Submitty/Submitty#3631]
**Describe the bug**
Text overflows if the category name is too long. 

**Expected behavior**
Text should either wrap, or page should alert user that the category name is too long.

**To Reproduce**
1. Go to Discussion Forum
2. Click on create thread
3. Click on Edit Categories
4. Click the edit icon and use insert a big string
5. See error

**Configuration**
 - OS: Linux
 - Browser Firefox/ Chrome

**Screenshots**
![overflow](https://user-images.githubusercontent.com/34754780/57098601-7f920800-6ce8-11e9-8ac0-5afa1a16b9d9.png)

**Comment by drumilpatel2000** [comment]
![ezgif com-video-to-gif(19)](https://user-images.githubusercontent.com/42701709/57123481-98a9c000-6d9f-11e9-86fa-506b738318d8.gif)
This issue should be extended to view of posts.
