### ISSUE TITLE
auto_grow(this) in TA grading Overall Comment

### ISSUE THREAD

**Issue by mattraneri** [Submitty/Submitty#3633]
**Describe the bug**
auto_grow(this) in the TA Grading view on the 'overall comment' tab does not behave well with scrolling and typing into the comment box

**Expected behavior**
It should not be scrolling on key up- because of the scrolling it makes typing nearly unusable.

**To Reproduce**
Type a long comment in to the Overall Comment box in the TA grading view, and observe the behavior when writing characters when the textbox expands

**Configuration**
 - Mac OS
 - Firefox

**Comment by drumilpatel2000** [comment]
See this for reference
![ezgif com-video-to-gif(18)](https://user-images.githubusercontent.com/42701709/57123311-f8539b80-6d9e-11e9-970d-886db62e7da3.gif)
