### ISSUE TITLE
Cases where grade inquiry is not displayed

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3637]
**Describe the bug**
Normally a grade inquiry will only be started for an assignment that has TA grading.

But...  a TA/instructor can open a grade inquiry for a student (and the assignment may not yet have TA grading or may have incomplete TA grading or may not yet even have been submitted!).

Or...  a student might open a grade inquiry and then the TA grading is reset for one or more components.

Or...  a student might open a grade inquiry and then cancel their submission.

In all of these cases...  the TA UI summary page will show that there is an unresolved grade inquiry, but the TA UI index/details page will not show which student has the unresolved grade inquiry.  

Also, if there is no submission, we don't show the grade inquiry conversation.  

**Desired Behavior**
... so let's please layer this information and make sure we can always find the grade inquiry.  incomplete grading + grade inquiry, cancelled submission + grade inquiry.

Also, let's prevent the ta/instructor from starting a grading inquiry on a student who hasn't submitted.  (But we will let them file a grade inquiry for incomplete or not started grading).

**Comment by sak6lab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cases where grade inquiry is not displayed](https://trello.com/c/cUKYNVtq/1-cases-where-grade-inquiry-is-not-displayed)
