### ISSUE TITLE
Cannot open second (or same again) PDF when grading

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3675]
**Describe the bug**
Attempting to open a second PDF (or the same one again) will cause an error to be shown in JS console about variable being redeclared. The requested PDF will not be loaded.

**Expected behavior**
The PDF to have loaded.

**To Reproduce**
1. Open a PDF
2. Go back to file viewer
3. Open the same PDF

**Configuration**
 - OS: Mac OS X
 - Browser: Chrome

**Comment by drumilpatel2000** [comment]
@MasterOdin. I checked this issue locally but I cannot reproduce the error. Can you please check if this issue is coming now?
