### ISSUE TITLE
GuestAdditions seems to be installed (6.0.6) correctly, but not running. - vbguest - add workaround in Submitty

### ISSUE THREAD

**Issue by Fenn-CS** [Submitty/Submitty#3676]
**Description**
The `vagrant-vbguest` plugin causes an error when running `vagrant up` on ubuntu 18.04 when some check is not available in the Vagrantfile.

```
[ubuntu-18.04] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
bash: line 4: setup: command not found
==> ubuntu-18.04: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
```

**Expected behavior**
`vagrant up` should run without errors.

**To Reproduce**
Steps to reproduce the behavior: Not sure if this Heisenbug kind of issue
1.  run vagrant up on ubuntu 18.04, `virtual box 6.0`, `vbguest 6.0.6` 

This is not a Submitty issue but a vagrant issue. however adding :

```
    if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
    end
```

to ones vagrant file, fixes the issue, should this not be in our vagrant file?

REF : https://github.com/dotless-de/vagrant-vbguest/issues/333

**Comment by MasterOdin** [comment]
So hopefully, https://github.com/dotless-de/vagrant-vbguest/pull/334#issuecomment-493135777 indicates that a new version of vbguest should be released soon with a fix for this issue. For now, I would suggest either downgrading your version of VirtualBox to a known working one (6.0.4 or lower) or you could put in the above lines, but it's not something we'd like to commit to master as it basically removes the point of this plugin, which is greatly desired given that the GuestAdditions that comes with bento/ubuntu-18.04 is almost certainly out of date (e.g. at the moment, it's for a version of VirtualBox that's at least 5 months old). If it ends up being the case that the plugin does not get an update soon, we'll re-evaluate.

Closing this for now.

**Comment by MasterOdin** [comment]
New version of vbguest has been released that should have a fix for this.
