### ISSUE TITLE
Avoid slow connection timeouts when worker is offline

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3684]
If a worker is offline, the INSTALL_SUBMITTY script and the restart_shippers_and_workers scripts seem to take a long time.  They wait for a timeout?

This is true even if the worker is in disabled mode in the autograding_workers.json file.

Let's do a faster check, and if the the worker is disabled, skip it altogether?

**Comment by MasterOdin** [comment]
I don't believe we've set a timeout for either autograding (https://github.com/Submitty/Submitty/blob/master/sbin/submitty_autograding_shipper.py#L131) or the update script (https://github.com/Submitty/Submitty/blob/master/sbin/shipper_utils/update_and_install_workers.py#L36).
