### ISSUE TITLE
Photo Scraper Tool Uses Wrong File Extension

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#3704]
**Describe the bug**
The [PhotoScraper](https://github.com/Submitty/InstructorTools/blob/master/PhotoScraper/RPI_SIS_PhotoScraper.py) always writes a .png file regardless of image content.

**Expected behavior**
The extension should be .png if the content is truly a PNG. SIS URLs do not specify the type (they are extensionless) but at present the content is actually JPEG content. The extension should thus be .jpg in these cases.

**To Reproduce**
1. Run the photoscraper script at RPI
2. Download from a course with at least one student still at RPI
3. Files are RCSID.png but contain JPEG content. (Adobe Photoshop uses a filter based on extension as opposed to image header content, and will fail to open these .png files but will open them fine if they are renamed to .jpg)

**Configuration**
 - OS: Any
 - Browser: Any

**Other Notes**
-A PR has been made in the InstructorTools repository to change the format, but this issue cannot be closed until the ImageView supports png/jpg/jpeg. 

~~Also have to figure out what to do if someone uploads multiple formats for the same file - should behavior be undefined or should an error be thrown? An error would have to be thrown when viewing the files since someone could just directly upload into `<semester>/<course>/uploads/student_images` so we can't rely on just the upload interface to catch things like RCSID.png and RCSID.jpeg for the same RCSID.~~

**Comment by MasterOdin** [comment]
Fixed in Submitty/InstructorTools#20

**Comment by holzbh** [comment]
The decision was made to just not care if multiple files with different extensions for one User ID are uploaded. Behavior should be pretty apparent and a confused instructor can always just delete the images in question and start over if need be.
