### ISSUE TITLE
Download single file or zip of entire submission directory or zip of all assigned students or zip of all students

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#371]
EDITED: Bumping the priority up on this feature request.
- [x] When viewing the rubric page for specific student, next to the "popout" on each file (within the file browser pane), add a "download" link, that allows the grader to save the file to their local machine.  This is necessary to view docx files, and possibly other proprietary formats.  [ highest priority ]
- [x] When viewing the rubric page for a specific student, add a button to download a zip of all of the files (submission & results & checkout) for that student.  Maybe all versions too?  This could be in the file browser pane.  Or in the student info pane.  [ low-medium priority ]
- [x] Allow a TA to download a zip of all of their assigned students for that gradeable [ medium priority ]
- [x] Same as above, but all students.  (maybe only instructor can do this?)  [ low priority ]

ORIGINAL:  We should allow for TAs a way to download student's code from the server as right now they have to go through ssh (which many don't and just bug the instructor/lead TA) to get the files. Generally, this is done to check previous student submissions (potentially for grading, so should be able to look at past submission attempts on the UI as well) as well as when a student's code doesn't work at all, it's sometimes useful to download the student's code to run locally while doing some small debug work to check how close the student was to the right answer but didn't submit working code.

**Comment by maksimt** [comment]
Hi,

This is a issue for us in FOCS as well. We don't use auto-grading, and if for some reason a student gets a extension or permission to only submit a digital copy, I have to retrieve the file by hand using SSH and email it to the relevant TA. The other TAs don't have SSH access.

**Comment by bmcutler** [comment]
Just edited the original message above.

**Comment by bmcutler** [comment]
closing related/duplicate issue #409
(be sure to read those notes too)
