### ISSUE TITLE
Organize 'your courses' list by semester better

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#3729]
**What problem are you trying to solve with Submitty**
The course list can get clunky with a lot of courses over multiple semesters, its a bit
hard to see which ones you're currently in versus past courses.
![a](https://user-images.githubusercontent.com/12129065/58289736-4861c480-7d85-11e9-8173-ad27e1464588.PNG)

Here's a potential way to organize it for students but im not sure to handle people who are TAs/Instructors/students at the same time
![b](https://user-images.githubusercontent.com/12129065/58289732-45ff6a80-7d85-11e9-8a08-ca3a8f811bc6.PNG)

**Comment by MasterOdin** [comment]
We might want to take this opportunity to redesign how the underlying model here works. What I mean by that is that our system focuses on things as "semesters", but there are schools that use trimesters or quarters, and that they may name them differently from us, and thus make it hard to order them via reverse lexicographical ordering (which is what we rely on).

I'd propose we add a new table to the `submitty` DB that holds these things and which would have a structure that has (at least) the following structure (with examples from above):

| id | name | start_date | end_date |
|---|-------|------------|------------|
| s19 | Spring 2019 | 01/10/2019 | 05/04/2019 |
| f18 | Fall 2018 | 08/30/2018 | 12/24/2018 |
| u19 | Summer 2019 | 05/20/2019 | 08/17/2019 |
| f19 | Fall 2019 | 08/29/2019 | 12/21/2018 |

Ordering of these can then be done easily through the `start_date` and then for any grouping on which the current date falls outside of the end_date can just be "minimized" as well to save space (with the expectation that students are really not going to be accessing old courses that much).

Other schools that are not RPI would then have an easy time of having their own ids and names for their sessions (whether they be semesters, trimesters, quarters, etc.).

**Comment by bmcutler** [comment]
This is related to #3653 & #1184 archiving courses and converting courses to read-only.   

The design is to put more control in the hands of the instructor, who might choose to allow you to see old course material, or who might remove your access shortly after the course finishes.  It will also be impacted by what period of time the system administrators allow you to have access to the machine.  (If you don't take an RPI CSCI course the next term, you may well lose all access to the server.)

We have been slow to archive the courses from Fall 2018 -- it will probably happen in the next couple weeks.  Spring 2019 courses will probably hang around a bit longer.  Archived courses are currently only visible to instructors, and they are nicely separated & labeled for instructors.  I do agree the students could be displayed better.
