### ISSUE TITLE
Router replacement to cater for the needs of API

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#3740]
**PROGRESS:**

- [x] AdminGradeableController
- [x] ConfigurationController
- [x] EmailRoomSeatingController
- [x] GradeableController
- [x] LateController
- [x] PlagiarismController
- [x] ReportController
- [x] UsersController
- [x] WrapperController
- [x] CourseMaterialsController
- [x] ForumController
- [x] ElectronicGraderController
- [x] ImagesController
- [x] SimpleGraderController
- [x] PDFController
- [x] LateDaysTableController
- [x] RainbowGradesController
- [x] SubmissionController
- [x] TeamController
- [x] AuthenticationController
- [x] HomePageController
- [x] MiscController
- [x] NavigationController
- [x] NotificationController

**What problem are you trying to solve with Submitty**
The router we are using is unable to handle complex requests that API needs. For example, a POST method with an endpoint of `/api/{semester_id}/{course_id}/assignments/{assignment_id}/build` cannot be simply parsed using our current router, which does not support regular expressions.

**Describe the way you'd like to solve this problem**
I plan to use https://github.com/klein/klein.php to replace the router we are using.

**Describe any potential alternatives you'd tried to solve the problem**
Alternatives include:
- Write a router myself. I do not think it is realistic. Although simple requests like `GET /api/users/?id=123` or `POST /api/users` can indeed be processed easily, it is not easy to handle complex requests. Worse, PUT and DELETE can be tricky.
- Use a framework for API such as Lumen. Discussed in #300 but decided not to because of the development resources.
- Use other routers like https://github.com/nikic/FastRoute. I compared several ones, and found Klein.php to be relatively more friendly.

**Comment by MasterOdin** [comment]
Some points:
1. If you're going to use an off the shelf router, we'd probably just go with Lumen or more preferably symfony (as Laravel does too much magic in my opinion) . Additionally, Klein does not look to be supported at all anymore.
1. "which does not support regular expressions" - while true, this isn't as big a concern as you make it to be. The current router would be done by just popping off arguments, done at the various levels of the controller (e.g. index.php pops off the argument for `$_REQUEST['controller']`, the controller then pops off the argument for `$_REQUEST['page']` and so on and so forth, cumbersome, but does allow for backwards compatibility with the current code/web addresses as we move off the current ugly URLs to something a router can do.

My longer view here was to implement a simple router, and then over time move all components of the web frontend to use it and the nicer URLs. Once that's done, make sure the response of all of
the components also confirm to whatever standard/response of Symfony, we can then look to more properly drop it in and use it for both the API and web front-end.

**Comment by MasterOdin** [comment]
Having said that, if it's not that much work to support both, I'd be fine with that as well.

**Comment by prestoncarman** [comment]
Is [Symfony](https://symfony.com/) used in other places in submitty?

**Comment by MasterOdin** [comment]
We use twig for templating. We could singularly bring in its router for this purpose (as opposed to the Klein router, or Lumen).

**Comment by zjxiaohan** [comment]
@MasterOdin Thanks for your suggestions. I will more carefully investigate our current router and try to modify it to serve this purpose before our weekly meeting.
