### ISSUE TITLE
Submission selection form for instructors not aligned properly

### ISSUE THREAD

**Issue by drumilpatel2000** [Submitty/Submitty#3756]
**Describe the bug**
Submission selection form is not aligned properly in firefox browser

**Expected behavior**
Submission selection form should be aligned in similar fashion for all browsers. In chrome browser it is aligned in center so it should be aligned in center for all browsers

**To Reproduce**
1. Open any gradeables for submission as instructor 
2. See error

**Configuration**
 - Browser [Firefox]

**Screenshots**
Submission Selection form in chrome browser
![Screenshot from 2019-05-30 00-08-20](https://user-images.githubusercontent.com/42701709/58583208-25498000-8271-11e9-93b3-c9cadec33d8b.png)
Submission Selection form in Firefox browser
![Screenshot from 2019-05-30 00-07-55](https://user-images.githubusercontent.com/42701709/58583209-25498000-8271-11e9-9a65-90c320b43284.png)

**Additional context**

**Comment by shailpatels** [comment]
This appears to be caused mainly be strange zoom levels in browsers, on firefox zoom at 90%, 110%, and 133% causes it to be offcenter.

Zooming in at 75%, 125% and 175% on chrome also appears to trigger this
