### ISSUE TITLE
time drift bug (sorry for vagueness)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#380]
Was observed once on the live server (we were 45 minutes in the future... caused big error at deadline)
I've observed it twice on the vagrant install as well (was 30 minutes in the past?  but it's confusing since the timezone on my host vs. vm don't match).

ntp does seem to be running...  (but I don't really know what I'm doing).
    sudo ntpdate pool.ntp.org 
maybe fixed it (?)

**Comment by gonsie** [comment]
These are the instructions @inlinefan shared when the time drift happened during the semester:

> If this should happen again, you can use
 `ntdate ntp.rpi.edu`
> to manually fix the time if ntp is not running, and then start ntp with
 `service nap start`

> When you restart ntp, it slowly brings things back into sync with small adjustments over time, so it's best to use ntpdate first if there is a known problem.
