### ISSUE TITLE
CSS variables for Submitty standard colors

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3812]
Let's establish CSS variables for all of the standard colors.

https://developer.mozilla.org/en-US/docs/Web/CSS/:root
(1 example at the top of our server.css)

Also...  please color merged threads the same color (grey) as deleted threads in the forum thread list.   Follow-on to issue #3628

**Comment by Kevin-MM** [comment]
Another example of usage is found here https://www.w3schools.com/css/css3_variables.asp

I think a good way to implement this would be:
- to have a stylesheet called colors.css which contains all these color declarations
- colors.css would be included at the top of all pages of submitty
- any stylesheet loaded after colors.css should now have access to the defined colors (I'm not 100% sure about this one but I'm pretty sure it works in this manner)
- colors.css will only contain 'variable' declarations with its associated color definition, no selectors or other styling data will be allowed here (to prevent it from becoming another server.css)
- all color data on all other stylesheets will be replaced to point to a predefined variable found in colors.css
- anyone working with stylesheets color MUST use a predefined variable from colors.css, picking your own random color will no longer be allowed
- if new colors are absolutely needed they may be added as a variable to colors.css, but the new color and usage must be approved by the submitty brass
