### ISSUE TITLE
Investigate max size for input/output and create second flag

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#383]
Right now, it looks like we've defined max size in a couple different places without any clear consensus what the units are (b? kb?). Someone needs to look into this and figure out what the specified units are.

Additionally, we should create two flags:
1) Max size of inputted files
2) Max size of outputted files

Instead of having them both be the same flag right now.

**Comment by bmcutler** [comment]
Just to clarify your terms:
1) Max sum of sizes of all submitted files (after unzipping)
2) Max size of any single file produced while running the student code (NOTE: this includes the .submit_runner_output.txt log file that is written while running the student code.)

**Comment by bmcutler** [comment]
They are both in bytes.  The defaults for both are defined in 
https://github.com/Submitty/Submitty/blob/master/grading/default_config.h

1) is MAX_SUBMISSION_SIZE
2) is RLIMIT_FSIZE_VALUE

The comment in: 
https://github.com/Submitty/Submitty/blob/master/public/controller/data_functions.php

 $max_size = 50; // this is in kb
    if (isset($assignment_config["max_submission_size"])) {
        $max_size = $assignment_config["max_submission_size"];
    }

Is wrong.  max_submission_size is always set (even if the instructor doesn't specify it, it is always defined, and the default is set above).

**Comment by MasterOdin** [comment]
There are then two checks against ```$max_size``` ([1](https://github.com/Submitty/Submitty/blob/master/public/controller/data_functions.php#L256) and [2](https://github.com/Submitty/Submitty/blob/master/public/controller/data_functions.php#L463)) where the other value is divided by 1024. We should remove that division in both places then to do a straight numerical comparison.

**Comment by ZishanHuang** [comment]
Will change that in my next commit.

**Comment by bmcutler** [comment]
fixed in PR #392
