### ISSUE TITLE
Tabbing on modal (popup) windows can cycles to elements on underlying page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3830]
**Describe the bug**
From the "Manage Graders" page, clicking on "Edit Grader" brings up a modal window to edit the fields of the user/grader.  Pressing tab cycles through the form correctly, but then focus jumps to elements on the background.

We just fixed this on the bulk uploads page in #3799 .  I notice its an issue on this modal window, so I assume it's a problem on most modal windows.  Eventually all will need to be fixed.

@shailpatels , any further comments/suggestions?

**Comment by shailpatels** [comment]
This was annoying to fix and was solved by manually taking control of what the tab key did. 
This issue exists for a lot of other people
https://github.com/valor-software/ngx-bootstrap/issues/1819
And I haven't found a good solution for it. Maybe for our case there can be a general JavaScript function that takes a list of elements and corrects the tab order whenever that modal is open.

**Comment by jchulton** [comment]
I've implemented a general Javascript function that takes in a modal id and prevents tab navigating out of that modal. This is done by grabbing the last and first tab-able elements from the modal and looping back to the first element when tabbing out of the last element. I've edited some of the simple modals created in server.js to use this function. Please check out my pull request #4901 4901. I haven't moved to more complex modals like Edit Grader yet, I wanted to get feedback first. Try Deleting and uploading Course Materials.
