### ISSUE TITLE
Cannot Clear Notifications 

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#3840]
**Describe the bug**
Pressing the checkmark icon next to a notification or "Mark all Seen" button does not actually 
clear notifications it only takes you back to the navigation page

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a notification (this can be done by replying to a post and logging on as that user
or making a grade inquiry and logging on as a grader
2. Go to notifications page
3. Try getting rid of notification(s)

 - OS: Linux (tested on development)
 - Browser Firefox

**Comment by zjxiaohan** [comment]
Sorry @sak6lab . Solved it before I saw your self-assignment. This bug comes from my negligence in https://github.com/Submitty/Submitty/commit/8951f05a6f96453067f436b67a528cf444080fc5.

**Comment by sak6lab** [comment]
Thats fine I just wanted to make sure it works cause im also working on discussion forum notifications
