### ISSUE TITLE
Student has different buttons than Instructors/TA for categories when posting a new thread

### ISSUE THREAD

**Issue by sak6lab** [Submitty/Submitty#3847]
**Describe the bug**
Students view of posting a thread
![student-category](https://user-images.githubusercontent.com/15002610/59459715-6f8f3d00-8deb-11e9-9523-30ee6881ca1c.JPG)
vs.
Instructors or users with grading access view of posting a thread
![teacher-category](https://user-images.githubusercontent.com/15002610/59459719-728a2d80-8deb-11e9-866c-a8155ba21f49.JPG)

**Expected behavior**
Both views should be the same.

I have traced this error back to this block of code in ForumThreadView.php

```
if($this->core->getUser()->accessGrading()){
            $categories = $this->core->getQueries()->getCategories();

            $dummy_category = array('color' => '#000000', 'category_desc' => 'dummy', 'category_id' => "dummy");
            array_unshift($categories, $dummy_category);
}
```

This `$category`  variable is sent to the createThread.twig file which then sends it to CategoriesForm.twig which creates a unordered list with a categories information.
Next the ThreadPostForm.twig  makes the checkbox buttons with a direct query

```
{% set categories = core.getQueries().getCategories() %}
    <div id="category-selection-container" style="margin-bottom:10px;display: inline-block;" class="form-group row">
        <label for="cat" id="cat_label">Categories</label> <br>
        {% if categories | length == 0 %}
            <span class='category-list-no-element' style="margin-left: 1em;" >
                No categories exists please create one.
            </span>
        {% endif %}
        <div id='categories-pick-list'>
        {% for category in core.getQueries().getCategories() %}
            <a class="btn cat-buttons" cat-color="{{ category.color }}" style="word-wrap: break-word; background-color: {{ category.color }}; color: white; max-width: 350px; text-align: left !important; white-space: unset !important;">{{ category.category_desc }}
                <input type="checkbox" name="cat[]" value="{{ category.category_id }}">
            </a>
        {% endfor %}
    </div>
```

Right after that it runs a script that calls refreshCategories which is in server.js. This function has a check where if the unordered list is not populated it will return, otherwise eventually in the function it will hide the checkbox and apply the correct click and event trigger to the button.

So, 

- Why do we need the check for access to grading to get the categories? 
- Do we need the extra query for the buttons themselves?
- Can we get rid of the default checkbox buttons and just put the button instead?

Note: This issue is related to issue #3839

**Comment by xprilion** [comment]
In my opinion, there isn't a need to check for access to grading for displaying the categories. I guess @andrewaikens87 can better answer these questions as it was part of the original logic before I converted it to Twig!
