### ISSUE TITLE
Setup http/2 on the server

### ISSUE THREAD

**Issue by mktung** [Submitty/Submitty#3850]
As we split up our files to be more modular, users will have to download more files for each page. The best way to optimize load times is to take advantage of http2's multiplexing and avoid bundling.

I'm pretty sure we just need to make a few changes to `submitty.conf` to setup http2. We should be sure to modify both `submitty.conf` and `submitty_http.conf` in the .setup directory to help new sysadmins install Submitty

**Comment by MasterOdin** [comment]
Relevant resources: https://symfony.com/doc/current/web_link.html
