### ISSUE TITLE
folder check on drag & drop is broken on mac chrome & firefox for cpp files

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#387]
cpp files are mis-identified as folders.  commented out the folder check in pull request #386.

**Comment by ZishanHuang** [comment]
Just discovered that if you name a folder to be something like "test.txt", the folder check will also not work.

**Comment by MasterOdin** [comment]
Would it be possible to make a very minimal example of dragging files and getting their types within something like [jsfiddle](http://jsfiddle.net) for a bit easier seeing this in action than through vagrant and that user interface?

**Comment by ZishanHuang** [comment]
Seems that the jsfiddle link has nothing in it?

**Comment by MasterOdin** [comment]
It was a request for you to make a minimal example of it on JSFiddle so I can look at it the code in action for a bit easier prototyping instead of going fully through the submitty vagrant box.

**Comment by ZishanHuang** [comment]
[Simple example](https://jsfiddle.net/hd30363y/3/)

**Comment by MasterOdin** [comment]
A test I made against the [latest fiddle](https://jsfiddle.net/hd30363y/6/) (you can correct me if it isn't) I made a folder called "test.txt" and dragged it into the zone and it was recognized as a file. Interestingly, we might additionally have an issue with it working at all in IE 11 based on comment on this [SO post](http://stackoverflow.com/a/8857445/4616655)

Chrome 52.0.2743.33
Windows 10

**Comment by ZishanHuang** [comment]
Forgot to change something. Here is the [new fiddle](https://jsfiddle.net/hd30363y/7/)

**Comment by ZishanHuang** [comment]
BTW just discovered that links can be dragged and dropped. So they could actually drag their desktop/download/document folder (which are actually links) and upload them. Though I would assume no one will try to do this and even if they did they will notice it right?

**Comment by ZishanHuang** [comment]
#388
