### ISSUE TITLE
Notifications Refactor

### ISSUE THREAD

**Issue by sak6lab** [Submitty/Submitty#3878]
**What problem are you trying to solve with Submitty**
Currently the Notification model and the data source DatabaseQueries has a lot of notification logic that reduces the amount of database queries we have to make but increases the amount of code we have to write and reduces abstraction which makes adding functionality to new notifications difficult as we have to write these special cases.

Notificaiton.php:
```
private function handleForum($details) {
        $this->setType($details['type']);
        switch ($details['type']) {
            case 'new_announcement':
                $this->actAsNewAnnouncementNotification($details['thread_id'], $details['thread_title']);
                break;
            case 'updated_announcement':
                $this->actAsUpdatedAnnouncementNotification($details['thread_id'], $details['thread_title']);
                break;
            case 'new_thread':
                $this->actAsNewForumThread($details['thread_id'], $details['thread_title']);
                break;
            case 'reply':
                $this->actAsForumReplyNotification($details['thread_id'], $details['post_id'], $details['post_content'], $details['reply_to'], $details['child_id'], $details['anonymous']);
                break;
            case 'merge_thread':
                $this->actAsForumMergeThreadNotification($details['parent_thread_id'],  $details['parent_thread_title'], $details['child_thread_title'], $details['child_root_post'], $details['child_thread_author']);
                break;
            case 'edited':
                $this->actAsForumEditedNotification($details['thread_id'], $details['post_id'], $details['post_content'], $details['reply_to']);
                break;
            case 'deleted':
                $this->actAsForumDeletedNotification($details['thread_id'],  $details['post_content'], $details['reply_to']);
                break;
            case 'undeleted':
                $this->actAsForumUndeletedNotification($details['thread_id'], $details['post_id'], $details['post_content'], $details['reply_to']);
                break;
            default:
                return;
        }
    }
```

**Describe the way you'd like to solve this problem**
I would like to refactor the notification system so that the logic is in a new classes where the logic is in two new classes: EventPublisher and EventObserver.
![submitty notificaitons design (2)](https://user-images.githubusercontent.com/15002610/59725039-262f5b00-91fa-11e9-980a-92409508704d.png)
The EventPublisher is the middleman which sends information about this new event to all observers. This allows us to scale our notifications easily. If we want to add a new kind of notification such as notifications for when a user joins a team we would add it to the respective observer. If we wanted to support say slack notifications we would just add a new observer.
https://codeburst.io/observer-pattern-object-oriented-php-4e669431bcb9

**Comment by MasterOdin** [comment]
I would advocate for using https://symfony.com/doc/current/components/event_dispatcher.html instead of trying to write your own.

**Comment by sak6lab** [comment]
Thanks @MasterOdin, symfony's event_dispatcher is definitely a solution to what I am trying to do. 

> However, it's not clear how much the set of listened events are going to be different from event to event (not much gained if all observers always listen to all events).

Yeah, the Event its not going be different at all. I plan to have a class Event that will have the type of notification: a string, the metadata: a link and the content: a generic string describing what happened. This Event will be sent to all of these listeners. The listeners will then decide who to send this event to with their respective preferences (notifications or email) and send it through that way. Is it not effective for all observers to listen to all events?

> Having said that, it's not really clear to me how this pattern is going to solve your stated problem.

After trying to stay away from that long if statement, I do not think we can get rid of it as different event types have a whole new set of recipients. However, I feel this will be consolidated in the event listeners.

>Are you going to split up each of these different cases into its own Event class? Are you going to make a factory method to generate an Event for a given notification type? Are you just going to make a ton of different methods in a singleton EventPublisher for all the different types?

I was going to create a generic Event class that has type, metadata, and content as members, however I will most likely use the Event class from symfony. So that will most likely be a factory method in core.

> How is the code in DatabaseQueries going to change, and is your solution going to increase the number of queries run?

I will change the DatabaseQueries pushNotifications to insert the Notification for a list of recipients and I will add one or more functions to query to select who should receive the event, ie. getAllUserWithPreference.
