### ISSUE TITLE
Discussion Forum Posts Don't Wrap

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#3894]
**Describe the bug**
If a forum post is too long, it does not automatically wrap. Instead the text is visually truncated. Zooming out enough or highlighting/select+all will still retrieve the text.

**Expected behavior**
Text should wrap based on screen width.

**To Reproduce**
1. Post a very long line of content on the forum
2. See error

**Configuration**
 - OS: Win 10
 - Browser: Firefox 67

**Screenshots**
![image](https://user-images.githubusercontent.com/26691043/59936480-16905c00-941e-11e9-87e5-8d312db16bc2.png)

**Comment by shailpatels** [comment]
Also effects chrome 75, tested on linux
