### ISSUE TITLE
C++ JSON should use library

### ISSUE THREAD

**Issue by seveibar** [Submitty/Submitty#39]
Unmaintainable methods for JSON generation within the C++ code, should be using a library.

**Comment by chameco** [comment]
Started work on this; currently using https://github.com/nlohmann/json. I have everything compiling and have converted a few cases to the library with no apparent issues, now it's just a matter of finding everywhere that JSON is generated.

**Comment by bmcutler** [comment]
I think most (all?) of these spots in the code have been replaced.  Will reopen if anything remains.

**Comment by MasterOdin** [comment]
This should remain open till we merge the json_library_testing branch and ensure all spots have been replaced. Right now, very little of the code has been changed to use a library

**Comment by bmcutler** [comment]
We are finished with this.
