### ISSUE TITLE
Remove emma from Submitty

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3904]
Currently, we install both emma and JaCoCo on Submitty. However, given that emma does not have support for the newer Java versions and features (as it was released when Java 6 came out), it's not really recommended that people should use this tool over JaCoCo.

My recommendation is to remove emma (installation and the grader methods), and delete Submitty/emma and just focus on JaCoCo support.

@bmcutler, thoughts?

Process for removal:
- [x] Remove from installation scripts (#4219)
- [x] Deprecate using emma in grading code
- [x] Remove emma from grading code
- [x] Delete emma repository mirror under Submitty/emma

**Comment by bmcutler** [comment]
closed by PR #6283
