### ISSUE TITLE
Tweaks to grade inquiry UI

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3921]
change first (white) 'submit grade inquiry' button to be 'open grade inquiry'
leave text on (blue) 'submit grade inquiry' button

when a student views a resolved grade inquiry, should have 3 options (approximate text):
(blue) reopen grade inquiry with response
(white) reopen grade inquiry with no response
(white) post message without reopening inquiry
--  maybe 2 of those options are disabled if the textbox is currently empty???  (forcing you to write a message)
-- other buttons should similarly be disabled if the textbox is empty (e.g., submitting the first post in a grade inquiry)

From the TA interface, for a resolved grade inquiry, change the "Submit Grade Inquiry" button to instead say "Reopen Grade Inquiry"

ALSO...  I left a bunch of "TODO"s in the student/grader/instructor documentation pages (I'll make & merge that PR very soon)

**Comment by sak6lab** [comment]
[Grade inquiry button breakdown](https://docs.google.com/document/d/11ULh8j1MLHl7DsKpEHlDCdzEwhZ8b6698uBKMQno310/edit)
