### ISSUE TITLE
Forum edit history doesn't render markdown

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#3928]
**Describe the bug**
When viewing edit history for a post on the discussion forum, markdown is not rendered. Most likely missing a `| markdown` somewhere.

**Expected behavior**
Markdown should be rendered here. 

**To Reproduce**
1. Go to forum
2. view edit history for a post that has markdown
3. See error

**Screenshots**
![exbad](https://user-images.githubusercontent.com/16356240/60159517-328e5780-97a8-11e9-82dd-774ffe3b523c.png)

**Additional context**
We recently changed to using markdown for forum posts. Should be a relatively easy fix.

**Comment by imskr** [comment]
Can i work on this issue ? If yes, please assign me.

**Comment by zjxiaohan** [comment]
> Can i work on this issue ? If yes, please assign me.

https://github.com/Submitty/Submitty/blob/master/CONTRIBUTING.md

**Comment by xprilion** [comment]
@andrewaikens87 @bmcutler This issue is due to History being fetched via Ajax as plain HTML from a JS function. Do we have a JS based Markdown rendering in Submitty?
