### ISSUE TITLE
Create API for Discussion Forum

### ISSUE THREAD

**Issue by xprilion** [Submitty/Submitty#3937]
Other parts of Submitty are being moved to API access. It will be good at this point to create an API for Forum and use that to load posts dynamically, allow custom UIs (if anyone wants to build anyday) or loading forum independently on any page without need to put it into code of that page.

**Comment by bmcutler** [comment]
API is a long term work in progress.  
Closing this issue for now, reopen issues with more specific tasks as appropriate.
