### ISSUE TITLE
double 'up' causes issues for change_grade_method_to_into.py

### ISSUE THREAD

**Issue by thef1stofhername** [Submitty/Submitty#3938]
**Describe the bug**
When I ran an update submitty, it uped the change_grade_method_to_int twice and then could not find the g_grader_assignment column

**Expected behavior**
the install should have booted as expected

**To Reproduce**
1. vagrant ssh in terminal
2. sudo /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh
3. /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh

**Configuration**
 - OS: Linux
 - Browser: FireFox

**Comment by bmcutler** [comment]
Just fixed in PR #3926 :)
