### ISSUE TITLE
add "semester=s16" url variable to the ta grading pages, rename databases

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#395]
Without the semester=s16, we can't view old data (even if the database is available and has a compatible schema)
Also, we discussed months ago re-ordering the pieces database name for better alphanumeric sorting.
right now we have:
hss_csci1100_f15
let's change that to:
submitty_f15_csci1100
discuss?

**Comment by MasterOdin** [comment]
I'm fine with renaming the database. The semester change for ta grading pages is already accomplished in the 1.0 branch.
