### ISSUE TITLE
TA grading UI Redesign:  next/prev student buttons when no assigned grading

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#3951]
A common confusion for instructors (and full access graders):

If you are not assigned any grading (whether by registration or rotating), 
and you select on a student from the index page (note: you may have had to click 'show all sections'), 

You are viewing a specific student, but the forward/next student buttons are grayed out.

Intuitively the user wants to browse through the students, but because they are not assigned to grade anyone it doesn't work and it is annoying and slow to have to return to the index page to click another student.

This also happens when you click to view a student in the null section, the buttons are always greyed out because you cannot be assigned to grade the nulls section.

** Needs UI Design Discussion **

**Comment by bmcutler** [comment]
We decided last week that we will add more buttons to the bar.

<<   <   HOME  >   >>

Use these font awesome symbols:

https://fontawesome.com/icons/backward?style=solid
https://fontawesome.com/icons/caret-left?style=solid

https://fontawesome.com/icons/caret-right?style=solid
https://fontawesome.com/icons/forward?style=solid


They are in order:
Previous Ungraded Student/Team
Previous Student/Team
Next Student/Team
Previous Ungraded Student/Team

These buttons will respect the choice of ordering (alpha by userid, alpha by last name, random, etc) and choice of "just my assigned students" vs "all sections" selected on the previous page (and tucked in the URL).

**Comment by Kevin-MM** [comment]
Checklist:
 - [ ] Add an additional set of arrows to the TA grading interface that allows the grader to move to the next ungraded item.  This is an important distinction from the initial set of arrows, which goes to the next submission (graded or not).
- [ ] Implement 'by component' functionality for the arrows.  For example, if a grader has a component open, and they click the 'next ungraded' arrow, they should get the next submission where that specific component is ungraded.
- [ ] Solidify the concept of 'view all' mode and 'view sections' mode.  The next arrows should respect which mode you are in.  The progress bar on the top of the TA grading interface should correctly indicate progress for each mode.

**Comment by bmcutler** [comment]
significant progress & reimplementation on the ta grading page.
closing this issue.  Will open new issues for future specific feature revisions.
