### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#3959]
Add API endpoint information to submitty.org, including the request methods (GET, POST etc), parameters and things to be returned.

**Comment by MasterOdin** [comment]
I think we should potentially consider having the API documentation to be contained elsewhere than the primary submitty.org which would give us more flexibility in how it's generated/what it looks like, as well as considering possible alternatives before going much further. Additionally, if using something like apidoc where the documentation is automatically generated, then we could setup an automated pipeline of push to master here, have a Travis/BuildBot job get kicked off to run apidoc, and then commit the changes to another repository.

Alternative to apidoc, I'm partial to how [Slate](https://github.com/lord/slate) outputs API's into a three-column design (See [Greenhouse](https://developers.greenhouse.io/harvest.html) for a good example), but of course all APIs are written in Markdown separate from the code itself, but I'm not sure if that's a true pro/con (comments just as easily drift apart as separate documentation). The upside to that is that generally it's a lot easier to write longer descriptions of the basics of how the API works, and descriptions of the APIs without being quite as constrained as apidoc with its annotation based format.

**Comment by zjxiaohan** [comment]
I agree with having it elsewhere. When I went around to see how others write API docs, I found that many services have separate API reference and other docs.

Slate looks great! I feel it is more flexible than `apidoc` and suits us better as `apidoc` requires something that we do not have (like error code. we use fail message instead).

**Comment by zjxiaohan** [comment]
close this as api.submitty.org is live
