### ISSUE TITLE
Provide Basic "Knobs" to Help Instructors Define Network Conditions for Networked Gradeables

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#3970]
- [ ] Update the Autograding Router to read in a ```network_properties.json``` file.
- [ ] By default, provide functionality so that the delay is supported.
- [ ] Provide a method by which instructors can easily extend this functionality to meet their needs.

**Comment by bmcutler** [comment]
The instructor is able to write scripts/functions customize much of this testing.
When/If we have specific requests for streamlining this process, we'll re-open new issues.
