### ISSUE TITLE
Inconsistent breadcrumbs

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#3995]
There are three types of breadcrumbs when you click a link in the sidebar.

### Type A
Breadcrumb + link
Discussion Forum: `http://192.168.56.111/index.php?semester=s19&course=sample&component=forum&page=view_thread`

### Type B
Breadcrumb without link
Manage Students: `http://192.168.56.111/index.php?semester=s19&course=sample&component=admin&page=users`

### Type C
No breadcrumb
Rainbow Grades: `http://192.168.56.111/index.php?semester=s19&course=sample&component=student&page=rainbow`

They should be of the same type.

**Comment by Kevin-MM** [comment]
I've added a breadcrumb to the Rainbow Grades page in a branch I am working on currently.

**Comment by mktung** [comment]
Partially fixed with #3893 and will be done when kevin pushes his branch

**Comment by mktung** [comment]
Should have been fixed with a number of separate PRs
