### ISSUE TITLE
Inconsistent usage of "students" and "users"

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4004]
When I am writing API things for course users, I find that graders are included in the students' list in the `Students Enrolled in Registration Section NULL` section. When clicking "Download Users", these graders will be included in the csv.

Is it an expected behaviour? Do we need to modify "students" to "users" or we want to remove graders from students' list?

**Comment by bmcutler** [comment]
graders and instructors are able to do all actions that students can do, including submission.  This is helpful for testing, and to learn/explain/demonstrate the interface to students.
Also, sometimes, a user is both a student in the course, and a grader of the course.
