### ISSUE TITLE
Remove hard-coded photo size limit

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4008]
The size limit per student photo or the zip file is hard-coded in the current controller.

https://github.com/Submitty/Submitty/blob/d43bb2643b3681b3095aa114aa707425f86a4bce/site/app/controllers/student/SubmissionController.php#L1686-L1689

We may want to put it into some configuration file.

Questions:
1. Will this config be different from course to course, or there should be a limit in a global config? (Are there courses that require super large student photos?)
2. Now that photos are uploaded manually by instructors, will that be meaningful to set up a limit especially considering PHP itself has a upper bound on the upload size?
3. @shailpatels will this problem still exist after #3724 is done?

**Comment by bmcutler** [comment]
duplicate/related to #3626  (and also #3724)

**Comment by bmcutler** [comment]
see also:
https://submitty.org/sysadmin/system_customization#allowing-large-student-file-upload-submissions
