### ISSUE TITLE
Forum: Markdown tweaks

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#4016]
**Describe the bug**
- In the thread preview (within the thread list), raw markdown is being displayed. We should filter this stuff out to make it plaintext. 
- When posting a code segment/inline image, the post can overflow when using markdown. We should scroll in the case of an overflowed post.

**Comment by xprilion** [comment]
@andrewaikens87 if a thread post contains only code in the first post, what are we looking to display?
