### ISSUE TITLE
Exceptions thrown during test_login_non_course_user e2e test

### ISSUE THREAD

**Issue by Kevin-MM** [Submitty/Submitty#4020]
**Describe the bug**
When running the TestLogin.test_login_non_course_user e2e test an exception is thrown which does not cause the test the fail.

**Expected behavior**
No exceptions should be thrown, further, the test should fail if an exception is thrown.

**To Reproduce**
1.  Run test_login.TestLogin.test_login_non_course_user 
2. Add
```self.wait_user_input()```
after
```self.driver.find_element_by_name("login").click()``` to pause test execution and see the exception data

**Configuration**
 - Server OS: Vagrant developer machine
 - Local OS: Ubuntu 18.04
 - Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Screenshots**
![failed_test](https://user-images.githubusercontent.com/7605020/60814046-e9a0b080-a162-11e9-97c8-ed260fd77cc8.png)

**Comment by MasterOdin** [comment]
PHP Notices and Warnings are different from Fatal Errors and Exceptions and while they will display, the PHP code is allowed to continue to run and finish (though something on the page is probably wrong). This then won't fail a E2E test unless they relate directly to what gets tested on a given page, which wasn't the case here (as we do not check the link itself, just that we hit this page).
