### ISSUE TITLE
TA toolbar has transparent background

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4060]
<img width="715" alt="Screen Shot 2019-07-11 at 11 07 30 PM" src="https://user-images.githubusercontent.com/5871417/61099566-c90d7a80-a430-11e9-863f-4b5c35bc8fa0.png">

**Comment by sak6lab** [comment]
The grading page's panels also seem to position themselves to the whole screen rather than their main div.
![grading_panels](https://user-images.githubusercontent.com/15002610/61131740-02250980-a488-11e9-8c68-b29007e81c23.PNG)

**Comment by Kevin-MM** [comment]
Also the settings for this system are larger than the height of the display.

![ta_settings](https://user-images.githubusercontent.com/7605020/61133364-51b90480-a48b-11e9-9aa4-b1616682d073.png)
