### ISSUE TITLE
Course Materials download zip buggy

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4063]
**Describe the bug**
Downloading the zip file of a directory as a student is buggy.  It produces a zero byte file.  

The download interaction is different than as an instructor.  As an instructor I'm asked to select a file name/directory.  As a student it just creates a file with default name in default location.

The zip file as an instructor includes files that are not yet released.

(I'm suspecting a bad merge with @zjxiaohan and @thef1stofhername recent work)

**Comment by zjxiaohan** [comment]
The zip downloading feature relies on the `checked` attribute to function.

I am confused reading the recent commit concerning course materials.

https://github.com/Submitty/Submitty/blob/9226ed1855077dcf8be314f69a0812d315c4dae3/site/app/controllers/course/CourseMaterialsController.php#L195-L201

It looks like that if `course_materias_file_data.json` exists, then `checked` is `null`. If not , it's `0`. It is weird as it will never be `1`.

@thef1stofhername may have a better knowledge of this. Could @thef1stofhername have a look?

**Comment by zjxiaohan** [comment]
And for

> The zip file as an instructor includes files that are not yet released.

That was an intended feature. When I was writing it, I was thinking that as instructors can see all, they should be able to download all too. Does @bmcutler think it should behave differently?

**Comment by thef1stofhername** [comment]
> @thef1stofhername may have a better knowledge of this. Could @thef1stofhername have a look?

Yeah this also confused me. I'm not sure I could rip out permissions without serious changes. I made it so that the permission should be automatically set to 1 as technically everything IS available just not until the time says so, however something could be overwriting it. Fixing now

**Comment by thef1stofhername** [comment]
fixed, please look for the PR soon

**Comment by Kevin-MM** [comment]
Also, the current behavior of objects inside the ```course_materias_file_data.json``` appears to be this:

- If a file is uploaded but the time stamp is never modified then it will not appear in the json
- If the timestamp is modified it will be correctly listed in the json
- If a file is deleted its contents should be correctly removed from the json (However I did see cases where metadata remained in the json even after the file had been deleted.  I am not sure how that happened)

**Comment by thef1stofhername** [comment]
I did fix that first part/second part with this afaik
however i did nothing with deletion (one of the few things I haven't touched in that file set) and I'm not quite sure how to proceed

**Comment by thef1stofhername** [comment]
okay so as far as i can tell, the delete function does not actually remove anything from the json. It's just hiding them

**Comment by Kevin-MM** [comment]
I believe it removes entries from the json here

https://github.com/Submitty/Submitty/blob/fa5f2522230291cb6929f180a711d6bd53626ec5/site/app/controllers/course/CourseMaterialsController.php#L45-L57

**Comment by thef1stofhername** [comment]
there is no call to it though from server.js or the delete form, so should i put in the ajax call for that?

**Comment by Kevin-MM** [comment]
I think here

https://github.com/Submitty/Submitty/blob/fa5f2522230291cb6929f180a711d6bd53626ec5/site/public/js/server.js#L328-L352
