### ISSUE TITLE
Course material release time is not time zone sensitive

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4065]
**Describe the bug**
When clicking "now" in the course material page, the time is set with regard to my time zone, which may be different from the time zone of the server.

**Expected behavior**
No matter where I am, when I, as an instructor, sets a course material to be release now, students should be able to see them immediately.

**To Reproduce**
1. Change the time zone of your computer while Submitty is running in NY.
2. Login as instructor, set one file to be released "now".
3. Login as student. Can't see the file.

**Configuration**
 - OS: Linux
 - Browser Chrome

**Screenshots**

Note 15:26:34 in China === 03:26:34 in NY, and after I set "now" in China, I can't see the course material released as a student.

Instructor Side:
![Screenshot from 2019-07-12 15-28-03](https://user-images.githubusercontent.com/20266703/61110612-331e3200-a4ba-11e9-9649-5dad4464e316.png)

Student Side:
![Screenshot from 2019-07-12 15-28-29](https://user-images.githubusercontent.com/20266703/61110616-344f5f00-a4ba-11e9-851a-ba2bff3ebdb8.png)

**Comment by Kevin-MM** [comment]
As part of this issue I am working on a few fixes

- [x] The now button should produce a timestamp in the server timezone, regardless of the user's timezone
- [ ] The background coloring of the date picker boxes should be based on server time, not client time
- [ ] Users in a timezone outside of the servers timezone should see a message indicating current server and client time when using the date time picker
