### ISSUE TITLE
Unable to upload duplicate course material files

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4069]
**Describe the bug**
I am unable to upload duplicate course material files.

**Expected behavior**
There should be a confirm window ("Do you want to replace the original file?") or simply a friendly reminder that you have to delete the file first.

**To Reproduce**
1. Upload one file
2. Upload exactly the same file again
3. See error (nothing happens. page doesn't refresh)

**Configuration**
 - OS: Linux
 - Browser chrome

**Additional context**

![Screenshot from 2019-07-13 00-20-16](https://user-images.githubusercontent.com/20266703/61143150-04c54480-a504-11e9-8f7f-4bace2a3f672.png)

**Comment by Kevin-MM** [comment]
I can confirm this I've seen this behavior also.
