### ISSUE TITLE
<br /> is not correctly displayed in gradeable message

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4086]
**Describe the bug**
![Screenshot from 2019-07-14 13-01-02](https://user-images.githubusercontent.com/20266703/61179565-76ea7600-a637-11e9-9de2-75f475ffd894.png)

**Expected behavior**
![Screenshot from 2019-07-14 13-02-08](https://user-images.githubusercontent.com/20266703/61179570-9f727000-a637-11e9-8f99-9693a74c3a57.png)

**To Reproduce**
1. Go to http://192.168.56.111/f19/development/student/cpp_simple_lab
2. See error

**Configuration**
 - OS: Linux
 - Browser: chrome

**Additional context**
https://github.com/Submitty/Submitty/blob/db8f7d4d91deac9180229253e510d5667db93b0c/site/app/templates/submission/homework/SubmitBox.twig#L4-L6

**Comment by MasterOdin** [comment]
In previous discussions with @bmcutler, we had decided to not allow any HTML in the markdown for the time being.
