### ISSUE TITLE
Change "Semester" to "Term"

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#4109]
**What problem are you trying to solve with Submitty**
Submitty uses the working for semester, but not all schools use semesters. Some other schedules include block or quarter. 

**Describe the way you'd like to solve this problem**
Submitty should pick a word to support these different schedule types instead of semester. Such as "Term".

**Describe any potential alternatives you'd tried to solve the problem**
Other words might be appropriate: "academic term".

**Additional context**
The naming for this "Term" should be open to what ever the user defines. Don't limit the user to only "A" and "U". They could use "f", "A", "Fall", or "AUTUMN".

**Comment by MasterOdin** [comment]
I agree with this, and made a similar comment on this in https://github.com/Submitty/Submitty/issues/3729#issuecomment-495411983:
> We might want to take this opportunity to redesign how the underlying model here works. What I mean by that is that our system focuses on things as "semesters", but there are schools that use trimesters or quarters, and that they may name them differently from us, and thus either have to use numerics for their semesters or use our set modified order of first letter of semester being of `/[a-eg-rtv-z]/` < s < u < f.
> 
> I'd propose we add a new table to the `submitty` DB that holds these things and which would have a structure that has (at least) the following structure (with examples from above):
> 
> | id | name | start_date | end_date |
> |---|-------|------------|------------|
> | s19 | Spring 2019 | 01/10/2019 | 05/04/2019 |
> | f18 | Fall 2018 | 08/30/2018 | 12/24/2018 |
> | u19 | Summer 2019 | 05/20/2019 | 08/17/2019 |
> | f19 | Fall 2019 | 08/29/2019 | 12/21/2018 |
>
> Ordering of these can then be done easily through the `start_date` and then for any grouping on which the current date falls outside of the end_date can just be "minimized" as well to save space (with the expectation that students are really not going to be accessing old courses that much).
> 
> Other schools that are not RPI would then have an easy time of having their own ids and names for their sessions (whether they be semesters, trimesters, quarters, etc.).

I agree in that calling this model/table/etc. `term` as well.
