### ISSUE TITLE
Plaintext vs Markdown for Forum Post

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4124]
**What problem are you trying to solve with Submitty**
We want to default to plaintext forum posts for simplicity, because we have students users who aren't familiar with markdown and will be confused if their use of basic math symbols turn into italics or bold and the symbols disappear.

**Describe the way you'd like to solve this problem**
When a user makes a new thread or new post in a thread there will be a checkbox at the top "Enable Markdown" that is initially false/unchecked.  

We store the state of the checkbox for the last new thread/post in a cookie (so it remembers whether this user knows how to use markdown).  It's a simple per browser/machine cookie -- not stored in the database per user.

We add a column to the database for every post storing the state of this checkbox at time of thread/post creation.  (The user can change the checkbox if they made an error by editing the post.  Editing a post does not use or change the state of the cookie.)

If the box is unchecked, the contents of the post will be rendered in plaintext.  All symbols will remain as originally typed.  Perhaps the only exception is that we will make a special case check for urls, they will turn into links.  (But just raw links, you cannot put different text for the link in plaintext mode.)

If the box is checked, then the entire post will be rendered as markdown (restricted markdown, no html tags allowed).  If the box is checked, then we have the shortcut buttons for code & url (& maybe some other options later) to help teach markdown syntax.

We have a link with the checkbox (in a ? bubble we use elsewhere on the site) to a tutorial on markdown.  Probably a simple tutorial with the most useful bits of markdown for the submitty forum that we write ourself on submitty.org.  But that tutorial will also link to other 'cheatsheet' pages with the full range of options allowed with our markdown package.

Note: Maybe later we add an option to preview the markdown rendering (similar to github).

Other comments @xprilion @andrewaikens87 @MasterOdin?

**Comment by MasterOdin** [comment]
I'm fine going this route and see how people feel about it. We may want to store their preference of using markdown (or not) in some way though so that someone who consistenly uses markdown does not have to keep hitting the checkbox on each and every post made.

**Comment by bmcutler** [comment]
Yup, I mentioned storing in a cookie :)
