### ISSUE TITLE
[Forum] Post redirect issue

### ISSUE THREAD

**Issue by andrewaikens87** [Submitty/Submitty#4127]
**Describe the bug**
When posts are published, we return a json response in order to send the next location of where the page should refresh. With the introduction of #4019, we have seen that after publishing, the json response is not *always* being consumed. This results in the user landing on a page with only a json object (which is confusing!). This functionality was introduced in GSOC last summer, and we should revisit this design and more importantly whether or not this functionality is required. I need to familiarize myself more with the plan of action for this issue, so I'm assigning myself and @xprilion to this for now.

**Comment by xprilion** [comment]
The implementation of the said feature is a bit off the convention. Please let me know if this needs discussion over call and I'll be available :)

**Comment by MasterOdin** [comment]
Should the forum post box still have an attached action given that the action leads to a page that will just post a JSON object and is expected that the page be called via ajax?

The line in question:
https://github.com/Submitty/Submitty/blob/8bc6c3a40ba8dee7d73a9c396e824f88bc32cf76/site/app/templates/forum/GeneratePostList.twig#L51

**Comment by xprilion** [comment]
I did notice that, has it got something to do with cases where JavaScript may be disabled?

**Comment by shailpatels** [comment]
Not sure if its related but after creating a reply this is what I got but I couldn't reproduce it
This might have something to do with introducing webresponse or jsononly response @zjxiaohan ? @xprilion  

![foo](https://user-images.githubusercontent.com/12129065/61435870-86074780-a907-11e9-8f4a-5914d50ee455.png)

**Comment by zjxiaohan** [comment]
No the forum hasn't been covered by the new router yet.
I cannot reproduce it either.

**Comment by xprilion** [comment]
Unable to replicate the issue on my local! @andrewaikens87 @shailpatels @MasterOdin  any suggestions how I can make this occur?

**Comment by MasterOdin** [comment]
What happens if the javascript that's supposed to block this form fails to fire (remove the stuff in the `onsubmit`)? My guess is that whatever configuration of the browser is probably messing up the javascript that's supposed to fire there and that it's falling back on the action, and landing in this unfortunate state.

**Comment by xprilion** [comment]
I'm able to identify and replicate the issue by introducing error in the JavaScript. Its essentially coming up when the JavaScript fails to fire/bind/load. Will push updates soon.
