### ISSUE TITLE
Multiple Forum Markdown issues

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#4135]
Apparently, the forum has markdown now?

This allows inline images, is that something we want?

Markdown doesn't render on the thread list on the left 
Lists are very buggy
They don't render for replies 
Markdown lists cut off to the left of each post
\* a
\* b
\* b
\* c
\* d

Results in 

![image](https://user-images.githubusercontent.com/12129065/61433060-4db03b00-a900-11e9-8ac5-c0b146872165.png)

\1. Item 
\2. Item  
--\* Mixed        <- pretend there are 2 spaces before * Mixed 
--\* Mixed   
\3. Item

Results in :

Should be : 
1. Item 
2. Item  
    * Mixed    
    * Mixed   
3. Item

\* a
\* b
\* c

\- a
\- b
\- c

results in : 
In addition to the cutting off, mixing the two types of list options causes weird spacing making
the bullets not line up with the line.
![image](https://user-images.githubusercontent.com/12129065/61431868-c0b7b280-a8fc-11e9-8f21-edcd9beee4e2.png)

Should be :

* a 
* b
* c

- a 
- b
- c

Code highlighting doesn't do much I prefered the old highlight, right now it looks like all it does 
it convert it to a monospace font?

"````
int foo(void)
{
return 0 ;
}
results in :

![image](https://user-images.githubusercontent.com/12129065/61433368-17bf8680-a901-11e9-8c51-16d6e49751ac.png)

selecting a language doesn't do anything either
````c
int main(void)
{
	return 0;
}
````
github's syntax highlight on c : 
![image](https://user-images.githubusercontent.com/12129065/61433509-7f75d180-a901-11e9-9d62-0705c471a17a.png)

Long code blocks don't wrap or scroll they just cut off 
![image](https://user-images.githubusercontent.com/12129065/61434098-08d9d380-a903-11e9-9a90-f8c5d4df54e4.png)

On github it adds a scroll whell
```c
char * longy = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

I don't know which flavor of markdown we're using but quotes and tables don't render
> a
> b
> c
> * a
> * b
> * c

I can't tell if anything is happening (or if its supposed to)

![image](https://user-images.githubusercontent.com/12129065/61433940-9e289800-a902-11e9-9599-66ccd47a7d74.png)

results in : 

![image](https://user-images.githubusercontent.com/12129065/61435649-fc577a00-a906-11e9-9977-8811e9c2c70c.png)

Github renders it like 

|A|B|C|
|-|-|-|
|A|B|C|

**Comment by MasterOdin** [comment]
Out of the box, Submitty does not have styling for plain lists, tables, etc. and they need to be provided, which would explain why things look so off in most of these cases. One of the things to discuss may be that given the places where this is used on the site, do we want a global markdown style or should markdown be styled on a case-by-case basis (e.g. markdown on the submission page looks different from the forums).

For the code box, if we want syntax highlighting, we'll need to hook up a code highlighter (can use a minimal codemirror instantiation without line counts and things).

**Comment by shailpatels** [comment]
Oh interesting I thought we were using a markdown package that handled all that.

I think we should get syntax highlighting, at one point the forum code blocks did have syntax highlighting along with line numbers too, I'm pretty sure we used codmirror for this.
