### ISSUE TITLE
URLs Audit

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4160]
As the router replacement work comes to a close, I am thinking about putting all URLs together and let's see if there are inconsistencies or better alternative paths.

Here is a list of all current routes (in master, until 2019-07-21, will keep updating):

```
  0 => string '/api/courses' (length=12)
  1 => string '/api/token' (length=10)
  2 => string '/api/{_semester}/{_course}/reports/summaries' (length=44)
  3 => string '/authentication/check_login' (length=27)
  4 => string '/authentication/login' (length=21)
  5 => string '/authentication/logout' (length=22)
  6 => string '/home' (length=5)
  7 => string '/home/change_password' (length=21)
  8 => string '/home/change_username' (length=21)
  9 => string '/{_semester}/{_course}' (length=22)
  10 => string '/{_semester}/{_course}/authentication/vcs_login' (length=47)
  11 => string '/{_semester}/{_course}/auto_rg_status' (length=37)
  12 => string '/{_semester}/{_course}/autograding_config' (length=41)
  13 => string '/{_semester}/{_course}/autograding_config/delete' (length=48)
  14 => string '/{_semester}/{_course}/autograding_config/rename' (length=48)
  15 => string '/{_semester}/{_course}/autograding_config/upload' (length=48)
  16 => string '/{_semester}/{_course}/autograding_config/usage' (length=47)
  17 => string '/{_semester}/{_course}/config' (length=29)
  18 => string '/{_semester}/{_course}/config/update' (length=36)
  19 => string '/{_semester}/{_course}/course_materials' (length=39)
  20 => string '/{_semester}/{_course}/course_materials/delete' (length=46)
  21 => string '/{_semester}/{_course}/course_materials/download_zip' (length=52)
  22 => string '/{_semester}/{_course}/course_materials/modify_permission' (length=57)
  23 => string '/{_semester}/{_course}/course_materials/modify_timestamp' (length=56)
  24 => string '/{_semester}/{_course}/course_materials/upload' (length=46)
  25 => string '/{_semester}/{_course}/email_room_seating' (length=41)
  26 => string '/{_semester}/{_course}/email_room_seating/send' (length=46)
  27 => string '/{_semester}/{_course}/extensions' (length=33)
  28 => string '/{_semester}/{_course}/extensions/update' (length=40)
  29 => string '/{_semester}/{_course}/extensions/{g_id}' (length=40)
  30 => string '/{_semester}/{_course}/gradeable/{gradeable_id}' (length=47)
  31 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/grade_inquiry/new' (length=65)
  32 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/grade_inquiry/post' (length=66)
  33 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/grade_inquiry/toggle_status' (length=75)
  34 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/grading' (length=55)
  35 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/grading' (length=55)
  36 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/grading/csv' (length=59)
  37 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/grading/pdf' (length=59)
  38 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/grading/print' (length=61)
  39 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/pdf' (length=51)
  40 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/pdf/annotations' (length=63)
  41 => string '/{_semester}/{_course}/gradeable/{gradeable_id}/{gradeable_version}' (length=67)
  42 => string '/{_semester}/{_course}/graders' (length=30)
  43 => string '/{_semester}/{_course}/graders/assign_registration_sections' (length=59)
  44 => string '/{_semester}/{_course}/grades' (length=29)
  45 => string '/{_semester}/{_course}/late_days' (length=32)
  46 => string '/{_semester}/{_course}/late_days/delete' (length=39)
  47 => string '/{_semester}/{_course}/late_days/update' (length=39)
  48 => string '/{_semester}/{_course}/late_table' (length=33)
  49 => string '/{_semester}/{_course}/no_access' (length=32)
  50 => string '/{_semester}/{_course}/notifications' (length=36)
  51 => string '/{_semester}/{_course}/notifications/seen' (length=41)
  52 => string '/{_semester}/{_course}/notifications/settings' (length=45)
  53 => string '/{_semester}/{_course}/notifications/settings' (length=45)
  54 => string '/{_semester}/{_course}/notifications/{nid}' (length=42)
  55 => string '/{_semester}/{_course}/notifications/{nid}/seen' (length=47)
  56 => string '/{_semester}/{_course}/rainbow_grades_customization' (length=51)
  57 => string '/{_semester}/{_course}/reports' (length=30)
  58 => string '/{_semester}/{_course}/reports/csv' (length=34)
  59 => string '/{_semester}/{_course}/reports/summaries' (length=40)
  60 => string '/{_semester}/{_course}/sections' (length=31)
  61 => string '/{_semester}/{_course}/sections/registration' (length=44)
  62 => string '/{_semester}/{_course}/sections/rotating' (length=40)
  63 => string '/{_semester}/{_course}/student_photos' (length=37)
  64 => string '/{_semester}/{_course}/student_photos/upload' (length=44)
  65 => string '/{_semester}/{_course}/theme' (length=28)
  66 => string '/{_semester}/{_course}/theme/delete' (length=35)
  67 => string '/{_semester}/{_course}/theme/upload' (length=35)
  68 => string '/{_semester}/{_course}/users' (length=28)
  69 => string '/{_semester}/{_course}/users' (length=28)
  70 => string '/{_semester}/{_course}/users/upload' (length=35)
  71 => string '/{_semester}/{_course}/users/{user_id}' (length=38)
  72 => string '/{_semester}/{_course}/{gradeable_id}/team' (length=42)
  73 => string '/{_semester}/{_course}/{gradeable_id}/team/invitation/accept' (length=60)
  74 => string '/{_semester}/{_course}/{gradeable_id}/team/invitation/cancel' (length=60)
  75 => string '/{_semester}/{_course}/{gradeable_id}/team/invitation/new' (length=57)
  76 => string '/{_semester}/{_course}/{gradeable_id}/team/leave' (length=48)
  77 => string '/{_semester}/{_course}/{gradeable_id}/team/new' (length=46)
  78 => string '/{_semester}/{_course}/{gradeable_id}/team/seek/new' (length=51)
  79 => string '/{_semester}/{_course}/{gradeable_id}/team/seek/stop' (length=52)
```

My two questions:

It looks more encouraged to have plural names in URLs (for API). Do we want `/gradeables/{gradeable_id}`?

Also I am editing AdminGradableController, and I find it hard to design a URL for `creating a new gradeable`. The first thing that came to my mind is `/gradeable/new`, but `new` can be recognized as an id. Although we could use regex to exclude that (by adding restrictions on gradeable_id), I don't really want to do that as it makes URLs more complicated. Ideas?

@prestoncarman @bmcutler

**Comment by prestoncarman** [comment]
Typically (at least for the API and I think it works here) we would used the POST method for the same URI for a specific resource minus the id. For a new gradeable, you would use POST /gradeable. The same GET URI will return all gradeables, but the POST version creates a new one. Remember that the HTTP method adds another layer of making URIs unique.

**Comment by prestoncarman** [comment]
Suggested changes: 

* /home/change_password to /current_user/change_password
* /home/change_username to /current_user/change_username

These URLs have the a special case when it comes to the {id}. Should we change other URLs so they do not conflict with the {id}?

* /{_semester}/{_course}/extensions/update
* /{_semester}/{_course}/extensions/{g_id}
* /{_semester}/{_course}/notifications/seen
* /{_semester}/{_course}/notifications/settings
* /{_semester}/{_course}/notifications/settings
* /{_semester}/{_course}/notifications/{nid}
* /{_semester}/{_course}/users/upload
* /{_semester}/{_course}/users/{user_id}

Similarly for:

* /{_semester}/{_course}/gradeable/{gradeable_id}/{gradeable_version} 

Suggestion:

* /{_semester}/{_course}/gradeable/{gradeable_id}/version/{gradeable_version}

**Comment by prestoncarman** [comment]
Plural is good. I would just be consistent in all your URIs.

**Comment by zjxiaohan** [comment]
> Typically (at least for the API and I think it works here) we would used the POST method for the same URI for a specific resource minus the id. For a new gradeable, you would use POST /gradeable. The same GET URI will return all gradeables, but the POST version creates a new one. Remember that the HTTP method adds another layer of making URIs unique.

Yes. For API we could do that, but for web interface there is another thing to consider: we need one page that has to be obtained by GET to initiate a POST request, like `https://github.com/Submitty/Submitty/issues/new`.

As you said, there are multiple places where there can be conflicts (notification id is fine, but gradeable id and user id conflicts should be avoided). For Github their issue # and PR # are numbers so it's fine, but in Submitty's case probably other designs should be considered to avoid conflicts.

Do you have some good URL design that may avoid conflicts here in mind? Honestly I hardly pay special attentions to URLs in my everyday life.

**Comment by zjxiaohan** [comment]
> Plural is good. I would just be consistent in all your URIs.

Yeah I am also for shifting from `gradeable` to `gradeables`. Let's do it after all is complete.

By the way, I am wondering if gradeable is a term that is only used at RPI?

**Comment by bmcutler** [comment]
No, it is not an RPI thing.
We chose gradeable as something not already used on any course's syllabus.
It is an umbrella term that includes tests, quizzes, assignments, homeworks, projects, labs, etc.

**Comment by MasterOdin** [comment]
Yeah, given that we strings for identifiers, it does make the routes a bit tricker to create. I think for the gradeable new form, it might be best to make it `admin/gradeable/new`. It's a bit inconsistent, but avoids the need for restricting allowed values of a gradeable id.
