### ISSUE TITLE
Ask "are you sure" when clicking away from edit modal to background

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4164]
If you click to edit a post on the discussion forum, make edits, but then click on the main page (e.g., to scroll and view other content as reference) the modal closes and you lose your edits.

Let's add a popup "are you sure", before discarding the modal & edits.

(not sure if I described that correctly)

**Comment by nitish81299** [comment]
@bmcutler 
I tried to reproduce the issue but In my case clicking away from modal window doesn't works until and unless user clicks on the cancel button inside the modal window to go back.
But if it's a bug we can work on that.

**Comment by hansongu123** [comment]
Currently, clicking away from the forum's "editing pop-up" or click "cancel" after any edit is made would not prompt the "You have unsaved changes! Do you want to continue?" modal unless you click on the edit icon again.

In other words, there is such a modal existing already, but buggy.
