### ISSUE TITLE
"Create Thread" should have some margin

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4169]
**Describe the bug**
![Screenshot from 2019-07-22 19-50-11](https://user-images.githubusercontent.com/20266703/61630290-f02e3c80-acb9-11e9-94ea-2927c28247a6.png)

**Expected behavior**
Personally I think there needs to be some space between "Create Thread" and the border of the form.

**To Reproduce**
1. http://192.168.56.111/index.php?semester=f19&course=sample&component=forum&page=create_thread
2. See error

**Configuration**
 - OS: Linux
 - Browser: chrome

**Additional context**
Could close this if it is intended. I am not that confident about my aesthetic judgment lol.

**Comment by bmcutler** [comment]
We're refactoring for VPAT and restyling for mobile.  
I'm going to close this because it is still perfectly functional 
and the style will be overhauled when we get to that page.
