### ISSUE TITLE
Migrate to more modern Java code coverage tools?

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#417]
From what I can tell, the last major release (ignoring bug fix releases) of Emma was in 2005 and it is not under any sort of development. There are now several newer code coverage tools that exist and are under current development. One possible example would be [JaCoCo](http://www.jacoco.org/jacoco/) which sort of bills itself as the successor of Emma.

**Comment by milana2** [comment]
I agree we should switch to JaCoCo --- also, Emma breaks with Java 8 features.

I used Emma back then because JaCoCo didn't have a ready-to-use command-line interface. I'll add a command-line report generator from the API (output should be as expected by the Emma graders).

**Comment by tcyrus** [comment]
See http://www.jacoco.org/jacoco/trunk/doc/cli.html

**Comment by tcyrus** [comment]
Since the version of JaCoCo with `jacococli.jar` is unreleased, I am going to try to use an AppVeyor build of JaCoCo. The next step is to test the code out with an example assignment.

**Comment by bmcutler** [comment]
closed with #1774
