### ISSUE TITLE
Generate CSV Report Fails

### ISSUE THREAD

**Issue by Kevin-MM** [Submitty/Submitty#4180]
**Describe the bug**
The Generate CSV Report button on the Grade Reports tab generates a Server Error.

**Expected behavior**
Pressing this button should allow you to download a spreadsheet of data.

**To Reproduce**
1. Log in as instructor
1. Go to the sample course
1. Click the ```Grade Reports``` tab on the navigation bar
1. Click the ```Generate CSV Report``` button
1. See error

**Configuration**
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Comment by zjxiaohan** [comment]
This line seems to be the cause?

https://github.com/Submitty/Submitty/commit/036bd71255dcde68a0cdd940ed099ea3eb1da386#diff-5a63f80435e405dfb3c3ef90d9fa1b2fR272

https://github.com/Submitty/Submitty/blob/036bd71255dcde68a0cdd940ed099ea3eb1da386/site/app/controllers/admin/ReportController.php#L272
