### ISSUE TITLE
Endpoint for invalidating API token

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4189]
@bmcutler requests there be:

1. [ ] A restriction on API access. For now don't enable students to get a token. Creative RPI students will be happy to play around with an easier tool to interact with Submitty database and we don't know what will happen (like API for getting all forum threads and some scripts to auto publish them somewhere public).

2. [x] One token at a time for one user.

3. [x] An endpoint for invalidating all existing API tokens, which is equivalent to changing `api_key` for the user.

`1` needs to be done after #4078 .

There is one question for `3`. I try to make it `DELETE /api/token`, but it looks like Symfony's request object only takes DELETE or PUT data from URL, which is in accordance with what HTTP/1.1 defines:

> The DELETE method requests that the origin server delete the resource **identified by the Request-URI**

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

So theoretically we should use DELETE with identifiers in URI, but obviously we don't want to put username and password in plaintext as part of query string.

As an alternative, do we want a not-so-RESTful thing like `POST /api/token/invalidate`? Or any other ideas? @prestoncarman

**Comment by MasterOdin** [comment]
You'll have to make it a `POST` request for now assuming we want to send both username/password in a payload. `DELETE` would make sense if we were passing along with token as part of the authorization header.
