### ISSUE TITLE
Test for @AccessControl

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4191]
Matt's comments make me think about adding tests for the `@AccessControl` decorator. We may want to use tests to ensure that some unintentional modifications do not expose methods that were previously protected.

That being said, I am not sure what the tests would look like. A unittest for `AccessControl.php` may be a bit trivial, but will listing all URLs with access control and testing them one by one be cumbersome?

---

Ah, now I get it. I misunderstood what was going on here and was thinking (wrongly) that we could check these permissions without using the router. I'm fine with these getting removed.

I do agree that we probably want to add some concept of integration tests (not full e2e) for these controllers that center around permissions which should be easier to do across the code-base with the Access + Router checking it instead of it being baked into the method.

_Originally posted by @MasterOdin in https://github.com/Submitty/Submitty/timeline_

**Comment by MasterOdin** [comment]
We can probably do a parameterized unit test inside a controller's test class that you pass in say the route and some details about the necessary access level and then the test sets up the router and request object, then runs the request to validate that we get the expected error.
