### ISSUE TITLE
Better Code Boxes for Forum

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#4208]
Looking at https://github.com/Submitty/Submitty/pull/4186 which was merged recently, I'd like to make a request to not wrap lines of code, but rather add a horizontal scroll bar. This is how I've seen most implementations for code viewers, and it's especially useful given the lack of line numbers. I think this is especially necessary for languages where whitespace is significant.

It may be that there was already a design discussion offline about this, and if so, I'd like to see a high level summary (as the original issue calls for scrolling) and then feel free to close this issue.

The wishlist:

* grey background for the block of code
* language specific syntax highlighting (perhaps a default per course, but allow author to specify/override)
* line numbers
* [probably] use horizontal scrolling for extra wide lines (don't wrap)

**Comment by xprilion** [comment]
@bmcutler @andrewaikens87 @MasterOdin I guess line numbers would be a good idea...the horizontal scroll would probably just add to the already 2-3 scrolls on the page...making it uglier :o

**Comment by bmcutler** [comment]
Let's just pause on the current state and get feedback from users.  (A prior state was terrible --code just ran off the right edge with no way to read it.)

We decided on a compromise (for now) for the forum.  Wrapping code is undesirable in many ways, but scrollbars are tricky to place (especially in a forum thread, do we horizontal scroll just the code block or the whole thread?) and can be unintuitive & frustrating.

Eventually we want to get code mirror with language specific syntax highlighting & line numbers.  We can revisit display of long code then.  But we have other priorities for the forum first.

**Comment by MasterOdin** [comment]
Most places I've seen have a scroll bar within just the codeblock itself while leaving the width of the overall post alone.

GitHub for example:
```
This is a very long line of code that stretches off the right hand side of the screen and that only has a scroll bar for this content and doesn't stretch the content of the page width or anything.
```

**Comment by bmcutler** [comment]
Sure, and github also puts the codeblock in a grey box, which is helpful.  

Our current markdown engine styling doesn't do that out of the box (either the scrolling or the grey box).   

I note that the styling of markdown for submitty.org does put code in grey boxes, but wraps long lines in the codeboxes (and without line numbers).  This can be misleading for command documentation.
