### ISSUE TITLE
Bootstrap is failing during configuration

### ISSUE THREAD

**Issue by xelfer** [Submitty/Submitty#4210]
**Describe the bug**
Running the bootstrap fails during the configuration step. 

I'm not prompted for any of these configuration options, it just fails. 

```
Welcome to the Submitty Homework Submission Server Configuration

Hit enter to use default in []

What is the database host?: [localhost] Traceback (most recent call last):
  File "/usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/CONFIGURE_SUBMITTY.py", line 205, in <module>
    DATABASE_HOST = get_input('What is the database host?', defaults['database_host'])
  File "/usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/CONFIGURE_SUBMITTY.py", line 34, in get_input
    user = input("{}: {}".format(question, add)).strip()
EOFError: EOF when reading a line
err_message

```

Manually running python3 CONFIGURE_SUBMITTY.py prompts me, but the bootstrap script or whatever script it is calling is failing. 

**To Reproduce**
1. Run `curl https://raw.githubusercontent.com/Submitty/Submitty/master/.setup/bootstrap.sh | bash` as root
2. See error

**Configuration**
 - OS: Ubuntu 18.04.2

Any help appreciated, I tried searching but couldn't find a matching issue.

**Comment by MasterOdin** [comment]
Sorry about that, this is a typo in the documentation. The command should actually be:
```
bash -c "$(curl -s https://raw.githubusercontent.com/Submitty/Submitty/master/.setup/bootstrap.sh)"
```

The former doesn't work as it assumes stdin being from the piped in first command, which it does not provide, which is why python is throwing that `EOF` error. The proper command here does not have that issue.

**Comment by xelfer** [comment]
Thank you, that seems to have done the trick. Appreciate the prompt response!
