### ISSUE TITLE
undefined table 7 error

### ISSUE THREAD

**Issue by xelfer** [Submitty/Submitty#4224]
**Describe the bug**
Fresh install, I can't login with the user I created during setup. Firstly I had a database auth error:

`SQLSTATE[08006] [7] fe_sendauth: no password supplied`

I fixed this by re-running setup and actually assigning a postgres password.. but then I got a password incorrect error. Is there a default postgres username/password I should be using? I fixed this by manually logging in to postgres and assigned one to submitty_dbuser, I'm unsure if this caused the error. 

**Expected behavior**
I should be able to login.

**To Reproduce**
1. Login to web interface
2. See error.

```
Message:
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "users" does not exist
LINE 1: SELECT * FROM users WHERE user_id=$1
                      ^

Stack Trace:
#0 /usr/local/submitty/site/app/controllers/AuthenticationController.php(127): app\libraries\Core->authenticate()
#1 unknown file(unknown line): app\controllers\AuthenticationController->checkLogin()
#2 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(157): call_user_func_array()
#3 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(138): app\libraries\routers\WebRouter->run()
#4 /usr/local/submitty/site/public/index.php(339): app\libraries\routers\WebRouter::getWebResponse()
```

**Configuration**
 - OS: Ubuntu 18.04.2
 - Browser: Chrome

Thanks!

**Comment by bmcutler** [comment]
Do you mean submitty_dbuser?  We recommend sticking with that name.  Likely in one or more places in the system we have that named hardcoded instead of reading from a variable.  Not something we can prioritize tracking down now.

**Comment by MasterOdin** [comment]
What is the list of tables of the Submitty database?

As root, what is the result of running 
```
python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/migration/run_migrator.py -e system status
```

**Comment by xelfer** [comment]
> Do you mean submitty_dbuser?

Yes, sorry for the typo

> As root, what is the result of running

```
# python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/migration/run_migrator.py -e system status
Could not find migration table for system
```

**Comment by xelfer** [comment]
`postgres@submitty:~$ psql -d submitty
psql (10.9 (Ubuntu 10.9-0ubuntu0.18.04.1))
Type "help" for help.

submitty=# \dt
Did not find any relations.`

actually looks like I don't have any tables defined at all

**Comment by bmcutler** [comment]
I'm going to close this issue and request we move this installation debugging conversation to the Submitty slack server.  

https://submitty.org/developer#online-community-discussion-and-contact-submitty-administration-team
