### ISSUE TITLE
Late Days Allowed form requires a format different than the datepicker

### ISSUE THREAD

**Issue by mktung** [Submitty/Submitty#4246]
**Describe the bug**
On the Late Days Allowed page (found on the sidebar), there is a form that grants extra late days. The Datestamp field label asks for MM/DD/YYYY, yet the datepicker selects a date with the format YYYY-MM-DD. Further, if you try to Submit with the datepicker formatting, it returns the error "Datestamp must be mm/dd/yy." (Note: it also handles MM/DD/YYYY, but this should be irrelevant).

**Expected behavior**
We should reformat the way the form is hanlded so that YYYY-MM-DD is used instead of mm/dd/yy. We should also update the error message so that it specifies YYYY-MM-DD as the required format.

This may affect the CSV bulk upload, so make sure to test that.

**Comment by bmcutler** [comment]
closed by #4248
