### ISSUE TITLE
PDF Annotation Improvements

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4247]
Feedback from instructor tester:

1. Maybe this feature already exists and I didn't see it, but it would be good
to have an easy way to make the homework being graded become full-screen, make
the grading edits on it, and then have it return to being a small window
again.

2. The pen tool was actually pretty good and responsive using the Wacom tablet
(certainly miles better than Acrobat). Is there a way to make the size of the
pen even smaller (I saw that it could be decreased from 1 to 3, but even
smaller)? The goal is to be able to write notes next to the student typed
work, where the letters being written are the same size as the typed text.
Even after zooming in on the student work to 300 percent, the pen is still not
responsive enough to write such small and precise letters, but possibly making
the size of the pen smaller would help?

3. The eraser definitely needs some improvement. Right now I had to
essentially click separately on each mark I wanted to erase, instead of being
able to just move the eraser smoothly over the marks that were made with
everything that it touches disappearing..

**Comment by MasterOdin** [comment]
Split these three tasks into three individual issues to better track the work necessary for them (especially with the third point which may take some time to implement compared to the others).
