### ISSUE TITLE
Split sbin/adduser.py into two files

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#4301]
The current [sbin/adduser.py](https://github.com/Submitty/Submitty/blob/a030f583116a6f739630512d401dd7e501971ad2/sbin/adduser.py) is used both for creating new users in the Submitty database as well as for adding users to a course. However, when you're just looking to add a user to a course, this is a clunky interface as the system asks you all the questions about user details (name, email, password) which is generally just hitting enter through.

We should split the file into two separate pieces:
1. sbin/adduser.py (just creates a user)
1. sbin/adduser_course.py (just adds a user to a course)

The first one should have the usage of `sbin/adduser.py <user_id>` and the second should have usage of `sbin/adduser_course.py <user_id> <semester> <course>`.

The relevant parts for adding to a course is https://github.com/Submitty/Submitty/blob/a030f583116a6f739630512d401dd7e501971ad2/sbin/adduser.py#L115-L141

Once done, need to modify https://github.com/Submitty/Submitty/blob/e5485b9cae3546b906fd8872f568b1085092c01c/sbin/submitty_daemon_jobs/submitty_jobs/jobs.py#L330
to take advantage of the new script (fixing a bug where that currently won't work if using DatabaseAuthentication). Will also need to update https://submitty.org/sysadmin/course_creation as appropriate and update https://github.com/Submitty/Submitty/blob/7dc7c26f3a2108cac86b876aa710fcfa4f09b59f/.setup/submitty_sudoers.

**Comment by bmcutler** [comment]
Did you swap the names of the proposed new/revised scripts?

**Comment by MasterOdin** [comment]
Yeah, my first pass had adduser and createuser, realized that was confusing and not good, and changed the names to above but forgot to update it in a couple places, thanks for pointing that out.
