### ISSUE TITLE
Improve time handling (finer precision, include timezone in timestamps)

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#431]
Two issues:
1) Right now we rely on the server and the code to be using the same timezone, else you run the risk of times being different than you would expect (and there's potential for a homework being considered late, but it's not, etc.)
2) All time stamps are only to the seconds place. This means that the number we output for length in the grading queue could be "0 seconds" (or some other rounded down number) which is not ideal for the purposes of statistic collection on how long processes are running at some given time.

**Comment by bmcutler** [comment]
timezones have been added.
if finer precision of grading processes needed, that should inside of the custom grading routines.  second precision should be sufficient.
