### ISSUE TITLE
Help Icons are now missing on many pages

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4319]
**Describe the bug**
Not sure when they disappeared, they are still in the code, but most helpicons on the instructor UI for createing a gradeable have disappeared.  I think it may have happened with PR #4238 

The helpicon stuff is currently in input.css and server.css -- why both??
git grep for "fa-question-circle" and also helpicon.  

Also tagging @jmcknight98 to help point out where these used to be on the instructor UI for create/edit gradeable.

**Comment by MasterOdin** [comment]
Fixed in #4326
