### ISSUE TITLE
Student view & TA grading view of plaintext file when filename has space

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4344]
**Describe the bug**
Perhaps specifically if the last character is a space?
E.g., "collaboration.txt "

Throws a confusing message "You do not have access to this file" (even as instructor user)

**Comment by zhangted** [comment]
when uploading, get filename and filename length. start at last index of filename -> while index == space, delete and -1 on the index

**Comment by VictoriaSavage526** [comment]
I am not able to replicate this issue: has it already been solved? I have used the following file to test out, and it seems to have been remedied. Am I not doing the correct steps?
[bad test.txt](https://github.com/Submitty/Submitty/files/3731387/bad.test.txt)
In addition, I seem to not be able to adding trailing space to a file name, automatically the filename is stripped on my machine upon saving.
What should I be doing differently?

**Comment by prakharg47** [comment]
@VictoriaSavage526 are you using Windows ? Perhaps, that is the reason your trailing space is automatically stripped.
On *nix you can create a file with trailing space

**Comment by shailpatels** [comment]
Related to #1596 possibly
