### ISSUE TITLE
Documentation for API development

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4347]
Write documentation on how to build API endpoints. The content should include:

- How we do authentication (what is API key & token)
- What is `Response` and how it is useful
- what else?

**Comment by MasterOdin** [comment]
I think https://api.submitty.org and https://submitty.org/developer/router cover writing the API stuff fairly well. We can address writing more pointed documentation as it becomes clear what sort of documentation people might want.
