### ISSUE TITLE
Redirect to a simple static 'System Upgrading' page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4350]
**What problem are you trying to solve with Submitty**
When we run INSTALL_SUBMITTY.sh there is generally a 1-2 minute period when some resources related to npm are unavailable (directory permissions?) and most webpages show confusing errors to the users.  If they are patient and hit reload in a minute or two, everything is fine.  During this time lengthy, jumbled messages get logged to site_errors (and drown out any  messages for errors we do need to fix)

**Describe the way you'd like to solve this problem**
During the period when we are updating pieces of submitty that will break the site, can we instead redirect all pages to a simple static page saying something like "Submitty is being updated. Please try again in 2 minutes."  And if we log anything at all, we could just have a 1 liner log that someone tried to load this specific page and we served them the updating page instead??

**Comment by MasterOdin** [comment]
I think the best way to do things is modify the following line to have `index.html` be first:
https://github.com/Submitty/Submitty/blob/72f7b74551794db55883e86211a0d0f5b63de950/.setup/apache/submitty.conf#L22

and then for the first step of `INSTALL_SUBMITTY_HELPER_SITE.sh` to be copy in a `index.html` to `/usr/local/submitty/site/public` which will have the default git permissions of 644 (so it should be served just fine by apache, though we could copy the file to `/tmp` first, set whatever permissions we want, and the move it into place in `site/public`). Then, after the script concludes, we delete the `index.html` file and users should then start being serviced by `index.php` again. We would do no logging (as it's just an html file) and that's probably fine.
