### ISSUE TITLE
Automatic deployment of API doc

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4361]
Use Travis or other continuous integration tools to automatically update api.submitty.org

I know Matt needs to test the deployment process several times before setting it up. Just file an issue here to avoid forgetting.

**Comment by Fenn-CS** [comment]
Would like to see the workflow associated with this! Can pick it up.

**Comment by MasterOdin** [comment]
So the gist of it is largely modifying the `deploy.sh` script to push to `https://$GITHUB_TOKEN@github.com/Submitty/api.submitty.org.git`. Unfortunately, this can lead to leaking Git credentials if a fatal error is hit during the push for whatever reason. Need to look into  the approach taken [here](https://github.com/X1011/git-directory-deploy/issues/7) and see how we can filter out the key from leaking.

**Comment by MasterOdin** [comment]
Turns out this was simpler than I thought.

Done in Submitty/api.submitty.org@873c312aea5a634f30f1bcedb994a40050bf9ef5.

**Comment by zjxiaohan** [comment]
thanks @MasterOdin !
