### ISSUE TITLE
Allow testcase_ref on a Notebook markdown cell

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4386]
If I have 2 test cases associated with a single input box (e.g. a compilation test case and an execution test case) I'd like to have the messages for both of those test cases appear somewhere.  Currently we can only associate one testcase label per notebook cell.  (I think that's ok.)

But I can only seem to put the testcase_ref on the input types.  This doesn't work:  (The messages don't display)

```
      {
            "type" : "markdown",
            "markdown_string" : " ",
            "testcase_ref" : "Q06_compilation"
        },
```

Also, I can't seem to have an empty markdown string.  I have to have at least one space in there.

**Comment by Kevin-MM** [comment]
We are currently unable to use 'testcase_ref' on a markdown type when the markdown type precedes an input type.  VPAT compatibility requires that HTML field sets have a label.  What is happening here is that the markdown cell is merging with the input cell, creating a single fieldset that contains all the information needed for VPAT compliance.  We could certainly forward the 'testcase_ref' to the input cell, but if the input cell already had a 'testcase_ref' then it remains unclear which 'testcase_ref' gets to stay and which must be removed.

These changes were made in [this commit and PR (see AutogradingConfig.php)](https://github.com/Submitty/Submitty/commit/8820cd16d274445945c2a90f2a55b2e8eb14ff6b#diff-eff634dd1719cc5658b838c723779d70).

Other changes addressed in a future PR.
