### ISSUE TITLE
(Option to?) Disable capitalization & spellcheck for Notebook textboxes

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4392]
**What problem are you trying to solve with Submitty**
A student is typing code in a Submitty notebook.
The browser autocapitalizes some of their typing...

"for (int i = 0; ..."  => . "for (int I = 0; ..."

Or spell corrects:

"std::cout << x << std::endl;"  => "std::count << x << std::end;"

The user can disable these in their browser preferences (but that would affect all webpages).

**Describe the way you'd like to solve this problem**
Let's consider disabling this for our pages (when appropriate -- e.g., when it's a code short answer box)
e.g.,

https://www.wufoo.com/html5/spellcheck-attribute/
https://stackoverflow.com/questions/11102729/how-to-prevent-auto-capitalization-in-ios-safari-input-tags

**Comment by MasterOdin** [comment]
Looking at #4694, and reading this, it sounds like instructors are specifying a short answer box without setting the `programming_language` value and then wanting to use that box for code. Is that an accurate reading of it?

If so, would you be able to comment as to why instructors are shunning the `programming_language` setting? Is it just that instructors want to avoid syntax highlighting, or do they want to avoid other codemirror features as well (which I think is just line numbers) for these short answers?

**Comment by bmcutler** [comment]
The prog lang box setting is incomplete right now.  (we still have a captured tab problem, box height in linese might not work.. I forget what else)

The prog lang setting is rather heavy.  In some cases we just want a single line short answer that might be a code fragment or even just a word.  The capitalization might be annoying/incorrect even if its not code.  That's why I suggest it be an option for the box.

**Comment by MasterOdin** [comment]
Agreed on option. 

I propose an options called `autocorrect` that defaults to `true` for short answer / input and is disabled/false when programming_language is set. When set to `false`, it would disable the auto-capitalization and spellcheck on the input.
