### ISSUE TITLE
Improve Autograding Error messages when requested Docker image was not available

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4398]
**Describe the bug**
Right now we have to manually pull the docker image to the worker machine that is doing the autograding.  But if we forget to do this step, the error message is currently confusing.  (it's only in the stack traces log, if you think to look there.) 

**Expected behavior**
So let's get this error message to a location visible to the instructor/ta who's preparing the autograding, debugging instantiation of this gradeable, etc.

**Comment by Divya063** [comment]
@bmcutler I went through the developer instructions (https://submitty.org/developer) and have set up submitty on my local system. I don't see any good first issues but I think this issue might be a good start so I wanted to work on this issue.

**Comment by shailpatels** [comment]
@Divya063 if you're interested in this issue feel free to work on it! However we can't assign issues to people outside of the submitty GitHub organization right now.

Also note you can use this link to filter issues by the "good first issue" tag

https://github.com/Submitty/Submitty/issues?q=is%3Aopen+is%3Aissue+label%3A"good+first+issue"
