### ISSUE TITLE
Add checks on code coverage of new commits

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4429]
Seeing Matt writing new unit tests these days, I feel we can force new PRs to have at least the same coverage as what we have in the master branch. This would slowly improve the code quality of Submitty over time without too much pain and forces developers to look more closely at their code to avoid some easy bugs (like possibly undefined variables, which happened many times as I can remember).

I am not sure if coveralls can do this. If it can't, codecov is good. I see in other projects codecov bot automatically replies in the PR saying if the coverage is increased/decreased.

**Comment by shailpatels** [comment]
I disagree, forcing new PRs to meet an arbitrary code coverage is going to have developers try to meet to min length as opposed to writing good tests. 

We have a course at RPI that requires hitting a certain coverage as part of the assignment and the majority of student tests try and get the highest coverage possible and as are pretty crappy tests E.g: student hits all the lines through some combination of unit tests but ignores a logical path that causes the program to crash in a valid edge case.

Talking about this subject I'm obligated to mention ["When a measure becomes a target, it ceases to be a good measure."](https://en.wikipedia.org/wiki/Goodhart%27s_law)

However yes we do need to write more tests (this is a major weakpoint of Submitty) but forcing people to write tests or hit a coverage is going to result in crappy code that doesn't help anyone.
I suggest we enforce writing tests through code reviews that ask developers to write tests under certain conditions

- PRs with complex logic e.g late days, timestamps, uploads
- PRs difficult to test manually e.g lots of different states/conditions
- Bugfixes e.g after fixing a bug write a test that specifically prevents it from occuring

There are also areas where we could improve writing tests - if we can reduce the effort and cognitive load to write good tests I'm sure people will write more.

You're points are valid for PHPUnit tests which is pretty well developed and we have some good examples (and we're getting better at this!)
Then there are selenium and integration tests which are less developed and typically harder to set up. They don't factor into code covereage but are still valuable. Then we have large chunks of python scripts doing tons of random back-end functions that probably never get tests or even have any testing infrastructure behind them. So many areas beyond phpUnit tests and coverage we should also consider. 

Sorry for the rant I typically ramble when its late night/morning/whatever time im writing this so I'll go through this tomorow and clear up some points. Glad you're still poking around after gsocs over :)

**Comment by MasterOdin** [comment]
@zjxiaohan coveralls was an arbitrary decision that I made back in the early days of both sites that they were pretty identical. At this point, it does seem like codecov is the better platform and I agree we should switch to it for a number of reasons.

Having said that, both can be used to:
1. post a message on a PR with code coverage number
1. enforce that a PR's code coverage delta does not decrease more than x%
1. enforce that any commit hits some minimum % (if not using the above rule)

With codecov, it looks like we could also go a step further and enforce rules on a per-directory basis as well.

**Comment by zjxiaohan** [comment]
@shailpatels 

First I doubt if code coverage will be a "target" even if it is forced. The contributions to Submitty are not graded, and the current <20% coverage is really an easy requirement. It would be weird to assume that once the requirement for increasing coverage is forced, then people will aim for the highest coverage possible.

Even if developers begin to always reach the highest coverage possible. Writing the unit test itself is somewhat helpful even if someone really wants to write bad ones. If the author writes bad code that is super long and is not well decoupled and decides to have a bad unit test that covers all lines, he/she may find it actually difficult to do so because so many things need to be mocked.

Moreover, it is unfair to say that "now that *some* unit tests *may* ignore a critical logical path, forced unit tests won't do much good" considering that not forcing it doesn't mean the critical logical path won't be ignored. Do you have an example that bad unit tests actually decrease code quality? From my experience, a little is better than none, especially we are not pursuing 100%, just 20%-ish.

Yes, code coverage is not an ideal measure and it doesn't really guarantee anything, and it would be best if reviewers can suggest where to add tests. However, during the summer, I haven't really seen any reviewers who say "let there be tests" and I got the impression that it is really up to the contributor 's will if they want to add tests. If it is hard to create a culture (and I believe it is hard because it's open-source and there are many people contributing) where we reviewers care about tests and hardly forget to assess the importance of tests, I believe an automatic way to enforce it would be better - though not perfect.

Yeah, I am still here because I like discussions like this :)

**Comment by zjxiaohan** [comment]
@MasterOdin 

Thanks for the information. I don't really know much about either. I was just kinda happy to see a graph posted in another project I am currently working on, and I was thinking well Submitty deserves one too, which looks like this:

![Screenshot from 2019-09-05 17-06-08](https://user-images.githubusercontent.com/20266703/64328112-78b13400-cfff-11e9-9cc4-84947a0c695b.png)

Even if we decide not to force an increasing trend of code coverage, I feel it would be good to let these coverage tools post coverage changes in the PR as a reminder. The current one in the "checks" section does not draw much attention. Sometimes while I want to add tests, I simply forgot it (like the response one you recently added). I may not be representative of Submitty developers, but a post that says the coverage is dropping would be nice to (at least) me.

**Comment by MasterOdin** [comment]
Yeah, the PR message was turned off as it was almost always decreasing which meant it just became noise.

The biggest thing is that it has to be a rule on _all_ PHP PRs, without exception (or at least incredibly rarely granted on a per-PR basis), or else it's too easy to slide into not having it. Also, given that the code coverage for much of the much of it is 0%, I'd be fine with people writing tests that just cover the happy path only to start with, adding in edge cases and other stuff as time goes on. Yes, writing tests for the sake of boosting code coverage can be bad, and reviewers must be able to spot bad tests and provide assistance into turning them into good tests (or telling a potential PR what a test might looks like for what they're fixing).

**Comment by MasterOdin** [comment]
Alright, see #4434 for an implementation of codecov for the repo using flags to section off the different components (that have tests that generate coverage).

For now, I think I'll leave demands on coverage off for a project as a whole, but turn it on for at least the `migrator` for now as its coverage is almost at 100% already.

**Comment by zjxiaohan** [comment]
Yeah I realized it would be hard to write tests for some PHP controllers as a majoriiity of them call view functions without returning. Before we have enough examples, it would be discouraging to force every developer to refactor them into `Response` when they make a very small change to the controller function.

Hopefully, I will slowly (...well.. I am busy next semester :sob: ) add more tests for existing hard functions.

**Comment by bmcutler** [comment]
We did switch to codecov.
We agree that increasing code coverage is desirable, 
but this issue does not propose solution to motivate this effectively.
