### ISSUE TITLE
Too many announcements in the forum

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4432]
**What problem are you trying to solve with Submitty**
If an instructor has made a couple dozen email announcements in the forum over the course of the semester, and leaves the star enabled for every post (they don't realize they can remove the star), those posts will be at the top of the forum and will drown out new threads.

**Describe the way you'd like to solve this problem**
Have some sort of hint to the instructor that they can un-announce the old announcements.  Instructor (and maybe all graders??) will have some extra messaging, suggestion, that they can accept (or decline), that will remove stars from threads that are at least 7 days old.

**Comment by sak6lab** [comment]
Discussed having a modal that appears when there are more than 5 announcements that asks to remove stars from announcements that are more than 7 days old.

**Comment by bmcutler** [comment]
Design revision (this is misused misunderstood in most classes, and let's avoid the annoying popups and manual announcement maintenance):

Let's add an 'expiration date' to every announcement thread (can be infinity (year 9999) for all existing threads)

For all new announcement threads lets default this expiration date to be 7 days from creation date.  Once "announcement" is selected, the instructor has a date picker UI to revise this date if desired.

Once the date passes, either 
  1) the star symbol (or whatever we agree on as the final symbol -- see issue #4520) disappears and the thread displays like a non announcement thread (now sorted chronologically)
OR
  2) the star symbol changes color(turns grey?) and the the thread drops  into chronological order.

1 might be difficult to accomplish?  What's stored in the database?  What does it look like it we try to edit this post?

2 might be less confusing?  Or more confusing?
