### ISSUE TITLE
Forum router request

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4433]
**What problem are you trying to solve with Submitty**

Can we have: 
https://submitty.cs.rpi.edu/f19/csci1200/forum
point to the default forum view, same as:
https://submitty.cs.rpi.edu/f19/csci1200/forum/threads

Currently, if you go to the first url, it takes you to the submitty homepage (listing all courses).  That short url is convenient to direct students to read the forum in general :)

**Comment by alice300** [comment]
My router IP [192.168.254.254](https://routerguide.org/192-168-254-254) couldn't be open after trying many times. What is the solution to this problem?
