### ISSUE TITLE
Begin to Constrain Docker Container Resources

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#4438]
Now that we have moved to using the python docker bindings, it has become much easier for us to constrain container resources to more closely match the already set Submitty ```RLIMITS```. 

To start, let's try to constrain docker runtime to be ```RLIMIT_CPU``` time plus a few second epsilon, and look into constraining docker's ```RAM``` footprint.

**Comment by emaicus** [comment]
Related Files: 
Autograding/where docker is used:
```autograder/autograder/grade_item.py```
```autograder/autograder/testcase.py```
```autograder/autograder/execution_environments/container_network.py```

Where default ```RLIMITS``` are defined:
```grading/execute_limits.cpp```
```grading/default_config.h```

Where ```RLIMITS``` are used:
```grading/execute.cpp```

**Comment by shwehtom89** [comment]
Closed via #4458
