### ISSUE TITLE
Discussion Forum Posts unrender when scrolling

### ISSUE THREAD

**Issue by jputlock** [Submitty/Submitty#4442]
When scrolling down the discussion forum on mobile, some names/previews completely blank out with white.

**To Reproduce**
1. Open Submitty on mobile.
2. Go to the discussion forum.
3. Scroll down through posts.

**Configuration**
 - OS: Android 9
 - Browser: Chrome

**Screenshots**
![submitty](https://user-images.githubusercontent.com/8323852/64478972-5265d280-d17e-11e9-8223-46ad08532bbc.jpg)

Note: The issue I'm referring to is the excess WHITE space. I blanked out some areas with solid red where there was information (actual posts, URL, course title).

**Comment by shwehtom89** [comment]
I was unable to recreate this bug on neither my virtual machine nor on a course on production with a fairly active discussion forum.

On my local setup I used chrome's developer tools to simulate a mobile device and I tested scrolling for all the default screen sizes which include chrome on Android and iOS. I also tested by adjusting the network speeds available in chrome's mobile tools.

![mobile](https://user-images.githubusercontent.com/34754780/75457538-988c3980-594a-11ea-9ab5-14abdf3f63b2.png)

**Comment by shwehtom89** [comment]
Closing this issue is now. If it comes up again please reopen the issue and provide what browser and device it was reported it. If possible try providing details about the course like number of threads, what thread is selected and any other miscellaneous details for about the page.
