### ISSUE TITLE
Checkpoint Gradeable -- sort on first or last name does not work

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4454]
**Describe the bug**
A checkpoint gradeable (graded by registration section, if that matters),
by default it's ordered by user_id.  There are buttons to click to instead sort by first or last name, but they seem to be broken now.  (The order changes, but it's totally wrong).

**Comment by Kohdz** [comment]
Hello, I will be working on the bug and hope to have it resolved soon

**Comment by shailpatels** [comment]
@MasterOdin do you think it would be worth it too add in a plugin to sort on the front in, if we do we could avoid having to re-query every time on sort.

https://getbootstrap.com/docs/4.3/content/tables/
https://github.com/wenzhixin/bootstrap-table

I have a feeling the querries we're using are broken when getting all the students, 
might be related to #4633

**Comment by MasterOdin** [comment]
I'd ask how often are people re-sorting things. If it's a couple times per grading, yes, it's probably worth it but it's just once a twice a semester, no, it's not worth the overhead.
