### ISSUE TITLE
Set use_router flag to default to false

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#4469]
As we move more and more courses to containers, it does not make sense to have this flag default to `true` when most courses are going to want it to be `false`. 

I think right now, the course list we plan to have (or do have) on Docker at RPI is:
* ITWS-4960 (Database Systems - Johnson)
* CSCI-4270 (Computational Vision)
* CSCI-4430 (Programming Languages)
* CSCI-4510 (Distributed Systems)

Possible:
* CSCI-1200 (Data Structures)
* CSCI-4380 (Database Systems - Adali)

where I believe only CSCI-4510 is using the router feature, though perhaps so is ITWS-4960 is as well, I'm not really sure.

**Comment by emaicus** [comment]
Done.

**Comment by MasterOdin** [comment]
Please update the docs then as they indicate otherwise: https://submitty.org/instructor/assignment_configuration/networking#specification-of-a-networked-gradeable
