### ISSUE TITLE
Uploading a zip in course materials will unpack hidden unviewable files

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#4475]
**Describe the bug**
When uploading a zip to course materials that contains `.git`, `__macosx`, `.DS_STORE`, or various other hidden metadata folders and files, these folders will be extracted, but never displayed to the user or added to the `course_materials_file_data.json`, but still existing on the filesystem.

**Expected behavior**
Do not extract these files.

**To Reproduce**
1. Upload 
[test.zip](https://github.com/Submitty/Submitty/files/3612952/test.zip) (contains `__macosx` folders and a `.DS_Store` file)
2. Look at files in UI
3. Look at files on filesystem
4. See bug

**Comment by shailpatels** [comment]
Closed via #4449
