### ISSUE TITLE
New gradable template set to none after not none

### ISSUE THREAD

**Issue by matgar1997** [Submitty/Submitty#4477]
**Describe the bug**
Server crash when creating a new gradable you can set the template to a type and revert back to none

**Expected behavior**
Reset the defaults back to when the page originally loaded

**To Reproduce**
1. New gradable
2. Set template to something other than None
3. Set template back to None

**Configuration**
 - OS: Mac
 - Browser: chrome

**Comment by bmcutler** [comment]
This feature is stale and I don't think used by anyone right now (it needs an overhaul).
Let's just comment it out from the GUI for starters.
