### ISSUE TITLE
Upload of empty file broken?

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#452]
If an empty file is dragged into a bucket, it is displayed in the bucket, but disappears (does not get saved to the directory) when the submit button is pressed.

[ more testing needed to confirm diagnosis ]

**Comment by bmcutler** [comment]
E.g., I cannot upload p2_bug.py to part 2 of the python_static_analysis test.

**Comment by bmcutler** [comment]
now named p2_bug.txt

**Comment by MasterOdin** [comment]
This was an issue on 192.168.56.101, doesn't seem to affect 192.168.56.104. Going to close this as a non-issue.
