### ISSUE TITLE
'Open/Close Submissions' button shows half of one line of code

### ISSUE THREAD

**Issue by AudreyBeard** [Submitty/Submitty#4525]
**Describe the bug**
When clicking the 'Open/Close Submissions' button after opening the submission folder manually, the embedded code box only displays half of one line of code. Only way to fix is to reload page.

**Expected behavior**
If some part of the submissions tree is open, a click of the 'Open/Close Submissions' button should either toggle the whole tree open or closed, with the files displaying at their normal size.

**To Reproduce**
1. Go to grading interface, as you do when grading a single student's code submission
2. Open the "Submissions" folder in the "Submissions and Results Browser"
3. Click the "Open/Close Submissions" button to close submissions tree
4. Click the "Open/Close Submissions" button again to open submissions tree

**Configuration**
 - OS: Ubuntu 18
 - Browser: Firefox

**Screenshots**
![image](https://user-images.githubusercontent.com/16946477/65362346-02066000-dbd5-11e9-8c66-812b3e5bc9f8.png)

**Comment by HenrikLam** [comment]
Was able to reproduce the bug using Google Chrome. The text also seems to be invisible when the panel is too small e.g. when using 4 panels view.
