### ISSUE TITLE
pdf annotation - add zoom levels between 100% and 200%

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4528]
Hopefully this is easy...  but we need increments for the zoom for the pdf viewer/annotator.

E.g. at least 100 -> 125 -> 150 -> 200 . 

Also, I have reports that when zoom is not 100% (I think when zoom is 200%) clicking on a component does not scroll to the right page.  But when it is 100% it did.  I thought we fixed this.  I didn't think to ask which OS/browser.  So let's please check that it works on all the browsers.

Tagging both @shailpatels and @mktung 
please figure out who will do what :)

**Comment by elihschiff** [comment]
I was having the scroll issue on Firefox 69 on Linux if that helps. (I did not try another browser)
