### ISSUE TITLE
Able to submit a grade inquiry after deadline (But does not go through)

### ISSUE THREAD

**Issue by sak6lab** [Submitty/Submitty#4535]
**Describe the bug**
When the grade inquiry deadline is before the current date, users are still able to see the form and options to submit a grade inquiry 

**Expected behavior**
When it is passed the grade inquiry deadline users should only see the grade inquiry form if only there is an active grade inquiry. Once this grade inquiry is closed further grade inquiry actions should not be able to made (or maybe?). No matter what the posts should be able to be seen.

**To Reproduce**
1. allow grade inquiries
2. make sure grade inquiry deadline date is before current date
3. go to grade inquiry box or panel
4. the form will still be shown to make a new grade inquiry
5. if you try to make a grade inquiry the page will reload and luckily no grade inquiry will be made.

**Comment by sak6lab** [comment]
I planning to add end to end tests along with a fix for this issue as there are many elements that appear conditionally on this page. Should this be an end to end test or is there a way to test twig templates?

**Comment by MasterOdin** [comment]
This should be an end-to-end test. While you could write a unit test for what the generated HTML of a twig template is, there's little value in it as it does provide any assurance that the HTML is actually usable/useful and behaves correctly.
