### ISSUE TITLE
Refactor Course Materials to no longer use 'check'

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#4538]
**What problem are you trying to solve with Submitty**
Before course material used release datetimes, instructors had an option of a binary checkmark which releases the materials immediately. This was replaced with an 
option to select a date on which the materials would be released.

However, the code base still has a lot of leftover code and specifically the variable
'checked' is still being passed from the client to the server which is then being written to
`course_materials_data_file.json` even though the value of 'check' for a file is never being used anymore.

**Describe the way you'd like to solve this problem**
Refactor course materials controller to remove using the value of check and update the tests accordingly

**Comment by Nabel0721** [comment]
I'd like to take a shot at fixing this. Could you point me to the files I should start with? First time looking at this repository.

**Comment by shailpatels** [comment]
Hi @Nabel0721, the old value 'check' is still being scattered across a few different places in the controller for course materials. I believe the two functions are uploadCourseMaterials , modifyPermission, and modifyTimestamp which are located in `CourseMaterialsController` under `Submitty/site/app/controllers`

Right now a json key of 'checked' is always being written as 1 even though its never read anywhere. 
 
It may be worthwhile to look at the front end in the `site/app/templates/course` which calls 
a couple of functions in `drag-and-drop.js` to interact with the backend although I'm not sure if the front end is still passing values for 'checked' in its ajax requests (it may be sending a dummy value if the controller is still expecting a value).

(The PHPUnit tests will also need to be updated as they're expecting the 'check' value in the json but that shouldn't be too bad to change)

If you're a new developer I recommend visiting https://submitty.org/ more information especially under the developer section :)

**Comment by Nabel0721** [comment]
I decided to back off, since I haven't dipped into php before. But thank you!
