### ISSUE TITLE
Student Photos broken for all

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4542]
**Describe the bug**
Student photos are broken for instructor & all graders.

Frog robot:

00:00:34 09/25/2019 - FATAL ERROR
Error (Code: 0) thrown in /usr/local/submitty/site/app/views/grading/ImagesView.php (Line 40) by:
                $mime_subtype = explode('/', FileUtils::getMimeType($expected_image), 2)[1];

Message:
Call to undefined method app\libraries\FileUtils::getMimeType()

Stack Trace:
#0 unknown file(unknown line): app\views\grading\ImagesView->listStudentImages(Array, Array, true)
#1 /usr/local/submitty/site/app/libraries/Output.php(200): call_user_func_array(Array, Array)
#2 unknown file(unknown line): app\libraries\Output->renderTemplate(Array, 'listStudentImages', Array, Array, true)
#3 /usr/local/submitty/site/app/libraries/Output.php(165): call_user_func_array('self::renderTemplate', Array)
#4 /usr/local/submitty/site/app/controllers/grading/ImagesController.php(42): app\libraries\Output->renderOutput(Array, 'listStudentImages', Array, Array, true)
#5 unknown file(unknown line): app\controllers\grading\ImagesController->viewImagesPage()
#6 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(169): call_user_func_array(Array, Array)
#7 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(147): app\libraries\routers\WebRouter->run()
#8 /usr/local/submitty/site/public/index.php(122): app\libraries\routers\WebRouter::getWebResponse(Symfony\Component\HttpFoundation\Request, app\libraries\Core)

URL: https://submitty.cs.rpi.edu//f19/csci1200/student_photos
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by holzbh** [comment]
Looks like this call got overlooked in #4531 and that this call should be replaced with a call to `mime_content_type()`.

Only other usage is cosmetic (it's in a comment) but kind of weird to leave any mention of a function we're removing: https://github.com/Submitty/Submitty/blob/master/site/app/controllers/student/SubmissionController.php#L1016

**Comment by MasterOdin** [comment]
Yeah, I incorrectly applied the merge from master from #4530 into #4531 and missed that.

I updated my PR to take care of the comment you point out as well.
