### ISSUE TITLE
Hidden Course Materials

### ISSUE THREAD

**Issue by jchulton** [Submitty/Submitty#4582]
When creating course materials, add a boolean field hidden (in the form of a checkbox). When this is checked, course materials will not be displayed to students in the Course Materials UI. However, the files would still be uploaded and could be accessed via URL.

*Default hidden to false
*Store as a boolean in the json file
*Hide course materials only from students (user group 4)

**Comment by ann458** [comment]
hi, can I work on this?

**Comment by jchulton** [comment]
This was added in pull request #4568
