### ISSUE TITLE
rainbow grades does not alphabetize last names that begin with lowercase letter correctly

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4589]
Currently does:

Zebra 
vanRensselaer

Should be
vanRensselaer
Zebra

**Comment by bmcutler** [comment]
(when sorting by section)

**Comment by matgar1997** [comment]
Is the only way for a name to start with a lowercase letter from a preferred name change by the student?

**Comment by MasterOdin** [comment]
While that may be true of RPI, it's almost certainly not true of other schools, so assume that both legal and preferred last names can start with a lowercase.

**Comment by bmcutler** [comment]
RPI's data includes (non preferred) last names that begin with a lowercase first letter.

**Comment by bmcutler** [comment]
This may only be a bug in the C++ rainbow grades code.  
We generate a rainbow grades summary of all students for the instructor, sorted by last name for use in data entry.
It does not appear to be a problem on the "manage students" page. 
Should check the lab checkpoints page (once we debug the alphabetization problem there)

**Comment by Yash1256** [comment]
@bmcutler @emaicus   Sir, i was looking at the issue I tried to look for cpp file that you mentioned as the possible source of bug. But I could not find it. It will be helpful if you could guide me on where to search?
