### ISSUE TITLE
Banner for excused absence extension does not appear for instructor users

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4591]
**Describe the bug**
It only appears for users who are student, limited access grader, or full access grader

<img width="280" alt="Screen Shot 2019-10-03 at 3 09 51 PM" src="https://user-images.githubusercontent.com/5871417/66156554-e006d780-e5ef-11e9-822c-9a4c0769a280.png">

**Comment by dpham-p** [comment]
First-time trying to contribute but isn't the banner not appearing for instructor intended? Instructor is only ever allowed to see the banner if they are part of a team.

https://github.com/Submitty/Submitty/blob/6b3d475eaf03c361054532e5d4bbde9ca40586ec/site/app/views/submission/HomeworkView.php#L46-L51

**Comment by filipe-gomes** [comment]
Is this issue occurring for instructors that are part of the team? @bmcutler

**Comment by adrijshikhar** [comment]
@bmcutler i would like to work on the issue
PS i have already setup the repo

**Comment by arougey** [comment]
Talked to Cutler and Chris, issue is fixed.
