### ISSUE TITLE
After selecting pen, cannot change pen size or text size

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#4599]
**Describe the bug**
When the pen is selected, cannot change the pen size or the text size.

**Expected behavior**
Can change the pen/text size even with the pen active.

**To Reproduce**
1. Open PDF for grading
2. Select pen
3. Attempt to change pen/text size

**Configuration**
 - OS: [e.g. Windows, Linux, ...] macOS
 - Browser [e.g. chrome, safari] Firefox, Chrome

**Comment by nitish81299** [comment]
![Screenshot](https://user-images.githubusercontent.com/39915361/75381225-6654ea80-58fe-11ea-9d02-f0b4a15a59e5.png)
***I see no error changing text size while selecting pen tool.***

**Comment by nitish81299** [comment]
![Screenshot1](https://user-images.githubusercontent.com/39915361/75381393-ad42e000-58fe-11ea-878d-62c2c8838059.png)

**Comment by nitish81299** [comment]
***I see no error changing text size while selecting pen tool. Can you elaborate the errror more.***
