### ISSUE TITLE
too many "download" files displayed when students view their bulk upload gradeable

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4615]
**What problem are you trying to solve with Submitty**
When a student views their grade for a test that was graded as a scan & bulk upload,
the currently see download links for the pdf, and every individual page as a png.

We're going to use the pngs to optimize TA grading, but the students don't need to see those files.  For bulk upload gradeables, let's not show files named upload_X.png.  Only show upload.pdf.  If there are additional files (e.g. laptop .txt files for certain students), do show those files.

**Comment by shailpatels** [comment]
This issue was closed via #5135 & #4627
