### ISSUE TITLE
Improve 192.168.56.104's styling and issues

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#462]
These are outstanding issues that need to be resolved before the start of the semester.

- [x] Clean up failed submissions. We should be deleting the newest version folder in both submissions and results directories

---

- [x] For cpp_cats, upload correct zip and submit. Delete cat.cpp and upload new cat.h (get warning message on replacing, say yes) and then hit submit. Throws exception on trying to uploading cat.h to server.
- [x] Using previous files, potentially throws exception on missing files
- [x] Disable submit button when pressed (so prevent multiple pushes)

- [x] when you roll back to a previous version, the list of files is empty, so the "clear" and "submit" buttons should be greyed out.  (currently they are not greyed out, but if you hit submit it does correctly error with a message about no new files).

----
- [x] Utilize queue status to display more informational messaging to the user about current submission status ([more below](https://github.com/Submitty/Submitty/issues/462#issuecomment-238407082))

---------------------
- [x] Move badges to left of title line
- [x] Clicking on the points badge should expand bar
- [x] Put a "Details" text on testcases that have something to show and while things with nothing don't show anything (ex: successful compliation test)
- [x] Maximize test results only if one test, otherwise minimize all test results boxes

- [x] badges for tests that are extra credit should be green if they are full credit, or gray otherwise.  (never red)  For example, submit "julian_full_credit.cpp" to cpp_simple_lab

---------------
- [x] Convert Diff Viewer to use divs instead of tables and make it adjust better to varying widths
- [x] There should be a unique id given to each diff instance as right now highlighting one diff box will highlight all of them
- [x] Width of outputted diff should not be 50% of the row but rather take up as much space as needed, even if it requires a horizontal scroll bar on the browser window
- [x] Right now the different autocheck elements should stack vertically even if there is room horizontally, E.g. the cpp_memory_debugging test
- [x] If (and only if) there is both a student and instructor file, append the autocheck description to "Student" and "Expected" label.  (Or maybe this appending should be done by the C++ code that generates the submission.json file.  Might change later).
- [x] If there are one or more "message"s for an autocheck, list them in red below the autocheck title and above the file contents box. (In the 101 version I think the message was above the title. In the 104 version, it's currently to the right of the file contents box.)
- [x] If the student file (or instructor file) exists but is empty...  it should be displayed.  Currently the file seems not to be displayed if empty.

---------------
- [x] Use "trashcan" icon to delete file instead of having to click on the file name
- [x] when there is only 1 part, change "Drag your Part 1 here or click to open file browser” to "Drag your file(s) here or click to open file browser” (or similar)
- [x] Remove the “SUCCESS” popup when uploading file and use the new notice toast

---------------
- [x] Change "ACTIVE" to "GRADE THIS VERSION" (both dropdown and set active button)
- [x] Change cancel button to be "DO NOT GRADE THIS ASSIGNMENT"
- [x] Cancel button should be right justified and not right next to the dropdown
- [x] Change "Cancelled" in dropdown to "Do not grade assignment"
- [x] Change Cancelled red text to include that you can still select previous versions

---------------
- [x] Fix DiffViewer not always using monospace font (due to code_inner class)

**Comment by bmcutler** [comment]
For the 2nd section:  If there are multiple tests, do not expand any of them on page load.  If there is a single test, expand it on page load (if it has details).

For the 3rd section:  If a autocheck (aka filedisplay) has a student and expected file, prepend the "description" (aka title) with "Student" and "Expected".  If it is only a student file, don't prepend anything.

If there are one or more "message"s for an autocheck, list them in red below the autocheck title and above the file contents box. (In the 101 version I think the message was above the title.  In the 104 version, it's to the right of the file contents box.)

**Comment by MasterOdin** [comment]
The queue is implemented such that there are two queues: interactive and batch.

Interactive is done when a student submits an assignment and batch when an instructor puts a bunch of things to be regraded. Once in the queue, the student can have two files to indicate what their status is in the queue:  

1. Waiting to be graded
2. Being graded (signified by the existance of a "GRADING_" file)  

We thus define the following booleans to exist for the Gradeable model:

1. In the interactive queue
2. In the batch queue
3. Currently being graded in a queue
4. Has results (existence of folder for version in results directory)

We then have the following two if blocks:

1. If in Batch Queue and Has Results: "Currently being reprocessed"

---
1. If in Interactive Queue or (in Batch Queue and No Results): 
    1. If being graded: "Currently being graded"
    2. else "Currently in queue to be graded"
2. If no results and not in a queue: "Error has happened, please report assigmnent and version to an administrator"
3. If has results: show results

---
We do not worry about the cases such that that they're in both queues simultaneously nor that a file gets left in a queue indefinitely in some way (as it is generally a result of some external process killing the grading system).

**Comment by bmcutler** [comment]
Add a bullet for a bug that its not displaying empty file.  For example, p2_bug.txt uploaded to part 2 of python_static analysis.

**Comment by bmcutler** [comment]
The width of the file display box should not be limited to 50% of the page width.
Also, I’d prefer the file box to never have its own horizontal scroll bar.  if the file is wider than the browser, just put a horizontal scroll on the whole browser (it’s easier to compare vertically stacked student & expected if they scroll together on the whole page than having individual scroll bars you need to manually keep in sync.
