### ISSUE TITLE
Popup grade view for non handwritten solutions

### ISSUE THREAD

**Issue by matgar1997** [Submitty/Submitty#4659]
**What problem are you trying to solve with Submitty**
To provide a quick way for an instructor to see that a student submitted extra files
beyond the original scanned test. This way a student doesn't have a question mistakenly
marked with a 0.

**Describe the way you'd like to solve this problem**
Have the grading view detect that more files have been uploaded for this student
and if they have show a popup when the grader selects the next student

**Describe any potential alternatives you'd tried to solve the problem**
Have the students write "laptop" in the box on the test but often students either forget
or only put it on the cover sheet

**Comment by bmcutler** [comment]
Proposal:  Let's place the label on the toolbar, similar to the "Late Submission" message.
(and add a background color)
![](https://user-images.githubusercontent.com/5871417/71208503-1bbc4f80-2277-11ea-9825-d40737c8bffd.png)
