### ISSUE TITLE
Buildbot cannot run tests on branches with an emoji in the branch name

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#4665]
**Describe the bug**
A branch that has an emoji cannot run on buildbot

Error :
``` buildbot.process.remotecommand.RemoteException: b'builtins.UnicodeEncodeError': 'ascii' codec can't encode character '\U0001f986' in position 4: ordinal not in range(128) Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/twisted/spread/pb.py", line 1054, in _recvMessage netResult = object.remoteMessageReceived(self, message, netArgs, netKw) File "/usr/local/lib/python3.6/dist-packages/twisted/spread/flavors.py", line 125, in remoteMessageReceived state = method(*args, **kw) File "/usr/local/lib/python3.6/dist-packages/buildbot_worker/base.py", line 153, in remote_startCommand d = self.command.doStart() File "/usr/local/lib/python3.6/dist-packages/buildbot_worker/commands/base.py", line 160, in doStart d = defer.maybeDeferred(self.start) --- <exception caught here> --- File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred result = f(*args, **kw) File "/usr/local/lib/python3.6/dist-packages/buildbot_worker/commands/shell.py", line 47, in start logEnviron=args.get('logEnviron', True), File "/usr/local/lib/python3.6/dist-packages/buildbot_worker/runprocess.py", line 334, in __init__ self.command = to_bytes(util.Obfuscated.get_real(command)) File "/usr/local/lib/python3.6/dist-packages/buildbot_worker/runprocess.py", line 329, in to_bytes cmd[i] = a.encode(self.builder.unicode_encoding) builtins.UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f986' in position 4: ordinal not in range(128) ```

**Expected behavior**

**To Reproduce**
1. Create any branch with emoji name
2. wait for build bot results

**Configuration**

**Screenshots**

**Additional context**

**Comment by elihschiff** [comment]
Would this not be a bug with buildbot instead of Submitty and therefore be posted on the buildbot issue tracker?

I found a bug report which is along the same lines as this bug.
https://github.com/buildbot/buildbot/issues/4053

**Comment by MasterOdin** [comment]
The error is with Buildbot, namely that it attempts to checkout a branch as part of its clone, which fails. I've reported it upstream (https://github.com/buildbot/buildbot/issues/5067), and also tracking this in the submitty-buildbot at https://github.com/Submitty/submitty-buildbot/issues/15.
