### ISSUE TITLE
Low-contrast favicon

### ISSUE THREAD

**Issue by io12** [Submitty/Submitty#4707]
**Describe the bug**

Submitty's favicon is low-contrast with the tab background on many themes.

**Expected behavior**

I expected Submitty's favicon to be clearly visible against the tab background.

**To Reproduce**
1. Set the browser theme to something light
2. Go to https://submitty.cs.rpi.edu/home
3. See the tab favicon

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

Firefox, linux

**Screenshots**

![image](https://user-images.githubusercontent.com/7348004/67876799-dc8f3f00-fb0e-11e9-881f-6b923c9b744b.png)

**Additional context**

One way to fix this would be to give the favicon a black outline.

**Comment by bmcutler** [comment]
This is a low priority feature.  The text is sufficient.
