### ISSUE TITLE
Course materials date calendar can go off screen

### ISSUE THREAD

**Issue by jchulton** [Submitty/Submitty#4712]
On small screens:
Go into course materials, click upload course materials.

In the modal, click on the input box under "Choose a time to release the file being uploaded".

The "now" button to finalize the date can go off screen.

**Comment by bmcutler** [comment]
Also when a course material is edited, and the date picker is popped up:

<img width="540" alt="Screen Shot 2023-02-02 at 3 53 44 PM" src="https://user-images.githubusercontent.com/5871417/216448177-6fab5466-d898-4adc-81d3-a1655007ef15.png">


The date picker does not go away intuitively.  It awkwardly overlaps the "Submit" button.
Here is what's under the date picker:

<img width="509" alt="Screen Shot 2023-02-02 at 4 00 43 PM" src="https://user-images.githubusercontent.com/5871417/216448748-362d51f9-037a-4d5f-82eb-7fcbc4b01581.png">


Weirdly if you vertically scroll, you can get the date picker panel to move upwards out of the way to see the submit button.

<img width="610" alt="Screen Shot 2023-02-02 at 4 01 15 PM" src="https://user-images.githubusercontent.com/5871417/216448997-860e0186-d60d-418e-816e-990f23f1bf29.png">

**Comment by saumyaborwankar** [comment]
Hey @bmcutler I've added the closing function of the date calendar when you click on one of the buttons. I wanted to add another button "Set time" which will allow user to click the button and set the time, currently you have to click on some other input area to make the calendar go away. Let me know if you want the new "Set time" button and I'll add it.

**Comment by hansongu123** [comment]
Closed with #9106
