### ISSUE TITLE
Limited access grader access issues for bulk (scanned) exams

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#4714]
**Describe the bug**

**Expected behavior**
An instructor reported issues where limited access graders cannot view PDFs on the electronic grading screen. 

**To Reproduce**
1. Submit a bulk upload 
2. Highest access limit set to limited access grader 
3. Try grading from a limited access grader

**Comment by jchulton** [comment]
This is no longer on master: Following the above steps does not cause an error but allows the limited access grader to grade as expected.
