### ISSUE TITLE
Checkpoint grades are not saved after being input on browser on Desktop

### ISSUE THREAD

**Issue by VictoriaSavage526** [Submitty/Submitty#4716]
**Describe the bug**
When trying to grade checkpoints, clicking on the checkpoint yields a blue bar that stops midway through the check box. Upon trying to refresh the page, the checked off checkpoint disappears.

**Expected behavior**
The Checkpoint remains blue or light blue after being selected.

**To Reproduce**
1. Open up lab grading
2. Try to input a checkpoint
3. See that it gets stuck, try to refresh the page.

**Configuration**
 - OS: 1. Windows, 2. Ubuntu
 - Browser 1. Chrome 2. Chromium

**Additional context**
Both myself and a TA are having this issue.

**Comment by MasterOdin** [comment]
Can you check the JavaScript console for your browser to see what it says when it gets stuck? (https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)

Additionally, can you check what the value of your cookies are set to? (With the console open, go to Application tab, open the "Cookies" section on the left pane, click submitty.cs.rpi.edu, and send me the cookies via PM on slack or email to `pevelm@rpi.edu`).

**Comment by MasterOdin** [comment]
This was not fixed by #4847. The bug here is that I believe the cookie for checkpoints is getting messed up, or invalid data is attempting to be saved into one, but either way a JS error is being thrown before the ajax function is called, causing the checkpoints to be stuck in the half-blue state.

**Comment by bmcutler** [comment]
same as #4645?

**Comment by MasterOdin** [comment]
More or less. I had hoped to get the value of the cookie that can cause this issue to try and help debug why that function is throwing an error, but this can issue can probably be closed in favor of leaving #4645 open.
