### ISSUE TITLE
Use nlohmann fifo_map for ordered json

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#472]
from @MasterOdin:

If we add https://github.com/nlohmann/fifo_map and make that the container type for object_t, we can actually get order on the json in C++ (which I'm in favor for just to make things easier in debugging. We could remove this in the future once we're never actually looking at json files anymore).

**Comment by MasterOdin** [comment]
This line I found in one of the issues of the JSON library might help to figure how to do this?

`using json = nlohmann::basic_json<nlohmann:fifo_map, std::vector, std::string, bool, int64_t, double, std::allocator>;`

**Comment by bmcutler** [comment]
@tkxxrf and I discussed for Rainbow Grades and to preserve order in one case we will use an array instead of an associative object.   A little bulkier than necessary, but the better design.

**Comment by bmcutler** [comment]
Solved :)
