### ISSUE TITLE
Use same naming scheme for late days throughout system

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#473]
Right now, we have different labels for late days as they're used in the system and what's been applied to them. We should change it such that we have the same naming scheme throughout such that when we see a certain name, we know what it means (instead of potentially having to guess/read through the code to figure out exactly what it means).

My proposed scheme:
* days_late - absolute value of days (rounded up to nearest day) homework was submitted after the due date.
* days_late_charged - number of days late student was charged with (which takes into account extensions given, could also be reduced if used too many late days on another assignment).

**Comment by bmcutler** [comment]
deprecated by #722 design
