### ISSUE TITLE
Add Angry Duck for bad submission

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#4730]
**What problem are you trying to solve with Submitty**
Currently the ta grading interface shows the entire grading interface background when a submission is back. Adding an angry duck will fully scare the grader into realizing something is wrong.

Angry duck can also appear when you use too many latedays or when you submit close to the deadline - the possibilities are endless

**Describe the way you'd like to solve this problem**
Add angry duck

**Describe any potential alternatives you'd tried to solve the problem**
this is the only way to solve this problem

**Comment by LeonMontealegre** [comment]
![angryboy](https://user-images.githubusercontent.com/29997057/68066069-a1f0f680-fd08-11e9-8a4f-018270fe2dd6.png)

**Comment by LeonMontealegre** [comment]
![angryboy](https://user-images.githubusercontent.com/29997057/68066166-e92bb700-fd09-11e9-952c-ddd5df19f273.gif)

**Comment by zjxiaohan** [comment]
I am fully scared.

![psyduck](https://user-images.githubusercontent.com/20266703/68186633-8b37f180-ffdf-11e9-9395-360f3fbda602.gif)

**Comment by BenKelly99** [comment]
This is highly important, Matt.

**Comment by bmcutler** [comment]
I'm veto-ing this.
The duck is only for positive messages.
Submitty celebrates positive accomplishments.
