### ISSUE TITLE
Gradeable Test For Compiler Warning (in C++)

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#4735]
**What problem are you trying to solve with Submitty**
We usually include a test for compiling (C++ code) but we are not aware of a way to deduct points for compiler warnings. It shows compiler warning to the students, but how can we write a test that considers these warnings.

**Describe the way you'd like to solve this problem**
In a gradeable test, I would like to assign points to having a compiler warning free program.

**Comment by kshitijandmojo** [comment]
Hi! I Suggest using the freopen() function to solve the problem.

Students can be instructed to use this function to redirect their stderr and stdout streams to text files that are placed in specified files and with a name that can be unique to each student like of format { (sectionno).(RollNo)err.txt and (sectionno).(RollNo)out.txt }  that can be later easily be utilized for evaluation purposes. 
Reference Links :-https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxbd00/freopen.htm

**Comment by prestoncarman** [comment]
Thanks for the idea. It would be nice if the students did not have to do anything. Depending on the assignment, you could have provided code that does the your suggestion. I would just be concerned that the students would be able to alter the code.

Submitty knows when warnings are generated because the web view shows a warning in red when the compiler has generated warnings. Although your post got me thinking, the test could be updated with a new compiler command that would generate all warning as errors. This option would not require changes to the submitty code, but force the students to fix the warnings.

**Comment by kshitijandmojo** [comment]
I am sorry but I can't provide the exact code for this problem since different C++ implementations have little variations of the same function.

I have been facing lot of problems setting up Submitty on my computer. Having said that I have absolutely no idea how it works or which C++ implementation and compiler is used. I would be glad to contribute if you could provide me with these necessary details.

**Comment by bmcutler** [comment]
If you have created a gradeable with a c++ compilation test, go look at the "complete_config" that was generated for that gradeable.  E.g.:

/var/local/submitty/courses/MYSEMESETER/MYCOURSE/config/complete_config/complete_config_MYGRADEABLE.json

This is the config.json you wrote, plus a bunch of defaults added in.  You can copy any of these defaults into your config and adjust the settings.

Go look at the "validation" section for the compilation test.  See what we do by default with the STDERR.txt for that compilation:

                {
                    "actual_file": "STDERR.txt",
                    "deduction": 0.0,
                    "description": "Compilation Errors and/or Warnings",
                    "method": "errorIfNotEmpty",
                    "show_actual": "on_failure",
                    "show_message": "on_failure"
                },

See how the deduction is 0.0?   That's a multiplier for points, not a subtraction of absolute points.   It will show the students the compilation error messages, but not charge them any points.  Just paste that into your own gradeable and set it to 1.0 if you want them to lose all compilation points if they have an error or warning.  Or set it to 0.5 if you want them to lose half of the compilation points.  

You could also write a custom grader and parse the compiler output if you want to grade based on type of warning or # of warnings (sounds messy to me though).

You control the exact compilation line, and yes, you can turn on "warnings as errors" or weed out or include specific warnings.  For example I do:

"clang++ -std=c++11 -Wall -o a.out *.cpp",

Hope this helps.

**Comment by kshitijandmojo** [comment]
Thanks for the information @bmcutler.
I think that deducting points on the basis of what type of errors or # of them is incorrect as it don't always be a fair method. 

Example 
`
int b;
int a                     
for(a=0;a<10;a++){
........
........
}`

When we use # of errors to deduct points :-
In this code snippet , student has forgot to put a semi-colon in the declaration of variable a, leading to multiple errors when ever he uses the variable and deduction of points accordingly. 

When we use type of errors to deduct points:-
Again the compiler will generate 2-3 types of errors here. Again deducting more points than actually it should. 

So , We need to properly think of a better way rather than these simple parameters. I do have a few ideas which I would like to develop further and would share them as soon as they are ready.

**Comment by kshitijandmojo** [comment]
Hi!
I have developed an idea :- 
(here the i am referring to errors that would be generated on making the mistake and the numbers can be changed if the instructor wants)

1.  Not declaring a variable
        **Identified by**:- error of declaration syntax error
         increase deduction by 0.15*(no of distinct error declaration syntax error)+0.02*(no of  error of variable not declared)
2. Not having " on ending of cout statements and not having ; in end of a statement
        **Identified by**:- error of ; not present.
        increase deduction by 0.02*(no of these errors)
3. Not including directry or not defining a user defined function properly or not following correct syntax when using inbuilt functions of library 
       **Identified by**:- Error of function prototype not found and warning of obsolute way of declaring function
         increase deduction by 0.05*(no of such errors)
4. Run time error of division by zero
      **Identified by**:- Error of division by zero  
        increase deduction by 0.07
5.Function not returning value when it must
     **Identified by**:- warning function must return value 
       increase deduction by 0.08*(no of such warnings)
6. forgetting { or }
    **Identified by**:- compound statement { missing
       increase deduction by 0.05

7. Statement missing of any loop or function
   **Identified by**:- statement missing error
       increase deduction by 0.08*(no of such errors)

8. Any other error or warning 
       increase deduction by 0.07*(no of such errors)

@bmcutler and @prestoncarman please let me know if the above plan needs changes or i have missed any type of error or warnings.

**Comment by bmcutler** [comment]
@kshitijandmojo 
Thanks for your ideas, but I think this is out of scope for current and near-term Submitty functionality.

Submitty autograding presents the output of compilation to the student (and the instructor) by default.  Students are encouraged to inspect that output and edit their code accordingly and resubmit.  It is probably not a worthwhile endeavor to score buggy work that has compilation errors.  Students should be encouraged fix the work and re-submit.  (re-submission is allowed by default).

I'm going to close this issue as I believe the original question is resolved.

**Comment by prestoncarman** [comment]
We have an alternate solution that is working. Thanks.

**Comment by kshitijandmojo** [comment]
Thanks @bmcutler  and @prestoncarman  for hearing me. 

By the way I just got curious regarding the compiler thing. How did you guys integrate a compiler which is itself a completely independent program with its own set of requirements and especially the memory requirements for the library on a web page in the form of a script? 

I mean the scripts which are executed on the client side are supposed to fundamentally not have intensive Computational and memory requirements. how was the problem resolved  ?
