### ISSUE TITLE
Navigation Page Issues

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#475]
From the PR #458:
- [x] Links to editing gradeables page and grading page not added.
- [x] User group check (instructors, TAs, students) hard-coded.
- [x] Gradeables not sorted chronologically yet.
- [x] Shortcuts to open grading for a closed item and releasing grades to be added
- [x] Date checks might be more efficient.
- [ ] Progress bars to be added.
- [x] More styling.

Questions:
1. If ta-grading disabled and the item is closed, should TAs still be able to see the item and item listed in being graded?
2. Should TAs see submission open time?

**Comment by bmcutler** [comment]
Also...  a limited access grader who is not assigned any sections (registration or rotating) for that gradeable should not see that gradeable in their list.

**Comment by sihsob** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Student View: Show status of submission on homepage for open assignments](https://trello.com/c/sxnetSv3/6-student-view-show-status-of-submission-on-homepage-for-open-assignments)

**Comment by bmcutler** [comment]
Replaced by issue #1045
