### ISSUE TITLE
Add a cancel button on the upload gradeable admin page

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#4751]
**What problem are you trying to solve with Submitty**
If you decide to cancel the upload, a user must click back in the browser.

**Describe the way you'd like to solve this problem**
A nicer workflow would be allow the user to click on a button to cancel the upload.

**Comment by cmlino** [comment]
I would like to work on this issue.

**Comment by shailpatels** [comment]
Hi @cmlino ! We typically can't assign issues to people outside of the Submitty github organization, if you're interested in working on this issue and making a branch/pull request for it we'll review and try and get it merged :)

Make sure to take a look at our developer resources first:
https://submitty.org/developer
https://submitty.org/developer/how_to_contribute
