### ISSUE TITLE
myers diff output of character differences

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#477]
I think the character output saved in the diff file is buggy for whitespace differences in the cpp_cats assignment for the frontSpacingOff.zip.  

The lines are correctly highlighted in yellow, but the extra space characters in the student output are not highlighted.  The diff.json has characters listed for the instructor/expected output.  But I think it's backwards.  The characters should be highlighted in the student/actual output.

**Comment by MasterOdin** [comment]
Couldn't reproduce.
