### ISSUE TITLE
Team invitation emails should have an 'accept invite' link

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#4807]
**What problem are you trying to solve with Submitty**
When you get an email notification for a team invitation, you must manually navigate to Submitty to accept the invitation.

**Describe the way you'd like to solve this problem**
There should be a link the invite recipient can click on in the email that will accept the invite and keep them on the team page maybe with the text `Accept Invite`

**Describe any potential alternatives you'd tried to solve the problem**
The link could only link to the team page for the gradeable and not accept the invitation.  Maybe with the text `View Team Invites` or something.  Another option would be to have both the `Accept` and the `View Invites` links.

**Additional context**
N/A

**Comment by marwanatef2** [comment]
Hello, I want to work on that issue as a "good first issue" to start contributing with Submitty, But is there already an email that is sent to students upon team invitations so we have to add a url to its content or an email should be sent with the notification for invitation and code for it should be added?

**Comment by marwanatef2** [comment]
I'm working on this issue

**Comment by marwanatef2** [comment]
I think this issue should be closed since PR #4855 , which is merged, solves it.

![Capture](https://user-images.githubusercontent.com/30902406/77124324-399e7980-6a4b-11ea-8e35-c216b4973760.PNG)

And the link works fine.
@bmcutler
