### ISSUE TITLE
Discuss release strategy going forward

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#481]
So one of the concerns that was expressed about our system at the last SIGCSE was that we get a ton of commits into master on a daily/weekly basis that it makes us look immature (and that we don't ever tag a release).

We should discuss a potential release strategy for the project going forward such that "released builds" are not likely to have any breaking changes if some other school was to use our system.

I'm going to use the following numbers:
`101` - New PHP Code/Site
`104` - Old TAGradingServer

My proposal is:
Versioning scheme: major.minor.bugfix (with 1.0.0 being when we've killed off `104` and folded it completely into `101`). We aim to push out at least a minor update every semester with possible bug fixes going on during the semester as necessary.

The two main branches (both protected from direct pushes) are:
1) Master - The head of this should always point to a tagged released on github
2) Develop - This contains merged pull requests during the semester/summer for ongoing work. I propose RPI uses this as we're fine seeing things potentially break mid-semester and debug it on the spot.

The interaction between the branches:
1) Create new feature branch and push some commits to it to fix some issue
2) Create pull request against the develop branch for feature branch
3) Squash & Merge PR into develop branch
4) Merge from develop into master for a release (don't squash commits here)

When we make a release, we then make a changelog for at least a bullet point on all things changed/fixed in the system with perhaps a link to the relative documentation for the feature if it exists

If there's ever a breaking change on the system mid-semester, we can cherry pick specific commits off develop branch to fix it and make a release.

**Comment by bmcutler** [comment]
For each submitty code repo, we will have a master branch, and any number of feature development branches.  Some commits in the master branch will be tagged with a release #.

Each repo can have it's own tag version, however, in the main Submitty repo, we will maintain a record of which versions we have tested to work together.
