### ISSUE TITLE
Thread list cuts off bottom of last thread when scrolling

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#4821]
**Describe the bug**
When scrolling in the thread list, the last thread box does not fully display.

**Expected behavior**
Display the whole thread box

**To Reproduce**
1. Go to forum
2. Scroll to bottom

**Configuration**
 - OS: [e.g. Windows, Linux, ...] macOS
 - Browser [e.g. chrome, safari] Chrome

**Screenshots**

![Screenshot 2019-11-28 21 24 57](https://user-images.githubusercontent.com/1845314/69830553-a801c680-1225-11ea-9529-e77d1276f2ee.png)

**Comment by elihschiff** [comment]
I cannot seem to recreate this issue on my computer. I tried on the live version of submitty 19.11.00
I am on Linux and I tried on both Firefox and google chrome

Firefox:
![image](https://user-images.githubusercontent.com/18558130/70258809-e2ee8780-175a-11ea-92fe-03af82ac530d.png)

Chrome:
![image](https://user-images.githubusercontent.com/18558130/70258817-e8e46880-175a-11ea-81c8-3cfcb0a13306.png)

**Comment by bmcutler** [comment]
closing, please reopen with details on OS and browser and a specific example if this is still an issue.
