### ISSUE TITLE
Display of autograding difference with extended ascii characters

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4839]
**Describe the bug**
When the output has greek characters (and other extended ascii characters) the difference viewer can break.  Significant sections of the student text is not displayed in this example (the differences are more subtle than this screenshot implies).

<img width="585" alt="greek_letters_screnshot" src="https://user-images.githubusercontent.com/5871417/70268596-cd835880-176e-11ea-9b5c-644f4dd652d9.png">

<img width="590" alt="bugfree_screenshot" src="https://user-images.githubusercontent.com/5871417/70269040-95c8e080-176f-11ea-9fd3-3a3253e53511.png">

I'll attach the student, expected, and difference files (autograding seems to compute the right information, it's just a display bug).

[greek_letters_student.txt](https://github.com/Submitty/Submitty/files/3928787/greek_letters_student.txt)

[greek_letters_expected.txt](https://github.com/Submitty/Submitty/files/3928790/greek_letters_expected.txt)

[greek_letters_diff_json.txt](https://github.com/Submitty/Submitty/files/3928797/greek_letters_diff_json.txt)

**Comment by MasterOdin** [comment]
This is a bug with the autograder. Each of the greek characters are two bytes-wide. 

For example, in python:
```python
import pprint
a = open('input_actual.txt', 'rb').read()
b = a.split(b"\n")
pprint.pprint(b)
# renders:
"""
[
 b'FOUND CONSTELLATION Ursa_Major',
 b'assigning  STAR_00001  \xcf\x85_UMa',
 b'assigning  STAR_00002  \xcf\x87_UMa',
 b'assigning  STAR_00003  23_UMa',
 b'assigning  STAR_00004  \xce\xb3_UMa',
 b'assigning  STAR_00006  \xce\xb5_UMa',
 b'assigning  STAR_00007  Mizar',
 b'assigning  STAR_00009  \xce\xb2_UMa',
 b'assigning  STAR_00011  \xce\xb8_UMa',
 b'assigning  STAR_00013  \xce\xbe_UMa_A',
 b'assigning  STAR_00016  \xce\xb1_UMa',
 b'assigning  STAR_00017  \xce\xb9_UMa',
 b'assigning  STAR_00019  \xce\xbc_UMa',
 b'assigning  STAR_00021  \xce\xbd_UMa',
 b'assigning  STAR_00023  \xce\xbf_UMa',
 b'assigning  STAR_00025  \xcf\x88_UMa',
 b'assigning  STAR_00026  \xce\xbb_UMa',
 b'assigning  STAR_00027  \xce\xb4_UMa',
 b'assigning  STAR_00030  \xce\xb7_UMa',
 b'assigning  STAR_00032  \xce\xba_UMa',
 b''
]
"""
```

For all of the lines that are broken (only show _Uma), the autograder is only specifying a single byte to highlight of the two bytes (24) which the DiffViewer dutifully performs, rendering the broken string (as we just inserted a `<span>` tag in the middle of the two bytes).

If you go through the JSON file and put a `23` before all instances of `24` that are not preceeded by `23`, the files will render correctly.

**Comment by MasterOdin** [comment]
This also isn't really something the DiffViewer can handle well due to the non-fixed number of bytes a character may take. ♞ for example is three bytes (`b'\xe2\x99\x9e'`) which makes it very tricky in a general case to detect whether or not the differences JSON is passing bad values or not.

**Comment by MasterOdin** [comment]
For why only one character is getting marked as highlighted, is that the autograder is doing a strict byte by byte comparison. For an example of a line that only gives "24":
```
b'assigning  STAR_00002  \xcf\x87_UMa',
b'assigning  STAR_00003  \xcf\x87_UMa',
```
where we see the first byte of the unicode character matches while the second differs, thus giving us just 24.
