### ISSUE TITLE
Confetti lags when you toggle it a lot

### ISSUE THREAD

**Issue by kwockn17** [Submitty/Submitty#4841]
**Describe the bug**
My friend showed me that if you get a perfect score on the autograding subtotal, you can click on it (the perfect score) to make some confetti appear. The confetti scrolls down the screen slowly as if it is falling. Clicking on the score again will toggle the confetti off. However, if you click the perfect score many times in a short period of time, the confetti appears to lag more every time it reappears.

**Expected behavior**
I expect that clicking on the perfect score should just toggle the confetti on/off without affecting how the confetti appears on the screen (it should not lag).

**To Reproduce**
1. Get a perfect score on an assignment with autograding.
2. Click the score on the submission page to turn on the confetti.
3. Continue clicking on the score to keep toggling the confetti off and on.
4. See error (the confetti will appear laggy).

**Configuration**
 - Chrome (I haven't tested other browsers)
 - Window

**Screenshots**
![image](https://user-images.githubusercontent.com/45607722/70379263-a6f12900-18f8-11ea-8bfb-ba822fc5e0b1.png)
This doesn't really show that it lags, but here's proof that the confetti exists.

**Additional context**
Have a happy holidays!

**Comment by mukul-kmr-jha** [comment]
@kwockn17 +1 , and also i would like to add that the `confetti` makes the layout of site disturbed. i.e it adds empty space on the right side .....

**To reproduce it**  
Start with following above mentioned first two steps.
1. Get a perfect score on an assignment with autograding.
2. Click the score on the submission page to turn on the confetti.
3. Try to scroll right , you will find the empty space.
