### ISSUE TITLE
Add to breadcrumbs, navbar with Manage Team

### ISSUE THREAD

**Issue by matgar1997** [Submitty/Submitty#4852]
**Describe the bug**
When you press the manage team button there is no way to go back from the
navbar without first going back to the course selection page

**Expected behavior**
When you press the manage team button something should be added to the
top navbar similar to when a gradable is pressed

**To Reproduce**
1. Open class with team gradables
2. Select manage team
3. See error

**Configuration**
Should appear on any config, first noticed on
 - OS: Ubuntu 18.05
 - Browser Chrome

**Comment by shwehtom89** [comment]
Here is an example:
![manage_teams](https://user-images.githubusercontent.com/34754780/70725392-4718ca80-1cca-11ea-8291-dc820d1c9594.png)

The breadcrumb should look something like
RPI Computer Science --> Submitty --> Programming Languages --> Manage Team for PA3
or
<Organization> --> Submitty --> <Course Name> --> Manage Team for <Gradeable Name>
