### ISSUE TITLE
Add Basic Peer Grading Example to Sample Course

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#4874]
Add a basic peer grading example to the sample course, where a number of peer graded marks are pre-populated. Note that this will be done ___before___ peer grading is fully implemented, and will be used as a way to begin working on the viewing of peer grading results before entering peer grades has been fully implemented.

**Comment by Dharmesh-Poddar** [comment]
@emaicus  I would like to work on it.

**Comment by emaicus** [comment]
A few features I want this to have (note that this doesn't necessarily require as many assignments as there are bullets, i.e. features can be combined).
1. A normal (non-team) assignment.
2. A team assignment.
3. An assignment where grading should be closed to Peers.
4. A "large scale" peer assignment, where there are >10 peers assigned to each student.
5. An "off by one" assignment where there is at least one group that has fewer peers than the other groups.
