### ISSUE TITLE
Advanced Peer Grading Features

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#4879]
This PR should be broken up when basic peer grading is implemented.
* __Grade the Peer Grader:__ Grade Peer graders for attendance and/or quality of grading.
* __Allow Instructors to Provide Alternate Peer Grade Averaging Schemes:__ Instructors may want to give students their grade based on a metric other than a standard average of peer grades.
* __Automatically Provide Peer Assignments__
* __Allow Instructors to Edit/Override Peer Grades__

**Comment by bmcutler** [comment]
options for generating / preparing peer matrix is now issue #5370

**Comment by bmcutler** [comment]
Closing this issue, replaced by multiple, more detailed issues.
