### ISSUE TITLE
Create an Interface for Instructors and Full Access Graders to View Peer Assignments

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#4880]
Create a space for Instructors and Full Access Graders to view Peer Assignments. This may be housed on the index page.

**Comment by Yash1256** [comment]
It seems Interesting I want to start fixing this issue is there any specific design pattern to create the interface?

**Comment by emaicus** [comment]
Hello @Yash1256. This issue will be partially closed by PR #4970, which you are welcome to review.
After that, can I redirect you towards issue #1385, which is a much needed Peer Grading Feature. 
Note that Peer Grading in general is still very much a work in process, and is currently being implemented/integrated into the system.

If you have any questions, feel free to post them in the comments of either PR #4970, Issue #1385, or in our Slack.

**Comment by emaicus** [comment]
Addressed in PR #4970. Related to new issue #5364.
