### ISSUE TITLE
email should not be sent to students that dropped the class

### ISSUE THREAD

**Issue by inlinefan** [Submitty/Submitty#4887]
Submitty was still trying to send email to a student that had dropped the class.  I noticed it when the email started bouncing because the user was no longer valid.

**Comment by cmlino** [comment]
I wasn't able to recreate the problem on my machine -- when I tried sending an email as an instructor, students who had dropped the class were not receiving it. Could you provide more detail about the issue?

**Comment by bmcutler** [comment]
thanks for investigating!
