### ISSUE TITLE
PHP code incorrectly rounds valid numbers

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#4890]
**Describe the bug**
Using a precision of 0.05 and a max value of 6 for points for a component, the PHP code will incorrectly set it to 6.05 always.

**Expected behavior**
The component should save as 6.

**To Reproduce**
1. Edit a gradeable's rubric
2. Set the precision to 0.05
3. Set the max value for component to 6
4. Hit save

**Additional context**
The problem exists in this function in the Gradeable model:
https://github.com/Submitty/Submitty/blob/c617b754c99a279997bcef35bc2cde2a0d6249e7/site/app/models/gradeable/Gradeable.php#L1157-L1179

where given a `$this->precision = 0.05` and `$points = 6`, it returns 6.05.

**Comment by MasterOdin** [comment]
This function should be moved into a `NumberUtils` library file (e.g. `app/libraries/NumberUtils.php`) and made into a static function to make it easier to test this function, as well as that it really does not need to be a part of the model.

**Comment by elihschiff** [comment]
I am a bit stuck solving this bug so for the next person who wants to give it a try, I changed line 1178 to `return round($points/$this->precision)*$this->precision;` and it solved most of the issue. I am pretty sure this new line works the exact same way but does a better job dealing with floating points. 

The one issue I cannot figure out is where this comes from 
![image](https://user-images.githubusercontent.com/18558130/71145579-1ec02d00-21f0-11ea-93d3-dc2af7ca3341.png)

It looks fine when you open the thing to edit a grade but when it is closed it gives this floating point error. I cannot trace where in the code this is coming from so I don't know how to fix it.
![image](https://user-images.githubusercontent.com/18558130/71145686-6646b900-21f0-11ea-8d6e-65468edb288b.png)
