### ISSUE TITLE
Show position in grading queue

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#490]
Broken out of #462 as it's fairly low priority.

Essentially, when submitting a homework, it'll display one of the following three:
1. This assignment is currently in the queue to be graded.
1. This assignment is currently being graded
1. The Results

The first one should show the position of where in the queue to be graded the student is. The relevant sorting code [here](https://github.com/Submitty/Submitty/blob/master/bin/grade_students.sh#L755) which does:
Organize files by last modified time (newest first) in reverse order with one element per line. Any files that have the same timestamp are done in reverse alphabetical order. Thus, if having the following files:
file1 - 04:00:00
file2 - 05:00:00
file3 - 04:00:00

The returned order will be:
file3
file1
file2

Additionally, we should make it such that the submission queue position is refreshed periodically, as well as have the page automatically refresh through the steps (instead of only refreshing once results are available).

**Comment by sihsob** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XMNIuOYS&#x2F;1-show-position-in-grading-queue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Show position in grading queue</a>

**Comment by sihsob** [comment]
For grade_students.sh, do all prints and echos get logged in a file or do only explicit calls to log get saved? As in if I print to stdout, does it in anyway get reflected back to the front page?

**Comment by bmcutler** [comment]
You don't need to modify grade_students.sh.  I don't recommend using prints in that script since it's hard to run the new code (it's a cron job) and no they don't get logged.
All of your work is looking at the files in the to_be_graded directories.

**Comment by MasterOdin** [comment]
And all this work can be done in PHP via scandir and filemtime within the PHP code (for the first point) and is_file (for the second point)

**Comment by sihsob** [comment]
Closed #728
