### ISSUE TITLE
Allow supplying only user_id for uploading grader list

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#4917]
**What problem are you trying to solve with Submitty**
When uploading the grader list via CSV (or XLSX), it is required to have the entire row filled out, which can be cumbersome to collect. It would be nice, much like the user add box, to just supply a user_id and have the other fields auto-populated.

**Comment by mukul-kmr-jha** [comment]
How will we assign the user_group to the graders by supplying just the user_id, I mean should we use some default value for this field(limited_access_grader ?) like in the case of the registration section.
