### ISSUE TITLE
Display link to assignment on the gradeable submission page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4926]
Instructors can add a url link to the assignment instructions.
This link is currently only displayed on the page with all gradeables (under the offsite link font awesome symbol).
Let's also add the link on the submission page for the specific gradeable.

**Comment by mridullpandey** [comment]
hi can you please asisst regarding this .. i want to work on it..
thanks:)

**Comment by MasterOdin** [comment]
After talking with @bmcutler, we would like to see the link that gets shown on the gradeable list page (circled here):
![Screenshot 2020-01-16 12 45 58](https://user-images.githubusercontent.com/1845314/72549145-2b22be80-385e-11ea-98ce-d6829d1c387f.png)

and put that same icon and link here on the submission page:
![Screenshot 2020-01-16 12 43 58](https://user-images.githubusercontent.com/1845314/72549196-42fa4280-385e-11ea-9ec4-53a9f6dc0ef5.png)
