### ISSUE TITLE
Move location of "Edit Categories" button for Discussion Forum

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4929]
Currently the "Edit Categories" button is (only?) on the page for creating a new thread (after you click "Create Thread").  Also, it's only available for instructors.

2 problems:

1.  If you've typed your new thread title & message, then realize you need a new category, you can't go to the edit categories page, it won't remember/save that information.   (Note:  I don't think this urgently needs to be fixed.)

2.  If you just want to create a category for future use (you aren't writing a thread right now), the current location of this button is non-intuitive.

Let's move this button instead to the main forum page, as a button left of the "Create Thread" one. Additionally, remove the link to manage categories from the create thread page.

**Comment by MasterOdin** [comment]
Per our discussion today, it was decided that:
1. A new button would be added to the forum top bar left of the "Create Thread" button that takes you to the categories page. 
2. Remove the edit categories link from the create thread page.
