### ISSUE TITLE
Badge Bugs

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#494]
The badge & title positions are sloppy now.  Would be better to ensure that the test titles are lined up regardless of the presence or size of the badge.

I'll try to attach images...
<img width="268" alt="screen shot 2016-08-14 at 3 49 04 pm" src="https://cloud.githubusercontent.com/assets/5871417/17651528/24ddcd90-6237-11e6-9f93-71b67debe357.png">
<img width="234" alt="screen shot 2016-08-14 at 3 48 53 pm" src="https://cloud.githubusercontent.com/assets/5871417/17651529/24deac6a-6237-11e6-82db-6a1b468eccf1.png">

The images above are from cpp_hidden_tests with various file uploads.  

A badge should not be displayed (though the title should be inline still) if:
* there is no points for a given test case
* if its an extra credit test and the score is zero, no badge. 
* if its a penalty test and the score is zero, no badge).

**Comment by bmcutler** [comment]
also, I propose we remove the prefix "Extra Credit" from those test titles.  Each of the titles should start with "Test X", neatly aligned.  We can discuss how to indicate extra credit in some other snazzy way.

**Comment by MasterOdin** [comment]
Move extra credit to the left of the title bar?
