### ISSUE TITLE
When I use the Plagiarism Detection tool, it always shows that cannot parse value `xxx'

### ISSUE THREAD

**Issue by keithzheng** [Submitty/Submitty#4944]
**Describe the bug**
Accoarding to https://submitty.org/instructor/plagiarism, I run
`/usr/local/submitty/SubmittyAnalysisTools/plagiarism --semester s20 --course cs201 --assignment hm_1 --language java submissions/hm_1`, it always shows that cannot parse value `s20'.

**Expected behavior**
It should do the detection after I run the tool.

**To Reproduce**
1. cd to the directory for the course. 
e.g. `cd /var/local/submitty/courses/s20/cs201/`
2. run the tool.
e.g. `/usr/local/submitty/SubmittyAnalysisTools/plagiarism --semester s20 --course cs201 --assignment hm_1 --language java submissions/hm_1`
3. See error 
`option --semester: cannot parse value `s20'`

**Configuration**
 - OS: MacOS
 - Browser Safari

**Comment by bmcutler** [comment]
Plagiarism is incomplete and not ready for use.
We are hopefully going to make progress on development this term -- we already have a number of more specific open issues.
