### ISSUE TITLE
Undefined index: args 

### ISSUE THREAD

**Issue by halmohri** [Submitty/Submitty#4955]
**Describe the bug**
I did a fresh installation of Submitty following the instructions in https://submitty.org/sysadmin/installation. However, when you load the main webpage, I see this: 

```
Notice: Undefined index: args in /usr/local/submitty/site/app/libraries/ExceptionHandler.php on line 83

Notice: Undefined index: args in /usr/local/submitty/site/app/libraries/ExceptionHandler.php on line 83
Server Error
Oh no! Something irrecoverable has happened...

An exception was thrown. Please contact an administrator about what you were doing that caused this exception.
                  ,--.    ,--.
                 (( O))--(( O))
               ,'_`--'____`--'_`.
              _:  ____________  :_      _____
             | | ||::::::::::|| | |        \ \
             | | ||::::::::::|| | |         \
             | | ||::::::::::|| | |
             |_| |/__________\| |_|
               |________________|
            __..-'            `-..__
         .-| : .----------------. : |-.
       ,\ || | |\______________/| | || /.
      /`.\:| | ||  __  __  __  || | |;/,'\
     :`-._\;.| || '--''--''--' || |,:/_.-':
     |    :  | || .----------. || |  :    |
     |    |  | || '----SSt---' || |  |    |
     |    |  | ||   _   _   _  || |  |    |
     :,--.;  | ||  (_) (_) (_) || |  :,--.;
     (`-'|)  | ||______________|| |  (|`-')
      `--'   | |/______________\| |   `--'
             |____________________|
              `.________________,'
               (_______)(_______)
               (_______)(_______)
               (_______)(_______)
               (_______)(_______)
              |        ||        |
              '--------''--------'
```

**Expected behavior**
I expect to load Submitty and start using it. How could this be fixed?

**To Reproduce**
1. Install Submitty on Ubuntu 18 and Apache using bash ./.setup/install_system.sh. 
2. Install certbot. 
3. Load the page using https. 

**Configuration**
 - OS: ubuntu 18
 - Browser Chrome

**Screenshots**

**Additional context**

**Comment by MasterOdin** [comment]
Whenever an exception gets thrown and prints the generic message (ignoring the undefined `$args` bit), it should write out to a file in `/var/local/submitty/logs/site_errors` which can be used to get more details as to what is throwing the exception. Would you be able to provide the contents of the latest file in that directory here to help with debugging?

**Comment by halmohri** [comment]
OK, here is the error message: 

`Message:
SQLSTATE[08006] [7] FATAL:  password authentication failed for user "submitty"
FATAL:  password authentication failed for user "submitty"

Stack Trace:
#0 /usr/local/submitty/site/app/libraries/Core.php(182): app\libraries\database\AbstractDatabase->connect()
#1 /usr/local/submitty/site/public/index.php(82): app\libraries\Core->loadMasterDatabase()`

**Comment by MasterOdin** [comment]
You should double check the values in `/usr/local/submitty/config/database.json` and that the username and password for DB user matches what you expect and can use with psql to login in as the submitty user.

**Comment by MasterOdin** [comment]
Closing this as nothing to be done on our end here anymore without further follow up from reporter.
