### ISSUE TITLE
Add the body of thread you want to merge into to the merge threads modal

### ISSUE THREAD

**Issue by elihschiff** [Submitty/Submitty#4960]
**What problem are you trying to solve with Submitty**

When merging a thread you only see the title of the thread you want to merge it into which can make it hard to know if you are picking the correct thread

**Describe the way you'd like to solve this problem**

The modal already has plenty of space, I want the body of the currently selected post to be put in the space below the dropdown.
This would be the body of post 12 in this example. Not the body of the post I am trying to merge
![image](https://user-images.githubusercontent.com/18558130/73043020-665e5800-3e31-11ea-830d-6e031f3455b0.png)

**Describe any potential alternatives you'd tried to solve the problem**
I usually open a new tab to find the correct thread

**Additional context**
I was going to try and add this myself but it seems like it could make a good first issue for somebody new to Submitty. If that is in fact not the case I would be happy to add this feature myself.

**Comment by harshagrwl** [comment]
Hey, I would like to work on this issue.

**Comment by adrijshikhar** [comment]
@harshagrwl are you still working on this issue?

**Comment by adrijshikhar** [comment]
@elihschiff i guess @harshagrwl is not working on the issue. should go ahead and start working on the issue?

**Comment by elihschiff** [comment]
@adrijshikhar go for it

(Also me closing the issue and reopening it was a mistake, ignore that.)

**Comment by AngadSethi** [comment]
Hi @elihschiff 
Would something like this work?

![Annotation 2020-03-25 123811](https://user-images.githubusercontent.com/58678541/77510796-95c32c80-6e95-11ea-9fbb-0ac40754adea.png)

Presently, I am implementing this using JSON in which the key is _thread_id_ and the value is the _content_. Also, the markdown is not being rendered.

Is this the correct way to go about it or should I implement is using AJAX, in which case .change() will make an AJAX call?

Regards
Angad Sethi

**Comment by AngadSethi** [comment]
Hi @elihschiff 
Linked a pull request. Please review!

Regards
Angad Sethi
