### ISSUE TITLE
Rainbow Grades Instructor UI # of items in category

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#4961]
Early in the semester, before all gradeables for a category have been created, the configuration might look like this:
<img width="305" alt="Screen Shot 2020-01-24 at 12 04 41 AM" src="https://user-images.githubusercontent.com/5871417/73045746-21d8b980-3e3d-11ea-8008-e028977c0a06.png">

We will have 10 homeworks, but so far we only have created 2 of them.  If homeworks are 50% of the grade, we have only graded 2/10 homeworks, so only 10% of the overall semester grade is available.

It seems to work initially, but when I go back to the UI it resets the first box (items) to 2.  Then the math gets off for rainbow grades.

**Comment by Kevin-MM** [comment]
Will investigate where they category information is being pulled from and adjust as needed.

**Comment by technostarbtd5** [comment]
I've been looking over this issue and I don't see any components of it that haven't been successfully addressed by a pull request. Are we aware of any lingering problems with this issue preventing it from being closed?
