### ISSUE TITLE
Twigjs 1.14.0 Error When Escaping Empty Strings

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#4976]
### The Bug
On Twigjs ```1.14.0```, escaping an empty string returns the string ```[object Object]```. This leads to errors in rubric creation where the empty string is used as the default for many fields.

Possibly related to twigjs/twig.js@895345291304d1b552d4aefb35ce86e906f7b36f or twigjs/twig.js@c426c95816ddb998577a8523263f46fdc85aa5aa.

### To Reproduce:
1. Bump Twigjs to ```1.14.0``` in the ```packages.json```.
2. Add the line ```{{""| e}}``` to any template rendered by Twig.js.

**Comment by MasterOdin** [comment]
Yes, the second of the two commits you linked to was a fix of the JS file that we need to wait on before we upgrade twig.js, alternatively just rip out twig.js and do server-side rendering and be done with this nonsense.

**Comment by MasterOdin** [comment]
Fixed in latest version of twigjs (1.15.0)
