### ISSUE TITLE
VPAT — Stray Closing </main> Tag

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#4999]
As noted in an internal accessibility audit, views have a stray closing `</main>` with no opening tag.  See attached screenshot.

![Screen Shot 2020-01-31 at 8 36 20 PM](https://user-images.githubusercontent.com/12703624/73584873-c1afcc00-4469-11ea-9999-6005e80034a6.png)

**Comment by elihschiff** [comment]
I think that \</main> which comes from [here](https://github.com/Submitty/Submitty/blob/2623546457c2daed816f9ae06de9c82a6bc34c42/site/app/templates/GlobalFooter.twig#L3) in fact does have a opening \<main> tag which comes from [here](https://github.com/Submitty/Submitty/blob/2623546457c2daed816f9ae06de9c82a6bc34c42/site/app/templates/GlobalHeader.twig#L120)

Also, when I inspect the source, on the live Submitty website, with `view-source:https://submitty.cs.rpi.edu/home` I see the opening main tag on line 183 and the closing tag on line 297 although your line number may be different from mine.

**Comment by pbailie** [comment]
I did not find the opening  `<main>` tag when I searched for it.  But as it does exist, I'll close this issue and mark it on the audit as fixed.  Thank you for the help.
