### ISSUE TITLE
Clicking the +/- zoom buttons when grading a pdf does not work

### ISSUE THREAD

**Issue by elihschiff** [Submitty/Submitty#5023]
**Describe the bug**
When you click +/- buttons to zoom in on a pdf it gives an error
![image](https://user-images.githubusercontent.com/18558130/74062499-65dec900-49bc-11ea-901b-594dc7d878d4.png)
It does work if you refresh the page after though

**Expected behavior**

No error it should just zoom in with no page refresh

**To Reproduce**
1. Open an exam with a pdf
2. click the +/- button

**Configuration**
 - OS: [e.g. Windows, Linux, ...]
Arch Linux Firefox

**Screenshots**
![image](https://user-images.githubusercontent.com/18558130/74062575-8dce2c80-49bc-11ea-8c74-36089be8dc39.png)

**Comment by jchulton** [comment]
I am not able to recreate this bug after following these steps:

1. Create an exam gradeable which takes one or more files directly uploaded to Submitty website
2. Have an instructor submit for a student
3. Open that student for grading
4. click +/- button

Works fine, am I missing something?

**Comment by elihschiff** [comment]
I am not sure what the issue is. I just tried it on my vm and it also working find. There must be something specific to the production server or the data structures exam that we were looking at. (There were a number of people with this issue, not just me)

I will see if it is still an issue during the next DS exam and update/close this issue based on if I can figure out more about the bug or if it no longer exists.

**Comment by jchulton** [comment]
I actually had it happen while testing another bug, but idk why it was happeninng then and not before. So it probbably still exists
