### ISSUE TITLE
Bug Fixes / Improvements on Create/Edit Gradeable Page

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#503]
[edited by @bmcutler]

On the page itself:

- [ ] Make upload type default to "Upload Files(s)".  (currently no default)
- [ ] Make box for "path to autograding config" bigger!  since the path is very long.
- [ ] When "Use TA grading" is false, hide the ta grading options: "what is lowest privileged user group", "overall instructions to TA" "who is assigned to grade this", "start date for grading", "release date to students".

- [ ] When editing an existing gradeable, it says "Save Gradeable" at the top and "Edit Gradeable" at the bottom.  Make this consistent.  (probably "save"?)  It correctly says "Add gradeable" at the top & bottom when its a new gradeable.

- [ ] Add an option to "Delete this gradeable" from the "edit gradeable" page.  It should only appear when you are editing an existing gradeable, not when you use that same interface to add a new gradeable.  We expect this to be used rarely.  It should be labeled clearly.  And it should have an "are you sure" confirmation box.

------------
Related to the page:

- [ ] From the top black bar for instructors, make a direct link to the "create a new gradeable" page. 
- [x] Delete the page for "manage gradeables" (functionality on the navigation page)

**Comment by bmcutler** [comment]
I've added more todo items to this issue and re-titled it
