### ISSUE TITLE
Limited Access Graders Cannot View PDFs

### ISSUE THREAD

**Issue by jchulton** [Submitty/Submitty#5032]
**Describe the bug**
A Limited Access Grader cannot view PDFs when grading students in their section, even when gradeable is set to allow limited access graders.

**Expected behavior**
The Limited Access Grader should be able to open and view the PDF as normal

**To Reproduce**
1.  Create a gradeable and minimum grader to limited access grader
2. Submit for a student
3. Attempt to grade as a limited access grader

![image](https://user-images.githubusercontent.com/11095297/74321443-3f1fea00-4d50-11ea-8eb4-380bd7a3c394.png)

**Screenshots**

**Comment by elihschiff** [comment]
@jchulton it looks like #5032 solved this issue. Is there a reason why this issue is still open or did you just forget to close it?
