### ISSUE TITLE
VPAT — Tab Order In Discussion Forum Does Not Flow Naturally

### ISSUE THREAD

**Issue by pbailie** [Submitty/Submitty#5039]
`[TAB]` key order does not flow naturally in the discussion forum.

* On top row, `[TAB]` focuses on `Create Thread` before `More`.
* Some elements do not receive focus via `[TAB]`.

Please note that `tabindex` property should not be used to correct `[TAB]` key focus order.  Element ordering must flow naturally by its inclusion in code.

**Comment by elihschiff** [comment]
It looks like this issue might be partially or fully solved by #4899 (once it is merged)

**Comment by elihschiff** [comment]
@pbailie #4899 has been merged which added tabindex to more stuff on the forum including the more button, can you take another look and see if this fixes the issue or if there is something else that is still broken?
