### ISSUE TITLE
Slack channel link is not found.

### ISSUE THREAD

**Issue by aashimgarg** [Submitty/Submitty#5044]
as the slack channel is not found i want to ask that is this organization participating in gsoc2020.
![Screenshot from 2020-02-14 12-44-20](https://user-images.githubusercontent.com/55639487/74509630-0470aa00-4f28-11ea-9caa-61813f495a72.png)

**Comment by bmcutler** [comment]
I'm not sure what url/link you followed, but this page contains the slack invite:
https://submitty.org/contact
