### ISSUE TITLE
Queue sound effects

### ISSUE THREAD

**Issue by matgar1997** [Submitty/Submitty#5052]
**What problem are you trying to solve with Submitty**
Make it easier for a grader with submitty running in the background to be notified
something changed in the queue

**Describe the way you'd like to solve this problem**
Similar to an option button for sound on/off just like a button to turn
on and off auto-refresh

**Additional context**
This feature was requested when the queue was presented at the CS 1 staff meeting

**Comment by elihschiff** [comment]
Having sound effects built into Submitty seem lake a strange addition to me. How about a notification?  The user could then set up sounds on their own device.

https://developer.mozilla.org/en-US/docs/Web/API/notification
