### ISSUE TITLE
Alphabetical sort in forum vs. Text/Numeric gradeable sort

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5053]
**Describe the bug**
Sorting the discussion forum alphabetically does not match the by section then alpha by username(?) sort used in the text/numeric gradeable.  

**Expected behavior**
If the instructor wants to grade posts in the discussion forum using a numeric gradeable, it is most convenient to have these sort orders match.

If the course has multiple sections, this will require lots of scrolling.  Also since we sort by username in one place and (preferred?) last name in the other, there will be differences.

Easiest thing to do is modify the forum alphabetical sort to match numeric.  Ideally use the same function.  We are doing this sort in multiple places, let's make sure we're not duplicating code.

**Comment by InfiniteVerma** [comment]
I'll like to work on this.

**Comment by ankurshr01** [comment]
Can i work on this?
