### ISSUE TITLE
Add primary keys to tables missing them

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#507]
Tables:
* electronic_gradeable
* grading_rotating
* late_days_used

**Comment by JerameyATyler** [comment]
The following three commands will need to be ran on each course's database.

ALTER TABLE electronic_gradeable
    ADD CONSTRAINT electronic_gradeable_g_id_pkey PRIMARY KEY (g_id);

ALTER TABLE grading_rotating
    ADD CONSTRAINT grading_rotating_pkey PRIMARY KEY (g_id, user_id, sections_rotating);

ALTER TABLE late_days_used
    ADD CONSTRAINT late_days_used_pkey PRIMARY KEY (user_id, g_id);
