### ISSUE TITLE
There should be a "Help" link on most pages

### ISSUE THREAD

**Issue by laprej** [Submitty/Submitty#511]
None of the pages I have come across have any "Help" links / buttons available.  For the moment it would be enough to link to the wiki or specific sub-pages in the wiki.

**Comment by MasterOdin** [comment]
Related to #261

**Comment by bmcutler** [comment]
Hey Justin @laprej 

I've added links from the Create/Edit Gradeable page to the appropriate parts of the wiki (also updated a bit).  Let me know what you think.
(it's live, and in branch "instructor_useability")

Still need to entirely create documentation on config.json
