### ISSUE TITLE
pdf rotation cookie from TA grading impacts student view

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5122]
**Describe the bug**
If I'm a grader in course A, and I use the TA grading interface to view and grade and annotate PDF files.  If the last time I used the TA grading interface I rotated a pdf, that setting is saved in a cookie.

If I'm just a student in course B, and I view the annotations on a pdf I've submitted for that course, the cookie setting for TA grading seems to carry over into the viewer.  from the student side I cannot control this rotation setting.

**Expected behavior**
Either introduce the rotation option on the student view of annotated PDFs, or just ignore the cookie setting for rotation and don't let it rotate the student view

**Comment by adityaketkar** [comment]
@bmcutler can I take this one up?

**Comment by MasterOdin** [comment]
This is true for both zoom and rotation, and that it carries across all annotated PDFs. So it is true that grader in course A will load a PDF, set the rotation and zoom, and then if they switch courses and open a PDF in course B, they will see the same rotation and zoom.

@bmcutler What is the desired behavior for loading PDFs and the persistence of zoom and rotation for all cases. Is it unique per PDF, or unique per similarly named PDFs in a given gradeable, or persist for all grading, but not for student viewing?

**Comment by shailpatels** [comment]
I think storing the value in session storage could work for this case. Thats how the options are stored for the bulk upload settings so the user will see the same options set while they are logged into the same browser but if once they leave their session the settings are lost.

**Comment by MasterOdin** [comment]
I am not sure moving it from local storage to session storage would fix the issues above, unless we're mandating a user completely close their browser between viewing PDFs in different courses, gradeables, etc.

**Comment by shailpatels** [comment]
Oh my bad, yes your right that wouldn't solve the issue of resetting between PDFs, I was thinking a user would want the same settings for viewing a pdf across a session but I can see the use case of not doing that, but thats not directly related to this issue now that I'm reading it over again.

**Comment by bmcutler** [comment]
@MasterOdin 

While within the TA grading pages, it is likely quite convenient to preserve the rotation.  E.g., if I'm grading a stack of landscape mode exam pages for many students.  

I don't think it's necessary to worry about what happens when I move to another computer/browser, it's 'ok' if I have to apply (or undo) the rotation again to continue with my grading.  I don't think it's necessary to worry about what happens if I move to another gradeable or course.  It's ok, and intuitive for me as a grader to understand that I have to unrotate.  The UI is right there.

What is problematic and unintuitive is to view the student facing version which does not have the controls (and I argue doesn't need the controls, it's just clutter.). I think the simplest thing is to ignore the previous cookie settings for rotation on the student facing viewer.  If it can possibly be that simple.
