### ISSUE TITLE
Attribute A not allowed on element B at this point, on the forum

### ISSUE THREAD

**Issue by elihschiff** [Submitty/Submitty#5131]
**Describe the bug**

The forum has a number of instances of "Attribute A not allowed on element B at this point" 
![image](https://user-images.githubusercontent.com/18558130/75920879-3346b580-5e2e-11ea-917c-13aa1209a06f.png)

**Expected behavior**

You should switch them to data attributes
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**To Reproduce**
1. Open forum
2. Save page as html
3. Upload html to https://validator.w3.org/#validate_by_upload

**Additional context**

I did fix some of them in #5123 so you might want to wait for that to be merged or base your branch off that one so you do not duplicate work.

**Comment by bmcutler** [comment]
@elihschiff @shwehtom89 Can we closet this issue now?
