### ISSUE TITLE
Spaces in text for numeric text gradeable

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5181]
Something has changed since I last did numeric text data entry several weeks ago.

When doing data entry and typing in a "text" box for a specific student each time I press space, the cell contents get highlighted/selected, so the next character a I type overwrites the contents of the entire box.  

This is on Mac Chrome.  Not sure if it happens on other browsers/OS.

**Comment by elihschiff** [comment]
I am not super familiar with the instructor parts of the website. What page(s) do you mean when you say data entry

**Comment by bmcutler** [comment]
The "Grading Test" gradeable in the sample course is a numeric/text gradeable.
Although it might only have numeric fields by default.
Sorry my vagrant is dead right now.  I'm re-vagrant up'ing right now

https://submitty.org/grader#ta-grading-of-non-electronic-assignments, the column that says "Text 1"

**Comment by elihschiff** [comment]
oops looks like this bug was my bad :cry:
