### ISSUE TITLE
Failure to save marks in open component when we jump back to index page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5190]
**Describe the bug**
When we are TA grading with a complex gradeable.
We have a specific component open for a specific student,
We select a couple marks for that component, but don't press "save"...
Then we press the house icon button to jump to the index of all students.
It does not save the marks for that last open, unsaved component.

**Expected behavior**
In other cases, the components for the open component ARE saved.
E.g., If we press the left or right arrows to go to the next or prev student.

**Comment by Architjain12** [comment]
When you press back or next or home, we will display an Alert box, that marks you entered did't saved.
Because, directly saving the marks at input is not good.

**Comment by bmcutler** [comment]
NOTE:  When debugging/testing/reviewing this issue, be sure to test all browsers (Firefox/Chrome/Safari) and all OS (Windows/Linux/Mac).  Not sure it currently behaves the same in all situations.
