### ISSUE TITLE
Determine proper handling of peer re-assignment

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#5195]
At present, if you reassign peers after grading begins, prior grading persists and cannot be removed.
For example if student A is assigned as student B's peer, they can grade normally. However, if student A is then unassigned, their grading persists, and still counts towards student B's score. This can be problematic in the case of version conflicts, which can no longer be resolved due to the reassignment.

**Comment by bmcutler** [comment]
@emaicus I propose that we just keep and display all peer grades in the system, even if the assignment changes.

When we calculate the students grade, we scrape the database for marks and average them.

When we display the peer marks to the instructor and to the student, we display all marks.

The only thing the matrix does is grant access for the peer to the students work.  So if we delete all assignments from the peer matrix, peers can't access any work, but the scores remain.  This might even be a "feature".  If you want to make sure peers don't edit anything, or even view files, just delete their assignments.

If an instructor wants to delete/erase marks from a specific peer, they can do that with #5368.
