### ISSUE TITLE
Queue position & star status

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5221]
**What problem are you trying to solve with Submitty**
Students in the queue currently don't know anything about their 'star/halfstar' status.

**Describe the way you'd like to solve this problem**
Let's add information messages:

Sample text if you have a full star:

There are currently 25 people ahead of you in the queue.  
Because you have not yet been helped through this queue during the last week, you may be prioritized.
There are currently 3 people ahead of you in the queue who have not yet been helped in the last week, and 4 additional people ahead of you in the queue who have not yet been helped today.

Sample text if you have a half star:

There are currently 5 people ahead of you in the queue.  
Because you have not yet been helped through this queue today, you may be prioritized.
There are currently 10 people in the queue who have not been helped in the last week (they may be prioritized over you), and 2 people ahead of you in the queue who have not yet been helped today.

Sample text if you have no star:

There are currently 3 people ahead of you in the queue.  
However, because you have been helped through this queue today, you may be de-prioritized.
There are currently 10 people in the queue who have not yet been helped in the last week, and 7 additional people in the queue who have not yet been helped today.

Please suggest tweaks to text.

ALSO...  let's maybe add text to suggest students periodically manually refresh the page to update this information.

**Comment by elihschiff** [comment]
I can pretty easily add an auto refresh that happens say every min in the background to the student page. I think that might be a better solution to that problem

**Comment by bmcutler** [comment]
My concern for a refresh is that we refresh a page that has unsaved data and we lose that data.
We are only talking about refreshing the "you are in the queue" page.  Not the "here's where you enter the queue" page?  Because if a student has selected the queue, typed in the code, and is trying to find their webex personal room URL...  then the page refreshes and they lose the code.  That would be annoyng!
