### ISSUE TITLE
TA grading & active version & graded version

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#523]
- [x] When a TA opens a homework for grading, the current "active_version" should be displayed prominently somewhere on the UI. **ASAP**
- [x] When a TA hits the submit button (or save) we should record what is currently marked active and store this in the database as the "graded_version". **ASAP**
- [ ] TAs should be able to review all submissions (not just active) with a drop down selection.  When they choose a different version, the grading results (diff views) and the file browser switches to the other version.  
- [ ] When viewing something not active, an obvious banner of "not the active version" (or similar) is displayed and the grading rubric is greyed out/disabled.
- [ ] If the TA realizes the student has the wrong version marked active, the TA may change this with a button.  This action writes to the user_assignments_settings.json file (and the history, and we add a TA changed field to the history as well), so students see this active version change too.
- [ ] If the TAs revisits the grading page to regrade something and the current active version does not match the graded version, this is visually clear to the TA and they can choose to grade the now marked active version or retain the previous graded version.  (UI design to be decided).
- [ ] When we generate grade summaries for a TA graded item, we grab the TA assigned points from the database, and grab the "graded_version" from the database, go to the autograding file from the graded_version and grab those autograding points.  **ASAP**
- [ ] When we generate grade summaries for a autograding only item, we grab the autograding points for the version currently marked active...  If the active version is late, the student gets a zero.  If the active version is before the deadline, they get those points.  **ASAP**

LOW PRIORITY TODO:  What is a autograding-only item allows late days.  Ugh.  Assume autograding-only does not allow late days and make a new issue for that when these other items are finished.

**Comment by JerameyATyler** [comment]
The database table gradeable_data has a column called gd_active_version already so no database changes would be required. If we want to keep a history of the ta regrades in the database we can talk about what would be needed.
