### ISSUE TITLE
Edit User/Student bug

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5232]
**Describe the bug**
When an instructor clicks the first time on the pencil icon next to an existing student on the manage students page, the data loads ok.  But if they press "cancel" (even without editing anything) they get a popup error "warning changes will be lost".  

The second (and future times) they click on the pencil icon next to a student from this page the data does not load correctly, some is missing / incorrect.

This might be related to PR #4996 ?  Or PR #5152 ?  Or something else?

**Comment by bmcutler** [comment]
@mukul-kmr-jha @elihschiff 
Can you look into this error?

reported by @holzbh

**Comment by mukul-kmr-jha** [comment]
sorry for this bug (result of #4996 ) :(
