### ISSUE TITLE
Peer graders cannot view upload.pdf

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5234]
**Describe the bug**

When an assigned peer clicks on upload.pdf (a bulk pdf) or perhaps any pdf(?)
they get a permission error.

This happens either when viewing within the submission frame or when using the "popout" to a separate window.

**Other notes**

The peer grader is able to download the zip of the assignment and the upload.pdf file is included.

The peer grader is able to view the names of the files in the results folder, but gets a permission error on all of those files.  Did we make a decision about whether any of these files were important for grading.  I'm not sure.  I think perhaps we should just be hiding all files in the results folder and not including them in the downloaded zip.

**Comment by bmcutler** [comment]
Oh, also when this file permission error happens for upload.pdf it might corrupt the rubric panel of TA grading?

**Comment by jchulton** [comment]
Not sure about the rubric corruption, but the inability to view a pdf is addressed in PR #5253
