### ISSUE TITLE
late days student has error when we have no gradeables

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#526]
Looks like retrieve_newest_gradeable_id_from_db( ) is failing?

We cannot add any late day exceptions when we have no gradeables, but we shouldn't get an error.

**Comment by MasterOdin** [comment]
I'm guessing (without serious examination of code) that https://github.com/Submitty/Submitty/blob/master/TAGradingServer/account/admin-latedays-exceptions.php#L414-L442 should just output "no gradeables" if `$g_id` or `$db_data` is empty and not the form. Of course we probably want to wrap https://github.com/Submitty/Submitty/blob/master/TAGradingServer/account/admin-latedays-exceptions.php#L203 with a "if isset else return null" type statement.

**Comment by bmcutler** [comment]
Closed in #844
