### ISSUE TITLE
[Security Bug] Open Redirection Vulnerability at Login Page

### ISSUE THREAD

**Issue by humblelad** [Submitty/Submitty#5265]
**Describe the bug**
It is possible to redirect a user to an attacker owned domain and trick the user. I am investigating on the potential chaining of this bug to perform other attacks.

**Expected behavior**
Redirection to external urls must not be allowed.

**To Reproduce**
This occurs at the  main login page when the user enters an invalid username/password.
The url gets changed to 
`http://localhost:1501/authentication/login?old=http%3A%2F%2Flocalhost%3A1501%2Fhome`
An attacker can change the url(to any attacker owned domain which may mimic submitty interface) to something like 
`localhost:1501/authentication/login?old=http%3A%2F%2Flgoogle.com` 
and trick redirection to google.com  users after they enter their creds.

**Additional context**
This can be prevented either by-
1. Adding regex checks on url and whitelisting the url.
2. Completely removing GET request based url redirection. 

I am trying to fix this but thought to create this issue for others to contribute the fix if interested.

**Comment by MasterOdin** [comment]
I think we can just insert something like:
```php
        if (!Utils::startsWith($old, $this->core->getConfig()->getBaseUrl())) {
            $old = null;
        }
```
at https://github.com/Submitty/Submitty/blob/master/site/app/controllers/AuthenticationController.php#L75 and https://github.com/Submitty/Submitty/blob/master/site/app/controllers/AuthenticationController.php#L95 as I would like to retain the behavior of redirecting the user after they login, and without making it complicated to copy/paste a URL if need be.

**Comment by humblelad** [comment]
ok if that works. :) ILYK for any bypasses.

**Comment by elihschiff** [comment]
Is there ever a time when we want the php to redirect users to external websites? It seems like automatically redirecting users to external websites is a bad idea anyway. There might be some way in the future where somebody finds a different way to redirect users to an external domain (other than on login) and only putting the check in the login code would not stop that. If we do want to have the ability to allow redirecting to external websites then we don't have a choice, but if we don't ever want to redirect users to external websites, I think it might be better to add that check here which will stop all redirects.
https://github.com/Submitty/Submitty/blob/1acccad70b6265bb6706dba5511a399b94bc57b2/site/app/libraries/Core.php#L531

I can even have it thrown an exception so if a future developer tries an external redirect, it will let them know.
