### ISSUE TITLE
Sidebar clickable region is obstructed by main content

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#5269]
**Describe the bug**
Part of the region on the side bar that can be clicked to navigate to the link is obstructed by the contents of the page (see picture).  This isn't a big deal when the sidebar isn't collapsed, but when it is, it makes the clickable region nearly half the size.

**Expected behavior**
The entire side-bar region should be clickable, in collapsed or expanded form.

**To Reproduce**
Open submitty in a window narrow enough to view the collapsed side-bar and try to click on the right half of an icon.

**Configuration**
 - OS: Linux
 - Browser Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/3719964/79798299-cc6e5480-8326-11ea-818f-ad8cd8b0d7d6.png)

The easiest fix would be to increase the side-bar z-index, but I don't know if that would be the preferred fix.

**Comment by bmcutler** [comment]
Thanks @KevinMackenzie 
I noticed when I was grading this weekend and almost made an issue.  
@elihschiff Perhaps this is a recently introduced bug?
