### ISSUE TITLE
Implement security.txt for Submitty

### ISSUE THREAD

**Issue by humblelad** [Submitty/Submitty#5279]
**security.txt**
Many tech orgs including Google have started to use security.txt for helping security researchers to easily find and report bugs; similar to robots.txt

Pl refer https://github.com/securitytxt/security-txt and https://securitytxt.org/ .

I have made a sample security.txt and it can be setup as submitty.org/security.txt

```
# Please send vulns here
Contact: submitty-admin@googlegroups.com

Preferred-Language: English

# Our policy
Policy: https://github.com/Submitty/Submitty/blob/master/VULNERABILITY_DISCLOSURE_POLICY.md

# Our Security Hall of fame
https://github.com/Submitty/Submitty/blob/master/AUTHORS.md 
```

**Comment by humblelad** [comment]
Seems like this may not be of interest. But it would have been really great if we did it according to current security standards. I will close the issue if it's not of relevance here.

**Comment by MasterOdin** [comment]
Feel free to submit a PR to https://github.com/Submitty/submitty.github.io. I agree that would be good to have this if it's something that's increasingly expected to have to follow in other well-known organizations.
