### ISSUE TITLE
Support Random Problem Selection in Notebook Gradeables

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#5283]
**What problem are you trying to solve with Submitty**
Notebook gradeables should support randomization of problems through the syntax started in #5246. 

**Describe the way you'd like to solve this problem**

- [x] Clean up JSON example
- [x] Make the global `item_pool` distinct by changing the per-`item` `item_pool` to `from_pool`
- [x] Get the build script to validate the configuration and pass it to PHP-land
- [x] Get PHP to support randomization by generating a hash using semester, user ID, optional `item_label`, etc.
- [x] Get the HomeworkView / SubmitBox to show the randomized problems
- [x] Make submission write a new per-submission hidden file that stores the `item_pool` `item_name`s that were selected, as well as the hash that was selected at randomization time
- [ ] Make sure that if an answer-file exists in the active version for a given item, display it (show student's previous answer), otherwise, don't load answer file.
- [ ] Test that validation uses the correct items
- [ ] Autograding also needs to work with the randomization - autograder will probably need to parse the hidden per-submission file. (Preferred over having the hashing done multiple places).
- [ ] Test that this also works with teams
- [ ] Test that backwards compatibility with existing notebook gradeables is supported

** Reach goals (for later issues) **
- [ ] Validate that every item's output file has a unique filename
- [ ] Render Notebook in TA grading interface
- [ ] Have a way to force viewing with a particular hash (instructor only)

**Comment by bmcutler** [comment]
I believe the bulk of these items are finished...  finished with PR #5927
