### ISSUE TITLE
Rollback on notebook gradeable buggy

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5288]
**Describe the bug**
If you select a prior version of a gradeable from the dropdown, it displays the autograding results from the prior version correctly, but it still shows the data (e.g., multiple choice selections) from the most recent submission.

**Comment by Kevin-MM** [comment]
As discussed, the PR for this issue will include a 3rd button for each notebook gradeable cell which allows the user to select between 'clear', 'selected version', 'recent version'.

**Comment by bmcutler** [comment]
Related to #6080
