### ISSUE TITLE
Create installation script for Ubuntu 20.04

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#5292]
Now that Ubuntu 20.04 LTS has been released, we should develop the necessary installation script for it. The steps for this are roughly:

* Create folder under `.setup/distro_setup/ubuntu` with `setup_distro.sh` file
* Create vagrant specification for Ubuntu 20.04
* Run `tests/integrationTests` from within Vagrant

At some undetermined point in the future, we will switch Ubuntu 18.04 to Ubuntu 20.04 as default VM for vagrant, but that will likely be a separate issue than this.

**Comment by bmcutler** [comment]
@MasterOdin Can we close this now?
