### ISSUE TITLE
Investigate migrating from Travis to GitHub actions

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#5305]
With GitHub actions being out of beta, and being relatively nice, we should work to convert our various pipelines from Travis to GitHub. This would give us better throughput of testing (as there's far higher concurrent job running, can run tests for longer, etc.) and is overall a nice thing. In this trial evaluation of it, we should focus on just moving the smaller, totally self-contained repos before attempting to tackle Submitty proper). The three repos I would like to target are:

- [x] submitty-php-codesniffer
- [ ] pdf-annotate.js
- [x] submitty.github.io
- [x] api.submitty.org

**Comment by bmcutler** [comment]
Looks like this issue is now complete...
