### ISSUE TITLE
Fix building random input/generated output assignments from the web GUI

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#5308]
Expected files do not appear to be properly generated when building assignments via the web GUI. Investigate and fix this bug.

**Comment by bmcutler** [comment]
This feature is probably not well documented, but here is the GSOC report
https://submitty.org/developer/google_summer_of_code/2019_DrumilPatel

We likely need more automated testing as well.

**Comment by poorna2152** [comment]
@bmcutler 
I added [python_random_input_output](https://github.com/Submitty/Submitty/tree/main/more_autograding_examples/python_random_input_output) example in `more_autograding_examples` folder as a gradeable and tried to do a submission there. I got the following error when the submission was autograded. Is this the bug described here. I didn't get a complete idea of the bug from the issue description.

![Screenshot from 2022-07-12 18-51-42](https://user-images.githubusercontent.com/58025190/178500239-2de82704-e81e-4fd0-8d22-51cd9e26d8f1.png)
