### ISSUE TITLE
More Student Info:  Local Time Zone & Student Photo

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5318]
**What problem are you trying to solve with Submitty**

1) For online classes, it can be helpful to know the student's current local time zone (so TA can know what contact hours are convenient for office hours, or instructor can schedule synchronous exams, etc.)

2) Instructors (or sysadmins) can upload photos of every user.  Currently we do this from freshman student IDs.  These photos can be quite out of date for senior students.  And the photos are not available for all students.  It would be nice to allow students to upload their own photo.  (Making clear this should be a recognizable passport style photo of themselves, not an avatar, etc.)

**Describe the way you'd like to solve this problem**

- [x] Let's add timezone to the users table, default to server timezone.

- [x] Display and allow users to edit their timezone on the "About Me" page.

- [x] Allow instructors to view the students timezone from the Manage Students page (either in a column, or just in the modal popup?

- [x] From the users "About Me" page, show the currently uploaded student photo, and allow users upload their own photo to be used instead.  Store that photo somewhere (don't overwrite the sysadmin/instructor uploaded version).  

- [x] When displaying the "View Student Photos" page, use the student uploaded one if available, then the sysadmin/instructor uploaded version.

- [x] Allow instructor/sysadmin to indicate that the student uploaded version is not sufficient -- and the instructor/sysadmin version should be used instead. [design discussion needed]

Note: We could eventually get fancy and display due dates & other dates on the gradeable screen in the users specified time zone.

**Comment by bmcutler** [comment]
tangentially related to issue #1865

**Comment by bmcutler** [comment]
And also issue #5170

**Comment by MasterOdin** [comment]
From slack, as we want to move towards displaying things in student's specified timezone, it should be accomplished by first using Twig to display all dates (instead of formatting them in PHP) and then we can just set `$twig->getExtension(\Twig\Extension\CoreExtension::class)->setTimezone($user->getTimezone());` and Twig will handle converting timezones for us on displaying them.
