### ISSUE TITLE
Improve UI for SVN grading request

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#532]
Currently:  
- Hitting "Grade SVN" at time X counts as a submission at time X, and we find and grade the most recent SVN commit (with timestamp <= X).  
- If you commit at 11:55pm, and hit the Grade SVN button at 12:05am, you'll be charged 1 late day.  \* It's not possible to request that earlier commits are graded.  
- It might be confusing to users that they have SVN commit numbers vs. Submitty version numbers.

Proposed new UI:  
- We display one or more SVN commit timestamps (all of them?  The most recent one?  All commits within the last 24 hours?)  Question:  How do we efficiently get the history of SVN commits?  Does the hwphp user have access to svn (I don't think so)?
- There's a button next to each commit that has not previously been submitted for grading.  When you push that button we grade it, and the time of that commit (the commit is on the SVN central server) is the grading timestamp.  (So you can request grading of something after the deadline, as long as you committed it to the server before the deadline).
- Figure out the UI design so that things are clearly labeled with the SVN commit numbers  (and also the Submitty version number?).

NOTE:  We don't want to grade every commit.  That might put a big load on the server, and we want to discourage excessive grading submissions or using the server for primary debugging.  (But we want to allow/encourage frequent commits for backup/recording progress/etc).

**Comment by MasterOdin** [comment]
We should also consider how we might apply this to if we were using Github (or some other repo service) to host code instead of internally (and not through SVN) before potentially making a very specific version control UI.

**Comment by bmcutler** [comment]
Make sure autograding result for an SVN submission clearly shows the timestamp
(from issue #189)
