### ISSUE TITLE
Automatically add Testcase limiting number of submissions

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#534]
With a large # of allowed submissions (20?)
Before a small point deduction is applied (-0.1)

**Comment by MasterOdin** [comment]
I disagree with anything being done "automatically" unless there's some flag or something explicitly stating to do this (and requiring the instructor to do this). There shouldn't be any surprises for a user that hasn't read all the documentation.

**Comment by bmcutler** [comment]
fixed in PR #581
