### ISSUE TITLE
Use Submitty/Herald for all repos in Submitty 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5357]
For example, generate basic release notes for Submitty/Lichen, etc.  Not just Submitty/Submitty.

Additional command line argument?  Or detect current working directory directory?

It may or may not make sense to have all the same categories... 
security, bugfix, feature, VPAT, etc.

**Comment by MasterOdin** [comment]
I like the idea of running it against the current directory best, as it also allows this to be more general purpose of a tool than potentially just "only works for Submitty". Usage though does get a bit funny as I guess you'd be doing `python3 ../herald/herald.py` which seems ugly. Could install it as a binary file, but I'm not sure what your feelings on that are (e.g. `pip3 install herald`) and then you'd get `herald` on the commandline? Though, at that point, might rewrite it into typescript as I vastly prefer their global installation story to python's.

**Comment by MasterOdin** [comment]
@bmcutler the big question I have, would you be alright with modifying the set-up step of herald to be from:

```bash
git clone https://github.com/Submitty/herald
pip3 install -r requirements.txt
```

to:

```bash
npm install -g @submitty/herald
```

and then running it would change from:

```bash
# inside the herald directory
python3 herald.py
```

to be:
```
# in any Submitty repository folder
herald
```

**Comment by bmcutler** [comment]
This won't be run by the average submitty contributer, only those of us with admin access.
Yes, I'm fine with adding a few more steps to the installation process.

**Comment by bmcutler** [comment]
closed!  Thanks @MasterOdin!
