### ISSUE TITLE
full access grader & limited access grader can be assigned to one or more registration sections

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#537]
Hi Peter,

One more thing for the "Manage Users" form (I renamed and reorganized the pages a bit..  the file name may still be something else).    This change is because we are expanding the use of this page from adding students to adding any type of user including students.

Students (=4) should be in exactly 1 registration section (or no sections, section=NULL if they drop).

Limited Access (=3) and Full Access graders (=2) can be assiged to 0, 1, 2, or more registration sections.

Instructors should be assigned/placed in all registration sections.

Barb

**Comment by bmcutler** [comment]
On the manage user form, "Student" should be the default for user group.

At todays meeting we decided that when a non student user is selected, we will show checkboxes for each registration section.

**Comment by MasterOdin** [comment]
There should be some clarification of terms here. 

Students are assigned to a registration section via the registration_section column in the users table. This can be null if the student has dropped the course (or is an instructor/ta/grader account).

Graders (Instructers, TAs, etc.) are "assigned" a registration section by adding rows to the grading_registration table per assigned section. Changing their value on the registration_section column will have no effect on who they're assigned to grade (and will probably just mess things up in the long run).

**Comment by bmcutler** [comment]
open item after merging #539 

TO DO: Disable ("gray out") Assigned Sections checkbox group when user group selectbox has Instructor or Student (not grader) selected. For now, user group is validated so that sections can only be assigned to graders. Also, students are forced to have no assigned sections by removing any existing rows in the database's grading_registration table. e.g. a user is erroneously added as a grader with assigned sections, but is later correctly updated to be a student -- their assigned sections are automatically removed.
