### ISSUE TITLE
Options for preparing the Peer Matrix

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5370]
Tackle this after finishing #5369 

Currently the only method to indicate which peer should grade which student is to upload a .csv file.  This works ok, and should remain an option.  But let's add more.

On the (soon to be created) "Peer Matrix" tab there will be a button 
"Upload / Generate Peer Matrix".  Below that button we display the current contents of the peer matrix & the ability to manually edit data in the matrix through the web UI #5364 

When the user presses the "Upload / Generate Peer Matrix" we get a modal with the following options:

* Generate random assignments:  All students in non null registration sections will be assigned to grade XX random students

   - [ ] restrict assignments to other students in the same registration section
   - [ ] exclude these registration sections:  checkbox list, (similar to manage sections / rotating sections)

* All students grade all assignments

* Upload new CSV matrix: Any existing peer grading matrix is replaced by this information

* Append new CSV matrix: Any existing peer grading is merged with the newly uploaded information.

* Clear peer grading matrix

**Comment by josharsh** [comment]
Closed by:
https://github.com/Submitty/Submitty/pull/5425
and 
https://github.com/Submitty/Submitty/pull/5416

**Comment by bmcutler** [comment]
Re-opening this issue.  

The functionality of randomized assignments is implemented & closed by the noted PRs, but the UI & set of requested options is incomplete.  We've revised the interface to be a tab instead of a popup/modal.  but we'd still like to provide several radio buttons/checkboxes of options.

One additional instructor requested feature...  only include people who have submitted to this gradeable (but not cancelled their submission) to this gradeable in the peer matrix assignment.   There may be 100 students in the class, but if 10 of them did not submit (they may have dropped the class), they should not be included in the peer matrix -- they should not be assigned to grade, and they should not receive a grade from their peers.
