### ISSUE TITLE
URL to external resource can be a "course material"

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5384]
**What problem are you trying to solve with Submitty**
Currently, course materials are files hosted on Submitty.  Instructors would also like to direct students to files/resources stored on external servers.  For example, posting a URL to a lecture video hosted on YouTube.

**Describe the way you'd like to solve this problem**
Allow the instructor to specific a "link" instead of a file that contains 2 fields: "url" and "title".  The link can be released on a specific date just like files.

**Comment by bmcutler** [comment]
@elihschiff 
Did you already start working on this issue?
Or do you have any more design notes?

**Comment by elihschiff** [comment]
I forgot I started working on this. I was pretty far along but got distracted having to work on other stuff. I will try and finish this up in the next day or so
