### ISSUE TITLE
Move /{_semester}/{_course}/ endpoints under /courses top-level

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#5388]
The current resource list for resolving a URL request looks something like:

* /authentication/login
* /current_user/change_password
* /api/courses
* /home/courses
* /{_semester}/{_course}
* /{_semester}/{_course}/office_hours_queue
* etc.

To support the first group of things that are not under a course, we need a couple of things to happen right now:
* must have a name that starts before `MiscController.php`
* cannot be in a sub-folder
* must be added as a special case in the WebRouter for authentication stuff

While the design made sense at first (as we only had one top-level page), as we expand to more things (like #5337 and #5353), dealing with the above is increasingly going to be a pain, regardless of documentation.

I'd like to propose to move all existing `/{_semester}/{_course}` endpoints under a top-level `/course` value. This would resolve any issues of the above, and make it easy to do the right thing with regards to routing.

The con would be that most URLs in the system would be a bit longer and break any previous links. I'm not sure how much people are using past course links after a semester ends, but should aim to do this between spring and fall semesters.

**Comment by MasterOdin** [comment]
Thoughts @bmcutler and @emaicus?

**Comment by bmcutler** [comment]
/course or /courses?
(I'd have a slight preference for /courses)

I'm ok with the change.
I'm not worried about bookmarks people may have for past terms.  
An invalid bookmark/url just goes to the main screen (after login) 
where you can pick the course, right?

**Comment by MasterOdin** [comment]
`/course` would be more idiomatic to how things are normally done as use `/courses` when you want to get all courses, and `/course/{_semester}/{_course}` when you want to get one course.

**Comment by bmcutler** [comment]
I suggest /courses because of 
/var/local/submitty/courses/s20/csciXXXX
is similar to 
https://submitty.XX.edu/courses/s20/csciXXX

**Comment by MasterOdin** [comment]
I'm not overly committed, and so will just go with `/courses`. I'm just happy to simplify the router logic. :)
