### ISSUE TITLE
forum error when undo-ing attempt to attach incorrect file format

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5390]
**Describe the bug**

bug report from instructor:

1. Start writing a message (mine was a response to a thread created by the student earlier)
2. Attempt to upload an attachment of the incorrect type which makes Submitty reject it. (I did it twice trying to change file extension but it also didn't work.)
3. Attempt to Submit the message and get an error message saying that attachments are invalid. (As a side note, this part was completely counter intuitive for me. Submitty keeps the attachment listed below the message, although it shows it in red hinting that it is invalid. To me it doesn't make a lot of sense because if Submitty rejects my attachments why does it still keep it forcing me to manually hit the trash can button before a message can be submitted?)
4. Delete all bad attachments by clicking the trash can button.
5. Attempt to hit the submit button again and get stuck. Submitty is "submitting" the post for a long time already. It is not clear if it got submitted or not, and I am afraid to hit Refresh to lose my message. The "Submitting post" button is grayed out, so I can't click it again.

**Comment by marwanatef2** [comment]
this happens if you uploaded more than 5 images (accepted type files) and attempt to submit the post as well, @jportorreal00 could you address this issue in your PR instead of opening another issue for the same problem?
