### ISSUE TITLE
Max allowed size of student output vs. expected output & resulting diff

### ISSUE THREAD

**Issue by kmcnellis** [Submitty/Submitty#54]

**Comment by sihsob** [comment]
Need testing

**Comment by bmcutler** [comment]
Determine critical sizes of 
  - student output (# of chars or # of lines)
  - expected output  (# of chars or # of lines)
  - myers diff output (diff.json)  (size of blob/# of chars, # of blobs)

That cause bugs/poor performance of validator:
  - validator runs too slowly (myers diff is an O(n^2) or worse alg?)
  - diff output is too big and hits file size limit for this assignment

That cause bugs/poor performance of student submission and/or ta grading webpages:
  - page freezes (may depend on browser)
  - very slow loading
  - weird/confusing rendering/interaractive behavior

Prevent this problem by:
  - don't run myers diff on big files (there is already an arbitrary file size, properly determine a reasonable threshhold).  Proper error/warning message needed.  Reasonable substitute grade needed.
  - webpage should not try to visualize the diff if its too big (how big is too big?).

**Comment by bmcutler** [comment]
See also  
Issue #96 
https://github.com/RCOS-Grading-Server/HWserver/issues/96

**Comment by chameco** [comment]
I've (tentatively) reworked the diff viewer on the submission side (which currently uses Javascript) to use the PHP code from the TA grading side as we discussed. Once I've worked through the remaining problems surrounding that, I'll start trying to determine critical file sizes.

**Comment by bmcutler** [comment]
add wrapper if statement in php diff viewer code...  if actual, expected, or diff are too big (hard coded some file size) then don't load, print a message to student instead.
