### ISSUE TITLE
Email-Errors while Emails are disabled

### ISSUE THREAD

**Issue by Mat2095** [Submitty/Submitty#5402]
**Describe the bug**
I'm getting an error in `/var/local/submitty/logs/emails/` every minute:
`[2020-05-21 00:37:02.103735] Error Sending Email: [Errno -2] Name or service not known`
That should not happen in my opinion, as I have emails disabled in `/usr/local/submitty/config/email.json`. My guess is that this is because `sbin/send_email.py` calls `construct_mail_client()` before checking if emails are even enabled.

**Expected behavior**
Don't try to construct the mail client if email is not enabled (and thereby don't produce errors).

**To Reproduce**
1. Set up Submitty with emails disabled. `email.json` should look like this:
```{
  "email_enabled": false,
  "email_user": "",
  "email_password": "",
  "email_sender": "submitty@myuniversity.edu",
  "email_reply_to": "submitty_do_not_reply@myuniversity.edu",
  "email_server_hostname": "mail.myuniversity.edu",
  "email_server_port": 25
}
```
2. Cron-job is enabled, so wait a few minutes
3. See `/var/local/submitty/logs/emails/`

**Configuration**
 - OS: Linux
 - Browser: not relevant

**Comment by MasterOdin** [comment]
@matgar1997 
```diff
diff --git a/sbin/send_email.py b/sbin/send_email.py
index 2f2f53379..35398146f 100644
--- a/sbin/send_email.py
+++ b/sbin/send_email.py
@@ -190,9 +190,9 @@ def send_email():
     """Send queued emails."""
     db, metadata = setup_db()
     queued_emails = get_email_queue(db)
-    mail_client = construct_mail_client()
-    if not EMAIL_ENABLED or len(queued_emails) == 0:
+    if len(queued_emails) == 0:
         return
+    mail_client = construct_mail_client()

     success_count = 0

@@ -230,6 +230,8 @@ def send_email():


 def main():
+    if not EMAIL_ENABLED:
+        return
     """Send queued Submitty emails and log any errors."""
     try:
         send_email()
```
