### ISSUE TITLE
Incorrect implementation of score calculation on grading index when peer grading is utilized in a gradable.

### ISSUE THREAD

**Issue by josharsh** [Submitty/Submitty#5403]
**Describe the bug**
When peer grading is availed on an assignment, the total score obtained after peer grading and ta grading(or auto grading) is SCORE(Peer Grading)+ SCORE(TA Grading) but the total score of the assignment is only reflective of TA Grading and/or Auto grading scores. 
e.g. In an Assignment there are 3 questions. 2 of them are TA graded and one is peer grading with 10 points each. Student A receives 9,8 and 7 respectively. When Grading Index is viewed, the score of student is shown as 24/20 rather than 24/30.

**Expected behavior**
When peer grading is involved the total score of the assignment should be TOTAL(Peer)+ Total(TA or/and Auto grading).

**Comment by paulis-reece** [comment]
Can I try to work on this?

**Comment by bmcutler** [comment]
closed by #5442
