### ISSUE TITLE
Site-wide time zone handling

### ISSUE THREAD

**Issue by Kevin-MM** [Submitty/Submitty#5420]
This issue is the successor to PR #5407

I'd like to finish implementing proper time zone handling site wide.  Below is a check list of all spots on the site which display date or time.  Unless otherwise specified all these data/times will be changed over to displaying the date/time adjusted for the user's time zone.  If the user hasn't set a time zone then the time will be formatted according to the server's time zone.  This isn't just limited to display of dates.  Collecting date/time information from an instructor should adjust the date/time stamp from the user's time zone into the server time zone before saving to the database/file.

- [x] Buttons on the Gradeables navigation page
- [x] Times on the gradeable submission page
- [x] Lab grading with 'Show Dates Graded' selected
- [x] Dates on the 'Dates' tab of the edit gradeable page
- [x] Dates appear inside the TA grading interface
- [x] Notifications
- [x] Office hours queue
- [x] Course material release times
- [x] Discussion forum list of threads
- [x] Discussion forum viewing a post
- [x] Discussion forum create thread lock date
- [x] Latedays allowed
- [x] Excused Absence Extensions
- [x] Grade Reports - time under grade summaries button
- [x] My Late Days/Extensions
- [x] Grade Inquiries
- [x] Peer Grading

**Comment by elihschiff** [comment]
I can do the office hours queue page if you want. I have already done some work (in unmerged code) to fix some other time/date issues so I would probably be easier for me to just add this on top of that pr.
Right now the queue does not even support timezones in the database, so I have been working to correct that.

**Comment by Kevin-MM** [comment]
Very well, Eli will handle the office hours queue page.
