### ISSUE TITLE
"No assignments yet"

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#543]
Add a friendly message when a student logs in early in the term and there are no assignment submissions open yet.

**Comment by sihsob** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No assignments yet](https://trello.com/c/Qjy1xyKC/7-no-assignments-yet)

**Comment by sihsob** [comment]
Closed #728

**Comment by sihsob** [comment]
Clean up redundant code related to this issue
