### ISSUE TITLE
Add new students to rotating section

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#544]
If rotating sections exist...  manually added new students should be added
(currently they are still null)

**Comment by bmcutler** [comment]
Also, the "setup rotating sections" page should tell you that you already have sections setup (and how many).  And warn you not to change them once grading has started.

**Comment by bmcutler** [comment]
Does it re-randomize the sections?
Do instructor/grader users get assigned a rotating section?  What if we want/don't want them to get assigned?
(add options)

**Comment by bdrumheller** [comment]
This re-randomizes the rotating sections each time this is run. I will add an option to allow students not currently assigned to rotating sections to be assigned to a new random section, keeping the existing assignments.

**Comment by bmcutler** [comment]
To re-iterate.  This page should tell you:
 * How many students are in the course (in a valid registration section)
 * How many rotating sections you have currently
     - whether they are "by random" or "by alphabetical"
     - current size of each rotating section
 * How many students are recent adds and dont yet have a rotating section
 * How many students are recent drops (aren't in a valid registration section), but are still in a rotating section.

The instructor user has a few options here...
   1.  Redo rotating sections completely, allowed to choose either "by random" or "by alphabetical", into any number of buckets.  This should be labeled clearly that doing this option will mess up any easy regrading of previously graded homeworks since the students will be re-assigned to rotating groups.  
    2. Just update things minimally, remove dropped kids from rotating sections, and add new kids to the rotating sections with the fewest members.  This option is only available for "by random" and you cannot change the number of rotating sections.

NOTE:  We should change the auto-feed script to set to NULL both the registration section AND the rotating section of students who are no longer in the registration list.  (Unless they are marked "manual").
