### ISSUE TITLE
make rubric creation points per item box keyboard friendly

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#547]
Right now its a drop down menu.
Instead let's replace it with the type a number box plus up down errors we have on the ta grading.

**Comment by bmcutler** [comment]
Also maybe a BUG:

Request to be able to have rubric item scores and total to be > 100 (at least 1000).

For the first rubric item the score ranges from -100 to +100

But when you click +rubric, the score for that rubric only ranges from -50-50.

**Comment by bdrumheller** [comment]
Mimic the pt assignment on the grading side on the create and edit a gradeable page.
