### ISSUE TITLE
Investigate design of distributed Submitty / Databases

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#5476]
A recent discussion brought up how we might want to support other departments at RPI, and how data ownership might look. Roughly, with the current design of a master submitty database that only holds users, and then each course stored in its own database, we should be able to support a distributed nature, where other departments could host their course databases on their server machine such that say CSCI would hold ownership only of course data for CSCI courses, PHYS for PHYS courses, etc.

This should be doable by ensuring two things:
1. We create a foreign server wrapper for remote machines ahead of time (https://stackoverflow.com/a/60603078/4616655). Right now, we do all dblinks ad-hoc, with the expectation that they're on the same server with same overall user permissions.
1. Ensure that setting course database details is doable from within the course config.json file

There was also an idea of maybe trying to run different URLs / PHP sites per department, but that is more complicated and probably does not offer any real advantage versus just having everyone go through a singular URL, beyond maybe doing general load balancing based on department. More information on how departments might want to do things would help drive discussion / ideas on this point.

**Comment by bmcutler** [comment]
Closing as this is no longer a priority.
