### ISSUE TITLE
Regex-checks for user_email too strict

### ISSUE THREAD

**Issue by Mat2095** [Submitty/Submitty#5489]
**Describe the bug**
Some valid emails are rejected by the regex-checks.
Affected mails have a '-' in the domain-part other than the first label.
For example `student@foo-bar.university.edu` is accepted, but `student@faculty.university-of-xyz.edu` is rejected.

**Expected behavior**
Emails like `student@faculty.university-of-xyz.edu` should be accepted since they are valid.

**To Reproduce**
1. Log in to a course
2. Manage students
3. Click "New Student"
4. Enter `student@faculty.university-of-xyz.edu` as Email
5. Click in another field so that the Email gets checked
6. See Email marked as invalid

**Configuration**
 - Server-OS: Linux
 - Client-OS: Windows
 - Browser: Firefox

**Additional context**

/site/app/models/User.php line 344:
`^[^(),:;<>@\\\"\[\]]+@(?!\-)[a-zA-Z0-9\-]+(?<!\-)(\.[a-zA-Z0-9]+)+$`
'-' is not allowed in domain-parts other than the first one.
Suggestion:
`^[^(),:;<>@\\\"\[\]]+@(?!\-)[a-zA-Z0-9\-]+(?<!\-)(?:\.(?!\-)[a-zA-Z0-9\-]+(?<!\-))+$`
Basically it adds dash to later labels, including the negative-checks to prevent labels from starting or ending with dash. Also use non-capturing group since there is no point in capturing.

/site/public/js/userform.js line 170:
`^[^(),:;\<\>@\\"\[\]]+@(?!\-)[a-zA-Z0-9\-]+(?!\-)(\.[a-zA-Z0-9]+)+$`
Here the negative-lookbehind from the previous file was changed to a negative-lookahead. That makes no sense because the following group starts with a '.', so it can never be '-'.
Lookbehinds are only available since 2018 in JS, so maybe it should not be used.
Suggestion:
`^[^(),:;\<\>@\\"\[\]]+@(?!\-)[a-zA-Z0-9\-]*[a-zA-Z0-9](?:\.(?!\-)[a-zA-Z0-9\-]*[a-zA-Z0-9])+$`
Work around lookbehind limitation by requiring one non-dash character at the end of each label, plus optionally other characters before that, but prevent starting with dash using negative-lookahead; allow dash in later labels; use non-capturing group

**Comment by MasterOdin** [comment]
For PHP, I would probably say let's move to using https://packagist.org/packages/egulias/email-validator, which is what symfony relies on and so can benefit from the larger community on keeping that up-to-date.

For userform.js, we should probably remove this validation and just mark the form input as type `email` and let the browser handle validation.
