### ISSUE TITLE
Submitty needs access to a PHP image library

### ISSUE THREAD

**Issue by Kevin-MM** [Submitty/Submitty#5494]
**What problem are you trying to solve with Submitty**
Working on the image portion of #5318 I need the ability to resize images.  Currently I can't find any good way using the native functionality of PHP.

**Describe the way you'd like to solve this problem**
I'd like to have PHP configured to include one of the two libraries:
- https://www.php.net/manual/en/book.imagick.php
- https://www.php.net/manual/en/book.image.php

**Describe any potential alternatives you'd tried to solve the problem**
This problem doesn't appear to be as simple as pulling in a library with composer.  I believe it requires special configuration of PHP.

**Comment by MasterOdin** [comment]
`apt install php-imagick`?

https://packages.ubuntu.com/bionic/php-imagick

**Comment by Kevin-MM** [comment]
Ok, now how do we ensure this makes it's way into vagrant, travis, production deployment, etc?

**Comment by MasterOdin** [comment]
1. add it as dependency in `.setup/distro_setup/bionic/setup_distro.sh`
2. add as `pecl install imagemagick` to .travis.yml on test stages that need it (see [these lines](https://github.com/Submitty/Submitty/blob/e004c21305c42251ebc147c128843ff130096a1b/.travis.yml#L104-L105) as example) and add `imagemagick` as apt package (https://docs.travis-ci.com/user/installing-dependencies)
3. Create system migration that runs `apt install php-imagemagick`


--

https://github.com/spatie/image might be a workable alternative that should be installable via composer and not require any extra steps as its only dependency (`php-exif`) should be builtin to php on Ubuntu.

**Comment by Kevin-MM** [comment]
Very well, I will take over on this issue.
