### ISSUE TITLE
TA & Peer Grade & Feedback Redesign

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5498]
<img width="765" alt="submission_info" src="https://user-images.githubusercontent.com/5871417/84103764-00d6c680-a9e2-11ea-9879-44d7e597728b.png">
<img width="765" alt="ta_grade_info" src="https://user-images.githubusercontent.com/5871417/84103940-6e82f280-a9e2-11ea-8b8b-007a943e67fc.png">
<img width="765" alt="peer_grade_info" src="https://user-images.githubusercontent.com/5871417/84103778-07fdd480-a9e2-11ea-9659-3d532b686ae1.png">

**Comment by jchulton** [comment]
Closed by PR #5536
