### ISSUE TITLE
ta grading homework index page improvements

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#550]
Right now, students without a section (dropped students, instructor/grader users, etc) are not on the index page.  Add students will null section at the bottom.

Also, make sure there is a "view all sections" button, and that it works, but only for full access graders.  limited access graders shouldn't be able to get there, even with url hacking.

**Comment by MasterOdin** [comment]
The null section should be at the bottom of the list of sections and only viewable when viewing all sections (and not a subset)

**Comment by sihsob** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;iRy3wMb2&#x2F;2-ta-grading-homework-index-page-improvements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ta Grading Homework Index Page Improvements</a>

**Comment by bmcutler** [comment]
This is done.  Will re-open if we notice something missing/broken.
