### ISSUE TITLE
Hide "Stoplights" for non-peer components from peers on the grading index page

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#5505]
At present, the grading index page shows "stoplights" for non peer components to peers. These should be hidden.

![hide_peer](https://user-images.githubusercontent.com/11758882/84277311-548c0180-ab01-11ea-9873-306b4674cac6.png)
The green stoplight in the image above should be hidden.

**Comment by bmcutler** [comment]
closed in PR #5577
