### ISSUE TITLE
Peer "Current percentage of grading done" incorrect on status page

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#5506]
Possibly related to #5505

At present, the `Current percentage of student grading done` on the status page is incorrect for peer graders. 

To reproduce: 
1. Create a peer gradeable with one peer component and one TA component
2. Assign peer `A` to assign peers `B` and `C`. 
3. Make a submission for peer `B`
4. As peer `A`, grade peer `B`.
5. Navigate to the status page to see that it says grading is `1/4` complete.

![bugged_peer_points](https://user-images.githubusercontent.com/11758882/84277925-1f33e380-ab02-11ea-8a6b-e1d5489eefdf.png)

![percentage](https://user-images.githubusercontent.com/11758882/84278115-5d310780-ab02-11ea-82d3-a2aeef7d28ad.png)

**Comment by josharsh** [comment]
Work on this issue us under review: 
https://github.com/Submitty/Submitty/pull/5580
