### ISSUE TITLE
Combine router / response pages

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#5519]
With Submitty/submitty.github.io#240 getting merged, we now two pages on working with the router / responses for PHP code:

https://submitty.org/developer/router
https://submitty.org/developer/development_instructions/router-response

Should coalesce around one, and also probably move whatever resultant page we have under `Developing the PHP Site` which is probably the most "discoverable" place for this doc (since it's clear at the top level is not right given we now have a second page).

**Comment by shailpatels** [comment]
@bmcutler @emaicus This is probably related to a larger issue. The newly added docs on the router and response objects were written as more of a walkthrough/tutorial for new developers. It uses more examples and common use cases as opposed to the existing docs which are more reference oriented.

I think there's value in leaving the two separate - yes there will be overlap but ultimately they serve a distinct purpose. 
The newly added pages are also part of the documentation of ajax that will explain to new developers how to connect the front-end to the back-end.

**Comment by bmcutler** [comment]
we will keep two pages, because one is documentation, and the other is tutorials for new developers.

(The submitty.org site will be reorganized to make this more clear)
