### ISSUE TITLE
How do I add a TA or undergrad mentors?

### ISSUE THREAD

**Issue by laprej** [Submitty/Submitty#553]
In trying to add Nikhil (mehtan4) via the Manage Users page, I am receiving quite a few php errors when I tried adding him by simply filling out the User ID and nothing else, then put in most of his info and that did not appear to do anything.  Is this supported yet?

**Comment by bmcutler** [comment]
If you hit enter after just entering the username of a user *not* in the system, it seems to give lots of errors (we should fix this and just say "user does not exist").  

But if you fill out the whole form for that new user not already in the system and press submit, it does work fine.

**Comment by bmcutler** [comment]
fixed! :)
