### ISSUE TITLE
Test variety of submission ids and names

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#554]
We should be limiting submission ids to be only characters allowable on a linux filesystem (minus a few characters like space). This should be supported throughout the system and not have any further restrictions. We also should not support any non-ascii characters.

We need to especially test where we're splitting things on `_` or `-` or `__`.

**Comment by bmcutler** [comment]
Proposal:

semester name and course names and assignment names and usernames may not start or end with '_' or contain '__' (consecutive double underscore) or spaces/tables or some additional restricted characters.
