### ISSUE TITLE
Non-Faculty users sometimes highlighted yellow in discussion board

### ISSUE THREAD

**Issue by kd2eom** [Submitty/Submitty#5564]
**Describe the bug**
In the discussion board, Submitty highlights any messages from course faculty with a yellow border. However, it appears that occasionally a student's post is highlighted with a yellow border. This persists even after refreshing the page.

**Expected behavior**
Student's post should not be highlighted in yellow.

**Screenshots**
![wut1](https://user-images.githubusercontent.com/29665790/85188406-34341380-b274-11ea-89c5-451b5b9323a2.png)
(Potentially sensitive information redacted, but this was a question about course material that was clearly written by a student and not a faculty member).

**Comment by bmcutler** [comment]
This is not a Submitty bug.  I looked at these specific posts and they were made by non-student users in the course.
