### ISSUE TITLE
remove inline css & script from templates/forum/StatPage.twig

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5586]
refactor to remove inline css & script

**Comment by Swapnil-2001** [comment]
@bmcutler I would like to work on this, please.

**Comment by sbelsk** [comment]
Fixed by https://github.com/Submitty/Submitty/pull/5817

**Comment by sbelsk** [comment]
Fixed by https://github.com/Submitty/Submitty/pull/5817
