### ISSUE TITLE
PDF Annotate is broken

### ISSUE THREAD

**Issue by bidwej** [Submitty/Submitty#5602]
**Describe the bug**
PDF Annotate crashes when running the Submitty sample code. [@submitty/pdf-annotate.js](https://www.npmjs.com/package/@submitty/pdf-annotate.js) says to submit bug reports to the main Submitty/Submitty repository. The "pdf-annotate.js" project is no longer maintained for reference.

I'd like to contribute to fixing the problem if anyone has any pointers. The render call on line 4150 of "pdf-annotate.js" looks correct. I think the issue may have something to do with the canvas context.

**Expected behavior**
A PDF should render with annotations from "MyStoreAdapter".

**To Reproduce**

Run the following code
```
import pdfjsLib from 'pdfjs-dist/build/pdf';
import PDFJSAnnotate from 'pdfjs-annotate';
import MyStoreAdapter from './myStoreAdapter';
 
const { UI } = PDFJSAnnotate;
const VIEWER = document.getElementById('viewer');
const RENDER_OPTIONS = {
  documentId: 'MyPDF.pdf',
  pdfDocument: null,
  scale: 1,
  rotate: 0
};
 
pdfjsLib.workerSrc = 'pdf.worker.js';
PDFJSAnnotate.setStoreAdapter(MyStoreAdapter);
 
pdfjsLib.getDocument(RENDER_OPTIONS.documentId).promise.then((pdf) => {
  RENDER_OPTIONS.pdfDocument = pdf;
  VIEWER.appendChild(UI.createPage(1));
  UI.renderPage(1, RENDER_OPTIONS);
});
```

"PDFPageProxy.getViewport is called with obsolete arguments"

**Configuration**
 - OS: Windows
 - Browser Chrome

**Screenshots**

**Additional context**

**Comment by MasterOdin** [comment]
Sorry for the (very) late response on this. It got shuffled onto my backlog of things, and then drowned by other stuff. The "onboarding" experience of getting started with the library outside of Submitty has not been a priority for us as we've not had anyone else try to use it (and we somewhat didn't expect anyone would).

The README example should be updated as the `./myStoreAdapter` does not exist out of the box and is perhaps confusing to someone who might (accurately) believe it does. A more accurate call for an example would be:
```
PDFJSAnnotate.setStoreAdapter(new PDFJSAnnotate.LocalStoreAdapter());
```

which will then set the adapter to use the [`LocalStoreAdapter`](https://github.com/Submitty/pdf-annotate.js/blob/master/src/adapter/LocalStoreAdapter.js) which just stores the annotations into [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) memory.

The web/index.js file gives a good example of using the library (and is also the basis for when you do `npm start` in the repo): https://github.com/Submitty/pdf-annotate.js/blob/master/web/index.js

**Comment by MasterOdin** [comment]
Updated the readme in Submitty/pdf-annotate.js@41d082cfd94e554d80febceae48b898c86377a0a. Please feel free to reopen this issue if using the `LocalStoreAdapter` does not work.
