### ISSUE TITLE
Allow instructor to specify an external link for their main course page 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#561]
And put this in an obvious place on the navigation page (and each homework page too)

**Comment by MasterOdin** [comment]
We'd want to add this to the course config file as an additional setting. However, where would it make the most sense to show this link?

**Comment by bmcutler** [comment]
The obvious place would be the "csci1200 data structures" part of the breadcrumb.  But we've already got that going to the main navigation page.

We could add another level to the breadcrumb line
csci1200 data structures >> submitty >> hw1
and "submitty" goes to the nav page.  

But then "f16" feels out of place.  (should just be removed?)
