### ISSUE TITLE
Upload Autograding Config Form Broken

### ISSUE THREAD

**Issue by Mat2095** [Submitty/Submitty#5613]
![ClipboarderTemp-1e6b276](https://user-images.githubusercontent.com/11258252/86268587-b30c4300-bbc8-11ea-8124-3872886fc19e.png)

The HTML for the previous uploads seems to break the site.

**Configuration**
 - OS: Windows
 - Browser: Firefox and Chrome

I guess the reason is that this commit https://github.com/Submitty/Submitty/commit/77797353164961dff8de2f6d1a850000988d7539#diff-9d970cfe4d6623140758ffca4770ed58 changed some `div`-elements to `li`-elements. However `display_files` is used recursively and the nested lists still use a `div`-container instead of `ul`.
So the resulting HTML is invalid. Firefox and Chrome seem to work around that by closing the top-level `li` too early, breaking the whole structure.

**Comment by Kevin-MM** [comment]
Can you list the steps to reproduce?  I've been working with this page quite a bit and I'm not experiencing any issues.

**Comment by Kevin-MM** [comment]
Ah, I see you've uploaded zips with a directory structure, I haven't been testing.
