### ISSUE TITLE
convert username to lowercase

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#563]
If a user capitalizes their username, they can't get in.

**Comment by MasterOdin** [comment]
We need to add a check also to prevent capitalized user_ids from entering the system then

**Comment by bmcutler** [comment]
Jeramey will add a "trigger"

**Comment by JerameyATyler** [comment]
The following commands will need to be executed on each courses' database. This ensures that any username in the database (user_id from users table) is lowercase, any column that references username cascades updates, and any future usernames that are inserted or updated will always be lowercase. 

-- Add cascading updates to the user id foreign keys
ALTER TABLE gradeable_data
    DROP CONSTRAINT gradeable_data_gd_user_id_fkey,
    ADD CONSTRAINT gradeable_data_gd_user_id_fkey
        FOREIGN KEY (gd_user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE;


ALTER TABLE gradeable_data
    DROP CONSTRAINT gradeable_data_gd_grader_id_fkey,
    ADD CONSTRAINT gradeable_data_gd_grader_id_fkey
        FOREIGN KEY (gd_user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE;


ALTER TABLE grading_registration
    DROP CONSTRAINT grading_registration_user_id_fkey,
    ADD CONSTRAINT grading_registration_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE;


ALTER TABLE grading_rotating
    DROP CONSTRAINT grading_rotating_user_id_fkey,
    ADD CONSTRAINT grading_rotating_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE;


ALTER TABLE late_day_exceptions
    DROP CONSTRAINT late_day_exceptions_user_id_fkey,
    ADD CONSTRAINT late_day_exceptions_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE;


ALTER TABLE late_days
    DROP CONSTRAINT late_days_user_id_fkey,
    ADD CONSTRAINT late_days_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE;


ALTER TABLE late_days_used
    DROP CONSTRAINT late_days_used_user_id_fkey,
    ADD CONSTRAINT late_days_used_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE;


ALTER TABLE sessions
    DROP CONSTRAINT sessions_fkey,
    ADD CONSTRAINT sessions_fkey
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE;


-- Set all user ids to lowercase
UPDATE users SET user_id=lower(user_id);


-- Create the function that will be executed when the trigger event occurs
CREATE OR REPLACE FUNCTION lower_case_user_id() RETURNS TRIGGER as $lower_case_user_id$
    BEGIN
        NEW.user_id = lower(NEW.user_id);
        RETURN NEW;
    END;
$lower_case_user_id$ LANGUAGE plpgsql;


-- Create the trigger
CREATE TRIGGER lower_case_user_id BEFORE INSERT OR UPDATE ON users
    FOR EACH ROW EXECUTE PROCEDURE lower_case_user_id();
