### ISSUE TITLE
confidential / copyright / responsible peer grading reminder

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5663]
**What problem are you trying to solve with Submitty**
Peer graders will be reviewing the materials submitted by their peers, 
and the process of peer grading may reveal the identity of the student. 

Let's add a reminder to both limited access and peer graders of their role as a reviewer.

Let's place it above the "Status of <gradeable name>" div on the info/stats/summary page for grading:
<img width="606" alt="Screen Shot 2020-07-09 at 3 10 49 PM" src="https://user-images.githubusercontent.com/5871417/87080871-68a54a80-c1f6-11ea-8bac-5bf2ff3e4b47.png">

Let's style it similarly to the "assignment message" on the gradeable submission page (a blue box with white text):
<img width="623" alt="Screen Shot 2020-07-09 at 3 09 41 PM" src="https://user-images.githubusercontent.com/5871417/87080773-3f84ba00-c1f6-11ea-803e-8e46cb365e83.png">

Here's a first draft of this message:  (with appropriate tweaks to the wording for limited access graders)

---

## Your Responsibility as a Peer Grader

You will be reviewing materials submitted by your classmates and these materials are considered confidential.  Your classmate, the author of this material, is entitled to copyright protection.  As such, you may not use or share any of these materials or ideas without explicit permission from the author.  You may not retain this material -- you must delete/destroy any copies of this material after your review and grading of the work is complete.

Your instructor has configured the grading for this assignment to be [ double-blind / single-blind / unblinded ].  
You should not attempt to discover the identify of your classmate.  However, the identify of the classmate may be unintentionally or unavoidably revealed.  Please respect your classmate's privacy.

Please refer to your instructor's course policies if you realize you have a *conflict of interest* with a peer that you have been assigned to grade.

---

@emaicus @MasterOdin @holzbh @KCony -- do you have any suggestions on phrasing/additions to the above statement?
Maybe we can borrow inspiration from instructions for academic reviewers??  (I did a little googling to start, but we can expand revise this.)

**Comment by MasterOdin** [comment]
I'm fine with the wording and think it's adequate for our needs and does not swing into dense "lawyer" speak.
