### ISSUE TITLE
Import From JSON doesn't work

### ISSUE THREAD

**Issue by maksimt** [Submitty/Submitty#567]
Same error in Chrome and Safari on Mac OS 10.11.

> [AJAX ERROR] Refresh Page

Nothing changes when I refresh the page.

**Comment by MasterOdin** [comment]
Could you email me the json files you're attempting to import? (pevelm@rpi.edu)

**Comment by maksimt** [comment]
Hi,

It doesn't show me a import dialogue. Immediately when I click on the
"Import From JSON" button (next to "New Gradeable") I get this error
dialogue:

Chrome:


Safari:


​
Both on Mac OS 10.11
​

**Comment by bmcutler** [comment]
Hi Maksimt,
 
I think there's a misunderstanding of how this new (completely undocumented... ) feature works.
The intention is that you go to the /var/local/submitty/courses/f16/cscixxxx/config/form directory, copy of one the form json files there changing the name to follow the file name structure and directly make the small edits to change the gradeable id, title, and dates.

This is intended for the power user who doens't want to enter the same thing 10 times for each of 10 identical assignments (except for the title & date).  If you mess up the structure of the json, it will fail to import.  There is little error checking and no error correction.

If you haven't touched the contents of the config/form directory, I don't know why you're getting an error.  That shouldn't happen.  But don't expect a browse file for upload to pop up.  (Perhaps the button should be named more intuitively.

Barb

**Comment by bdrumheller** [comment]
The issue with this stems from the ajax request being made to a different url. This will be resolved once everything is on the same url.

**Comment by bmcutler** [comment]
Re-implementing & re-designing this feature in another issue.
