### ISSUE TITLE
Add Travis check for migrations that change DB but did not change sql files

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#5718]
From a slack discussion, it was found that #5455 added a migration file, but did not update the corresponding sql files, which means any new Submitty installation will be broken when attempting to use those features.

Given that this is probably not the first time this has happened, it would be good to add a Travis step (in the same round as unit tests?) that for PRs, runs `git diff --name-status origin/master` and for any changed or new file under `migration/migrator/migrations/{course,master}`, grep the file for `database.execute` and if it has that, then check that the corresponding sql file was also updated.

**Comment by wusatosi** [comment]
Just to clarify. The problem #5455 have is that a developer can submit code that adds a migration file under `migration/migrator/migrations/{course,master}` but does not update the initialization SQL files under `migration/migrator/data/`, like `submitty_db.sql` without warning. Causing an upgrade migration to be valid, but not a fresh install. 

Is this correct?

**Comment by MasterOdin** [comment]
Yes

**Comment by bmcutler** [comment]
closed by #8198
