### ISSUE TITLE
Grader feedback file box does not show annotated pdfs buttons inline

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#5761]
**Describe the bug**

When going to the TA results on the submission page for a gradeable with annotated PDFs, the view of submitted files does not have the buttons for the annotated pdf stuff inline any longer with the file that they correspond to.

**Expected behavior**

The buttons to be at least inline with the file that they refer to.

**To Reproduce**
1. Submit PDFs to gradeable
2. Annotated them
3. Go to submission page

**Configuration**
 - OS: [e.g. Windows, Linux, ...] macos
 - Browser [e.g. chrome, safari] chrome

**Screenshots**

![Screen Shot 2020-07-31 at 11 48 29 AM](https://user-images.githubusercontent.com/1845314/89054324-46b86700-d361-11ea-8041-676721ad2518.png)

**Comment by jportorreal00** [comment]
Should these buttons be in a new section called  "Annotated Feedback" or something or should it be directly under the original buttons?
