### ISSUE TITLE
stop using function/script that appends course & semester GET url variable 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#579]
(hunt down all places where we forgot semester= or course=)

**Comment by bmcutler** [comment]
@MasterOdin & @JerameyATyler:

This is now more urgent.  I was just testing another commit and I hit one of these errors.  I went to grade a regular electronic rubric as instructor, got to the index page with all students, clicked to grade a specific student and got an error because neither course= nor semester= were in the URL.  When I hit back and clicked on another student it was ok (course= and grading= were in the URL) and I entered grading. 

I reproduced it a minute later.  I logged out, then entered back in and I got the error on the first student.  But I couldn't reproduce a 3rd time.  I'm not sure what was different.  Maybe its the time I pick an assignment, etc.  Maybe it was a different course(?)  Since I can't fully log out of the TA side w/o closing the browser.

It's just a matter of time before TAs start hitting this too.

**Comment by MasterOdin** [comment]
The real problem (though it's a good way to ensure we see errors) with the way things are currently handled is on [these javascript lines](https://imgur.com/gallery/nEwZs), however if the page errors out at any point these lines aren't run and the links break and it's not super obvious to end users who don't know this.

However, it does sound like there's other errors in the system though and we should investigate those as they might be somewhat problematic in addition to the URL breaking.

**Comment by bmcutler** [comment]
BEFORE WE CLOSE THIS:
let's delete that now commented out javascript function, and delete those FIXME comments.
