### ISSUE TITLE
Add LaTeX rendering support to the forum

### ISSUE THREAD

**Issue by BenKelly99** [Submitty/Submitty#5797]
**What problem are you trying to solve with Submitty**
While basic markdown support is great for many purposes, it lacks the flexibility of LaTeX for mathematical equations. We should add an option for LaTeX math mode equations to allow users to share snippets of LaTeX to communicate more effectively.

**Describe the way you'd like to solve this problem**
There could be a button similar to the buttons for links and code which would allow the insertion of some identifier for LaTeX code. We could use $, which is used in LaTeX to enter math mode.

**Comment by eddiekrystowski** [comment]
It has been decided that since the new markdown engine implemented in #6669 doesn't natively come with support for LaTeX rendering, this issue will get closed. It does, however, give syntax highlighting for LaTeX code.
