### ISSUE TITLE
notebook vertical spacing on Safari

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5811]
**Describe the bug**
Vertical spacing before h3 is inconsistent on Mac safari.  
The spacing on Mac Chrome & Mac Firefox looks ok.

See the crash course in CPP lesson 01 gradeable
(accessible only to submitty organization members)

The space around short answer input looks ok (e.g. Q15)

<img width="649" alt="Screen Shot 2020-08-12 at 2 21 11 PM" src="https://user-images.githubusercontent.com/5871417/90057467-6c713480-dcae-11ea-9533-f2cfb968d784.png">

But the space around the multiple choice inputs looks squished/overlapping/negative space (e.g., Q09)

<img width="597" alt="Screen Shot 2020-08-12 at 2 20 50 PM" src="https://user-images.githubusercontent.com/5871417/90057389-56fc0a80-dcae-11ea-8067-0d4aa614942e.png">

@Kevin-MM Thinks it might be related to fieldset(?) which was added to solve an accessibility issue.  So be sure we don't remove any important functionality in fixing this visual bug.

Also tagging @elihschiff for review of eventual PR.

**Comment by elihschiff** [comment]
I actually can't review this I don't have safari or a Mac

**Comment by bmcutler** [comment]
@elihschiff I'm hoping you will review the code change and make sure it doesn't undo accessibility (if indeed this bug is related)
