### ISSUE TITLE
Improve Contact Information Field for Office Hours Queue

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5870]
* Let's make the form box for typing contact information bigger.  It isn't big enough for a long webex URL.

* Also, let's add an option that will help enforce requirements for contact info.  It was suggested it be a regexp to ensure the student has typed in a webex url for example.  (or alternately require skype or whatever)

**Comment by pratikaher88** [comment]
Hi @bmcutler! I think I can help out with this feature if it is already not being worked on.

**Comment by BenKelly99** [comment]
@pratikaher88 I'm not aware of anyone working on it so you should go for it

**Comment by pratikaher88** [comment]
Thanks, will do.

**Comment by rajpratyush** [comment]
@BenKelly99 is anyone working on this issue???

**Comment by BenKelly99** [comment]
@rajpratyush I don't think so, go for it
