### ISSUE TITLE
Poll status marked as 'No Response'

### ISSUE THREAD

**Issue by sbelsk** [Submitty/Submitty#5881]
**Describe the bug**
Out of the 5-6 polls for each lecture, the answer for one poll is recorded but the answer status says 'No Response'

**Expected behavior**
My answer should be recorded, and the answer status should display the answer I chose instead of 'No Response' 

**Configuration**
 - OS: Windows
 - Browser: chrome

**Screenshots**
<img width="830" alt="Screenshot_1" src="https://user-images.githubusercontent.com/71195502/93025171-cf196100-f5c9-11ea-867f-bd7163b475d1.png">
<img width="367" alt="Screenshot_2" src="https://user-images.githubusercontent.com/71195502/93025172-d17bbb00-f5c9-11ea-952d-b7ff79c3bf5d.png">
<img width="333" alt="Screenshot_3" src="https://user-images.githubusercontent.com/71195502/93025175-d3de1500-f5c9-11ea-89ef-2781195d41eb.png">

**Comment by BenKelly99** [comment]
Closed by #5895
