### ISSUE TITLE
Hide until TA grades are released autograding option

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5892]
Currently autograding test cases are hidden (points & test details are not display) during submission and remain hidden when ta grading is released (points earned are shown but test details are never displayed).  For example:

https://github.com/Submitty/Submitty/blob/master/more_autograding_examples/cpp_hidden_tests/config/config.json

        {
            "title" : "Frame Size 13",
            "command" : "./a.out 13",
            "points" : 2,
            "hidden" : true,
            "validation" : [
                {
                    "method" : "diff",
                    "actual_file" : "STDOUT.txt",
                    "expected_file" : "frame_13.txt"
                }
            ]
        },

Note that hidden is an optional parameter that is false by default.

---------------------

Let's add another variant of this option:

        {
            "title" : "Frame Size 13",
            "command" : "./a.out 13",
            "points" : 2,
            "hidden_until_grades_released" : true,
            "validation" : [
                {
                    "method" : "diff",
                    "actual_file" : "STDOUT.txt",
                    "expected_file" : "frame_13.txt"
                }
            ]
        },

With this option, everything (points & details) about the test case should be displayed after the grades released date.
Note that hidden_until_grades_released is optional, and is false by default.

----

And a final option..    This one should never display that the test even exists.  Probably autograding points are zero, or maybe the many tests are hidden like this and students are intentionally not told how autograding was prepared.

        {
            "title" : "Frame Size 13",
            "command" : "./a.out 13",
            "points" : 2,
            "always_hidden": true,   
            "validation" : [
                {
                    "method" : "diff",
                    "actual_file" : "STDOUT.txt",
                    "expected_file" : "frame_13.txt"
                }
            ]
        },

The always_hidden parameter is optional, and is false by default.

Note that it should be an error if more than one of hidden and hidden_until_grades_released and always_hidden to true in the same test case.

**Comment by DefinitiveAbove** [comment]
Changes:
hidden_until_grades_released -> release_hidden_details
- release_hidden_details requires hidden to be true
- default of release_hidden_details is false

Not implementing always_hidden
