### ISSUE TITLE
Titles for pages are formatted repetitively and are too long

### ISSUE THREAD

**Issue by bepvte** [Submitty/Submitty#5904]
**What problem are you trying to solve with Submitty**
Submitty pages have a long prefix before each page `<title>`. Instead of "Polls | [CSCI1200]", the page title is something long like "Submitty Csci1200: Data Structures Polls". Not only is this long and repetitive, its also unclear where the course name ends and the page title begins. Usually these long titles are truncated by the browser so the relevant part of the title is hidden in tabs.

**Describe the way you'd like to solve this problem**
Submitty page titles should be concise and avoid truncation of relevant info from the title. I suggest "Polls - Data Structures", or "Polls - CSCI1200". Including the name "Submitty" is unnecessary because Submitty's icon is visible.

**Additional context**
![image](https://user-images.githubusercontent.com/8226605/93930184-f61f1380-fcea-11ea-9b43-573c36a9d95e.png)
Example of how submitty page titles are truncated and useless on a vertical tab based browser. Compare the title formatting to other pages like RPI INFO, Blackboard LMS, and github, who all put the primary title in front and a secondary title afterwards.
![image](https://user-images.githubusercontent.com/8226605/93930266-15b63c00-fceb-11ea-80b2-ac32f7e818b0.png)
The tab truncation also occurs on conventional browsers.

**Comment by hbh7** [comment]
My personal favorite: The Gradeables Page
![image](https://user-images.githubusercontent.com/5050375/94387601-a42a2380-0118-11eb-96d4-b67831b43b5a.png)
