### ISSUE TITLE
Polling: Existing Feature Improvements

### ISSUE THREAD

**Issue by BenKelly99** [Submitty/Submitty#5912]
Here are a list of existing features that can be improved for polling:

- [ ] Overall UI improvements. The UI is messy and can be improved, especially for the new/edit polls, and for student view for answering a poll.

- [x] Currently, an instructor can only open a poll once. That is, once it is opened for students to see, it cannot be closed. Instructors should have the ability to set a poll to any of three states at any time. Closed: cannot be viewed or answered by students. Open: Can be viewed and answered. Ended: Can be viewed, but no longer answered.

- [x] Currently, the viewPoll, editPoll, and viewResults page all are POST requests whose payloads contain the poll ID to show. This should be GET requests instead. 

- [x] Currently, when an instructors submits edits or a new poll and there is a part that is an invalid setup, it will simply kick the instructor back to the all polls page, and discard their changes. This is very frustrating so instead if there is an invalid part it should kick them back to the page they were on, retaining their changes, but not updating the polls in the database at all.

Note: if fixing one of these issues, do not use the "Closes"  tag unless the PR resolves all remaining issues. I will put check marks next to the issues as they are fixed.

**Comment by Harshalzzzzzzz** [comment]
@BenKelly99  Dear Mentor ,
I would like to work on this issue, can you please guide me further on what needs to be done and how I can approach this issue and contribute to the project?
I have already completed the setup.

Thank you

**Comment by Harshalzzzzzzz** [comment]
@BenKelly99 Dear Mentor, 

Although both the issues interest me, I would like to work on this and then move on to the other if possible. Can you please guide me further? I'd like to get started on this.

**Comment by BenKelly99** [comment]
I would choose one of the bullet points on one of the issues, and start on that. Which one looks good to you? In general, most of the polling work is done in PollController.php, PollView.php, PollModel.php, the twig templates in site/app/templates/polls, and the database stuff is in DatabaseQueries.php

**Comment by sbelsk** [comment]
@BenKelly99 The only bullet point left on the list is "Overall UI improvements". What, in your opinion, makes the student poll view and instructor new/edit poll UI's messy that can be improved? Perhaps it's been so long that this was handled and is no longer relevant... :)

**Comment by BenKelly99** [comment]
@sbelsk There are some various things like weird scaling problems when the window is resized, resizing uploaded images I think might still need to be done, and personally I'm not a fan of the poll answering page. The radio buttons look kinda bleh, especially when grayed out when the poll is over. Not a high priority issue for sure.

**Comment by bmcutler** [comment]
Closing this overall issue, let's open specific issues for anything else to be done.
