### ISSUE TITLE
Web-Based Rainbow Grades Generation Calculations

### ISSUE THREAD

**Issue by alicebibaud** [Submitty/Submitty#5919]
Path: http://localhost:1501/courses/f20/blank/reports/rainbow_grades_customization

In the Rainbow Grades Customization window, instructors are obligated to manually calculate and fill out the grade-specific statistics (lowest a-, lowest b-, etc.) they want to display in rainbow grades. 

It would be more intuitive for the program to actually calculate all of these things based on student grades; the instructor should not have to do this.

This is indeed a work in progress, so I imagine some other solution is being worked on by someone else at the moment.  Consider this a suggestion for whoever is doing that; if not, please consider adding this feature once bugs are no longer a problem.

![Screen Shot 2020-09-29 at 10 57 13 AM](https://user-images.githubusercontent.com/60297067/94575738-8ce75500-0242-11eb-9279-3e2099071dae.png)

**Comment by bmcutler** [comment]
Closing as this is an unclear design request.   The interface correctly puts grade cutoffs in the instructors hands.
