### ISSUE TITLE
Late Days Allowed CSV upload requires carriage returns

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5925]
**Describe the bug**
The page says:
"Do not use column headers. CSV must be of the following form: student_id, MM-DD-YYYY, late_days"

However, unless each line ends with a \r (carriage return) the file will be rejected.

Let's make it work with linux line endings (\n) OR windows line endings.

**Comment by Kevin-MM** [comment]
Hi @bmcutler I was unable to replicate this issue.  I made a small test csv with about 10 lines in it.  Using `unix2dos` and `dos2unix` linux utilities I tested uploading the file with the different line terminators `\n` and `\r\n`.  In my testing the files were uploaded and parsed correctly with both line endings.

**Comment by DefinitiveAbove** [comment]
Tested using Notepad++ with `\n` and `\r\n` and both parsed correctly. However, using `\r` as the line ending resulted in an error; I don't have macOS to test the current version of Excel on it, but if a CSV was saved from an older version on macOS it may have used `\r` as the line ending (https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_mac-mso_o365b/csv-line-endings/2b4eedaf-22ef-4091-b7dc-3317303d2f71) - should we check for this?
