### ISSUE TITLE
New submission page doesn't clear out old submission

### ISSUE THREAD

**Issue by laprej** [Submitty/Submitty#596]
On Mac / Safari:

After submitting a file to grade on the submission page, it does not clear out the entry once it has been uploaded.  So dragging an updated version of the file makes it look like no improvement has been made.  Hitting the clear button and _then_ uploading the updated file works fine, however.  Just a UI issue.

**Comment by MasterOdin** [comment]
Are you just asking to have some visual indicator that you've overwritten the previous submission name (beyond just the pop-up when you're trying to overwrite the file)?

So you drag in a new file with the same name, hit confirm on the popup and then you've got (let's say) yellow coloring on the file name?

**Comment by laprej** [comment]
I do not get a pop-up indicating that I'm trying to overwrite the file.  In fact it would seem that I am not overwriting the file at all but it is held in some sort of buffer.  Even if I come back to the page from another location on the website, nothing really changes.  The only way to create a new submission is by first hitting the clear button and then uploading another file again.

**Comment by bmcutler** [comment]
Unfortunately this is a difference of opinion with the CS1 instructors who requested that the previous files always be auto populated into the submission bucket for incremental edits.  The replace-everything-with-my-new-files use case means in practice yes, hit clear, then upload.

UNLESS...  are you saying that our implementation of the design in buggy?  Last time I tested it was replacing with the new file (with the same name) correctly.  Are you asking for some sort of visual confirmation about a file being new?  We do have the file size displayed.

**Comment by ZishanHuang** [comment]
It might be that you disabled pop-ups in your Safari?

**Comment by MasterOdin** [comment]
The popup that should be showing up:

![](https://www.dropbox.com/s/4nwobwyprpv1uew/Screenshot%202016-09-10%2014.38.41.png?dl=0)
