### ISSUE TITLE
Small bugs in new TA interface

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5971]
* arrow keys don't work from rubric.  
   - down & up arrow keys used to close current component, and open component above (up) or below (down).
   - left & right keys used to navigate to next or previous student (the arrows on the gui bar do work)

* In some cases, the panel layout does not correctly remember what content you have placed in each panel when you switch to next student.

(I might add more items if I remember something else)

**Comment by bmcutler** [comment]
@DefinitiveAbove @Kevin-MM @shailpatels 

Another small(?) bug with the Notebook display in the new TA grading interface:
When we first load the new interface, the Notebook form boxes are all empty/blank, even if the student did fill in answers.
Weirdly, when we click on the box, then the text appears.  But you have to "click" on each box.  
But perhaps on reload of the page, or load of the next and all future students, the textboxes are not blank.

And yet another bug related to notebook textboxes....  for the most part, the boxes are disabled and you can't type to edit the students answer in the box.  (That's good, of course.)  
But one of the TAs did manage to (accidentally) paste text from the clipboard into one of the boxes.   It didn't actually change the student submission, but it did display.    (reloading the page correctly reset the display).

Tagged Kevin & Shail since they worked on notebook display in ta grading.

**Comment by bmcutler** [comment]
Also, let's remove the animation that expands the TA grading content to full screen, hiding the top and left side bars.  This animation plays everytime you switch from one student to the next.  It might be helpful/interesting the first time, but it gets annoying after a while.

**Comment by bmcutler** [comment]
Also...  

dark mode needs revision -- student code / student answers is really hard to read  -- both for students taking the test, and for tas grading the test.

new ta grading interface:  more than 2 panels, the layout (which panel content in which position) is not saved / remembered when you go to the next student

**Comment by Kevin-MM** [comment]
Having to click each box to show is contents is a code mirror bug.  It is related to the code mirror being instantiated while the element is not visible.  I will look into this when I have a chance.
