### ISSUE TITLE
Irrelevant Dates (second values) change when editing Relevant Dates

### ISSUE THREAD

**Issue by semicolon-madness** [Submitty/Submitty#5980]
**Describe the bug**
Gradeables with type Checkpoint (simple data entry: full/half/no credit) have bugs when setting relevant dates for TA's and instructors: the seconds and minutes change when adjusting calendar dates for customizable categories.

**Expected behavior**
When selecting relevant dates, other information should not change.

**To Reproduce**
1. Start building a New Gradeable by selecting the "New Gradeable" option in the sidebar
2. Give it a title, unique ID, and select "Checkpoints (simple data entry: full/half/no credit)" as the type.
3. Select "Create New Gradeable"
4. Go to the "Dates" option in your new gradeable
5. Select "Show All Dates"
6. Change the Grades Released Date

**Configuration**
 - OS: [iOS]
 - Browser [firefox]

**Screenshots**
<img width="774" alt="Screen Shot 2020-10-26 at 6 43 33 PM" src="https://user-images.githubusercontent.com/60297067/97236620-d7191300-17bb-11eb-9753-b33857c7d598.png">

<img width="739" alt="Screen Shot 2020-10-26 at 6 43 46 PM" src="https://user-images.githubusercontent.com/60297067/97236624-d97b6d00-17bb-11eb-8f69-40d5ecb7d860.png">

<img width="828" alt="Screen Shot 2020-10-26 at 6 44 11 PM" src="https://user-images.githubusercontent.com/60297067/97236629-dbddc700-17bb-11eb-9d65-14fac1da1255.png">

**Comment by cjreed121** [comment]
The extra dates listed on this page after you click show all dates would be useless for a checkpoint gradeable. Show all dates shows every option even if you can't set it for that type of gradeable. This isn't necessarily a bug as those are essentially garbage data in this case.
