### ISSUE TITLE
.pptx submission gets extracted as if it were a zip

### ISSUE THREAD

**Issue by hbh7** [Submitty/Submitty#5995]
**Describe the bug**
When uploading a .pptx, Submitty appears to extract the file as if it were a zip (which I guess it technically is). 

**Expected behavior**
Submitty should really not be extracting the pptx as even though it's technically a zip, no one wants it to be extracted. 

**To Reproduce**
1. Visit gradeable submission
2. Click and drag .pptx file in 
3. Click submit
4. See a massive list of submitted files that were extracted out of the .pptx file

**Configuration**
 - OS: Windows 10
 - Browser: Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/5050375/97821032-dfbb8e80-1c7e-11eb-95bd-0754141211b5.png)
![image](https://user-images.githubusercontent.com/5050375/97821024-d4686300-1c7e-11eb-8b27-6dd6ba74a29e.png)

**Additional context**
This specific assignment has no autograding so I don't think that's part of the issue. 

Also, if I zip the pptx, then it unzips the zip and leaves the pptx alone as expected.

**Comment by hdrodz97** [comment]
I'm having issues reproducing this bug. Just like you, I'm on Windows 10 and using Chrome. Would you happen to know what version of PowerPoint was used to create the .pptx file in question?

**Comment by hbh7** [comment]
I think it was actually just downloaded straight from Google Slides through their Download as pptx functionality. Maybe they do something weird that regular PowerPoint doesn't?

**Comment by hdrodz97** [comment]
Yup, looks like Google Slides pptx files trigger this bug!

**Comment by hbh7** [comment]
Very interesting. I wonder what they do different with the formatting.
