### ISSUE TITLE
Add counter/timer indicating how long a student has been paused

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5996]
**What problem are you trying to solve with Submitty**
The intention for the queue pause feature was for a short period of time (use the restroom), it is not to allow students to hold a place in the queue for hours.

Let's add a timer to the pause feature, allowing TAs to manually remove from the queue a student who is abusing the pause feature (TAs can determine policy on how long is "too long").

**Comment by BenKelly99** [comment]
Should this timer display the amount of time a student has been paused in total or just the time of the most recent pause?

**Comment by bmcutler** [comment]
I answered @BenKelly99 s question in person months ago...  
My answer was "either, whatever is easy"

**Comment by bmcutler** [comment]
Also...  let's modify the on screen text facing the student when they pause themselves.
Define “overuse” of pause, and that teaching staff will remove students who are using pause other than intended.

**Comment by A3Digital** [comment]
The timer should display the total time paused that way a student can not just un-pause and re-pause to make it seem like they have not been holding their place in the queue for long.
