### ISSUE TITLE
Excused Absense Extensions:  # of days vs new due date

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6017]
When I use the Excused Absence Extension page (Mac Chrome, not sure it matters)
and I select a valid homework, enter a valid student and a number of days late 
(leaving the date field blank) I get an error.   This used to work....
In order to enter an extension I have to enter the extension by manually chosing the 
date the desired number of days after the deadline.

The original design was to allow the instructor to specify either the number of days OR
the new due date.

**Comment by Amoldreamer** [comment]
Hey@bmcutler, I am a new developer and want to make some contributions. I have done everything as per the instructions and I have been able to log into submitty. Despite the comprehensive description, I still have a lot of questions to ask. Some of the questions may be very basic. Would you like me to work on the project?

**Comment by satishhhh** [comment]
@bmcutler i want to work on this issue

**Comment by loadedskiffer** [comment]
could not reproduce

**Comment by loadedskiffer** [comment]
could not reproduce
