### ISSUE TITLE
New TA interface - view non-active version

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6070]
From the new TA grading interface, selecting a version other than the active version (not changing the active version by saying "Grade this version") jumps back to the old TA grading interface.

We're going to switch to the the new interface and remove the old interface soon (before Spring term) so this may be a non issue.  But we need to make sure this action doesn't cause problems.

**Comment by burnerlee** [comment]
@bmcutler could you please assign me this issue, I would like to work on this

**Comment by MasterOdin** [comment]
We cannot assign issues on GitHub to people outside our organization. Feel free though to start working on this as we do not have anyone actively looking into it.

**Comment by DefinitiveAbove** [comment]
#5859 removed the old TA grading interface, issue appears to no longer be present.
