### ISSUE TITLE
How to handle submission deadline / late day window / excused absense submissions

### ISSUE THREAD

**Issue by kmcnellis** [Submitty/Submitty#61]
- [x] a popup alert if they are after the deadline, but before the 2 day late day window has expired "hey you're going to use a late day if you click ok, hit cancel if you don't want to use a late day".
  
  note: the 2 day late day window might vary per class.  CS1 & DS allow max 2 late days per homework.  Other classes might allow no late days or a different size window.
  
  note2: an assignment with multiple parts calculates late days as the max late days across all parts of that homework.
- [x] a different popup alert of they are after the 2 day late day window "hey you're not supposed to submit unless you have an excused absense, hit ok if you have or believe you will soon receive a  formal excused absense for this homework or hit cancel if this was a  mistake".  (We allow late submissions,  even if the formal excused absense hasn't been received/processed by the instructor/TA).
- [x] clearly display the exact timestamp on the submission. (now it only displays # of days late)
- [x] better labeling of # of late days used for each version of the homework.  (it's not super clear now)
- [x] better documentation/labeling of how to "roll back".  If a student  wants to use an older version (either if was more corect or it used  fewer late days), they can do that now.  The TA grading server  automatically grabs the "active" assignment.
- [ ] a popup alert if you attempt to change the "active" assignment after the late day window has expired (TAs start grading at this point and we need to block changing the "active" version)
- [ ] In addition to the "released" true/false toggle in the config/class.json file (which both makes the assignment visible & allows submissions) it seems we need a "allow submissions"  true/false toggle that would leave the prior submission results & TA grade visible to students, but just not allow new submissions/changes to "active" assignment.  Some instructors want to allow submissions to old homeworks, some want to shut them off completely.  And this would ensure no accidental submissions to the wrong assignment.

**Comment by sihsob** [comment]
If it's passed a deadline, there should be a message about being late and need permission from instructor. Warning message about missing deadline

**Comment by bmcutler** [comment]
- [ ] a popup alert if they are after the deadline, but before the 2 day late day window has expired "hey you're going to use a late day if you click ok, hit cancel if you don't want to use a late day".

    note: the 2 day late day window might vary per class.  CS1 & DS allow max 2 late days per homework.  Other classes might allow no late days or a different size window.

    note2: an assignment with multiple parts calculates late days as the max late days across all parts of that homework.


- [ ] a different popup alert of they are after the 2 day late day window "hey you're not supposed to submit unless you have an excused absense, hit ok if you have or believe you will soon receive a  formal excused absense for this homework or hit cancel if this was a  mistake".  (We allow late submissions,  even if the formal excused absense hasn't been received/processed by the instructor/TA).

- [ ] clearly display the exact timestamp on the submission. (now it only displays # of days late)

- [ ] better labeling of # of late days used for each version of the homework.  (it's not super clear now)

- [ ] better documentation/labeling of how to "roll back".  If a student  wants to use an older version (either if was more corect or it used  fewer late days), they can do that now.  The TA grading server  automatically grabs the "active" assignment.

- [ ] a popup alert if you attempt to change the "active" assignment after the late day window has expired (TAs start grading at this point and we need to block changing the "active" version)

**Comment by bmcutler** [comment]
(tried to assign both marina & beverly)

**Comment by bmcutler** [comment]
Added new subtask:

In addition to the "released" true/false toggle in the config/class.json file (which both makes the assignment visible & allows submissions) it seems we need a "allow submissions" true/false toggle that would leave the prior submission results & TA grade visible to students, but just not allow new submissions/changes to "active" assignment. Some instructors want to allow submissions to old homeworks, some want to shut them off completely. And this would ensure no accidental submissions to the wrong assignment.

**Comment by bmcutler** [comment]
Closing.  Remaining open problems are in other issues.
