### ISSUE TITLE
Interest in contributing to Submitty :Installation issue

### ISSUE THREAD

**Issue by dilawari2008** [Submitty/Submitty#6111]
I am new to Submitty and I want to contribute. I faced issue with installation.
The process I followed was as follows:
enabled virtualization on windows 10
installed virtualBox,vagrant,ruby & git
installed vagrant vbguest
forked and clone repo
performed **vagrant up** inside the Submitty repo- returned **INSTALLATION FAILURE**
log file:[install_ubuntu_18.04.log](https://github.com/Submitty/Submitty/files/5742879/install_ubuntu_18.04.log)

although the virtual box shows Submitty-ubuntu as running.
![submitty screenshot](https://user-images.githubusercontent.com/40742522/103149122-a0945000-478c-11eb-85ef-e4031c4b6495.png)

**vagrant ssh** returns the following:
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-128-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantageWelcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-128-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Dec 25 22:47:24 EST 2020

  System load:  0.0               Processes:           97
  Usage of /:   2.4% of 61.80GB   Users logged in:     0
  Memory usage: 6%                IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.56.111

This system is built by the Bento project by Chef Software
More information can be found at https://github.com/chef/bento

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

Failed to start submitty_autograding_shipper.service: Unit submitty_autograding_shipper.service not found.
Failed to start submitty_autograding_worker.service: Unit submitty_autograding_worker.service not found.
Failed to start submitty_daemon_jobs_handler.service: Unit submitty_daemon_jobs_handler.service not found.
Failed to start submitty_websocket_server.service: Unit submitty_websocket_server.service not found.
Failed to start nullsmtpd.service: Unit nullsmtpd.service not found.

Please let me know where I need to correct.

**Comment by MasterOdin** [comment]
I posted this on slack, but copying it here:

The error you're getting within Vagrant is:

```
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 4h 19min 28s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 4h 20min 15s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 4h 21min 16s). Updates for this repository will not be applied.
```

This error happens because the system time of the machine (the Submitty VM in this case) is set to a time that's different from that of the real world. The VM is inheriting the system time of your host, so I would double check the time on your machine (and if using WSL2, be aware that the environment there can drift away from your host), restart your machine, and try again.

You could also look through the installation scripts and modify any usage of `apt-get update` to be `apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update` which would ignore the date mismatch.

**Comment by dilawari2008** [comment]
@MasterOdin Thnx. Its working.
