### ISSUE TITLE
late days table is not initialized 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#617]
In the past, every student started with a row in the table with allowed late days = the default allowed lates and a since_date with year 1970.

But there's nothing in the table.  (Is it because the students were added differently this year?)

**Comment by MasterOdin** [comment]
Every student added through the upload classlist feature is given a row in the late days table, this feature was not applied to the new method it would seem.

**Comment by bmcutler** [comment]
Instead of initializing, lets make the code use the default value form the course configuration page if the student doesn't have a row in late days.
