### ISSUE TITLE
Rainbow Grades fail to build due to Submini polls errors

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6177]
**Describe the bug**
Rainbow Grades build process results in a core dump

**Expected behavior**
Build finishes successfully, no errors are reported to stdout/stderr.

**To Reproduce**
1.  make pull
2.  make
3. See error

**Configuration**
 - OS: Ubuntu 20.04.2 LTS
 - Browser N/A

**Screenshots**
Build fails with the following errors:
```
/media/sf_sharp/psoft-s21/RainbowGrades/RainbowGrades-main/submini_polls.cpp:75:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<Student*>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
   75 |   for (int i = 0; i < students.size(); i++) {
      |                   ~~^~~~~~~~~~~~~~~~~
./process_grades.out by_overall
WARNING: invalid section 2
WARNING: invalid section 2
WARNING: invalid section 2
WARNING: invalid section 2
WARNING: invalid section 2
WARNING: invalid section 2
print it   Programming language                     2021-01-25      6 0   234   0
print it ERROR WITH Favorite IDE
process_grades.out: /media/sf_sharp/psoft-s21/RainbowGrades/RainbowGrades-main/submini_polls.cpp:33: std::ostream& operator<<(std::ostream&, const Poll&): Assertion `p.correct_options.size() > 0' failed.
make: *** [/media/sf_sharp/psoft-s21/RainbowGrades/RainbowGrades-main/MakefileHelper:107: overall] Aborted (core dumped)

```

**Additional context**
I just ran Rainbow Grades on another one of my courses with no issues. That course has Submini polls enabled but we did not have any actual polls created or run. For this course (the one I'm having trouble with), we have run Submini polls this semester already.

**Comment by BenKelly99** [comment]
@KCony It looks the assertion is caused by a poll with no correct answers? Do any of your polls have no correct responses? I'm making a change that will prevent polls from being created without a correct answer but you might need to fix your existing polls manually.

**Comment by KCony** [comment]
Yes, we have a poll that was meant to have no correct answers. We were just asking students what their favorite IDE is. Does that really make sense to force every poll to have a correct answer? I would doubt it...

**Comment by bmcutler** [comment]
@KCony Yes, you should always specify at least one correct answer,
or all answers as correct if it is a poll with no wrong answers.

**Comment by KCony** [comment]
@bmcutler Thanks! OK, so you can mark all of them as correct. Makes sense! I mean as simple as it may sound, it might be worth adding this to the Submini documentation. Two different TAs in two of my different classes were asked to create the polls, and none of them had the intuition to mark all answers as correct. Both of them left all the check boxes blank breaking my Rainbow Grades. :)
