### ISSUE TITLE
Queue Statistics Page Displays Too Many Digits

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#6179]
The averages on the queue statistics page show decimal seconds.  This is not needed and clutters the page excessively.  The averages could be reduced to only include hh:mm:ss times.

See the below screenshot for an example of the current behavior:
<img width="896" alt="Untitled" src="https://user-images.githubusercontent.com/16820599/106942790-969e2f00-66f2-11eb-9534-40f4ad647de7.png">

**Comment by rohitgeddam** [comment]
I would Like to work on this.
