### ISSUE TITLE
Allow diff viewer within TA grading to display side by side

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#618]
Seems to always stack actual (student) on top of expected (instructor), even when you zoom out and/or hide the right pane with the file viewer.

**Comment by MasterOdin** [comment]
The changes made in this commit c253e3bb6faced3a274f4dd48a5a6980a88ae579 to the student DiffViewer needs to be back ported to the TA side.

**Comment by bmcutler** [comment]
Student submission and TA grading should *SHARE* the same code to display the test case results.
