### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dilawari2008** [Submitty/Submitty#6183]
I had successfully installed submitty and it was up and running. But on performing a vagrant suspend(or restarting the system) and doing a vagrant up, it continues to give the following error.
/etc/update-motd.d/00-header: new permissions are rw-r--r-x, not rw-r--r--
 I am attaching the complete log file.
[install_ubuntu_18.04.log](https://github.com/Submitty/Submitty/files/5940624/install_ubuntu_18.04.log)

**Comment by MasterOdin** [comment]
If you suspend the VM, you will need to use `vagrant resume` to start it back up. If you do `vagrant halt`, then you can do `vagrant up`. I suspect doing `vagrant suspend` followed by `vagrant up` is causing Vagrant to try and reprovision the machine, which causes a number of issues.

**Comment by MasterOdin** [comment]
When you do an initial `vagrant up` from a blank slate (e.g. after you run `vagrant destroy`), does it run all the way through? Are you running just `vagrant up`, or are you doing `vagrant up --provision`? What version of vagrant are you using?

The log that you provided indicates to me that it's attempting to provision the VM for a second time, but that it's then crashing out during it. While we should look to make provisioning a second time work better, it's not the expected behavior on doing just `vagrant up` to bring back a suspended VM as it should check to see if the VM has already been provisioned, and if so, just resume the VM and do nothing else.

**Comment by dilawari2008** [comment]
I had performed a vagrant up after vagrant suspend because it was mentioned in the documentation:

To resume work on a VM that is suspended or halted:

vagrant up

I could not find vagrant resume in it.

When you do an initial vagrant up from a blank slate (e.g. after you run vagrant destroy), does it run all the way through? 
Yes,it succesfully runs submitty on the browser (localhost:1501) and the username password screen appears into which I could login.

Are you running just vagrant up, or are you doing vagrant up --provision?
When I did vagrant halt then did a vagrant up, it promted me to do a vagrant provision  (vagrant up --provision didn't do anything) after which the aforementioned error in the log happened.

What version of vagrant are you using?
2.0.3

I will try a vagrant resume after a vagrant suspend, but I would like to point out that a vagrant up after a vagrant halt was also generating the same error.
(A friend of mine was also trying the same and faced the same issue.)

It could be nice if you could tell me the  entire correct way of installation once.

I had performed the installation in the following way (ubuntu 18.04):
Enabled virtualization

installed ruby - sudo apt-get install ruby
ruby --version - ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

installed git - sudo apt install git
git --version - 2.17.1

installed virtualbox (from ubuntu software)

installed vagrant:
wget -c https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.deb
sudo dpkg -i vagrant_2.0.3_x86_64.deb

[this is a little different than the one mentioned in the submitty documentation because in the way mentioned in the documentation, installation of vbguest was throwing the following error:
conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
  Activated fog-core-1.45.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 1.45.0), 1.45.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)
]

installed vbguest - vagrant plugin install vagrant-vbguest

vagrant up

Please tell me the  entire correct way of installation once.

**Comment by MasterOdin** [comment]
Yeah, you should not use `vagrant provision` when resuming the VM, you should just be using `vagrant up` which will just boot up the VM to the state it was when you did `vagrant halt`.
