### ISSUE TITLE
Long Notebook Checkbox Options Render Inconsistent Widths

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#6194]
**Describe the bug**
When a notebook is using a `"type" : "multiple_choice",` question block with  `"allow_multiple" : true,` it will display options with checkboxes. When these options get longer, the checkboxes are variable widths as the text starts pushing some boxes further to the left.

**Expected behavior**
All checkboxes should be the same size and the start of all options should have the same horizontal positioning.

**To Reproduce**
1. Make a new gradeable with the config.json in the "Additional Context" section
2. Build the gradeable
3. View the page in Submitty by going to Submit

**Configuration**
 - OS: Windows 10
 - Browser: Screenshots from Firefox, but issue also happens in Chrome.

**Screenshots**
There are two screenshots - one with 5 options showing variable widths, and another that just has the 3 visibly different widths.

![NotebookCheckboxes_Obfuscated](https://user-images.githubusercontent.com/26691043/107724566-25421b80-6cb2-11eb-8b78-555affdd18e1.png)
![NotebookCheckboxes_Obfuscated_Fewer](https://user-images.githubusercontent.com/26691043/107724567-25421b80-6cb2-11eb-8f95-ba5d72f3a484.png)

**Additional context**
To make the screenshots above you can use the below [nearly] MWE:

```
{
    "hide_submitted_files" : true,
    "hide_version_and_test_details" : true,

  
    "notebook" : [
        {
            "type":"markdown",
			"markdown_string":"### Syfpex kdk tl ztu ltpebhbnc hvvndupanv xxfc nbk _onpe_ fpsyp Dkrc Szbyxeggef Lft Shptr Ggerz yriviwvleo:"
        },
        {
            "type" : "multiple_choice",
            "allow_multiple" : true,
            "choices" : [
                {"value":"a", "description":"Ia I hqqr sqdkec yy pwb tlecbv tqpjnimt vfj mmkyyk wghlmght opa 3 cijsmtvkcku fxjnka vv ydjedchj bce parel cgfre wrgz kaevw, I eoc leey eoel xz bocavy psmdks pxejy mi Tjzrxtzw xi whyrlla nofn ofnxql qil wotxo yzfnwlklkly."},
                {"value":"b", "description":"Iz csnhfmr fdrfx ra ugh WmuEn URL upe rmxeujz eya qtpfm vhsxt I cqb xbp xxup larhpx cyjjphoc hurgo mndxm wyyo dfvbsg wxg oiu uqo xpdqqeme qml cyf napgu vuqvrczaqk fp xtqkdhf."},
                //{"value":"c", "description":"Ia I ymwr v pfalnyjdjy fswvdixj ekyh q tjysvylw lut xenm, I dde piixpgf bg tktgdiff iej TA ppad ms pkiujcw (t.b., 7 jrxc bg dqbqkwd) cal fogw hddqrwclzkkb ej pxdqkr cdd lipzhvamuxk gxrpda tybsxx qnrtc."},
                {"value":"e", "description":"Liv ikuva maxwg mfslfiwcza iv rstzhvxy.  Ceesacrzaj hb ket pnavt hmrkf fgmecswmm atlt nzax xw phsbvj nazffb wd co qnluh ozuht ey esb ntoxyw."}/*,
                {"value":"f", "description":"I yn ovdznylg lp uyzd *zuk bdqdrejtfy zdmdodd* rz kdutmz te ezrfm, hnmugk sg knipe, xdx vlc uqsluh bxxhosx fi lnrdrql yzb ojsxfxwzodw kb atao fvmfpr do ltmugtfy uzn zxnxv gcxac WsuEl datzwatz." }*/
            ],
            "filename" : "Q04.txt",
            "testcase_ref" : "Q04"
        }
        

        
    ],

    "testcases" : [
   ]
}
```

**Comment by williamjallen** [comment]
Is this still an issue?  I am unable to reproduce it on macOS Safari and macOS Chrome latest versions.

Here's what it looks like for me now:
![Untitled](https://user-images.githubusercontent.com/16820599/122573057-5e9de580-d01c-11eb-95df-62a424ae3c34.png)

**Comment by holzbh** [comment]
Can confirm on latest version of `master` with Windows 10/Firefox 89.0.1 and Chrome 91.0.4472.101 that this looks correct now.
