### ISSUE TITLE
Inline page view of some or all files (README.txt, specific code files, all *.h files, etc.), as specified by instructor/TA

### ISSUE THREAD

**Issue by kmcnellis** [Submitty/Submitty#62]
Already implemented?
- [ ] Need documentation on the wiki (need to decide where)
- [ ] Need samples of configuration (it's in the class/config.json, right?) of how to allow this, what wildcards are allowed, etc.
- [ ] Automated tests(?)

**Comment by sihsob** [comment]
Add documentation

**Comment by bmcutler** [comment]
Already implemented?
- [ ] Need documentation on the wiki (need to decide where)
- [ ] Need samples of configuration (it's in the class/config.json, right?) of how to allow this, what wildcards are allowed, etc.
- [ ] Automated tests(?)

**Comment by bmcutler** [comment]
this was implemented in "filecontent_display" and related commits (but the code may have been commented out or deleted with the big overhaul

**Comment by bmcutler** [comment]
Design change, partially handled.  Will open a new issue if other functionality desired.
