### ISSUE TITLE
Student Information is not displayed in any of the panels

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6206]
**Describe the bug**
Student information is not displayed anywhere in the grading interface.

**Expected behavior**
Student information should be displayed in the selected panel.

**To Reproduce**
1. Navigate to the gradeable page: https://submitty.cs.rpi.edu/courses/s21/csci4960/gradeable/hw01/grading/grade?who_id=sGdZb5KNNNjMVsC&sort=id&direction=ASC
2. Click on Student Info and select any of the options for the panel.
3. Observe the panel selected in step 2 filled with gray background with no information about the student

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Firefox 85.0.2 (64-bit)

**Screenshots**
Attempting to display Student Info in any of the panels (screenshot below shows bottom right panel as an example):
![image](https://user-images.githubusercontent.com/7108039/108002853-de5c6a80-6fbe-11eb-997a-51bf0106e6f2.png)

just leaves the panel empty:
![image](https://user-images.githubusercontent.com/7108039/108002890-f7651b80-6fbe-11eb-88ff-0b7a6fbcf73b.png)

**Additional context**
Peer grading is enabled for this gradeable.

**Comment by loadedskiffer** [comment]
Could not reproduce issue. Tested in chrome, edge and firefox with multiple different panel combinations.
