### ISSUE TITLE
Link to google group not working

### ISSUE THREAD

**Issue by erelsgl** [Submitty/Submitty#6208]
**Describe the bug**
In the "contact us" page: https://submitty.org/index/contact
when I click this link  https://groups.google.com/forum/#!forum/submitty
I get an error message "content is not available".

**Expected behavior**
The link should bring me to a page where I can register to the group.

**To Reproduce**
1.  Open a private browser window
2.  Open this link: https://groups.google.com/forum/#!forum/submitty
3.  See error

**Configuration**
 - OS: Windows
 - Browser: Firefox

**Screenshots**
![image](https://user-images.githubusercontent.com/1462215/108114468-80ed1a00-70a1-11eb-9e17-dfb2c7d03ad3.png)

**Additional context**
An additional issue with this page is that it is not clear to which email address I should send questions: submitty@googlegroups.com or  submitty-admin@googlegroups.com or both?

**Comment by MasterOdin** [comment]
Thanks for bringing this to our attention. The group itself was not super high traffic, and so we missed that Google had updated their permission settings. However, to make it easier for us to keep on top of things, we're going to just move to [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) as then it's consolidated into this repo and not another disparate thing to keep on top of. I've activated the setting, and am in the progress of updating our docs, which once done, I'll close this issue.

**Comment by sagnik3788** [comment]
@bmcutler can I work on this issue ?

**Comment by MasterOdin** [comment]
Nothing to do on this issue, we've since gotten rid of the link to google groups, and direct people to file issues or use slack instead.
