### ISSUE TITLE
need default value for "unblinded grading?" on windows firefox

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6231]
Report:

on windows firefox, for a new gradeable that will use manual grading,
the grader assignment tab appears to have no default value for "blinded or unblinded" grading.

tagging @holzbh

**Comment by holzbh** [comment]
Windows Firefox screenshot from live tonight - I just did Create Gradeable -> changed the name, id, category, and clicked Checkpoint grading. Once the gradeable was created I went to the Graders tab:

![image](https://user-images.githubusercontent.com/26691043/108798206-3f55e680-755b-11eb-899a-5e10314dcdaf.png)
