### ISSUE TITLE
generating peer matrix error checking on omitting # of students

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6232]
**Describe the bug**
Peer matrix tab:  
When I go to generate a peer matrix, but if I leave the "number of students" box empty, I get a spinning icon that just hangs.  Not sure what it is thinking so hard about.  It should be an error...   The number of students should be required to create a peer matrix.

**Comment by loadedskiffer** [comment]
@bmcutler I have been trying to reproduce this error but every time I leave the number of students box empty, it clears the matrix and no error occurs. The circle spins for a second and then goes away. I tested on Chrome, Edge and  Maybe this was fixed in another PR?
