### ISSUE TITLE
Allow users to type alternate answers / "other" for Submini Polls

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6236]
**What problem are you trying to solve with Submitty**
If enabled:  students can add alternate Submini poll answers.

These newly added items can be selected by other students.
These should be displayed on the graph.
The instructor can decide whether they are worth credit.
The instructor can edit the text and/or delete these answers (like regular poll answers).
Custom poll responses store the author in the database in case it is necessary.

**Comment by BenKelly99** [comment]
Do these responses need to be designated as different from normal responses? i.e. on the instructorUI, should it differentiate between pre-made responses and "other" responses, or can submitting an "other" response simply add an extra response to the database that the instructor can edit like they would any other?
