### ISSUE TITLE
Office Hours Queue doesn't get updated

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6237]
**Describe the bug**
Office Hours queue notifications are enabled but when new students join the queue no notifications are shown and the queue is not even automatically updated to show the names of the newly added students. Those new names would only appear after I either forcefully reload the page or interact with some controls on the page (e.g., click the "Finish Helping" button for the student who is currently being helped).

**Expected behavior**
Notifications when enabled should appear immediately when a new student joins the queue. The queue should be automatically refreshed to immediately show the newly joined students.

**To Reproduce**
1. Navigate to the page: https://submitty.cs.rpi.edu/courses/s21/csci4380/office_hours_queue
2. Refresh the page until someone appears in the Office Hours Queue.
3. Click Help to start helping that student.
4. Another student who just joined the queue sends an email complaining that Submitty shows them that there are 0 people in front of them in the queue but they are not being helped. 
5. I have had no notifications in my browser from Submitty.
6. I check the Submitty page referenced above.
7. The page only shows the student being helped but not any of the newly added students.

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Firefox 85.0.2 (64-bit)

**Screenshots**
Here is the state of the queue when it doesn't show newly added students:
![image](https://user-images.githubusercontent.com/7108039/108925105-fc068100-7609-11eb-84b8-34189febac8d.png)

**Additional context**

**Comment by shailpatels** [comment]
For some reason, the websocket server is immediately closing after connecting, on my vagrant I'm seeing the following:
```
WebSocket: connecting to ws://localhost:8443/ws        websocket.js:41:17
WebSocket: connected                                                    websocket.js:44:21
WebSocket: Closed                                                          websocket.js:69:29
```

@KCony Do you see something similar? You can check by going to the office hours queue, inspect element, and going to the console tab either on chrome or firefox.

**Comment by KCony** [comment]
@shailpatels This is what I get:

```
WebSocket: connecting to wss://submitty.cs.rpi.edu:8443/ws websocket.js:41:17
WebSocket: connected websocket.js:44:21
Cannot play media. No decoders for requested formats: audio/wav, audio/x-wav office_hours_queue
Cookie “collapse_sidebar” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite server.js:1521:8
```

However, I did click the "Enable notification" button several times after I experienced the problem described above and made the screenshots. I also do not have any new students in my office hours right now.

**Comment by KCony** [comment]
@shailpatels This is what I get:

```
WebSocket: connecting to wss://submitty.cs.rpi.edu:8443/ws websocket.js:41:17
WebSocket: connected websocket.js:44:21
Cannot play media. No decoders for requested formats: audio/wav, audio/x-wav office_hours_queue
Cookie “collapse_sidebar” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite server.js:1521:8
```

However, I did click the "Enable notification" button several times after I experienced the problem described above and made the screenshots. I also do not have any new students in my office hours right now.

**Comment by KCony** [comment]
I collected some additional screenshots. The Google Chrome shows that a student is in the queue. The Firefox shows the instructor view of Submitty with an empty office hours queue.

![s21-csci4380-SubmittyOH-01](https://user-images.githubusercontent.com/7108039/116758129-758d6780-a9dd-11eb-9524-07cd10debda5.jpg)
![s21-csci4380-SubmittyOH-02](https://user-images.githubusercontent.com/7108039/116758131-7625fe00-a9dd-11eb-935e-92899cb784aa.jpg)
![s21-csci4380-SubmittyOH-03](https://user-images.githubusercontent.com/7108039/116758132-76be9480-a9dd-11eb-8436-3b25559c0bc3.jpg)
![s21-csci4380-SubmittyOH-04](https://user-images.githubusercontent.com/7108039/116758134-77572b00-a9dd-11eb-8a98-73cadd78084d.jpg)
![s21-csci4380-SubmittyOH-05](https://user-images.githubusercontent.com/7108039/116758136-77efc180-a9dd-11eb-8669-09120db5bc04.jpg)
![s21-csci4380-SubmittyOH-06](https://user-images.githubusercontent.com/7108039/116758139-77efc180-a9dd-11eb-811b-353da7590754.jpg)
![s21-csci4380-SubmittyOH-07](https://user-images.githubusercontent.com/7108039/116758141-78885800-a9dd-11eb-9d79-a69678cb39ff.jpg)
![s21-csci4380-SubmittyOH-08](https://user-images.githubusercontent.com/7108039/116758142-7920ee80-a9dd-11eb-92df-40e6fbbd1092.jpg)

**Comment by A3Digital** [comment]
I am currently trying to recreate this bug of the queue not updating but have had no success thus far. However, my notifications do not seem to be working either so I'll look into that in the meantime.
