### ISSUE TITLE
Usability improvements suggestion for the Office Hours Queue page

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6238]
**Describe the bug**
A usability issue on the Office Hours Queue page dos not allow to determine if Notifications are enabled or not. Same for the audible alerts.

**Expected behavior**
The interface should make it visually very clear what the state of the option is (enabled or disabled).

**To Reproduce**
1. Navigate to https://submitty.cs.rpi.edu/courses/s21/csci4380/office_hours_queue
2. Observe the state of the notification button that says "Enable Notifications".
3. Does it mean that notifications are enabled now or does it mean that they will become enabled if I click the corresponding button? There are no visual cues (the button doesn't go up and down or doesn't get raised or lowered) when it is pressed. Only the text changes but the text is confusing as mentioned above. The only way to tell what action is going to happen if I press the button is to click it and read the pop-up notification with "Notifications have been disabled". If this is not that I wanted, then I would click the button one more time.
4. Observe the state of the button with a bell crossed out.
5. Does it mean that audible alerts are disabled now or does it mean that they will become disabled if I click the corresponding button? There are no visual cues (the button doesn't go up and down or doesn't get raised or lowered) when it is pressed. Only the icon changes but the icon is confusing as mentioned above. Unlike the notification button which generates a pop up notification when clicked, operating the audible alert button does not bring to life any notifications.

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Firefox 85.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/108926135-ce223c00-760b-11eb-8d80-d80dc14bea70.png)

**Additional context**
I suggest improving the usability of this page by providing clear and unambiguous visual cues as to the state of notifications and the audible alerts. Perhaps, using "sticky" toggle buttons that are visually either raised or lowered and a corresponding text that matches this new behavior, e.g., "Notifications enabled"? This way, it would be clear that if the button is lowered, i.e., ON, the notifications are enabled and when the button is raised, i.e.,  OFF, the notifications are disabled.

Or perhaps a more suitable widget for both notifications and audible alerts may be used, like this one:
![image](https://user-images.githubusercontent.com/7108039/108926686-e050aa00-760c-11eb-8228-335b20cacd48.png)

**Comment by wusatosi** [comment]
I agree with this!! as a mentor, I am often confused with what is the actual state of the notification!
