### ISSUE TITLE
No options are displayed in the "Choose an autograding configuration" field of the gradeable

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6239]
**Describe the bug**
When creating a gradeable, on the "Submissions/Autograding" tab, no drop-down list with options for the gradable configuration is shown. No arrow is displayed either.

**Expected behavior**
There should be an arrow displayed next to the red cross in the gradeable configuration selection list. The arrow when clicked should open a drop-down list of options.

**To Reproduce**
1.  Navigate to https://submitty.cs.rpi.edu/courses/s21/csci4380/gradeable
2. Fill out the required fields
3. Click Create New Gradeable
4. Click the red cross to the right of the configuration name (see screenshot 1)
5. No arrow is shown. No drop-down list is displayed (see screenshot 2). The arrow is supposed to invite the user to click it to open the drop-down list with options to select from.

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Firefox 85.0.2 (64-bit)

**Screenshots**

![image](https://user-images.githubusercontent.com/7108039/108927186-d1b6c280-760d-11eb-999a-aec4e74b651c.png)
![image](https://user-images.githubusercontent.com/7108039/108927225-e09d7500-760d-11eb-9478-8cad21ed22af.png)

**Additional context**
N/A

**Comment by bmcutler** [comment]
I just tested this on Mac Chrome...  feature appears to work as before.
But on Mac Firefox...  I see the problem described above, the dropdown feature is missing.

Note: This UI is clumsy and confusing and needs a redesign.
(I thought we might have had a related open issue, but I can't find it quickly)

**Comment by MasterOdin** [comment]
Looking into this, it appears to be a quirk of how the [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) tag we're using works. On Chrome (and Safari?), it'll show an arrow that you can use to trigger the dropdown, but on firefox, there is no arrow and you need to click twice in the text input to trigger the dropdown.

I agree it would be good to replace the usage of datalist here with a select or something else more standard (or a proper custom JS/CSS widget that gives uniform usage across platforms).
