### ISSUE TITLE
The administrator account set during installation cannot be logged in

### ISSUE THREAD

**Issue by alonegg** [Submitty/Submitty#6303]
**Describe the bug**
The administrator account set during installation cannot be logged in
Already searched the entire installation instructions and couldn't find them, so maybe I'm missing something, but if I am, please let me know.
Installed via aws' ubuntu 18.04 and the whole process went smoothly.
I entered something like localhost when installing, I chose database when setting the authorization mode, and I entered the appropriate content when setting admin&pass.
However, after completing the installation, I couldn't log in with the password I entered before.
I reopened a new ec2 and found the same problem.
Can someone kindly tell me what the problem is, whether it is a bug or I have set it up wrong?

**Expected behavior**
Installed via aws' ubuntu 18.04 and the whole process went smoothly.
I entered something like localhost when installing, I chose database when setting the authorization mode, and I entered the appropriate content when setting admin&pass.
However, after completing the installation, I couldn't log in with the password I entered before.
I reopened a new ec2 and found the same problem.

**To Reproduce**

- What authentication method to use:
1. PAM
2. Database
Enter number?: [1] 2

- What is the submitty admin username (optional)? : 
- What is the submitty admin password: 

**Configuration**
 - OS:Ubuntu18.04 on AWS
 - Browser [chrome&safari]

**Comment by bmcutler** [comment]
Your message is unclear, where were you trying to use this admin username & password?  ssh to the machine or through the website?

The admin username & password you are prompted for is for an optional website user. If you add that admin user as an "instructor" level user in each new course, then the admin user will have access to all of the courses for tech support, and also some nightly cron tasks are streamlined (rainbow grades, plagiarism).  You may even need to manually create that user before it can be used.
https://submitty.org/sysadmin/course_creation

This database password does not give access to the machine via ssh, that's standard linux login management.  The installation scripts don't make admin users or set their passwords.  The installation scripts create a submitty_php and submitty_daemon user -- but I believe those accounts do not have passwords, they are not full users.

[Apologies if I've mis-stated anything.]
