### ISSUE TITLE
Odd behavior on returned exams where version chosen to be graded is not the final version

### ISSUE THREAD

**Issue by Xystem4** [Submitty/Submitty#6306]
Not a Submitty contributor, but wanted to point out some strange behavior I noticed when I recently got back an exam using it.
**Describe the bug**
When taking an exam on Submitty, if you make some changes to your answers and choose submit, but then switch to a previous version and select the "grade this version" option, when the graded exam is returned it will be shown strangely.

At the bottom of the page in the "Select Submission Version" box, the last submission will be shown as selected, with the "GRADE THIS VERSION", even though it was not the one actually selected. The answers in any textboxes or multiple choice questions will also show the answers given in that final submission. Switching to a different submission version and then back to this one will change the answers in the boxes back to the actual answers submitted, but the wrong version number will still be marked as "GRADE THIS VERSION".

I'm not quite sure what the expected behavior is here (the existence of the "Use Most Recent Version" buttons confuses me), but as a blank slate user what I would expect to happen would be this: The actual submitted version would be shown in the submission version box as "GRADE THIS VERSION" (even if it is not the last one submitted), and all text boxes/multiple choice questions show the answers given in the version graded by the instructors (*not* the last answers given but the ones chosen to be graded). I wouldn't expect to see a "use most recent version" button at all, but I could imagine maybe a button that allows you to look at your last submission's answer.

**Configuration**
 - OS: Windows 10
 - Browser Chrome

P.S. the text formatting on grade inquiries is broken too

**Comment by bmcutler** [comment]
I believe this is related (or even duplicate) to issue #6080

**Comment by bmcutler** [comment]
Make sure to talk to @loadedskiffer about who is going to do this, before starting implementation.
