### ISSUE TITLE
Create test course with submissions that'll always be in certain category

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#631]
Right now, the vagrant machine creates 4 dummy courses that are useful for demoing various properties of the autograder. We should add a course that has all three types of gradeables in all possible sections of navigation (future, ta beta testing, open, closed, open to grading, grades released) where it's impossible for the gradeable to leave that section on its own.

**Comment by MasterOdin** [comment]
There should also be courses that have no gradeables in each given assignment.

**Comment by bmcutler** [comment]
Is this done?

**Comment by bmcutler** [comment]
This is done.  Can be re-opened with more specifics if necessary.
