### ISSUE TITLE
Improvements for SQL toolbox

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6362]
SQL Toolbox looks great!  Yay!  

Small tweaks/suggestions:

* When the query output table is large, with lots of columns, the right edge would be better with some padding/margin.  This will make it more obvious that the data is horizontally scrollable.

* Add an option to download the CSV of the table data.  (Copy paste into a spreadsheet may or may not correctly grab all of the data, so CSV download would be more helpful.)

* Consider adding a left column that is the line# for the output.  This would be helpful when the instructor is curious how many rows of data are returned for a medium large query.   Or if this is easy to add into the query itself, we could just document this bit of SQL on our general submitty.org documentation page for this feature with sample useful queries (documentation not yet written... )

edited to add:

* When a query runs successfully but the result is empty (no rows), it can be confusing...  are we waiting for the query to finish and the results to be displayed?  Or is the result *nothing*?  Maybe let's display an explicit note in this case.

**Comment by MasterOdin** [comment]
Broke this issue up into individual issues to make easier to follow the "close an issue per PR" style. The issues are:

* query output table padding: #6373 
* option to download CSV from table: #6374 
* show row number in leftmost column: #6372 
* display message on finishing a query with no results: #6375
