### ISSUE TITLE
Peer Grading - Solution/TA Notes & Grade Inquiry

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6366]
**Describe the bug**
The Solution/TA Notes panel displays both peer and non peer components are displayed to peers.

The non peer components should only be displayed to instructors & full/limited graders.

ALSO...  the Grade Inquiry panel should never be displayed to peer graders

**Comment by HenrikLam** [comment]
I have a small question, by grade inquiry panel do you mean the empty slot under the grading index or is there a grading inquiry button? If it's the button I am unable to find it, could you tell me the steps to reproduce this bug?

**Comment by shailpatels** [comment]
> I have a small question, by grade inquiry panel do you mean the empty slot under the grading index or is there a grading inquiry button? If it's the button I am unable to find it, could you tell me the steps to reproduce this bug?

@HenrikLam Grade inquiries need to be enabled first, 

1. Go to course settings, and tick the " Grade Inquiries Allowed " check box
2. Go to a gradeable list and press the pencil icon to edit it
3. Then select 'yes' for "Should grade inquiries be enabled for this assignment?" under the general tab
4. You should see the grade inquiry pannel option under that gradeable's TA grading page now
