### ISSUE TITLE
Diff Viewer for TA grading does not display on Firefox

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#637]
Just a blank box.
Does seem to work on Chrome.

(report from a TA user)

**Comment by MasterOdin** [comment]
This is most likely the version of jQuery that is used not working with the latest Firefox version that graders have, which means the resize window code fails to work so the iFrame always just has a height of 0px. We need to update jQuery to a newer version and see if this is fixed.

**Comment by bmcutler** [comment]
Closing, I assume this will be fixed with the port to the new code base (& using the student version of the code).
