### ISSUE TITLE
Print row number in SQL Toolbox table

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#6372]
**What problem are you trying to solve with Submitty**

For a table with many rows, it can be tough to know which number row you're looking at.

**Describe the way you'd like to solve this problem**

A new column should be added to the left of the table that shows the row number. This should be calculated as we insert the rows into the DOM.

**Comment by callapa1** [comment]
Hello, I'm a beginner and I'd like to take this issue. I already found the related .js file
