### ISSUE TITLE
Add padding around SQL Toolbox table

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#6373]
**Describe the bug**

The sides of the SQL Toolbox table collides with the border of the box container that surrounds it.

**Expected behavior**

There should be some padding between the table and the sides of the container.

**Comment by swayamg20** [comment]
Hi, I am interested to try on this bug, as this will be my first participation ever in any open source project, I am little bit unclear about how to start and where to find the respected file of code to be edited, I understood you bug and I think I can solve it, please guide me.

**Comment by MasterOdin** [comment]
To find the code, you would want to first find the related controller function that is used. To do that, you would want to search for the static bit of the URL at the very end of it, in this case it's `/sql_toolbox`. This leads you to [this function](https://github.com/Submitty/Submitty/blob/master/site/app/controllers/admin/SqlToolboxController.php#L26-L28). From there, we see that it returns a `WebResponse` that utilizes the [`showToolbox`](https://github.com/Submitty/Submitty/blob/0f11c72ad08d566409724c67d8a0022c8cb9b75e/site/app/views/admin/SqlToolboxView.php#L10-L18) function in [`SqlToolboxView`](https://github.com/Submitty/Submitty/blob/0f11c72ad08d566409724c67d8a0022c8cb9b75e/site/app/views/admin/SqlToolboxView.php). From here, we see that it loads a couple of CSS and JS files specific to this page, and then renders the twig template [`admin/SqlToolbox`](https://github.com/Submitty/Submitty/blob/0f11c72ad08d566409724c67d8a0022c8cb9b75e/site/app/templates/admin/SqlToolbox.twig). From here, you would look to modify some combination of the JS, CSS, and Twig files to add the padding.
