### ISSUE TITLE
Migrate JS files to ts/mjs

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#6404]
**What problem are you trying to solve with Submitty**

Currently, all our JS usage within Submitty is using old style JS includes in the page, and we have our scope leak all over the place, having to also manually annotate files with a `/* exported */` and `/* global */` directives for eslint to understand what might be dropping through scripts.

**Describe the way you'd like to solve this problem**

A better way to handle this mess would be to make use of the module system that all modern browsers now support (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), and is inline with how most people write JS these days. The JS files would get loaded as modules in the HTML, and then we have regular import / export statements within the files, giving us understanding of where functions / classes are coming from, while also allowing the IDE to provide more meaningful intellisense.

A side effect of this is that we can leverage the import / export syntax to also write proper unit testing for the JS files without resorting to any ugly shims or scope leakage in the test suite.

**Additional context**

This issue isn't necessarily to track the full scope of effort to do this project, but to gain feedback from developers on if we should do (or should not) do this, any potential pitfalls, etc. The actual migration process would most likely be more drawn out and take a while, doing it gradually overtime as it would require rewriting the hooks of the JS into the DOM that currently exist in a lot of places.

**Comment by shailpatels** [comment]
I support moving to modules

I think a possible issue would be with the `addInternalJS` functions, would the versioned file be able to be used in the JS `import` statement?

**Comment by wusatosi** [comment]
I see all the code related to #6421 has been moved to the TS folder, so is `ts` modules favored over `mjs` modules, and `mjs` modules have been deprecated? Do we need to update this issue? @MasterOdin

**Comment by MasterOdin** [comment]
The basis for this was accomplished in #7285 with documentation in Submitty/submitty.github.io#392. Now it's just a matter of slowly transitioning the code over, but we don't need a meta issue to track that.
