### ISSUE TITLE
TA grading diff viewer occasionally not showing

### ISSUE THREAD

**Issue by JerameyATyler** [Submitty/Submitty#641]
In some instances the diff viewer on the ta grading side does not display the expected output.

* Currently test cases that are configured to not show the diff viewer to students also do not show the diff viewer to graders. The diff needs to be displayed for graders.

**Comment by MasterOdin** [comment]
Any more details on when this happens, what's supposed to show, what was trying to be shown, etc

**Comment by JerameyATyler** [comment]
Look at HW 1 output test 6 for DS. It looks like it doesn't appear for any student.

**Comment by JerameyATyler** [comment]
The issue is that the diff viewer is configured to not be visible for the student but it is also not visible to the grader.

**Comment by MasterOdin** [comment]
Discussed, not an issue with the diff viewer. There is no expected file for the diff viewer to even show.
