### ISSUE TITLE
Intrusive red background color on late submissions

### ISSUE THREAD

**Issue by HenrikLam** [Submitty/Submitty#6410]
**What problem are you trying to solve with Submitty**
Red background for Submitty grading interface is very intrusive and many have complained about it.

**Describe the way you'd like to solve this problem**
I would like to possibly remove the red background, and possibly introduce a new way to alert the TA if the red banner is not currently enough by itself. 
**Additional context**
![image](https://user-images.githubusercontent.com/49821332/118153247-af01a200-b3e3-11eb-8a33-e8d5b610111e.png)

**Comment by williamjallen** [comment]
I agree that the background is rather ugly and over the top here.  The giant red and yellow box right under the navigation controls should be more than enough of an indication to the grader that this is a late submission.

**Comment by MasterOdin** [comment]
I would like to see @bmcutler weigh in here (or someone reiterate what she might have said in person if this was brought up in a meeting), but the intrusive color was picked by design to be a jarring effect so that a TA would notice. This is especially true where one can get into a bit of an "auto-pilot" when grading 100+ submissions.

**Comment by bmcutler** [comment]
It is meant to be obnoxious.  

Different instructors have different policies for what to do when an assignment is submitted "too late".  Some ask the TA to grade it anyway, the student may have a pending excused absense that will be processed retroactively and it's best for the TA to grade it right now, while the rubric standard is fresh in their mind.  In other courses, the TA is instructed to ignore late work.

Let's save this visual redesign for future work.  I'm more concerned with the logic bugs we may still have in when this message/rendering style is displayed, and possible (slow) performance of loading the page information.

**Comment by bmcutler** [comment]
Issue #6205 is an example of the bugs we have with grading & late days.

We calculate and display the percentage of grading completed in several places.
* on the main "gradeables" page, there is a progress bar under the "Grade" button for a specific assignment
* on the statistics page summarizing the grading for the assignment 
* when grading a specific student, there is a progress bar

We are not consistent about whether students who have "too late" (or cancelled) assignments are included in these stats.
