### ISSUE TITLE
SQL Toolbox on page DB Schema documentation

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6418]
**What problem are you trying to solve with Submitty**
An instructor who knows SQL syntax, but doesn't know the exact details of the Submitty course DB has to go digging through our .sql file (currently 2200 lines long):
https://github.com/Submitty/Submitty/blob/master/migration/migrator/data/course_tables.sql
Or squint at an out of date entity relationship diagram
https://submitty.org/developer/database_design

Or they could type a query like this:
```
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND 
    schemaname != 'information_schema';
```
(from https://www.postgresqltutorial.com/postgresql-show-tables/)

And then to get the field names & types of a table:
```
select column_name, data_type from information_schema.columns where table_name = 'users';
```

Note, when I'm directly logged into a DB, I usually do
```
select * from users where false; 
```
just to remind myself of the exact column names --> it prints the column headings with no rows of data.  But in our SQL Toolbox, currently nothing gets printed as a result of this query, not even the column headings.

**Describe the way you'd like to solve this problem**
Instead it would be great to have up-to-date basic documentation on this page.
* Maybe right underneath the title "SQL Toolbox" is a button/expandable/link titled "Database Schema Documentation".  When you click on that button, you get a simple list of the 43(current # of) tables in the database.
* Each one of the table names is now clickable/expandable, and when you do, you get a simple list of the fields.

**Describe any potential alternatives you'd tried to solve the problem**
Alternatively we could just put a link to submitty.org, a link to the .sql file, and try to keep the ER diagram up to date.  But it does depend on the exact version of Submitty installed -- our field names & types change occasionally.  So generated/onserver docs would be better.  Docs could be generated on each click, or written to a markdown file when we INSTALL_SUBMITTY.sh.

...  I'm sure this type of simple docs have been made before, please use a standard tool if one exists :)
Thoughts @MasterOdin ?

**Comment by MasterOdin** [comment]
It should be quick and easy enough to generate the information on the fly that I would just go that approach, as you can use a single query to get the information easily enough (`SELECT * FROM information_schema.columns WHERE schema='public'`, see https://www.postgresql.org/docs/9.5/infoschema-columns.html) and then iterate over that result set to get the list of unique table names and their columns. The returned info should also almost certainly always be small enough to not worry about data or speed issues on generating it.
