### ISSUE TITLE
Attachments Toggle Button not working as expected

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#6445]
**Describe the bug**
When on a thread inside the discussion forum, you can click attachments from the dropdown menu which is supposed to toggle all attachments on current thread. When clicked it opens all attachments and does nothing on repeated clicks.

**Expected behavior**
Since this is a toggle button, repeated clicks on this button should open or close the attachments.

**To Reproduce**
1. Open a thread in the discussion forum that contains a few attachments. (Example: Thread 8 in Sample)
2. Click attachments and all attachments will open
3. Click attachments again and nothing will happen

**Configuration**
 - OS: Linux
 - Browser: Chrome

**Comment by williamjallen** [comment]
I also noticed that the number next to the attachments shows 0 for all posts.  I will investigate this issue as well.
