### ISSUE TITLE
Dates on Polls Summary Page

### ISSUE THREAD

**Issue by sbelsk** [Submitty/Submitty#6451]
**What problem are you trying to solve with Submitty**

- [ ]  Future polls on the instructor's Polls Summary page should be displayed/sorted in chronological order with the nearest release date on the top. Currently, the poll with the farthest release date is at the top, so if an instructor has many polls ready ahead of time and wants to see or edit the poll with the nearest release date, they have to scroll to the bottom of the page

- [ ]  The date formats should be changed to MM-DD-YY or to the standard way Submitty displays dates. Currently, dates on this page are displayed as YY-MM-DD

Example where polls are displayed with the wrong date format and sorted chronologically but backwards:
![image](https://user-images.githubusercontent.com/71195502/118711873-135ea000-b7ee-11eb-89a8-cf191f192f6e.png)

**Comment by MasterOdin** [comment]
Thanks for creating an issue to track these bugs. While I understand that there's quite a few issues in our backlog that are "omnibus" that includes several items, I am pushing to avoid them going forward as possible, making separate issues for each task that can be done individually. This is to help encourage "best practices" for development such that for each of these tasks, I would want to see an individual PR, not a single PR that tries to accomplish both at once.

On that, I've split this issue into #6458 and #6459, and will close this one.
