### ISSUE TITLE
Late day policy & extensions for TA graded and non TA graded electronic submissions

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#651]
TA graded electronic rubrics can use late days.

Non TA graded electronic rubrics cannot use late days.  

Extensions can be entered for either TA graded or non TA graded items.

Late days for TA graded items are calculated when the TA grades.  We grab the submission time of the active version, check to see if the status is good (not too late, taking into account extensions and available late days), and store the active version, and grade status at time of grading.  NOTE:  MAYBE STOP STORING LATE DAYS USED FOR THIS HOMEWORK IN THE DATABASE?

Non ta graded items are processed when generate grade summaries is run.  If the currently selected active version is not past the deadline + any extension for that student on that assignment, then they get the autograding score.  If it's late, they get a zero.  NOTE: If a student changes the active version, it may change their score when grade summaries is rerun.  That's fine.  We don't need to store the active version.

**Comment by bmcutler** [comment]
This will be fixed by #722,
test after #722 is finished

**Comment by JerameyATyler** [comment]
Closes with new late day stuff
