### ISSUE TITLE
checkpoint data entry bug, possibly related to -stu account name

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#652]
A test account for a head TA named xxx-stu seems to work for everything except lab checkpoint data entry.  Might be because of the '-' in the username?

When boxes are checked and page is reloaded, data wasn't saved.  Also can't click on username for one touch full credit on lab.

**Comment by MasterOdin** [comment]
It's probably related to the fact that it has a `-` in the name. We should discuss what is a valid username and what isn't (what characters, numbers, and case are allowed). Related to #563.

**Comment by bmcutler** [comment]
Yes, it's a valid username (unless absolutely impossible).
We've been using that convention for instructor/head TA test accounts.

**Comment by MasterOdin** [comment]
What are the valid characters in a username?
`a-z`?
`A-Z`?
`0-9`?
`-`,`.`,`,`,`!`,`$`,`?`,`-`,`_`,`@`,`#`,`&`, etc?

Are there restrictions (ex: username cannot start with `-`) to character placement?

I'd like a set group of characters to support as this is the first I'm hearing that we have usernames with `-` in them.

**Comment by bmcutler** [comment]
Decision valid characters for user name are limited to:  a-z (lowercase), 0-9, -, _

**Comment by bmcutler** [comment]
Decision valid gradeable ids:  A-Z, a-z, 0-9, single underscore (not 2 in a row), -,

**Comment by MasterOdin** [comment]
This was fixed in the ports of the page.
