### ISSUE TITLE
Rainbow Grades fail to build due to Submini polls errors

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6594]
Describe the bug
Rainbow Grades build process results in a core dump

Expected behavior
Build finishes successfully, no errors are reported to stdout/stderr.

To Reproduce

    make pull
    make
    See error

Configuration

    OS: Ubuntu 20.04.2 LTS
    Browser N/A

Screenshots
Build fails with the following errors:

mkdir -p individual_summary_html
mkdir -p all_students_summary_html
mkdir -p all_students_summary_csv
./process_grades.out by_overall
print it   Java background                          05/23/2021      8 0    36   0
print it   Mode of attendance                       05/23/2021      3 0    36   0
process_grades.out: /media/sf_sharp/appjava-u21/RainbowGrades/RainbowGrades-main/submini_polls.cpp:60: std::string convert_date(const string&): Assertion `ch == '-' && ch2 == '-'' failed.
make: *** [/media/sf_sharp/appjava-u21/RainbowGrades/RainbowGrades-main/MakefileHelper:107: overall] Aborted (core dumped)

**Comment by bmcutler** [comment]
Grab the newest version of Rainbow Grades main branch, the parser for dates should handle the new format (and also the old format).  The date change was not planned/intentional.
