### ISSUE TITLE
Bootstrap Split Buttons not working

### ISSUE THREAD

**Issue by loadedskiffer** [Submitty/Submitty#6618]
**Describe the bug**
Currently if you follow bootstrap's documentation for making split buttons, they don't render properly and have no functionality.
This is due to edits being made to bootstrap dropdown-menu class. Upon looking further into this, there are other places where bootstrap classes have been edited strangely. This could have negative effects on adding new feautures going forward.
<img width="128" alt="issue3_1" src="https://user-images.githubusercontent.com/66340271/122275290-87559c00-ceb1-11eb-9130-154bef466945.PNG">
<img width="226" alt="issue3_2" src="https://user-images.githubusercontent.com/66340271/122275298-89b7f600-ceb1-11eb-887f-14c9cb74a661.PNG">

**Expected behavior**
If you exactly follow bootstrap's documentation for split buttons or any other component, they should render properly.
The edits to bootstrap's classes within submitty should most likely be rolled back in some way.
<img width="84" alt="issue3_3" src="https://user-images.githubusercontent.com/66340271/122275443-b23ff000-ceb1-11eb-9a64-745bfbd52433.PNG">

**To Reproduce**
1. Find the documentation for bootstrap 2.0 and find "split button dropdowns" under the components
2. Follow the instructions to implement them
3. See error
4. See line 818 of server.css and see edits 

**Configuration**
 - OS:  Windows
 - Browser chrome, edge

**Screenshots**

**Additional context**

**Comment by eddiekrystowski** [comment]
Yes, I ran into this earlier and was going to mention it at the meeting but I forgot. 
It seems as if someone just copied over the bootstrap styling into server.css and then changed it for their specific needs. Fortunately, it looks like only one place uses it, `site/app/templates/forum/ForumBar.twig:85`, so it should be simple enough to change that class to something else, and then include the proper bootstrap classes in `bootstrap.css`.
