### ISSUE TITLE
Create New Gradeable button isn't disabled when it is unable to be clicked

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#6626]
**Describe the bug**
When no gradeable type is selected, the "Create New Gradeable" button is active.  When clicking on the button, an alert appears to tell the user to select a gradeable type.  

**Expected behavior**
It would be better to disable the button until all of the requirements are met to prevent any confusion.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/16820599/122563744-92740d80-d012-11eb-89c0-2c24a541d856.png)

**Comment by Devtinator** [comment]
I would love to work on this.

**Comment by sonalika2001** [comment]
Hi @williamjallen, I'd like to work on this issue. This is my first time contributing to open source. However, I've worked on frontend development and I fully understand the issue at hand. Please guide me as to how to get started with setting up my system for the same and where to look for this page in the code. Thank you!

**Comment by Gulsonish** [comment]
Hey @williamjallen , Please check the pull request, I think I have fixed your mentioned bug. please reply me if it correct.

**Comment by Gulsonish** [comment]
Can You guide me @williamjallen with the error like which folder or file is connected with that .twig file for that error or suggest me connected files for that issue, it would be easy to fix the issue in very less time.
