### ISSUE TITLE
Create post button on empty forum is misaligned

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#6629]
**Describe the bug**
The "create thread" button is misaligned when there are no posts in a forum.

**To Reproduce**
1. Open forum with no posts
2. See error

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/16820599/122571181-75433d00-d01a-11eb-9194-05cec447ce7e.png)

**Comment by jyggiz** [comment]
Hey, can I take this issue?
