### ISSUE TITLE
PDF Annotation issue between devices

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#6637]
**Describe the bug**
A device can only erase it's own marks on the PDF annotation tool. If you try to erase marks made by a different device it does not work.

**Expected behavior**
You should be able to erase any marks made by this tool.

**To Reproduce**
1. Open PDF annotate tool on 1 device
2. Draw something and save it
3. Open PDF annotate tool on a different device and try to erase those marks

**Configuration**
 - OS: Linux and iPad OS
 - Browser: Chrome and Safari

**Comment by eddiekrystowski** [comment]
Turns out this was caused by trying to erase annotations made by a different user. It is intended behavior that users can only erase annotations which they have made.
