### ISSUE TITLE
Team history array bug

### ISSUE THREAD

**Issue by loadedskiffer** [Submitty/Submitty#6639]
**Describe the bug**
Ever since upgrading to ubuntu 20.04 every time I go to the Student index page for a team gradeable I get the PHP warning below
<img width="627" alt="issue4_1" src="https://user-images.githubusercontent.com/66340271/122811628-b9df0a80-d29e-11eb-9181-532dacfc5b60.PNG">

**Expected behavior**
The warning should not be occurring because nothing is actually broken, all information about the team and the gradeable is correct, there's just an error for some reason.

**To Reproduce**
1. upgrade to ubuntu 20.04
2. login as a grader and attempt to grade a team gradeable
4. See error on details page

**Configuration**
 - OS: Windows
 - Browser chrome, edge

**Comment by eddiekrystowski** [comment]
I am not able to reproduce this bug on ubuntu 20.04, but it sounds a lot like that strange forum bug I was getting. Can you try deleting your Submitty cookies in Chrome (or a different browser) and see if it persists?

And with the fix from #6640, your version of the page looks the exact same as it should (no info missing)?
