### ISSUE TITLE
Gradeable form json should use list of objects for numeric/checkpoints

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#667]
Right now, within the form json we have:

```
    "num_numeric_items": 2,
    "num_text_items": 1,
    "numeric_label": [
        "1",
        "2"
    ],
    "max_score": [
        5,
        5
    ],
    "numeric_extra": [
        2
    ],
    "text_label": [
        "Seating"
    ],
```

which is confusing to parse as a human. This should be written to:

```
"numeric_questions": [
    {
        "label": "1",
        "score": 5
    },
    {
        "label": "2",
        "score": 5,
        "extra_credit": true
    }
],
"text_questions": [
    {
        "label": "Seating"
    }
]
```

(using an object for text questions is overkill right now, but the amount of overhead is minimal and allows for easy addition of fields to text questions).

This should similarly be done for checkpoints and rubrics

**Comment by bmcutler** [comment]
ALSO... write a simple backend script to force export all gradeables from database to form files.

**Comment by bmcutler** [comment]
@bdrumheller did you finish this or have it partially finished?
