### ISSUE TITLE
Small tasks for secondary email

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#6670]
* The toggle box for "send email to secondary email" should be unchecked and disabled if the secondary email string is empty/null.

* Please adjust the placement/wrapping of the "Edit Secondary Email" text for the Profile page.   Perhaps those 2 edit pencils should go next to  the data values that will be edited.  

  <img width="778" alt="Screen Shot 2021-06-24 at 8 46 41 PM" src="https://user-images.githubusercontent.com/5871417/123352452-4bfc4280-d52d-11eb-853d-273d6bbc7a74.png">

* Please add a screenshot of the finished UI (and update text if needed) here:
https://submitty.org/student/account/email_addresses

**Comment by cjreed121** [comment]
This can be closed as soon as https://github.com/Submitty/submitty.github.io/pull/353 gets merged.
