### ISSUE TITLE
Students get a frog robot page instead of a Submini Poll page

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6680]
**Describe the bug**
Submini Poll causes a frog robot page on Submitty when students attempt to answer the poll.

**Expected behavior**
Submini Poll page should be properly displayed to the students.

**To Reproduce**
1. On the instructor's side, make a new poll and make sure it is visible and accepting answers. This can be verified by navigating to https://submitty.cs.rpi.edu/courses/u21/csci2600/polls/editPoll/4 and observing the page (see screenshot 1).
The poll is visible and accepting answers, see screenshot 2.
2. Log in a student (kuzmik-stu in my case) and try to navigate to the polls page: https://submitty.cs.rpi.edu/courses/u21/csci2600/polls, see screenshot 3
3. When you click "Answer" for the "Writing Dafny on midterm" poll, a frog robot page is displayed, see screenshot 4

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Firefox 89.0 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/123726519-20939380-d85e-11eb-9ee4-bf70968ce70c.png)
![image](https://user-images.githubusercontent.com/7108039/123726568-3739ea80-d85e-11eb-90e1-0ebfd4b10a8a.png)
![image](https://user-images.githubusercontent.com/7108039/123726736-75cfa500-d85e-11eb-8e03-1e7a9d121f21.png)
![image](https://user-images.githubusercontent.com/7108039/123726799-9435a080-d85e-11eb-99ad-1d778714f8db.png)

**Additional context**
We had another poll ("Homework 3 deadline") in the same course (CSCI-2600) just a week or so ago (created on 6/16). Everything worked as expected. Whatever was done to break this functionality is a fairly recent change (no earlier than June 16, 2021)

One other thing that I noticed is the weird behavior of the "Expected release date:". I don't know if it is related to the bug that I described above or if it is a separate bug. If it is the latter, please feel free to extract this description as a separate issue. So, when I'm editing a poll that I recently created (https://submitty.cs.rpi.edu/courses/u21/csci2600/polls/editPoll/4) I can see some date there:
![image](https://user-images.githubusercontent.com/7108039/123727093-1625c980-d85f-11eb-81ee-2dd6634d4cb7.png)

If, however, I click in the date field, the date disappears and no matter what I select in the calendar, there is no way to get the date back in:
![image](https://user-images.githubusercontent.com/7108039/123727161-3bb2d300-d85f-11eb-89da-a10c51ba0554.png)
I tried selecting different dates, both in the past and in the future. Still no luck.

I even tried typing the date "06/27/2020" to at least restore the previous state of this field but as soon as I typed it and moved to another field, this date got erased:

![image](https://user-images.githubusercontent.com/7108039/123727323-774d9d00-d85f-11eb-9e52-fd9ca58fe7f1.png)
![image](https://user-images.githubusercontent.com/7108039/123727354-82a0c880-d85f-11eb-8c6b-71c65a5e5fdd.png)

Of course, Submitty doesn't allow me to save the changes because now the date is missing...

**Comment by bmcutler** [comment]
This problem seems to be fixed by recent PRs fixing and refactoring the Submini/Poll implementation
