### ISSUE TITLE
Rainbow Grades fail to build with the customization.json that worked just a week before

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6698]
Describe the bug
Rainbow Grades build process results in a core dump

Expected behavior
Build finishes successfully, no errors are reported to stdout/stderr.

To Reproduce

    make pull
    make
    See error

Configuration

    OS: Ubuntu 20.04.2 LTS
    Browser N/A

Screenshots
Build fails with the following errors:

cpp -xc++ customization.json | sed -e '/^#/d' > customization_no_comments.json
python3 -m json.tool customization_no_comments.json > /dev/null
grep '{"file":' customization_no_comments.json > iclicker_file_list.txt || true
python3 /media/sf_sharp/psoft-u21/RainbowGrades/RainbowGrades-main/parsexml.py iclicker_file_list.txt
./process_grades.out by_overall
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is array
make: *** [/media/sf_sharp/psoft-u21/RainbowGrades/RainbowGrades-main/MakefileHelper:107: overall] Aborted (core dumped)
kuzmik@kuzmik-VirtualBox:/media/sf_sharp/psoft-u21/RainbowData$

**Additional context**
I was building Rainbow Grades successfully with the same customization.json file in the same course (CSCI-2600) about a week ago (on 6/23). Everything worked as expected. Whatever was done to break this functionality is a fairly recent change (no earlier than June 23, 2021).

**Comment by bmcutler** [comment]
@KCony 
What version of the rainbow grades source code are you using?
If you're not on the latest version, please update.  
We had to modify the parser to handle the different poll response types.
