### ISSUE TITLE
Annotating PDFs doesn't work with typing text

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6699]
**Describe the bug**
When attempting to annotate a student's PDF, typing text is either not working a tall or allows the text to be types but then all text disappears, depending on the browser. Clicking "Save" button has no effect.

**Expected behavior**
Text typed in the annotation node of grading PDFs should remain visible on the page and saved when the "Save" button is clicked.

**To Reproduce**
1. Open a student's PDF (I was grading article01 gradeable from CSCI-4963).
2. Click on "A" and then click anywhere on the PDF to start typing. The box appears and allows you to type (see screenshot 1).
3. When you click outside of the box to confirm the entry (or press Enter), the box disappears along with the text (screenshot 2).
4. Clicking the "Save" button says "Saved" but the text is still gone (screenshot 2).

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Google Chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/124189180-574ff080-da8e-11eb-8b45-7bf92c5f7b75.png)
![image](https://user-images.githubusercontent.com/7108039/124189313-85353500-da8e-11eb-8de9-cd5dc26030f9.png)
![image](https://user-images.githubusercontent.com/7108039/124189382-9ed67c80-da8e-11eb-8ca9-49a7fc463b89.png)

**Additional context**
"Text size" combo box that can be accessed by clicking the 
![image](https://user-images.githubusercontent.com/7108039/124189606-f83eab80-da8e-11eb-81dc-ce896e731ccd.png)
icon doesn't have any font size selected by default. It just shows blank space.

**Comment by eddiekrystowski** [comment]
@KCony Can you let me know if the text is still disappearing after selecting a specific font size? (ie. the font size isn't blank)

**Comment by eddiekrystowski** [comment]
@KCony I believe I have fixed this in #6727 but unfortunately for gradeables that are already affected, they will need to be reset by navigating to `/var/local/submtity/<course path>/annotations/<gradeable id>` and deleting the directory associated with the user whose pdf you are annotating. Until the fix is released in production, ensure that pen size and text size are always set before making annotations to avoid this bug.

**Comment by KCony** [comment]
It doesn't look like it got fixed, unfortunately. I just spend like an hour making a lot of annotations on a student's PDF. Before I started, I made sure I selected the color and the text size. Also, I saved everything, and Submitty was saying "Saved". I leave the page and then come back to check everything still looks good. One annotation is missing but all others are still in place. So, I typed the missing annotation again, saved, left the page, came back, and ... Now, the only annotation that is there is the one that was added last, just one. Everything else has been erased. The entire hour of work is gone. I can't tell you how frustrating it is:

![image](https://user-images.githubusercontent.com/7108039/125221030-97d11a80-e295-11eb-90b3-c8b140bf2694.png)

**Comment by KCony** [comment]
And now, I thought I redo my annotations while I remember them. I did like the first paragraph, saved, left the page, came back, and now my "Title" annotation is gone!

![image](https://user-images.githubusercontent.com/7108039/125221389-28a7f600-e296-11eb-8261-553685ba3708.png)

**Comment by eddiekrystowski** [comment]
That is definitely quite frustrating... if you get the chance, would you mind going to this pdf and opening the browser console and sending a screenshot of any errors you see there?

**Comment by KCony** [comment]
It doesn't look like I have the necessary permissions, even when I try it with sudo:

![image](https://user-images.githubusercontent.com/7108039/125677437-23e16c33-9d8b-4d63-8981-5460d296e237.png)

**Comment by KCony** [comment]
Here are the errors that get logged in the browser:

![image](https://user-images.githubusercontent.com/7108039/125678061-ffc756d6-4caf-4ae2-9054-bb67184bd425.png)

In the screenshot above note also how the student's name area is screwed up with some weird vertical scroll and text running over some other text on the page.

![image](https://user-images.githubusercontent.com/7108039/125678311-9403e130-c3ea-4942-aedc-f8b5b2cd4364.png)

Here is the full log:
Some cookies are misusing the recommended “SameSite“ attribute 20
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1533
grade:1129:30
WebSocket: connecting to wss://submitty.cs.rpi.edu:8443/ws websocket.js:41:17
WebSocket: connected websocket.js:44:21
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ twig.min.js:2:79872
Uncaught SyntaxError: redeclaration of let currentTool
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC line 2 > injectedScript:1
    jQuery 11
    success https://submitty.cs.rpi.edu/js/ta-grading.js?v=1624944782:1543
    jQuery 4
grade:1:1
Warning: Setting up fake worker. grade:1:10529
SingleFile is hooking the FontFace constructor to get font URLs. 2 hooks-frames-web.js:1:514
SingleFile is hooking the FontFace constructor to get font URLs. grade:1:223
SingleFile is hooking the FontFace constructor to get font URLs. grade:1:223
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://submitty.cs.rpi.edu/vendor/twigjs/twig.min.js?v=1625860340
Source Map URL: twig.min.js.map
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30

**Comment by KCony** [comment]
When I then add another annotation and Submitty kills all previous ones, it logs an additional error at the very bottom:

![image](https://user-images.githubusercontent.com/7108039/125678638-58dcf1ed-ca40-4d60-ab1d-0664ea03eb66.png)

Full log is now:

Some cookies are misusing the recommended “SameSite“ attribute 24
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1533
grade:1129:30
WebSocket: connecting to wss://submitty.cs.rpi.edu:8443/ws websocket.js:41:17
WebSocket: connected websocket.js:44:21
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ twig.min.js:2:79872
Uncaught SyntaxError: redeclaration of let currentTool
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC line 2 > injectedScript:1
    jQuery 11
    success https://submitty.cs.rpi.edu/js/ta-grading.js?v=1624944782:1543
    jQuery 4
grade:1:1
Warning: Setting up fake worker. grade:1:10529
SingleFile is hooking the FontFace constructor to get font URLs. 2 hooks-frames-web.js:1:514
SingleFile is hooking the FontFace constructor to get font URLs. grade:1:223
SingleFile is hooking the FontFace constructor to get font URLs. grade:1:223
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://submitty.cs.rpi.edu/vendor/twigjs/twig.min.js?v=1625860340
Source Map URL: twig.min.js.map
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught ReferenceError: toolbar_bbox is not defined
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1129
grade:1129:30
Uncaught SyntaxError: redeclaration of let currentTool
    <anonymous> https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC line 2 > injectedScript:1
    jQuery 11
    success https://submitty.cs.rpi.edu/js/ta-grading.js?v=1624944782:1543
    jQuery 6
    loadPDF https://submitty.cs.rpi.edu/js/ta-grading.js?v=1624944782:1531
    viewFileFullPanel https://submitty.cs.rpi.edu/js/ta-grading.js?v=1624944782:1513
    openFrame https://submitty.cs.rpi.edu/js/ta-grading.js?v=1624944782:1448
    onclick https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/grade?who_id=i8oJ1l1CjA1MLBC&sort=id&direction=ASC:1
grade:1:1
Warning: Setting up fake worker. grade:1:10529

**Comment by KCony** [comment]
Also this:
![image](https://user-images.githubusercontent.com/7108039/125679025-6c30ee95-1a8e-4dc0-ad8e-f092174008d5.png)
