### ISSUE TITLE
Annotations disappear from the PDF when atempting to move them

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6700]
**Describe the bug**
When attempting to annotate a student's PDF, typing text is either not working a tall or allows the text to be types but then all text disappears, depending on the browser. Clicking "Save" button does not restore lost annotations.

**Expected behavior**
Annotations that were moved around the PDFs should remain visible on the page and saved when the "Save" button is clicked.

**To Reproduce**
1. Open a student's PDF (I was grading article01 gradeable from CSCI-4963).
2. Add some annotations, e.g., underlining some text. See screenshot 1.
3. Click on an arrow button and then attempt to drag the underlining to another part of the PDF. Release the mouse button and observe the underlining disappear. In other words, the arrow erases the annotation instead of moving it. See screenshot 2.
4. For some other annotation, the effect was slightly different. Click on an arrow button and then attempt to drag the underlining to another part of the PDF. The annotation would not move but a small blue highlighted artifact appears on the PDF (see screenshot 3 the artifact is circled with red pen).

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Google Chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/124190341-1a84f900-da90-11eb-8f2d-5bf80819dcf4.png)
![image](https://user-images.githubusercontent.com/7108039/124190829-e65e0800-da90-11eb-8888-caacb2cbdae7.png)
![image](https://user-images.githubusercontent.com/7108039/124190970-19080080-da91-11eb-838f-0f9341f7b1ee.png)

**Additional context**
I was not able to understand what accounts for the difference between the behavior described in 3 and 4. Maybe it is the zoom level? Overall, the PDF annotation feature feels very clunky, hard to use, and unreliable. I had several cases when it actually didn't save my annotations despite me clicking the Save button and Submitty saying that everything was saved. It is a highly wanted feature, I just wish it was debugged better, so that it is more intuitive to use and more reliable too.

Another thought that maybe if it is hard to get the annotation feature to work correctly inside Submitty, it would be possible to allow graders use some external tool (like Acrobat) and then allow them to replace the student's PDF with its annotated version in the submission? I'm just trying to see what can be done so that I could grade a bunch of student PDFs quickly and hopefully with little effort.

**Comment by eddiekrystowski** [comment]
I was never able to reproduce this issue, but my hope is that with #6771 any weirdness within the PDF will get sorted out, and cause this behavior to go away. Feel free to reopen if it is still happening.
