### ISSUE TITLE
TA grading hangs when navigating by arrows

### ISSUE THREAD

**Issue by JerameyATyler** [Submitty/Submitty#673]
TAs are experiencing intermittent hanging when they open the grading page by clicking on the next and previous buttons and when the page automatically progresses after pressing 'submit'.

**Comment by MasterOdin** [comment]
I'm guessing there's an infinite loop happening somewhere (most likely JS if the web browser isn't killing the page load after some amount of time).

**Comment by bmcutler** [comment]
Is this still a bug?

**Comment by bmcutler** [comment]
Closing this.  If it happens again we need more details to debug.
