### ISSUE TITLE
Grading comments are not formatted properly for comments written by other graders

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6739]
**Describe the bug**
When viewing grading comments left by other graders (both TAs/mentors and peer graders), the formatting of the first line of comments is off. First, there is a big gap at the beginning of the line. Second, the font is different from the rest of the text. Third, long lines are not wrapped (the rest of the text is wrapped) and appear as a single long line that is cut at the right boundary of the window. Comments that are written by me (the leftmost tab) are displayed properly. Note that to the best of my knowledge no markdown markup was used in any of the comments.

**Expected behavior**
Text of the grading comments should be formatted consistently. The first line of text should not be formatted differently from the rest of the text, unless some special Markdown markup is explicitly present.

**To Reproduce**
1. Open a grading page for some student (in the screenshots below gradeable hw02 gradeable from CSCI-4963 is shown).
2. Observe correct formatting for my own comment in Edit mode (see screenshot 1).
3. Observe correct formatting for my own comment in Preview mode (see screenshot 2).
4. Switch to another tab with the comment written by another grader and observe the three problems described above (labeled as 1, 2, and 3 with handwritten annotations in red in screenshot 3).
5. Switch to a different tab with the comment written by another grader and observe the three problems described above (labeled as 1, 2, and 3 with handwritten annotations in red in screenshot 4).

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Mozilla Firefox 89.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/125512605-c90eba3f-65de-4b41-a6b4-c3e1a5cc98a6.png)
![image](https://user-images.githubusercontent.com/7108039/125512573-993108e2-1ede-4883-a8b9-b45bd7000e5b.png)
![image](https://user-images.githubusercontent.com/7108039/125512806-376422d0-a23d-4286-840c-cd8b3cb8dfa2.png)
![image](https://user-images.githubusercontent.com/7108039/125512828-b9c4d623-f336-4633-8c82-a73d9d97cb25.png)

**Additional context**
It appears that this bug was introduced around the same time when the new feature of allowing graders to use Markdown in those comment boxes was rolled out.

**Comment by eddiekrystowski** [comment]
Fixed in #6756
