### ISSUE TITLE
Student View:  Show status of submission on homepage for open assignments

### ISSUE THREAD

**Issue by galengold** [Submitty/Submitty#674]
When I submit assignments, I can't tell if they have been submitted previously or what the score is. I'm requesting a simple (for example) "Not Submitted" or "Submitted 1 Time, Score: 50/50" text next to the submission button to notify the user what their score is next to the open assignments.

**Comment by bmcutler** [comment]
Yup, this is a known issue.   (I think its buried in the details of another issue.)

This feature got clobbered this summer with the improvements pulling data from both autograding & TA grading for that index page.

It is a top priority to fix.

**Comment by MasterOdin** [comment]
I don't think this is for TA Grading but rather to display the submission status on the navigation page that students are viewing.

**Comment by zd9** [comment]
@MasterOdin is correct. I am a student, not a TA

**Comment by bmcutler** [comment]
Our initial design for the student would visualize this status through button colors (green or blue means 'click here to submit', red means 'oops, you missed the deadline', etc).  

And also through a progress bar that could either indicate time remaining before deadline or percent of autograding points received.

**Comment by sihsob** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ll](https://trello.com/c/sxnetSv3/6-ll)

**Comment by bmcutler** [comment]
In progress...   see PR #962

**Comment by bmcutler** [comment]
Replaced by issue #1045
