### ISSUE TITLE
Grade inqury comments are hidden from the grader who wrote them until the inquiry is closed.

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6740]
**Describe the bug**
When viewing grade inquiries from the grader's interface, comments that were left without closing the inquiry are hidden. On the student's side those comments are showing up normally. When a the grade inquiry is closed, it reveals all previously hidden comments.

**Expected behavior**
Text of all inquiry comments should be always visible in the grader's interface regardless of whether the inquiry was closed or not.

**To Reproduce**
1. Make a grade inquiry from the student's interface (see screenshot 1).
2. Open a grading page for some student (in the screenshots below gradeable article01 gradeable from CSCI-4963 is shown).
2. Observe a grade inquiry from a student (see screenshot 2).
3. Write a comment for the grade inquiry and click "Post Additional Information" (see screenshot 3).
4. Observe that the comment for the grade inquiry is hidden and only the rubric component name ("Article Review Draft") is shown (see screenshot 4).
5. Write another comment for the grade inquiry and click "Post Additional Information" (see screenshot 5).
6. Observe that both comments for the grade inquiry are hidden and only the rubric component name ("Article Review Draft") is shown for them (see screenshot 6).
7. Click "Close Grade Inquiry" (see screenshot 7).
8. Observe that all comments (including the ones that were hidden before) now become visible (see screenshot 8).

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Mozilla Firefox 89.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/125513718-0da49494-09c5-4c83-ae1c-9d54f914f593.png)
![image](https://user-images.githubusercontent.com/7108039/125513769-72251fb3-0c4a-4f48-9262-b7cd8bfd78ef.png)
![image](https://user-images.githubusercontent.com/7108039/125513816-06e984ed-ca09-44d3-9e27-3f82650a8969.png)
![image](https://user-images.githubusercontent.com/7108039/125513881-36eac6a9-4594-4c7e-b621-f4a011d03df8.png)
![image](https://user-images.githubusercontent.com/7108039/125514029-19c1b107-c9e9-4d9b-b682-971bc5fd1ccb.png)
![image](https://user-images.githubusercontent.com/7108039/125514078-1a118ac3-2c92-49a4-a8ca-e29d7ca814de.png)
![image](https://user-images.githubusercontent.com/7108039/125515152-452ff99f-cdb9-4b4b-987b-2f5b509b2cde.png)
![image](https://user-images.githubusercontent.com/7108039/125515365-e842418d-ef61-476d-af4d-e144ad4f5ac8.png)

**Additional context**
None.

**Comment by eddiekrystowski** [comment]
Fixed in #6756
