### ISSUE TITLE
Forum posts ignore line endings and empty lines; Markdown is also ingnored regardless of the "M" switch.

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6750]
**Describe the bug**
When editing the post that originally had Markdown turned off, no Markdown is rendered even if Markdown was turned on when editing. All text is lumped together in a single paragraph ignoring line breaks and empty lines.

**Expected behavior**
It should be possible to turn on Markdown when editing an existing post and have that Markdown properly rendered. With or without Markdown markup, the rendered text should honor line endings and empty lines that separate the paragraphs.

**To Reproduce**
1. Make a post with Markdown turned off which is the default, unfortunately (I almost always want to use Markdown but I occasionally forget to turn it on). Note that there is an empty line in the middle, between two paragraphs (see screenshot 1).
2. Create the post and observe that it misses an empty line between the paragraphs (see screenshot 2).
2. Edit the post and turn the Markdown on hoping that it would preserve the empty line (see screenshot 3).
3. Observe that the empty line is still missing (see screenshot 4).
4. Edit the post and add more Markdown markup (see screenshot 5).
5. Observe that there Markdown markup is not rendered at all. The empty line is still missing (see screenshot 6).

**Configuration**
 - OS: Windows 10 Enterprise x64, 10.0.19042, Build 19042
 - Browser: Mozilla Firefox 89.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/125866992-ff42da93-5519-4e5f-a899-da97f4c1c351.png)
![image](https://user-images.githubusercontent.com/7108039/125867238-d78d55ae-fbaf-4411-a039-f2e5540c4ce3.png)
![image](https://user-images.githubusercontent.com/7108039/125867315-3b052311-9f2c-410e-83f2-6e77667486fb.png)
![image](https://user-images.githubusercontent.com/7108039/125867375-62341835-b9c0-4632-b79b-ff0af98755d0.png)
![image](https://user-images.githubusercontent.com/7108039/125867424-a8a2d375-8646-4619-a8f9-82d5567bd7ff.png)
![image](https://user-images.githubusercontent.com/7108039/125867487-e9213526-f8dc-4884-886f-7e55f6314aa4.png)

**Additional context**
I'm pretty sure this functionality worked correctly before. So, it probably got broken reasonably not that long time ago.

**Comment by KCony** [comment]
It gets even uglier when there is just one paragraph of text:
![image](https://user-images.githubusercontent.com/7108039/126052702-d098676b-3b2c-4d0e-9eae-153b73a8058c.png)

As you can see, it gets cut off, and I would imagine students have no way of reading the hidden part since there is no horizontal scroll.

**Comment by KCony** [comment]
Just wanted to share an observation that I am seeing more student posts with this formatting problem. It's just the last couple of days, I don't think even posts created Thursday or Friday last week were exhibiting this issue.

![image](https://user-images.githubusercontent.com/7108039/126094878-ffa6134e-6c92-4289-8f22-86fc6ced7ab2.png)
![image (1)](https://user-images.githubusercontent.com/7108039/126094881-5919babd-bc25-4ffb-915d-eeb7c9f75830.png)

Something else that I observed that hopefully helps whoever is debugging this issue. Even some old posts that have never been edited are affected by this formatting issue. Below is my post from Summer 2020:

![image (2)](https://user-images.githubusercontent.com/7108039/126094886-9769780f-0526-4313-941d-2de0d4a1f332.png)

**Comment by KCony** [comment]
Unfortunately, it doesn't look like the issue is fixed completely. It does work when "M" is on but if not, the posts are still displayed incorrectly. This is a brand new thread that I just created:

![image](https://user-images.githubusercontent.com/7108039/126906394-70cfad33-7821-4209-a502-f2b5d881b180.png)
![image](https://user-images.githubusercontent.com/7108039/126906398-9b4b71e9-f6bf-4552-9c69-492bab0f1b92.png)

Some old posts are also displayed incorrectly:
![image](https://user-images.githubusercontent.com/7108039/126906523-6b87f72c-0137-4767-9f06-53c60ce2b76d.png)

Also, the state of "M" mode is not saved for me. I turn it on:
![image](https://user-images.githubusercontent.com/7108039/126906459-9593a718-3ce3-4170-b97a-bb3c08af1577.png)


but on creating the next new post, it is off again:
![image](https://user-images.githubusercontent.com/7108039/126906451-e03426b2-53d2-4f5a-8686-15844f8636fd.png)

**Comment by eddiekrystowski** [comment]
This should get fixed in the next release when this PR gets deployed to production. The behavior you are describing is exactly what I encountered and think I have fixed, so hopefully this will get fixed soon!

**Comment by eddiekrystowski** [comment]
@KCony There was a release last night which should have fixed this issue, but please let me know if that isn't the case!

**Comment by KCony** [comment]
Thank you, @eddiekrystowski It looks like all issues have been fixed except for "M" button doesn't stay on for me. Maybe the fix hasn't been installed yet? If you need, I have fresh screenshots taken just a few minutes ago.

Writing the first of the two posts:

![Screenshot 2021-08-01 232654](https://user-images.githubusercontent.com/7108039/127801046-51a84a7b-b4ab-499f-8167-d54990c6a172.png)

After publishing the first, I'm attempting to create the second one, and "M" is turned off:

![Screenshot 2021-08-01 232700](https://user-images.githubusercontent.com/7108039/127801053-a83c4a88-35bb-4cfc-88db-02eb5ee151c9.png)
