### ISSUE TITLE
account-summary page should better display graded status

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#676]
Writing up the issue Barb discussed in #674.

Right now, the button always looks the same regardless if the assignment has been graded or not (the difference being that it'll either contain only the auto-grading score or also the TA grades). The columns should then be something like this:

| Name |  AutoGrading | Grade |
|-------|--------------|--------|
| pevelm (Matthew Peveler) | 20/20  | Grade (Blue Button) |
| cutleb (Barb Cutler) | 20/20 | 33/30 (White Button) |

Where only the last column is a button and contains the student's TA grade.

**Comment by sihsob** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ll](https://trello.com/c/sxnetSv3/6-ll)
