### ISSUE TITLE
Other users with mark are identified by hash instead of name

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#6810]
**Describe the bug**
When viewing the rubric panel in the TA grading interface, it is possible to click an icon on the right side of each mark to see the other users who also received that mark.  When not in blinded grading or anonymous mode, the names of the users who received the mark are still displayed as random strings instead of the name or user ID of the user.

**Expected behavior**
When not in a grading mode which hides student names, the random string should be replaced with either the name or user ID of the student.

**To Reproduce**
1. Go to the TA grading interface
2. Start grading a student and switch to the rubric pane
3. Click the users icon next to any mark

**Configuration**
N/A

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/16820599/126833072-98c210da-6a3c-4637-92ef-57ff3d972bef.png)

**Comment by iota-008** [comment]
@williamjallen hi, i am to open source and would like to contribute to this solve this issue, I have cloned the repo just wanted to know to run this application on windows so that I could into it.

**Comment by Pranjal-dew** [comment]
Hi, is this issue still open? Care if I take it?
