### ISSUE TITLE
Instructor pages for team gradeables are broken

### ISSUE THREAD

**Issue by sbelsk** [Submitty/Submitty#6842]
**Describe the bug**
When trying to access the gradeable page for team gradeable, the following twig error is thrown:
![image](https://user-images.githubusercontent.com/71195502/127398531-5d6f867f-0523-40a9-bcaf-24a620c6ef71.png)

**To Reproduce**
1. Log in as instructor
2. In the sample course on the gradeables page, click to view the gradeable page for "Grading Homework Team PDF" (or any other team gradeable)
3. See error

**Comment by loadedskiffer** [comment]
I can't reproduce this error

**Comment by sbelsk** [comment]
> I can't reproduce this error

@loadedskiffer not for trying to access the grading page, but when trying to access the page from which you can make submissions? (http://localhost:1511/courses/f21/sample/gradeable/grading_homework_team_pdf)

**Comment by loadedskiffer** [comment]
> > I can't reproduce this error
> 
> @loadedskiffer not for trying to access the grading page, but when trying to access the page from which you can make submissions? (http://localhost:1511/courses/f21/sample/gradeable/grading_homework_team_pdf)

Now I see it, I'll have both of the issues fixed asap
