### ISSUE TITLE
"Grade" button went missing in the student peer grading interface

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6860]
**Describe the bug**
"Grade" button is not displayed in the students' peer grading interface, so students are unable to proceed with peer grading.

**Expected behavior**
"Grade" button should be displayed in the students' peer grading interface, allowing students to proceed with peer grading.

**To Reproduce**
NB: All steps below are shown using a student account (specifically, kuzmik-stu). Steps to reproduce the behavior:
1. Navigate to the main Submitty page using a student's account. In my specific example, this is gradeble hw03 in CSCI4963. See screenshot 1.
2. Click "GRADE" to navigate to the grading page of Homework 03. See screenshot 2.
3. Click "Grading index" to see the list of submissions assigned for peer grading to this student. Note the absence of "Grade" buttons for all submissions. See screenshot 3.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/127728342-bd46c7dd-0fd0-4651-8138-52139fb8cecd.png)
![image](https://user-images.githubusercontent.com/7108039/127728353-84628f7b-a2b1-4326-b008-636e85efc1d1.png)
![image](https://user-images.githubusercontent.com/7108039/127728366-a05b7d1e-d4fc-4632-b0e7-a6dc4500f646.png)

**Additional context**
This functionality worked correctly before. So, it probably got broken reasonably not that long time ago. Here is a screenshot from a little while ago:
![Step3](https://user-images.githubusercontent.com/7108039/127728242-5e5fa8e1-41fd-4795-a015-9b884de82056.png)

**Comment by cjreed121** [comment]
#6855 fixed this a few days ago. It will be live after next release. I'll close the issue for now but if it continues after release please re-open.
