### ISSUE TITLE
No way to resolve version conflicts through instructor grading interface

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6912]
**Describe the bug**
The instructor view of the grading rubric has no provisions to fix the version conflict. The result is that students cannot see their grades because of the version conflict but TAs/instructors are unable to specify on Submitty that all rubric items graded on the basis of the previous version of the submission are still valid and should be carried over to the latest submission version. Submitty used to have this feature when it was just allowing the TA/instructor to click a button in the rubric panel saying that I want to keep all scores from the previous versions and carry them over to the current version. Now this feature seems to be gone, and there is no way to resolve this conflict and make grades visible to students.

**Expected behavior**
The instructor view of the grading rubric should has some means of fixing the version conflict.

**To Reproduce**
1. Navigate to the gradeable index page on Submitty. In my specific example, this is gradeble article01 in CSCI4963. The corrsponding URL is https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/article01/grading/details?sort=id&direction=ASC&view=all. Observe that some students have "Version Control" shown on the grading button. See screenshot 1.
2. Click the grading button that says "Version control" for any of the students. Observe that the rubric panel shows the correct scores and no indication that there is a version conflict. Hence, no controls are provided to resolve the version conflic. See screenshots 2-4.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Mozilla Firefox 90.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/128640607-c75989bb-7896-430e-9f2d-1b27f3a53358.png)
![image](https://user-images.githubusercontent.com/7108039/128640639-7a63600b-ae1e-4388-818f-d3fcf3eebeb7.png)
![image](https://user-images.githubusercontent.com/7108039/128640655-0d1a4b69-a1b4-49ad-a00c-0232118628c3.png)
![image](https://user-images.githubusercontent.com/7108039/128640664-62dd26a2-10a1-4fea-9f42-8c7db4e5fd7c.png)

**Additional context**
This functionality worked correctly before, at least for "student submit files" type of gradeable. The gradeable that we use is a "git repo" type of gradeable.

**Comment by bmcutler** [comment]
I don't believe this issue is solved.

**Comment by bmcutler** [comment]
browser clear cache is (probably) necessary to force twig update
