### ISSUE TITLE
Display course materials on the calendar

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#6921]
**What problem are you trying to solve with Submitty**
Only gradeables are shown on the current calendar. It would be great if course materials could be placed on the calendar.

**Describe the way you'd like to solve this problem**
Course materials will appear on the calendar with a date they are associated with. This will require #6360 to hold extra information that the calendar can then use.

**Comment by micpap25** [comment]
Closing in favor of #9706 since that has more direct work on it.
