### ISSUE TITLE
New Submitty Forum message is not shown after being created

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6940]
**Describe the bug**
When creating a new Submitty Forum message, the page is not reloaded to show the newly created message but disables the "Publish" button and still shows the editor. Forcefully refreshing the browser page or navigating to the Forum page through the panel on the left reveals that the message has in fact been created.

**Expected behavior**
A newly created message should be shown in the "view" mode of the Submitty Forum automatically, without forcing the user to refresh the browser page or navigate to the Forum page using the "Discussion Forum" link in the panel on the left.

**To Reproduce**
1. Navigate to the Forum page and start creating a new thread. In my specific example, this is course CSCI-4963. The corresponding URL is: https://submitty.cs.rpi.edu/courses/u21/csci4963/forum/threads/new
2. Click the "Publish thread" button to publish the thread.
3. Submitty disables the "Publish thread" button but stays on the "edit" page for the new thread. See screenshot 1.
4. When browser page is forcefully reloaded, it shows the warning that there is some unsaved contents where in fact there is no unsaved contents because the thread has already been created successfully. So, this message is incorrect. See screenshot 2.
5. Clicking "Leave page" shows a new empty "Create Thread" which is confusing because the thread has already been created. See screenshot 3.
6. We can verify that the new thread has been successfully created by navigating to the Forum through the panel on the left. See screenshot 4.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Mozilla Firefox 90.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/129464548-5da37501-f036-4e6d-8d01-d739ce618b0c.png)
![image](https://user-images.githubusercontent.com/7108039/129464669-81ab44f5-ba45-45ab-927b-ef4ffd4eb305.png)
![image](https://user-images.githubusercontent.com/7108039/129464677-99aa9c99-fe0e-4ada-bb96-31302c2d4840.png)
![image](https://user-images.githubusercontent.com/7108039/129464695-28a90a31-0db8-4a16-9984-d339aba54246.png)

**Additional context**
I'm pretty certain everything worked correctly just a day or two ago, so, it is probably a freshly introduced bug.

**Comment by williamjallen** [comment]
Have you tried this on other browsers by any chance?  It seems to work properly for me on my development VM using macOS Safari 14.1.2 and macOS Chrome 92.0.4515.131.  I don't have Firefox so maybe someone else can confirm.  Also, were there any console errors?

**Comment by HenrikLam** [comment]
I tried to reproduce this on windows Firefox as well and I wasn't able to do so. My hunch was that there was probably an error in the console, if this happens again could you check to see if there is an error?

**Comment by KCony** [comment]
@williamjallen @HenrikLam 
I see this error all the time. There is not a single thread that I can edit or create without observing this issue. So, it's easy to reproduce on my end. Sure, here are the screenshots that show errors (the first one is befor clicking "Publish", the second one is after):
![image](https://user-images.githubusercontent.com/7108039/129784362-d5e6e836-c0c7-46ee-b530-e391fa6c9214.png)
![image](https://user-images.githubusercontent.com/7108039/129784373-6c48d2d1-3a4a-42ab-8610-6591806b6e41.png)

**Comment by KCony** [comment]
Works fine in Chrome although still throws some errors complaining about Websocket:

![image](https://user-images.githubusercontent.com/7108039/129784767-ee6e5195-0d02-4de7-9eca-8d6c74759817.png)
![image](https://user-images.githubusercontent.com/7108039/129784786-c6dd3011-4287-4276-b98a-aa65ccb29a27.png)

**Comment by KCony** [comment]
Fixed!
