### ISSUE TITLE
Numeric/Text is unable to save changes; editing is broken for text fields

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#6953]
**Describe the bug**
Numeric/Text gradeable fails to save the contents of the text field. When attempting to edit the contents of the Text field, arrows do not work, so there is no way to move the insertion point to make edits. You can only select all contents and delete it and then start typing over again.

**Expected behavior**
The contents of all fields should be saved. Arrows should work to move the insertion point inside the Text field.

**To Reproduce**
1. Navigate to the gradeable page of a Numeric/Text gradeable. In my specific example, this is course CSCI-4963. The gradeable is flipped01. The corresponding URL is https://submitty.cs.rpi.edu/courses/u21/csci4963/gradeable/flipped01/grading?view=all The configuration of the gradeable is shown in screenshot 1.
2. Enter the value for the numeric field and the Text field and attempt to move to another row. Submitty marks the text field with red and shows an error message. See screenshot 2. The error message doesn't really tell me what I did wrong.
3. Attempt to click in the text field and press arrow to the left. Instead of moving the insertion point to the desired word that needs to be edited, it moves the focus to another field and triggers the error message. Clicking in the middle of the text also doesn't move the insertion point but instead selects the entire text. Pressing right arrow has no effect whatsoever. See the animated gif.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Mozilla Firefox 90.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/129788802-5012c52b-76ed-40be-9f7e-22a5d264c55d.png)
![image](https://user-images.githubusercontent.com/7108039/129789750-ce5c9dd9-f139-4fd4-9778-a164aee848b5.png)
![WaqzbfSizI](https://user-images.githubusercontent.com/7108039/129789453-f21774eb-002d-4e5d-a876-0205a588967f.gif)

**Additional context**
N/A

**Comment by williamjallen** [comment]
Are there any errors in the console currently?

**Comment by williamjallen** [comment]
I believe that the issue here may be related to https://github.com/Submitty/Submitty/issues/6940 as a web sockets issue on the production server but I'm not certain.

**Comment by KCony** [comment]
Nothing particularly interesting in the console. When it fails to save my text, here is what gets logged:
![image](https://user-images.githubusercontent.com/7108039/129790976-ac5fa7a7-cbd2-4832-b058-fdb55bcacfee.png)

**Comment by KCony** [comment]
If I refresh the page, all edits are saved:
![image](https://user-images.githubusercontent.com/7108039/129791099-07cd1e31-2df0-402c-ab6d-94a667c4d796.png)

bu it is quite annoying to dismiss the error message and refresh the page after entering every single comment.

**Comment by KCony** [comment]
One of the latest updates fixed the "Refresh Page" issue but the inability to move the insertion point with arrow buttons or clicking inside the text to edit it remains. So, the issue cannot be marked as fully resolved.

**Comment by zacharymnp** [comment]
This cannot be reproduced, so it was likely fixed. If the issue reemerges, feel free to reopen.
