### ISSUE TITLE
Discussion Forum accessible via direct URL but not visible on sidebar

### ISSUE THREAD

**Issue by benjaminrsherman** [Submitty/Submitty#6989]
**Describe the bug**
For certain classes, the discussion forum is not visible on the sidebar but is accessible via direct URL.  If it's accessed by the URL, clicking on any post directs to the gradeables page instead of the post.

**Expected behavior**
The discussion forum should be visible on the sidebar and posts should be able to be viewed.

**To Reproduce**
1. Go to the submitty page for an affected class.
2. Despair at the lack of a forum link on the sidebar.
3. Go to the forum for the class directly.
4. Try to open any forum post.
5. See error.

**Configuration**
- Linux, Firefox 91.0.2
- iOS 14.7.1, Firefox Daylight 36.0 (5732)
- iOS 14.7.1, Safari

**Screenshots**
![image](https://user-images.githubusercontent.com/15524035/131405795-cc9de0c7-cea8-42a0-9477-c71d89a58525.png)
The above screenshot was accessed via directly entering the forum url.  Post information has been redacted for privacy purposes.

**Additional context**
The following RPI courses were affected for me:
- CSCI 4460 (I am registered for CSCI 6460).  The issue has not been resolved for this course.
- CSCI 4150 (I am registered for CSCI 6150).  The issue has been resolved for this course.
- CSCI 1200 (I am a full-access grader for this course).  The issue has been resolved for this course.

**Comment by MasterOdin** [comment]
Is the forum enabled in these courses?

**Comment by bmcutler** [comment]
To clarify, I believe these are the steps to reproduce:
enable the forum
make some threads posts - bookmark/save the url to the forum
disable the forum
try to reload/go to the forum urls directly -- they still work (some pages load), or sort of work.

When the forum is disabled, all attempts to access forum urls should be redirected to the homepage, possibly with an error popup that indicates the forum is disabled.
