### ISSUE TITLE
Investigate usage of Docker for sandboxing user applications

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#700]
Right now, we install all software on the machine, whitelist commands, and then allow instructors to create commands based on that. However, this does make it hard for instructors to configure things on the fly (as it requires going through us to whitelist the command and install the program). 

However, a problem starts to arise if we want to support multiple versions of a programming language (an example would be that NodeJS 0.10.25 is available on Ubuntu 14.04 while the latest version is 6.6.0, but maybe they want to use the LTS 4.5.0). We would have to restrict the version that an instructor could use for languages that don't allow for easy switching of versions in a way that doesn't intrude on the system or other users. Another example would be installation of python packages as right now all packages are installed system-wide which might not be preferable (not allowed to use a package for a given homework, etc.)

It might be useful to investigate the use of something like Docker to handle this for us in that the workflow would be:
1) Instructor chooses a docker image to use
2) Gives us a script of commands to run when creating image
3) Student uploads code
4) Docker image created for student
5) Student code run on docker image
6) Results saved and docker container destroyed

This would lead to some amount of more overhead than our current set-up, but it might not be prohibitive as because Docker is a container rather than VM, it shares resources nicely (keeping space requirements down) with the host and should spin-up in seconds rather than minutes like a VM.

We should also cache the created docker image for reuse by the instructor again (we should use something like sha-256 hash for the image name). Any images that are not used for some period of time (> 6 months? >1 month?) are destroyed via a daily cron job to keep space usage down.

As stated, this would mainly be to allow instructors an easier time to configure an assignment environment to better fit their needs without us needing to do anything our selves. Additionally, this means that we do not have to maintain a global whitelist for all courses, but that instructors can configure this feature for themselves within the image.

We would continue to use Vagrant for our main development infrastructure however.

**Comment by MasterOdin** [comment]
Potentially relevant papers :

1. [Docker as Platform for Assignments Evaluation](http://www.sciencedirect.com/science/article/pii/S1877705815005688)

(others should edit this comment as papers are found)

**Comment by JCBird1012** [comment]
First of all, great idea! 

As of now, what privileges are Submitty programs ran with relative to the system, and what other safeguards are taken to isolate Submitty programs from the rest of the system?

**Comment by MasterOdin** [comment]
Running the student code inside the Docker image still requires us to have any resulting files have the proper permissions such that hwcron (or untrusted) can have access to them on completion:
https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by MasterOdin** [comment]
So I'm going to split this into two stages:
Stage 1 (simple):
1. Create a Dockerfile per semester+course with the needed specifications (whatever languages, etc.)
2. Build that dockerfile giving it the name of semester+course: `docker build -t ${SEMESTER}_${COURSE} .`
3. When we get to autograding, we want to run it with this on the front of the command:
`docker run --name ${SEMESTER}_${COURSE} -v /var/local/submitty/autograding_tmp/${UNTRUSTED} /home/mount /bin/sh -c "...run autograding code..."
4. Copy out files as necessary

Stage 2 (harder):
1. Allow instructors to either:
    a. Use preconfigured Dockerfile per homework
    b. Define their own Dockerfile per homework (this should be reusable for all other homeworks)
2. Writer Dockerfile image to use within the autograder JSON file
3. Build the Dockerfile after saving a homework (part of build homework process?)
4. Use this custom docker build within the grading process

For 1a. I'd like to allow instructors to be able to specify a couple different versions of languages (Python 2.7, Python 3.4, Python 3.5, Python 3.5, GCC-6.x, GCC-7.x, etc.)

I'll probably handle this through the use of finding and using various PPA (or building some of our own as necessary) as downloading and building some of these would be somewhat prohibitive in time and resources used (such as GCC, though we would only need to compile it once as Docker would cache and use that for all future attempts).

**Comment by MasterOdin** [comment]
This issue is being closed with the initial implementation being done in PR #1720 and the rest of the work to be broken up into a bunch of subsequent issues and then tracked within https://github.com/Submitty/Submitty/projects/3
