### ISSUE TITLE
Student Contact Information is not shown to the instructor in the Office Hours Queue

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#7000]
**Describe the bug**
When student joins the office hours queue and specifies their contact information, this contact information is not shown in the TA/instructor view of the queue.

**Expected behavior**
Student's contact information, if provided, should be shown in the TA/instructor view of the queue.

**To Reproduce**
1. On the student's side, navigate to the Office Hours Queue page. In my specific example, this is course CSCI-2500. The corresponding URL is https://submitty.cs.rpi.edu/courses/f21/csci2500/office_hours_queue 
2. Select an open queue from the dropdown list, enter the access code and specify contact information. See screenshot 1.
3. Click "Join" and observe that the student was successfully added to the queue. See screenshot 2.
4. On the instructor side, navigate to the Office Hours Queue page. URL is the same as in step 1. Refresh the Web page and observe that the student's name is shown in the queue but no contact information is visible. See screenshot 3.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Mozilla Firefox 91.0.2 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/7108039/131604665-4259840c-9852-45aa-b507-e955fb27f32f.png)
![image (1)](https://user-images.githubusercontent.com/7108039/131604675-550735a1-acb8-4ecd-bf1c-d4dcd0d97ef0.png)
![image (2)](https://user-images.githubusercontent.com/7108039/131604682-f0882286-c9a4-4933-b39f-2f7ca08a8cd6.png)

**Additional context**
It was discovered by @bmcutler and confirmed by me that using `.*` as the regex pattern for a particular office hours queue mitigates the problem.

**Comment by RahulJha393** [comment]
Do you want a new column to display the contact information of the students?
@KCony

**Comment by KCony** [comment]
@RahulJha393 I'd say it doesn't really matter that much if it is a separate column, as long as this information is shown in the instructor view. Whatever was implemented before things got broken after regex's were introduced, I think worked fine.
