### ISSUE TITLE
Unread & deleted thread/post

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#7027]
**What problem are you trying to solve with Submitty**
Only instructors (& other teaching staff?) can view deleted thread/posts.  

[in light mode] When a post is new/unread, it is light blue.  When a post is deleted it is grey.  However, when a post is both deleted and unread, it is blue.  It is rare, but it can be confusing.  Let's it a different darker grey blue in this case -- how about '#aabbcc'.

...  also a pick a color that works in dark mode.

**Comment by Gauravjadhav22** [comment]
assign me this issue..

**Comment by Tausif4171** [comment]
Hii, Is this issue still open?
