### ISSUE TITLE
Improve account-summary.php page

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#703]
Should add two additional columns that show submitted and status flags. 

Submitted is a binary switch with green check (submitted) or red x (not submitted). 

Status is a trinary switch with green check (all good), yellow exclamation point (late), or red x (too late or not submitted -> bad)

**Comment by bmcutler** [comment]
blocked by #722

**Comment by bmcutler** [comment]
another duplicate to #890
