### ISSUE TITLE
View queue statistics on empty queue page leads to error page

### ISSUE THREAD

**Issue by HenrikLam** [Submitty/Submitty#7034]
**Describe the bug**
A frog robot occurs when I clicked view queue stats. I had a queue opened, however, there was no one in the queue. I have tested the button when there is no queue, and the frog robot also occurs there. Pictures attached for context of the issue.

**Expected behavior**
The button should simply lead to the statistics page with no entries in the tables. Frog robot error should be fixed.

**To Reproduce**
1. Go to the office hours queue page
2. Start a new queue
3. Click view queue stats

Alternatively, you can just click view queue stats when there is no queue.

**Configuration**
 - OS: Windows 10
 - Browser: Chrome

**Screenshots**
How my queue was set up
![image](https://user-images.githubusercontent.com/49821332/132367625-b90c9312-4993-48af-b6b7-15a1e1d6e462.png)

Frog robot message
![image](https://user-images.githubusercontent.com/49821332/132367511-c1ff5fda-593a-454f-81f3-ad30d4369e40.png)

**Comment by williamjallen** [comment]
Is this the same error described in this issue?  https://github.com/Submitty/Submitty/issues/6909

**Comment by HenrikLam** [comment]
> Is this the same error described in this issue? #6909

Seems like it is the same error. Perhaps this was reintroduced recently.
