### ISSUE TITLE
Removal of margin for card in peer matrix tab

### ISSUE THREAD

**Issue by HenrikLam** [Submitty/Submitty#7039]
**Current behavior**
Currently, the cards in the peer matrix tab seems to be misaligned with the table. This is due to the inherent padding that comes with the `card` class. Let's add a new class to the card that overrides the padding or get rid of the padding if we can not override it.

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

**Screenshots**
![image](https://user-images.githubusercontent.com/49821332/132424025-b1d79151-c804-48b5-b52d-eed69861e15f.png)

**Comment by williamjallen** [comment]
I suspect that something with Bootstrap has been changed recently.  I am seeing new UI changes on the plagiarism interface which look like Bootstrap updates to me.  I looked for the source of the issue but couldn't find anything which may have caused this.  I believe the issue affects anything which uses the Bootstrap grid (which is the only part of Bootstrap currently updated by dependency PRs), most notably when it affects padding/margins and table borders.
