### ISSUE TITLE
Out of place white colored background in dark mode.

### ISSUE THREAD

**Issue by HenrikLam** [Submitty/Submitty#7040]
**Describe the bug**
The Numeric/Text gradeable table have an obnoxious white background when in dark mode.

**Expected behavior**
The background should fit the theme of dark mode. This can be done with `table-striped` class, or just giving it a transparent border.

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

**Screenshots**
![image](https://user-images.githubusercontent.com/49821332/132424409-3f04da1d-f4f2-40cc-9c47-837ee67958b4.png)

**Comment by Gulsonish** [comment]
I think you're talking about this segment if --default-white could be dark as per the dark mode changes, right??

![Screenshot 2021-09-09 003341](https://user-images.githubusercontent.com/83022751/132745351-a7b914ab-c989-40b2-ac50-2775f65b2f35.png)

**Comment by HenrikLam** [comment]
If the site is set to dark mode, the `--default-white` will actually be a shade of gray (see `colors.css`), which is actually what we want. However, since these 2 tables in my screen shot does not use the `table-striped` class, these lines do not apply to the tables.

**Comment by Gulsonish** [comment]
Okay, I am looking into that. But I have another solution, I don't know if it will work and You can look into my PR #7051
> colors.css

**Comment by Gulsonish** [comment]
> colors.css

the <tr> in table having multi-field class and mult-field-0 id and I have used this class and id to fix this issue.
