### ISSUE TITLE
Frog Robot page is shown when grading a student with multiple bulk-uploaded files

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#7069]
**Describe the bug**
For a bulk upload gradeable, if a student has multiple files uploaded for them, clicking on the "Grade" button causes a frog robot page.

**Expected behavior**
A grading page should be open normally even for students with multiple bulk uploaded files.

**To Reproduce**
1. Do a bulk-upload of PDF for students, including the students who have additional files to be uploaded later.
2. Upload a file of the student who has additional files (e.g., a text file to complement the scanned PDF). When Submitty asks how to treat the new file, tell it to keep both the old file and the new file.
3. Go to the grading index and click "Grade" for the student with multiple files. See screenshot 1.
4. Observe the frog robot error page. See screenshot 2.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Mozilla Firefox 91.0.2 (64-bit)

**Screenshots**
![image (3)](https://user-images.githubusercontent.com/7108039/133119489-bcb36e78-baae-4568-a4f2-3b9388ef1b79.png)
![image (4)](https://user-images.githubusercontent.com/7108039/133119502-f7091723-5bad-4d6d-bfe5-7a48c8b671c6.png)

**Additional context**
N/A

**Comment by shailpatels** [comment]
This issue should be closed by 
https://github.com/Submitty/Submitty/pull/7050 once it's merged 

@KCony
