### ISSUE TITLE
Editing thread expiration date missing on Firefox

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#7089]
**Describe the bug**
Instructor wants to change the thread expiration date for a pinned post.
Instructor clicks pencil to edit the thread/post.
The thread expiration date correctly appears in the edit thread modal for Chrome.
But it does not appear on Firefox.

Same behavior on both Windows & Mac.

**Comment by jenaybarela** [comment]
This was addressed by #7123
