### ISSUE TITLE
Late day table error when late day difference is negative

### ISSUE THREAD

**Issue by jportorreal00** [Submitty/Submitty#7093]
**Describe the bug**
There is a bug within the late day table view when the late day calculated has a negative difference.

**Expected behavior**
![image](https://user-images.githubusercontent.com/51247866/133696074-fa757d8c-c105-4bd1-888a-134b8ba68341.png)

**To Reproduce**
1. Add a late day for a user with the value 1 (this is date 1)
2. Add a late day for the same user with the value 2. It should take place after date 1 (this is date 2)
3. Add a late day for the same user with the value 1. It should take place after date 2 (this is date 3)

**Configuration**
 - OS: Windows
 - Browser: Chrome

**Comment by williamjallen** [comment]
Does this issue need to be closed now that #7095 has been merged?

**Comment by shailpatels** [comment]
Yeah this is closed by #7095
