### ISSUE TITLE
Newline in Submini poll breaks histogram

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#7106]
**Describe the bug**
(unintentional) newline in submini poll answer breaks the histogram view for instructor & students with a console error:

<img width="764" alt="Screen Shot 2021-09-18 at 12 37 03 PM" src="https://user-images.githubusercontent.com/5871417/133895958-51a1b328-2904-412c-8f0a-e9fc05760acb.png">
<img width="501" alt="Screen Shot 2021-09-18 at 12 36 45 PM" src="https://user-images.githubusercontent.com/5871417/133895964-748da8e0-95cb-40cf-87ab-2628c68c5e91.png">

**Expected behavior**
If we cannot handle newlines in the histogram viewer, they should not be allowed in the poll choices.
(If they are already not allowed, maybe I snuck one in since I used copy paste?)
However, it would be nice to allow newlines in the answers, and to support markdown formatting.  
The histogram already truncates lengthy answers...  so perhaps just fix the histogram to not break with newlines.

**Comment by KCony** [comment]
I just hit this very issue:

![image](https://user-images.githubusercontent.com/7108039/134750327-a73b4ecf-58a0-4b6f-aac6-1070026b175d.png)

I only had newline in one of the answer options and it still broke the histograms completely...

Also, in the edit mode of Submini Poll (the pencil icon), it is possible to add a newline to any of the answer options at any time. You just press Shift-Enter, and Submitty happily inserts a newline.
