### ISSUE TITLE
Switch to most recent version button not disabled for notebook gradeables

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#7108]
**Describe the bug**
When viewing a notebook gradable submission version that is not the most recent version, the green "switch to most recent" is not disabled when it should be disabled.

If a student tries to click it a submission is attempted to be made but then are shown an error message on trying to submit on an older version.

**Expected behavior**
Button should always be disabled

**To Reproduce**
1. Go to notebook gradeable with multiple versions (or submit multiple times)
2. Select a version from the dropdown that is not the most recent
3. See error

**Configuration**
 MacOS firefox

**Screenshots**
Example state where the button should be disabled:
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/12129065/134200379-bcf731ee-6f35-4b27-a24e-ec4ab042a129.png">

**Comment by imsks** [comment]
@shailpatels I'm new to open source. Can I work on this issue? Please guide me.

**Comment by shailpatels** [comment]
Hi @imsks  
Please read the suggestions for new developers here: https://submitty.org/developer#suggestions-for-new-developers and try and get a developer instance of Submitty running locally. Here are instructions for setting one up: 
https://submitty.org/developer/vm_install_using_vagrant
https://submitty.org/developer/development_instructions

You can find issues labeled "good first issue" here: https://github.com/Submitty/Submitty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

We cannot assign an issue to someone outside of the Submitty Github project, but if you make a PR we would be happy to review it and try to get it merged. Please try and look at the documentation at submitty.org and if you get stuck on something ask on the general chat here.

Once you have a developer instance running, instructions on how to reproduce the issue are above.
The button gets rendered in `app/templates/submission/homework/SubmitBox.twig`

**Comment by shailpatels** [comment]
@bmcutler it looks like the "switch to latest version" just renames the "submit" button on the gradeable page, is the purpose of the button to change what version you're on or should it just always be disabled

**Comment by loadedskiffer** [comment]
> @bmcutler it looks like the "switch to latest version" is really just the "submit" button on the gradeable page but renamed if you're not on the most recent version, is the purpose of the button to change what version you're on or should it just always be disabled ?

It is meant to always be disabled.

**Comment by shailpatels** [comment]
I've updated this issue to reflect the actual intended behavior, not that this issue is solved by #7102
