### ISSUE TITLE
Allow the create_term.sh script to fail gracefully for existing term

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#7160]
**What problem are you trying to solve with Submitty**
The create_term.sh throws an error when a second time with the same information. Thus, causing my ansible script to fail. 

**Describe the way you'd like to solve this problem**
I would like to be able to run create_term.sh with term information that already exists in the database and have it just confirm its there, instead of failing. So if you accidentally (or on purpose) ran the script twice, it would just show a nice message that the term already existed. A more declarative process.

**Describe any potential alternatives you'd tried to solve the problem**
Other scripts like, create_course.sh have more friendly failure/statement when the value already exists.

**Comment by MasterOdin** [comment]
Looking at this, I would consider it a bug that `create_course.sh` does not return an error exit code under all early exit conditions. I do feel like we should return some non-zero code as the script failed to do what it was asked (similar to `mkdir`). However, would it be preferable to add a runtime flag to ignore failure if course / term exists (similar to `mkdir`) or just have a unique exit code for that case which can be tested for within ansible?

**Comment by prestoncarman** [comment]
I think adding a flag to allow it ignore failure sounds like a good option. 

For Ansible, the playbook declares the state I want in the system. In this case a term and course to exist in Submitty. The scripts should succeed in either confirming the information is there or create it and only fail if something breaks.

Side note: While `create_course.sh` does a not fail execution when the class exists, it does not completely confirm it was set up correctly either. (Is that to many nots?) In my case, the term was missing, so it build the class, but could not associate it with a term. After creating the term and running the script a second time, the output suggests the course is set up, but is missing the link between course and term.
