### ISSUE TITLE
Late days and the database...

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#722]
At the end of autograding, we will add a call to write to a new(?) table in the database the autograding total score (perhaps separated into regular and extra credit points), and the timestamp, for that student/gradeable_id/version#.  Full details on the autograding  are only available in the results_grade.json file, and that file is unchanged.

Each time the student changes the active/to_be_graded version, we made a call to write to the database the current active version.  Note: this is not the same active version as the TA_graded_active_version.  Presumably they should be the same in most cases.  (students should not change the active version or submit new files after TAs have graded.)  Full details on the active version history are only available in the assignment_settings.json file, and that file is unchanged.

After these changes, all late day calculations (for the hw report, for the grade summaries export, for the TA grading rubric panel on student info, for the hw summary page list) will be database only. Specifically doing the subtraction of active or TA graded active submission timestamp - deadline, comparing to late day exceptions and late days allowed.  This will be robust to all types of edits (changing extension, changing deadline, regrading, changing verison graded, etc).  And it will be much faster than pulling some values out of files for each student.

Also, all autograding total scores, even for non ta graded items, will be in the database :)

TODO list:
1.  @JerameyATyler  or @MasterOdin :  Design whatever new tables/columns we need in the database to store autograding score & timestamp for each version, and active version for each gradeable & student.
2.  @bmcutler:  Write data to the tables after each autograding completion
3.  someone:  Write current active version to database.
4.  @JerameyATyler & @bmcutler:  scrape through all prior submissions this term to populate database with autograding & timestamp for every submission, and active for every gradeable & student.
5.  @JerameyATyler or @MasterOdin:  write & install code to use only database for all things late day and autograded.

EDITED TO ADD
1.  Make sure we test that if an assignment has "bad" status (too many late days used for one assignment, student used late days they did not have, etc):
   - the autograding score is zeroed out
   - the ta grading score is zeroed out
   - the student is not "charged" any late days
   - it is clear to the TA that the status is bad, and that they should not spend time to grade it  (but maybe allow them to put comments & scores if they know that an extension will be granted?  discuss more... )

**Comment by MasterOdin** [comment]
Proposed tables:

```
CREATE TABLE autograding_version (
    g_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    active_version integer,
    CONSTRAINT autograding_version_pk PRIMARY KEY (g_id, user_id),
    CONSTRAINT autograding_version_gid FOREIGN KEY (g_id) REFERENCES gradeable (g_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT autograding_version_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT autograding_version_version FOREIGN KEY (active_version) REFERENCES autograding_results (version) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE autograding_results (
    g_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    version integer NOT NULL,
    autograding_total numeric DEFAULT (0) NOT NULL,
    autograding_extra_credit_total numeric DEFAULT (0) NOT NULL,
    submission_time timestamp(6) without time zone NOT NULL,
    CONSTRAINT autograding_results_pk PRIMARY KEY (g_id, user_id, version),
    CONSTRAINT autograding_results_gid FOREIGN KEY (g_id) REFERENCES gradeable (g_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT autograding_results_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);
```

**Comment by bmcutler** [comment]
tweak table names:  remove "autograding" from the table titles.  homeworks with no autograding still have a version.  and a timestamp.

maybe call them submission_version, and submission_info?  (not sure)

**Comment by MasterOdin** [comment]
how about `electronic_gradeable_version` and `electronic_gradeable_results`?

**Comment by bmcutler** [comment]
Yeah, sounds good

**Comment by MasterOdin** [comment]
Are we fine with doing a sed replace with the database information directly into the python file for now?

**Comment by bmcutler** [comment]
If it's owned and accessible only by hwphp or hwcron (which step are we talking about), sure.

**Comment by MasterOdin** [comment]
I assume it'll have the same permissions as grade_student.sh

**Comment by bmcutler** [comment]
well that's got non-hwcron read permissions (it doesn't have any password)

**Comment by MasterOdin** [comment]
what user runs grade_student.sh?

**Comment by bmcutler** [comment]
hwcron, but the script itself may be readable by other users (for no particular reason or danger)

**Comment by bmcutler** [comment]
what step are you working on?  it sounds like your working on my step

**Comment by MasterOdin** [comment]
I'm working on several steps I'm not directly assigned to. The latest commit 8b829a30c4ff00755d38571bfa0e9c62e96790b3 deals with step 4 decently well.

**Comment by MasterOdin** [comment]
Branch autograding is ready for hooking up the autograder to using the `insert_database_version_data.py` script.

Installation of this would be:
```
sudo apt-get install postgresql-contrib libpq-dev python-dev
sudo pip install sqlalchemy
sudo pip install psycopg2

sudo chmod -R 555 /usr/local/lib/python2.7/*
```

and the following database queries
```
CREATE TABLE electronic_gradeable_data (
    g_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    g_version integer NOT NULL,
    autograding_non_hidden_non_extra_credit numeric DEFAULT 0 NOT NULL,
    autograding_non_hidden_extra_credit numeric DEFAULT 0 NOT NULL,
    autograding_hidden_non_extra_credit numeric DEFAULT 0 NOT NULL,
    autograding_hidden_extra_credit numeric DEFAULT 0 NOT NULL,
    submission_time timestamp(6) without time zone NOT NULL
);

CREATE TABLE electronic_gradeable_version (
    g_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    active_version integer NOT NULL
);

ALTER TABLE ONLY electronic_gradeable_data
    ADD CONSTRAINT electronic_gradeable_data_pk PRIMARY KEY (g_id, user_id, g_version);

ALTER TABLE ONLY electronic_gradeable_version
    ADD CONSTRAINT electronic_gradeable_pk PRIMARY KEY (g_id, user_id);

ALTER TABLE ONLY electronic_gradeable_data
    ADD CONSTRAINT electronic_gradeable_data_gid FOREIGN KEY (g_id) REFERENCES gradeable(g_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY electronic_gradeable_data
    ADD CONSTRAINT electronic_gradeable_data_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE;

ALTER TABLE ONLY electronic_gradeable_version
    ADD CONSTRAINT electronic_gradeable_gid FOREIGN KEY (g_id) REFERENCES gradeable(g_id) ON DELETE CASCADE;

ALTER TABLE ONLY electronic_gradeable_version
    ADD CONSTRAINT electronic_gradeable_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE;

ALTER TABLE ONLY electronic_gradeable_version
    ADD CONSTRAINT electronic_gradeable_version FOREIGN KEY (g_id, user_id, active_version) REFERENCES electronic_gradeable_data(g_id, user_id, g_version) ON UPDATE CASCADE ON DELETE CASCADE;
```

**Comment by MasterOdin** [comment]
I'd like to see the current autograding branch edited and then merged into master so that tasks 1-4 can be accomplished and then I will handle 5 in a separate PR as I'm going to accomplish that with a larger rewrite of the code to get the gradeable information as well (more efficient, less queries, etc.)

**Comment by bmcutler** [comment]
We have finished this.  Will create new issues if we find bugs
