### ISSUE TITLE
URL routing flexibility

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#7253]
**What problem are you trying to solve with Submitty**

The url to the main page of my course, and the forum for my course are:
https://submitty.cs.rpi.edu/courses/f21/csci1200
https://submitty.cs.rpi.edu/courses/f21/csci1200/forum

But if I manually type in these urls and add a trailing slash, e.g.,
`https://submitty.cs.rpi.edu/courses/f21/csci1200/`
`https://submitty.cs.rpi.edu/courses/f21/csci1200/forum/`
I get re-directed to the main submitty page (it is treated as an invalid url/route)

**Describe the way you'd like to solve this problem**
Can we make the routing a little more flexible and go to the intuitive page?

**Comment by wusatosi** [comment]
This seems to be a simple request, but I am not terribly sure how to implement it. 
There's an [official guide](https://symfony.com/doc/3.3/routing/redirect_trailing_slash.html) in symfony about this, writing a controller handling anything matching `.*\/$` in the url and returning a 301 would work. 
Though I don't know how to order this controller to make sure it has the least priority for url matching comparing to the others.

**Comment by MasterOdin** [comment]
@bmcutler, Do we need to allow both `https://submitty.cs.rpi.edu/courses/f21/csci1200/forum` and `https://submitty.cs.rpi.edu/courses/f21/csci1200/forum/`? Or could it be that `https://submitty.cs.rpi.edu/courses/f21/csci1200/forum/` just silently redirects to `https://submitty.cs.rpi.edu/courses/f21/csci1200/forum`?

If it's the latter case, the easiest implementation might be to patch the apache configuration.

**Comment by bmcutler** [comment]
A silent redirect should be fine.
