### ISSUE TITLE
Visiting the grading stats page turns off random order

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#7283]
**Describe the bug**
If random order is turned on, visiting the grading stats page and then returning to the grading index turns random mode off.

**Expected behavior**
Random order mode should remain on when visiting the grading stats page and returning.

**To Reproduce**
1. Visit a gradeable and turn random order on
2. Visit the grading stats page
3. Visit grading index again

**Comment by daviddevore** [comment]
Where can I find the relevant files to fix this issue?

**Comment by GargDivanshu** [comment]
Im a beginner in Open-source and willing to start my journey, i wish to contribute & pls if possible do assist me by assigning & telling what prerequisite knowledge to cover to fix a issue
