### ISSUE TITLE
Useful error when worker machine partition has no available space

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#7315]
**Describe the bug**
One of our worker machines ran out of space on / (root).
Causing autograding jobs got stuck on the worker machine.
The jobs just froze in the queue.  No error was returned back to the primary machine.
Running /usr/local/submitty/sbin/restart_all_shippers_and_workers.py script ran successfully, 
but some of the jobs (the jobs re-assigned to the broken machine) immediately got stuck again.

**Expected behavior**
Besides getting stuck, it would be helpful to have an error message and/or a timeout happen.

NOTE: The machine ran out of space because /var/lib/docker/overlay2 was large (20GB) and the machine had been mispartitioned with a significantly smaller than intended amount of space available for /var.

Maybe the restart_all_shippers_and_workers.py script should do basic file system checks on return warnings if a partition is > 80% full?

**Comment by MasterOdin** [comment]
Should be easy to minimally add some statistic printing to starting the shipper / worker process using the [`shutil.disk_usage`](https://docs.python.org/3/library/shutil.html#shutil.disk_usage) method. Given a small enough amount of free space, we could just have the worker fail immediately and not even allow picking up jobs?
