### ISSUE TITLE
Consistently handle unreachable worker machines

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#7339]
As shown below, we do not consistently handle unreachable worker machines during update. If we can reach the machine, but SSH times out, then we skip the machine. If the machine is totally unreachable, than we error out.

The intended behavior I think is to just skip unreachable machines. We may wish to update the script though to prevent out a "summary" of the update process to make sure the user is aware the installation failed given that the install log is quite chatty.

---- 

_Posted by @wusatosi in https://github.com/Submitty/Submitty/issues/7332#issuecomment-962680291_

There is another problem associated with this issue though, our CI system [is not reporting this bug](https://github.com/Submitty/Submitty/runs/4128241910?check_suite_focus=true#step:3:5690).

From CI:
```
ubuntu-20.04: Stopping all remote machine workers...
ubuntu-20.04: perform worker stop on worker machine submitty-worker
ubuntu-20.04: ERROR: could not open a connection to the target host: timed out
ubuntu-20.04: ERROR: could not ssh to submitty@172.18.2.8 due to following error: timed out
ubuntu-20.04: Connection to machine submitty-worker timed out. Skipping this machine...
ubuntu-20.04: done
```
From local:
```
ubuntu-20.04: Stopping all remote machine workers...
ubuntu-20.04: perform worker stop on worker machine submitty-worker
ubuntu-20.04: ERROR: could not open a connection to the target host: [Errno None] Unable to connect to port 22 on 172.18.2.8
ubuntu-20.04: ERROR: could not ssh to submitty@172.18.2.8 due to following error: [Errno None] Unable to connect to port 22 on 172.18.2.8
ubuntu-20.04: submitty-worker: Failure performing the stop operation
ubuntu-20.04: ERROR: Could not stop the worker daemon on submitty-worker
```
It seems like in GitHub CI environment, the 172.18.2.8 (submitty worker address) is an reachable blackhole (which results in timeout), while in local development environment, this address is not reachable at all. The exit strategy is different for the two cases. 

Here is the related code:
https://github.com/Submitty/Submitty/blob/7119efc222377a81dd4dad0e0443e23f6c699701/sbin/shipper_utils/systemctl_wrapper.py#L101-L108
https://github.com/Submitty/Submitty/blob/7119efc222377a81dd4dad0e0443e23f6c699701/sbin/shipper_utils/systemctl_wrapper.py#L73-L76
They are related to #6819 ([highlighted](https://github.com/Submitty/Submitty/pull/6819/files#diff-d742ff0e7957b505ca51dcba0c6fb688eba343776af0587a72bbc9042b23d94dR54-R76)).

Do we need to fix this? Is ignoring the worker when its timed-out but not when its unreachable intentional?
Should we treat timeout & unreachable worker the same problem and skip it entirely?

**Comment by wusatosi** [comment]
I did some testing and digging around the documentation. 
It seems when there's a timeout, it throws `socket.timeout`, when there's a connection error, it [throws](https://docs.paramiko.org/en/stable/api/ssh_exception.html) `paramiko.ssh_exception.NoValidConnectionsError`.
```
perform worker stop on worker machine timeout
ERROR: could not open a connection to the target host: timed out
>>>>> python class: timeout
ERROR: could not ssh to submitty@8.8.8.8 due to following error: timed out
Connection to machine timeout timed out. Skipping this machine...
perform worker stop on worker machine unreachable
ERROR: could not open a connection to the target host: [Errno None] Unable to connect to port 22 on 172.18.2.8
>>>>> python class: NoValidConnectionsError
ERROR: could not ssh to submitty@172.18.2.8 due to following error: [Errno None] Unable to connect to port 22 on 172.18.2.8
unreachable: Failure performing the stop operation
ERROR: Could not stop the worker daemon on unreachable
```

The above result is tested with worker configuration:
```
{
    "primary": {
    ...
    },
    "timeout": {
        "capabilities": [
            "default",
            "cpp",
            "python",
            "et-cetera",
            "notebook"
        ],
        "address": "8.8.8.8",
        "username": "submitty",
        "num_autograding_workers": 5,
        "enabled": true
    },
    "unreachable": {
        "capabilities": [
            "default",
            "cpp",
            "python",
            "et-cetera",
            "notebook"
        ],
        "address": "172.18.2.8",
        "username": "submitty",
        "num_autograding_workers": 5,
        "enabled": true
    }
}

```
