### ISSUE TITLE
View all of students grades in one place

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#736]
There should be a way to view all students' grades from a centralized place and be taken to any particular grade from this interface. 

The easiest place to put it right now is on the admin-only "View Students" area as an additional button next to the pencil that shows a popup (like the edit user one) that shows all grades.

Should be implemented in a similar fashion to the edit user box as well (opening the box sends an ajax request to the server to get the details to populate it with).

**Comment by bmcutler** [comment]
Once we have Rainbow grades running on the server, the instructor view of everything and instructor view of each student's individual file can be made available somewhere...

**Comment by bmcutler** [comment]
For starters, let's allow users with faculty access level in the master submitty database who are instructor users in a particular course to be able to view the rainbow grades .html file for any student in that course.   (Graduate student TAs who are serving as head TAs for the course cannot see this data) 

If Rainbow Grades is enabled, let's add a new column to the "Manage Students" table, all the way on the right.  A column of  icons -- same icon we use on the left sidebar for rainbow grades.  And when we click on it we can see the rainbow grades view for the selected student.

We need to use the access system to tightly lock down these files.  Normally you can only see your own .html, but only faculty user access with instructor type can view other user's .html.

**Comment by bmcutler** [comment]
related/duplicate #4789
