### ISSUE TITLE
displaying previous files inside directories inside zip

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#742]
I just fixed a bug for uploading a zip containing a directory.
But...  when listing the  files of a previous submission the directory is not included.  Thus when you try to upload a revised file list including any of those files you get an error.

**Comment by MasterOdin** [comment]
I guess we just display the directory object to the user as is (without any way to edit its contents)?

**Comment by ZishanHuang** [comment]
If a user uploaded a zip containing directories, should we replace the files in the directories if the user uploaded a revised zip?

**Comment by ZishanHuang** [comment]
Also found a bug:
The file viewer on the grading side won't display files that are in the directory of a zip.
Example:
-cats.zip
    -cats (folder)
        - cats.cpp

The grading page will display the cats folder but clicking on the link will not open the folder.

**Comment by ZishanHuang** [comment]
Based on the bug found, should we still allow submission of zipped directories?
@bmcutler

**Comment by bmcutler** [comment]
We must allow zip submission of directory structure.  

I don't understand the bug you found in the TA grading, but that certainly can and should be fixed as well.  They are using many level submission directory structure with SVN in Principles of Software.

**Comment by bmcutler** [comment]
To answer your first question about old & new files when uploading a zip:  I think mixing old & new is not worth spending time on.  How about...  if someone selects or drags a zip file to add to a bucket, we empty the bucket, then unzip the zip file.  That is the most likely use case anyway.

**Comment by bmcutler** [comment]
Closing now.
Remaining open request is #776
