### ISSUE TITLE
Add a "live" option to Gradeables

### ISSUE THREAD

**Issue by laprej** [Submitty/Submitty#748]
One thing that would be nice is if the students were able to see live updates to their grades.  One place where this may come in handy is during lab.  It's up to the students to make sure they are checked off for lab.  At the moment I don't think this is possible as we have to go through the process of pulling down all released grades and then sending them back to Submitty.

**Comment by bmcutler** [comment]
related to issue #1979 (hwcron daemon)

**Comment by bmcutler** [comment]
Closing this for now, once rainbow grades is updated regularly, that will be a big improvement.
