### ISSUE TITLE
indication of who submitted on homework overview page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#750]
A homework with no autograding has 0/0 and a blue grade box for everyone.
I think we were planing on adding more columns (active version?, etc).  
Just make sure it is clear on the overview page who has or has not submitted for non autograded homeworks too.

**Comment by JerameyATyler** [comment]
In addition disable the grade button for any assignment that has not been submitted. If time in this commit change ta grading for students with no submission. Skip the student when clicking the arrows. Give some visual indicator of % of students with no submission. Possibly add a third color to the right end of the progress bar for no submissions.

**Comment by bmcutler** [comment]
duplicate issue #890
