### ISSUE TITLE
Use YAML for autograding configuration files instead of JSON

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#751]
[YAML](https://en.wikipedia.org/wiki/YAML) provides a more "human readable" format for writing configuration files than JSON. It would also produce a more condense version of these files as well as allow for comments without having to add a preprocessing step like we do for the JSON. The con of this would be adding an additional library for parsing YAML files, but I believe the positives (smaller files, more human readable) outweigh that.

**Comment by chameco** [comment]
:+1:

I've had positive experiences with YAML in the past. Establishing some sort of dichotomy between human-readable/writable configuration files (in YAML or some similar format) and internal files (likely still JSON) seems generally beneficial, especially given that demonstrating how easy it is to write `config.json` has become a talking point.

**Comment by MasterOdin** [comment]
Yeah, this is mainly proposing any human facing file would use yaml while everything internal would stay JSON. The two formats are also completely compatible with each other, both being parsed into the same structures in various languages.

**Comment by MasterOdin** [comment]
An example of this (for a new file I'm writing):

```
- user_id: instructor
  user_firstname: Quinn
  user_lastname: Instructor
  user_email: instructor@example.com
  user_group: 1
  registration_section: null
  rotating_section: null

- user_id: student
  user_firstname: Joe
  user_lastname: Student
  user_email: student@example.com
  user_group: 4
  registration_section: 1
```

vs 

```
[
  {
    "user_id": "instructor",
    "user_firstname": "Quinn",
    "user_lastname": "Instructor",
    "user_email": "instructor@example.com",
    "user_group": 1,
    "registration_section": null,
    "rotating_section": null,
  },
  {
    "user_id": "student1",
    "user_firstname": "Joe",
    "user_lastname": "Student",
    "user_email": "student@example.com",
    "user_group": 4,
    "registration_section": 1
  }
]
```

And I can put a big block comment at the top on format of each record instead of having to document it elsewhere.

We'll also have PyYAML already installed due to SQLAlchemy being installed which will come from #740.

**Comment by bmcutler** [comment]
We need to be able to store both array-like and dictionary-like data in our configs.  While the extra {} and [] may seem like clutter in very simple config files, we need this in our complex configs.

**Comment by MasterOdin** [comment]
YAML supports both array-like and dictionary-like data though?
