### ISSUE TITLE
late day exceptions table only shows students or users w/valid sections

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#752]
This table should show all users with an exception for that gradeable.

**Comment by JerameyATyler** [comment]
I am able to insert exceptions for students that have NULL sections. There is a check that only allows exceptions for users in user_group = 4 (student group). Do you want this check removed to allow any user to be given a late day exception?

**Comment by MasterOdin** [comment]
We'd at least want to weaken it to only exclude instructors as it's possible an instructor may have a TA taking the class actively.

**Comment by JerameyATyler** [comment]
Closed. The checks were removed.
