### ISSUE TITLE
Colors used for numeric gradeables are hard coded

### ISSUE THREAD

**Issue by DanJanikowski** [Submitty/Submitty#7568]
**Describe the bug**
Within the 'simple-grading.js' file there are a bunch of uses of hard coded colors for numeric gradeables instead of using 'colors.css'. This mainly causes problems with the dark mode version of the site. When a number is entered, and the field is updated the background color of the cell will change to the light mode version color.

The uses in 'simple-grading.js' I found were on line numbers: 420, 466, 557, 560, 564, 905, 907

**Comment by immortalcodes** [comment]
I looked into the 'simple-grading.js' , I think changing the value of the hard coded colors to their respective standard names in the colors.css should solve the problem. I will add a pull request for it, please let me know if there is something else I shall take care off?

**Comment by immortalcodes** [comment]
@DanJanikowski @bmcutler 
I have changed all the hex codes in 'simple-grading.js' to standard names from colors.css in a separate branch in the forked repo.
I am facing problem for color '#ff7777' , as there is no standard name in colors.css , (shall I add it?) , are there any tests I should conduct?

**Comment by williamjallen** [comment]
@immortalcodes `colors.css` is currently overflowing with colors and we have been trying to reduce the number of colors lately.  Are there any existing colors which would be an acceptable replacement?

**Comment by immortalcodes** [comment]
'#ff9999' could be good replacement.

**Comment by williamjallen** [comment]
That seems to be a reasonable replacement, as long as it doesn't cause any contrast issues

**Comment by immortalcodes** [comment]
Shall I make changes and link a pull request for same?

**Comment by williamjallen** [comment]
Sure, you can always make pull requests.

**Comment by immortalcodes** [comment]
@DanJanikowski  could you please help me locate the exact place(in application) where the issue arises , so that I could validate the results after the changes.
