### ISSUE TITLE
Upvoting/Downvoting in Discussion Forum

### ISSUE THREAD

**Issue by bnidevs** [Submitty/Submitty#7570]
**What problem are you trying to solve with Submitty**
Would like to include upvoting and downvoting on answers/replies in the discussion forum so that good/insightful answers/thoughts/replies/questions rise to the top, in addition to the highlighting system that we have for posts from faculty and mentors.

This would add a layer of complexity of storing "like"/"dislike" counts in the database (whether or not you display these counts is another issue), then sorting (this can be delegated to frontend?) the posts based on these counts.

**Additional context**
This is a difficult addition due to storage constraints, so understandable if not able to be added.

I would also like to ask if there are any reasons other than difficulty of implementation that are factors in a "no", such as moderation (see [YouTube disables dislike count](https://blog.youtube/news-and-events/update-to-youtube/))

**Comment by sbelsk** [comment]
@bnidevs Thanks for the feature request! I will start working on this in the near future. After a bit of discussion, we decided on:
- students will be able to upvote posts
- see the upvote counts on posts and comments
- course staff can "endorse" a post or a comment
- upvotes and endorsements will not affect the sorting posts in the discussion forum (order will remain chronological)

**Comment by ziesski** [comment]
Additional Idea - Archived Discussion forum from previous terms could be reused (when instructor reuses the homework) - more like instructor tool, if it is marked as "good question", archive it and make it visible to current term users. 

Barb's comment during meeting 
- In CS1, Prof.Sibel curates "good questions" and display them in form of FAQ as PDF for future term users. 
- anonymity is important as past term users won't be expecting their name to be shared in future terms. 


Pro:
- Many students will trip over the same problem, which past term students have already experienced, this will reduce redundancy. 
- Especially submitty is continuously experiencing record breaking high volume of students each term, but with limited staff member, current response system from staffs may be less sustainable. 

Con:
- Many students don't even bother browsing through current discussion forum, experienced merging thread topic frequently [comment by Ryon during meeting], which means they might not make good use of archived comments. 
-  Might be making specific courses (i.e. Data structure) too easy and friendly? - but we all want students to success!

===========================================================================================

Current thoughts - instructor can press "insightful" button in discussion forum, which will be saved into matching HW directory.  ( I might want to study how scraping comment in reddit works?) 


Please add your thoughts on this, there may be various ups & downs :)

**Comment by ziesski** [comment]
> 

Additionally thoughts - I saw myself referencing some discussion forum answer from previous term to answer this term DS discussion forum, with common mistakes such as Submitty is broken because "works fine on my device but does not match Submitty output" for every homework, and depending on homework the answer slightly varies, such as for HW1 -> exceeding loop boundary, HW3-> maybe using iterator after .end() etc.

**Comment by d0ngeun** [comment]
Another possible feature idea:
-Changes since last view:
A number next to a post that details that there are __ changes/updates since you last viewed it. This would help someone know if there has been additional comments or answers to a question.
-Instructor/ta replied icon:
An icon/symbol that would show on a post to indicate an official response from an instructor or a ta has been made.

**Comment by d0ngeun** [comment]
A quality of life UI change that could also be made for the search results:
Bolded keyword that was searched.
Nested results instead of stacked, body of post would be indented underneath the post title.

**Comment by micpap25** [comment]
@ziesski Can this be closed since Upducks are implemented?

**Comment by ziesski** [comment]
@micpap25 Yes, can you link the PR to it and close it please?

**Comment by micpap25** [comment]
Closed by #10017
