### ISSUE TITLE
Fix incorrectly displayed late days in Student Information panel

### ISSUE THREAD

**Issue by JerameyATyler** [Submitty/Submitty#758]
For at least one student late days are displayed incorrectly. Also, status is displayed incorrectly in some instances. See image for example. Student has not used 134 late days. No late days were used on this assignment but it is still marked as bad. 
![incorrect_late_days](https://cloud.githubusercontent.com/assets/5366642/19814967/8f9e52fa-9d0e-11e6-93bf-07ef480508c7.png)
- [x] Display late days used for each assignment up to and include the assignment being viewed. Do not include any later assignments.
- [x]  Total late and display late days 
- [x] Fix incorrect assignment status
- [x] Give a strong visual indicator that the assignment is bad (red background)

**Comment by JerameyATyler** [comment]
![img_20161105_145223](https://cloud.githubusercontent.com/assets/5366642/20032757/d3c03fd4-a367-11e6-8f45-ca920f4b364f.jpg)

![img_20161105_150815](https://cloud.githubusercontent.com/assets/5366642/20032862/d7a88aa0-a369-11e6-8826-498bd1106578.jpg)


Create the table described in the image. The bottom row of the table will need to be included in the homework reports that the students see. 

- Allowed per term - from course config + late_days table.
-  Allowed per assignment - electronic_gradeable
- Late Days used - min(0, ceiling(timestamp-duedate)) egd join egv - eg
- Extensions - lde
- Status - calculated from previous column (see below for details)
- Late days charged = if (status != late then 0 else (ldu-excs))
- Remaining late days - allowed per term (at time of assignment) - sum(charged)

(Status : Good = No late days and submitted, Not submitted = no submission, Cancelled = cancelled submission, Bad too many used for this assignment = ldu - excs > allowed per assignment, Bad too man used this term = (ldu - excs) + sum( ldu - excs excluding this assignment), Late = ldu - excs > 1 && not bad status)

**Comment by JerameyATyler** [comment]
Add modal window to confirm grade submission when status is not submitted, cancelled, or bad

**Comment by bmcutler** [comment]
I think this is mostly finished.

**Comment by JerameyATyler** [comment]
Closed with new late day stuff
