### ISSUE TITLE
Late vs Bad Gradeable Visuals Unclear

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#7581]
**Describe the bug**
At the moment a gradeable can have a "late" banner if:
1. The version displayed was submitted after the due date and is still on time (due to late days/extensions)
OR
2. The version displayed was submitted after the due date and will be in the "Bad" state (too many late days/extensions used) AND there IS an earlier version that could be counted as "Late"/"On Time"
OR
3. The version displayed was submitted after the due date and will be in the "Bad" state (too many late days/extensions used) AND there IS NOT an earlier version that could be counted as "Late"/"On Time"

Currently if case 1 or 2 is true, when viewing the submission from the grading interface, the background is orange and an orange banner is displayed up top stating `Late (Roll-back to on time submission -X)` where X is a version number of a submission prior to the due date.

If case 3 is true, then instead the grading interface will have a red background and a red banner that states `Late (No on time submissions available)`

**Expected behavior**
This section needs to be discussed with @bmcutler 

Case 1 behaves as expected.

However, in cases 2 AND 3, we should display the red banner, since we are trying to indicate to the grader that until something changes (extension applied, student reverts to an earlier version if applicable), the grader probably does not need to grade this submission. Whether or not an earlier version exists to roll back to should not impact the grader's choice, since the student, not the grader should be the one to decide to select a different active version.

For case 2 we can still display the text about `(Roll-back to on time submission -X)`.

For cases 2 and 3 it may also be worth changing the word `Late` to something more descriptive to distinguish it from the orange banner. (Orange and red can be difficult for some people to differentiate.)

**To Reproduce**
1. Create a new gradeable with a deadline in the future. Make sure maximum late days allowed for the gradeable is 0 and that submissions will be accepted after the deadline.
2. On one user, make a submission to the gradeable
3. Close the gradeable (set the due date to Now)
4. On the same user, make a second submission to the gradeable
5. On a different user, make a submission to the gradeable
6. As a grader, view both submissions from the grading interface
7. See the difference

**Comment by DefinitiveAbove** [comment]
Discussed during meeting;

Case 1: Display that the assignment was late but is still valid (orange).
Case 2: Display that the assignment is bad (red) but there is a valid submission that the submitter has.
Case 3: Display that the assignment is bad (red) and that there is no valid submission that the submitter has.
