### ISSUE TITLE
Need Documentation for Student Activity Dashboard

### ISSUE THREAD

**Issue by sbelsk** [Submitty/Submitty#7603]
This feature was added in the summer and no documentation on it has been added to the Submitty docs.

**Comment by abhijain2003** [comment]
hey can I work on this. but I need more elaboration on this issue

**Comment by AnoshanJ** [comment]
[[#](https://github.com/Submi)](https://github.com/Submitty/submitty.github.io/pull/484)

**Comment by AnoshanJ** [comment]
[added documentation](https://github.com/Submitty/submitty.github.io/pull/484)
