### ISSUE TITLE
Markdown Code blocks Line Numbers Displaying Inconsistently 

### ISSUE THREAD

**Issue by sbelsk** [Submitty/Submitty#7614]
**Describe the bug**
Sometimes when inserting a code block using markdown syntax, line numbers appear next to the code block and some times they don't. In the following example I typed:
![image](https://user-images.githubusercontent.com/71195502/152708407-1e88f238-7947-40a2-a679-f2c87866608c.png)
and it rendered
![image](https://user-images.githubusercontent.com/71195502/152708415-b2b017e1-98b2-4635-8ef8-781c36c71264.png)
(this might be due to the two newlines at the end of the first block??)

**Expected behavior**
Options of handling this:
1. Line numbers should always be displayed
2. Line numbers should never be displayed
3. Line numbers should be displayed only when syntax highlighting is applied to the block for a specific language (do we even support syntax highlighting?)

**Comment by wusatosi** [comment]
From my testing, code segments that has more than 5 lines (inclusive) will have its line number displayed. 

5 Lines:
![image](https://user-images.githubusercontent.com/26424577/155828365-e88fb150-d460-409c-bf1c-a9dd693b9351.png)

4 Lines:
![image](https://user-images.githubusercontent.com/26424577/155828376-2b0d02aa-3ac0-470d-95f1-0c00c0b80902.png)

I don't think this is necessarily an undesired behavior.

**Comment by wusatosi** [comment]
This is the code segment that define this behavior:
https://github.com/Submitty/Submitty/blob/e46abea405692fe3e50bbca52d574ad5ad49b985/site/app/libraries/CustomCodeBlockRenderer.php#L25-L35

This is intentionally introduced in pr: #6755, diff [here](https://github.com/Submitty/Submitty/pull/6755/files#diff-a655c144f6e8967e42c4a98f83024b6e0f43c63348596e08a177f9832b5631feR28-R32).
