### ISSUE TITLE
Right click on buttons on navigation page allows user to open in new tab

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#764]
Users can have multiple submitty browser tables/windows open for different Submitty assignments.  But it could be made easier by allowing right click from the buttons on the main navigation page.  

Related to issue about getting rid of unneeded javascript #592

**Comment by MasterOdin** [comment]
This issue (and #592) has work already done in the issue_764 branch. The main issue is that changing to `<a>` tags instead of buttons breaks the styling somewhat so whoever does this needs to fix that and then this should be ready to go.

**Comment by MasterOdin** [comment]
Tracked in #592. Closing this as duplicate.
