### ISSUE TITLE
Calling TypeScript functions from Twig/Event Listeners

### ISSUE THREAD

**Issue by DefinitiveAbove** [Submitty/Submitty#7689]
**What problem are you trying to solve with Submitty**
Currently, any inputs/items that need events that depend on TypeScript code either has the event listener for the item added inside of the TypeScript file that has the function to be called or in a Twig file under a module type script tag. While it isn't much of an issue now, as more files are migrated over to TypeScript this could lead to worse code readability when there are TypeScript files that are depended on by multiple Twig files that need different event listeners (putting them in the top-level module when it is depended on by multiple Twig files means adding event listeners that are unnecessary for some of the files or having multiple init functions in the module, and putting them in the Twig file requires a separate script tag to add them and loses the TypeScript checks). Additionally, importing from module files in Twig means that you have to get the timestamp of the file over to Twig if you don't want to request the file twice.

**Describe the way you'd like to solve this problem**
Below are some potential ideas for trying to keep it a bit more organized:

Attach objects from TypeScript onto the `window` global variable:

+ Can call functions directly in non-module JS/in HTML in Twig; very similar to current style of many Twig files
- No TypeScript coverage in Twig files
- Potentially clutter `window` global variable (one way to reduce this clutter could be to have each top-level module only put one object on the `window` global variable and have all of the necessary functions/variables for that module in that object)

Individual .ts files for each Twig file that are all entry points:

+ Potentially full TypeScript coverage (if no calls in Twig files)
- Potential bloat from redundant bundled dependencies, many files may lead to high overhead

Individual .ts files for each Twig file that are exported into a single entry point:

+ Potentially full TypeScript coverage (if no calls in Twig files)
- File is bloated for most pages

It should also be noted that to have full TypeScript coverage, the data from Twig has to be sent through other methods (attributes in HTML/AJAX calls).

**Comment by MasterOdin** [comment]
One option not considered is doing more [code splitting](https://esbuild.github.io/api/#splitting), where then any common code that's been split off into its own file would then be shared amongst several independent entrypoints. This would ideally lower the amount of duplicate JS that would get loaded page to page to pretty minimal, while also making it easy to keep everything in TS files.

> Attach objects from TypeScript onto the `window` global variable

I am very much opposed to this approach as it bleeds global state all over the place making debugging a huge chore, and also potentially introduces race conditions depending on where someone is trying to get things to bleed to.
