### ISSUE TITLE
Late days allowed should allow removing late days

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#770]
If the instructor would like to modify the allowed late days for a student to decrease the number...  this doesn't currently work.

If a course starts everyone at 3 late days.  But we'd like to zero out the available late days for a specific student, using the late days web form doesn't work.  You can't specify zero (that is used to undo-ing/removing an edit to allowed late days). And it seems if you specify a value less than the default it ignores it.   

Wish list:
You should be able to increase or decreased allowed late days.
You should be able to set allowed lates for a student to zero, effective a specific date. 
We should use some other mechanism to delete an entry in this table (besides the hack of "0")

**Comment by bmcutler** [comment]
I think this is partially or fully complete...  ?

**Comment by JerameyATyler** [comment]
This should be completed with the new late day stuff.
