### ISSUE TITLE
Submitty Progressive Web App (PWA) GSOC 2022

### ISSUE THREAD

**Issue by ForchaGlen** [Submitty/Submitty#7730]
Hi everyone congratulations to Submitty on being a selected organization for GSOC 2022.
1-Please How may I start contributing?
2-Please for the link to join the Joomla developer group.

**Comment by khaled9912** [comment]
Hi There, I wanna contribute to this issue please how can I do so ?

**Comment by shailpatels** [comment]
Issues created should be related to the Submitty project, please see the following links for gsoc specific information and how to start as a contributor 

https://submitty.org/developer/google_summer_of_code/index
https://submitty.org/index/overview
https://submitty.org/developer/getting_started/index
