### ISSUE TITLE
Peer Graders should not be able to grade themselves

### ISSUE THREAD

**Issue by alicebibaud** [Submitty/Submitty#7731]
**What problem are you trying to solve with Submitty**
When peer grading, the option exists that students may grade themselves.  This is not an objective evaluation of the student's progress in the class

**Describe the way you'd like to solve this problem**
I would like to remove that capability by graying out relevant profiles.  For example, if Ben Bitdiddle was a peer grader (perhaps a mentor in RCOS), his profile in the grading section would be greyed out, so he wouldn't be able to enter a score in for himself.  The amount of assignments left to be graded should not include this other profile in the percentage of grades left to go.

**Describe any potential alternatives you'd tried to solve the problem**
I haven't considered any other alternatives, but there are many potential solutions to this problem.

**Comment by bmcutler** [comment]
@alicebibaud 
We were not able to reproduce this issue.
Can you please email me more specifics about the problem you saw?
We did find an error with the instructor interface for adding graders -- but I don't think that is what you describe above.
