### ISSUE TITLE
Uploading file with same name does nothing?

### ISSUE THREAD

**Issue by luciencd** [Submitty/Submitty#775]
Submitted machine learning homework, and it had a name "Lucien Christie-Dervaux Machine Learning Homework 9 Google Docs.pdf"

Then I changed the file (Downloaded it again from google docs) and reuploaded it by dragging it into the thingy.

Nothing changed with the file size, even though the file was supposed to be different.

So i changed the name of the file, and reuploaded, and the file size was different. 

Is it possible that uploading a file with the same name doesn't do anything?

**Comment by MasterOdin** [comment]
When you tried uploading it the second time, did you get any errors or did the submission at least go through?

**Comment by ZishanHuang** [comment]
Do you see a pop-up that tells you the file names are the same and asks you if you want to replace the file or not? Can it be possible that pop-up boxes are disabled in your web browser?
<img width="938" alt="popup" src="https://cloud.githubusercontent.com/assets/13242335/20240873/b88900c2-a8f1-11e6-9fd6-a1853072a70c.png">

**Comment by luciencd** [comment]
No I didn't get a popup. Not sure if popups are disabled, but I doubt it. I can check later. 

The second time I tried uploading, I never got any errors, it was just a lack of action. That's why I tried changing the file name to see if something would change

**Comment by bmcutler** [comment]
Closing.  Please reopen with more details if it's still an issue.
