### ISSUE TITLE
Homework Reports Totals Calculation Incorrect

### ISSUE THREAD

**Issue by bluemellophone** [Submitty/Submitty#783]
The total number of points shown to the student when the HWReport option is selected is calculated incorrectly when there are negative rubric items.  We have a HW gradable with a rubric item with -80 points and set to extra credit, but the reports generated for the students is incorrectly summing that -80 and making the total score artificially low.

For example, see here: http://imgur.com/a/C9mKD

**Comment by bmcutler** [comment]
I believe this was fixed in a recent PR.
