### ISSUE TITLE
Add "Expand All/Collapse All" Functionality to Gradeable Results

### ISSUE THREAD

**Issue by bnidevs** [Submitty/Submitty#7866]
**What problem are you trying to solve with Submitty**
There is no easy way to open ALL of the gradeable sections other than by pressing "Show Details" for every single section of the gradeable, which becomes frustrating because the rest of the sections shift downward when sections above them are opened.

**Describe the way you'd like to solve this problem**
Add a similar "Show Details" text on the Autograding/Grading Total bar displaying "Expand All/Collapse All" which will open all the sections and close all the sections at the same time.

If some but not all of the sections are opened, "Collapse All" will be displayed and will "Hide Details" on all open sections. "Expand All will only be displayed if all sections are closed. (This is subject to UX/UI discussion, it can be the other way around, but this is just one proposal).

Here is the current appearance:

<img width="1430" alt="Screen Shot 2022-04-29 at 9 15 11 PM" src="https://user-images.githubusercontent.com/33227410/166085037-4450dbb7-9d8c-4669-9ae5-1fae4121fa7c.png">

Here is desired appearance and functionality:

<img width="1444" alt="Screen Shot 2022-04-29 at 9 14 58 PM" src="https://user-images.githubusercontent.com/33227410/166085041-6e96ab80-1cb1-4dce-a197-a8d6ae1a4361.png">

<img width="1432" alt="Screen Shot 2022-04-29 at 9 15 56 PM" src="https://user-images.githubusercontent.com/33227410/166085099-4153c892-a152-414b-9cd0-f54bb250dd01.png">

(Answers to autograder in attached photos are redacted for academic integrity)

**Comment by akshay2742** [comment]
Hello, I'm interested to work on this issue, can you assign me to work upon this

**Comment by AMMAR-62** [comment]
Hey! @akshay2742 , are you working on this issue?? if not may I take up this issue?? @bnidevs please give an update on this

**Comment by akshay2742** [comment]
Still it is not assigned to me

**Comment by bnidevs** [comment]
why are you mentioning me, its pretty clearly already assigned

**Comment by AMMAR-62** [comment]
Sorry for mentioning you! I am still a beginner to open source, don't know the best practices to follow here
