### ISSUE TITLE
Reading forum post does not clear related notification

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#8033]
I have all notifications turned on for several of my classes, and I receive a notification each time a post is made on the discussion forum.  If I go to the discussion forum and read multiple posts, I still see a corresponding notification badge on the sidebar.  This is annoying, because I have to manually clear the list every time I finish checking the forum.

Suggestion: Mark notifications as read automatically when the corresponding forum post or grade inquiry is viewed.  There is existing (albeit somewhat buggy) logic to mark forum posts as read, so it should be relatively straightforward to modify that code to also manage notifications.

**Comment by RayReyRam** [comment]
Unable to reproduce this issue on my virtual machine. Sent a notification as instructor, then logged in as student opened that forum and the notification badge disappeared.

**Comment by williamjallen** [comment]
I just confirmed that this no longer occurs on the production site.
