### ISSUE TITLE
Forum page title does not reflect current selected thread title

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#8034]
**Describe the bug**
The page title does not change when switching between forum threads.

**Expected behavior**
The page title should reflect the title of the thread which is currently selected.

**To Reproduce**
1. Open the discussion for any course
2. Click on any post and observe that the page title matches the post title
3. Click on a different post and observe that the page title does not change

**Configuration**
N/A

**Screenshots**
<img width="1202" alt="first" src="https://user-images.githubusercontent.com/16820599/173361356-5a56696c-aeea-4741-af1f-4c496889c03d.png">
<img width="1201" alt="second" src="https://user-images.githubusercontent.com/16820599/173361368-9c53ae58-fb55-422f-9eab-2c6b61b09092.png">

**Comment by chandankumar1307** [comment]
Hello @williamjallen 
I would love to fix this issue. I think I understand what the issue is here. Would love to talk more about if you could assign me this issue.
I would love to be a part of Submitty's community.
Thank you

**Comment by kevin-pease** [comment]
@chandankumar1307 Are you working on this issue? If not, I'd like to pick up this issue! :)

**Comment by williamjallen** [comment]
Closed by #8062
