### ISSUE TITLE
Dynamic Rainbow Grades

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#804]
When output.html is generated...  make options to sort the list by column (instead of having to e.g., "make section" which re-runs the program and produces a new output.html

**Comment by MasterOdin** [comment]
I think the implementation of this would allow for you to click on the header of the "Last Name" or "Section" and it would sort on that (where clicking on Section would sort by section, but sort by alpha last name always).

**Comment by bmcutler** [comment]
Not a current direction.
