### ISSUE TITLE
System Message clobbered by running CONFIGURE_SUBMITTY.sh

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8151]
**Describe the bug**

If the "system_message" variable is stored in the /usr/local/submitty/config/submitty.json file, that value is lost when CONFIGURE_SUBMITTY.sh is run.

See also:
https://submitty.org/sysadmin/installation/system_customization#show-system-message-to-all-users

**Comment by SaNsK11** [comment]
Hey! Can I work on this issue?

**Comment by dev-DTECH** [comment]
Hey @bmcutler, I would like to work on this issue.

**Comment by snehalchaudhari98** [comment]
Hi, I would like to work on this issue.
