### ISSUE TITLE
record if student viewed grade for a specific gradeable

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#816]
Add column to electronic_gradeable_version table "viewed" records whether a student has looked at a grade.
@MasterOdin will do this ASAP

After its in the database...

**Comment by JerameyATyler** [comment]
I think this should go on electronic_gradeable_data instead of electronic_gradeable_version. Version relates exclusively to the active version while data relates to the individual version. If we are going through with rolling back versions this will be a little more versatile.

**Comment by MasterOdin** [comment]
We actually should stick this in gradeable_data next to where we store the
graded version and would contain all other information about stuff for the
student to view on TA grading.

**Comment by JerameyATyler** [comment]
I'll agree with that. I'll submit the change.

**Comment by bmcutler** [comment]
Finished!  Thanks @InfinityMin3r
