### ISSUE TITLE
dotfiles missing from TA Grading - "Download Zip File" for a specific student

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8180]
**Describe the bug**
TA Grading interface, for a specific gradeable, for a specific student, in the "Submission and Results Browser" when you click "Download Zip File", it zips up the submissions, results, and checkout folder for the specific version.

However, the zip is missing the "dotfiles", specifically it should include the .submission.timestamp and .submit.VCS_CHECKOUT (for GIT submissions).  And if the student submits a dotfile, or the results or checkout folders contain any dotfiles or folders starting with a dot, they should be included.

**Comment by MBon1** [comment]
Confirmed with @bmcutler not an issue
