### ISSUE TITLE
Add default permissions for course database user

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#8209]
**What problem are you trying to solve with Submitty**
After PR https://github.com/Submitty/Submitty/pull/8031, a course database user was added and all permissions were set for current tables. Any new table will still need permissions set.

**Describe the way you'd like to solve this problem**
We should make a migration to set the default permissions on the schema so that the course database user will have the correct permission for any new table. Make sure to do this for tables AND sequences.

**Describe any potential alternatives you'd tried to solve the problem**
The alternative is that we are stuck setting permissions on every migration that adds a new table/sequence. PR https://github.com/Submitty/Submitty/pull/8002 had to do this but it shouldn't be necessary.

**Comment by 852hamza** [comment]
@bmcutler  @akshatbatra  heloo can you tell me how to add any column in submitty database and how to migrate because i follow the developer link but migrator not worked can you tell me the process

**Comment by akshatbatra** [comment]
> @bmcutler @akshatbatra heloo can you tell me how to add any column in submitty database and how to migrate because i follow the developer link but migrator not worked can you tell me the process

Hi @852hamza 
The process of dealing with migrations is explained here: [https://submitty.org/developer/development_instructions/migrations](https://submitty.org/developer/development_instructions/migrations).

To get an understanding of how to write database migrations, you can have a look at [course migrations](https://github.com/Submitty/Submitty/tree/main/migration/migrator/migrations/course) and [master migrations](https://github.com/Submitty/Submitty/tree/main/migration/migrator/migrations/master).

If you still face an issue, then you can share the exact error that you are encountering on [Slack server for Submitty developers](https://join.slack.com/t/submitty/shared_invite/enQtMzE1NzgyMzUzNzI5LWZhOGM4NWU4M2U3ZmM2ZmM5NTYwNjk3NTc5Yjg1ZGRlYzU1MjcwYWNkNGYxZjk2YTk3ZmEyODY3MjEyOTc0M2E). Kindly make sure to follow the community discussion guidelines available at [https://submitty.org/index/contact](https://submitty.org/index/contact).

**Comment by 852hamza** [comment]
Ok i solved it sir thankx
