### ISSUE TITLE
Confetti bunches up when user changes tabs

### ISSUE THREAD

**Issue by HenryCullom** [Submitty/Submitty#8213]
**Describe the bug**
The confetti that appears when the user gets full points and clicks on the "Autograding Total" section will bunch up and drop all at once if the user changes tabs.

**Expected behavior**
The confetti should come down at the same rate with the same spacing even if the tab is changed

**To Reproduce**
1. Get full Autograder points on an assignment (hard)
2. Click "Autograding Total" to make the confetti appear as it normally would
3. Change to another tab
4. Wait (the longer you wait, the more the confetti bunches up)
5. Change back to Submitty tab
6. See error

**Configuration**
 - OS: Windows 10
 - Browser Chrome
And
 - OS: Ubuntu 20.04 virtual machine
 - Browser: Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/54919530/180903130-6371305a-5ac1-4268-93bb-bd50823aa384.png)

**Additional context**
none

**Comment by shailpatels** [comment]
This is most likely a bug caused by browsers stopping execution of the JS script when changing tabs. Although one could argue its a feature to encourage users to enjoy the confetti without distractions
