### ISSUE TITLE
Manage sessions page for all users

### ISSUE THREAD

**Issue by akshatbatra** [Submitty/Submitty#8258]
**What problem are you trying to solve with Submitty**
A user can't retrieve information about their active sessions.

**Describe the way you'd like to solve this problem**
A "Manage Sessions" page will be created listing all the active sessions for a user, if the user wishes to terminate any of the sessions, they will be able to do so by simply clicking a button in front of that session.

**Additional context**
Once this is done, work on #8257 can be started.

**Comment by cjreed121** [comment]
What information would be the ID of the session to the user? Like if a user sees 3 sessions, how would they know which session refers to what? Would you display IP, user agent, or something else?

**Comment by akshatbatra** [comment]
I was thinking about user agent and session creation timestamp.
