### ISSUE TITLE
Course Materials Upload folder/subfolder selector

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8263]
**What problem are you trying to solve with Submitty**
When an instructor uploads a new course material, they have an option of specifying a subfolder.
The webbrowser does autofill previous data you've typed in that input box on the webform -- but it's not necessarily a folder/subfolder that exists in the current course (it could be for another course).

If the instructor makes a small unintentional typo in the name, they might create a new folder e.g., 'Homeworks'  or "homework' instead of 'Homework'.  

**Describe the way you'd like to solve this problem**
It would be nice to change this form to have a selection dropdown with all of the existing folders & subfolders in the current courses course materials uploads.  
And then a 'new folder/subfolder' button if you did want to specify something new.
[ note: this design suggestion is incomplete, please propose an intuitive and efficient UI. ]

Note: Instructors use course materials organization in many different ways.  Let's make sure we support all:
Some instructors put all files in the top level, and don't use any folders.
Some instructors have 1 level of folders.
Some instructors have multiple levels of folders & subfolders.
Some folders contain a mix of files & subfolders.
Some folders only have subfolders.

@holzbh comments?

**Comment by akshatbatra** [comment]
This can be an input text field + dropdown, a user can select the folder name from dropdown, if there are a lot of folders, user will be able to type inside the text field (acting as a search box) to find the folder easily and select it. If a new folder has to be created then user can simply type in that same text field, there will be no suggestions in the dropdown so user will know for sure that a name similar to this doesn't already exist.
