### ISSUE TITLE
Peer grading stats incorrect

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#8275]
**Describe the bug**
When looking at the grading stats of a peer gradeable, many of them are not sensible or just completely wrong.

Here is a screenshot of some averages:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/55092742/183974877-2eb2a84c-a4dd-4af6-a094-aa6879a96156.png">

Also the stats for the manually graded components were much higher than they actually were. Can't attach screenshot of this though.

**Expected behavior**
The stats should be accurate.

**To Reproduce**
Unsure of exact steps to reproduce since this was noticed on production. This assignment only had peer components.

**Configuration**
 - OS: Mac
 - Browser: Brave (Chromium)

**Comment by cmkolb8** [comment]
Hi, I would like to be assigned this! Thanks!
