### ISSUE TITLE
Add SAML user mapping via autofeed

### ISSUE THREAD

**Issue by mcglow2** [Submitty/Submitty#8285]
Update auto feed tool to automatically create a submitty to saml user mapping in saml_mapped_users for any new user created by the autofeed.

EXCEPT if the RCS id you are creating a new user mapping for already exists in the saml_mapped_users.user_id column.

The reason for this exception is that it prevents any namespace collisions between existing submitty proxy users mapped to alternate RCS id.  This collision should be incredible rare but represents a security risk.

**Comment by bmcutler** [comment]
Just one more note:  Not all systems use SAML, and the saml_mapped_users table is unnecessary.  

The authentication setting is in /usr/local/submitty/config/authentication.json  
(I'm not sure if it's also in the database?)

By default it is:
    "authentication_method": "DatabaseAuthentication"

Only do these additions if it is:
    "authentication_method": "SamlAuthentication"
Alternately we could check if saml_mapped_users table is empty.

also tagging @cjreed121 for comments

**Comment by cjreed121** [comment]
Checking "authentication_method" in the authentication.json file is probably the most reliable way of checking if SAML is enabled. The SAML table could also theoretically be non-empty even though SAML is disabled.

There is an existing trigger in place to fire off if a user gets added that could cause a security issue. If an issue is detected on insert, the whole transaction will get aborted. Ideally the auto feed should check before inserting to handle the issue more gracefully.
