### ISSUE TITLE
Older poll UI misalignment with long answer

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#8287]
**Describe the bug**

**Expected behavior**
The gray background of the second poll in the attached screenshot should span the entire height of the row all the way across.  Additionally, the extraneous gray line between the two poll names should be eliminated.

**Screenshots**
![image](https://user-images.githubusercontent.com/16820599/184550271-a6e7281e-bd7c-4b99-b6dd-eb1ec52cf36a.png)

**Comment by PRO-GUNE** [comment]
Can I work on this issue?

**Comment by ThienPham-Si** [comment]
Hi, Is this issue still open? I can work on it

**Comment by kusumita29** [comment]
Hey @williamjallen Is the issue still open? I want to work on it under Hacktoberfest '22.

**Comment by williamjallen** [comment]
Hi @ThienPham-Si and @kusumita29 

We cannot assign an issue to someone outside of the Submitty GitHub project, but if you make a PR we would be happy to review it. Please try and look at the documentation at submitty.org and if you get stuck on something ask on the general chat in slack [here](https://join.slack.com/t/submitty/shared_invite/enQtMzE1NzgyMzUzNzI5LWZhOGM4NWU4M2U3ZmM2ZmM5NTYwNjk3NTc5Yjg1ZGRlYzU1MjcwYWNkNGYxZjk2YTk3ZmEyODY3MjEyOTc0M2E).

Please read the suggestions for new developers here: https://submitty.org/developer/getting_started/index and try and get a developer instance of Submitty running locally.

**Comment by 852hamza** [comment]
@williamjallen 
**Kindly review**

![Screenshot from 2022-12-24 11-45-08](https://user-images.githubusercontent.com/86769921/209424898-94883c68-e734-4e84-8ea3-d05685d86433.png)

**Comment by hansongu123** [comment]
William, I tried and couldn't recreate the issue... can you check if this is already solved and merged? @williamjallen

**Comment by williamjallen** [comment]
@hansongu123 It appears to be fixed now.  I am not certain what the source of the original issue was, but I assume that it was fixed by #6708.
