### ISSUE TITLE
Vagrant box course starts up "mid semester"

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#830]
In addition to a variety of gradeables of all types with deadlines in the past & future...
we would like:
- [x] a large number of students 
- [x] students assigned to multiple rotating & mutliple registration sections 
- [x] some dropped students
- [x] multiple TA users, assigned to zero, one, and multiple sections
- [x] the database should be populated with some checkpoint and numeric grades (and some blank, to allow exploration by newcomers)
- [x] electronic submissions from students, with automated grading, and some with TA grading
- [ ] full variety of late day status demonstrated through those upload (on time, late, too many days used overall, too many days used on one hw, rollback, cancel, graded out of order, etc)
- [x] Build out rainbow grades

**Comment by bmcutler** [comment]
copied from #1075...

Sample should have gradeables in the grading complete category that have:

no autograding (ta grading only)
no tagrading (autograding only)
both tagrading & autograding
autograding with hidden test cases
autograding with extra credit tests
ta grading with extra credit
ta grading with penalty

Tutorial and Dev will only have the four "core" accounts on them (developer, instructor, ta, grader, student) while Sample will have 100+ students.

**Comment by holzbh** [comment]
As a note to myself, it appears right now if a score of 0 is assigned by the setup script, the Grade button is showing instead of [0 / X] despite a submission being created. I'll investigate and either fix it in the pull request that addresses #830, or I'll open a new issue if it's going to be resolved later.
