### ISSUE TITLE
Markdown multiple choice duplicates

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#8345]
**Describe the bug**
If a notebook/markdown gradeable has duplicate values, the gradeable will build fine and produce unexpected behavior to the student submitting. If 2 options had the same value, the website may pick the incorrect value to set when loading the page.

**Expected behavior**
The gradeable should just not build successfully because not all values were unique.

**To Reproduce**
1. Create a notebook/markdown gradeable config with a multiple choice but have duplicate values.
2. Build the gradeable on Submitty
3. Pick the higher order option and submit
4. See that after the refresh, the option changed to the lower one

See comments for a full example

**Comment by cjreed121** [comment]
Here is an example:
```
{
    "required_capabilities": "notebook",

    "hide_submitted_files" : true,
    
    "notebook" : [

        {
            "type": "markdown",
            "markdown_string": "## A question?"
        },
        {
            "type": "multiple_choice",
	    "filename": "output.txt",
            "choices":[
                {"value": "a", "description": "A"},
                {"value": "b", "description": "B"},
                {"value": "b", "description": "C"}
            ]
        }

    ],
    "testcases": []
}
```
Build this locally. Then select B and you'll notice that C is chosen after you submit.

**Comment by williamjallen** [comment]
Would it be reasonable to enforce this by changing each element of the `choices` array to be key-value pairs with unique keys?  For example:
```
"choices": [
    "a": {"description": "A"},
    "b": {"description": "B"}
]
```

**Comment by cjreed121** [comment]
It seems reasonable to me. Don't forget the value on "choices" has to be an object rather than an array to be valid. The only issue I see is that it'll invalidate any current gradeable when rebuilding them. It wouldn't be too hard to change any that need to be fixed.

**Comment by bmcutler** [comment]
@williamjallen 
Good suggestion, but the similar typo by the instructor would just mean the duplicate key was silently ignored & lost when parsing the file -- unless the parser complained.  Similar result.
More importantly, by making this a dictionary instead of an array, the instructor loses control of the ordering of the options.  The values might be something other than chars, and alphabetical may not be the desired order.
