### ISSUE TITLE
"Locked" gradeables are not visible to Teaching Staff

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8355]
**What problem are you trying to solve with Submitty**
The feature to 'lock' a gradeable until another gradeable is completed satisfactorily can be a burden to teaching staff.   Teaching staff cannot view or submit to the later gradeable -- which can block their ability to help a student who has questions about the later gradeable.

**Describe the way you'd like to solve this problem**
Teaching staff (limited, full access, and instructor) should not be blocked from viewing these gradeables.  I would still like it to be clearly labeled that the gradeable does have the dependency on another gradeable, but maybe after clicking to confirm that they want to proceed, the teaching staff can access the gradeable.

**Comment by cjreed121** [comment]
Should they also be able to submit or just view?

**Comment by bmcutler** [comment]
submitting could be helpful, so yes, both.

**Comment by mahi-pas** [comment]
Could you assign this to me?

**Comment by mahi-pas** [comment]
could you assign this to me @bmcutler

**Comment by ch3nnyj** [comment]
My understand is teaching staff is TA's not including mentors or do mentors counts as well?

**Comment by cjreed121** [comment]
> My understand is teaching staff is TA's not including mentors or do mentors counts as well?

I would think anyone with grading access should be able to access and submit. So limited access graders and up.
