### ISSUE TITLE
Office hour staff text color

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#8356]
**Describe the bug**
When on the staff office hour queue page, the text color for the office hour queue boxes are different depending whether the queue is open or closed. This only happens when in dark mode.

**Expected behavior**
The text color should be the same for both open and closed queues.

**To Reproduce**
1. Create a couple queues if you don't have any
2. Have at least one open and closed queue.
3. You'll see the text color is different between the open/closed queue

**Screenshots**
<img width="710" alt="image" src="https://user-images.githubusercontent.com/55092742/188026472-b8bc4d82-2bcf-40ff-810f-98acf1f59384.png">

**Comment by billyvande** [comment]
I'm interested in contributing to this issue. Can i get assigned to this issues?

**Comment by cjreed121** [comment]
Sure

**Comment by cjreed121** [comment]
Unassigning for now. Anyone is able to work on this. No assign is necessary to make a PR.

**Comment by kevinochoa8266** [comment]
I would like to contribute. This is my first open-source contribution!

**Comment by williamjallen** [comment]
Hi @kevinochoa8266!  Submitty welcomes contributions from anyone.  If you'd like to tackle this issue, go right ahead!  Once you make a pull request, it will undergo a review, and hopefully be merged once any requested changes have been addressed.  If you need help with anything, feel free to ask in our [Slack](https://submitty.org/index/contact).
