### ISSUE TITLE
Remove "floating bar" from the students / graders list

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#836]
(It looks bad, at least on Mac Chrome)

If the appearance is improved (on all browsers), we can discuss whether to add it back in.

**Comment by bmcutler** [comment]
still floating despite installing #840

**Comment by MasterOdin** [comment]
Most browsers cache static resources (such as .js and .css files). You'll have to wait for that cache to expire (which it most surely has by now) or cause a hard refresh of the file (by going to the file itself and hitting refresh).
