### ISSUE TITLE
Support single backticks

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#8371]
**What problem are you trying to solve with Submitty**
For the forum, I want to use single backticks for inline code, such as:
```md
`this`
```.

**Describe the way you'd like to solve this problem**
Add a new section of code in the markdown formatting section dealing with inline code blocks.

**Describe any potential alternatives you'd tried to solve the problem**
Using code blocks

**Additional context**
N/A

**Comment by williamjallen** [comment]
The Submitty Forum does support single backticks.  See the attached acreenshot.  I personally am in favor of changing the interface to be slightly more prominent like GitHub does: `this has single backticks`.  Feel free to edit and reopen this issue or create a new issue with any suggestions for how to make the interface more clear.

![image](https://user-images.githubusercontent.com/16820599/189007659-1016ded1-14b8-4c50-948b-486ac9fff45a.png)

**Comment by PythonCoderAS** [comment]
@williamjallen On submitty.cs.rpi.edu, backticks still render.

**Comment by williamjallen** [comment]
Do you have markdown enabled?  (e.g., is the MD icon blue?)

**Comment by PythonCoderAS** [comment]
Oh sorry, I didn't realize it was disabled by default.
