### ISSUE TITLE
Notebook - instructor cannot submit as another student

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8388]
**Describe the bug**

The instructor view of a notebook gradeable includes the radio button option to submit as student:

<img width="415" alt="Screen Shot 2022-09-12 at 3 54 46 PM" src="https://user-images.githubusercontent.com/5871417/189743854-b7f79d6c-1531-4d0c-9319-d0ae0d43fd00.png">

But this option does not work.  (It was only implemented to work for regular file upload submissions.
It doesn't even have a box to type in a student name!

**Expected behavior**

First, let's remove this option from the webpage for all notebook gradeables, it's not implemented and it's confusing.

Second, let's actually implement this functionality.  It would be useful for an instructor giving an in-class electronic quiz.  Most of the students successfully submit using their laptop, but if one student doesn't have a working laptop, they can submit on paper and the instructor or TA can type up and submit their answers afterwards.

NOTE:  Let's make sure it's not easy to accidentally submit the form as a student.  For both notebook and regular file uploads, let's have a popup "Are you sure you want to submit as student smithj?" after clicking the "Submit" button.  Maybe also there should be big colored box with notices at the top & bottom of the page when the 'submit as student' radio button is selected.

**Comment by kevinochoa8266** [comment]
This is my first open-source contribution. Can I participate?

**Comment by williamjallen** [comment]
Hi @kevinochoa8266!  Submitty welcomes contributions from anyone.  If you'd like to tackle this issue, go right ahead!  Once you make a pull request, it will undergo a review, and hopefully be merged once any requested changes have been addressed.  If you need help with anything, feel free to ask in our [Slack](https://submitty.org/index/contact).

**Comment by ratika-12** [comment]
Can I work on this ? @bmcutler
