### ISSUE TITLE
Note next to 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8403]
**What problem are you trying to solve with Submitty**
Numeric & Checkpoint gradeables are not visible to students from the gradeables page (since they don't submit anything for these gradeables.  The 'release date' for numeric & checkpoint gradeables has confused instructors since the students still can't see anything on the gradeables page -- they only see the score in rainbow grades.

**Describe the way you'd like to solve this problem**
Let's add a message on the Dates tab for Edit Gradeable next to the Grades Released Date for checkpoint & numeric gradeables.

"NOTE: Released Grades for checkpoint and numeric gradeables are available to students only through Rainbow Grades."

**Comment by kevinochoa8266** [comment]
Hi I would like to attempt to contribute to this!
