### ISSUE TITLE
Annotation cache removal

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#8404]
Inside .setup/install_submitty/install_site.sh, the annotation cache clearing needs to be removed. This should happen no earlier than 1-2 releases after #8398 is merged. This was left in so the old unused cache could get removed.

**Comment by OMH-G** [comment]
Do we have to remove the lines from 126-130 ? if I have get it correct then can you give me chance to make some modification .

**Comment by cjreed121** [comment]
That is correct but we should wait until another release before making a PR.
