### ISSUE TITLE
Download all submissions (& checkout & results) for all students & active only option

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8423]
**What problem are you trying to solve with Submitty**
Currently you can download all students submissions folder for all versions.  
For a specific gradeable, on the  ta grading / 'grading stats' page there is a button at the bottom left.
The download zip includes the user_assignment_settings.json file indicates which version is the 'active' version (by default the highest numbered)

But an instructor might want to only download the active version (less to download & does not require consulting the user_assignment_settings.json file.
The download button has a drop down with checkboxes to select 'active only' and to request also downloading the results folder.  

BUG 1: But these options do not appear to work at all.  (OR maybe I'm confused about the UI...  but if so, this interface is not intuitive)

Furthermore, if the assignment is a submit by git, the download of the submissions folder is not the main assignment, we MUST ALSO include the parallel checkout folder, which contains the actual files in the repo at the time of submissions. 

BUG 2:   We are missing the .submit.timestamp file (and maybe other dotfiles) from the submissions folder.

BUG 3: download all for team submissions seems very broken....  Instead of having a layer of directories for each team name, there are just lots of directories that appear to be the submission versions for all students jumbled together.  NOTE:  I tested this with a gradeable that was both git & team, but all combinations should be tested & debugged.

**Comment by LunaFang1016** [comment]
Hi, I would like to work on this issue, thank you!
