### ISSUE TITLE
Updating existing rotating sections, exclude specific registration sections

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8429]
When rotating sections are creating initially and students are assigned to rotating sections, instructor has the option to exclude section (e.g., they can include a 'staff' registration section).

But if students add after that, we only have the option to all all non-NULL registration section students to rotating section.  We cannot exclude the staff section.

**Comment by Pratyakshshiv** [comment]
i would like to work on this issue.

**Comment by deveshkedia** [comment]
Is this issue still open?
