### ISSUE TITLE
add leading zeros on bulk upload page .pngs

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8430]
**What problem are you trying to solve with Submitty**
When we bulk upload a exam with 12 pages, the images of each page are numbered without leading zeros.  And the default sort-by-string is out of order and can be confusing.
<img width="178" alt="Screen Shot 2022-09-23 at 7 15 19 PM" src="https://user-images.githubusercontent.com/5871417/192068348-3c8ea80a-d545-4948-82de-813f8c68b83a.png">

**Describe the way you'd like to solve this problem**
Let's add leading zeros on these filenames to fix this problem.
NOTE: The goal is not just to fix the display in TA grading, but also to fix anywhere we might want to view & access these files (e.g., linux 'ls').

Assuming that the test will be < 100 pages is fine.

**Comment by ibonkonesa** [comment]
I'll do it!
