### ISSUE TITLE
Replace "Graded by: TA_LAST_NAME" with "Graded by: TA_FIRST_NAME TA_LAST_NAME/LAST_INITIAL"

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8431]
**Describe the bug**
When a student checks the TA grade on a homework assignment, just the last name of the person who graded the work is displayed.  This is inconsistent where in other places
<img width="310" alt="Screen Shot 2022-09-23 at 9 39 01 PM" src="https://user-images.githubusercontent.com/5871417/192074700-0477b1bc-d3d5-488c-9b64-14f52ce831c5.png">

This is inconsistent with name usage on other parts of the site.

**Expected behavior**
Instead, let's replace this by "Graded by: Preferredfirstname Preferredlastname" (case sensitive) for full access graders & instructors.
And for limited access graders, do not display any information about the grader.  (Limited access graders remain anonymous for graded homework).

**Comment by williamjallen** [comment]
I believe that Grade Inquiries also share this inconsistency, except that they only use the first name/first preferred name.  For example, here is a snippet of one of my recent grade inquiries:
![image](https://user-images.githubusercontent.com/16820599/192075633-5f1e639e-a2ef-4d75-bd6a-02cc22932522.png)
and the corresponding reply:
![image](https://user-images.githubusercontent.com/16820599/192075642-699b06a8-5e5e-4fb8-bf56-288250cbede1.png)

**Comment by bmcutler** [comment]
I'll make another issue (I'm doing forums too)

**Comment by JulieMaricicDetweiler** [comment]
Hi, I may be interested in working on this issue. This would be a first contribution for me.
