### ISSUE TITLE
Replace "Helped Started By USERNAME" with FIRST_NAME LAST_NAME / LAST_INITIAL

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8432]
**Describe the bug**
Similar to #8431. 

When a student has been helped in the office hour queue, it says you were helped by (& removed by) USERNAME.

<img width="483" alt="Screen Shot 2022-09-23 at 9 42 24 PM" src="https://user-images.githubusercontent.com/5871417/192074803-fba357fb-6536-457d-8cd7-e66661b0f497.png">

**Expected behavior**
Instead, let's help students learn the names of the teaching staff by:
* putting the preferred first name & preferred last name (for full access graders and instructors)
* putting the preferred first name & preferred last initial there (for limited access graders)

**Comment by sayande2002** [comment]
Hey an I help you?

**Comment by Saptadev-Chatterjee** [comment]
i want to try

**Comment by shailpatels** [comment]
Hi @sayande2002 , @Saptadev-Chatterjee 

Please read the suggestions for new developers here: https://submitty.org/developer/getting_started/index and try and get a developer instance of Submitty running locally.

You can find issues labeled "good first issue" here: https://github.com/Submitty/Submitty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

We cannot assign an issue to someone outside of the Submitty GitHub project, but if you make a PR we would be happy to review it. Please try and look at the documentation at submitty.org and if you get stuck on something ask on the general chat in slack [here](https://join.slack.com/t/submitty/shared_invite/enQtMzE1NzgyMzUzNzI5LWZhOGM4NWU4M2U3ZmM2ZmM5NTYwNjk3NTc5Yjg1ZGRlYzU1MjcwYWNkNGYxZjk2YTk3ZmEyODY3MjEyOTc0M2E).
