### ISSUE TITLE
Add last name to instructors & full access in the forum

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8433]
**Describe the bug**
Similar to #8431 & #8432

**Expected behavior**
Let's update the authors of forum post.
If the person in an instructor or a full access TA, lets make the author "Preferredfirstname Preferredlastname"
(unless they have the anonymous flag checked, then of course, leave it anonymous)
 
Leave the limited access graders and all students as "First name last initial"

**Comment by jason0kenyon** [comment]
Hi, I would like to work on this bug. Would you mind assigning it to me? :)

**Comment by shailpatels** [comment]
Hi @jason0kenyon, due to how our github organization is setup we cannot assign external users to an issue. But if no one else is assigned/working on it feel free to work on it! If you make a pull request we would be happy to go through the review process and try and get it merged.

**Comment by aimankhan24** [comment]
I would like to work on this issue please assign me this.
