### ISSUE TITLE
Office hours queue "View Queue Occupancy" button re-instantiated on office hours queue size change without deletion, causing duplicates

### ISSUE THREAD

**Issue by WISH-ETHEREAL** [Submitty/Submitty#8442]
**Describe the bug**
As a student: When office hours queue occupancy changes, the button and table are being created again, causing a duplicate entry showing the new value while the old one is still present. Only one button changes between the two button states when any is clicked, which would show all of the tables at once.

**Expected behavior**
Only one button and one table should ever be on screen at one time.

**To Reproduce**
How it happened to me:
- As a student, sit on the office hours queue page for a while, whether you are being helped or not.
- Have another application/tab in the foreground. (Likely not a hard requirement)
- Check the page at a later time after the queue occupancy has changed.

**Configuration**
Observed on Windows using Vivaldi and LibreWolf browsers.

**Screenshots**
[Taken on an office hours queue for a class I am taking in the time it took for me to find this repo and begin writing the issue.](https://imgur.com/a/GSSJimM)

**Comment by williamjallen** [comment]
This appears to be the same bug https://github.com/Submitty/Submitty/pull/7610 was attempting to fix.  

https://github.com/Submitty/Submitty/pull/8395 was proposed as a temporary mitigation (to simply comment out the relevant code) but this should be fixed long-term.

I believe that @tkoz0 was investigating this issue most recently.

**Comment by bmcutler** [comment]
closed via #7610
