### ISSUE TITLE
Add 'user numeric id' to exported data for rainbow grades

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8552]
**What problem are you trying to solve with Submitty**
We have a column for 'user numeric id' in the database, but it's not exported via generate grade summaries to Rainbow Grades

**Describe the way you'd like to solve this problem**
add that field to the exported data:
raw_data/all_grades/<USERNAME>_summary.json

**Comment by ratika-12** [comment]
@bmcutler Assign me this issue I want to work on this

**Comment by ratika-12** [comment]
@bmcutler Hi I'm new and want to work on this. Please assign me :)

**Comment by Sharath-1517** [comment]
Hello, I am **new** to this workspace and **I am intrested to work** on this. **Please assign me this** .
