### ISSUE TITLE
Get Most Recent Files Button UX

### ISSUE THREAD

**Issue by bennyty** [Submitty/Submitty#860]
Using Submitty for the first time in a long while. Site looks & feels great.

There is a new button labeled "Get Most Recent Files." For me, the result of this button was unclear. I thought it would pull the most recently changed files (assuming they were at the same path) off of my computer and upload them to the server. After clicking and seeing that it populated the window I realized that was impossible as I am on a different machine without the files in question; if I was on the same computer I might have assumed that new files were uploaded rather than reusing the server side files (is that what the button does?) Regardless, I would advocate for a different label: "Resubmit last submission" for example.

Thanks

**Comment by MasterOdin** [comment]
"Get Last Submission Files" maybe?

**Comment by bmcutler** [comment]
How about "Append Most Recent Files"?

**Comment by bennyty** [comment]
The problem is it's unclear what a "recent file" is; whether it is your last uploaded file (local file) or your most recent submission file (server currently held).

I actually still don't know for sure what the button does; does it just add the server-side files from your last submission? Why would someone want to do that?
