### ISSUE TITLE
Student access to API

### ISSUE THREAD

**Issue by ryanting01** [Submitty/Submitty#8631]
I am trying to create a Visual Studio Code extension for students. Features would be to view their gradeables, submit from VS code to Submitty, see their results, etc.
I am having a problem as the API is not available for student as I when making a call it says i is only available for staff. I am just wondering if it is possible to implement these things through the API, and why is the API currently not available for students even though it says it is available in the documentation.

Hopefully this can be done and thank you for the help!

**Comment by IDzyre** [comment]
Student API access has been added in #10330
