### ISSUE TITLE
release date for discussion forum category

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8643]
**What problem are you trying to solve with Submitty**
An instructor would like to have discussion forum categories "hw1", "hw2", "hw3", etc.
But they don't want to have all of the categories visible at the start of class (to avoid overwhelming with currently unneccessary categories)
An instructor can make each category as they release each homework, but if they forget, students can't pick the correct label for their questions for the new homework.

**Describe the way you'd like to solve this problem**
Let's add a release date / visible date for each forum category.  Before that date only instructors can see the category.
After that date everyone can see and use the category.

**Comment by 852hamza** [comment]
@bmcutler  can you assign me I have **solve this issue**  
I complete it
i am attaching picture for what i am done
 
![Screenshot from 2022-12-23 16-59-02](https://user-images.githubusercontent.com/86769921/209332719-732dc00e-928f-47b0-8a06-73460dfcae63.png)

**Comment by ishhanayy** [comment]
I want to work on this issue, please assign me this issue .

**Comment by shailpatels** [comment]
Hi @ishhanayy , due to how our github organization is setup we cannot assign external users to an issue. But if no one else is assigned/working on it feel free to take it on - If you make a pull request we would be happy to go through the review process and try and get it merged.
