### ISSUE TITLE
Download submitted files & access prior versions options broken

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8659]
**Describe the bug**
These settings:
<img width="315" alt="Screen Shot 2022-12-12 at 4 28 07 PM" src="https://user-images.githubusercontent.com/5871417/207158291-c7173351-f6e9-44fa-a34b-9c97f3a1f868.png">
don't appear to be working.

**Expected behavior**
The "View and download  submitted files" should hide:
<img width="383" alt="Screen Shot 2022-12-12 at 4 28 47 PM" src="https://user-images.githubusercontent.com/5871417/207158513-6f50cc87-d2a7-4c0b-83b5-088da2902aac.png">

And the "access prior versions" should hide
<img width="392" alt="Screen Shot 2022-12-12 at 4 29 00 PM" src="https://user-images.githubusercontent.com/5871417/207158653-c642f103-4aa7-4b27-89f0-8cc7e672f470.png">

I'm not sure if these options are doing anything right now.  BTW, I tested this using a notebook gradeable.  These settings are also useful for bulk upload, so maybe they currently only work for bulk upload -- which is an error.

**Comment by ashwin-acharya01** [comment]
Could you please elaborate on what is expected? I would like to solve this problem.

**Comment by PythonCoderAS** [comment]
Why would "access prior versions" be hidden if it's enabled?

Are you trying to make it where they cannot access prior versions? In that case you need to file a feature request probably.

**Comment by Prajjawal12** [comment]
please assign me this task, i want  to resolve this issue.

**Comment by jason490** [comment]
I'm unable to reproduce this issue in both a notebook gradeable and regular gradeable.
It might've been fixed with someones PR.
