### ISSUE TITLE
Improvements for textbox/short answer submissions

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#869]
- [ ] Should probably rename this from intructor config textbox to short_answer (or something else?) so it naturally includes true/false, multiple choice.

- [ ] Improve the display of answers from previous submission to students.  Current method is clunky for the instructor, have to duplicate names from boxes to test cases.  If we implemented an instructor setting that allowed students to see the contents of all submitted files (including textbox generated files) this would be easier.

- [x] Allow radio button answers, making True/False, multiple choice questions easy.  (Still just store the answer in the file).  

- [x] Allow multiple checkbox answers (e.g., choose all of the items that are true)

- [x] Demo of autograding possibilities for these...  true/false, multiple choice are easy.

- [ ] Autograde of simple short answer that look for one of a set of words or phrases.  (e.g., instructor specifies that an answer including "ERROR" or "error" or "Error" or "syntax problem" are all worth full credit)

- [ ] ...  more to come?

**Comment by bmcutler** [comment]
Evan, please open new issues for whatever is not handled by paragraph textboxes PR.... (or other open issues)

**Comment by bmcutler** [comment]
(and then close this)

**Comment by emaicus** [comment]
Created new issues for this.
