### ISSUE TITLE
Warning about depreciated feature used in submitty install script

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#8728]
**Describe the bug**
The following message is displayed when running the submitty update command.

Command:
```sh
sudo /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh
```

Message:
```text
Copy the submission website
Set permissions
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
```

**Expected behavior**
No warning messages.

**To Reproduce**
1. Install submitty.
2. Wait until an update is needed. (may be not be required)
3. Run update script.
4. Review log message from update script in terminal output.

**Configuration**
 - OS: Ubuntu 20.04

**Screenshots**
![Screenshot from 2023-01-08 10-52-15](https://user-images.githubusercontent.com/3517157/211213601-f6366966-f5b6-44b4-9894-a40b482aecda.png)

**Additional context**
We are running an updating our submitty server that is using software from September 2023. The updated version is © 2023 [Submitty](https://submitty.org/) [v19.11.00](https://github.com/Submitty/Submitty/releases/tag/v19.11.00)

**Comment by Kaushik-Iyer** [comment]
Should I try to work on this? I don't know which file to change though
