### ISSUE TITLE
Allow Users To Remove Old Courses

### ISSUE THREAD

**Issue by N-Desmarais** [Submitty/Submitty#8747]
**What problem are you trying to solve with Submitty**
Currently classes don't get removed from a user's home section until all students in that course have cleared their incompletes. This can cause the homepage to be filled with several non relevant classes, with no way for a user to hide or remove them.

**Describe the way you'd like to solve this problem**
Provide either a method for hiding non relevant classes, or removing classes that are from previous terms.

**Comment by bmcutler** [comment]
Thanks for the suggestion, but this isn't actually a bug or performance problem.  The department/university/instructor chooses when to "archive" a course and remove access to that course for all students and teaching assistants.  This may be done within days of the course finishing, or it may be done weeks or months later.  

Adding an option to cosmetically hide access to the course would only lead to the potential for accidental hiding -- and we'd need to add a feature to let students unhide the course.
