### ISSUE TITLE
Another RPI building and room need to be added to Rainbow Grades templates

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#8754]
**What problem are you trying to solve with Submitty**
I am trying to have Rainbow Grades schedule an exam in RPI's Academy Hall Auditorium (coded as "ACADMY AUD" by the Registrar's) but it doesn't look like Rainbow Grades are aware of such a building.

**Describe the way you'd like to solve this problem**
Currently, it appears that Rainbow Grades (RainbowGrades\Submitty\site\room_templates\) contain templates (*.twig files) for just the following buildings:
Amos Eaton
Darrin
Low
Ricketts
Sage
West Hall

I would like to add Academy Hall to this list with at least Academy Hall Auditorium as a specific room that I have to use.

**Describe any potential alternatives you'd tried to solve the problem**
I don't see any other alternatives other than not using assigned seating through Rainbow Grades at all.

**Additional context**
N/A

**Comment by bmcutler** [comment]
I do have a chart for Academy Hall -- but it looks like it's not committed yet.
I'll message you relevant file on Slack.
