### ISSUE TITLE
Support tar submissions

### ISSUE THREAD

**Issue by tcyrus** [Submitty/Submitty#876]
`PharData` supports both `.zip` and `.tar` files while `ZipArchive` only supports `.zip` files

**Comment by tcyrus** [comment]
`PharData` is throwing an exception because the tar temporary file doesn't have the file extension

**Comment by tcyrus** [comment]
Added support for `tar` files in tcyrus/Submitty@e03da6c4b967b35084223486a21b542ed4f3a23e. This still needs to be tested

**Comment by tcyrus** [comment]
Added support for `tar.gz` and `tar.bz2` in tcyrus/Submitty@3fdb23d02bdd73285248a5dea6466478cf6d9235. This still needs to be tested against Tarbombs and other similar cases.

**Comment by MasterOdin** [comment]
Is there a reason you're not using Phardata for both Tar and Zip (removing ZipArchive dependency completely).

**Comment by tcyrus** [comment]
Code encounters fatal memory error when dealing with large tar files.
The simplest solution I can think of is using exec to check file size and proceed if the file isn't too large
```
zcat file.tar.gz | wc -c
bzcat file.tar.bz2 | wc -c
```

**Comment by MasterOdin** [comment]
`exec` php command is not allowed on the server as are a [bunch of functions](https://github.com/Submitty/Submitty/wiki/System-Customization-Checklist#disable-php-functions)

**Comment by tcyrus** [comment]
We have decided not to implement tar submissions
