### ISSUE TITLE
Form requires editing to resubmit with same url

### ISSUE THREAD

**Issue by PythonCoderAS** [Submitty/Submitty#8801]
**Describe the bug**
For https://submitty.cs.rpi.edu/courses/s23/csci2961/gradeable/git, we have to put in a Git repo clone URL and submit it to the automated testing. However, if I want to resubmit, I need to add a character to the URL and delete it since the Submit button is gray otherwise.

**Expected behavior**
The Submit button should always be green.

**To Reproduce**
1. Enter URL
2. Submit
3. Try to resubmit the same URL

**Configuration**
 - OS: [e.g. Windows, Linux, ...] MacOS
 - Browser [e.g. chrome, safari] Chrome

**Screenshots**

**Additional context**

**Comment by bmcutler** [comment]
NOTE:  The linked assignment URL is not publicly accessible.  
This is an issue with the design of the gradeable configuration for a course.  
Not with the open source Submitty project.

Our notebook gradeable interface is design to prevent duplicate submissions.  This prevents students from accidentally re-submitting their assignment with no changes, using up their limited number of "free submissions" (20 by default), and prevents overloading the autograding servers.   We cannot automatically detect that a particular assignment should allow duplicate submissions.

Perhaps the feature you desire is an override to the instructor when they create a gradeable that welcomes duplicate submissions.  But this should not be the default behavior of the notebook/form gradeable.

**Comment by PythonCoderAS** [comment]
An override would be a good idea. A hypothetical gradable could also be making an assignment where a specific URL must be accessible and contain some data, and it would have a similar issue.

**Comment by bmcutler** [comment]
On further thought, this is a very narrow, special case situation.  It is a minor inconvenience to the student, and low priority feature for Submitty to implement.  It would be so rarely used feature and it is not worth the burden to test and maintain.  So I'm closing this issue.
