### ISSUE TITLE
ta grading assignment with discussion forum thread id - auto-open image attachments

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8818]
**What problem are you trying to solve with Submitty**
When grading an assignment that has a discussion forum thread, we can use the "Discussion" panel to display all posts within the specified thread(s).  If the student has included an image attachment, it requires the grader to click to load and open and display that image.

**Describe the way you'd like to solve this problem**
Let's auto open all image attachments if the discussion panel is displayed.

<img width="500" alt="Screen Shot 2023-02-02 at 8 35 10 PM" src="https://user-images.githubusercontent.com/5871417/216490711-a288b175-942f-4662-a585-37b5036f7e6a.png">

**Comment by sonustar** [comment]
One possible solution is to modify the existing code for the "Discussion" panel to automatically load and display image attachments when the panel is displayed. It could be done by adding some JavaScript or JQuery code to the page that detects when the "Discussion" panel is opened, and then automatically triggers the loading and display any image attachments within that panel.

Do you allow me to contribute for this problem .

**Comment by sonustar** [comment]
Is there any way that I can talk to the mentor ? if any then please let me. I need to ask a few things

**Comment by saumyaborwankar** [comment]
Hey, @bmcutler I wasn't able to find any linked discussion forum on the assignment grading page. Am I missing something?
Is there a certain homework I'm supposed to be looking at?
I'm logged in as "ta2"

![image](https://user-images.githubusercontent.com/46644513/218383642-ae3565f2-0621-4bc7-9f49-c2acb6b9967b.png)

**Comment by Ahmed89shaaban** [comment]
Want to share all information about mechanical engineering to collect data and books and courses and how to be excellent
