### ISSUE TITLE
default radio button to 'submit by bulk pdf upload'

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8821]
**What problem are you trying to solve with Submitty**
If a gradeable is a submit by bulk upload gradeable

<img width="440" alt="Screen Shot 2023-02-02 at 10 25 55 PM" src="https://user-images.githubusercontent.com/5871417/216505427-78269e42-bfc2-49a5-b433-9b62dcc01062.png">

currently the submission page for the instructor/graders defaults to Normal Submission, which often leads to user errors when we 
grader mistakenly uploads the exams as a submission for themselves.

Instead, let's default the radio button in this case to "Bulk PDF Upload"
(don't remove the other options, since sometimes we do use the other options to upload special cases)

<img width="411" alt="Screen Shot 2023-02-02 at 10 26 27 PM" src="https://user-images.githubusercontent.com/5871417/216505548-9a527de7-f20e-47c2-ba56-000aa6bc5fe4.png">

**Comment by PiyushBhatnagar09** [comment]
i  like to work on this issue

**Comment by PiyushBhatnagar09** [comment]
And from where i can access the code for this issue ?? I am a beginner in open source contribution. Plz help...

**Comment by harmanbatheja15** [comment]
Solved the issue and opened the pull request. Please review it.

**Comment by ArSenic04** [comment]
Please assign me this issue

**Comment by Pursottam6003** [comment]
I would like to work on this issue please assign me the task if possible
