### ISSUE TITLE
Replace usage of withConsecutive in phpunit tests

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#8833]
In the [9.6.0](https://github.com/sebastianbergmann/phpunit/blob/9c1d35553417e1ea333ce278885d3f853bc4efdb/ChangeLog-9.6.md?plain=1#L24) release of phpunit, it had:

> https://github.com/sebastianbergmann/phpunit/issues/5063: Deprecate withConsecutive()

Where this function will be removed in phpunit 10. We use this in a number of places in Submitty, so we'll want to replace it in whatever is the recommended way for phpunit 9.6+.

**Comment by rt-001** [comment]
I will like to work on this .

**Comment by neeraj-2** [comment]
I would like to work on this one. Can I?

**Comment by MasterOdin** [comment]
Hi @neeraj-2, due to how our GitHub organization is set up we cannot assign external users to an issue. However, if no one else is assigned/working on the issue, feel free to just post that you're working on it, and then open a pull request! Once you make a pull request, we'll be happy to go through the review process and try to get it merged.

We recommend reading the suggestions for new developers [here](https://submitty.org/developer/getting_started/index) as well as our [How to Contribute](https://submitty.org/developer/getting_started/how_to_contribute) guide to help you get started, and if you get stuck on something, feel free to ask on the general chat on [Slack](https://join.slack.com/t/submitty/shared_invite/enQtMzE1NzgyMzUzNzI5LWZhOGM4NWU4M2U3ZmM2ZmM5NTYwNjk3NTc5Yjg1ZGRlYzU1MjcwYWNkNGYxZjk2YTk3ZmEyODY3MjEyOTc0M2E).

**Comment by saumyaborwankar** [comment]
hi @MasterOdin I have made changes locally. How can i run test cases to make sure that the new phpunit code runs perfectly. I have made changes in the the files
- site\tests\app\controllers\admin\ConfigurationControllerTester.php
- site\tests\app\controllers\course\CourseMaterialsControllerTester.php

I've made a draft PR, if someone can have a look and let me know how, that's be great. Cheers

**Comment by MasterOdin** [comment]
To run things locally, you can use `composer run test` from within the `site` directory. You can pass `-- --filter <name>` to the script to run specific tests. See the `-- --help` doc from phpunit to see more information.

Otherwise, when you make a draft PR against Submitty, it'll run our test suite against it.

**Comment by saumyaborwankar** [comment]
Hey @MasterOdin when i run `composer run test' in the `\site` folder i get 20 errors. Is there something im doing wrong?
![image](https://user-images.githubusercontent.com/46644513/217972702-e321ce36-ed83-4791-b15d-eb549e909912.png)

**Comment by lucasctd** [comment]
Hello folks, hope you are all doing well.

May you help on what I am supposed to use in version 10 to replace the withConsecutive method?
I need a feature like that in my tests but I don't know what I am supposed to do XD

Thx in advance.

**Comment by Pursottam6003** [comment]
I would like to work on this issue if possible please assign me
