### ISSUE TITLE
Move away from cron jobs to proper grading scheduler

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#885]
Right now, we basically have 20 different cron jobs that spawn an instance of `grade_students.sh` passing in a different untrusted user. Within that shell script, we have then:
1. Make sure that the untrusted user isn't already being used by a different instance of `grade_students.sh`
2. Make sure the grading directory is locked as we get a queue file and then unlock the directory (using `flock`).
3. If there is nothing to grade, have the script sleep and then try again after some number of seconds  
4. Actually kick off grading the student and saving the various details of that properly

We should break this apart and just have one central script (python with asyncio?) that manages all of this for us which would allow us to say "we have 20 untrusted users" or "we have 40 untrusted users" and the script would scale up or down accordingly instead of just adding more and more cron jobs to achieve "scale".

The script would monitor the queue directory for incoming files adding them to an internal queue of what's available to grade (and the order to grade them in) and when an untrusted user was available, it would pull a file off this queue and grade it.

**Comment by bmcutler** [comment]
I agree in principle, but this is quite complicated.

The main motivation for a rewrite is to more fairly schedule the grading of assignments that require multiple threads/processes, more RAM, etc.

**Comment by bmcutler** [comment]
Closed in #1197
