### ISSUE TITLE
Attach comments to submissions

### ISSUE THREAD

**Issue by bennyty** [Submitty/Submitty#887]
Ferrying along a request for old functionality.

Old HW Server allowed students to attach a comment to their submission; this is unavailable on new Submitty.

**Comment by MasterOdin** [comment]
For implementation detail, we could accomplish this by adding a new column to `electronic_gradeable_data` called `submission_comment` and then add a textbox on the submission page that pulls in that column on a per version basis. This textbox would also have a button to submit. We would then need to add an area on the grading page to show this information to the grader.

**Comment by bmcutler** [comment]
@bennyty Can you please clarify what you think used to be available?  In Data Structures we asked students to write any notes they had for the grader in the README.txt file.  That method of collecting comments through file upload is still available, following a format defined by the instructor.

I recently checked in a feature only being used by 1 course so far allowing short answers to be typed directly in a form (saved as separate files).  This can be combined with file upload.   No course has used it yet though...  This is functionality that would need to be configured by the instructor.

**Comment by bmcutler** [comment]
@MasterOdin It's already implemented.

**Comment by bennyty** [comment]
Thanks! It sounds like this functionality is here and is probably just not enabled by the professor. I'm going to close this issue. @twise2 can reopen if he meant something different
