### ISSUE TITLE
Textbox shows with no reply all option in Discussion forum

### ISSUE THREAD

**Issue by jason490** [Submitty/Submitty#8873]
**Describe the bug**
When trying to submit a comment in the thread and the screen is big, the reply to all button shows. But when I zoom in, the submit button doesn't show even if you scroll down.

**Expected behavior**
The reply to all button should show no matter what screen size or zoom level.

**To Reproduce**
1. Zoom in and try to scroll down to the reply to all button

**Configuration**
 - OS: Windows
 - Browser: Microsoft Edge

**Screenshots**
<img width="531" alt="image" src="https://user-images.githubusercontent.com/116290832/218173058-08819c6a-84be-4267-8631-9edc0d306f1d.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/116290832/218173673-afeafe64-3822-4987-af1d-fb8da70fc8eb.png">

**Additional context**
In both of the images, the forum post has been scrolled all the way down

**Comment by williamjallen** [comment]
The buttons are stacked in the screenshot you attached.  It would be better UI design to position them next to each other horizontally whenever this gets fixed.

**Comment by harmanbatheja15** [comment]
I want to work on this issue. Please assign it to me.

**Comment by cherish2003** [comment]
@jason490  i want to work on this issue can you please assign me ?

**Comment by jason490** [comment]
![image](https://user-images.githubusercontent.com/116290832/218528843-dfe61d43-864f-4b12-af08-5ff258a3626f.png)
For some reason this happens to my profile in Microsoft, even though I don't have any extensions that are changing anything.

I tried doing it inPrivate mode in Microsoft edge and other profiles in edge. I also tested on chrome and safari. In those tests, I also couldn't replicate the issue of my current profile in Microsoft edge.
But when you zoom in all the way, you can see the submit reply to all button starts getting cut off.

**Comment by jason490** [comment]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/116290832/218552457-578693de-7a14-45a8-9cc0-848bfd71aff4.png">

**Comment by SatendraDiwakar** [comment]
Hi there,

I was able to reproduce the issue, and it seems, kind a similar to issue - **6014**, its just related to the thread view box, and I have already provided the fix in this [PR](https://github.com/Submitty/Submitty/pull/8861), I hope when PR gets merged then this issue will be fixed as well.

- #6014 

- **Issue**:
![image](https://user-images.githubusercontent.com/85498397/219954536-43e1891c-bcb8-4424-b097-76195c0d83c0.png)

- **Fix**:

![image](https://user-images.githubusercontent.com/85498397/219955523-d39f2e06-e49f-4516-a016-579be1fbcdda.png)

- **I think the divider between filters and Threads overlaps with the filter option and needs to be fixed.**

![overlapIssue](https://user-images.githubusercontent.com/85498397/219956339-542eab87-d2c6-4d40-a1a2-13b01dcdadb0.png)
