### ISSUE TITLE
Write Cypress test cases for Numeric/Text gradeable

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8895]
See comment on PR #8867 

"Given that this is a relatively low-traffic page which seems to get broken on a regular basis, it might be good to write some basic Cypress tests for this page. In particular, this action of navigating both the UI and the text within each of the cells seems prone to breaking in the future. It should be relatively straightforward to write a basic test for this."

**Comment by amitkshatriya01** [comment]
I'd like to take up this issue, if no one is already working on it.

**Comment by AryanSharma9917** [comment]
Heyy, @bmcutler I would like to work on this issue. 
I can try some of the following scenarios:- 
Whether the low-traffic page loads successfully
Whether the form submission works correctly
Whether the navigation menu displays correctly on a larger screen.

**Comment by williamjallen** [comment]
#8958 added test cases for the checkpoint grading page, not the numeric gradeable page.  The checkpoint grading page also needed tests, but #8958 doesn't explicitly solve this issue per se.
