### ISSUE TITLE
More options for TA Grading regrade drop down menu

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8899]
**What problem are you trying to solve with Submitty**

From the TA grading page, the grader can queue the students submission for regrade.
They do this from the "Autograding" panel.
Currently, they have 2 choices, the currently marked active version and all versions.

<img width="280" alt="Screen Shot 2023-02-13 at 7 48 52 PM" src="https://user-images.githubusercontent.com/5871417/218609547-79887db3-e34b-49e4-983e-4b7e7ecd7290.png">

NOTE:  The TA can view & modify which version is "active".
They do this from the "Student Information Panel":

<img width="296" alt="Screen Shot 2023-02-13 at 7 49 07 PM" src="https://user-images.githubusercontent.com/5871417/218609563-8a9a3b4c-241c-4e46-95f6-938cd84194be.png">

Sometimes it is useful to regrade one of the non-active versions (if there was an autograding misconfiguration), but important to not regrade all versions (if there are alot of versions and/or the autograding for the gradeable is computationally intensive).

**Describe the way you'd like to solve this problem**
Let's modify the regrade dropdown (first image above) to list all versions of the students submission
with the active one clearly labeled (similar to the dropdown in the student information panel.

NOTE: selecting to regrade all versions should still be available as a simple one click option.

**Describe any potential alternatives you'd tried to solve the problem**
NOTE: currently the TA can switch the version then regrade active, then switch it back.
But this is error prone, potentially confusing if the student happens to visits the page in the middle of this process.
Also, there is a permanent record of the version change in the version change history log.

**Comment by sahoo-subha** [comment]
is this issue resolved ?

**Comment by 51stDimension** [comment]
Hi, I would like to take up this issue. Is it possible? Would help me in building up my proposal for Gsoc 2023.

**Comment by snehalchaudhari98** [comment]
Hi, is this issue is still open. I would like to work in it.

**Comment by SAJ33L** [comment]
Hi, can you guide me along the issue I want to contribute in this project.
