### ISSUE TITLE
Exception thrown when managing rotating sections by removing unregistered students when all students are removed from rotating sections

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#8900]
**Describe the bug**
There appears to be an exception thrown if the user selects " Remove all students from rotating sections " followed by a "Remove unregistered students (registration section=NULL) from rotating sections and put newly registered students into rotating section with fewest members "

![image](https://user-images.githubusercontent.com/12129065/218625743-590c0ead-8c26-465e-bded-3a2b6e91fc60.png)

**Expected behavior**
No exception should be thrown, if the user is trying to do something invalid or wrong an error message should be shown instead

**To Reproduce**
1.  Go to the manage sections page in a course
2. Scroll down to the Manage Rotating Sections part of the page
3. Select the radio button " Remove all students from rotating sections " and hit submit 
4. Then select the radio button "Remove unregistered students (registration section=NULL) from rotating sections and put newly registered students into rotating section with fewest members " and hit submit

**Additional context**
The operation does appear to do something, the sections are distributed back after the first removal so not sure if this is completely failing or what the expected behavior is 

This appears to only happen when there's more than 2 rotating sections

**Comment by jason490** [comment]
To be more specific, the issue is when there is no one in the rotating sections the curr_section_sizes would contain NULL elements, which would break the array_map, since its subtracting using a NULL element
