### ISSUE TITLE
Exception thrown when seeking a team

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#8911]
**Describe the bug**
As described in https://github.com/Submitty/Submitty/pull/8857#issuecomment-1430153644, clicking the "Seek Team/Partner" button results in an error.  The direct cause of the error is this function, which does not handle cases where no rows are returned gracefully.  https://github.com/Submitty/Submitty/blob/4d6120e98b3ef3be3a4f48573a55c72081bc5781/site/app/libraries/database/DatabaseQueries.php#L3446-L3456

**Expected behavior**
No error should appear.

**To Reproduce**
1. Go to a gradeable with teams enabled (for example: http://localhost:1511/courses/s23/sample/gradeable/open_team_homework/team)
2. Click "Seek Team/Partner" button
3. See error

**Comment by cherish2003** [comment]
@williamjallen can you assign me this issue i would love to work on it
