### ISSUE TITLE
null value for "User Numeric ID" causes Rainbow Grades to crash

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8919]
**Describe the bug**
Reported by instructor:

My "User Numeric ID" was set to null instead of an empty string ""
This caused a failure in the parser in `./process_grades.out`
Manually setting my ID to an empty string in Submitty fixed the issue
Specifically, what I was seeing when running `make` is below:
```
./process_grades.out by_overall
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is null
make: *** [../RainbowGrades/MakefileHelper:108: overall] Aborted (core dumped)
```

**Comment by tanwar-abhi** [comment]
Was this issue observed for existing user or for a new user?
Can you please describe a little about how to recreate this issue?

**Comment by Junaidm678** [comment]
i want to work on this please asign me

**Comment by anupkewat** [comment]
I could help with this issue. Please assign it to me.
