### ISSUE TITLE
Missing Students in Homework Summary

### ISSUE THREAD

**Issue by Erotemic** [Submitty/Submitty#893]
I've noticed that as I progress through gradables I'm seeing students who aren't showing up in the homework summary page. The problem persists if I click view all sections.

**Comment by MasterOdin** [comment]
What course and what students?

**Comment by bmcutler** [comment]
Please don't post private student details on github.  Use the RPI email list instead.

**Comment by bmcutler** [comment]
fixed in PR #886 and  #883
