### ISSUE TITLE
Toggle background color for late/bad submission when grading

### ISSUE THREAD

**Issue by nazime1** [Submitty/Submitty#8962]
**What problem are you trying to solve with Submitty**
The background color when grading late or bad submissions turns to a bright orange or red and there's no way to turn this off.

**Describe the way you'd like to solve this problem**
I'd like a toggle that removes this background color change, probably located on the user's Profile page as that's where other site options are located. 

**Describe any potential alternatives you'd tried to solve the problem**
I've considered using different themes on Submitty, but I don't think that would solve the problem of the backgrounds genuinely hurting my eyes and being distracting when grading.

**Additional context**
This is what late and bad submissions look like on Submitty:
![late_submission_orange](https://user-images.githubusercontent.com/98502343/221477037-a0ccab3d-ba32-47e2-8272-ea4a7bbf81e6.png)
![bad_submission_red](https://user-images.githubusercontent.com/98502343/221477048-b9328be3-fe36-4d8a-9678-a82e960de23c.png)

**Comment by mistryiam** [comment]
May I work on this issue can you please assign it to me?

**Comment by ch3nnyj** [comment]
During Submitty meeting, I was notified by Barb that this feature is one that we would not like to implement. With the different colors we want to ensure those grading that these gradeable are late/bad. Implementing this change would be "annoying".

**Comment by powe97** [comment]
I'd consider straining your eyes due to an unnecessarily searing red/orange background "annoying" as well.

**Comment by bmcutler** [comment]
To clarify, this background color is an intentional alert and only appears when an assignment will receive an automatic zero because it was submitted in excess of the allowed late days.  The grader should ask the course instructor how to handle these submissions.  Either skip this student and move on to the next.  Or if this student was granted a personal or medical exception to the deadline, that exception needs to be entered.

**Comment by nazime1** [comment]
This issue was opened with the intention of toggling off both the late and bad submission backgrounds. I do understand the alert regarding bad submissions, but late submission (which appears when late days are used to make a submission) also creates a background that is uncomfortable to look at for a long period of time while grading.
