### ISSUE TITLE
Folders don't close properly when clicking Open/Close All folders button

### ISSUE THREAD

**Issue by VortiganOfficial** [Submitty/Submitty#8986]
**Describe the bug**
In course materials, I noticed that the the folders are displayed as open or closed based on a cookie saved when a folder is open or closed. However, while the Open/Close all folders button temporarily opens and closes the folders, the changes are not saved and refreshing the page undos the action.

**Expected behavior**
Folders stay closed/open when the button is clicked and the page is refreshed

**To Reproduce**
1.  Go to course materials
2. Open and close random folders, and folders withing folders
3.  Click the open/close all folders button
4. Refresh the page, and the folders should revert to how you had them before
5. See error

**Configuration**
 - OS: Windows 11
 - Browser: Chrome

**Screenshots**
Initial config:
![image](https://user-images.githubusercontent.com/96987732/221999588-0652decd-9a75-45a1-83e8-42ed668778a1.png)
After open/close all folders button:
![image](https://user-images.githubusercontent.com/96987732/221999620-da1b2343-2bf1-4e8f-9d66-a2ff4de44dbc.png)
After refresh:
![image](https://user-images.githubusercontent.com/96987732/221999690-357109b1-22d4-4fc8-8256-e1e7dafa5c4f.png)

**Additional context**
I would start with checking if the button modifies the cookie, as that is probably the core issue.

**Comment by williamjallen** [comment]
Just putting this here as a reminder:
Whenever a PR is created to fix this, a test case should be added to our Cypress test suite to ensure that this functionality continues to work in the future.

**Comment by Pursottam6003** [comment]
Hii I would like to work on this issue please assign me if possible
