### ISSUE TITLE
"Set Folder Release Date" Buttons for Course Material Folders Overlap Visually 

### ISSUE THREAD

**Issue by hansongu123** [Submitty/Submitty#9045]
**What problem are you trying to solve with Submitty**
In the Course Material page within the instructor's UI, "Set Folder Release Date" buttons for course material folders overlap visually and create a blue lump when there are multiple.
![image](https://user-images.githubusercontent.com/123511202/225755230-7fa69c5a-2b5e-436c-8dbc-ded89bc0bb0b.png)

**Describe the way you'd like to solve this problem**
Find a way to separate out the buttons from each other.

**Describe any potential alternatives you'd tried to solve the problem**
By adding reasonable amount of space in between those folder items (slight) or reducing the size of background for those buttons just in this page.

**Additional context**
If adding more space distort the current structure of showing folders or make too big of a difference visually when there are many items, abort and jump on to other suggestions.

**Comment by SwagatikaBehera** [comment]
Here buttons looks a bit bigger we can reduce the size and adjust border-radius or we can add margin-bottom around the listed items div or using gap property of display:flex to listed div we could fix it. I would love to fix this problem @hansongu123.
