### ISSUE TITLE
Refactor Colors in the Poll Histogram Table for Dark Mode

### ISSUE THREAD

**Issue by hansongu123** [Submitty/Submitty#9051]
**Describe the bug**
Currently the colors in the Poll Histogram table appearing the same in light mode and dark mode. Both the regular response column and the correct answer column are currently assigned with darkish colors - which would look good only in light mode for contrast, but not in dark mode.

**Expected behavior**
Reassign the colors for the Poll Histogram in dark mode to make them appearing more clear in contrast in dark mode. 

**To Reproduce**
1.  Go into the Polls page
2.  Click on "View Poll" on any poll
3.  Open the Response Histogram by clicking on relevant button
4.  See error

**Screenshots**
![image](https://user-images.githubusercontent.com/123511202/226049833-e8e43f06-1747-4a32-a1d5-b490724cd093.png)

**Additional context**
Note: the Poll Histogram object cannot be tested for color contrast in WAVE, so this issue was ignored and long due. In the future, the contrast of the table and its background maybe tested using snapshot tests if planning on implement them.

**Comment by vannekariabhiram** [comment]
trying to work on this issue
