### ISSUE TITLE
Sorting broken on gradeable grading page

### ISSUE THREAD

**Issue by jenaybarela** [Submitty/Submitty#9080]
**Describe the bug**
Sorting is not working on the gradeable grading page for all except user id.

**Expected behavior**
When the column is clicked it should sort by that column. 

**To Reproduce**
1. As a TA go to a gradable grading page 
2. Try to sort by first name

**Configuration**
 - OS: Windows and Mac
 - Browser: Chrome and Firefox

**Additional context**
Sorting is working on other grading pages such as the lab page.

**Comment by SaadAhmedGit** [comment]
I have pushed a fix which seems to be working. The issue was that the `'sort'` key coming from network request was being looked in `$_COOKIE` while it was supposed to be contained in the get request hence, should have been looked in `$_GET`

**Comment by Rayan-Rasheed** [comment]
Is this issue open? I want to work on it

**Comment by SaadAhmedGit** [comment]
@Rayan-Rasheed I have made a PR that fixes the issue. It's just waiting for approval by a reviewer after I made the suggested changes.
