### ISSUE TITLE
Date-Picker does not attach to the Pop-up they are opened in

### ISSUE THREAD

**Issue by hansongu123** [Submitty/Submitty#9106]
**Describe the bug**
See the comment section of Issue [#4712](https://github.com/Submitty/Submitty/issues/4712).

When a date-picker is opened in a pop-up form, it is not controlled by the scrolling inside of the pop-up but instead gets attached to the main page. PR [#8893](https://github.com/Submitty/Submitty/pull/8893) tried to resolve this issue by setting it to static but experienced a error in WAVE test's error detection. (see the comments within that PR).

This appears to be the nature within all pop-up forms in Submitty when a modal or a detachable object is opened within them. 

**Expected behavior**
A date-picker calendar object or any modal/pop-up object should attach to the subpage or the pop-up component that calls it, and not allowed to be scrolled or invoked outside.

**To Reproduce**

An example:
1.  Go to Course Material tab.
2.  Click the Upload button or Edit Course Materials.
3.  Click on a date/time-selection window, a calendar would pop-up, then scroll the page.
4.  See error.

**Configuration**
- All

**Screenshots**
**Taken from the comment section of the above mentioned issue.*
![image](https://user-images.githubusercontent.com/123511202/228107779-e7bb2ceb-c492-4c7f-9be8-f5940f1e9771.png)

**Additional context**
The issue maybe related to the way the "pop-up forms" are set up in Submitty. Note that in some part of the website, many of those and other modals are hacked for functionality.  A general fix or even a re-implementation of the pop-up should be presented in the future.

Chris' PR on implementing close-on-click feature to Pop-ups might be causing the issue with it not closing properly (PR [#7711](https://github.com/Submitty/Submitty/pull/7711)) (fixed)

**Comment by Pursottam6003** [comment]
Hii I would like to work on this project please assign me to do the task, it would be very helpful to me previously I had worked on such projects 
Thank You

**Comment by hansongu123** [comment]
Issue partially resolved by bumping flatpickr v4.6.6 to v4.6.12
