### ISSUE TITLE
Add Solid Background to the Checkmark Icon for Polls in Dark mode

### ISSUE THREAD

**Issue by hansongu123** [Submitty/Submitty#9114]
**What problem are you trying to solve with Submitty + How to solve it**

When an option in a poll is considered correct, and the instructor allowed answer releasing, a checkmark would appear next to the correct option's text in student's poll page like this:
![image](https://user-images.githubusercontent.com/123511202/229147727-fda9d625-0ace-4667-b757-ab95ecae7ea3.png)
However, this solid **FA icon** uses whatever the background color it is in to color the inside (while the outside is colored by a defined color in Submitty)

Change the inside color of the checkmark to a defined white color in Submitty, regardless of what mode it is in (Light, Dark, Black), so it is less uglier when in a darker background.

**Additional context**
_Please note that the corners of the square check are round, it would take a little bit of extra engineering._

**Comment by StephCurry07** [comment]
Did you try overwriting it with CSS?
Something like:
`.fa-check:before {
  font-weight: bold;
  content: "\f00c";
  color: white !important; /* Set the color to white */
  -webkit-text-fill-color: white !important; /* For Safari */
}
`
