### ISSUE TITLE
Exception in console in notebook file submission

### ISSUE THREAD

**Issue by jason490** [Submitty/Submitty#9120]
**Describe the bug**
When putting in a file in the notebook file submission gradeable and submitting (inside of the course development), a console error shows

**Expected behavior**
There shouldn't be an error that shows in the console

**To Reproduce**
1. Go into the development course
2. go into gradeables and click notebook filesubmission gradeable
3. upload a file and submit
4. See error in console

**Configuration**
 - OS: Linux
 - Browser safari

**Screenshots**
![Screenshot from 2023-03-31 21-23-01](https://user-images.githubusercontent.com/116290832/229258990-8f265a05-74ff-459e-8a69-382791a022e3.png)

**Comment by 26thavenue** [comment]
@jason490 Please can you assign me this issue

**Comment by snehalchaudhari98** [comment]
Hi, I would love to work on this issue.

**Comment by jason490** [comment]
Its seems like this issue was fixed
