### ISSUE TITLE
No proper documentation how to use  Tutorial / AnalysisTools / Rainbow in our main application 

### ISSUE THREAD

**Issue by Pursottam6003** [Submitty/Submitty#9122]
**What problem are you trying to solve with Submitty**
Hi I am new to open-source development so please guide me 
I installed the [Vm Install using Vagrant ](https://submitty.org/developer/getting_started/vm_install_using_vagrant)

**Describe the way you'd like to solve this problem**
I wanted to work on [Refactor and Performance Improvements for the Manual/TA Grading Interface] but (https://submitty.org/developer/getting_started/project_ideas)  but i have no idea how to do next and it would be great if someone would guide me 

I have experience in refactoring of websites 

**Describe any potential alternatives you'd tried to solve the problem**
I would be very happy if I would get some assistance from young and proactive contributors 

**Additional context**
Since it's not a particular issue I would request the maintainer to change the label to **Discussion**   

Thank You

**Comment by shailpatels** [comment]
Documentation on Rainbow grades as a sysadmin: https://submitty.org/sysadmin/configuration/rainbow_grades and as a student: https://submitty.org/student/grades/rainbow_grades

Analysis tools: https://submitty.org/instructor/autograding/static_analysis/index 

Tutorial is just a repo with additional autograding assignment examples
https://github.com/Submitty/Tutorial/tree/main/examples

You can view the docs on autograding for more details 
https://submitty.org/instructor/autograding/directory_structure

You also mention performance improvements which is different from your title, have you tried to visit the autograding web interface? We can't really help unless you have a specific question or have listed what you have already tried to do.

If you have specific questions/issues over the existing documentation such as missing or incorrect docs that would be a better issue to make, but this is currently to broad and off topic
