### ISSUE TITLE
Change download all button to be consistant with other download buttons

### ISSUE THREAD

**Issue by jason490** [Submitty/Submitty#9145]
**What problem are you trying to solve with Submitty**
The download all button is small and hard to see and also inconsistent with the other download buttons

**Describe the way you'd like to solve this problem**
Change the UI for download all button to be more consistent with the other buttons in gradeables.

From this download all button look that has 
![Screenshot from 2023-04-04 16-42-08](https://user-images.githubusercontent.com/116290832/229915804-b0bd61eb-c4ef-4365-8f7e-83a08df39ee1.png)
To this download button look:
![Screenshot from 2023-04-04 16-40-27](https://user-images.githubusercontent.com/116290832/229915385-649c08f2-12d0-4acc-bd8c-d4eedea6b2c4.png)

**Comment by DivyaKandhasamy** [comment]
hi, I would love to work on this one. Can you please assign this to me?

**Comment by Sranjan0208** [comment]
Hey! Can I work on this issue?

**Comment by ShubhamAXS19** [comment]
Hello,
i would love to on this issue
