### ISSUE TITLE
Display Pronouns In Discussion Forum

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9154]
**What problem are you trying to solve with Submitty**
Pronouns are only shown to instructors in Manage Students

**Describe the way you'd like to solve this problem**
Make an optional opt-in feature that displays your pronouns beside your name in the discussion forum

User profiles must also store a boolean value that is true when they would like to show their names in discussion forum

**Comment by sahil-ansari01** [comment]
1. Add a Pronoun Field to User Profiles:
To add a field for pronouns to user profiles in Submitty, you will need to modify the code that generates the user profile form. You can add a new input field for pronouns and store this information in the database.

2. Display Pronouns in Discussion Forum Posts:
To display a user's pronouns in their forum posts, you will need to modify the code that generates the user information block that appears next to each post. You can add a new field for pronouns and retrieve this information from the database.
