### ISSUE TITLE
Add Pronouns To Sample Data

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9157]
**What problem are you trying to solve with Submitty**
Currently in the Manage Students Tab (Instructor View) for developers there is no testing data for pronouns.
![image](https://user-images.githubusercontent.com/47994802/230673318-3cfdb445-c0fb-4819-9f13-c08333751b2a.png)

**Describe the way you'd like to solve this problem**
Edit the yaml file to add pronouns to students.
In .setup/data/users there are a handful of .yml files that set data for a small number of users
Add the pronoun field to those files and update the script that parses those files when we do a fresh “vagrant up” or a “recreate sample courses”.
Any users that aren’t explicitly included in that small set of files are generated randomly.
There’s also a script to generate that random data.  We’ll want to have a variety of data for that field, including empty/blank values.
Add them with certain probabilities, such as (example)
25% empty
30% He/Him
30% She/Her
10% They/Them
5% some other pronouns

**Comment by izha135** [comment]
Hello, I would like to work on this!

**Comment by mahi-pas** [comment]
> Hello, I would like to work on this!

Make the branch and when you're finished link it here!

**Comment by paurav42** [comment]
@mahi-pas , from the description, "update the script that parses those files" , are you referring to setup_sample_courses.py script? I was able to add the pronouns in the respective .yml files in the above mentioned probabilities, but just want to make sure I am able to follow other instructions. 
PS: I'm new to opensource contributions and trying to learn. Thanks

**Comment by mahi-pas** [comment]
> @mahi-pas , from the description, "update the script that parses those files" , are you referring to setup_sample_courses.py script? I was able to add the pronouns in the respective .yml files in the above mentioned probabilities, but just want to make sure I am able to follow other instructions. PS: I'm new to opensource contributions and trying to learn. Thanks

Yes, that should be the correct script
