### ISSUE TITLE
Course Materials Make Links Open In New Tab

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9175]
**What problem are you trying to solve with Submitty**
Documents in Course Materials open in a new tab, but links stay in the same tab and take you away from the course materials page. 

**Describe the way you'd like to solve this problem**
Links should open in a new tab.

**Comment by sahil-ansari01** [comment]
I'll fix it !!

**Comment by cjreed121** [comment]
See issues such as https://github.com/Submitty/Submitty/issues/5869 and https://github.com/Submitty/Submitty/issues/4526. I believe it's an intentional design choice for links to open in current tab. If you want to open in new tab you can middle click, shift click, or choose it on the context menu.

**Comment by sahil-ansari01** [comment]
@cjreed121 Sure I'll check them!!
Can you provide me the resources using which I can run the submitty application locally, using localhost.

**Comment by sahil-ansari01** [comment]
Hey! @cjreed121 I check the post mentioned on #5869 
And what's my take about links opening in new tab is, the links behaviour across the tab should be not be inconsistent.
I believe we can make the change mentioned in the above issues.
