### ISSUE TITLE
Undo button overlaps when scrolling in Grading lab

### ISSUE THREAD

**Issue by ziesski** [Submitty/Submitty#9177]
**Describe the bug**

Search for student, undo, redo button overlaps with Color info of check points, when scrolling down.

**Expected behavior**

Expect to stay in its original position, rather than following scroll.
I checked the original PR #3994, but there is no clear description of overlapping as intended behavior. 

**To Reproduce**
1. Go to Lab grading of gradable. 
2. Scroll down
3. See error

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

Mac / chrome

**Screenshots**
![Screen Shot 2023-04-12 at 22 37 38](https://user-images.githubusercontent.com/123261952/231633637-44bf58eb-a89e-4895-aea3-5711a9f3f920.png)

![Screen Shot 2023-04-12 at 22 38 14](https://user-images.githubusercontent.com/123261952/231633650-092877eb-638c-42d4-8992-3653e07e80d4.png)

**Additional context**

Checked mobile view, and it stays in its original position when scrolling. (works as expected)
iOS / Safari

Non critical, yet bugged me for the whole semester.

**Comment by yanliw123** [comment]
i would like to work on this
