### ISSUE TITLE
Add Pronouns to Student Photos page

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9182]
**What problem are you trying to solve with Submitty**
Currently only the instructor can see the user-specified pronouns on the "Manage Students" page.

**Describe the way you'd like to solve this problem**
Let's add the user-specified pronouns (if specified) to the "Student Photos" page.  
Currently, underneath the student's photo we have their preferred name, and their user id.
Let's put the pronouns underneath the user id.

NOTE:  We will also have to change the My Profile page to indicate that ALL members of the teaching staff will have access to the pronoun data entered by students.

**Comment by sahil-ansari01** [comment]
I'll fix it !!
We just need to add few tags and attributes to make this possible changes in the Student photo page.
Please assign me.

**Comment by sahil-ansari01** [comment]
@bmcutler can suggest me, how to indicate that ALL members of the teaching staff will have access to the pronoun data entered by students.
Just an overview!!
