### ISSUE TITLE
Change "Submit" button text for "Bulk Upload" mode

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9190]
**What problem are you trying to solve with Submitty**
When in bulk upload mode, the initial green button on the page should say "Bulk Upload" instead of "Submit":

<img width="659" alt="Screen Shot 2023-04-15 at 12 45 20 AM" src="https://user-images.githubusercontent.com/5871417/232183519-20dc9972-f096-45bb-9462-ae6e952d21e2.png">

The actual "Submit" buttons (that insert submissions for the students into the file system & database are below).

**Comment by sahil-ansari01** [comment]
I'll try fixing it !

**Comment by Kunal-debug-png** [comment]
please assign me this issue @bmcutler i can do this
