### ISSUE TITLE
Move to postgres 9.5

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#920]
We are currently running on Postgres 9.3 which is what's supported on Ubuntu 14.04, but 16.04 comes with postgres 9.5 by default.

**Comment by inlinefan** [comment]
Changed to postgres 9.5 on submitty

**Comment by inlinefan** [comment]
Note that there was a lot to be done manually after installing the new version

**Comment by MasterOdin** [comment]
So is the live server then now running postgres 9.5?

And what was a high level description of the tasks needed to manually move versions?

**Comment by inlinefan** [comment]
correcting links in /usr/bin to point to new versions... there were around 20 at a guess
