### ISSUE TITLE
Dependency `urllib3` currently locked to v1.26.14

### ISSUE THREAD

**Issue by skara9** [Submitty/Submitty#9246]
Python dependency `urllib3` is currently locked to v1.26.14 in the pip system requirements, as v2.0.0 currently crashes the docker installation. This should be changed when the dependency is updated to resolve the issue.

**Comment by pquentin** [comment]
Would you mind sharing the traceback? I'm not seeing here or in https://github.com/Submitty/Submitty/pull/9245. It would allow me to tell what is the issue: either the fact that you needed requests 2.29.0, or an actual incompatibility.

**Comment by pquentin** [comment]
Thanks! So you are hitting https://github.com/docker/docker-py/issues/3113. I have a fix here: https://github.com/docker/docker-py/pull/3118.
