### ISSUE TITLE
Calendar input fields don't line up when creating item.

### ISSUE THREAD

**Issue by EdenBendheim** [Submitty/Submitty#9249]
**What problem are you trying to solve with Submitty**
The input fields don't line up. I think the message text field should also be larger to accommodate a longer message without the user having to scroll.

![](https://user-images.githubusercontent.com/16820599/232245564-965644eb-0492-4558-bf3b-351827dbcee6.png)

**Describe the way you'd like to solve this problem**
Adding a margin or padding on the left to make them line up should be simple enough. Making the message text a _text area_ may be useful. Maybe making the order:
1. Type
2. Date
3. <TEXTAREA> Message Text

**Describe any potential alternatives you'd tried to solve the problem**

**Additional context**

**Comment by RohanJacob23** [comment]
Hello @EdenBendheim,

I would like to contribute to this issue. Could you please provide me with the link so that I can access it on my laptop and start working on it?
