### ISSUE TITLE
Allow multiple iclicker IDs

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#930]
In case a student loses, and buys a new iclicker, allow a student to have 2 or more iclicker numbers associated with their username.  

must accept multiple iclickers to be input (probably not all previous versions of submission, but rather multiple numbers in a single submission)

also rainbow grades/iris must handle multiple numbers

**Comment by holzbh** [comment]
@bmcutler Is this still a live issue? I know you made some changes in F17.

**Comment by bmcutler** [comment]
closed in PR #1642
