### ISSUE TITLE
add plagiarism text to Rainbow Grades web generator for customization.json

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9320]
**What problem are you trying to solve with Submitty**
The rainbow grades web form for customization is missing input for academic integrity violations. 

**Describe the way you'd like to solve this problem**
Here is an example of the syntax needed in the json file:

```
    "plagiarism" : [
        { "user" : "XXXXX",     "gradeable" : "XXXXX",      "penalty" :  1.0 },
        { "user" : "XXXXX",     "gradeable" : "XXXXX",      "penalty" :  0.0 },
        { "user" : "XXXXX",     "gradeable" : "XXXXX",      "penalty" :  0.5 }
    ]
```

Let's add a "add academic integrity violation" button to the web UI.  And then the instructor types the user id, gradeable id, and penalty.  We should do some basic validation on the user id string and gradeable id string.   And the penalty should be 0.0-1.0 in value.

**Comment by ziesski** [comment]
Just a small notes for future developers (who wants to work on Rainbow Grades)

Rainbow grades for individual summary on Submitty is not rendered with .html files in "individual_summary_html" directory, but from "/reports/summary_html/" directory. This may cause confusion, and solution was to copy all files from A to B. This may be an issue in the future, but for now below is the quick fix snippet. 

root@vagrant:/var/local/submitty/courses/s23/sample/rainbow_grades# cp individual_summary_html/*_summary.html ../reports/summary_html/

You may want to do "make clean" command before "make", to create Rainbow Grades.
