### ISSUE TITLE
Add in basic routing (semester + course) for URL

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#933]
We should be able to go to:
https://submitty.cs.rpi.edu/s17/csci1100/index.php
https://submitty.cs.rpi.edu/csci1100/index.php

and be taken to the course page for it (instead of having to do `index.php?semester=s17&course=csci1100`, though this might still be supported?)

More complex style of routing will come later once things are better defined and all functionality is then routed through that central index.php. The more complex style can be tested within a REST API (#300)

**Comment by MasterOdin** [comment]
@Nerdsie, what were you thinking of doing for this?

I believe that by inserting:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)\/(.*)\/index\.php$ index.php?semester=$1&course=$2 [QSA,L]
    RewriteRule ^(.*)\/(.*)\/index\.php\?(.*)$ index.php?semester=$1&course=$2&$3 [QSA,L]
</IfModule>
```
in our apache configuration will probably get us almost there for what this issue has (namely just dealing with semester/course).

I'd probably then open a new issue for doing research into various existing PHP routers or if we're just best off writing our own (which I don't think we need).

**Comment by Nerdsie** [comment]
Yeah that's basically what I was going to do, just a little more in-depth.
And I feel like we kinda have a sketchy implementation of a PHP router with how everything goes down in index.php

**Comment by MasterOdin** [comment]
Yes, you could further this with the parts of a path being `/{semester}/{course}/{component}/{page}/{action}/index.php`.

**Comment by Nerdsie** [comment]
I was going to have two scenarios setup, /class/{semester}/{course}/{component}/{page}/{action}/ and {component}/{page}/{action}/ in case there are a few odd scenarios that pop-up where there's a component/page/action being called without a semester/course specified (right now, just authentication)

I was planning on putting this all into an .htaccess file I'd add to /site/public/, would there be any problems with that or would that work?

**Comment by MasterOdin** [comment]
This should be done in the Apache configuration directly, there's no reason
to do this in an .htaccess.

**Comment by Nerdsie** [comment]
Why's that?  If it's done as an .htaccess it makes it pretty easy to deploy and if the website ever gets transferred to another server or something the url settings will automatically come with the code and not break everything

**Comment by MasterOdin** [comment]
Well, we have to edit the apache configuration no matter what as right now .htaccess is disabled:
https://github.com/Submitty/Submitty/blob/ec44ab8cc76ff978dc7d14f7bf32fe22ae071901/.setup/vagrant/sites-available/submitty.conf#L43-L45

Couple this with the note on htaccess directive page (https://httpd.apache.org/docs/2.4/howto/htaccess.html):
> You should avoid using .htaccess files completely if you have access to httpd main server config file. Using .htaccess files slows down your Apache http server. Any directive that you can include in a .htaccess file is better set in a Directory block, as it will have the same effect with better performance.
(see https://www.eschrade.com/page/why-you-should-not-use-htaccess-allowoverride-all-in-production/ for a brief test on performance using htaccess vs not)

Submitty, by virtue of what it is, requires you have server access and subsequently apache access. The rewrite block is small enough that transferring it to a new server is no more trouble than making sure the rest of the apache configuration transfers anyway.

**Comment by KevinMackenzie** [comment]
I think it would also be worth our while to change all of the URL's for buttons and links to use this routing scheme.

**Comment by KevinMackenzie** [comment]
The least intrusive method to accomplish this is to modify the `submitty.conf` in the `sites-available` to allow redirection and then redirect everything, excluding static resources in designated folders, to `index.php` and then have a layer that interprets the provided path and injects it into the `GET` parameters just like if the `?course=...` scheme was used.  This wouldn't break backwards compatibility at all.

A more involved method would be to use an existing / make a router like [bramus/router](https://github.com/bramus/router)
