### ISSUE TITLE
Move sample_files and combine with tutorial

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#941]
Right now we have sample configs/submissions spread out in the [sample_files](https://github.com/Submitty/Submitty/tree/master/sample_files) folder in this repository and then an additional [Tutorial](https://github.com/Submitty/Tutorial) repository that contains some. 

We should move this all to one repository (sample_files?) that contains all of this in one standardized location and we use for samples. We should the have a separate repo that contains all the configs and things that we use purely for testing in this repo.

**Comment by bmcutler** [comment]
No, they should not just be merged.  The tutorial examples are step by step for learning how to write configs.  The sample_files versions that were not duplicated/selected for tutorial use are for integration testing and should not clutter the tutorial.
