### ISSUE TITLE
Create Shortcut Command for recreate sample courses

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9425]
**What problem are you trying to solve with Submitty**
To recreate sample courses, one must type:
`sudo bash /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh`
Which can be annoying to copy and paste from documentation.

**Describe the way you'd like to solve this problem**
Similar to how `submitty_install` is a shortcut for `sudo /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh`,
make a shortcut for recreate sample courses that can be called using `recreate_sample_courses`

Make sure your are able to append the `--no_submissions` flag, which can speed up the command by skipping submissions.
The user would write `recreate_sample_courses --no_submissions`, which would translate to:
`sudo bash /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh --no_submissions`

**Additional context**
Submitty.org page mentioning recreate sample courses command:
https://submitty.org/developer/development_instructions/index

**Comment by williamschen23** [comment]
closed by #10578
