### ISSUE TITLE
Refactor Cypress Tests to Use Cypress Variables

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9482]
**What problem are you trying to solve with Submitty**
Cypress recommends using its own variable system when returning Cypress elements rather than javascript variables. In order to make our code reflect the best practices, we should refactor our tests to use Cypress's system.

For more info:
https://docs.cypress.io/guides/references/best-practices#Assigning-Return-Values
https://docs.cypress.io/guides/core-concepts/variables-and-aliases

**Describe the way you'd like to solve this problem**
Refactor all the tests in `site/cypress/e2e` to use Cypress variables when needed.

**Additional context**
For information on installing and using Cypress, consult the documentation:
https://submitty.org/developer/testing/cypress

To see a test with proper cypress variables, reference `site/cypress/e2e/Cypress-UI/pronoun_change.spec.js` or read the comments on the PR #9433 which added that test.

**Comment by mahi-pas** [comment]
@tarunsamanta2k20 would you like to work on this?

**Comment by Mehul-Agrawal410** [comment]
hey I am new to contributing and would like to try this out if you could assign it to me

**Comment by IDzyre** [comment]
The way the Submitty organization works, is we cannot assign external contributors to issues. However if you create a pull request and link it to the issue, we, and other contributors will know you are working on it.

**Comment by tarunsamanta2k20** [comment]
@IDzyre please run the cypress test once for my PR. And send  me the log what is the error.
