### ISSUE TITLE
Fix Development PDF Exam Settings

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9485]
**What problem are you trying to solve with Submitty**
Development -> PDF Exam has a gradeable type "Students will submit one or more files by direct upload to the Submitty website"
![image](https://github.com/Submitty/Submitty/assets/47994802/157e29fb-e7c6-4a01-81bc-8acd45e2ad76)

However, the gradeable type should be "TA/Instructor will (bulk) upload scanned .pdf for online manual grading"
![image](https://github.com/Submitty/Submitty/assets/47994802/529919fb-ac98-497f-aff8-1caa6eb8e9d3)

**Describe the way you'd like to solve this problem**
Change the settings for PDF Exam to make the gradeable type "TA/Instructor will (bulk) upload scanned .pdf for online manual grading"

**Comment by jd-becerra** [comment]
Hi, so you want to have that line changed to "TA/Instructor will (bulk) upload scanned .pdf for online manual grading"? Or do you want all instances with "PDF Exam" changed to "hulk/bulk"? I'm sorry, I'm new at working in projects

**Comment by jd-becerra** [comment]
Hi, so what you need is to change the value of 'electronic_hw' in "gradeable_type_strings" in the file "AdminGradeableController.php" from"Students will submit one or more files by direct upload to the Submitty website" to: "TA/Instructor will (bulk) upload scanned .pdf for online manual grading" ?   I'm sorry, I'm new at contributing in projects but if that is what you need I can help

**Comment by jd-becerra** [comment]
> > Hi, so what you need is to change the value of 'electronic_hw' in "gradeable_type_strings" in the file "AdminGradeableController.php" from"Students will submit one or more files by direct upload to the Submitty website" to: "TA/Instructor will (bulk) upload scanned .pdf for online manual grading" ? I'm sorry, I'm new at contributing in projects but if that is what you need I can help
> 
> My understanding is that you would change the data in `.setup/data/courses/development.yml`. You would find there the `pdf_exam` gradeable is defined and edit the settings to be correct.
> 
> Afterwards, you can test your changes by running recreate sample courses: https://submitty.org/developer/development_instructions/index#re-creating-all-sample-course-data
> 
> `.setup/data/courses/development.yml` is interpreted by `.setup/bin/setup_sample_courses.py`. If you read `setup_sample_courses.py`, you'll be able to find out which settings are needed to make it into a bulk upload.
> 
> To get a better idea of what type of changes you have to make, it might help to look at PR #9241 which added a new gradeable to sample. Instead of adding a course, you'd just be editing an existing one.
> 
> Thank you for your contribution! Let me know if you need any help.

Ok thank you for responding. I looked at the ".setup/data/courses/development.yml" file and the Database Design in the documentation for Submitty and I understand I can add an integer for "g_gradeable_type", although I don't know what types are available and which is the one for "TA/Instructor will (bulk) upload scanned .pdf for online manual grading"
