### ISSUE TITLE
Default Anonymous Mode Setting for Full Access Graders/Instructors

### ISSUE THREAD

**Issue by NiaHeermance** [Submitty/Submitty#9490]
**What problem are you trying to solve with Submitty**
Currently, for each Gradeable, instructors can set the blindness settings for peer graders and limited access graders. Full access graders and instructors however always can see students' names unless the instructor/full access grader manually clicks for themselves "Enable Anonymous Mode" on the Gradeable's details  page.

Sometimes, however, it is better for the default for instructors and full access graders to have Anonymous Mode enabled. Thus there should be a setting for each Gradeable on the default Anonymous mode.

**Describe the way you'd like to solve this problem**
On the Gradeable's config page, under Grader Asssignment, instructors can set whether instructors and full access graders should start in Anonymous Mode.

**Additional context**

![image](https://github.com/Submitty/Submitty/assets/51209504/16e447f4-5d08-43df-82e7-4f59793d2d55)

![Enable Anonymous Mode](https://github.com/Submitty/Submitty/assets/51209504/dd044a6d-a08e-42b3-860f-c3f4bc72117d)

**Comment by im-ajaymeena** [comment]
can I work on this?

**Comment by im-ajaymeena** [comment]
I was trying to understand codebase, could you help me in finding where is method `getLimitedAccessBlind` for `gradeable` defined 
I can see many places its been used`$gradeable->getLimitedAccessBlind()` but couldn't found the declaration

**Comment by NiaHeermance** [comment]
Sure! I'm taking some time off currently.
