### ISSUE TITLE
Add Rainbow Grades version to bottom of generated html

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9492]
**What problem are you trying to solve with Submitty**
To help understand which version of the RainbowGrades code was used to produce an output file, let's add a line to the bottom of the individual .html and instructor output.html files:

"Output generated by Submitty RainbowGrades v23.06.01 (123bsd)"

That includes the latest tagged version & commit hash.

This is similar to the footer that is generated on the main Submitty repository.
<img width="474" alt="Screenshot 2023-06-28 at 3 22 27 PM" src="https://github.com/Submitty/Submitty/assets/5871417/b4d84d88-dae5-4f68-a8d5-ff79a56bd693">

**Comment by ziesski** [comment]
above mentioned PR closes this issue
