### ISSUE TITLE
Improve error messages when students submission is missing a required file, missing required directory structure, or contains unnecessary directory structure

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#95]
Right now, when a student submits a homework that contains multiple parts, they need to zip the parts together and submit it. However, they need to have the exact proper folder structure as the server else it'll cause a failure to run. Should have the option of just flattening the submitted zip into one folder if possible.

An example would be:
Looking for hw06.py and Bird.py
If you right-click and zip them, and upload to the server, it'll upload as:
hw06.py
Bird.py

But if you zip the folder containing them (hw06), then submit that, you'll get:
hw06/hw06.py
hw06/Bird.py

which causes failure to run. A fix would cause the second example to just be:
hw06.py
Bird.py

instead. This should be accomplished by an optional flag in the configuration details of a HW assignment or something.

---

edited to add todo list

Changing submitted directory structure is a low priority "what if" feature.
We do list the files/directories received.  We could improve this visualization.
Better to improve error messages when files are not as expected for the assignment.

Test cases (assignment configuration + sample submissions) needed:
- [ ] required file is missing (e.g. README.txt)
- [ ] required directory structure is missing (e.g., src/ or test/ or docs/ directories)
- [ ] unnecessary directory was included (hw1/my_file.py instead of just my_file.py)

Make sure each has a clearly visible, clearly worded error message.
(May require additions/changes to instructor configuration so the server knows to check for these things).

**Comment by MasterOdin** [comment]
Here's a code snippet of how this would probably work:

```php
public static function flatten_dir($base_dir, $current_dir) {
    if ($handle = opendir($current_dir)) {
        while (false !== ($entry = readdir($handle))) {
            if ($entry != "." && $entry != "..") {
                if (is_dir($current_dir."/".$entry)) {
                    flatten_dir($base_dir, $current_dir."/".$entry);
                }
                else {
                    rename($current_dir."/".$entry, $base_dir."/".$entry);
                }
            }
        }
        closedir($handle);
    }
    @rmdir($current_dir);
}
```

And then call this function on line 210 (wrapped via a setting flag of some sort for if this should be enabled) of data_functions.php. It'll move all files out of directories to the top-level (overwriting anything that has the same name) as well as deleting all the directories (if it can).

**Comment by sihsob** [comment]
Add an instructor option to print a warning message if folder structure detected

**Comment by bmcutler** [comment]
Changing submitted directory structure is a low priority "what if" feature.
We do list the files/directories received.  We could improve this visualization.
Better to improve error messages when files are not as expected for the assignment.

Test cases (assignment configuration + sample submissions) needed:

- [ ] required file is missing (e.g. README.txt)
- [ ] required directory structure is missing (e.g., src/ or test/ or docs/ directories)
- [ ] unnecessary directory was included (hw1/my_file.py instead of just my_file.py)

Make sure each has a clearly visible, clearly worded error message.
(May require additions/changes to instructor configuration so the server knows to check for these things).

**Comment by lindquistador** [comment]
When a student submits the incorrect type of file an error message should appear. Currently nothing shows up and the student just receives a 0.

**Comment by bmcutler** [comment]
What do you mean incorrect type of file?   Not a zip?  Not python/c++ code?

**Comment by bmcutler** [comment]
closing this because drag & drop buckets has made this easy.
