### ISSUE TITLE
Better Calendar Sample Data

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9514]
**What problem are you trying to solve with Submitty**
Currently all the sample data for Calendar is this:
![image](https://github.com/Submitty/Submitty/assets/47994802/d085a011-69c3-454f-b6e3-6ed2abe55604)

In order to make developing and testing new features easier, we should make more sample data

**Describe the way you'd like to solve this problem**
Try not to create more gradeables, use the ones currently available and try to stagger it to make a good (at least) 2 weeks of complicated data.

**Comment by saurabhbakolia** [comment]
I would like to work on this issue.
