### ISSUE TITLE
Update Sample Discussion Forum Data With Markdown

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9515]
**What problem are you trying to solve with Submitty**
In the discussion forum, we use markdown to format text. However, some of our sample data uses an obsolete format. 
For example:
![Screenshot from 2023-07-11 11-38-16](https://github.com/Submitty/Submitty/assets/47994802/411b7174-6690-440b-b63a-a12a2b33f7d4)
Uses code tags rather than the markdown syntax

**Describe the way you'd like to solve this problem**
Sample forum data is generated based on the files in `.setup/data/forum/`. Go through these files and make changes to ensure these are using the proper markdown syntax. Then also look at the discussion forum to make sure these changes are displayed properly.

**Additional context**
Information on markdown: https://submitty.org/student/communication/markdown

**Comment by im-ajaymeena** [comment]
@mahi-pas 
I had an query, If I do any changes local files. How can I force those changes to be visible in website, is there any command to update vagrant state?
(I did some changes to `.setup/data/forum/posts.txt` but the corresponding discussion at `http://localhost:1511/courses/f23/sample/forum/threads/3` still looks same)

**Comment by saurabhbakolia** [comment]
Hey @mahi-pas  I would like to work on this issue.

**Comment by mahi-pas** [comment]
> @mahi-pas I had an query, If I do any changes local files. How can I force those changes to be visible in website, is there any command to update vagrant state? (I did some changes to `.setup/data/forum/posts.txt` but the corresponding discussion at `http://localhost:1511/courses/f23/sample/forum/threads/3` still looks same)

Normally, if you made a change to a php/js/twig/css/etc file you would have to ssh into the VM by running `vagrant ssh`. Once you ssh, you would run `submitty_install`.

However, for this PR, since you're changing the files for how sample course are constructed you would run recreate sample courses (make sure you run this after `vagrant ssh` as well. 
Run `sudo bash /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh --no_submissions` . 
The no submissions flag speeds up the process by skipping submissions. This command takes a long time so try to get in as many changes before running it.
Documentation: https://submitty.org/developer/development_instructions/index#re-creating-all-sample-course-data

**Comment by mahi-pas** [comment]
> Hey @mahi-pas I would like to work on this issue.

Sure thing! Make a fork and make a pull request when you want us to look at it

**Comment by im-ajaymeena** [comment]
@mahi-pas 
Thanks for the explanation, it worked !

Also for the confirmation, we just have to replace syntax like [code][/code], [url][/url] etc. with appropriate markdown syntax as listed in [https://submitty.org/student/communication/markdown](https://submitty.org/student/communication/markdown)
