### ISSUE TITLE
Deductions Affecting Gradeable Max Total Score Displayed

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#956]
I added a "general deductions" rubric item to the TA-graded portion of the submission. It is worth -35 points. Unfortunately on what I believe is the "grade index" page (where all the students are shown in their respective rotating sections, with the autograder/TA grading/totals), this deduction is being added in so the max score appears to be 15 instead of 50.

If a criterion has a max value < 0 it is my belief that it shouldn't be added to the max total. Naturally, if the score given in <0 that deduction should still be reflected in the total points received, but right now it would look strange to have 16/15 or 50/15.

**Comment by holzbh** [comment]
To add to that, in retrospect it's a bit of an odd rubric item, I want the graders to have the ability to give a deduction, and I want it to be clear that it's up to a 35 point deduction. I could put this in the TA notes instead, but I don't think there's clear guidelines on how a rubric item should be represented to allow deductions.

If there's another way to go about this and we don't want rubric items with negatives, the UI shouldn't allow it.

**Comment by holzbh** [comment]
One more addition, since I don't think I should open a separate issue for a related problem.

I had an assignment where the student had 33 autograder points. I gave them no other points and gave a -33 point deduction (shows up correctly in the grading interface). On the index though, it now reads
33/35 for the autograding
-35/-20 for the TA grading (I didn't put in -35 or -20...)
-2/15 for the total.

The homework report reads:
AUTO-GRADING TOTAL [ 33 / 35 ]
TA GRADING TOTAL [ -33 / 15 ]
HOMEWORK 8: B+ TREES GRADE [ 0 / 50 ]

So the max-TA-points issue is reflected in the homework report, but at least the deduction and gradeable totals are correct.

**Comment by bmcutler** [comment]
@masterodin   this is probably best fixed by you.  It looks like you're not accounting for penalty rubric items correctly.  When we marked the penalty rubric item as extra credit, at least the total possible (excluding extra credit) is now correct (/50), but the student total is still wrong.

**Comment by bmcutler** [comment]
update:  the "generate hw report" creates the correct data, with or without the rubric item marked "extra credit"

however:  the index page showing all students (viewed by tas while grading) has the wrong data in the numerator of the tagrading (either way marked ec or non ec) and the wrong data in the denominator when not marked ec.  note: marking a penalty rubric item ec is confusing.  it should be irrelevant to the maths.
