### ISSUE TITLE
Add broader notification for `vagrant_up.yml` failure

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#9596]
Whenever the [`vagrant_up.yml` scheduled workflow](https://github.com/Submitty/Submitty/blob/main/.github/workflows/vagrant_up.yaml) fails, it sends a notification to the person who  last updated the schedule, which happens to be me. If someone else updates the schedule, then they'll be the only person who gets a notification this workflow is failing. This isn't super useful as it creates a bus factor of 1 on knowing the status of this workflow, and is easy to miss/ignore.

Instead, should send out a broader notification if the workflow fails (use the `if: ${{ failure() }}` syntax for a step to have it run only on failure) so that more of the team knows this is happening and be encouraged to fix it. Two options for type of notification would be to create a GH issue or to send a slack message. I would lean towards the latter as it's easier to gain visibility vs a GH issue.

**Comment by bmcutler** [comment]
Can we do both slack & github issue?

**Comment by MasterOdin** [comment]
Yeah, though one thing would GH issue would be figuring out how it gets posted / updated. Like, probably wouldn't want a GH issue per failure, so figuring out how to condense the failures to a single issue. Could just have a single "omnibus" GH issue that gets opened and posted in if there's a test failure? Might be easier than creating a new issue on a failure, and then coordinating each additional failure to find that new issue.
