### ISSUE TITLE
Flatpickr (Datetime picker) not properly working

### ISSUE THREAD

**Issue by Youssef-Chip** [Submitty/Submitty#9597]
**Describe the bug**
On Submitty, some datetime pickers are provided by Flatpickr, which are not working properly. If you try to change the month, the year or the hour (but not the day) from within the datetime picker, you will exit it and you won't be able to choose a time in that way.

**Expected behavior**
The datetime picker should always let you change the hour, the month and the year.

**To Reproduce**
1. Log in as instructor
2. Go to course materials ( one of the pages that use flatpickr)
3. Click on Set Folder Release Date ( or any button that will display a datetime picker) 
4. Within the Datetime picker (not manually in the textbox), try to change the month, the year or the hour.
5. Error: you will be prompted out

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

**Screenshots**
For example, click on August here: 
![image](https://github.com/Submitty/Submitty/assets/131885371/692466c9-fe1e-428c-986a-22ed6495e14b)
**Additional context**

**Comment by williamjallen** [comment]
What browser are you using?  I don't see this issue on Chrome, but I do see it on Safari.

**Comment by Youssef-Chip** [comment]
> What browser are you using? I don't see this issue on Chrome, but I do see it on Safari.

I have this issue on Chrome

**Comment by hansongu123** [comment]
Seems to be an event conflict between my PR intended to fix the scrolling and Chris' PR (#7711) that implements that added a feature to close a pop-up form when clicking outside of it.
