### ISSUE TITLE
Side bar collapses by itself although it should stay expanded

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#9669]
**Describe the bug**
The side bar collapses without any request from the user.

**Expected behavior**
The user wants the sidebar to stay expanded at all times. In reality, the side bar collapses on its own when navigating the pages.

**To Reproduce**
See the screenshots that show some example scenarios but there are more. The side bar has a tendency to collapse in quite a few different page traversals.

**Configuration**
 - OS: Windows 11 Home Version 22H2 OS build 22621.1848 Experience Windows Feature Experience Pack 1000.22642.1000.0
 - Browser: Mozilla Firefox 116.0.2 (64-bit)

**Screenshots**
![firefox_l9vIuZRYwj](https://github.com/Submitty/Submitty/assets/7108039/5e6264f8-610c-4902-90b0-90b434545b42)
![firefox_1gRhJYXr5d](https://github.com/Submitty/Submitty/assets/7108039/de77791f-a78f-4c02-be8b-cabe5e5c052a)

**Additional context**
N/A

**Comment by bmcutler** [comment]
The original design was for the sidebar to automatically collapse when the page was narrow.  
The examples above are clearly a bug.   

But I will also request that we revisit the threshold page width that triggers automatic collapse.  
I think it is too aggressive.  
I would like to revise the criteria for collapse, and give more control to the user on whether it should be collapsed or uncollapsed regardless of page width.

**Comment by KCony** [comment]
I agree. There might be other users like me who want the sidebar to stay expanded no matter what. Maybe I would be more inclined to keep it collapsed, if I could interpret the icons easily. When the sidebar had a lot fewer items in the original Submitty design, I could memorize the meaning of a few icons. But now with so many items, the icons just ring no bells in my head. Maybe the icons could be revisited and made more intuitive? Some icons are so similar, I can hardly tell the difference, and if I look long enough, I can tell they are different but what this difference really means still evades me. Here is a good illustration:
![image](https://github.com/Submitty/Submitty/assets/7108039/89aba9f7-1048-4fc0-aaa7-565fb4028ed9)

How many people would be able to tell what each of these two icons mean without using a tool tip?

**Comment by williamjallen** [comment]
Is this another variation of the bug fixed in https://github.com/Submitty/Submitty/pull/7781?
