### ISSUE TITLE
Forum page doesn't get updated after making a new thread or responding to an existing message

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#9670]
**Describe the bug**
When a new message or a response is created the post button is disabled but the new message is not shown

**Expected behavior**
The new message should be shown in the "view thread" mode.

**To Reproduce**
See the screenshots that show some example scenarios but there are more.

**Configuration**
 - OS: Windows 11 Home Version 22H2 OS build 22621.1848 Experience Windows Feature Experience Pack 1000.22642.1000.0
 - Browser: Mozilla Firefox 116.0.2 (64-bit)

**Screenshots**
![firefox_Q0w1lz949h](https://github.com/Submitty/Submitty/assets/7108039/fae15146-0787-4e3a-8169-42edcedaf74f)

**Additional context**
I believe we had similar issues at some point, and it was decided that they are related to Websockets. It was fixed and we had no problem for some time but looks like here it is again.

**Comment by powe97** [comment]
I can't reproduce this (Arch Linux, Firefox). It was probably fixed at some point but went unnoticed. If this is still an issue, reopen.
