### ISSUE TITLE
For a numeric gradeable, an error is shown on editing the grade for every student

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#9673]
**Describe the bug**
When an instructor enters grades for a numeric gradeable, an error pops up after every single edit. Refreshing the page suggested by the error message doesn't help. The grades seem to save fine though.

**Expected behavior**
There should be no errors shown when an instructor updates the grades in the gradeable.

**To Reproduce**
See the screenshot that shows all steps.

**Configuration**
 - OS: Windows 11 Home Version 22H2 OS build 22621.1848 Experience Windows Feature Experience Pack 1000.22642.1000.0
 - Browser: Mozilla Firefox 116.0.2 (64-bit)

**Screenshots**
![Untitled Project](https://github.com/Submitty/Submitty/assets/7108039/d6b9ab87-07bb-4a97-b97f-daaef9876ab7)

**Additional context**
N/A

**Comment by musaabimran** [comment]
I wasn't able to reproduce the error!

**Comment by powe97** [comment]
I can't reproduce this (Arch Linux, Firefox). We probably fixed this at some point, but I also can't pin down what PR solved it. If this is still an issue, reopen.
