### ISSUE TITLE
Rainbow Grades should include a legend

### ISSUE THREAD

**Issue by KCony** [Submitty/Submitty#9674]
**What problem are you trying to solve with Submitty**
With the recent addition of borders and even more colors, we really need a legend to specify what each visual cue means.

**Describe the way you'd like to solve this problem**
A legend should be added to the html file with Rainbow output. In addition, it would be nice to have tooltips. Adding some JS to show tooltips in the HTML should be doable.

**Describe any potential alternatives you'd tried to solve the problem**
I'd say, not as an alternative but the color coding and line type coding (dashed vs solid, etc.) should be updated in the documentation. I searched the documentation just now, and I cannot find the relevant description. If it is there, it is probably too hard to find.

**Additional context**
See the screenshots below:

![image](https://github.com/Submitty/Submitty/assets/7108039/a1241786-6869-4df7-b8f9-bb1736c4977d)
![image](https://github.com/Submitty/Submitty/assets/7108039/328a592b-fce6-4a9c-b9b6-9a363afc1807)

To this day, I still can't figure out what the yellow solid vs. red sold vs. green dashed borders mean.

**Comment by bmcutler** [comment]
@KCony 

It's something like:

green dashed means unresolved grade inquiry
yellow outline means grade override
red outline means academic integrity violation

But yes, @ziesski already has on his todo list to create a legend both for the instructor and the student.

**Comment by bmcutler** [comment]
Or maybe red outline was 'too many late days used'. (obviously this guessing game isn't acceptable)

**Comment by KCony** [comment]
Yes, this is exactly what I meant. Perfect! Thank you @bmcutler !

**Comment by ziesski** [comment]
![Screen Shot 2023-08-17 at 12 54 52 PM](https://github.com/Submitty/Submitty/assets/123261952/e5a04ce9-6e2b-4be2-a497-dda7dfedd064)

For clarification purpose, these are the meaning of each border-line, will implement the explanation soon. 
Sorry for any inconveniences.

**Comment by KCony** [comment]
What does bad status mean? In my opinion, it would probably be best to have the same wording as Submitty uses, like "Version Conflict" or "Too many late days used", etc. Otherwise, it is not clear what exactly  "bad" means in this context.

**Comment by ziesski** [comment]
![Screen Shot 2023-08-18 at 9 36 15 AM](https://github.com/Submitty/Submitty/assets/123261952/75d68e2e-d6a9-4f2d-ad94-40d91e3436f4)
Thanks for pointing it out, we had the discussion on the meeting, and agreed that bad status has to be more descriptive.
Bad status = too many late days used on this assignment OR you didn’t have sufficient late days to use

**Comment by bmcutler** [comment]
@ziesski 
Did we forget to handle "version conflict"?  That can be a surprise/confusing for students and staff.  Would be worth having a different visual for that, perhaps a dashed red outline?

**Comment by ziesski** [comment]
@bmcutler I agree Version Conflict should have its own mark. Will work on it right away.

**Comment by KCony** [comment]
Any updates?

**Comment by KCony** [comment]
@ziesski
