### ISSUE TITLE
Idea: Show Clickable Calendar Entries with two tones of color

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9705]
**What problem are you trying to solve with Submitty**
There is no way to show entries are clickable.

**Describe the way you'd like to solve this problem**
Make a calendar entry have a lighter/darker shade to show it is clickable or not clickable

**Describe any potential alternatives you'd tried to solve the problem**

**Additional context**

**Comment by rajatmohan22** [comment]
Could I please submit a PR for this?

**Comment by sahil-ansari01** [comment]
Hey! @rajatmohan22 are you currently working on this specific issue ??

**Comment by sahil-ansari01** [comment]
@mahi-pas I would like to provide possible solution to the problem statement 
Please assign me to the task !!
Solution:

1. Clickable Calendar Entries:
Clickable calendar entries should have a lighter shade to indicate that they can be interacted with. This shade change should be subtle enough to maintain readability and usability.

2. Non-Clickable Calendar Entries:
Non-clickable calendar entries should have a darker or grayed-out shade to visually indicate that they are not interactive. This shade change makes it clear to users that these entries cannot be clicked.
