### ISSUE TITLE
Calendar Should Use Display Name Not Course Name

### ISSUE THREAD

**Issue by mahi-pas** [Submitty/Submitty#9727]
**What problem are you trying to solve with Submitty**
![image](https://github.com/Submitty/Submitty/assets/47994802/f9937ed3-ef73-4feb-be12-23a4c04203a5)
The calendar lists these courses, but it is hard to understand what these courses are if you don't have the course codes memorized

**Describe the way you'd like to solve this problem**
Courses have a display name property that is usually human-readable. Default to using that, but if none is set then use the course id.

**Comment by sahil-ansari01** [comment]
I would like to fix it !!
