### ISSUE TITLE
Improper use of Date strings in JS

### ISSUE THREAD

**Issue by skara9** [Submitty/Submitty#9731]
Currently in our JavaScript code, there are numerous calls to the Date constructor which pass in a date string.
Many of the strings passed in do not follow the ISO8601 format and rely on non-standard browser behavior to parse the date.
This is very bad practice and can lead to parts of the site breaking across different browsers.

To fix this, all date strings in JavaScript should be updated to be formatted properly.

Ex.) `new Date("02/01/1970 05:00")` => `new Date("1970-02-01T05:00:00")`

**Comment by williamjallen** [comment]
Related to https://github.com/Submitty/Submitty/issues/6415

**Comment by Piyush2504** [comment]
can you specify where do we need to change the formatting

**Comment by anish-patro** [comment]
Hi, I would like to work over this issue.

**Comment by shubhalgupta** [comment]
@skara is this issue still open?

**Comment by Chandan-Singh10** [comment]
I want to work on this issues please assign me this issues.

**Comment by Jatingupta9120** [comment]
assign this issue to me

**Comment by antriksh-9** [comment]
Hey @skara9 I want to work on this issue. 
Please assign it to me.
