### ISSUE TITLE
Undo Button for Grading Lab is Buggy

### ISSUE THREAD

**Issue by hansongu123** [Submitty/Submitty#9779]
**Describe the bug**
Clicking on the "undo" changes button on "grading lab" page doesn't properly revert the changes that an user makes. The "redo" button, which is dependent on this feature may be potentially broken because of this.

This bug also causes simple_grading.specs.js to be broken most of the times when running locally.

This is caused by WebSocket being broken, so the page wouldn't load dynamically, the feature should be removed per our discussion.

**Expected behavior**
Clicking on the "undo" button should revert the most recent change made to the grading sheet - the button may or may not be available after an user refreshes or prompts out of the page. The "redo" button should revert the most recent change made by "undo".

After fixing this bug, make sure simple_grading.specs.js runs smoothly locally.

**To Reproduce**
1. login as a Ta/Instructor
2. go to "gradeables" page, open a "lab" assignment to grade
3. make a change to the current grading sheet, click "undo"

**Configuration**
 - OS: Windows
 - Browser chrome

**Comment by jason490** [comment]
We are removing the undo button
