### ISSUE TITLE
Show Graders/ Dates Graded option should remember selected options using cookies

### ISSUE THREAD

**Issue by jason490** [Submitty/Submitty#9787]
**Describe the bug**
The Show Graders check box and Show Dates Graded options, when the check box is checked and page reloaded, the options get reset.

**Expected behavior**
There should be a cookie that remembers the options of Show Graders/Show Dates Graded that the user selected

**To Reproduce**
1. Go to /courses/f23/sample/gradeable/grading_lab/grading
2. click on the check box for show Graders and Show Dates Graded
3. Reload the page

**Configuration**
 - OS: Windows
 - Browser edge

**Screenshots**
### Before Reload
![image](https://github.com/Submitty/Submitty/assets/116290832/48bba6e9-06f8-402e-9c7c-251f18ba2469)

### After Reload
![image](https://github.com/Submitty/Submitty/assets/116290832/c54cf0cd-be0a-4c68-a3f7-c0368c8b3425)

**Comment by parisinderain** [comment]
I can work on this
