### ISSUE TITLE
Forum attachment functionality is buggy

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#9794]
**Describe the bug**
When trying to post on the discussion forum, I had to try multiple times before I was able to attach an image to my post.  This problem didn't seem to have a specific cause that I was able to identify, but it could be related to #9788.  I saw various errors in the console during my several attempts.

**Expected behavior**
The attachment upload functionality should work cleanly no matter the current state of the socket server.

**To Reproduce**

Unknown.

**Configuration**
MacOS + Safari 16.3

**Comment by Kaarti22** [comment]
I wanted to work on this issue @williamjallen . Please assign this issue to me. I want to start contributing as a newcomer.

**Comment by sak-90** [comment]
@williamjallen I would like to work on this issue. If it hasn't been solved (no PR for this issue yet) please assign it to me. Thank you.
