### ISSUE TITLE
Add ability to add attachments when editing discussion forum post

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#9795]
**What problem are you trying to solve with Submitty**
While struggling to add an attachment to my post on the discussion forum (#9794), I discovered that it is impossible to add an attachment to an existing post.  In my opinion, users should be able to do anything via the edit menu that they can do when making a post normally.

**Describe the way you'd like to solve this problem**
Users should be able to add attachments when editing existing posts.

**Comment by dhruvinjs** [comment]
hello I am new here so can I solve this issue but first can you tell me which language I have to use for this issue

**Comment by oskurtt** [comment]
can i take a look a this?

**Comment by nikki-priyaHIT** [comment]
@williamjallen if no one's assigned to this issue I would like to be assigned for this, please assign it to me

**Comment by bmcutler** [comment]
HI @dhruvinjs @nikki-priyaHIT 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
