### ISSUE TITLE
Supress Automatic Wildcard in regrade.sh

### ISSUE THREAD

**Issue by holzbh** [Submitty/Submitty#983]
If there is a gradeable with id "hw06" and an id "hw06_extra", running ./regrade.sh hw06 will feed both folders to the script. While the wildcard is often convenient, in this case it is undesirable for the user and the system.

May be something to hold off on until regrade.py is ironed out, and just address it in the Python version.

**Comment by MasterOdin** [comment]
I think that not autoexpanding to a wildcard is desirable such that if you type "./regrade.py hw06" you only look at hw06, while if you want both hw06 and hw06_extra you'd type "./regrade.py hw06*".

Explicit is better than implicit.

**Comment by bmcutler** [comment]
Closed in #990
