### ISSUE TITLE
red REGRADE button despite TA grading being 'complete'

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9846]
**Describe the bug**

On the gradeables page for a specific homework, the REGRADE button is red, and the progress bar is incomplete, suggesting TA grading is incomplete and overdue:

<img width="672" alt="Screenshot 2023-10-04 at 11 08 19 AM" src="https://github.com/Submitty/Submitty/assets/5871417/cb4ac179-7bb8-43a3-820e-a3a6f9b6ced3">

Also, when viewing a specific student, there is an indication that grading is incomplete:
<img width="162" alt="Screenshot 2023-10-04 at 11 24 08 AM" src="https://github.com/Submitty/Submitty/assets/5871417/77238ab2-6011-492d-9b20-3130556252ea">

However on the stats page,

All on time submissions have been graded
<img width="323" alt="Screenshot 2023-10-04 at 11 06 13 AM" src="https://github.com/Submitty/Submitty/assets/5871417/9b4a794c-3f3f-46fa-8508-bdfd7f7d957f">

And there are no unresolved grade inquiries
<img width="369" alt="Screenshot 2023-10-04 at 11 06 22 AM" src="https://github.com/Submitty/Submitty/assets/5871417/6f672ad1-7995-4606-89fb-3565bcefc910">

And the stats filter is not configured to include any corner case 
<img width="439" alt="Screenshot 2023-10-04 at 11 06 39 AM" src="https://github.com/Submitty/Submitty/assets/5871417/9c70b317-c324-4f62-b3de-33e22bf21b2d">

I know we've discussed having all of the ta grading pages using the settings from that stats filter.  What is the status of that implementation?

Also, perhaps this case is red because there are version conflicts?   Maybe we forgot to include that in the stats filter?

**Expected behavior**

If the button is red / progress meter incomplete... it should be clear WHY on the stats page.  

- [ ] add text with "# of version conflicts" to the stats page

- [ ] add "include version conflicts" to the stats filter (maybe this doesn't make sense?)

- [ ] on the gradeables page, make the button color & progress meters use the settings of the ta grading stats filter

- [ ] when on the ta grading page for a specific student, make the progress meter use the settings of the ta grading stats filter

(some of these items may duplicate other issues)

**Comment by Youssef-Chip** [comment]
Also see issue #9559 for more information on which other settings need to be affected by the filter modal.
