### ISSUE TITLE
Manage Student - additional toggle columns options

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9848]
**What problem are you trying to solve with Submitty**
From the Manage Students page the instructor can see many columns of data for the student.

The "Toggle Columns" option allows them to remove some columns from display (it can be overly crowded with columns that aren't necessary useful to some instructors/courses).

Additional data about the user is available by clicking "edit student" (user numeric id, legal first name, legal last name, email, secondary email)

It may be helpful to view that additional data for all students at once (rather than click edit student for each student).  E.g. if a student writes their user numeric id on their exam instead of their username, we could search the manage students page for the matching student row.

**Describe the way you'd like to solve this problem**

- [ ] Add 5 more options to the "toggle columns" selector: (user numeric id, legal first name, legal last name, email, secondary email).  These columns should be off/not visible by default.

- [ ] make the "Download Users" option download the data for all currently visible/selected columns.  Currently it is a fixed format and you can't add additional columns (e.g., pronouns are not exported).

ADDED A NEW ITEM 12/1/23

- [ ] let's allow the order of the columns to be rearranged by the instructor.  A draggable interface to order the options similar to the TA grading rubric marks interface and the rainbow grades syllabus categories and gradeable interface would be nice.

**Comment by sagnik3788** [comment]
can i work on this issue @bmcutler

**Comment by Akshun-01** [comment]
Hey, is someone working on this issue? I can try it if no one's currently working on it.

**Comment by bmcutler** [comment]
Hi @sagnik3788 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
Also join our Slack server to discuss technical questions:
https://submitty.org/index/contact
