### ISSUE TITLE
Write bit unset in vagrant box when making new assignment

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#985]
After creating a new assignment on the vagrant box, users are unable to upload due to a lack of the proper file permissions to create the assignment's submission folder. (error thrown at SubmissionController.php line 123)

To fix, /var/local/submitty/courses/s17/COURSE_NAME/submissions must be made writable.

The startup script should be updated so that this is not an issue.

**Comment by bmcutler** [comment]
specifically it's the group write bit.

**Comment by MasterOdin** [comment]
I think the [create_course.sh](https://github.com/Submitty/Submitty/blob/master/bin/create_course.sh) script is the one that needs to be updated, not the setup script since that's where the bits are set?

**Comment by bmcutler** [comment]
Actually, I misspoke.  It's not the group write bit.  That should stay unset.
It's that the owner of the submissions directory should be hwphp (that's the only user who should have write access to that portion of the tree).
Somehow the owner of submissions is instructor on the vagrant machine.

create_course.sh is correct.  Somehow setup on the vagrant machine is weird.

**Comment by bmcutler** [comment]
@MasterOdin 
Is it how you're creating fake submissions?  Everything should be owned by hwphp.

**Comment by MasterOdin** [comment]
Yeah, I change the ownership of submissions. There was some amount of shotgun chowning to get the demo assignments to work. 

Need to fix these three lines to have proper ownership of the directory and the moved around files (which have to be

**Comment by MasterOdin** [comment]
Should be fixed now.
