### ISSUE TITLE
Capitalize folder name under cypress test

### ISSUE THREAD

**Issue by yanliw123** [Submitty/Submitty#9859]
![image](https://github.com/Submitty/Submitty/assets/114595115/03a3143d-63f3-4207-8d4b-5daaeab49a1f), 
notice folder cypress-system is in lowercase while all other folder is in uppercase. Change cypress-system to uppercase

**Comment by abansal15** [comment]
@ZheyuDeng can you please tell how to self assign to a issue ?

**Comment by ZheyuDeng** [comment]
> @ZheyuDeng can you please tell how to self assign to a issue ?

Just simply click setting icon next to assigners
