### ISSUE TITLE
AUTHOR.md file items are not clearly or not properly visible

### ISSUE THREAD

**Issue by abansal15** [Submitty/Submitty#9863]
**What problem are you trying to solve with Submitty**
A clear and concise description of what the problem is.
![image](https://github.com/Submitty/Submitty/assets/120590200/c9f688fa-992c-4272-881c-fe0bf39115db)

in the author.md file the names are just written below each other but since in this ordering does not matter therefore it will be good and will be clearly visible if there is bullets before each name 

**Describe the way you'd like to solve this problem**
i will solve this problem by adding bullet points before each name 
like this 
![image](https://github.com/Submitty/Submitty/assets/120590200/1265244a-5eba-405e-a46c-eae58167f0ce)
![image](https://github.com/Submitty/Submitty/assets/120590200/c7abc171-e566-4e6c-b5e0-aa33294bc4b9)

now the formatiing is pretty good

**Describe any potential alternatives you'd tried to solve the problem**

**Additional context**
@bmcutler please assign this issue to me i am new to open source

**Comment by abansal15** [comment]
@bmcutler please assign this issue to me i am new to open source and would like to contribute

**Comment by abansal15** [comment]
@bmcutler i have raised the pr please review it

**Comment by bmcutler** [comment]
The formatting of this page is sufficient and does not require revision.
