### ISSUE TITLE
submitty.org website looks ugly / is unusable on mobile 

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#987]
Side bar overlaps page content

**Comment by MasterOdin** [comment]
Opened Submitty/submitty.github.io#4 for this issue, and closing this here.

**Comment by bmcutler** [comment]
Moving back (since no one looks at the other issue list).

**Comment by tcyrus** [comment]
It seems to be fixed

**Comment by bmcutler** [comment]
yay!
