### ISSUE TITLE
RCOS link leads to old RCOS site

### ISSUE THREAD

**Issue by DarthNyan** [Submitty/Submitty#9875]
The RCOS links at the bottom of the main site page and the documentation page lead to the old RCOS site, which is abandoned. These should lead to the new RCOS site, new.rcos.io.

**Comment by MasterOdin** [comment]
If the top-level `rcos.io`site is abandoned and no longer updated, why still have it around as the top-level domain, and have this new subdomain? When I google RCOS or "Rensselaer Center of Open Source", my top result is only for stuff on `rcos.io`, but maybe that'll be fixed over time?

**Comment by Ashhar-24** [comment]
Hey @ZheyuDeng @DarthNyan I'm interested in working with this issue.
Can you please assign it to me.

**Comment by Ashhar-24** [comment]
Can you please help me to locate where is the directive that needs to be modified. :)

**Comment by MasterOdin** [comment]
Hi @Ashhar-24, thanks for your interest in continuing to Submitty. At this time, we cannot assign external users to an issue.

Additionally, per the comment in #9881, we are not accepting PRs for this issue until we've resolved the discussion of whether or not this is something we even want to do in the first place.

**Comment by Ashhar-24** [comment]
oh okay.
I had made the changes that was said in the issue. :'(
