### ISSUE TITLE
Can't show all the links available (RCOS)

### ISSUE THREAD

**Issue by jonha1** [Submitty/Submitty#9884]
**Describe the bug**
For RCOS, when a member submits a lot of links, only a portion of them are shown. You can't see the rest of the links available.

**Expected behavior**
You should clearly be able to see all the links.

**To Reproduce**
1. When grading or writing commits in the "Links" section, this happens.

https://github.com/Submitty/Submitty/assets/78988736/d35511b1-4138-4aa7-86db-c49a8910bc47

**Configuration**
 - OS: Windows and Mac
 - Browser: Chrome

**Comment by bmcutler** [comment]
@jonha1 

Thank you for opening an issue to the Submitty project.
However your issue does not contain all the necessary information to allow the team & developers to design a solution.

You reference the use of Submitty for the RCOS class, but the developers are not all familiar with how the RCOS class uses Submitty.  It is necessary better to describe more context of your situation.

It appears you have shown a screenshot from a 'notebook' style gradeable.  The boxes that you type in are flexible and the instructor can configure different size boxes.

I think this is a problem with the configuration of your gradeable, not with the Submitty system.
I encourage you to talk to the course instructor if you have suggestions to improve your experience as a student/grader.
I am closing this issue, but please re-open it with more information if there is something for the Submitty team to improve.
