### ISSUE TITLE
Warning error when an instructor with a team of 1 makes a submission in a team gradeable

### ISSUE THREAD

**Issue by Youssef-Chip** [Submitty/Submitty#9886]
**Describe the bug**
When an instructor makes a team of 1, and makes a submission in a team-gradeable, a warning error appears in the top left corner
**Expected behavior**
No warning error should appear
**To Reproduce**
1. Go to open team homework as an instructor
2. Create a team of 1
3.  Make a submission

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

**Screenshots**
![image](https://github.com/Submitty/Submitty/assets/131885371/43160d83-b0f5-4e13-a679-86ff7edcb13d)

**Additional context**

**Comment by akkshitgupta** [comment]
I would like to fix this issue.

**Comment by xixvtt** [comment]
hi @akkshitgupta  are you still working on this, I'm trying to reproduce this issue on my site but failed, I cannot find where team homework is located, any hints and help?

**Comment by akkshitgupta** [comment]
Hey @xixvtt, I am still stuck in setting it up locally

**Comment by xixvtt** [comment]
> Hey @xixvtt, I am still stuck in setting it up locally. I am not able to find the exact steps to run it locally.

@Youssef-Chip  Hi Youssef, me and @akkshitgupta  both have an issue on reappearing the bug, could you be more specific on how we could find the following steps:

1. Go to open team homework as an instructor
2. Create a team of 1 

personally i couldn't find where to open team homework when login as the instructor.

**Comment by nikki-priyaHIT** [comment]
@Youssef-Chip can you please assign me an issue if available for beginner, I am new here and unable to understand where to start

**Comment by bmcutler** [comment]
Hi @nikki-priyaHIT 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
Also join our Slack server to discuss technical questions:
https://submitty.org/index/contact

**Comment by Youssef-Chip** [comment]
Hello all, I recently tested this bug again and I am unable to reproduce it. I will therefore close the issue.
