### ISSUE TITLE
Pull request titles should start with a capital letter

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#9893]
Many of the pull requests open right now have titles which do not start with a capital letter.  While there may be a handful of cases where starting a title with a lowercase letter is desired, requiring the first letter to be capitalized will result in better consistency, with few real downsides.

The relevant code for this can be found [here](https://github.com/Submitty/action-pr-title).

**Comment by gurjot03** [comment]
please check the pr #9904

**Comment by vikulpbansal** [comment]
Can I pick this up? Please let me know @MasterOdin @williamjallen

**Comment by bmcutler** [comment]
Hi @gurjot03 
Hi @vikulpbansal 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
Also join our Slack server to discuss technical questions:
https://submitty.org/index/contact

**Comment by bmcutler** [comment]
@williamjallen 
I disagree with this being an important or necessary requirement.
It is low priority and we have only gotten incomplete/buggy PRs so I'm going to close it.
