### ISSUE TITLE
Title check action should fail with helpful message

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#9894]
The PR title check action currently prints a message stating that a title is invalid, but does not state what the valid prefixes are.  See [here](https://github.com/Submitty/Submitty/actions/runs/6511276786) for an example.  It would be helpful to have the title check action print a list of the valid options on failure.

**Comment by kacperswis** [comment]
Please check this - https://github.com/Submitty/action-pr-title/pull/8
