### ISSUE TITLE
Remove unnecessary visit statements in Cypress CI

### ISSUE THREAD

**Issue by IDzyre** [Submitty/Submitty#9910]
**What problem are you trying to solve with Submitty**
When #9522 was merged, this made all of the cy.visit('/'); statements before logging in obsolete, as the login function no longer required the UI to be visible, since it is using a post request. 

**Describe the way you'd like to solve this problem**
Remove all of the cy.visit('/'); statements that are directly before a cy.login() statement (or in a beforeEach that happens before logging in during the test), as they are no longer needed, and it just adds unnecessary time/complexity to the tests. 

**Additional context**
NOTE: The cy.visit('/') statement in the logout function is still needed, just none of the ones before the cy.login() statements.

**Comment by Akshun-01** [comment]
Hey, I would like to work on this issue. Can you please assign it to me?

**Comment by bmcutler** [comment]
Hi @Akshun-01 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
Also join our Slack server to discuss technical questions:
https://submitty.org/index/contact

**Comment by Akshun-01** [comment]
Hey @IDzyre , I wanted to clarify do we need to also remove The cy.visit('/') statements such as these? 
1.)
![image](https://github.com/Submitty/Submitty/assets/93793691/13797ee7-e553-49cd-b68e-3329b2320f3e)

2.)
![image](https://github.com/Submitty/Submitty/assets/93793691/e70b76cd-9dfc-49e4-a59f-8bc8ab0e6e72)

- the first one is a visit statement in before each block, and just after that a login statement is there, so I am confused what to do as it is not directly before it.
- in the second one, loginViaUi is used which maybe a login statement. 

So, I would like you to clarify what I need to do in these cases ?

**Comment by IDzyre** [comment]
Those visit statements still run directly before a  login statement, so yes remove those too

**Comment by IDzyre** [comment]
actually, the second one, the visit before the loginViaUI one needs to stay I believe

**Comment by Akshun-01** [comment]
> Those visit statements still run directly before a login statement, so yes remove those too

So, in the first case, after removing the visit statements, the  beforeEach()  would be empty should I also remove it? As it wouldn't be doing anything then.

**Comment by Akshun-01** [comment]
@IDzyre
