### ISSUE TITLE
Calendar Select Multiple Courses note/announcement

### ISSUE THREAD

**Issue by RitaLei123** [Submitty/Submitty#9919]
**What problem are you trying to solve with Submitty**
When the instructors create a note/announcement, they have to select one course at a time so if the note/announcement on the calendar that applies to multiple courses, they will have to post it multiple times for each course.

**Describe the way you'd like to solve this problem**
When creating a note/announcement in calendar, add a feature that allows the instructor to select multiple courses or all their courses to apply the note/announcement on. 

**Describe any potential alternatives you'd tried to solve the problem**
In the drop box, allow the instructor to select more than one course. Additionally, add a select all check box button next the the select course option so when the box is selected, then it will apply to all the courses.

**Additional context**
Perhaps something like this:
<img width="509" alt="image" src="https://github.com/Submitty/Submitty/assets/117528498/6cc10c21-e13a-4dd0-ac0c-a8bd69c2acaf">

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by bmcutler** [comment]
Hi @Sranjan0208 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
Also join our Slack server to discuss technical questions:
https://submitty.org/index/contact

**Comment by bmcutler** [comment]
After some thought, I've decided to close this feature request.
The calendar is a work-in-progress and we need to increase the functionality and feature set for a single course before adding functionality across multiple courses that has limited usefulness.

Most items that would be posted across multiple courses are probably global calendar items.
See also #9974
