### ISSUE TITLE
Informational auto-reply to a New-Submitty-Contributor's first post on Submitty github issue conversation

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9940]
**What problem are you trying to solve with Submitty**

Our "good first issue" labels on Github issues attract attention from prospective developers.  

These new contributors may not be aware of our existing documentation on how to get started (including how to set up a development environment, how to join our online conversations to ask technical questions, and how to make a PR for the first contribution).
https://submitty.org/developer/getting_started/index
https://submitty.org/developer/getting_started/make_a_pull_request

Sometimes these prospective developers make simple initial posts on an issue such as "please assign me to this issue" or "please tell me how to get started" or "tell me what edits to make to what files to close this issue".  Sometimes these messages are directed at specific Submitty developers who may no longer be actively contributing to the project.  Note that our policy is to not assign issues to users who have not yet contributed to our project, but we welcome and review and merge pull requests from new contributors.  

Without more information about the prospective developer our reply to the user is simply to point at this existing documentation since the prospective developer may not have found those resources.  Due to differing time zones and busy developer schedules, sometimes a reply from a Submitty developer is delayed or the message is misplaced and never happens at all.

**Describe the way you'd like to solve this problem**

Let's add a Github action to auto-reply to these posts with links to these introductory resources and encourage the new prospective developer to to ask technical questions in the public forum (not to a specific developer).

Which users / which issue posts should get the auto-reply?  Ideally it would be on the user's first post to any Submitty issue -- can we determine if the Github user is not already part of the Submitty organization and has never posted to any other Submitty issue?

**Comment by bmcutler** [comment]
Here is a draft of the template response
----------------------------------------------------------

Hi   INSERT_MENTION_TO_GITHUB_USERNAME

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
Also join our Slack server to discuss technical questions:
https://submitty.org/index/contact

**Comment by williamjallen** [comment]
You could use markdown to hide the links and reduce the wall of text a bit.  Something like this perhaps:

### Suggested Response:
Hi INSERT_MENTION_TO_GITHUB_USERNAME

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on [how to to get started with Submitty](https://submitty.org/developer/getting_started/index), specifically our pages on [setting up your development environment](https://submitty.org/developer/getting_started/vm_install_using_vagrant) and [making a pull request](https://submitty.org/developer/getting_started/make_a_pull_request).  You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.  We also encourage you to join our [Slack](https://submitty.org/index/contact) server to discuss technical questions.
