### ISSUE TITLE
Markdown regions do not retain size when expanded

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#9949]
**Describe the bug**
The text box for markdown regions on the forum can be expanded, but the box returns to its original size when you enter more text into it.  I did not test other markdown regions to determine whether this is a forum-specific issue.

**Expected behavior**
Text boxes should retain their size when expanded.

**To Reproduce**
1. Expand markdown box on the forum
2. Add some text to the box

**Configuration**
 - OS: macOS 
 - Browser: Safari 16.3

**Screenshots**

https://github.com/Submitty/Submitty/assets/16820599/3ae10d1c-c661-49d4-87cb-bad0d8ade018

**Comment by rajesh604** [comment]
@williamjallen I would like to work on this issue

**Comment by nikhilniky** [comment]
Assign it to i will work

**Comment by bmcutler** [comment]
Hi @rajesh604 
Hi @nikhilniky 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!  
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
Also join our Slack server to discuss technical questions:
https://submitty.org/index/contact
