### ISSUE TITLE
Invalid term/course can still call route code

### ISSUE THREAD

**Issue by cjreed121** [Submitty/Submitty#9950]
**Describe the bug**
When an invalid term/course is entered in the route, it's still possible for some of the route code to be executed. The course DB will be null in this case and cause null errors when it is used.

**Expected behavior**
The page load should just redirect to `/home` if there is an invalid term/course combo.

This will need an edit of some WebRouter/Core code.

**Comment by shivam969619** [comment]
can i take this issue?

**Comment by Shineri** [comment]
Can you please assign this issue to me?

**Comment by bmcutler** [comment]
@shivam969619 
@Shineri 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
Also join our Slack server to discuss technical questions:
https://submitty.org/index/contact

**Comment by ZheyuDeng** [comment]
Closed issue #9950 as PR #9983 is merged.
