### ISSUE TITLE
Add specific error messages to accessibility.spec.js

### ISSUE THREAD

**Issue by taorif25** [Submitty/Submitty#9977]
**What problem are you trying to solve with Submitty**
Currently, accessibility.spec.js creates a temporary html file for every webpage and runs v.NU on each temporary html to find errors. However, when an error is found, no specific error messages are given to the user from v.NU. This makes debugging difficult as you have to run all of the cypress test's commands locally to get specific error messages.

**Describe the way you'd like to solve this problem**
If error messages are found, accessibility.spec.js should display them to the user, making debugging easier.

**Additional context**
Current error message when failing test:
![image](https://github.com/Submitty/Submitty/assets/143554378/ece776b1-cf70-470a-bcdd-72e9a7d34aa0)

**Comment by narasimha-1511** [comment]
I want to work on this issue .?

**Comment by bmcutler** [comment]
Hi @narasimha-1511 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
