### ISSUE TITLE
TA grading (teams?) bug - Viewing pdf from earlier submission is broken

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9984]
**Describe the bug**
A team gradeable.
A team has made 2 submissions.  Each one contains a pdf.
The 2nd version is the active version.
I would like to view the pdf from the first submission (to compare and see what they have changed).

When I click on the pdf, it opens the pdf viewer, but it's empty and I get this error:
<img width="629" alt="Screenshot 2023-11-13 at 9 17 56 PM" src="https://github.com/Submitty/Submitty/assets/5871417/98f715f1-5f59-4e7a-8fa5-22e38765c637">

I don't know if the team part is relevant.  I can view other files within the submission.  It seems that the problem is with the pdf viewer.

**Comment by aditramdas** [comment]
Hey, is someone working on this? If not, I would love to work on this

**Comment by pankuz1** [comment]
@aditramdas are you working on this??

**Comment by bmcutler** [comment]
Hi @aditramdas  @pankuz1 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact

**Comment by vikas-chaudhary-2802** [comment]
@bmcutler Hey, Can please give me steps to reproduce ?

**Comment by bmcutler** [comment]
Hi @vikas-chaudhary-2802 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
