### ISSUE TITLE
Rainbow Grades seating assignment with empty files breaks every webpage for a class

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#9987]
**Describe the bug**

Here are the instructions to prepare exam seating assignments for students

https://submitty.org/instructor/course_settings/rainbow_grades/exam_seating
https://submitty.org/instructor/course_settings/rainbow_grades/room_templates

However, if there is an error in the setup and the individual student files are empty..
(that is, these files do not contain the necessary information, but the entire file just contains `null`)

{course_dir}/reports/seating/{gradeable_id}/{user_id}.json

Then unfortunately, when the course settings webpage is pointed to show the seating for that exam,
then all webpages for that course will break with a frog robot when they try to access those files and use variables expected in the files.

Here is an example of the error message:

```
10:44:11 11/14/2023 - FATAL ERROR
TypeError (Code: 0) thrown in /usr/local/submitty/site/app/views/NavigationView.php (Line 147) by:
                if (property_exists($user_seating_details, 'building') && property_exists($user_seating_details, 'room')) {


Message:
property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

Stack Trace:
#0 /usr/local/submitty/site/app/views/NavigationView.php(147): property_exists()
#1 unknown file(unknown line): app\views\NavigationView->showGradeables()
#2 /usr/local/submitty/site/app/libraries/Output.php(247): call_user_func_array()
#3 /usr/local/submitty/site/app/libraries/Output.php(216): app\libraries\Output->renderTemplate()
#4 /usr/local/submitty/site/app/controllers/NavigationController.php(87): app\libraries\Output->renderOutput()
#5 unknown file(unknown line): app\controllers\NavigationController->navigationPage()
#6 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(262): call_user_func_array()
#7 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(240): app\libraries\routers\WebRouter->run()
#8 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()

URL: https://submitty.cs.rpi.edu//courses/TERM/COURSE
```

**Expected behavior**
If the seating json file does exist, or is empty, or is missing some data, the page should have a clear error message indicating a problem with the seating assignment (and directing students to contact their instructor) but should still successfully load the page.

**Comment by dhruvgupta0503** [comment]
I would like to work on this issue

**Comment by Paulie-Aditya** [comment]
why not just replace the null values with say an empty string?
it won't break the code and result will be displayed with some seats empty

**Comment by bmcutler** [comment]
@Paulie-Aditya @dhruvgupta0503 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact
